### ISSUE TITLE
（已用技术方式处理）如报错 429 Too Many Requests ，可多次运行脚本直至成功。

### ISSUE THREAD

**Issue by fscarmen** [fscarmen/warp#1]
### 再次运行，因为所有的依赖工具都已经更新下载完，所以会比第一次快得多。

![wgcf_429.png](https://i.loli.net/2021/03/20/AfIKekngQ8bzl97.png)

**Comment by fscarmen** [comment]
因为公网IPv6的，两端要加 [ ]，比如 [2a02:180:6:1::2361]:5678 这样。

**Comment by fscarmen** [comment]
> 请问大佬 为什么装上后，docker 启动容器后 无法使用ip:端口进入脚本的控制面板

因为公网IPv6的，两端要加 [ ]，比如 [2a02:180:6:1::2361]:5678 这样。

**Comment by fscarmen** [comment]
> 加上后还是无法进入 显示503报错 用wgcf的ip也无法进入

同时你的网络需要支持IPv6，最简单你用德鸡做的代理访问，应该可以了

**Comment by fscarmen** [comment]
用非DiG9的可以，我晚点试试 DiG9的

![23123.png](https://i.loli.net/2021/04/04/827LYGXsoAdyvfK.png)

**Comment by fscarmen** [comment]
是的，我觉得你可以分两步：1、用德鸡A搭个代理使用上，去访问德鸡B搭的项目以确没有问题。2、用cloudflare处理IPv4网络下的访问。
等你好消息。

**Comment by testermania** [comment]
2: wgcf: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500

**Comment by fscarmen** [comment]
> 2: wgcf: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
> 
> precedence ::ffff:0:0/96 100
> https://www.speedtest.net/result/c/99862336-9c22-4de7-889a-7deed7d87371

????
