### ISSUE TITLE
请问双栈服务器如何配置使用ss

### ISSUE THREAD

**Issue by ben-august** [fscarmen/warp#10]
配置好wgcf后，能正常使用xray。但是ss却无法使用，请问ss配置文件是需要更改吗？

**Comment by fscarmen** [comment]
那个新增的warp IP是公共的，只能用于VPS通过WARP网络接口访问外部的，不能用于本地与VPS之间连接。
你指的SS无法使用具体是如何呢？主机那里不能填 WARP 给到的IP了

**Comment by ben-august** [comment]
![WechatIMG133](https://user-images.githubusercontent.com/36500518/134596367-a051f37b-803d-4697-b84a-2aff307f4d01.jpeg)
![WechatIMG134](https://user-images.githubusercontent.com/36500518/134596373-3b75652a-40c3-4e60-80f4-e03f486f6ef2.jpeg)

**Comment by fscarmen** [comment]
据我了解，ss 协议属于直连的。即是你本地的网络要与VPS的网络相对应才行，这个warp帮不上忙
我试了一下，在甲骨文 ipv6 only 的先装了warp，再搭建的 ss 。SS客户端主机处填入 IPv6 的信息
在本地宽带只有ipv4的情况下连不上，然后用手机发热点共享给PC就可以连上了
同时，通过 ip.gs 查访问网站的IP，发现变为 warp的那个IP了

![image.png](https://i.loli.net/2021/09/24/ud6DhoyOEJUsAFK.png)
![image.png](https://i.loli.net/2021/09/24/G5xo3IQa469fwFr.png)
![image.png](https://i.loli.net/2021/09/24/l85qIs7yTKf6NGV.png)

**Comment by fscarmen** [comment]
看 ip a那里好像不太对，你运行脚本后，能正常获取IP吗？即最后提示成功的时候，有显示IP和归属的，正常吗？

**Comment by ben-august** [comment]
能获取ip wgcf显示成功 我用xray连接正常 也能解锁流媒体

**Comment by ben-august** [comment]
我发现wgcf安装成功后，使用ping.pe试我ss的端口发现ping不通。但是wgcf删除就可以ping通，客户端也能正常使用ss。

**Comment by ben-august** [comment]
我服务器只有ipv4地址，使用wgcf另外获取“原生”ipv4，解锁流媒体。所以ss使用的也是ipv4。

**Comment by fscarmen** [comment]
即使安装了 双栈 warp，即 ipv4和v6都是warp的IP。连ss，和在ping.pe里都要用回原来的vps的IP，包括你ssh进vps也是用原来的IP
warp只是改变vps访问外面资源的路径，并不会改变你访问他的路径的
这点我在 GCP IPv4 only 上试了，即使用了双栈，在 ping.pe 里输入 原始的IP和ss端口，显示成功的

**Comment by ben-august** [comment]
ping.pe我输入的是原来的ip

**Comment by ben-august** [comment]
大佬能留个telegram地址吗 这里聊消息不及时

**Comment by ben-august** [comment]
> 即使安装了 双栈 warp，即 ipv4和v6都是warp的IP。连ss，和在ping.pe里都要用回原来的vps的IP，包括你ssh进vps也是用原来的IP
> warp只是改变vps访问外面资源的路径，并不会改变你访问他的路径的
> 这点我在 GCP IPv4 only 上试了，即使用了双栈，在 ping.pe 里输入 原始的IP和ss端口，显示成功的

那ss能连上吗？

**Comment by fscarmen** [comment]
能啊，我用一键脚本 
```bash
wget --no-check-certificate -O shadowsocks-all.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-all.sh && chmod +x shadowsocks-all.sh && ./shadowsocks-all.sh 2>&1 | tee shadowsocks-all.log
```
选 第4项 Shadowsocks-libev，你先不要用Warp( wg-quick down wgcf)，看能连上了，再把Warp打开 (wg-quick up wgcf)，
ss的设置不用变的。反正我是GCP是如此了

**Comment by ben-august** [comment]
> 能啊，我用一键脚本
> 
> ```shell
> wget --no-check-certificate -O shadowsocks-all.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-all.sh && chmod +x shadowsocks-all.sh && ./shadowsocks-all.sh 2>&1 | tee shadowsocks-all.log
> ```
> 
> 选 第4项 Shadowsocks-libev，你先不要用Warp( wg-quick down wgcf)，看能连上了，再把Warp打开 (wg-quick up wgcf)，
> ss的设置不用变的。反正我是GCP是如此了

我测试也可以 是不是和docker有关 或者ss我用的rust版有关

**Comment by fscarmen** [comment]
> > 能啊，我用一键脚本
> > ```shell
> > wget --no-check-certificate -O shadowsocks-all.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-all.sh && chmod +x shadowsocks-all.sh && ./shadowsocks-all.sh 2>&1 | tee shadowsocks-all.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 选 第4项 Shadowsocks-libev，你先不要用Warp( wg-quick down wgcf)，看能连上了，再把Warp打开 (wg-quick up wgcf)，
> > ss的设置不用变的。反正我是GCP是如此了
> 
> 我测试也可以 是不是和docker有关 或者ss我用的rust版有关

我觉得与docker 无关的，你可以这样测试关了docker ```docker stop $(docker ps -aq)``` 试
可能是ss-rust有关，这块我就不太了解了。我觉得如果 Shadowsocks-libev 你试过可以，就换用这个行了吧

**Comment by ben-august** [comment]
> > > 能啊，我用一键脚本
> > > ```shell
> > > wget --no-check-certificate -O shadowsocks-all.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-all.sh && chmod +x shadowsocks-all.sh && ./shadowsocks-all.sh 2>&1 | tee shadowsocks-all.log
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 选 第4项 Shadowsocks-libev，你先不要用Warp( wg-quick down wgcf)，看能连上了，再把Warp打开 (wg-quick up wgcf)，
> > > ss的设置不用变的。反正我是GCP是如此了
> > 
> > 
> > 我测试也可以 是不是和docker有关 或者ss我用的rust版有关
> 
> 与docker 无关，你可以这样测试关了docker `docker stop $(docker ps -aq)` 试
> 可能是ss-rust有关，这块我就不太了解了。我觉得如果 Shadowsocks-libev 你试过可以，就换用这个行了吧

嗯嗯 谢谢啦 可以close了
