### ISSUE TITLE
wgcf Endpoint 建议改 162.159.193.10:2408 比较多奈飞ip-【结论：2022年2月25日，ipv4 Endponit 更换为可能更好的 162.159.193.10 】

### ISSUE THREAD

**Issue by WXR2727** [fscarmen/warp#101]
[Interface]
PrivateKey = KDQVUdVNPyrK740iOszwfTrcoYGEdCiVFFmN9u4Lvlg=
Address = 172.16.0.2/32
Address = fd01:5ca1:ab1e:8c5b:961:1608:b241:b786/128
DNS = 8.8.8.8,8.8.4.4
MTU = 1420

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = 162.159.193.10:2408

或者

[Interface]
PrivateKey = KDQVUdVNPyrK740iOszwfTrcoYGEdCiVFFmN9u4Lvlg=
Address = 172.16.0.2/32
Address = fd01:5ca1:ab1e:8c5b:961:1608:b241:b786/128
DNS = 8.8.8.8,8.8.4.4
MTU = 1420

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = 162.159.193.7:2408

别用162.159.192.1:2408

谢谢

**Comment by fscarmen** [comment]
#83 这里有些列表如下，好像没有包括你提到的，162.159.193.10 和 162.159.193.7 ，我马上试试

### Personal & WARP
| 162.159.192.0 | [2606:4700:d0::a29f:c000] |
| :---: | :---: |
| 162.159.192.1:2408 | [2606:4700:d0::a29f:c001]:2408
| 162.159.192.2:2408 | [2606:4700:d0::a29f:c002]:2408
| 162.159.192.3:2408 | [2606:4700:d0::a29f:c003]:2408
| 162.159.192.4:2408 | [2606:4700:d0::a29f:c004]:2408
| 162.159.192.5:2408 | [2606:4700:d0::a29f:c005]:2408
| 162.159.192.6:2408 | [2606:4700:d0::a29f:c006]:2408
| 162.159.192.7:2408 | [2606:4700:d0::a29f:c007]:2408
| 162.159.192.8:2408 | [2606:4700:d0::a29f:c008]:2408
| 162.159.192.9:2408 | [2606:4700:d0::a29f:c009]:2408

### Teams & WARP+
| 162.159.193.0 | [2606:4700:d0::a29f:c100] |
| :---: | :---: |
| 162.159.193.1:2408 | [2606:4700:d0::a29f:c101]:2408
| 162.159.193.2:2408 | [2606:4700:d0::a29f:c102]:2408
| 162.159.193.3:2408 | [2606:4700:d0::a29f:c103]:2408
| 162.159.193.4:2408 | [2606:4700:d0::a29f:c104]:2408
| 162.159.193.5:2408 | [2606:4700:d0::a29f:c105]:2408
| 162.159.193.6:2408 | [2606:4700:d0::a29f:c106]:2408
| 162.159.193.7:2408 | [2606:4700:d0::a29f:c107]:2408
| 162.159.193.8:2408 | [2606:4700:d0::a29f:c108]:2408
| 162.159.193.9:2408 | [2606:4700:d0::a29f:c109]:2408

**Comment by WXR2727** [comment]
162.159.193.10 很多奈飞ip

**Comment by fscarmen** [comment]
我用甲骨文东京的来试，三个 IP 获取的都是  8.37.43.* ，一样都不解锁哦

**Comment by WXR2727** [comment]
我用的新加坡鸡 ，如 谷歌云  DigitalOcean 甲骨文 都行

**Comment by WXR2727** [comment]
如果用162.159.193.10 , 大多的IP都是 icloud private relay .

**Comment by fscarmen** [comment]
> 如果用162.159.193.10 , 大多的IP都是 icloud private relay .

这个如何测的？同时我去试试甲骨文新加坡先

**Comment by WXR2727** [comment]
Speedtest 会检测出来 是ICloud Private Relay 还是 Cloudflare .

**Comment by WXR2727** [comment]
Warp 不会隐藏真实ip所以google my ip 检测不了， 得去Speedtest。

**Comment by fscarmen** [comment]
我这里没有什么效果哦，第1个是新加坡的，第2个是东京的
 
![image](https://user-images.githubusercontent.com/62703343/155717977-3ccbe294-6b2e-4079-9438-46ca3af3f4ce.png)

![image](https://user-images.githubusercontent.com/62703343/155718165-659f5daf-11e4-46fa-a819-c2546fb1e42a.png)

**Comment by fscarmen** [comment]
2022年2月25日，ipv4 Endponit 更换为可能更好的 162.159.193.10
感谢你的支持和建议，希望你会有个好的用户体验。

**Comment by WXR2727** [comment]
好的 谢谢大佬 永远支持您的脚本 👍🏻

**Comment by fscarmen** [comment]
> 好的 谢谢大佬 永远支持您的脚本 👍🏻

可以支持另一个 Netflix 解锁脚本: https://github.com/fscarmen/warp_unlock
现支持5种解锁方式，总有一样适合你！

**Comment by eve2ptp** [comment]
> #83 这里有些列表如下，好像没有包括你提到的，162.159.193.10 和 162.159.193.7 ，我马上试试
> 
> ### Personal & WARP
> 162.159.192.0	[2606:4700:d0::a29f:c000]
> 162.159.192.1:2408	[2606:4700:d0::a29f:c001]:2408
> 162.159.192.2:2408	[2606:4700:d0::a29f:c002]:2408
> 162.159.192.3:2408	[2606:4700:d0::a29f:c003]:2408
> 162.159.192.4:2408	[2606:4700:d0::a29f:c004]:2408
> 162.159.192.5:2408	[2606:4700:d0::a29f:c005]:2408
> 162.159.192.6:2408	[2606:4700:d0::a29f:c006]:2408
> 162.159.192.7:2408	[2606:4700:d0::a29f:c007]:2408
> 162.159.192.8:2408	[2606:4700:d0::a29f:c008]:2408
> 162.159.192.9:2408	[2606:4700:d0::a29f:c009]:2408
> ### Teams & WARP+
> 162.159.193.0	[2606:4700:d0::a29f:c100]
> 162.159.193.1:2408	[2606:4700:d0::a29f:c101]:2408
> 162.159.193.2:2408	[2606:4700:d0::a29f:c102]:2408
> 162.159.193.3:2408	[2606:4700:d0::a29f:c103]:2408
> 162.159.193.4:2408	[2606:4700:d0::a29f:c104]:2408
> 162.159.193.5:2408	[2606:4700:d0::a29f:c105]:2408
> 162.159.193.6:2408	[2606:4700:d0::a29f:c106]:2408
> 162.159.193.7:2408	[2606:4700:d0::a29f:c107]:2408
> 162.159.193.8:2408	[2606:4700:d0::a29f:c108]:2408
> 162.159.193.9:2408	[2606:4700:d0::a29f:c109]:2408

这些endpoint结果是不是都是提供一个就近入口（我这边192完全连不上），而且193、195怎么换都是104.28。
实测还有下面这些IP，但104.28结果不变。
![image](https://user-images.githubusercontent.com/42791572/224889061-e340f4a0-8555-42c5-ad0c-52739842cb6e.png)

**Comment by fscarmen** [comment]
> > #83 这里有些列表如下，好像没有包括你提到的，162.159.193.10 和 162.159.193.7 ，我马上试试
> > ### Personal & WARP
> > 162.159.192.0	[2606:4700:d0::a29f:c000]
> > 162.159.192.1:2408	[2606:4700:d0::a29f:c001]:2408
> > 162.159.192.2:2408	[2606:4700:d0::a29f:c002]:2408
> > 162.159.192.3:2408	[2606:4700:d0::a29f:c003]:2408
> > 162.159.192.4:2408	[2606:4700:d0::a29f:c004]:2408
> > 162.159.192.5:2408	[2606:4700:d0::a29f:c005]:2408
> > 162.159.192.6:2408	[2606:4700:d0::a29f:c006]:2408
> > 162.159.192.7:2408	[2606:4700:d0::a29f:c007]:2408
> > 162.159.192.8:2408	[2606:4700:d0::a29f:c008]:2408
> > 162.159.192.9:2408	[2606:4700:d0::a29f:c009]:2408
> > ### Teams & WARP+
> > 162.159.193.0	[2606:4700:d0::a29f:c100]
> > 162.159.193.1:2408	[2606:4700:d0::a29f:c101]:2408
> > 162.159.193.2:2408	[2606:4700:d0::a29f:c102]:2408
> > 162.159.193.3:2408	[2606:4700:d0::a29f:c103]:2408
> > 162.159.193.4:2408	[2606:4700:d0::a29f:c104]:2408
> > 162.159.193.5:2408	[2606:4700:d0::a29f:c105]:2408
> > 162.159.193.6:2408	[2606:4700:d0::a29f:c106]:2408
> > 162.159.193.7:2408	[2606:4700:d0::a29f:c107]:2408
> > 162.159.193.8:2408	[2606:4700:d0::a29f:c108]:2408
> > 162.159.193.9:2408	[2606:4700:d0::a29f:c109]:2408
> 
> 这些endpoint结果是不是都是提供一个就近入口（我这边192完全连不上），而且193、195怎么换都是104.28。 实测还有下面这些IP，但104.28结果不变。 ![image](https://user-images.githubusercontent.com/42791572/224889061-e340f4a0-8555-42c5-ad0c-52739842cb6e.png)

2023.3.14 warp-go V1.1.2 / menu.sh 2.48

To speed up WARP, automatically find the most suitable endpoint for local use and apply it to wgcf, warp-go and client. Thanks to an anonymous and enthusiastic user for the tool;

为了提速 WARP，自动寻找最适合本机使用的 endpoint，应用在 wgcf, warp-go 和 client，感谢匿名的热心网友提供的工具

https://github.com/fscarmen/warp
