### ISSUE TITLE
可否增加开关，自行选择根据ipv4或ipv6的地址获取warp的IP-【结论：2022年2月28日，双栈VPS的 Endpoint 从原来的 engage.cloudflareclient.com 改为 162.159.193.10，有加速buff】

### ISSUE THREAD

**Issue by Ivan-ggg** [fscarmen/warp#102]
甲骨文的机器，ipv4地址识别为韩国，ipv6地址识别为美国。同时打开ipv4，v6，warp会连接美国机房，导致延迟很大。如果关闭ipv6，通过ipv4连接warp，则可以连上韩国机房。可否自己选择根据v4或v6地址连接？

**Comment by Ivan-ggg** [comment]
测试了一下，新开的机器，全新安装warp，只启用ipv4网络接口，还是接到美国机房了。
只有把原生ipv6删除才能接到当地机房。
![image](https://raw.githubusercontent.com/Ivan-ggg/pic/main/warp.PNG)

**Comment by fscarmen** [comment]
你试试 ```vi /etc/wireguard/wgcf.conf```，按图显示的把 -6 的两行注释掉
![image](https://user-images.githubusercontent.com/62703343/155952389-f3f55fd2-629e-4bc1-98b7-c9d956dd186f.png)
```warp o ; warp o``` 看看

**Comment by Ivan-ggg** [comment]
试了，不行，还是接到美国去了

**Comment by fscarmen** [comment]
把最下面的 engage.cloudflareclient.com 改为 162.159.192.1 再看看，即 
Endpoint = 162.159.193.10:2408

**Comment by Ivan-ggg** [comment]
搞定，接到韩国机房了，谢谢！

**Comment by fscarmen** [comment]
不客气，感谢你支持并使用本项目，并反馈有价值的意见，今晚我更新一下，对于双栈的vps，指定 Endpoint 来接较近的机房。

**Comment by fscarmen** [comment]
> 搞定，接到韩国机房了，谢谢！

麻烦你试试，把 PostUp -6 那两条的注释去掉，只改 Endpoint 是否可以呢？

**Comment by Ivan-ggg** [comment]
经测试，只和Endpoint 有关，当Endpoint 为域名时，就连到美国了，当Endpoint 为162.159.193.10时，就连到了韩国

**Comment by fscarmen** [comment]
我试到个很有趣的和你分享一下，我是一台193.122.**.**的首尔甲骨文，如果用最原始的 Endpoint  IPv4 162.159.192.1 ，分出来是日本的，如果换作 162.159.193.10 的，分出来的则是香港的。之前有位用户说后者有buff。
你方便也试试用162.159.192.1这个看分到哪里的

**Comment by fscarmen** [comment]
好像也能换到韩国的

![image](https://user-images.githubusercontent.com/62703343/155977195-c01186d4-df2d-4437-bdc9-a6b5f3692740.png)

**Comment by Ivan-ggg** [comment]
我测试了，162.159.193.10连接韩国，162.159.192.1连接美国，192.159.193.1-9我随即选了三四个ip，都是连韩国的，192.159.192.1-9我随即选了三四个ip，都是连美国的

**Comment by fscarmen** [comment]
> 我测试了，162.159.193.10连接韩国，162.159.192.1连接美国，192.159.193.1-9我随即选了三四个ip，都是连韩国的，192.159.192.1-9我随即选了三四个ip，都是连美国的

看结论是 193 要优于 192，我已经改了脚本了，下次你运行就是193那段了。已经安装的只能手动改改，幸好脚本有快捷方式 ```warp o```

**Comment by ben-august** [comment]
> 我试到个很有趣的和你分享一下，我是一台193.122.**.**的首尔甲骨文，如果用最原始的 Endpoint IPv4 162.159.192.1 ，分出来是日本的，如果换作 162.159.193.10 的，分出来的则是香港的。之前有位用户说后者有buff。#101 你方便也试试用162.159.192.1这个看分到哪里的 ![image](https://user-images.githubusercontent.com/62703343/155976951-4958268c-93ef-49cd-a2cd-6590baaf7144.png)

意思是可以通过更改endpoint的方式刷到不同国家的warp ip？

**Comment by testermania** [comment]
warp not getting ip. today

Maximum 5 attempts to get WARP IP...
Try 1

stuck

**Comment by fscarmen** [comment]
> warp not getting ip. today
> 
> Maximum 5 attempts to get WARP IP... Try 1
> 
> stuck

Not only you but all of us . It must be some wrong with CloudFlare WARP.
