### ISSUE TITLE
Error: Unable to find a match: resolvconf-【结论：iptabels 方案在CentOS 还没有适配，不能工作，建议换到 Debian 或者 Ubuntu 系统，后续有时间会跟进完善，谢谢！】

### ISSUE THREAD

**Issue by vincentwenzj** [fscarmen/warp#104]
甲骨文ARM， Oracle Linux 8.5，自动安装iptables+dnsmasq+ipset。

进度 3/3：寻找 MTU 最优值已完成
 
Copr repo for wireguard owned by jdoss                                                                                              2.0 kB/s | 3.3 kB     00:01    
Package wireguard-dkms-1:1.0.20211208-1.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:00:03 ago on Fri 04 Mar 2022 05:33:40 PM CST.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:00:06 ago on Fri 04 Mar 2022 05:33:40 PM CST.
Package ipset-7.1-1.el8.aarch64 is already installed.
Package dnsmasq-2.79-19.el8.aarch64 is already installed.
No match for argument: resolvconf
Package mtr-2:0.92-3.el8.aarch64 is already installed.
Error: Unable to find a match: resolvconf
 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
我之前试过 CentOS stream 8，好像也是这个报错，你可以换 Ubuntu 20.04 系统，那个我试过可以的。
