### ISSUE TITLE
warp刷国内ip-【结论：大陆 VPS 也有可能连接 WARP 服务】

### ISSUE THREAD

**Issue by xiaoxiaofeixf** [fscarmen/warp#106]
https://github.com/fscarmen/warp/issues/72尝试原来的这个方法但是更新为debian11+5.15.25-bbrplus

还是刷不了ip

**Comment by fscarmen** [comment]
microsoft虚拟化没关系，有很大可能是 warp 还没恢复的地区，已知有香港和多伦多

**Comment by xiaoxiaofeixf** [comment]
> microsoft虚拟化没关系，有很大可能是 warp 还没恢复的地区，已知有香港和多伦多

谢谢作者回复，确实是香港机
还有一个问题刚刚看那个原来的接口换了，用国内机试了一下果然可以刷了，于是刷了个ipv6但是是美国的ip，问一下有没有办法分流就是国外的网站用刷的ipv6访问

**Comment by fscarmen** [comment]
> > microsoft虚拟化没关系，有很大可能是 warp 还没恢复的地区，已知有香港和多伦多
> 
> 谢谢作者回复，确实是香港机 还有一个问题刚刚看那个原来的接口换了，用国内机试了一下果然可以刷了，于是刷了个ipv6但是是美国的ip，问一下有没有办法分流就是国外的网站用刷的ipv6访问

这种分流不太适合做在v2ray/xray配置文件里，比较好的做法是在客户端，如 pc 和 安卓的 clash ，IPhone 用 QX 和 loon 之类

**Comment by xiaoxiaofeixf** [comment]
> > > microsoft虚拟化没关系，有很大可能是 warp 还没恢复的地区，已知有香港和多伦多
> > 
> > 
> > 谢谢作者回复，确实是香港机 还有一个问题刚刚看那个原来的接口换了，用国内机试了一下果然可以刷了，于是刷了个ipv6但是是美国的ip，问一下有没有办法分流就是国外的网站用刷的ipv6访问
> 
> 这种分流不太适合做在v2ray/xray配置文件里，比较好的做法是在客户端，如 pc 和 安卓的 clash ，IPhone 用 QX 和 loon 之类

那是否可以刷一个warp ipv4，然后国内网站用国内机原有ip访问，然后国外的用warp访问

**Comment by fscarmen** [comment]
> > > > microsoft虚拟化没关系，有很大可能是 warp 还没恢复的地区，已知有香港和多伦多
> > > 
> > > 
> > > 谢谢作者回复，确实是香港机 还有一个问题刚刚看那个原来的接口换了，用国内机试了一下果然可以刷了，于是刷了个ipv6但是是美国的ip，问一下有没有办法分流就是国外的网站用刷的ipv6访问
> > 
> > 
> > 这种分流不太适合做在v2ray/xray配置文件里，比较好的做法是在客户端，如 pc 和 安卓的 clash ，IPhone 用 QX 和 loon 之类
> 
> 那是否可以刷一个warp ipv4，然后国内网站用国内机原有ip访问，然后国外的用warp访问

v2ray/xray的配置文件我没有研究太深，实际使用中我也是用上述的软件分流，国内流量不走代理用直连

**Comment by xiaoxiaofeixf** [comment]
> > > > > microsoft虚拟化没关系，有很大可能是 warp 还没恢复的地区，已知有香港和多伦多
> > > > 
> > > > 
> > > > 谢谢作者回复，确实是香港机 还有一个问题刚刚看那个原来的接口换了，用国内机试了一下果然可以刷了，于是刷了个ipv6但是是美国的ip，问一下有没有办法分流就是国外的网站用刷的ipv6访问
> > > 
> > > 
> > > 这种分流不太适合做在v2ray/xray配置文件里，比较好的做法是在客户端，如 pc 和 安卓的 clash ，IPhone 用 QX 和 loon 之类
> > 
> > 
> > 那是否可以刷一个warp ipv4，然后国内网站用国内机原有ip访问，然后国外的用warp访问
> 
> v2ray/xray的配置文件我没有研究太深，实际使用中我也是用上述的软件分流，国内流量不走代理用直连

warp是否可以刷到国内的ip呢？我看warp服务器有国内的点

**Comment by fscarmen** [comment]
> 
> warp是否可以刷到国内的ip呢？我看warp服务器有国内的点

没有遇到过，第1我没有国内的鸡试，第2我看用户反馈阿里和腾讯的鸡根本连都连不通 warp，更不要服务了。

**Comment by xiaoxiaofeixf** [comment]
> > warp是否可以刷到国内的ip呢？我看warp服务器有国内的点
> 
> 没有遇到过，第1我没有国内的鸡试，第2我看用户反馈阿里和腾讯的鸡根本连都连不通 warp，更不要服务了。
https://github.com/fscarmen/warp/issues/102
由于这个你把原来的那个替换之后，国内机就可以刷warp了

**Comment by fscarmen** [comment]
> > > warp是否可以刷到国内的ip呢？我看warp服务器有国内的点
> > 
> > 
> > 没有遇到过，第1我没有国内的鸡试，第2我看用户反馈阿里和腾讯的鸡根本连都连不通 warp，更不要服务了。
> > #102
> > 由于这个你把原来的那个替换之后，国内机就可以刷warp了

你算是很走运啊，哈哈，我看用户反馈大陆鸡无论如何换 Endpoint 都连不通

**Comment by xiaoxiaofeixf** [comment]
> > > > warp是否可以刷到国内的ip呢？我看warp服务器有国内的点
> > > 
> > > 
> > > 没有遇到过，第1我没有国内的鸡试，第2我看用户反馈阿里和腾讯的鸡根本连都连不通 warp，更不要服务了。
> > > #102
> > > 由于这个你把原来的那个替换之后，国内机就可以刷warp了
> 
> 你算是很走运啊，哈哈，我看用户反馈大陆鸡无论如何换 Endpoint 都连不通

啊这，我以为刷换了那个刷的链接就可以了

**Comment by xiaoxiaofeixf** [comment]
> > > > warp是否可以刷到国内的ip呢？我看warp服务器有国内的点
> > > 
> > > 
> > > 没有遇到过，第1我没有国内的鸡试，第2我看用户反馈阿里和腾讯的鸡根本连都连不通 warp，更不要服务了。
> > > #102
> > > 由于这个你把原来的那个替换之后，国内机就可以刷warp了
> 
> 你算是很走运啊，哈哈，我看用户反馈大陆鸡无论如何换 Endpoint 都连不通

刚刚试了下原来的engage.cloudflareclient.comping不通，但是新的162.159.193.10可以ping通意味着国内可以刷ip了

**Comment by fscarmen** [comment]
> 
> 刚刚试了下原来的engage.cloudflareclient.comping不通，但是新的162.159.193.10可以ping通意味着国内可以刷ip了

靠你反馈结果：）刷到哪里的？

**Comment by xiaoxiaofeixf** [comment]
> > 刚刚试了下原来的engage.cloudflareclient.comping不通，但是新的162.159.193.10可以ping通意味着国内可以刷ip了
> 
> 等你反馈结果：）刷到哪里的？

刷的都是美国的
![捕获](https://user-images.githubusercontent.com/95118427/157884588-5b602e82-04d1-4dbe-a1ff-742152bfb630.PNG)

**Comment by fscarmen** [comment]
> > > 刚刚试了下原来的engage.cloudflareclient.comping不通，但是新的162.159.193.10可以ping通意味着国内可以刷ip了
> > 
> > 
> > 等你反馈结果：）刷到哪里的？
> 
> 刷的都是美国的 ![捕获](https://user-images.githubusercontent.com/95118427/157884662-fd44ee56-8968-4cfd-8c86-3ed84a018beb.PNG)

中美一家亲嘛：）哈哈

**Comment by xiaoxiaofeixf** [comment]
> > > > 刚刚试了下原来的engage.cloudflareclient.comping不通，但是新的162.159.193.10可以ping通意味着国内可以刷ip了
> > > 
> > > 
> > > 等你反馈结果：）刷到哪里的？
> > 
> > 
> > 刷的都是美国的 ![捕获](https://user-images.githubusercontent.com/95118427/157884662-fd44ee56-8968-4cfd-8c86-3ed84a018beb.PNG)
> 
> 中美一家亲嘛：）哈哈

所以现在理论上是可以刷了，那么就是能不能刷国内那几个节点的问题

**Comment by fscarmen** [comment]
> > 
> > 
> > 中美一家亲嘛：）哈哈
> 
> 所以现在理论上是可以刷了，那么就是能不能刷国内那几个节点的问题

高手啊，连了WARP能科学吗？

**Comment by xiaoxiaofeixf** [comment]
> > > 中美一家亲嘛：）哈哈
> > 
> > 
> > 所以现在理论上是可以刷了，那么就是能不能刷国内那几个节点的问题
> 
> 高手啊，连了WARP能科学吗？

ipv6因为使用warp可以科学，我就刷了个ipv6
