### ISSUE TITLE
digitalocean新加坡节点用了warp后延迟就会特别高，访问网站都会超时-【结论：我用甲骨文觉得还可以，油管有6万。不同厂家线路，不同运营商，不同地区存在巨大差异，以用户实际场景数据为主】

### ISSUE THREAD

**Issue by wangsicheng0710** [fscarmen/warp#108]
digitalocean新加坡节点用了warp后延迟就会特别高，访问网站都会超时

**Comment by fscarmen** [comment]
新加坡有时候会获取的美国的 WARP IP，你留意一下，是新加坡的才使用，不是的话就运行两次  ```warp o```来更换试试

**Comment by wangsicheng0710** [comment]
我的意思是开了warp接口就会很卡，刷到的也是新加坡ip，但是开了接口就会在开网页的时候超时

**Comment by fscarmen** [comment]
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/62703343/158017150-718c1808-54c7-463a-a5a8-72bb3180f636.png">

<img width="473" alt="image" src="https://user-images.githubusercontent.com/62703343/158017164-cab49701-410d-48c4-8b8d-7c42e5c73771.png">

**Comment by wangsicheng0710** [comment]
我这个不开warp还能开网页，但是开了warp就会超时是啥问题

**Comment by fscarmen** [comment]
我是用 VLESS+WS+优选CDN 的，使用如上，感觉还好，不太确认你那里的问题

**Comment by josephzjw** [comment]
@fscarmen 我看其他issue上有提到亚太地区刷不出解锁的ip，你这个oracle的新加坡节点也是不解锁netflix的是吗？

**Comment by fscarmen** [comment]
> @fscarmen 我看其他issue上有提到亚太地区刷不出解锁的ip，你这个oracle的新加坡节点也是不解锁netflix的是吗？

要试试才知道，昨晚只看了速度，对我来说可以（我要求不高，所以可以的定义是油管稳定2.5万+）

致于刷Netflix，下午回去试试才行

**Comment by fscarmen** [comment]
> @fscarmen 我看其他issue上有提到亚太地区刷不出解锁的ip，你这个oracle的新加坡节点也是不解锁netflix的是吗？

下午刷了下新加坡的，刷不出来。

**Comment by wangsicheng0710** [comment]
我的节点链接speed test延时100多毫秒，但是挂了warp之后直接超时，是因为vps有问题吗

**Comment by fscarmen** [comment]
warp的原因吧，我本时都没speedtest，所以对这数据不敏感，印象中数据是很难看的，实际使用效果你在应用中感受下。
我用甲骨文新加坡感觉还可以。

**Comment by jackiehj** [comment]
> 我是用 VLESS+WS+优选CDN 的，使用如上，感觉还好，不太确认你那里的问题

我用的是Vless+Xtls ，会经常断开。奇了怪

**Comment by fscarmen** [comment]
> > 我是用 VLESS+WS+优选CDN 的，使用如上，感觉还好，不太确认你那里的问题
> 
> 我用的是Vless+Xtls ，会经常断开。奇了怪

#103

**Comment by wangsicheng0710** [comment]
我用的是trojan+xtls也是断线

**Comment by fscarmen** [comment]
> 我用的是trojan+xtls也是断线

有使用换解锁 IP 吗？
