### ISSUE TITLE
IPv6 Only VPS 开启 WARP 后 Docker Ubuntu apt update 特别慢-【结论：经实测数据，与宿主机的性能和网络强相关】

### ISSUE THREAD

**Issue by hmsjy2017** [fscarmen/warp#109]
Docker 已开启 IPv6 支持。在未启用 WARP 时，Docker 能正常使用。启用 WARP（IPv6 优先）后，Docker 下 Ubuntu apt update 特别慢，甚至无法使用。
```
root@ff19e6d10065:~# apt update
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  Connection failed [IP: 91.189.88.152 80]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [108 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]                                          
Fetched 222 kB in 1min 1s (3645 B/s)                                                                                  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/InRelease  Connection failed [IP: 91.189.88.152 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@ff19e6d10065:~# apt update
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Waiting for headers]
```

**Comment by fscarmen** [comment]
这个我需要试试才能回复你，你的docker 是 ubuntu20.04？宿主机是 IPv4 only?

**Comment by fscarmen** [comment]
> Docker 已开启 IPv6 支持。在未启用 WARP 时，Docker 能正常使用。启用 WARP（IPv6 优先）后，Docker 下 Ubuntu apt update 特别慢，甚至无法使用。

现在处理得如何了？

**Comment by hmsjy2017** [comment]
@fscarmen 暂时没有完美的解决方案，我现在的方法是关闭 WARP，有需要的时候再开启。

**Comment by fscarmen** [comment]
我想是与宿主鸡关系很大的

**Comment by hmsjy2017** [comment]
@fscarmen 根据 P3TERX 大佬的回复，目前解决此问题可以使用 Host 网络模式或者用 nginx 反代。经测试，此方法有效。
> Docker 应用在 Bridge 网络模式下确实存在这个问题，暂时没有解决方案。你可以使用 Host 网络模式，或者用 nginx 反代。
https://github.com/P3TERX/warp.sh/issues/3#issuecomment-877094178

**下面简述一下具体方法：**
### 配置方法
首先保证已配置 DNS64，Docker  已启用 IPv6 支持，然后开启 WARP IPv4。
运行 docker 容器时，命令加上 `--net=host` 即可使用 Host 网络模式。

**注意：`--net=host` 必须加在镜像名之前，否则不生效。
像 `docker run -it ubuntu --net=host` `这样加在镜像名后就是无效的。**
### 测试命令
宿主机创建一个 Ubuntu 容器并进入：
（可能要加 `sudo`）
```bash
docker run --net=host -it ubuntu
```
然后在容器内执行 `apt update`，发现可以正常更新。
*****
另外，通过此方法在 Docker 中运行 Ubuntu 桌面，VNC 连接容器，
### 测试命令：
运行 `ubuntu-desktop-lxde-vnc` 容器：
（如果是 arm64 系统则在末尾加上 `:arm64`）
```bash
docker run -p 6080:80 -p 5900:5900 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
```
然后通过 VNC 连接容器，打开 Firefox 访问 IPv4 only 网站，发现能正常打开。

**Comment by fscarmen** [comment]
> @fscarmen 根据 P3TERX 大佬的回复，目前解决此问题可以使用 Host 网络模式或者用 nginx 反代。经测试，此方法有效。
> 
> > Docker 应用在 Bridge 网络模式下确实存在这个问题，暂时没有解决方案。你可以使用 Host 网络模式，或者用 nginx 反代。
> 
> https://github.com/P3TERX/warp.sh/issues/3#issuecomment-877094178
> 
> 
> 
> **下面简述一下具体方法：**
> 
> ### 配置方法
> 
> 首先保证已配置 DNS64，Docker  已启用 IPv6 支持，然后开启 WARP IPv4。
> 
> 运行 docker 容器时，命令加上 `--net=host` 即可使用 Host 网络模式。
> 
> 
> 
> **注意：`--net=host` 必须加在镜像名之前，否则不生效。
> 
> 像 `docker run -it ubuntu --net=host` `这样加在镜像名后就是无效的。**
> 
> ### 测试命令
> 
> 宿主机创建一个 Ubuntu 容器并进入：
> 
> （可能要加 `sudo`）
> 
> ```bash
> 
> docker run --net=host -it ubuntu
> 
> ```
> 
> 然后在容器内执行 `apt update`，发现可以正常更新。
> 
> *****
> 
> 另外，通过此方法在 Docker 中运行 Ubuntu 桌面，VNC 连接容器，
> 
> ### 测试命令：
> 
> 运行 `ubuntu-desktop-lxde-vnc` 容器：
> 
> （如果是 arm64 系统则在末尾加上 `:arm64`）
> 
> ```bash
> 
> docker run -p 6080:80 -p 5900:5900 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
> 
> ```
> 
> 然后通过 VNC 连接容器，打开 Firefox 访问 IPv4 only 网站，发现能正常打开。
> 
> 

收到，谢谢你提供方法，我找时间用青龙，哪吒等试试

**Comment by fscarmen** [comment]
试过可行。
改 docker 网络模式从默认的 bridge 为  host，青龙可以正常访问。
我想借用 iptable ，把 docker 用到的 172.17.0.1/16 作分流应该也是可行的。

**Comment by fscarmen** [comment]
刚才试了 iptables 是可以的

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/62703343/162632128-0b129f98-cf6a-44f4-8389-c26cd2893679.png">

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/62703343/162632152-bf93d6e8-8596-4887-8f07-dc1f9f8a3025.png">

**Comment by fscarmen** [comment]
> ```shell
> docker run -p 6080:80 -p 5900:5900 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
> ```

这个我加上 -dit --net=host，其中 -dit 不加，容器建立后一直挂在最后那里不能其他操作， --net=host是为了能在warp下远程访问
```shell
docker run -dit --net=host -p 6080:80 -p 5900:5900 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
```
