### ISSUE TITLE
为什么每次获得都是同一网段的IP，可以获得不同的么？-【结论：不行，IP按就近分配原则，共享并且会变化的】

### ISSUE THREAD

**Issue by matthuo333** [fscarmen/warp#11]
大神 如题 请教

**Comment by fscarmen** [comment]
不行的，首先 CloudFlare 会自动分配与原生 IP 地点相近的节点，人为不可挑选的。其次这些IP是共享的，即可能多个VPS都分配同一个IP。

**Comment by matthuo333** [comment]
嗯嗯，有什么办法知道 一个IP 当前又多少VPS在用呢？

**Comment by fscarmen** [comment]
这个我就不会了。相当于小区共享宽带有多少户接入一样，估计也比较难获取吧。
