### ISSUE TITLE
安装老失败，无法获取warp ip，求教大佬帮忙-【结论：香港 VPS，受3.3事件影响，仍然未能接入 WARP 服务】

### ISSUE THREAD

**Issue by hukejiayi** [fscarmen/warp#112]
<img width="708" alt="微信图片_20220324161245" src="https://user-images.githubusercontent.com/60979448/159871832-36fbebf2-c790-436f-b091-9d9789f350cd.png">

**Comment by fscarmen** [comment]
输入以下两条指令看看，怀疑收获IP时间超时
```
wget -qO- -4T10 ip.gs # 查 IPv4
wget -qO- -6T10 ip.gs # 查 IPv6
```

**Comment by hukejiayi** [comment]
没反应，我每次warp网络接口都是未开启，每次都是尝试5次未成功
<img width="398" alt="11" src="https://user-images.githubusercontent.com/60979448/159873192-b8e20054-7ec2-452c-a340-b175d51a24f8.png">

**Comment by issaceyan** [comment]
自从CF香港出问题，我越南的小鸡都是获取不了的，系统信息都是正常的

**Comment by fscarmen** [comment]
哦哦，应该是与香港的一样了，不提供 WARP 服务了

**Comment by fscarmen** [comment]
> 自从CF香港出问题，我越南的小鸡都是获取不了的，系统信息都是正常的

话说之前你的越南小鸡获取的 WARP IP 显示是哪里的呢？

**Comment by issaceyan** [comment]
> 

那通过切换地区，可以用吗？

**Comment by fscarmen** [comment]
> > 
> 
> 那通过切换地区，可以用吗？

有难度了，因为如果他被视为邻近的香港的话就一直获取不了。如果能分到新加坡还可以。

**Comment by hukejiayi** [comment]
我就是香港的vps

**Comment by fscarmen** [comment]
> 我就是香港的vps

建议跟着我问候 CloudFlare ： MMP

**Comment by majiancy** [comment]
我也是香港腾讯的VPS，一直WARP IP获取失败。怎么解？

**Comment by fscarmen** [comment]
暂时无解

**Comment by fscarmen** [comment]
> 我就是香港的vps

最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局
一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)

**Comment by hbxnlsy123** [comment]
> 

香港vps用warp-go还是五次失败

**Comment by fscarmen** [comment]
> > 
> 
> 香港vps用warp-go还是五次失败

判断不出问题点，回显什么呢？

**Comment by hbxnlsy123** [comment]
> > 香港vps用warp-go还是五次失败
> 
> 判断不出问题点，回显什么呢？

![CD947CB8-CF51-497A-83C9-9C3150A847C4](https://user-images.githubusercontent.com/53092039/186385811-942257da-e009-4fa0-8868-95678f676f2c.jpeg)

**Comment by fscarmen** [comment]
这样看不出来，方便你加我的tg: https://t.me/fscarmen2 ，告诉我ssh进去看看了

**Comment by GreenTeodoro839** [comment]
> 

一样的问题，有解决方案吗？

**Comment by fscarmen** [comment]
> 
> 一样的问题，有解决方案吗？

有了，用warp-go.sh脚本即可解决香港vps的问题，运行详情请看项目主页。

**Comment by GreenTeodoro839** [comment]
> > 一样的问题，有解决方案吗？
> 
> 有了，用warp-go.sh脚本即可解决香港vps的问题，运行详情请看项目主页。

我是说warp-go也不行。系统centos7

**Comment by fscarmen** [comment]
> > > 一样的问题，有解决方案吗？
> > 
> > 
> > 有了，用warp-go.sh脚本即可解决香港vps的问题，运行详情请看项目主页。
> 
> 我是说warp-go也不行。系统centos7

你的机器是原生IPv4单栈的吗？

我刚才用GCP来试，好像 C7 的机制有些不同，可惜试不了香港，你先用 `bash warp-go.sh u` 卸载之前，再运行以下发一下回显 `ip route get 2606:4700:d0::a29f:c001`

**Comment by GreenTeodoro839** [comment]
> > > > 一样的问题，有解决方案吗？
> > > 
> > > 
> > > 有了，用warp-go.sh脚本即可解决香港vps的问题，运行详情请看项目主页。
> > 
> > 
> > 我是说warp-go也不行。系统centos7
> 
> 你的机器是原生IPv4单栈的吗？
> 
> 我刚才用GCP来试，好像 C7 的机制有些不同，可惜试不了香港，你先用 `bash warp-go.sh u` 卸载之前，再运行以下发一下回显 `ip route get 2606:4700:d0::a29f:c001`

发现了一个问题，阿里云原系统能用，使用moeclub的系统镜像或者dd原版系统都不正常，是不是缺依赖？

**Comment by fscarmen** [comment]
warp-go没有什么依赖的哦，就一个iproute2，应该都有的。你用萌咖的 d 成什么系统？

**Comment by GreenTeodoro839** [comment]
> warp-go没有什么依赖的哦，就一个iproute2，应该都有的。你用萌咖的 d 成什么系统？

centos https://api.moetools.net/get/centos-79-image
debian是脚本直接-d参数dd原版debian11

**Comment by fscarmen** [comment]
不太确定是否与阿里有关系，你试试换外国的vps供应商。
