### ISSUE TITLE
找到一个可能的warp-cli s5模式替代品-【结论：2022.3.27 V2.36 通过 wireproxy，让 WARP 在本地建议一个 socks5 代理。感谢 Fangliding 提供资讯】

### ISSUE THREAD

**Issue by Fangliding** [fscarmen/warp#113]
https://github.com/octeep/wireproxy
这个项目可以把wireguard转成一个Socks5代理 搭配wgcf或许可以弄出一个Socks5的warp入口而不使用cli 这样一来可以同时实现方便地在v2ray对流媒体进行分流 和绕开warp-cli崩溃 速度慢各种问题

**Comment by fscarmen** [comment]
谢谢，这就去研究一下

**Comment by fscarmen** [comment]
成功，以下为截图，十分感谢你提供的重要信息，我抽个时间集成到脚本里

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/62703343/160276506-54339ae3-c1cb-4780-ac3f-de11630b1f8e.png">

**Comment by fscarmen** [comment]
2022.3.28 已经集成到主脚本里，V2.36，细节再花点时间完善一下。谢谢兄弟，再有什么好玩的记得告诉我，一起玩。
<img width="922" alt="image" src="https://user-images.githubusercontent.com/62703343/160290041-465a1aa9-5253-4dfe-9abe-dd4e5f116f5b.png">

**Comment by malikshi** [comment]
cool enhancement, using wireproxy instead wireguard. so it's not create new interface right? maybe this one can work along other dockers stufff without worry?

**Comment by fscarmen** [comment]
> cool enhancement, using wireproxy instead wireguard. so it's not create new interface right? maybe this one can work along other dockers stufff without worry?

Yes. You got that right. It 's a whitelist.

**Comment by malikshi** [comment]
> > cool enhancement, using wireproxy instead wireguard. so it's not create new interface right? maybe this one can work along other dockers stufff without worry?
> 
> Yes. You got that right. It 's a whitelist.

i gonna try on my idle vps. how the speed this method compared to wireguard or native warp-cli socks5 ?

**Comment by malikshi** [comment]
> Much better than warp-cli.

Wireproxy support dual stack?

**Comment by fscarmen** [comment]
> > Much better than warp-cli.
> 
> Wireproxy support dual stack?

IPv4 for socks5

**Comment by malikshi** [comment]
> > > Much better than warp-cli.
> > 
> > 
> > Wireproxy support dual stack?
> 
> IPv4 for socks5

Thanks you for the info. I need reconfigure routing transit in xray server. Wireproxy can't set DNS localhost/127.0.0.1 ?

**Comment by octeep** [comment]
> > > > Much better than warp-cli.
> > > 
> > > 
> > > Wireproxy support dual stack?
> > 
> > 
> > IPv4 for socks5
> 
> Thanks you for the info. I need reconfigure routing transit in xray server. Wireproxy can't set DNS localhost/127.0.0.1 ?

Hi, I'm the official maintainer of wireproxy. Setting DNS to localhost would not work. Are you hosting a DNS server on the same machine as the one hosting wireproxy? If so, I can fix it for you in a new commit.

**Comment by ben-august** [comment]
这种模式支持定时检查流媒体解锁状态吗？我看脚本好像还没这个功能

**Comment by fscarmen** [comment]
> 这种模式支持定时检查流媒体解锁状态吗？我看脚本好像还没这个功能

与本脚本原来的方式一样啊，```warp i```
但可能你是早几天安装的，你试试 ```grep change_wireproxy /etc/wireguard/menu.sh``` 有没有东西，没有的话，建议卸载掉再重新安装，加入了刷解锁 Netflix 的

**Comment by ben-august** [comment]
> > 这种模式支持定时检查流媒体解锁状态吗？我看脚本好像还没这个功能
> 
> 与本脚本原来的方式一样啊，`warp i` 但可能你是早几天安装的，你试试 `grep change_wireproxy /etc/wireguard/menu.sh` 有没有东西，没有的话，建议卸载掉再重新安装，加入了刷解锁 Netflix 的

大佬我telegram联系你

**Comment by visense** [comment]
要是能支持ipv6就好了

**Comment by fscarmen** [comment]
> 要是能支持ipv6就好了

可以的，把 /etc/wireguard/wgcf.conf 里的  Address = 2606:4700:110:8eef::20d3:***:***/128 ，复制到 /etc/wireguard/proxy.conf 相应的位置  ，最后两次 `warp y`

**Comment by visense** [comment]
> > 要是能支持ipv6就好了
> 
> 
> 
> 可以的，把 /etc/wireguard/wgcf.conf 里的  Address = 2606:4700:110:8eef::20d3:***:***/128 ，复制到 /etc/wireguard/proxy.conf 相应的位置  ，最后两次 `warp y`
> 
> 
> 
> 看你的 奈飞的重度用户，靠 warp 始终不稳，你不用 dns中转的呢？

哪里找稳定的dns？
