### ISSUE TITLE
ubuntu16.4获取 WARP IP 不成功-【结论：系统相对较老，并没有定点到哪里出问题，用户把系统换为 Ubuntu 18.04 后正常使用。】

### ISSUE THREAD

**Issue by zyrf-web** [fscarmen/warp#114]
![Snipaste_2022-03-28_08-30-57](https://user-images.githubusercontent.com/62420426/160309084-6df1e187-131d-406e-a00f-c1e1c355e0ea.png)
在ubuntu16.4-bbr中进行安装的时候，为什么会出现这种情况啊

**Comment by fscarmen** [comment]
这是安装resolvconf依赖后的重启建议，ubuntu16.04才有的。实际我测试中发现不重启也没问题，你先确认看看。

**Comment by zyrf-web** [comment]
确认之后就变成尝试5次不成功了

**Comment by fscarmen** [comment]
机器是什么地区的呢？运行以下指令发发回显
```
systemctl is-active wg-quick@wgcf
wg-quick up wgcf
```

**Comment by zyrf-web** [comment]
我换了个版本，用了18.4可以了
![image](https://user-images.githubusercontent.com/62420426/160312525-88336632-fb85-4ccb-8a66-0ccd99858784.png)

**Comment by fscarmen** [comment]
> 我换了个版本，用了18.4可以了。
 
排除了某些地方现在停了 WARP ，获取不了 IP 导致失败的情况。
那结论推断是16.04过旧，这些偏旧的系统包括 Debian 9，Linux 内核也很旧，多多少少出现这样那样的问题。所以还是建议用较新的系统 Ubuntu 20.04 , Debian 10,11 之类的。遇到的问题少得多。

**Comment by zyrf-web** [comment]
谢谢您，不过厂家给的机器没有最新版本的系统，只能先这样用了。
