### ISSUE TITLE
原生双栈 添加 WARP 双栈网络接口 后无法打开docker版本的qbittorrent -【结论：同时使用docker和warp的，可以用wireproxy, warp-cli, iptables 方案，不影响访问容器服务。又或者容器创建时使用host网络模式】

### ISSUE THREAD

**Issue by dinaau** [fscarmen/warp#115]
先安装docker 版的qb 
之后脚本安装了ipv4 +6的 warp+

然后web页面的qb就无法打开了 ip:8080

永久关闭 WARP 网络接口，并删除 WARP 和 Linux Client后 ip:8080 url 立刻恢复

有没有方案2者共存的

**Comment by fscarmen** [comment]
可以用iptable（菜单12）
或 wireproxy（菜单13）
这两个不影响docker，但要在v2ray配置文件指定域名白名单走warp，没指定的走vps原出口

**Comment by dinaau** [comment]
用了iptable选项可以了
如果需要卸载，也是选择    7. 永久关闭 WARP 网络接口，并删除 WARP 和 Linux Client 吗？

**Comment by fscarmen** [comment]
> 用了iptable选项可以了 如果需要卸载，也是选择 7. 永久关闭 WARP 网络接口，并删除 WARP 和 Linux Client 吗？

是的。这里要注意，iptables 方案本来为分流流媒体设计的，即 youtube , Netflix ,Disney+ 等流量走warp，其他不走。
如果你有哪些网站数据需要走warp出口的，可以参照这个 #98

**Comment by dinaau** [comment]
> > 用了iptable选项可以了 如果需要卸载，也是选择 7. 永久关闭 WARP 网络接口，并删除 WARP 和 Linux Client 吗？
> 
> 是的，当然你也可以用快捷指令 `warp u` 这里要注意，iptables 方案本来为分流流媒体设计的，即 youtube , Netflix ,Disney+ 等流量走warp，其他不走。 如果你有哪些网站数据需要走warp出口的，可以参照这个 #98

如果需要所有流量都走warp， 并且不影响docker要怎么实现呢

**Comment by fscarmen** [comment]
> 如果需要所有流量都走warp， 并且不影响docker要怎么实现呢

你试试用docker的host网络模式

**Comment by dinaau** [comment]
> > 如果需要所有流量都走warp， 并且不影响docker要怎么实现呢
> 
> 你试试用docker的host网络模式

什么意思没看懂 求教程步骤

**Comment by fscarmen** [comment]
[docker的四种网络模式（Bridge、Host、Container、None 网络模式），自定义网络(创建自定义网桥、使两个不同网桥的容器通信、跨主机容器容器通讯等)](https://blog.csdn.net/qq_41830712/article/details/90721395)

 创建窗口的时候 把   --network=bridge 改为 --network=host

**Comment by dinaau** [comment]
> [docker的四种网络模式（Bridge、Host、Container、None 网络模式），自定义网络(创建自定义网桥、使两个不同网桥的容器通信、跨主机容器容器通讯等)](https://blog.csdn.net/qq_41830712/article/details/90721395)
> 
> 创建窗口的时候 把 --network=bridge 改为 --network=host
哇这么麻烦 算了暂时先卸载掉warp了

**Comment by cedar-c** [comment]
> 可以用iptable（菜单12） 或 wireproxy（菜单13） 这两个不影响docker，但要在v2ray配置文件指定域名白名单走warp，没指定的走vps原出口
不好意思，想问一下，这里怎么在v2ray配置域名白名单

**Comment by fscarmen** [comment]
项目的 README.md 里有各种模板，套用即可。

**Comment by cedar-c** [comment]
> 项目的 README.md 里有各种模板，套用即可。

对不起，我实在是没找到。。。

**Comment by fscarmen** [comment]
<img width="1117" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/61ee4ef6-2b89-41c7-ad89-87480dbd1e8b">
