### ISSUE TITLE
为什么停止warp后vps可以使用。-【结论：用户长时间没有反馈。暂时 Close 处理】

### ISSUE THREAD

**Issue by Master-Bene** [fscarmen/warp#116]
我的vps是v2ray，获得ip后原本的ip和warp的ip服务都通不了，停止warp后才能恢复正常，这个啥情况

**Comment by fscarmen** [comment]
既然能获取warp IP，为什么warp说不通呢

**Comment by fscarmen** [comment]
> > 既然能获取warp IP，为什么warp说不通呢
> > 获取到warp ip后vps就不能正常访问网站，卸载warp后又可以正常访问

？？？？

**Comment by Master-Bene** [comment]
> > > 既然能获取warp IP，为什么warp说不通呢
> 
> > > 获取到warp ip后vps就不能正常访问网站，卸载warp后又可以正常访问
> 
> 
> 
> ？？？？

可以加个好友远程帮看下吗？我也是对这个不太了解

**Comment by fscarmen** [comment]
加 tg @fscarmen2

**Comment by ben-august** [comment]
可能是一直在刷warp ip就会这样

**Comment by thormuxin** [comment]
ipv4 单栈warp ip获得后 vps就会断网
