### ISSUE TITLE
德鸡 Ubuntu20.04 系统 ipv4无法登录-【结论：WARP 的 IP 是让VPS多个网络出口，并不是添加 IPv4 入口的】

### ISSUE THREAD

**Issue by fys666** [fscarmen/warp#117]
大佬好，
可以告知一下德鸡怎么设置吗？我安装了Ubuntu20.04 系统 然后输入了bash menu.sh 4 然后就有一个ipv4地址了，但是我还是无法在本地只支持ipv4的电脑登陆德鸡，另外这样操作完，请问怎么搭tizi呢？

**Comment by fscarmen** [comment]
> 大佬好， 可以告知一下德鸡怎么设置吗？我安装了Ubuntu20.04 系统 然后输入了bash menu.sh 4 然后就有一个ipv4地址了，但是我还是无法在本地只支持ipv4的电脑登陆德鸡，另外这样操作完，请问怎么搭tizi呢？
用户才是大佬。

> 我安装了Ubuntu20.04 系统 然后输入了bash menu.sh 4 然后就有一个ipv4地址了，但是我还是无法在本地只支持ipv4的电脑登陆德鸡
是这样的，那个IPv4只是用于VPS访问外面的，是公用的IP，并不是用于我们访问VPS的。原理 README 有

* 为仅IPv6服务器添加IPv4

原理如图，IPv4的流量均被WARP网卡接管，实现了让IPv4的流量通过WARP访问外部网络。
<img src="https://user-images.githubusercontent.com/62703343/135735404-1389d022-e5c5-4eb8-9655-f9f065e3c92e.png" width="70%" />

> 请问怎么搭tizi呢?
这分两个情况：
1、如果你想把这个德鸡当作服务端，那么客户端一定需要支持IPv6（如果没有也可以用 warp ，bash 6 获取到 IPv6 的网络出口），然后客户端填的德鸡服务端 IPv6  或者 域名（ 德鸡 AAAA 解析的) 

如果你是把德鸡当作客户端，安装 warp 4 获取到 IPv4 后，填服务端 VPS 的 IPv4 或者  IPv6 又或者解析的域名都可以。

**Comment by fys666** [comment]
> 

请问可以详细说一下服务端的事情吗？我客户端可以用手机热点，就保证了IPV6，后续呢？比如我使用V2ray这个软件，只有德鸡服务端 IPv6 或者 域名（ 德鸡 AAAA 解析的)不够啊，具体怎么操作呢？或者我可以从哪里看到帮助文档呢？可以简单讲一下吗？拜托了！！！

**Comment by fscarmen** [comment]
我的德鸡是这样使用的：
1.CF 设置 AAAA 解析
2.安装warp
3.安装mack-a 八合一，选用带ws的，VLESS+TLS+WS、VMESS+TLS+WS 或 Trojian-GO+WS
4.v2rayN 那里设置优选IP，用CDN

**Comment by fys666** [comment]
> 

好的，感谢，大体已经成功了，剩下的就是调试一下速度了。我使用的是VLESS+TLS+WS，cloudfare 的设置是关闭云朵和AAAA解析以及full ssl ，v2rayN也用作者推荐的测速软件选了优选IP 用CDN是什么意思么？谢谢，大体已经成功了，大部分国外网站都可以登录了，但是离谱的是最重要的谷歌无法登录！

**Comment by fscarmen** [comment]
> 
> v2rayN也用作者推荐的测速软件选了优选IP 用CDN是什么意思么？谢谢，大体已经成功了，大部分国外网站都可以登录了，但是离谱的是最重要的谷歌无法登录！

CDN就是你用了优选之后，CF给你的服务，需要用优选+ws才可以，延时会高些，但速度还行，我油管有7000-20000上下。
至于谷歌无法登录的话就是太神奇了，我想像不到问题在哪

**Comment by fys666** [comment]
> > 大佬好， 可以告知一下德鸡怎么设置吗？我安装了Ubuntu20.04 系统 然后输入了bash menu.sh 4 然后就有一个ipv4地址了，但是我还是无法在本地只支持ipv4的电脑登陆德鸡，另外这样操作完，请问怎么搭tizi呢？
> > 用户才是大佬。
> 
> > 我安装了Ubuntu20.04 系统 然后输入了bash menu.sh 4 然后就有一个ipv4地址了，但是我还是无法在本地只支持ipv4的电脑登陆德鸡
> > 是这样的，那个IPv4只是用于VPS访问外面的，是公用的IP，并不是用于我们访问VPS的。原理 README 有
> 
> * 为仅IPv6服务器添加IPv4
> 
> 原理如图，IPv4的流量均被WARP网卡接管，实现了让IPv4的流量通过WARP访问外部网络。 <img alt="" width="70%" src="https://user-images.githubusercontent.com/62703343/135735404-1389d022-e5c5-4eb8-9655-f9f065e3c92e.png">
> 
> > 请问怎么搭tizi呢?
> > 这分两个情况：
> > 1、如果你想把这个德鸡当作服务端，那么客户端一定需要支持IPv6（如果没有也可以用 warp ，bash 6 获取到 IPv6 的网络出口），然后客户端填的德鸡服务端 IPv6  或者 域名（ 德鸡 AAAA 解析的)
> 
> 2、如果你是把德鸡当作客户端，安装 warp 4 获取到 IPv4 后，填服务端 VPS 的 IPv4 或者 IPv6 又或者解析的域名都可以。



最后一个问题，老哥，我想把这个德鸡当作服务端，但是客户端没有支持IPv6（我不能一直用手机热点），然后怎么操作呢？我已经使用了你的脚本打开了IPV4，然后在我的电脑上选择的是德鸡AAAA解析的域名 ，但是我在电脑上输入域名是打不开网站的，不应该是访问那个ipv4的地址吗？对了。如果我有多个服务器，是不是必须有多个域名，非常感谢你的帮助

**Comment by fscarmen** [comment]
> 最后一个问题，老哥，我想把这个德鸡当作服务端，但是客户端没有支持IPv6（我不能一直用手机热点），然后怎么操作呢？我已经使用了你的脚本打开了IPV4，然后在我的电脑v2ray上选择的是德鸡AAAA解析的域名 ，但是我在电脑上输入域名是打不开网站的，不应该是访问那个ipv4的地址吗？对了。如果我有多个服务器，是不是必须有多个域名，非常感谢你的帮助

我用了 warp 之后，网站的端口设置为 cf https 支持的443，就能访问了啊。

多个服务器，用第一个一级域名可以啦，绑定不同的二级域名可以了，比如  1.abc.com, 2.abc.com, 3.abc.com，他们分别是3个不同的vps

**Comment by fys666** [comment]
> > 最后一个问题，老哥，我想把这个德鸡当作服务端，但是客户端没有支持IPv6（我不能一直用手机热点），然后怎么操作呢？我已经使用了你的脚本打开了IPV4，然后在我的电脑v2ray上选择的是德鸡AAAA解析的域名 ，但是我在电脑上输入域名是打不开网站的，不应该是访问那个ipv4的地址吗？对了。如果我有多个服务器，是不是必须有多个域名，非常感谢你的帮助
> 
> 我用了 warp 之后，网站的端口设置为 cf https 支持的443，就能访问了啊。
> 
> 多个服务器，用第一个一级域名可以啦，绑定不同的二级域名可以了，比如 1.abc.com, 2.abc.com, 3.abc.com，他们分别是3个不同的vps

非常感谢，老哥，上不去谷歌是因为我浏览器的插件代理冲突了，这个二级域名挺方便的但是我只有ipv4的电脑还是没办法打开我的伪站，我是不是应该去问问另一个脚本的作者

**Comment by fscarmen** [comment]
> 但是我只有ipv4的电脑还是没办法打开我的伪站，我怀疑IPv4的流量没有被WARP网卡接管。但是脚本已经希纳是warp网络接口开启，并且有ipv4的ip

结论都说了-【结论：WARP 的 IP 是让VPS多个网络出口，并不是添加 IPv4 入口的】
无论你 ssh 或者访问伪站，都是入口，只能 IPv6

**Comment by fscarmen** [comment]
今天早上的德鸡还挺好的呢，旧 mack-a 里的八合一 trojan-go tls ws
<img width="850" alt="image" src="https://user-images.githubusercontent.com/62703343/161671618-1728ac99-806d-4a1b-8a6c-7d493e706e50.png">
