### ISSUE TITLE
请问WireProxy每次重启之后都要手动重新运行一次脚本才能创建是吗

### ISSUE THREAD

**Issue by gcphym** [fscarmen/warp#118]
请问每次重启机器之后 WireProxy都要手动重新运行一次脚本才能创建是吗
有没有类似warp r之类的开关功能

**Comment by fscarmen** [comment]
> 有没有类似warp r之类的开关功能

有 ```warp y```，今晚加上其他 WireProxy 的集成一并更新。内容很多，需要花点时间。

<img width="612" alt="image" src="https://user-images.githubusercontent.com/62703343/160852056-b2b19d21-f5d8-4d34-b3f2-db53230145e2.png">

**Comment by fscarmen** [comment]
今天加入了 wireproxy systemd,  建议你重装，之后使用 warp y 来开关 wireproxy 更方便。

**Comment by gcphym** [comment]
谢谢
