### ISSUE TITLE
为什么安装的时候会出现reboot recommended

### ISSUE THREAD

**Issue by Rpower666** [fscarmen/warp#119]
![image](https://user-images.githubusercontent.com/63964257/160974168-8a19a287-ad44-461e-80d8-7acfb3a5b10e.png)

**Comment by fscarmen** [comment]
#114

系统过旧了吗？确认先不重启，试试不行再重启看，再不行建议升级系统。

**Comment by Rpower666** [comment]
怎么确认啊，我安回车键没反应

**Comment by Rpower666** [comment]
> #114
> 
> 系统过旧了吗？确认先不重启，试试不行再重启看，再不行建议升级系统。

怎么确认啊，我安回车键没反应

**Comment by fscarmen** [comment]
这个系统是LTS最新了你按按 tab键看能不能选进去，不行要百度一下

**Comment by Rpower666** [comment]
> 这个系统是LTS最新了你按按 tab键看能不能选进去，不行要百度一下

ok了，但是为啥会出现那个提示呢

**Comment by fscarmen** [comment]
我在几个vps，甲骨文 dd debian11，GCP和德鸡，hax上都没遇到过，那个不要紧的，是依赖安装的重启系统建议，能使用不要reboot

**Comment by Rpower666** [comment]
> 我在几个vps，甲骨文 dd debian11，GCP和德鸡，hax上都没遇到过，那个不要紧的，是依赖安装的重启系统建议，能使用不要reboot
好的，谢谢
