### ISSUE TITLE
如何修改license_key

### ISSUE THREAD

**Issue by Effie123** [fscarmen/warp#12]
有WARP+账号，怎么修改license_key呢。

**Comment by fscarmen** [comment]
在 wgcf register 步骤之后生成 wgcf-account.toml 文件，按我理解官方关于 Warp+ 说明，需要添加以下这步：修改该文件，更换 private_key 为Warp+的，再进行接着原来的步骤。又或者使用环境变量 WGCF_LICENSE_KEY="123412341234" wgcf update

由于以下两个原因，我脚本处没有添加这步。
1.我没有Warp+账号，不能作测试。
2.脚本会对已经生成的 wgcf-account.toml 删除处理。如果不这样做，再次运行  wgcf register 的时候（场景是使用其他作者的脚本，而他没有对该文件删除或者移动处理），当前已经存在 wgcf-account.toml 而导致运行报错。

最后问问如何弄Warp+账户的？我可以考虑放在脚本开头让用户输入账户。

**Comment by Effie123** [comment]
> 在 wgcf register 步骤之后生成 wgcf-account.toml 文件，按我理解官方关于 Warp+ 说明，需要添加以下这步：修改该文件，更换 private_key 为Warp+的，再进行接着原来的步骤。又或者使用环境变量 WGCF_LICENSE_KEY="123412341234" wgcf update
> 
> 由于以下两个原因，我脚本处没有添加这步。 1.我没有Warp+账号，不能作测试。 2.脚本会对已经生成的 wgcf-account.toml 删除处理。如果不这样做，再次运行到 wgcf register 的时候，由于当前已经存在 wgcf-account.toml 而导致运行报错。（场景是使用其他作者的脚本，没有对该文件删除或者移动处理）
> 
> 最后问问如何弄Warp+账户的？我可以考虑放在脚本开头让用户输入账户。
> 
> ![image](https://user-images.githubusercontent.com/62703343/135720211-a602cc26-0daa-4a26-a838-fb60e4e2fa7d.png)
> 
> ![image](https://user-images.githubusercontent.com/62703343/135720140-476ef02e-fa87-499d-ae98-5aa58928b0ed.png)

确实如你所说，我已经通过修改生成的wgcf-account.toml 文件

**Comment by fscarmen** [comment]
好的，你加我一下TG: https://t.me/fscarmen2

**Comment by fscarmen** [comment]
非常感谢你的issue，2021年10月3日的脚本已经添加对 Warp+ 的支持。
