### ISSUE TITLE
wireproxy，让 WARP 在本地建议一个 socks5 代理  有没有具体的教程？-【结论：项目 README.md 有配置模板，照着做可以了，已经测试过mack-a和Wulabing，其他主流的估计差不多，记得改完配置文件要重启xray,v2ray服务才生效】

### ISSUE THREAD

**Issue by fscarmen** [fscarmen/warp#120]
安装 wireproxy，让 WARP 在本地建议一个 socks5 代理  有没有具体的教程？现在用的是 iptables+dnsmasq+ipset 方案 ，感觉有点影响出口速度。

_Originally posted by @jackiehj in https://github.com/fscarmen/warp/issues/103#issuecomment-1086678920_

**Comment by fscarmen** [comment]
> 安装 wireproxy，让 WARP 在本地建议一个 socks5 代理 有没有具体的教程？现在用的是 iptables+dnsmasq+ipset 方案 ，感觉有点影响出口速度。

使用方式与 warp-cli 一样，安装后vps有一个 socks5 代理（默认：40000端口，可改）

<img width="992" alt="image" src="https://user-images.githubusercontent.com/62703343/161393765-300a11de-767b-4b0c-8b83-28a231ae0333.png">

之后你参数这里的配置v2ray outbound:   [Netflix 分流到 WARP Client Proxy、WireProxy 的方法](https://github.com/fscarmen/warp/blob/main/README.md#Netflix-%E5%88%86%E6%B5%81%E5%88%B0-WARP-Client-ProxyWireProxy-%E7%9A%84%E6%96%B9%E6%B3%95)

BTW: 更换Netflix IP 仍然可以用 ```warp i```，又或者用另一个更pro的解锁项目: [【刷 WARP IP】 - 为 WARP 解锁流媒体而生](https://github.com/fscarmen/warp_unlock)

**Comment by jackiehj** [comment]
我用的是 Wulabing的VLESS + TCP + XTLS / TLS + Nginx 一键脚本。在 Xray 服务端配置：/usr/local/etc/xray/config.json 配置文件里，怎么修改参数？

{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "197",
            "flow": "xtls-rprx-direct"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 60000,
            "alpn": "",
            "xver": 1
          },
          {
            "dest": 60001,
            "alpn": "h2",
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "minVersion": "1.2",
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/xray/self_signed_cert.pem",
              "keyFile": "/usr/local/etc/xray/self_signed_key.pem"
            },
            {
              "certificateFile": "/ssl/xray.crt",
              "keyFile": "/ssl/xray.key"
            }
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}

**Comment by fscarmen** [comment]
1.先备份好原文件
```cp /usr/local/etc/xray/config.json /usr/local/etc/xray/config.json.bak```
2.按以下更改
```
{
"log": {
"access": "/var/log/xray/access.log",
"error": "/var/log/xray/error.log",
"loglevel": "warning"
},
"inbounds": [
{
"port": 443,
"protocol": "vless",
"settings": {
"clients": [
{
"id": "197",
"flow": "xtls-rprx-direct"
}
],
"decryption": "none",
"fallbacks": [
{
"dest": 60000,
"alpn": "",
"xver": 1
},
{
"dest": 60001,
"alpn": "h2",
"xver": 1
}
]
},
"streamSettings": {
"network": "tcp",
"security": "xtls",
"xtlsSettings": {
"minVersion": "1.2",
"certificates": [
{
"certificateFile": "/usr/local/etc/xray/self_signed_cert.pem",
"keyFile": "/usr/local/etc/xray/self_signed_key.pem"
},
{
"certificateFile": "/ssl/xray.crt",
"keyFile": "/ssl/xray.key"
}
]
}
},
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
]
}
}
],

    "outbounds": [
        {
            "protocol": "freedom"
        },
        {
            "tag": "media-unlock",
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1",
                        "port": 40000,
                        "users": []
                    }
                ]
            }
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:netflix"
                ],
                "outboundTag": "media-unlock"
            }
        ]
    }
}
```

3.重启Wulabing的服务

4.实测，如不成功还原原文件，并去Wulabing那提issue，说想分流到端口为40000的socks5如何处理

**Comment by jackiehj** [comment]
> 1.先备份好原文件 `cp /usr/local/etc/xray/config.json /usr/local/etc/xray/config.json.bak` 2.按以下更改
> 
> ```
> {
> "log": {
> "access": "/var/log/xray/access.log",
> "error": "/var/log/xray/error.log",
> "loglevel": "warning"
> },
> "inbounds": [
> {
> "port": 443,
> "protocol": "vless",
> "settings": {
> "clients": [
> {
> "id": "197",
> "flow": "xtls-rprx-direct"
> }
> ],
> "decryption": "none",
> "fallbacks": [
> {
> "dest": 60000,
> "alpn": "",
> "xver": 1
> },
> {
> "dest": 60001,
> "alpn": "h2",
> "xver": 1
> }
> ]
> },
> "streamSettings": {
> "network": "tcp",
> "security": "xtls",
> "xtlsSettings": {
> "minVersion": "1.2",
> "certificates": [
> {
> "certificateFile": "/usr/local/etc/xray/self_signed_cert.pem",
> "keyFile": "/usr/local/etc/xray/self_signed_key.pem"
> },
> {
> "certificateFile": "/ssl/xray.crt",
> "keyFile": "/ssl/xray.key"
> }
> ]
> }
> },
> "sniffing": {
> "enabled": true,
> "destOverride": [
> "http",
> "tls"
> ]
> }
> }
> ],
> 
>     "outbounds": [
>         {
>             "protocol": "freedom"
>         },
>         {
>             "tag": "media-unlock",
>             "protocol": "socks",
>             "settings": {
>                 "servers": [
>                     {
>                         "address": "127.0.0.1",
>                         "port": 40000,
>                         "users": []
>                     }
>                 ]
>             }
>         }
>     ],
>     "routing": {
>         "domainStrategy": "AsIs",
>         "rules": [
>             {
>                 "type": "field",
>                 "domain": [
>                     "geosite:netflix"
>                 ],
>                 "outboundTag": "media-unlock"
>             }
>         ]
>     }
> }
> ```
> 
> 3.重启Wulabing的服务
> 
> 4.实测，如不成功还原原文件，并去Wulabing那提issue，说想分流到端口为40000的socks5如何处理

好的，我去试试看 谢谢大神

**Comment by fscarmen** [comment]
上面格式化了json，好看多了

**Comment by jackiehj** [comment]
> 上面格式化了json，好看多了

确实好看多了。我试了下，按照你的配置更改好，可以看了。哈哈哈～ 不过用Netflix 解锁检测小工具 

wget -O nf https://github.com/sjlleo/netflix-verify/releases/download/2.52/nf_2.52_linux_amd64 && chmod +x nf && clear && ./nf 是无法检测出解锁状态了。还有我怎么可以让Disney+ 也走socks5 ？我要怎么知道IP失效还是解锁状态的？还有使用 warp I 得到的ip都显示没有解锁，但实际是解锁的。

**Comment by jackiehj** [comment]
脚本版本：2.36  功能新增：1. 全网首发: 通过 WireProxy，让 WARP 在本地建议一个 socks5 代理; 2. WARP+ 和 Teams 账户可用于 WireProxy 安装或者升级
 系统信息：
        当前操作系统：Debian GNU/Linux 10 (buster)
        内核：4.14.129-bbrplus
        处理器架构：amd64
        虚拟化：kvm 
        IPv4：**.**.**.**  美国  FIBER-LOGIC 
        IPv6：     
        WARP 网络接口未开启 
        Client 未安装 
        WARP WireProxy 已开启   本地 Socks5:127.0.0.1:40000 WARP IPv4:8.26.182.132 美国 CLOUDFLARENET 

======================================================================================================================

 1.  连接 Client
 2.  断开 WirePorxy
 3.  更改 Client 或 WireProxy 端口
 4.  升级为 WARP+ 或 Teams 账户
 5.  安装 WARP 的 Linux Client 和代理模式
 6.  更换支持 Netflix 的 IP
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy
 8.  刷 WARP+ 流量
 9.  升级内核、安装BBR、DD脚本 
 10. 同步最新版本
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS)
 13. 安装 wireproxy，让 WARP 在本地建议一个 socks5 代理
 0. 退出脚本
 
 请选择: 0

**Comment by fscarmen** [comment]
加入迪士尼的配置文件，就是加多个 ,"geosite:disney"
市面上的检测流媒体解锁只会查 IPv4，IPv6全局的流量，查不到以下4个warp方案 ：iptable, warp-cli, wireproxy和 wgcf docker
warp i 只支持奈飞，如果你想加入迪士尼，可以用另一个更pro的解锁项目: [【刷 WARP IP】 - 为 WARP 解锁流媒体而生](https://github.com/fscarmen/warp_unlock)，这支持解锁信息发送到 tg bot

```
{
    "log": {
        "access": "/var/log/xray/access.log", 
        "error": "/var/log/xray/error.log", 
        "loglevel": "warning"
    }, 
    "inbounds": [
        {
            "port": 443, 
            "protocol": "vless", 
            "settings": {
                "clients": [
                    {
                        "id": "197", 
                        "flow": "xtls-rprx-direct"
                    }
                ], 
                "decryption": "none", 
                "fallbacks": [
                    {
                        "dest": 60000, 
                        "alpn": "", 
                        "xver": 1
                    }, 
                    {
                        "dest": 60001, 
                        "alpn": "h2", 
                        "xver": 1
                    }
                ]
            }, 
            "streamSettings": {
                "network": "tcp", 
                "security": "xtls", 
                "xtlsSettings": {
                    "minVersion": "1.2", 
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/etc/xray/self_signed_cert.pem", 
                            "keyFile": "/usr/local/etc/xray/self_signed_key.pem"
                        }, 
                        {
                            "certificateFile": "/ssl/xray.crt", 
                            "keyFile": "/ssl/xray.key"
                        }
                    ]
                }
            }, 
            "sniffing": {
                "enabled": true, 
                "destOverride": [
                    "http", 
                    "tls"
                ]
            }
        }
    ], 
    "outbounds": [
        {
            "protocol": "freedom"
        }, 
        {
            "tag": "media-unlock", 
            "protocol": "socks", 
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1", 
                        "port": 40000, 
                        "users": [ ]
                    }
                ]
            }
        }
    ], 
    "routing": {
        "domainStrategy": "AsIs", 
        "rules": [
            {
                "type": "field", 
                "domain": [
                    "geosite:netflix","geosite:disney"
                ], 
                "outboundTag": "media-unlock"
            }
        ]
    }
}
```

**Comment by jackiehj** [comment]
> 加入迪士尼的配置文件，就是加多个 ,"geosite:disney" 市面上的检测流媒体解锁只会查 IPv4，IPv6全局的流量，查不到以下4个warp方案 ：iptable, warp-cli, wireproxy和 wgcf docker warp i 只支持奈飞，如果你想加入迪士尼，可以用另一个更pro的解锁项目: [【刷 WARP IP】 - 为 WARP 解锁流媒体而生](https://github.com/fscarmen/warp_unlock)，这支持解锁信息发送到 tg bot


嗯嗯！太棒了！成功了！哈哈～～～

**Comment by fscarmen** [comment]
> 嗯嗯！太棒了！成功了！哈哈～～～ 多谢大神指导

给个fork，star，会有解锁buff的

**Comment by malikshi** [comment]
@fscarmen sir, regarding wireproxy config. Are your wireproxy config same as the upstream? I found it's differents, correct me if it's wrong

**Comment by fscarmen** [comment]
> @fscarmen sir, regarding wireproxy config. Are your wireproxy config same as the upstream? I found it's differents, correct me if it's wrong

I was updata WireProxy to v1.0.1,which the same as the upstream.
v1.0.1 config-file is different with beta  one.
You'd better uninstall the former one and install the newest.

**Comment by malikshi** [comment]
> > @fscarmen sir, regarding wireproxy config. Are your wireproxy config same as the upstream? I found it's differents, correct me if it's wrong
> 
> I was updata WireProxy to v1.0.1,which the same as the upstream. v1.0.1 config-file is different with beta one. You'd better uninstall the former one and install the newest.

Thx you. Just updated and works fine
