### ISSUE TITLE
安装脚本之后，每次登录ssh都会跳出一行warning

### ISSUE THREAD

**Issue by lsbjkc** [fscarmen/warp#121]
-bash: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8)
请问这是什么情况，会有什么影响？

**Comment by fscarmen** [comment]
这问题与本脚本无关，最好谷歌

搜 warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8)

https://snippets.aktagon.com/snippets/614-how-to-fix-bash-warning-setlocale-lc-all-cannot-change-locale-en-us-

https://www.cnblogs.com/kevingrace/p/8191929.html

**Comment by lsbjkc** [comment]
非常详细，已解决，感谢！

**Comment by fscarmen** [comment]
> 非常详细，已解决，感谢！

最终如何解决？

**Comment by lsbjkc** [comment]
> 

按照https://www.cnblogs.com/kevingrace/p/8191929.html这个步骤解决的
