### ISSUE TITLE
Features requests: add support lock country

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#122]
can we have option lock country in changing warp ip feature? so option changing country of warp ip/wireproxy ip without checking netflix support.

**Comment by malikshi** [comment]
my vps are from SEA but has better routing to france, the warp/wireproxy always in france but i want to have warp/wireproxy from SG.

**Comment by fscarmen** [comment]
It is estimated that you will be disappointed, consider the following two points:
1. If the user chooses improperly and input in different regions, there is a high probability that WARP IP will never be obtained. For example, jp wants to get the fr IP
2. User can use ```warp o``` several times to achieve.

**Comment by malikshi** [comment]
Well I am aware how warp works, maybe I can try commercial VPN.
