### ISSUE TITLE
 疑似使用WireProxy一段时间后会导致Temporary failure in name resolution

### ISSUE THREAD

**Issue by gcphym** [fscarmen/warp#123]
我用的是nat机 有独立ipv6 ipv4是共用 安装前ping google.com ping出来ipv6的地址
使用脚本第13项安装WireProxy 脚本默认选择ipv4优先 刚安装完成时正常 ping google.com ping 出来ipv4的地址
运行一段时间后 ping: google.com: Temporary failure in name resolution

**Comment by gcphym** [comment]
> nat机我没有试过，估计问题点出在脚本误判断vps有公网 IPv4，导致配置文件 /etc/wireguard/proxy.conf 错误 你试试改一下 Endpoint = 162.159.193.10:2048 改为 Endpoint = [2606:4700:d0::a29f:c001]:2048
> 
> DNS = 1.1.1.1,8.8.8.8,8.8.4.4,2606:4700:4700::1111,2001:4860:4860::8888,2001:4860:4860::8844 改为 DNS = 12606:4700:4700::1111,2001:4860:4860::8888,2001:4860:4860::8844,1.1.1.1,8.8.8.8,8.8.4.4
> 
> 最后 systemctl restart wireproxy 试试

不行 改了之后走warp的网站直接打不开了

**Comment by fscarmen** [comment]
昨天在外面用手机，DNS打错了应该是这个。
DNS = 2606:4700:4700::1111,2001:4860:4860::8888,2001:4860:4860::8844,1.1.1.1,8.8.8.8,8.8.4.4

**Comment by fscarmen** [comment]
> 
> 不行 改了之后走warp的网站直接打不开了

请问问题解决了吗？

**Comment by gcphym** [comment]
> > 不行 改了之后走warp的网站直接打不开了
> 
> 请问问题解决了吗？

不知道怎么回事 没有进行操作就恢复正常了 不知道怎么回事 谢谢

**Comment by fscarmen** [comment]
Wireproxy的效果如何？
