### ISSUE TITLE
did you get new IPs?

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#124]
i found out this morning my warp IP with 104.28.xxx.xxx usually 8.xxx.xxx.xxx is it good news?

all my 4 server got new IPs, did cf add more IPs for warp?

**Comment by fscarmen** [comment]
It sounds a good news. And i have never met that IPs so far.
What region are your 4 servers in?

**Comment by malikshi** [comment]
2 in SG, 2 in ID

**Comment by fscarmen** [comment]
Why my SG could not brush that IPs.
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/62703343/162575367-39f60c85-b09c-4ceb-98e5-afd7959c7159.png">
