### ISSUE TITLE
获取WARP IP失败-【结论：jsDelivr CDN 长时间没有同步最新脚本，请记录最新的安装命令: wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh】

### ISSUE THREAD

**Issue by IAXRetailer** [fscarmen/warp#125]
脚本版本：2.36  功能新增：1. 全网首发: 通过 WireProxy，让 WARP 在本地建议一个 socks5 代理; 2. WARP+ 和 Teams 账户可用于 WireProxy 安装或者升级
 系统信息：
        当前操作系统：CentOS Linux 7 (Core)
        内核：3.10.0-1160.41.1.vz7.183.5
        处理器架构：amd64
        虚拟化：openvz 
        IPv4：     
        IPv6：2a01:4f8:13a:2690:face:470:*******    Hetzner Online GmbH 
        WARP 网络接口未开启 
        Client 未安装 
        WireProxy 未安装 

看起来好像github一直连不上，会不会是这个原因，我先尝试重启vps

**Comment by IAXRetailer** [comment]
Resolving github.com (github.com)... 2001:67c:2b0:db32:0:1:8c52:7904
Connecting to github.com (github.com)|2001:67c:2b0:db32:0:1:8c52:7904|:443... failed: Connection refused.

**Comment by fscarmen** [comment]
> --2022-04-10 11:50:51-- https://github.com/ViRb3/wgcf/releases/download/v2.2.12/wgcf_2.2.12_linux_amd64
> Resolving github.com (github.com)... 2001:67c:2b0:db32:0:1:8c52:7904
> Connecting to github.com (github.com)|2001:67c:2b0:db32:0:1:8c52:7904|:443... failed: Connection refused.
> --2022-04-10 11:50:51-- https://github.com/fscarmen/warp/raw/main/wgcf/wgcf_2.2.12_linux_amd64
> Resolving github.com (github.com)... 2001:67c:2b0:db32:0:1:8c52:7904
> Connecting to github.com (github.com)|2001:67c:2b0:db32:0:1:8c52:7904|:443... failed: Connection refused.

请用现在最新的版本，我上两天已经把其中一个地址换成 jsDelivr 的CDN了

**Comment by IAXRetailer** [comment]
好的，我去试试看

**Comment by IAXRetailer** [comment]
感谢🙏，问题已解决
