### ISSUE TITLE
求助Netflix,Google 分流到 Client WARP 网络接口的方法

### ISSUE THREAD

**Issue by bigpao88** [fscarmen/warp#126]
我按教程里面的文本复制进xray以后无法联通，想请问一下172.16.0.2 为 CloudFlareWARP 网络接口的 IP，这个172.16.0.2是需要自行更改相应数值，还是直接照抄？

**Comment by fscarmen** [comment]
你看  ```ip a | grep CloudflareWARP | grep 172``` 查查是不是这个ip了，现在我脚本写死是 172.16.0.2 这个ip 的

**Comment by bigpao88** [comment]
执行脚本会报以下错误
W: GPG error: https://pkg.cloudflareclient.com focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6E2DD2174FA1C3BA
E: The repository 'http://pkg.cloudflareclient.com focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cloudflare-warp
Failed to start warp-svc.service: Unit warp-svc.service not found.

**Comment by fscarmen** [comment]
你这个是什么系统？

**Comment by bigpao88** [comment]
又重新试了一下，这次可以了，不好意思，麻烦大佬了。关闭ISSUES了

**Comment by fscarmen** [comment]
开头是安装CloudFlare-warp不成功吧？CentOS 7安装要编译glibc库的，时间较长。
后面你是如何解决的

**Comment by fscarmen** [comment]
用这个方案看Netflix 的效果如何？速度和延时和原来的Proxy模式对比如何？

**Comment by bigpao88** [comment]
我用的亚洲区，warp都解不了奈飞，只拿dianey做了测试，速度确实要比其他方法快一点。
