### ISSUE TITLE
谢谢，yyds，救活了我的晚高峰vps，希望加入定时开关-【结论：暂时不考虑做到脚本里，回复提供手动解决方案，在 crontab 设置可以了】

### ISSUE THREAD

**Issue by geekbb** [fscarmen/warp#128]
谢谢，yyds，救活了我的晚高峰vps，但是否可以加入自动执行？比如我的vps晚上18：00后开始抽抽，脚本设置18：00自动执行warp开启，00：00自动执行warp关闭，此乃神器也！
![image](https://user-images.githubusercontent.com/46196358/163190461-390bd557-4534-4b0d-b5b4-8319e0a2f033.png)

**Comment by fscarmen** [comment]
你执行以后命令吧，暂时不加到主脚本的功能了
```
timedatectl set-timezone Asia/Shanghai # 设为中国+8时区
date # 看看显示的时间是不是北京时间
echo -e "0 0 * * * root systemctl stop wg-quick@wgcf\n0 18 * * * root systemctl start wg-quick@wgcf " >> /etc/crontab # 18：00自动执行warp开启，00：00自动执行warp关闭 的定时任务
```
