### ISSUE TITLE
为什么我的日本vps 获取的ipv6是美国的，ipv4又是正常-【结论：两个可能，1、真实部分或者全部 IPv6 绕美了，2、IPv6 库不准确，刷多几次看看】

### ISSUE THREAD

**Issue by geekbb** [fscarmen/warp#129]
如图
<img width="524" alt="image" src="https://user-images.githubusercontent.com/46196358/163192500-fcfb8349-bed3-43cb-8f74-4f52fe0006b1.png">

**Comment by fscarmen** [comment]
你这个ipv6并不是warp的，是vps原生的，有可能是ipv6库判断错误了
