### ISSUE TITLE
Warp+ ID怎么获取？？

### ISSUE THREAD

**Issue by pingProMax** [fscarmen/warp#13]
Warp+ ID怎么获取？？-【结论：主页已加傻瓜式图文说明】

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/135984664-de40e2bd-dd60-4db9-996f-3b3aa480b925.png)

 手机下载地址：https://1.1.1.1/，访问和苹果外区 ID 自理
 获取 Warp+ ID 方法：App右上角菜单 三 --> 高级 --> 诊断 --> ID

**Comment by fscarmen** [comment]
已加图文说明
https://github.com/fscarmen/warp/blob/main/README.md#warp-license-%E5%8F%8A-id-%E8%8E%B7%E5%8F%96
