### ISSUE TITLE
iptable, docker, wireproxy socks5, CloudFlare Client WARP, CloudFlare Client Proxy 哪个更好-【结论：需要结合使用场景的才能判断，有对宿主机影响小，有warp网络好点，情况太复杂，我也没有一一测速，还请用户自己多试试对比一下效果】

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#132]
首先感谢大佬辛苦付出！我想问安装脚本里貌似有三种模式CloudFlare Client Proxy 模式、 wireproxy socks5、CloudFlare Client  WARP 模式，哪个模式好，速度哪最快，比如
wireproxy socks5 > CloudFlare Client WARP > CloudFlare Client Proxy?
请大佬指教！

**Comment by fscarmen** [comment]
具体我没有实测过，理论上说 
wireproxy socks5 > CloudFlare Client Proxy > CloudFlare Client WARP
或者
CloudFlare Client Proxy > wireproxy socks5 > CloudFlare Client WARP

**Comment by visense** [comment]
> 

感谢大佬回复！

**Comment by fscarmen** [comment]
> > 
> 
> 感谢大佬回复！

期待你试试，反馈过结果过来呢：）

**Comment by visense** [comment]
> > > 
> > 
> > 
> > 感谢大佬回复！
> 
> 期待你试试，反馈过结果过来呢：）

使用IPtable方式，
用大佬之前在其他issue中提到的命令：curl -ks4m5 ip.gs查看ip是warp ip
用curl ipinfo.io ，显示vps原来v4 ip
想问如何查看访问特定域名自己使用的是哪个ip?比如我想知道自己访问Google用的是warp ip还是vps原来ip，而访问Netflix用的是warp ip还是vps原来ip，命令是什么呀？

**Comment by fscarmen** [comment]
> 
> 使用IPtable方式， 用大佬之前在其他issue中提到的命令：curl -ks4m5 ip.gs查看ip是warp ip 用curl ipinfo.io ，显示vps原来v4 ip 想问如何查看访问特定域名自己使用的是哪个ip?比如我想知道自己访问Google用的是warp ip还是vps原来ip，而访问Netflix用的是warp ip还是vps原来ip，命令是什么呀？

https://github.com/fscarmen/warp/issues/98#issuecomment-1072903709

**Comment by visense** [comment]
> > 使用IPtable方式， 用大佬之前在其他issue中提到的命令：curl -ks4m5 ip.gs查看ip是warp ip 用curl ipinfo.io ，显示vps原来v4 ip 想问如何查看访问特定域名自己使用的是哪个ip?比如我想知道自己访问Google用的是warp ip还是vps原来ip，而访问Netflix用的是warp ip还是vps原来ip，命令是什么呀？
> 
> [#98 (comment)](https://github.com/fscarmen/warp/issues/98#issuecomment-1072903709)

十分感谢

**Comment by visense** [comment]
> 具体我没有实测过，测速应该在实际应用场景，比如 Netflix, Disney+，还有测速网 speed.net, fast.com 等，宽带有500兆或以上这样的环境才好。
> 
> 按我不专业的理解上说 iptables > wireproxy socks5 > CloudFlare Client Proxy > CloudFlare Client WARP 或者 iptables > CloudFlare Client Proxy > wireproxy socks5 > CloudFlare Client WARP
> 
> 同时 CloudFlare Client Proxy 和 wireproxy socks5 对宿主机影响少，换IP的时候不会让主服务断流

还有一个问题请教一下？
1、使用iptable模式，如何让所有流量走warp【默认是油管、奈飞、Disney、tvb、tiktok】；
2、/etc/dnsmasq.d/warp.conf里面加其他网站，比如Google，里面的ipset后面的域名哪里找
比如：ipset=/fast.com/warp
ipset=/netflix.com/warp
ipset=/netflix.net/warp
ipset=/nflxext.com/warp
ipset=/nflximg.com/warp
ipset=/nflximg.net/warp
ipset=/nflxso.net/warp
ipset=/nflxvideo.net/warp
上面这些我要换成Google、Twitter和Facebook哪里找

**Comment by fscarmen** [comment]
如何是全局warp，就不要选iptable方案了

**Comment by visense** [comment]
> 如何是全局warp，就不要选iptable方案了

在你之前的issue中提到只有iptable、docker和client 方案换ip,不影响断网。但是从速度上来说，好像iptable是最快的了，想知道如何在/etc/dnsmasq.d/warp.conf中加Twitter和Facebook等配置

**Comment by fscarmen** [comment]
> Google、Twitter和Facebook

我没有太深研究，你可以在此项目找找这些网站的 geoip，添加方法你打开 /etc/dnsmasq.d/warp.conf 照抄可以了，记得重启xray服务以生效

https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by visense** [comment]
> 

感谢！！！最近获取的warp ip 解锁奈飞一直失败，新加坡和俄罗斯的都是获取100多个ip都解不了Netflix

**Comment by fscarmen** [comment]
> > 
> 
> 感谢！！！最近获取的warp ip 解锁奈飞一直失败，新加坡和俄罗斯的都是获取100多个ip都解不了Netflix

加速主义啊！

**Comment by visense** [comment]
> > > 
> > 
> > 
> > 感谢！！！最近获取的warp ip 解锁奈飞一直失败，新加坡和俄罗斯的都是获取100多个ip都解不了Netflix
> 
> 加速主义啊！

?什么意思

**Comment by fscarmen** [comment]
哦，对了，还有个docker方案的，以alpine为基础系统，把wgcf warp 和换ip都放在容器里完成，并为宿主机提供socks5代理，这样对宿主机的影响也是最小的。

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp_unlock/issues/13#issuecomment-1113898629
