### ISSUE TITLE
安装 CloudFlare Client 并设置为 WARP 模式 重启之后会失效？-【结论：2022年4月16日 8：55 AM 修复该问题，该bug只发生在某些系统】

### ISSUE THREAD

**Issue by gcphym** [fscarmen/warp#133]
使用脚本第14项 安装 CloudFlare Client 并设置为 WARP 模式 按照下面的模板进行分流 第一次安装之后可以正常使用
但是不能用warp r 开关控制或者reboot机器 不然会失效 必须卸载重装才能用

安装完成后 输入warp 并没有出现 再次运行用 warp [option] [lisence] 黄色菜单 出现的是初次安装时的绿色菜单

**Comment by fscarmen** [comment]
> 但是不能用warp r 开关控制或者reboot机器 不然会失效 必须卸载重装才能用

昨天 2022年4月14日下午5点左右做了修正，你用 ```warp v```升级一下，之后用```warp r```开关。如果再不行，在确认创建好 CloudFlareWARP 网络端口后，重启一下xray服务



> 安装完成后 输入warp 并没有出现 再次运行用 warp [option] [lisence] 黄色菜单 出现的是初次安装时的绿色菜单

是的，黄色的 warp [option] [lisence] 只在第一次安装的结尾时候出现，后续想了解，可以用 ```warp h```，但考虑屏幕显示的问题，那个也不是最全的，最全的在项目的readme里

**Comment by fscarmen** [comment]
> 使用脚本第14项 安装 CloudFlare Client 并设置为 WARP 模式 按照下面的模板进行分流 第一次安装之后可以正常使用 但是不能用warp r 开关控制或者reboot机器 不然会失效 必须卸载重装才能用

2022年4月16日 8：55 AM 收复该问题，你用 ```warp v``` 升级一下，之后用 ```warp r``` 开关。
