### ISSUE TITLE
开启本地sock5 代理后，netflix 检测到使用vpn代理-【结论：之前我测试奈飞是可以的，现在的风控判定可能有变化，也可能与地区有关，请用户自行测试】

### ISSUE THREAD

**Issue by hadow** [fscarmen/warp#134]

**Comment by fscarmen** [comment]
或许 Netflix 改了风控规则了，没有办法

**Comment by hadow** [comment]
有可能cf 并没有隐藏真实的IP

**Comment by fscarmen** [comment]
> 有可能cf 并没有隐藏真实的IP

Netflix 域名不是托管到cf的，所以cf应该会隐藏真实IP，只暴露warp的IP。判断依据是在网址后面加上 /cdn-cgi/trace
有数据即是托管在 cf的
比如以下这个是有数据的 ： https://ip.sb/cdn-cgi/trace
以下这个是没有数据的：https://ip.gs/cdn-cgi/trace
