### ISSUE TITLE
warp CLIENT 没办法添加 warp plus 账号-【结论：初始 license 要刷些流量才能正常使用，脚本提供三个刷流量脚本，让大家刷到天荒地老，warp p 按提示操作即可】

### ISSUE THREAD

**Issue by yl1677866238** [fscarmen/warp#135]

**Comment by fscarmen** [comment]
可以啊，安装的时候填入plus账号。又或者用 ```warp a [plus license]``` 来升级啊

![image](https://user-images.githubusercontent.com/62703343/163690602-5227db44-a869-4462-87d5-45ecabacb451.png)

**Comment by hadow** [comment]
[root@193 ~]# warp a pFa5N942-ZvU089F7-1F37ufY2
 检查环境中…… 
 请自定义 WARP+ 设备名 (如果不输入，默认为 [WARP]): 
 升级失败，WARP+ 账户错误或者已激活超过5台设备，自动更换免费 WARP 账户继续

**Comment by fscarmen** [comment]
> [root@193 ~]# warp a pFa5N942-ZvU089F7-1F37ufY2 检查环境中…… 请自定义 WARP+ 设备名 (如果不输入，默认为 [WARP]): 升级失败，WARP+ 账户错误或者已激活超过5台设备，自动更换免费 WARP 账户继续

升级失败提示了，你这个 license 应该是超过5台设备了，两个方法处理了。
1.在 1.1.1.1 的账户-->管理设备 里看已经用该 license 激活的设备列表，把不需要的删除。
2.重新弄个 license

**Comment by yl1677866238** [comment]
我在客户端里面把，授权设备删完了也不行，不知道咋回事

**Comment by fscarmen** [comment]
license是复制过去的吗？有时候0和O，I和l会搞混的

**Comment by yl1677866238** [comment]
> license是复制过去的吗？有时候0和O，I和l会搞混的
是复制过去的 不知道咋回事 我再试一次

**Comment by yl1677866238** [comment]
> > license是复制过去的吗？有时候0和O，I和l会搞混的
> > 是复制过去的 不知道咋回事 我再试一次
主要是wireproxy添加都没问题

**Comment by hadow** [comment]
试过了，一直不成功，确定正确license 和 绑定设备数量

**Comment by fscarmen** [comment]
> 试过了，一直不成功，确定正确license 和 绑定设备数量

我又试过 wgcf warp 的，也是可以啊，设备名字叫 test 的

<img width="570" alt="image" src="https://user-images.githubusercontent.com/62703343/163776952-8073d2c0-3813-4bd4-9576-0355a9378fb7.png">

<img width="425" alt="image" src="https://user-images.githubusercontent.com/62703343/163777261-7292a8b0-c195-49e1-8f5c-abaeca32fc66.png">

<img width="421" alt="image" src="https://user-images.githubusercontent.com/62703343/163777307-479f1a45-a98a-415c-b371-34d2e6b82155.png">

**Comment by hadow** [comment]
我换了一种方法，先通过分享，获得奖励流量，然后再添加就正常了

**Comment by fscarmen** [comment]
按```warp p``` ，有3个可以用的刷流量脚本，后台刷可以了
<img width="704" alt="image" src="https://user-images.githubusercontent.com/62703343/163974945-8fb3ae2e-8b79-45b0-8e97-d4fbb94d8596.png">
