### ISSUE TITLE
warp u 卸载了后 安装脚本面上还是显示已经安装了WARP WireProxy -【结论：`warp u` 卸载，如有问题再来反馈】

### ISSUE THREAD

**Issue by ouuobbc** [fscarmen/warp#136]
warp u 运行后wireproxy服务疑似无法卸载；
warp u 运行后 重新脚本安装 ，面板显示WARP WireProxy 已开启   安装界面也不是新的安装界面 ；
截图为warp u 后 重新脚本安装的界面；

![1650165951(1)](https://user-images.githubusercontent.com/59521430/163699462-215b998a-6a7d-4bf7-b189-e045e126da7e.jpg)

**Comment by fscarmen** [comment]
先试试这个 ```rm -rf /usr/bin/wireproxy```

问题仍旧的话，运行以下

```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh # 下载
bash menu.sh # 卸载
type -P wireproxy # 查看是否还存在，卸载的话应该不会再存在了
```

**Comment by ouuobbc** [comment]
> ```
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh) u # 卸载
> type -P wireproxy # 查看是否还存在，卸载的话应该不会再存在了
> ```

> ```
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh) u # 卸载
> type -P wireproxy # 查看是否还存在，卸载的话应该不会再存在了
> ```
 
非常感谢  删除了/usr/bin/wireproxy后成功解决

**Comment by fscarmen** [comment]
> 非常感谢 删除了/usr/bin/wireproxy后成功解决

有点奇怪，卸载应该会把该文件删除的，不知道为什么你的没有删除掉，导致脚本误判断了
