### ISSUE TITLE
弱弱问一句 中国ip登陆的相关问题-【结论：各地的运营商情况不一定，请用户自行测试】

### ISSUE THREAD

**Issue by FUjr** [fscarmen/warp#137]
1、经过测试发现 中国教育网/中国ipv6（广东）使用官方客户端登陆成功概率极高，在linux、windows、ios、android 都成功登录，但是macos（12.3 M1）登录不了，由于是team，没有办法获取链接日志
2、除了linux客户端，中国家宽ipv4几乎无法登录，但是使用warp-cli客户端能够正常稳定连接

但是测试无论是教育网、ipv6、家宽ipv4都不能使用wire guard连接
**提问：所以第三方客户端在国内能用么**

**Comment by fscarmen** [comment]
> 1、经过测试发现 中国教育网/中国ipv6（广东）使用官方客户端登陆成功概率极高，在linux、windows、ios、android 都成功登录，但是macos（12.3 M1）登录不了，由于是team，没有办法获取链接日志

不同地区，不同运营商，官方客户端是否能登陆，登陆后是否能使用，真要实测过才行了。我这里的情况是广东移动4G用1.1.1.1的teams是正常。公司电信wifi 开 teams 也能4K，油管在4-6W，速度起来快。




> 2、除了linux客户端，中国家宽ipv4几乎无法登录，但是使用warp-cli客户端能够正常稳定连接

这句不太明白意思



> 但是测试无论是教育网、ipv6、家宽ipv4都不能使用wire guard连接

可以，我从teams里提取到信息放到 wireguard 里运行是可以啊，速度也行。


<img width="1668" alt="image" src="https://user-images.githubusercontent.com/62703343/163971802-5838facc-0b83-4e53-8b3e-b6e482fd4cbd.png">

**Comment by FUjr** [comment]
> 2、除了linux客户端，中国家宽ipv4几乎无法登录，但是使用warp-cli客户端能够正常稳定连接
意思是我测试：使用只有ipv4的家宽（广东移动），通过官方客户端（win、Android、macos、linux、iOS）只有linux能顺利连接，其他都是无限转圈。不过结合您的家宽正常连接，我觉得有可能是运营商屏蔽了，而非cf屏蔽中国ip。

>但是测试无论是教育网、ipv6、家宽ipv4都不能使用wire guard连接
目前测试使用wireguard连接用wgcf生成的wireguard配置会提示：
2022-04-20 08:28:17.866 [NET] peer(bmXO…fgyo) - Sending handshake initiation
无论是使用hk的机器还是家里的宽带。

>可以，我从teams里提取到信息放到 wireguard 里运行是可以啊，速度也行。
后来用Android studio提取的xml，字段好像改了，已经变成了这样子，复制进wireguard会提示私钥解析错误了
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/53910283/164124079-89593fb4-eee2-4d8a-8b25-12f22e31dbb4.png">

**Comment by FUjr** [comment]
我推测会不会和注册地有关，我注册地是中国大陆和香港地区，好像这俩地方都被滥用的很严重

**Comment by fscarmen** [comment]
> 意思是我测试：使用只有ipv4的家宽（广东移动），通过官方客户端（win、Android、macos、linux、iOS）只有linux能顺利连接，其他都是无限转圈。不过结合您的家宽正常连接，我觉得有可能是运营商屏蔽了，而非cf屏蔽中国ip
我这情况如下
1，广东移动和电信家庭宽带，连着wifi，1.1.1.1 app改为teams之后，macos,ios都可以使用
2，广东移动和电信家庭宽带，连着wifi，wireguard app 用提取到的teams信息作配置文件，macos,ios都可以使用
3，广东移动4G网，1.1.1.1 app改为teams之后，ios可以
4，广东移动4G网，wireguard app 用提取到的teams信息作配置文件，ios 不能使用

**Comment by fscarmen** [comment]
> 目前测试使用wireguard连接用wgcf生成的wireguard配置会提示： 2022-04-20 08:28:17.866 [NET] peer(bmXO…fgyo) - Sending handshake initiation 无论是使用hk的机器还是家里的宽带，都是无限卡发送握手初始化信息
> 
> >

我一直重复使用提取出来的teams信息，没有用wgcf generate的了，该信息脚本也附带，可以使用的。

**Comment by fscarmen** [comment]
> 后来用Android studio提取的xml，字段好像改了，已经变成了这样子，复制进wireguard会提示私钥解析错误了

上周我试还是可以的，我找个时间再试试吧

**Comment by touchmii** [comment]
国内阿里云无法连接，只能走CDN中转连接海外服务器，这样保险一点。

**Comment by aeeq** [comment]
很可能是 endpoint ip 不通，换端口看看，除了 2408 还有 500 4500 1701
