### ISSUE TITLE
为什么我TW的VPS，会解锁到HK-【结论：warp 有时候会分配到邻近地区，也就是加入需要解锁地区的目的，就是防止这些跨区】

### ISSUE THREAD

**Issue by hadow** [fscarmen/warp#138]
![微信图片_20220419100529](https://user-images.githubusercontent.com/5329368/163905833-42818906-6442-4c06-bd7c-0269c6b16fd9.png)

昨天还正常的，今天莫名其妙分配到香港的IP节点了，求教怎么切换会台湾地区。。。

**Comment by hadow** [comment]
....又恢复正常了。。。奇怪，可能就cf抽抽了

**Comment by fscarmen** [comment]
是的，如果是tw 你直接用 ```warp i tw``` 强行指定可以了。

**Comment by fscarmen** [comment]
建议用另一个专门的项目的来刷 : https://github.com/fscarmen/warp_unlock
