### ISSUE TITLE
老哥初次运行option好像无效呀

### ISSUE THREAD

**Issue by n0thing2speak** [fscarmen/warp#139]
还是需要选择语言和各种选项

**Comment by fscarmen** [comment]
语言在第一次安装的时候一定要选的，后续快捷方法会以第一次录入为主。
除语言外的所有都能用 option 来完成，README.md 里有说明，不用进主菜单

**Comment by fscarmen** [comment]
> 还是需要选择语言和各种选项

我在使用你的项目，哈哈 [n0thing2speak](https://github.com/n0thing2speak/oracle_arm)

**Comment by n0thing2speak** [comment]
> > 还是需要选择语言和各种选项
> 
> 我在使用你的项目，哈哈 [n0thing2speak/oracle_arm](https://github.com/n0thing2speak/oracle_arm)
> 
> 语言一定要选的，否则默认英文和中文都不好。 当然实在不想选，默认英文，有一个比较暴力的方法
> 
> 默认英文，以 WARP+ license : N5670ljg-sS9jD334-6o6g4M9F 。设备名为 Goodluck 来安装 WARP 双栈
> 
> ```
> echo -e "\n" | bash menu.sh d N5670ljg-sS9jD334-6o6g4M9F Goodluck
> ```

谢谢大佬，你的脚本也超赞，我改了一下哈哈哈
