### ISSUE TITLE
digitalocean机子无法正常获取ip

### ISSUE THREAD

**Issue by stakeswky** [fscarmen/warp#14]
rt

**Comment by fscarmen** [comment]
请问卡在哪个位置呢？能截个图呢吗？
卡在最后获取IP的时候？一直不动？

**Comment by fscarmen** [comment]
今天给位网友处理了个 case ，小鸡是raksmart.com。操作系统老掉牙，我通过以下步骤处理好的
1.重置成 CentOS 7 min
2.下载脚本，菜单选“升级内核、BBR、DD”，或者直接 ``` bash menu.sh b ```，选10 DD 系统为 Ubuntu 20.04，升级需要1.5小时
3.再次``` bash menu.sh b ```，选1 安装BBR原版内核
4.``` bash menu.sh 1 ```，为 IPv4的VPS 添加 Warp IPv6，十分顺利

附图1，能选的系统
<img src="https://user-images.githubusercontent.com/62703343/136685439-64a6ae8d-bc2a-4b95-b8ab-33a45d0b12ac.png" width="40%" />
附图2，完成的截图
<img src="https://user-images.githubusercontent.com/62703343/136685625-2350c941-84e4-4e72-bced-866d56f0631f.png" width="50%" />

**Comment by stakeswky** [comment]
尝试了一下，发现仍然无法正常获取ip；然后今天下午用甲骨文春川的机子试了一下，也遇到了相同的问题。

**Comment by fscarmen** [comment]
> 尝试了一下，发现仍然无法正常获取ip；然后今天下午用甲骨文春川的机子试了一下，也遇到了相同的问题。

下午还没有修好车，刚刚才弄好的，19:00，你看版本是 2.02才是最新的

**Comment by fscarmen** [comment]
你要重新下载脚本

**Comment by stakeswky** [comment]
我尝试的时候用的就是你的最新脚本，我注意到了你上面那个弃wget用curl的更新记录了

**Comment by fscarmen** [comment]
请问你的系统是CentOS 8吗？
之前脚本有处地方没有判断好CentOS7和8，导致有的 CentOS 8 安装不成功，现在已经修改，有机会安装的时候再试试，谢谢反馈。

**Comment by bg3apk2021** [comment]
1.English
 2.简体中文
 Choose language (default is 1.English): 2
 检查环境中…… 
 没有加载 TUN 模块，请在管理后台开启或联系供应商了解如何开启，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
请问你的机器是KVM还是OPENVZ的？

```
cat /dev/net/tun
```
把回显给我
