### ISSUE TITLE
大神，我安装 CloudFlare Client 并设置为 WARP 模式，设置client的时候竟然提示没有cloudflare warp-【结论：不清楚是否越南VPS是否能正常使用client】

### ISSUE THREAD

**Issue by issaceyan** [fscarmen/warp#141]
请选择: 14
 如有 WARP+ License 请输入，没有可回车继续: 
 进度 1/2： 安装 Client…… 
Hit:2 http://deb.debian.org/debian buster InRelease                                                                                          
Hit:3 http://deb.debian.org/debian buster-updates InRelease                                                                                  
Hit:4 http://security.debian.org/debian-security buster/updates InRelease               
Hit:5 http://nginx.org/packages/mainline/debian buster InRelease                        
Hit:1 https://pkg.cloudflareclient.com buster InRelease                          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
21 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lsb-release is already the newest version (10.2019051400).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1688  100  1688    0     0   4220      0 --:--:-- --:--:-- --:--:--  4220
OK
deb http://pkg.cloudflareclient.com/ buster main
Hit:2 http://security.debian.org/debian-security buster/updates InRelease               
Hit:3 http://deb.debian.org/debian buster InRelease                                     
Hit:4 http://deb.debian.org/debian buster-updates InRelease       
Hit:5 http://nginx.org/packages/mainline/debian buster InRelease                                     
Hit:1 https://pkg.cloudflareclient.com buster InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
21 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  desktop-file-utils
The following NEW packages will be installed:
  cloudflare-warp desktop-file-utils
0 upgraded, 2 newly installed, 0 to remove and 21 not upgraded.
Need to get 20.8 MB of archives.
After this operation, 63.5 MB of additional disk space will be used.
Get:2 http://deb.debian.org/debian buster/main amd64 desktop-file-utils amd64 0.23-4 [85.8 kB]
Get:1 https://pkg.cloudflareclient.com buster/main amd64 cloudflare-warp amd64 2022.4.235-1 [20.8 MB]
Fetched 20.8 MB in 2s (13.4 MB/s)                           
Selecting previously unselected package desktop-file-utils.
(Reading database ... 43840 files and directories currently installed.)
Preparing to unpack .../desktop-file-utils_0.23-4_amd64.deb ...

Progress: [  0%] [........................................................................................................................] 
Unpacking desktop-file-utils (0.23-4) ....................................................................................................] 

Selecting previously unselected package cloudflare-warp...................................................................................] 
Preparing to unpack .../cloudflare-warp_2022.4.235-1_amd64.deb ...

Unpacking cloudflare-warp (2022.4.235-1) ...#############.................................................................................] 

Setting up desktop-file-utils (0.23-4) ...#############################...................................................................] 

Progress: [ 56%] [##################################################################......................................................] 
Setting up cloudflare-warp (2022.4.235-1) ...####################################################.........................................] 

Created symlink /etc/systemd/system/multi-user.target.wants/warp-svc.service → /lib/systemd/system/warp-svc.service.......................] 

Processing triggers for man-db (2.8.5-2) ...################################################################################..............] 
Processing triggers for mime-support (3.62) ...
 进度 2/2： 设置 Client 模式 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
Cannot find device "CloudflareWARP"
 第2次尝试 
Cannot find device "CloudflareWARP"
 第3次尝试 
Cannot find device "CloudflareWARP"
 第4次尝试 
Cannot find device "CloudflareWARP"
 第5次尝试 
Cannot find device "CloudflareWARP"
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

请问这样怎么处理

**Comment by issaceyan** [comment]
root@22021914065146issaceyan:~# warp-cli --accept-tos connect
Success
root@22021914065146issaceyan:~# warp-cli --accept-tos enable-always-on
Success
root@22021914065146issaceyan:~# sleep 15
root@22021914065146issaceyan:~# ip -4 rule add from 172.16.0.2 lookup 51820
root@22021914065146issaceyan:~# ip -4 route add default dev CloudflareWARP table 51820
Cannot find device "CloudflareWARP"
root@22021914065146issaceyan:~# ip -4 rule add table main suppress_prefixlength 0


手动也是提示没有"CloudflareWARP"

**Comment by fscarmen** [comment]
看不出问题🤣

**Comment by issaceyan** [comment]
。。。#-#

**Comment by fscarmen** [comment]
VPS 是AMD64？ 同时有独立的 IPv4 吗？

**Comment by issaceyan** [comment]
是的，AMD64,同时有独立的IPV4

**Comment by issaceyan** [comment]
当前操作系统：Debian GNU/Linux 10 (buster)
        内核：5.15.30-bbrplus
        处理器架构：amd64
        虚拟化：kvm 
        IPv4：103.173.255.173  越南  FPT Telecom Company 
        IPv6：     
        WARP 网络接口未开启 
        Client 已安装，模式为:WARP， 断开状态 
        WireProxy 未安装

**Comment by fscarmen** [comment]
试试这样看看状态
```
warp-cli --accept-tos connect
warp-cli --accept-tos status
```

**Comment by issaceyan** [comment]
root@22021914065146issaceyan:~# warp-cli --accept-tos connect
Success
root@22021914065146issaceyan:~# warp-cli --accept-tos status
Status update: Disconnected
Success

**Comment by fscarmen** [comment]
十分奇怪，connect 反馈成功，结果即是 Disconnected 的，不知道与越南有没有关系，你有没有其他地区的 VPS 再试试

**Comment by issaceyan** [comment]
暂时没有呢，真的好怪啊

**Comment by fscarmen** [comment]
十分诡异，我也暂时判断不了哪里出问题。我能想到的有可能是 warp 对越南地区不支持。

**Comment by issaceyan** [comment]
之前香港没挂的时候，其实是可以用的，当时转到了香港的CF

**Comment by issaceyan** [comment]
所以我非常迷糊啊，哭

**Comment by fscarmen** [comment]
> 所以我非常迷糊啊，哭

请问该vps是大陆的吗？

**Comment by issaceyan** [comment]
越南的

**Comment by fscarmen** [comment]
不知道是不是被墙了
