### ISSUE TITLE
DMIT香港在获取IP时ctrl+z退出，脚本无法再次打开-【结论：自从2022年3月3日起香港 wgcf warp 中断服务，截止到2022年5月19日问题仍旧】

### ISSUE THREAD

**Issue by wangsicheng0710** [fscarmen/warp#142]
DMIT香港在获取IP时ctrl+z退出，脚本无法再次打开

**Comment by fscarmen** [comment]
自从2022年3月3日起，香港一直连不上 warp 了，其他亚太地区可以，具体可以在这里查

https://www.cloudflarestatus.com/

**Comment by wangsicheng0710** [comment]
那么更新日志里说的解决香港没有warp的方法是什么

**Comment by fscarmen** [comment]
用 WARP-cli ，并设置为 warp 模式，本地多了个 cloudflare-warp 的网络接口，你香港想通过 warp 的流量，在xray里分流过去 ，配置文件在 README.md 里有
```wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh l```

**Comment by fscarmen** [comment]
最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局
一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)
