### ISSUE TITLE
EUserv 无法安装 WARP

### ISSUE THREAD

**Issue by hmsjy2017** [fscarmen/warp#145]
EUserv 配置 DNS64 不生效，只能访问支持 IPv6 的网站，而 GitHub 不支持 IPv6，导致 wgcf 和 wireguard-go 无法下载。
![Screenshot_20220428_093801](https://user-images.githubusercontent.com/42692274/165675314-35c3836c-a0a7-4cb3-ab24-4bf093736add.jpg)

**Comment by fscarmen** [comment]
上两个月开始，githubusercontent.com 支持双栈了，脚本在要下载的文件也做了 cdn 备选方案处理。你试试用以下两个dns，再刷

第三方的
```
echo -e "nameserver 2a00:1098:2b::1\nnameserver 2a01:4f9:c010:3f02::1\nnameserver 2a01:4f8:c2c:123f::1\nnameserver 2a00:1098:2c::1" > /etc/resolv.conf
```

EUserv官方的
```
echo -e "search blue.kundencontroller.de\noptions rotate\nnameserver 2a02:180:6:5::1c\nnameserver 2a02:180:6:5::4\nnameserver 2a02:180:6:5::1e\nnameserver 2a02:180:6:5::1d" > /etc/resolv.conf
```

**Comment by hmsjy2017** [comment]
CDN timeout 无法下载
![Screenshot_20220428_125424_edit_983347895610967](https://user-images.githubusercontent.com/42692274/165679229-ef631bd7-e3e9-45ec-ba49-4ac5afeef29a.jpg)

**Comment by fscarmen** [comment]
![AB8C3310-D318-4FAD-9E27-A9CAB507140C](https://user-images.githubusercontent.com/62703343/165679613-e038b9bb-2e65-4e9d-ba0c-38a837aa4f3c.jpeg)

这个githubusercontents.com就是支持双栈的cdn了，与githubusercontent.com不同，结尾多个s的

**Comment by hmsjy2017** [comment]
可以了

**Comment by fscarmen** [comment]
> 可以了

请问是什么问题？我刚试了两个下载，都是支持IPv6的，所以我估计是你的 nameserver 出问题，所有网络都解析不了

```
[root@srv17425 ~]# wget -6 -N . https://raw.githubusercontents.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
--2022-04-28 15:30:59--  http://./
Resolving . (.)... failed: Name or service not known.
wget: unable to resolve host address ‘.’
--2022-04-28 15:30:59--  https://raw.githubusercontents.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
Resolving raw.githubusercontents.com (raw.githubusercontents.com)... 2407:d340:f020::6ffe:42f3, 2402:a7c0:8100:a015::b7:b3d8, 2603:c024:4501:8700::cdef, ...
Connecting to raw.githubusercontents.com (raw.githubusercontents.com)|2407:d340:f020::6ffe:42f3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8384512 (8.0M) [application/octet-stream]
Saving to: ‘wgcf_2.2.13_linux_amd64’

100%[=====================================================================================================================================>] 8,384,512   4.04MB/s   in 2.0s   

Last-modified header missing -- time-stamps turned off.
2022-04-28 15:31:03 (4.04 MB/s) - ‘wgcf_2.2.13_linux_amd64’ saved [8384512/8384512]

FINISHED --2022-04-28 15:31:03--
Total wall clock time: 3.3s
Downloaded: 1 files, 8.0M in 2.0s (4.04 MB/s)
[root@srv17425 ~]# wget -6 -N . https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
--2022-04-28 15:31:30--  http://./
Resolving . (.)... failed: Name or service not known.
wget: unable to resolve host address ‘.’
--2022-04-28 15:31:30--  https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8384512 (8.0M) [application/octet-stream]
Last-modified header missing -- time-stamps turned off.
--2022-04-28 15:31:30--  https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
Reusing existing connection to [raw.githubusercontent.com]:443.
HTTP request sent, awaiting response... 200 OK
Length: 8384512 (8.0M) [application/octet-stream]
Saving to: ‘wgcf_2.2.13_linux_amd64’

100%[=====================================================================================================================================>] 8,384,512   --.-K/s   in 0.1s    

2022-04-28 15:31:30 (57.4 MB/s) - ‘wgcf_2.2.13_linux_amd64’ saved [8384512/8384512]

FINISHED --2022-04-28 15:31:30--
Total wall clock time: 0.7s
Downloaded: 1 files, 8.0M in 0.1s (57.4 MB/s)

**Comment by hmsjy2017** [comment]
> > 可以了
> 
> 请问是什么问题？我刚试了两个下载，都是支持IPv6的，所以我估计是你的 nameserver 出问题，所有网络都解析不了
> 
> ```
> [root@srv17425 ~]# wget -6 -N . https://raw.githubusercontents.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
> --2022-04-28 15:30:59--  http://./
> Resolving . (.)... failed: Name or service not known.
> wget: unable to resolve host address ‘.’
> --2022-04-28 15:30:59--  https://raw.githubusercontents.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
> Resolving raw.githubusercontents.com (raw.githubusercontents.com)... 2407:d340:f020::6ffe:42f3, 2402:a7c0:8100:a015::b7:b3d8, 2603:c024:4501:8700::cdef, ...
> Connecting to raw.githubusercontents.com (raw.githubusercontents.com)|2407:d340:f020::6ffe:42f3|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 8384512 (8.0M) [application/octet-stream]
> Saving to: ‘wgcf_2.2.13_linux_amd64’
> 
> 100%[=====================================================================================================================================>] 8,384,512   4.04MB/s   in 2.0s   
> 
> Last-modified header missing -- time-stamps turned off.
> 2022-04-28 15:31:03 (4.04 MB/s) - ‘wgcf_2.2.13_linux_amd64’ saved [8384512/8384512]
> 
> FINISHED --2022-04-28 15:31:03--
> Total wall clock time: 3.3s
> Downloaded: 1 files, 8.0M in 2.0s (4.04 MB/s)
> [root@srv17425 ~]# wget -6 -N . https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
> --2022-04-28 15:31:30--  http://./
> Resolving . (.)... failed: Name or service not known.
> wget: unable to resolve host address ‘.’
> --2022-04-28 15:31:30--  https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 8384512 (8.0M) [application/octet-stream]
> Last-modified header missing -- time-stamps turned off.
> --2022-04-28 15:31:30--  https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.13_linux_amd64
> Reusing existing connection to [raw.githubusercontent.com]:443.
> HTTP request sent, awaiting response... 200 OK
> Length: 8384512 (8.0M) [application/octet-stream]
> Saving to: ‘wgcf_2.2.13_linux_amd64’
> 
> 100%[=====================================================================================================================================>] 8,384,512   --.-K/s   in 0.1s    
> 
> 2022-04-28 15:31:30 (57.4 MB/s) - ‘wgcf_2.2.13_linux_amd64’ saved [8384512/8384512]
> 
> FINISHED --2022-04-28 15:31:30--
> Total wall clock time: 0.7s
> Downloaded: 1 files, 8.0M in 0.1s (57.4 MB/s)
> ```

504 Gateway Timeout 
可能是 CDN 故障
