### ISSUE TITLE
切换优先级

### ISSUE THREAD

**Issue by RatedR9** [fscarmen/warp#146]
第一次安装选了ipv4优先级如何再次修改优先级
执行warp后
![image](https://user-images.githubusercontent.com/62322670/167138654-cb4989df-a631-417b-beb2-9a18d6aa0183.png)

**Comment by fscarmen** [comment]
暂时没有像 warp IPv4, IPv6, Dual-stack 那样做快速切换方案。看你安装了 WireProxy，分流主要在xray,v2ray配置文件里完成的。

**Comment by RatedR9** [comment]
> 暂时没有像 warp IPv4, IPv6, Dual-stack 那样做快速切换方案。看你安装了 WireProxy，分流主要在xray,v2ray配置文件里完成的。

主要目的是探针 ， 一开始好像选了个warp ipv4优先 本身是v6 only鸡， 探针服务端面板可以装但是控机装不上

**Comment by RatedR9** [comment]
> > > 暂时没有像 warp IPv4, IPv6, Dual-stack 那样做快速切换方案。看你安装了 WireProxy，分流主要在xray,v2ray配置文件里完成的。
> > 
> > 
> > 主要目的是探针 ， 一开始好像选了个warp ipv4优先 本身是v6 only鸡， 探针服务端面板可以装但是控机装不上
> 
> 没有影响的啊，如果你是同一台vps的客户端，可以填 127.0.0.1 如果是其他vps，这些vps需要有 ipv6 的ip，又或者安装warp 有 ipv6，之后填服务端的信息填你那台 ipv6 only 服务端的 IPv6 或者AAAA解析的域名也行。 所以与v4 v6优先无关的。

原来如此 ！
