### ISSUE TITLE
无法更换ip

### ISSUE THREAD

**Issue by DEabcdp** [fscarmen/warp#148]
warp换到的ip（ipv4）被封了，因为我是全局代理，所以百度都连不上。而且warp i更换换到的一直是原来的ip（ipv4），不知道到底应该怎么换。我换成设置默认ipv6了。不过想问问ipv4这种情况应该怎么办？

**Comment by fscarmen** [comment]
warp i 更换ip的时候会断网的，如果你用于全局的话会出问题的。但不太清楚为什么你用了 warp IPv4 之后 ，换来换去却显示原来vps的 IPv4。
你这个情况，要不分两个vps。一个用于科学，一个用于流媒体。又或者同一台 VPS，选用 WireProxy 、Client WARP模式、unlock docker 这些方案，并在xray配置文件里设置分流，到这些socks5或者warp 网络接口

**Comment by DEabcdp** [comment]
> warp i 更换ip的时候会断网的，如果你用于全局的话会出问题的。但不太清楚为什么你用了 warp IPv4 之后 ，换来换去却显示原来vps的 IPv4。 你这个情况，要不分两个vps。一个用于科学，一个用于流媒体。又或者同一台 VPS，选用 WireProxy 、Client WARP模式、unlock docker 这些方案，并在xray配置文件里设置分流，到这些socks5或者warp 网络接口

我刚刚重新安装脚本，开启Client WARP模式后，然后卸载脚本，不知道怎么的，现在安装一直卡在检查环境这里：

Last-modified header missing -- time-stamps turned off.
2022-05-07 17:55:08 (60.8 MB/s) - ‘menu.sh’ saved [107199/107199]


 Language:
  1.English (default)
  2.简体中文

 Choose: 2
 检查环境中……

**Comment by fscarmen** [comment]
`bash -x menu.sh` 看卡在哪？

**Comment by DEabcdp** [comment]
感谢已解决

**Comment by fscarmen** [comment]
> 感谢已解决

什么情况？

**Comment by DEabcdp** [comment]
> > 感谢已解决
> 
> 什么情况？

我等了几分钟检查环境后出来了，看样子Client WARP已开启，但是warp什么的是关的，ipv4地址也是空的，不知道为啥，我重新开了双栈就好了。
