### ISSUE TITLE
好奇问一下，看cloudflarestatus这里面有不少国内节点，是否可以搞个ip代理池？

### ISSUE THREAD

**Issue by scoful** [fscarmen/warp#149]
RT

**Comment by fscarmen** [comment]
之前用提取到的teams信息连wireguard，是8开始的美国IPv4，速度很可以的，白嫖不花钱，手机pc都可以。自从加了104.28这段，显示的WARP IP虽然是中国，但已慢到令人发指。
具体你想如何玩？

**Comment by scoful** [comment]
就是常规的ip代理池，用于爬虫之类的，可以控制每次获取的ip都是变化的

**Comment by scoful** [comment]
当然这样子的需求就跟这个项目的目的不一样了，我是想知道有没有这个可能性，可以做成ip代理池？
大佬你这个项目按我的初步理解是为了刷到一个外区ip，然后伪装代理，可以看流媒体，这个追求稳定ip，而如果是ip代理池，那就是另一面，变化的，可控的。
担心点：
1. 没法自由切换ip
2. 没法选择区域
3. 速度

**Comment by fscarmen** [comment]
【摘选】人民网评：对“秒拨IP”黑产必须露头就打！
蒋萌
2022年01月18日10:06 | 来源：[人民网-观点频道](http://opinion.people.com.cn/)
电信诈骗、网络赌博、网络水军……在这些严重危害网络安全的违法犯罪行为背后，有一批人正悄然为其打造“地基”，利用所谓的“秒拨IP”服务，为违法犯罪提供便利。云南近期破获一起“秒拨IP”黑产案，使这一新型犯罪“浮出水面”。

“秒拨IP”黑产涉及“IP地址”这一概念。简单说来，互联网好比一个虚拟世界，要想在数以亿计的联网电脑中找到特定的一台，需要一个唯一的地址——“IP地址”。而“秒拨IP”，就是不法分子利用家用宽带上网每次断线重连都会获取一个新“IP地址”的原理，租用大量家用宽带线路，瞬间制造百万量级的“IP地址”，形成“IP池”，将其提供给网络犯罪团伙使用。“秒拨IP”制造的海量IP地址绕开了正常的IP限制，给警方追查网络犯罪带来很大障碍，被犯罪分子利用以逃避打击。说白了，这就是“助纣为虐”的卑鄙勾当。

新型犯罪往往有着隐蔽性高、技术手段先进等特点。据媒体报道，该犯罪团伙的“反侦查意识之强、技术手段之高”，令警方坦言“从未遇到过”。为了掩人耳目，犯罪窝点的外观十分简陋。然而，其内部却集中了许多高科技设备：门口设置门禁报警系统，有人闯入手机马上就会提示；房间内安装360度远程智能监控摄像头；电脑使用遥控WIFI智能插座，随时可以自动重启虚拟服务器并将电脑格式化……犯罪分子费尽心思监控，就是为了反侦查，一旦发现风吹草动，电脑就会被格式化，罪证将被销毁，如此机关算尽，丑恶狡猾可见一斑。

原文链接：http://opinion.people.com.cn/n1/2022/0118/c223228-32334029.html
