### ISSUE TITLE
建议在安装脚本前置检查curl是否安装-【结论：2.03已有curl命令的检测，没有的话会安装】

### ISSUE THREAD

**Issue by SoraKasvgano** [fscarmen/warp#15]
纯IPV6的机子新系统没有curl
会导致 curl命令找不到死循环
同时由于已经改变网络环境，主机无法解析原IPV6 下的HOST，无法使用apt 手动安装curl

**Comment by fscarmen** [comment]
谢谢你的反馈，这个问题已经收到
最新的 V2.02 我在一开始检查系统状态的时候的时候加入 curl 的检测，没有的话会安装，这时vps还处于原来的网络状态，所以应该是能安装到的，具体如下
# 安装 curl
[[ ! $(type -P curl) ]] && green " 安装curl中…… " && (apt -y install curl >/dev/null 2>&1 || yum -y install curl >/dev/null 2>&1 )

另外我已经在2.03对刷网络作了优化，加快了两次尝试之间的间隔时间，不会出现死循环，因为已经限制次数，暂停为10次，有明确的提示

现还在观察替代 WireGuard-GO 的 BoringTun 是否稳定，可以的话，我今晚更新上去。
如果你着急使用的话，可以用
wget --no-check-certificate -N -O ~/menu.sh https://raw.githubusercontent.com/fscarmen/warp/main/old/t.sh
接着用原来的命令
