### ISSUE TITLE
mac 的 WARP 一键脚本

### ISSUE THREAD

**Issue by JinYuJia13** [fscarmen/warp#150]
<img width="724" alt="12312312" src="https://user-images.githubusercontent.com/51956530/167849193-42725b3c-c333-4b34-9397-9800fbdce492.png">
mac 的 WARP 一键脚本，我是 m1 版本的 mac，系统是最新的

**Comment by fscarmen** [comment]
终端是不是 zsh?

**Comment by fscarmen** [comment]
你看看文件的第一行是不是上面那行？

**Comment by JinYuJia13** [comment]
> 你看看文件的第一行是不是上面那行？
<img width="962" alt="65656" src="https://user-images.githubusercontent.com/51956530/167893866-d4ccf0de-b140-40ce-a6cd-c0b7b211c99e.png">
在文件夹中无法找到，但是我可以按回车之后在文件夹中会有mac.sh

**Comment by JinYuJia13** [comment]
> #!/usr/bin/env bash
<img width="1437" alt="7777777" src="https://user-images.githubusercontent.com/51956530/167895048-77645b2b-e1bd-4f65-a19f-e0f10e1b3f85.png">
不好意思刚刚看错文件夹了，有这个文件

**Comment by fscarmen** [comment]
你用 root 用户吗？可以用系统的用户，不需要sudo -i 的。不过报错不是那个原因，报错是那个 申明关连数组的 declare 不能正常使用，原因没有使用到 bash ，我要找找方法。

**Comment by fscarmen** [comment]
我这里的 amd64 的可以。你看看 ```bash -v ``` 显示什么版本的
<img width="570" alt="image" src="https://user-images.githubusercontent.com/62703343/167896319-de83c798-9011-4a48-b652-d950ff9052f8.png">

**Comment by JinYuJia13** [comment]
> bash -v
<img width="633" alt="9999" src="https://user-images.githubusercontent.com/51956530/167896545-6e02ccfc-29ee-478f-95b9-ae2f328b03ee.png">

**Comment by JinYuJia13** [comment]
> 我那个是5.1 ，你那里是 3.2，可能是这个原因，往升级bash 这个方向，因为我手提原因，不能像vps那样可以无限重置，所以有点东西可能我在之前已经无意中安装了。

好的我找资料看看能不能升级

**Comment by fscarmen** [comment]
一定可以的，等你好消息，我也只能谷歌百度，没有机器试，兄弟靠你了

**Comment by JinYuJia13** [comment]
> 厉害啊，刷成功了吗？或者我加个判断bash版本过低，先升级

但是还是有点小问题

**Comment by fscarmen** [comment]
你这样运行，能看到哪里出问题的，方便截图
```bash -x mac.sh```

**Comment by JinYuJia13** [comment]
> 你这样运行，能看到哪里出问题的，方便截图 `bash -x mac.sh c`
<img width="733" alt="1111" src="https://user-images.githubusercontent.com/51956530/167909613-db3ce632-7ce1-41c5-b80c-d6cf39eb8a21.png">
<img width="727" alt="123123212287" src="https://user-images.githubusercontent.com/51956530/167909629-4c51f0d1-ddfb-4a6f-be07-0772d8660917.png">
还是报错

**Comment by JinYuJia13** [comment]
> bash -x mac.sh c
<img width="745" alt="99999234" src="https://user-images.githubusercontent.com/51956530/167917017-748474a2-4af2-4115-a2b3-3b8e299d3d6a.png">
bash --version
GNU bash，版本 5.1.16
(没有修改mac.sh 文件也是报一样的错误)
#!/opt/homebrew/bin/bash
echo $BASH_VERSION

**Comment by fscarmen** [comment]
加我tg沟通呢？及时一点 https://t.me/fscarmen2

**Comment by JinYuJia13** [comment]
已经解决
