### ISSUE TITLE
机器人不推送日志-【结论：经多次测试没有问题，请用户正确填写token和userid】

### ISSUE THREAD

**Issue by wangsicheng0710** [fscarmen/warp#151]
机器人不推送日志
正确填写token和userid但不推送日志

**Comment by JinYuJia13** [comment]
我昨天可以推送，今天不知道

**Comment by fscarmen** [comment]
刚试了一下，是可以的
<img width="603" alt="image" src="https://user-images.githubusercontent.com/62703343/168114406-f58822d1-c288-4019-913f-b898560f31d3.png">

**Comment by wangsicheng0710** [comment]
能指导一下咋弄吗

**Comment by fscarmen** [comment]
> 能指导一下咋弄吗

TG bot 创建方法
转自 北纬37度的大飛 [如何申请Telegram机器人 | 推送通知](https://w37fhy.cn/2364.html)
