### ISSUE TITLE
Client 和 WireProxy 突然变成断开连接状态，重新连接也不起作用

### ISSUE THREAD

**Issue by hadow** [fscarmen/warp#153]
![image](https://user-images.githubusercontent.com/5329368/168756714-b1460e58-021d-46b1-9f6e-4c873859d535.png)

**Comment by fscarmen** [comment]
你试试卸载后再逐个安装看看什么情况？

**Comment by fscarmen** [comment]
长时间未见反馈，先行 Close，遇到问题随时来提。
