### ISSUE TITLE
创建 Socks 代理失败-【结论：用户的甲骨文 Ubuntu 18.04 没有 ping 指令，通过 `apt -y install inetutils-ping` 安装后恢复正常】

### ISSUE THREAD

**Issue by wenfxl** [fscarmen/warp#154]
进度 2/2： 设置代理模式
创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp/issues]

使用ubuntu18.04和ubuntu16.04、centos7都是提示这个错误，不知道什么原因。

**Comment by fscarmen** [comment]
是ipv6的机器，你加了warp ipv4吗？

**Comment by wenfxl** [comment]
我是运行脚本后，按数字 【5 安装 CloudFlare Client 并设置为 Proxy 模式】 这个选项进行安装的。就出现报错
![1](https://user-images.githubusercontent.com/28726830/169176983-78f3a7af-e0d0-4cf1-94a0-0e28d5fd33e5.jpg)

出现报错后，我重新运行脚本，在选择【13 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理】这个可以使用

**Comment by fscarmen** [comment]
要进去机器排查一下才知道，什么系统和版本，什么架构？
如果wireproxy能用，他比client的proxy模式要强的

**Comment by wenfxl** [comment]
![1](https://user-images.githubusercontent.com/28726830/169181977-e556eed5-9700-46c9-8830-6a8692501d6a.jpg)
![2](https://user-images.githubusercontent.com/28726830/169182004-30f1404d-8af4-407a-a598-27e3a5ba6bdf.jpg)

**Comment by fscarmen** [comment]
> 难道是因为国内机器的原因吗

我想破案了

**Comment by wenfxl** [comment]
![image](https://user-images.githubusercontent.com/28726830/169630693-be53d9ad-7273-497f-a409-06f67ecf4057.png)

**Comment by fscarmen** [comment]
最后一个 status 一直是 Connecting 即是不通啊，你是不是 IPv4 是 WARP的？你再输入看看
```
curl -s4m8 https://ip.gs/json
curl -s4m8 ip.sb
```

**Comment by wenfxl** [comment]
最后一个status不是显示了Success么。这两条命令执行完显示的是IPv4的ip地址

**Comment by fscarmen** [comment]
那个 Success 不代表成功的，是个坑。真成功的话如图

<img width="343" alt="image" src="https://user-images.githubusercontent.com/62703343/169634221-905875f0-adc5-4520-a7d5-0973619d6adb.png">

判断你的国内鸡有墙，不让连

**Comment by wenfxl** [comment]
那应该是的啊  我本地服务器肯定连不上外网

**Comment by fscarmen** [comment]
> 那应该是的啊 我本地服务器肯定连不上外网

我想办法加个判定进去，遇到连不上的就提前告知

**Comment by wenfxl** [comment]
难道创建socks5代理失败就是国内的原因，只能国外鸡才能创建成功。
如果13和5、14是两个不同的体系的话，我是不是安装开始只用选择13就够了。

**Comment by fscarmen** [comment]
是的，13在国内鸡可以连的

**Comment by wenfxl** [comment]
好的，感谢你的耐心解答。

**Comment by wenfxl** [comment]
我刚用国外鸡试了一下，提示Client 在非 WARP IPv4 下才能工作正常，脚本中止，这是什么原因。新系统18.0.4
![image](https://user-images.githubusercontent.com/28726830/169643585-33ed88e6-43fa-47c9-a7c2-20b6cf3fef79.png)
![image](https://user-images.githubusercontent.com/28726830/169643599-16136866-bccd-4cd1-ab0c-21967647a88a.png)

**Comment by fscarmen** [comment]
检测不到任何 ip 信息，导致脚本误差。你手动运行一个上面的两条指令，看是否能正确获致到vps的 ipv4，甲骨文我大量试的，不可能存在问题啊

**Comment by wenfxl** [comment]
能正常获取到IPV4啊，奇怪了

**Comment by fscarmen** [comment]
我看你上面的界面就没有获取到

**Comment by wenfxl** [comment]
就是脚本没法获取到 我用这两句命令是能获取到的
`curl -s4m8 https://ip.gs/json
curl -s4m8 ip.sb`

**Comment by fscarmen** [comment]
真的判断不了，你方便的话，改个ssh 密码，我进去看看
```
bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/tools/main/root.sh) 
```

https://t.me/fscarmen2

**Comment by wenfxl** [comment]
tg发给你了 你帮我看看

**Comment by fscarmen** [comment]
破案了，该Oracle Ubuntu 18.04 居然没有 ping 指令，安装后正常使用

```
apt -y install inetutils-ping
```

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/62703343/169662355-7e53d7ae-71ae-4011-af29-d686c14a27dd.png">
