### ISSUE TITLE
创建 Socks5 代理失败-【结论：CentOS 7 官方是不支持使用 Client，后面我处理了 Glibc 2.28 的运行库，但不sure其兼容所有版本的 CentOS 7.X，可以的话建议更换系统解决】

### ISSUE THREAD

**Issue by Jackliang9090** [fscarmen/warp#156]
请选择: 5
 如有 WARP+ License 请输入，没有可回车继续: 
 请自定义 Client 端口号 (必须为4-5位自然数，如果不输入，会默认40000): 
 进度 1/2： 安装 Client…… 
--2022-05-28 10:12:36--  https://github.com/fscarmen/warp/raw/main/Client/Client_CentOS_8.rpm
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
error: Failed dependencies:
        nftables is needed by cloudflare-warp-2022.4.235-1.x86_64
Failed to start warp-svc.service: Unit warp-svc.service not found.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/fscarmen/warp/main/Client/Client_CentOS_8.rpm [following]
--2022-05-28 10:12:36--  https://raw.githubusercontent.com/fscarmen/warp/main/Client/Client_CentOS_8.rpm
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20568126 (20M) [application/octet-stream]
Saving to: ‘Client_CentOS_8.rpm’

Client_CentOS_8.rpm                            100%[==================================================================================================>]  19.62M  78.3MB/s    in 0.3s    

2022-05-28 10:12:37 (78.3 MB/s) - ‘Client_CentOS_8.rpm’ saved [20568126/20568126]

 进度 2/2： 设置 Client 模式 
 创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp/issues] 
我该怎么解决这个问题呢

**Comment by fscarmen** [comment]
输入两个，把结果发上来看看

```
warp-cli --accept-tos status
warp-cli --accept-tos settings
```

**Comment by GF157** [comment]
warp-cli: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by warp-cli)

我也遇到了这个问题，想问下安装client需要很久吗，我安装时gcc跑了半天...

**Comment by fscarmen** [comment]
> warp-cli: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by warp-cli)
> 
> 我也遇到了这个问题，想问下安装client需要很久吗，我安装时gcc跑了半天...

CentOS 7 官方本来不支持，通过升级 Glibc 可以运行，但也有部分仍然不成功。建议换成 C8, Debian 或者 Ubuntu
