### ISSUE TITLE
[wireproxy] ip public from wireproxy changes too much.

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#157]
it's create more trouble, e.g you'are accessing hosting sites/cpanel and etc.

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/124

fuck 104.28.***.***

**Comment by malikshi** [comment]
> #124
> 
> fuck 104.28.***.***

Are you didn't get that IP?
I didn't know everytime using wireguard wgcf get 8.*.***.*** but wireproxy always 104.Xxx.xxx

**Comment by fscarmen** [comment]
> > #124
> > fuck 104.28._**.**_
> 
> Are you didn't get that IP? I didn't know everytime using wireguard wgcf get 8._._**.*** but wireproxy always 104.Xxx.xxx

Yes .  I think that 104.28 is mush worst than 8.\*

**Comment by malikshi** [comment]
I wouldn't says that, it just changes too much and make it worse for certain cases . i recommend wireguard wgcf either global or non global routing, it's better for my case.

**Comment by fscarmen** [comment]
> I wouldn't says that, it just wireproxy changes too much and make it worse for certain cases . i recommend wireguard wgcf either global or non global routing, it's better for my case.

You mean wireproxy works badly with 104.28 CIDR changing very fast. So you recommend wireguard wgcf either global or non global routing.

I rarely use the wireproxy solution so can't come to this conclusion. Thanks for your comments.
