### ISSUE TITLE
纯ipv6服务器无法套上warp-【结论：香港暂时使用不了warp，可以选择 Client 的两个方案或者只能换地区了】

### ISSUE THREAD

**Issue by yangnengxuan** [fscarmen/warp#158]

**Comment by yangnengxuan** [comment]
Version：2.36  New features：1. First publication on a global scale. Wireguard client that exposes itself as a socks5 proxy; 2. WARP+ and Teams can be used in WireProxy
 System infomation：
	Operating System：Ubuntu 20.04.1 LTS
	Kernel：5.4.0-47-generic
	Architecture：amd64
	Virtualization：kvm 
	IPv4：45.129.10.255  Hong Kong  Cloudie Limited 
	IPv6：2404:8c80:0:1011:f3:e93e:f2bc:8bf8  Hong Kong  Cloudie Limited 
	WARP Interface is off 
	Client is not installed. 
	WireProxy is not installed. 

======================================================================================================================

 1.  Switch WARP dualstack to WARP IPv4
 2.  Switch WARP dualstack to WARP IPv6
 3.  Upgrade to WARP+ or Teams account
 4.  Turn off WARP
 5.  Install WARP Client for Linux and Proxy Mode
 6.  Change the WARP IP to support Netflix
 7.  Turn off, uninstall WARP interface, Linux Client and WireProxy
 8.  Getting WARP+ quota by scripts
 9.  Upgrade kernel, turn on BBR, change Linux system 
 10. Sync the latest version
 11. Professional one-click script for WARP to unblock streaming media (Supports multi-platform, multi-mode and TG push)
 12. Install iptable + dnsmasq + ipset. Let WARP only take over the streaming media traffic (Not available for ipv6 only)
 13. Install wireproxy. Wireguard client that exposes itself as a socks5 proxy or tunnels
 0. Exit

**Comment by yangnengxuan** [comment]
Maximum 5 attempts to get WARP IP...
五次都无法安装

**Comment by fscarmen** [comment]
两个问题：
1. 从脚本版本 2.36来看，你用那个指令已经过期很久，那个jsDelivr CDN 已经失效。现在你需要用以下的
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh
```

2. 从vps 归属地 Hong Kong 来看，现在香港没有 WGCF warp 服务，你可以换成 Client 的 warp 模式（菜单14项）

**Comment by fscarmen** [comment]
最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局
一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)
