### ISSUE TITLE
arm不支持么？

### ISSUE THREAD

**Issue by langhun** [fscarmen/warp#159]
我的甲骨文东京arm

![image](https://user-images.githubusercontent.com/3387983/170888546-7751bf5f-4136-4f8d-8698-664a731a50eb.png)

**Comment by fscarmen** [comment]
是的，官方暂未支持，支持系统和架构列表可看
我增加了centos7和ubuntu22.04的支持，但都是amd64的
https://pkg.cloudflareclient.com/packages/cloudflare-warp

**Comment by langhun** [comment]
> 是的，官方暂未支持，支持系统和架构列表可看 我增加了centos7和ubuntu22.04的支持，但都是amd64的 https://pkg.cloudflareclient.com/packages/cloudflare-warp

好的，感谢你的回答！

**Comment by fscarmen** [comment]
> 好的，感谢你的回答！

感谢反馈，我将把官方的支持列表信息加到提示那那，同时在菜单的选项上明确前置提示不能安装。减少用户的问题。

**Comment by fscarmen** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/62703343/171077946-915633e7-6bfb-4af2-b233-4b619f929c48.png">
