### ISSUE TITLE
socks5服务局域网无法访问

### ISSUE THREAD

**Issue by mhqschen** [fscarmen/warp#160]
对这个不了解。是因为监听到127.0.0.1:40000而不是0.0.0.0:40000么？
想问下怎么修改？或者有没有别的方式解决这个问题。想让局域网内的机器都走warp出国。

**Comment by fscarmen** [comment]
> 是因为监听到127.0.0.1:40000而不是0.0.0.0:40000么？

只能为本地服务啊，所以是127.0.0.1，不能对外服务，好不是监听所有的 IPv4 0.0.0.0。
README里有使用 *ray ，把本地某些指定流量分流过去的配置模板。


> 想让局域网内的机器都走warp出国。

你指的局域网的机器是什么操作系统的？

**Comment by mhqschen** [comment]
openwrt的路由器，通过上面的插件透明代理，本来想把这个socks5作为一个节点，这样局域网里的机器都能根据插件的规则走这个代理了。但是发现插件无法访问脚本开的这个socks5。

**Comment by fscarmen** [comment]
在openwrt安装个v2ray，分流过去可以吗？

**Comment by mhqschen** [comment]
修改了下menu.sh里监听的地址，改成0.0.0.0，搞定了

**Comment by fscarmen** [comment]
> 修改了下menu.sh里监听的地址，改成0.0.0.0，搞定了

你的 openwrt 是什么 cpu 架构的？透明代理的插件是哪个？这么好玩教下。你是用 wireproxy 的吗？还是 client?

**Comment by fscarmen** [comment]
即是在局域网里的 nas 里虚拟了 debian ，在上面安装 client 或者 wireproxy ，把原本是监听本机的 127.0.0.1 改为全部 IPv4 的 0.0.0.0，之后 k2p openwrt 使用 overalll 插件，nas 上的服务做成一个socks5。这样局域网里或者外网（有公网或者内网穿透服务）的其他终端通过这个socks5的节点访问外网？

端终 ( socks5 )---> openwrt overwall ---> nas debian wireproxy ---> cloudflare ---> out?

**Comment by mhqschen** [comment]
对的。中间这个openwrt overwall 有很多别的替代方式，反正就是把socks5转换成透明代理。

外网访问的话，甚至把40000端口映射后，可以直接外网终端---> nas debian wireproxy ---> cloudflare ---> out
当然这样太不安全了，我也就临时用过几次，还是转换成其他协议后出去比较好。

**Comment by fscarmen** [comment]
> 对的。中间这个openwrt overwall 有很多别的替代方式，反正就是把socks5转换成透明代理。
> 
> 外网访问的话，甚至把40000端口映射后，可以直接外网终端---> nas debian wireproxy ---> cloudflare ---> out 当然这样太不安全了，我也就临时用过几次，还是转换成其他协议后出去比较好。

BindAddress = 127.0.0.1:40000 
wireproxy 在把这里的 127.0.0.1 改为 0.0.0.0？

client 默认是 127.0.0.1 的，你会改吗？

**Comment by mhqschen** [comment]
> > 对的。中间这个openwrt overwall 有很多别的替代方式，反正就是把socks5转换成透明代理。
> > 外网访问的话，甚至把40000端口映射后，可以直接外网终端---> nas debian wireproxy ---> cloudflare ---> out 当然这样太不安全了，我也就临时用过几次，还是转换成其他协议后出去比较好。
> 
> BindAddress = 127.0.0.1:40000 wireproxy 在把这里的 127.0.0.1 改为 0.0.0.0？
> 
> client 默认是 127.0.0.1 的，你会改吗？

哪会呀~我是三脚猫中的三脚猫……
我想到的一个曲线救国的办法就是在本地再开一个支持链式代理的服务，比如v2ray。配置前置代理为client的socks5。

**Comment by mhqschen** [comment]
> > 对的。中间这个openwrt overwall 有很多别的替代方式，反正就是把socks5转换成透明代理。
> > 外网访问的话，甚至把40000端口映射后，可以直接外网终端---> nas debian wireproxy ---> cloudflare ---> out 当然这样太不安全了，我也就临时用过几次，还是转换成其他协议后出去比较好。
> 
> BindAddress = 127.0.0.1:40000 wireproxy 在把这里的 127.0.0.1 改为 0.0.0.0？
menu.sh里有3个地方是127.0.0.1，把和wireproxy相关的第一第三个改了就能用。想好好改的话，还有些检测的地方也得改一下，比如本地socks5代理的地址那里

**Comment by fscarmen** [comment]
> > BindAddress = 127.0.0.1:40000 wireproxy 在把这里的 127.0.0.1 改为 0.0.0.0？
> 
> menu.sh里有3个地方是127.0.0.1，把和wireproxy相关的第一第三个改了就能用。想好好改的话，还有些检测的地方也得改一下，比如本地socks5代理的地址那里

client 你有办法弄成0.0.0.0吗？

**Comment by mhqschen** [comment]
> 哪会呀~我是三脚猫中的三脚猫……
> 我想到的一个曲线救国的办法就是在本地再开一个支持链式代理的服务，比如v2ray。配置前置代理为client的socks5。

我上面回答你啦。不会修改。不过应该有类似工具可以转发，比如v2ray，具体我也没试过。
局域网设备---路由器透明代理插件---虚拟机v2ray server---虚拟机client socks5---cloudflare---外网
外网设备---路由器端口转发---虚拟机v2ray server---虚拟机client socks5---cloudflare---外网
