### ISSUE TITLE
cloudflare client warp模式和无法持久化

### ISSUE THREAD

**Issue by xu-zheng-hao** [fscarmen/warp#161]
**首先是warp模式的问题：**
不知道是否是机器是个人的原因，出现问题的这台是azure的香港机器，使用Ubuntu20.04，首先是warp模式的问题，在使用warp模式时，脚本的IPv4确实会显示warp的ip，不过尝试curl myip.ipip.net后，仍是本机ip，或者尝试运行流媒体测试脚本，也是没被代理，所以只能换成proxy模式
**其次是持久化的问题：**
想到持久化，我一开始想到的就是screen啊之类的，不过尝试后，仍旧发现无法持久化，在断开ssh连接后，还是会断开连接，只能执行warp r进行重连，我还考虑了手动开启永久连接warp-cli enable-always-on，也是不行

**Comment by fscarmen** [comment]
> **首先是warp模式的问题：**
> 不知道是否是机器是个人的原因，出现问题的这台是azure的香港机器，使用Ubuntu20.04，首先是warp模式的问题，在使用warp模式时，脚本的IPv4确实会显示warp的ip，不过尝试curl myip.ipip.net后，仍是本机ip，或者尝试运行流媒体测试脚本，也是没被代理，所以只能换成proxy模式

你只用 curl myip.ipip.net，不行的，第1.ipip.net是托管在CF的。所以能穿透获取真实IP的，你可以通过网址后面加入 `/cdn-cgi/trace` 来通过浏览器访问 ，有信息说明是托管在CF，如 `https://myip.ipip.net/cdn-cgi/trace`。第2.改为 curl -s4m5 --interface CloudflareWARP ip.gs 让他强制走 Client 的网络接口。

> 尝试运行流媒体测试脚本

在 warp 模式下，除了vps原生的网络接口，还多了个 CloudflareWARP 的网络接口，你可以通过 `ip a` 查到。那些脚本根本不可能查到的，因为只会测你 vps 原生的网络接口。至于解锁，你可以配合兄弟脚本来处理  https://github.com/fscarmen/warp_unlock

> 规则持久化

请安装  iptabels-persistent，又或者 `service iptables save` 和 `iptables-restore`。详细请谷歌

**Comment by xu-zheng-hao** [comment]
myip.ipip.net貌似是腾讯云的cdn，不过还是感谢对我的小白问题的回答，warp模式的问题已经解决了，万分感谢

**Comment by fscarmen** [comment]
> myip.ipip.net貌似是腾讯云的cdn

可能是合作伙伴吧🤣

感谢你的使用和支持。

**Comment by GreenTeodoro839** [comment]
> 你只用 curl myip.ipip.net，不行的，第1.ipip.net是托管在CF的。所以能穿透获取真实IP的，你可以通过网址后面加入 `/cdn-cgi/trace` 来通过浏览器访问 ，有信息说明是托管在CF，如 `https://myip.ipip.net/cdn-cgi/trace`。第2.改为 curl -s4m5 --interface CloudflareWARP ip.gs 让他强制走 Client 的网络接口。

#167 
尝试该命令为warp ip，且用 curl -s4m5 --interface CloudflareWARP https://www.cloudflare.com/cdn-cgi/trace/ 可以得到warp=on，但直接 curl ip.gs 得到的为原来的ip，且 curl https://www.cloudflare.com/cdn-cgi/trace/ 得到warp=off

**Comment by fscarmen** [comment]
> 
> #167 尝试该命令为warp ip，且用 curl -s4m5 --interface CloudflareWARP https://www.cloudflare.com/cdn-cgi/trace/ 可以得到warp=on，但直接 curl ip.gs 得到的为原来的ip，且 curl https://www.cloudflare.com/cdn-cgi/trace/ 得到warp=off

就是要这个 warp 非全局的效果呀，你通过v2ray分流，可以让那些流量走原生网络，那些流量走warp网络。

**Comment by GreenTeodoro839** [comment]
> > #167 尝试该命令为warp ip，且用 curl -s4m5 --interface CloudflareWARP https://www.cloudflare.com/cdn-cgi/trace/ 可以得到warp=on，但直接 curl ip.gs 得到的为原来的ip，且 curl https://www.cloudflare.com/cdn-cgi/trace/ 得到warp=off
> 
> 就是要这个 warp 非全局的效果呀，你通过v2ray分流，可以让那些流量走原生网络，那些流量走warp网络。

有没有办法开全局，这样的话和v2用socks分流一个样了

**Comment by GreenTeodoro839** [comment]
> > #167 尝试该命令为warp ip，且用 curl -s4m5 --interface CloudflareWARP https://www.cloudflare.com/cdn-cgi/trace/ 可以得到warp=on，但直接 curl ip.gs 得到的为原来的ip，且 curl https://www.cloudflare.com/cdn-cgi/trace/ 得到warp=off
> 
> 就是要这个 warp 非全局的效果呀，你通过v2ray分流，可以让那些流量走原生网络，那些流量走warp网络。

大佬能不能开发个全局的，hk用不了wgcf，client按照官方教程开启之后vps就失联

**Comment by GreenTeodoro839** [comment]
> 你用本脚本的client两个模式，会失联吗？

不会，但是我想要全局的，cloudflare官方教程好像是直接安装client并注册，连接，应该是全局的，但是机器会失联
