### ISSUE TITLE
Table off参数不能用-【结论：为避免选项过多，本项目没有做 Table = off 配合 ip route 的方案。如想非全局，可以选用wireproxy或者client方案】

### ISSUE THREAD

**Issue by kathylincn** [fscarmen/warp#162]
用P3TERX的warp脚本，使用这个参数就没问题。用了这个脚本的team账号，加入table=off就不能用了。请问是team账号有这个限制，还是脚本哪里不对？

**Comment by fscarmen** [comment]
我好像没有用这个 Table = off，我对这个不了解。
查了一下是禁止wireguard自动修改路由表，修改wgcf配置文件，在[Interface]下添加的。
请问这个有何作用的？用普通账户加这个参数可以吗？

**Comment by kathylincn** [comment]
你的脚本的普通账户我也加了试过了。不行。5次获取IP失败，team的更不行。2秒刷完5次提示失败，但是P3TERX的使用就没有问题

**Comment by kathylincn** [comment]
就是你说的禁止wireguard自动修改路由表，添加了WARP后默认出口还是本机的。

**Comment by fscarmen** [comment]
你是要这个效果吗？ wgcf 非全局，需要在 v2ray 配置文件里指定网络接口来分流

<img width="947" alt="image" src="https://user-images.githubusercontent.com/62703343/172334108-f41834fc-dbda-4103-971a-c6c251545c90.png">

**Comment by kathylincn** [comment]
对啊。只用配置来分流，默认还是全部走本机流量。测速下载命令啥的都还是默认本机出口的好

**Comment by fscarmen** [comment]
说实在话，我刚刚试了 p3 的脚本 ，并不能像你据说的，加 Table = off 啊，那个网络接口不处理过不通的，我用 `bash <(curl -fsSL git.io/warp.sh) wgd` 来安装的双栈，之后`wg-quick down wgcf` 加上 Table = off 后再 up的

<img width="975" alt="image" src="https://user-images.githubusercontent.com/62703343/172345270-61096919-acfc-435a-a638-1b8b598f0e88.png">

<img width="659" alt="image" src="https://user-images.githubusercontent.com/62703343/172345606-96741d7b-bc43-49b8-b446-b8c66a1ee785.png">

**Comment by kathylincn** [comment]
一般我是用的systemctl restart wg-quick@wgcf，没有用过wg-quick down wgcf 再加然后再up。都是正常的时候加。然后restart wgcf或者reboot机器

**Comment by kathylincn** [comment]
哪怕换IP也是用的systemctl restart wg-quick@wgcf，down然后up没用过，不知道是不是一样

**Comment by fscarmen** [comment]
一样的效果的，试了下好像 p3 的也不支持非全局吧，我判断的依据是加了 Table = off 后，wgcf的网络接口不能通过curl 获取到warp的ip
