### ISSUE TITLE
获取到的IP都是ICMP通，TCP不通，请问这是正常的吗-【结论：引用3楼 GreenTeodoro839 的回复，WARP 分配的 IP，只作为出口 IP，不能通过这些 IP 连接到服务器】

### ISSUE THREAD

**Issue by jamesyoung233** [fscarmen/warp#163]
大佬，你好，我这里能获取到ip，但是这些IP的TCP都不通，请问是其他地方配置不对吗， CloudFlare Client 设置为 Proxy 模式也是这样的
![1654578727842](https://user-images.githubusercontent.com/14790381/172301005-887b302b-e1db-4423-91cf-c79ebf1be375.png)
![1654578865429](https://user-images.githubusercontent.com/14790381/172301069-ac298e13-c5ae-47b3-8e3b-64c1b9db1e3d.png)

**Comment by fscarmen** [comment]
我对这个没有研究啊，具体在应用场景中有什么影响？

**Comment by GreenTeodoro839** [comment]
这个ip只作为出口ip，不能通过这些ip连接到服务器
