### ISSUE TITLE
centos7 socks5创建失败

### ISSUE THREAD

**Issue by Sweetestcc** [fscarmen/warp#164]
输入
warp-cli --accept-tos status
warp-cli --accept-tos settings后报
warp-cli: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by warp-cli)
warp-cli: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by warp-cli)
warp-cli: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by warp-cli)

两台centos7一台成功了，一台失败了。失败的是centos7.6.1810

**Comment by fscarmen** [comment]
`strings /lib64/libc.so.6 | grep 'GLIBC_2.28'`，不行那台看看回显什么，脚本会检测没有 c 运行库 2.28的前提下会编译安装的，过程很长时间，可能是1小时左右（建议在 screen 下运行）。
这在你正常那台应该是这样，想了解一下你说不行那台，有没有这个过程？没有的话，可能是脚本判断出问题了，有的话，可能是编译不成功。

**Comment by Sweetestcc** [comment]
> `strings /lib64/libc.so.6 | grep 'GLIBC_2.28'`，不行那台看看回显什么，脚本会检测没有 c 运行库 2.28的前提下会编译安装的，过程很长时间，可能是1小时左右（建议在 screen 下运行）。 这在你正常那台应该是这样，想了解一下你说不行那台，有没有这个过程？没有的话，可能是脚本判断出问题了，有的话，可能是编译不成功。

没有返回任何东西

**Comment by Sweetestcc** [comment]
> `strings /lib64/libc.so.6 | grep 'GLIBC_2.28'`，不行那台看看回显什么，脚本会检测没有 c 运行库 2.28的前提下会编译安装的，过程很长时间，可能是1小时左右（建议在 screen 下运行）。 这在你正常那台应该是这样，想了解一下你说不行那台，有没有这个过程？没有的话，可能是脚本判断出问题了，有的话，可能是编译不成功。

不过安装确实有在编译，安装过程进行了很长时间

**Comment by fscarmen** [comment]
> > `strings /lib64/libc.so.6 | grep 'GLIBC_2.28'`，不行那台看看回显什么，脚本会检测没有 c 运行库 2.28的前提下会编译安装的，过程很长时间，可能是1小时左右（建议在 screen 下运行）。 这在你正常那台应该是这样，想了解一下你说不行那台，有没有这个过程？没有的话，可能是脚本判断出问题了，有的话，可能是编译不成功。
> 
> 不过安装确实有在编译，安装过程进行了很长时间

我在甲骨文和GCP等vps上试是可以成功的，所以不太确认为什么你那机器不行。

**Comment by fscarmen** [comment]
> > `strings /lib64/libc.so.6 | grep 'GLIBC_2.28'`，不行那台看看回显什么，脚本会检测没有 c 运行库 2.28的前提下会编译安装的，过程很长时间，可能是1小时左右（建议在 screen 下运行）。 这在你正常那台应该是这样，想了解一下你说不行那台，有没有这个过程？没有的话，可能是脚本判断出问题了，有的话，可能是编译不成功。
> 
> 没有返回任何东西

说明没有 glibc2.28 没有安装成功

**Comment by Sweetestcc** [comment]
> > > `strings /lib64/libc.so.6 | grep 'GLIBC_2.28'`，不行那台看看回显什么，脚本会检测没有 c 运行库 2.28的前提下会编译安装的，过程很长时间，可能是1小时左右（建议在 screen 下运行）。 这在你正常那台应该是这样，想了解一下你说不行那台，有没有这个过程？没有的话，可能是脚本判断出问题了，有的话，可能是编译不成功。
> > 
> > 
> > 没有返回任何东西
> 
> 说明没有 glibc2.28 没有安装成功

我想卸载warp相关，重装试一下，可是执行warp u没有反应

**Comment by fscarmen** [comment]
```
bash menu.sh u
```

最好能换个高级一点的系统

**Comment by Sweetestcc** [comment]
> ```
> bash menu.sh u
> ```
> 
> 最好能换个高级一点的系统

我再尝试一下，谢谢解答

**Comment by fscarmen** [comment]
你在可以那台试试 ```strings /lib64/libc.so.6 | grep 'GLIBC_2.28'``` ，应该是有显示的

**Comment by Sweetestcc** [comment]
> 你在可以那台试试 `strings /lib64/libc.so.6 | grep 'GLIBC_2.28'` ，应该是有显示的

这是在旧的那台重装后报的信息，
/usr/bin/ld: cannot find -lnss_test2
collect2: error: ld returned 1 exit status
Execution of gcc -B/usr/bin/ failed!
The script has found some problems with your installation!
Please read the FAQ and the README file and check the following:
- Did you change the gcc specs file (necessary after upgrading from
  Linux libc5)?
- Are there any symbolic links of the form libXXX.so to old libraries?
  Links like libm.so -> libm.so.5 (where libm.so.5 is an old library) are wrong,
  libm.so should point to the newly installed glibc file - and there should be
  only one such link (check e.g. /lib and /usr/lib)
You should restart this script from your build directory after you've
fixed all problems!
Btw. the script doesn't work if you're installing GNU libc not as your
primary library!
make[1]: *** [Makefile:111: install] Error 1
make[1]: Leaving directory '/root/glibc-2.28'
make: *** [Makefile:12: install] Error 2
Failed to start warp-svc.service: Unit not found.

**Comment by fscarmen** [comment]
这个看不明白了，本来官方也是不支持centos 7的，我处理了 C 运行库这里，估计还有不少兼容性的问题的。

**Comment by Sweetestcc** [comment]
> 你可以那台是7吗？

centos-7.7-x86_64

**Comment by GreenTeodoro839** [comment]
> > > `strings /lib64/libc.so.6 | grep 'GLIBC_2.28'`，不行那台看看回显什么，脚本会检测没有 c 运行库 2.28的前提下会编译安装的，过程很长时间，可能是1小时左右（建议在 screen 下运行）。 这在你正常那台应该是这样，想了解一下你说不行那台，有没有这个过程？没有的话，可能是脚本判断出问题了，有的话，可能是编译不成功。
> > 
> > 
> > 不过安装确实有在编译，安装过程进行了很长时间
> 
> 我在甲骨文和GCP等vps上试是可以成功的，所以不太确认为什么你那机器不行。

我的centos7.9也是make报错，tg发给你ssh信息了，ip 206.***.***.92
