### ISSUE TITLE
Client works with non-WARP IPv4. The script is aborted.

### ISSUE THREAD

**Issue by mhqschen** [fscarmen/warp#165]
全新安装的Debian11，第一次运行脚本，识别到的也是家宽的IP。但是选5或者14安装Client就会提示这个。

**Comment by fscarmen** [comment]
看看
```
curl -s4m8 ip.sb
warp-cli --accept-tos status
```

**Comment by mhqschen** [comment]
![image](https://user-images.githubusercontent.com/9138710/173180074-0aa5eb84-033e-467e-8b84-a151bed38ce1.png)

**Comment by mhqschen** [comment]
curl -s4m8 ip.sb访问不了，curl -s4m8 ip.gs的结果是一样的

**Comment by fscarmen** [comment]
这个情况是国内的机器，连 cloudflare-client 的服务器被墙了，而且不能改地址的。我这里是偶尔可以连一下，建议你用 wireproxy 或者 warp 单双栈 方案

**Comment by mhqschen** [comment]
好吧，手机上1.1.1.1的客户端是正常的。wrap单双栈方案是指什么？

**Comment by fscarmen** [comment]
就是菜单的1、2、3项，还有13项 ，这个的Endpoint可以自定义，我选了些多数能连上的，之后你可以用xray,v2ray分流，具体可以看项目 README.md

**Comment by fscarmen** [comment]
> 好吧，手机上1.1.1.1的客户端是正常的。wrap单双栈方案是指什么？

新版本的 Client 支持更换 Endpoint ，你通过以下方式更换
```
warp-cli disconnect    # 断开client连接
warp-cli set-custom-endpoint 162.159.193.10:2408   # 更换大陆可连接的 Endpoint
warp-cli connect    # 重新连接client
warp-cli status    #  查看状态
```
