### ISSUE TITLE
关闭WARP后怎么开启-【结论:显示错误，已修正，用 `warp v` 升级即可】

### ISSUE THREAD

**Issue by zhoujun0601** [fscarmen/warp#166]
1.  WARP IPv4 转为 WARP IPv6
 2.  WARP IPv4 转为 WARP 双栈
 3.  升级为 WARP+ 或 Teams 账户
 4.  暂时关闭 WARP
 5.  安装 CloudFlare Client 并设置为 Proxy 模式
 6.  更换支持 Netflix 的 IP
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy
 8.  刷 WARP+ 流量
 9.  升级内核、安装BBR、DD脚本 
 10. 同步最新版本
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知)
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS)
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理
 14. 安装 CloudFlare Client 并设置为 WARP 模式
 0. 退出脚本
**之前关闭了WARP网络，重新运行脚本只有上述选项，没有重新开启WARP IPV4的选项**

**Comment by fscarmen** [comment]
是个显示的bug，我稍后修复，你选 4 
又或者在命令行输入 `warp o`

**Comment by fscarmen** [comment]
已处理，请用 `warp v` 升级脚本，再运行`warp`即可。
