### ISSUE TITLE
debian10官方warp client无法正常使用

### ISSUE THREAD

**Issue by GreenTeodoro839** [fscarmen/warp#167]
warp模式，已经正常启动并获取到ip，但是curl https://www.cloudflare.com/cdn-cgi/trace/ 时返回warp=off，香港机器，以前用过这个脚本socks5代理，卸载后重装warp模式

**Comment by fscarmen** [comment]
最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局
一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)
