### ISSUE TITLE
新版选14安装 CloudFlare Client 后，不能再使用dnsmasq分流了？-【如有相同问题的，楼主提供了他的解决方案：去WARP Desktop Client官网下载并手工替换成4月的旧版解决】

### ISSUE THREAD

**Issue by chztv** [fscarmen/warp#169]
好像是 CloudFlare Client 模式也启用了53端口，dnsmasq 就启动失败了

**Comment by fscarmen** [comment]
我试了一下可以啊。测 ip 都是前者 VPS 原生 IP，后者 WARP ip
菜单 12 dnsmasq 
```
root@chuncheon2:~# curl -s4m5 ipinfo.io
{
  "ip": "146.56.***.***",
  "city": "Chuncheon",
  "region": "Gangwon-do",
  "country": "KR",
  "loc": "37.8625,127.6996",
  "org": "AS31898 Oracle Corporation",
  "postal": "24239",
  "timezone": "Asia/Seoul",
  "readme": "https://ipinfo.io/missingauth"
}

root@chuncheon2:~# curl -s4m5 https://ip.gs/json
{"ip":"8.38.149.140","ip_decimal":136746380,"country":"South Korea","country_iso":"KR","country_eu":false,"region_name":"Seoul","region_code":"11","zip_code":"04524","city":"Seoul","latitude":37.5794,"longitude":126.9754,"time_zone":"Asia/Seoul","asn":"AS13335","asn_org":"CLOUDFLARENET","user_agent":{"product":"curl","version":"7.68.0","raw_value":"curl/7.68.0"}}
```

菜单 14 client warp 模式
```
root@chuncheon2:~# curl -s4m5 ipinfo.io
{
  "ip": "146.56.***.***",
  "city": "Chuncheon",
  "region": "Gangwon-do",
  "country": "KR",
  "loc": "37.8625,127.6996",
  "org": "AS31898 Oracle Corporation",
  "postal": "24239",
  "timezone": "Asia/Seoul",
  "readme": "https://ipinfo.io/missingauth"
}root@chuncheon2:~# curl --interface CloudFlareWARP -s4m5 ipinfo.io
{
  "ip": "104.28.239.62",
  "city": "Tongjin",
  "region": "Gyeonggi-do",
  "country": "KR",
  "loc": "37.6569,126.6299",
  "org": "AS13335 Cloudflare, Inc.",
  "postal": "10060",
  "timezone": "Asia/Seoul",
  "readme": "https://ipinfo.io/missingauth"
```

**Comment by chztv** [comment]
> 我试了一下可以啊。测 ip 都是前者 VPS 原生 IP，后者 WARP ip，你可以在 README.md 里找相应v2ray模版。 菜单 12 dnsmasq
> 
> ```
> root@chuncheon2:~# curl -s4m5 ipinfo.io
> {
>   "ip": "146.56.***.***",
>   "city": "Chuncheon",
>   "region": "Gangwon-do",
>   "country": "KR",
>   "loc": "37.8625,127.6996",
>   "org": "AS31898 Oracle Corporation",
>   "postal": "24239",
>   "timezone": "Asia/Seoul",
>   "readme": "https://ipinfo.io/missingauth"
> }
> 
> root@chuncheon2:~# curl -s4m5 https://ip.gs/json
> {"ip":"8.38.149.140","ip_decimal":136746380,"country":"South Korea","country_iso":"KR","country_eu":false,"region_name":"Seoul","region_code":"11","zip_code":"04524","city":"Seoul","latitude":37.5794,"longitude":126.9754,"time_zone":"Asia/Seoul","asn":"AS13335","asn_org":"CLOUDFLARENET","user_agent":{"product":"curl","version":"7.68.0","raw_value":"curl/7.68.0"}}
> ```
> 
> 菜单 14 client 的 warp 模式
> 
> ```
> root@chuncheon2:~# curl -s4m5 ipinfo.io
> {
>   "ip": "146.56.***.***",
>   "city": "Chuncheon",
>   "region": "Gangwon-do",
>   "country": "KR",
>   "loc": "37.8625,127.6996",
>   "org": "AS31898 Oracle Corporation",
>   "postal": "24239",
>   "timezone": "Asia/Seoul",
>   "readme": "https://ipinfo.io/missingauth"
> }
> 
> root@chuncheon2:~# curl --interface CloudFlareWARP -s4m5 ipinfo.io
> {
>   "ip": "104.28.239.62",
>   "city": "Tongjin",
>   "region": "Gyeonggi-do",
>   "country": "KR",
>   "loc": "37.6569,126.6299",
>   "org": "AS13335 Cloudflare, Inc.",
>   "postal": "10060",
>   "timezone": "Asia/Seoul",
>   "readme": "https://ipinfo.io/missingauth"
> ```

我是使用了菜单14的warp模式，然后单独安装了dnsmasq进行分流。
我去[WARP Desktop Client](https://pkg.cloudflareclient.com/)官网查看了原来6月18日有新版，然后我手工替换成4月的旧版解决了问题。

**Comment by fscarmen** [comment]
今天系统测试到有新版本: V2022.7.472，本库已经同步更新了。你看看新版本是否能解决你的问题？

<img width="868" alt="image" src="https://user-images.githubusercontent.com/62703343/182534998-a6d54ddc-0aac-485c-af3c-a771331311c5.png">

**Comment by chztv** [comment]
> 今天系统测试到有新版本: V2022.7.472，本库已经同步更新了。你看看新版本是否能解决你的问题？
> 
> <img alt="image" width="915" src="https://user-images.githubusercontent.com/62703343/182537244-edfcc9ed-075e-4d92-bf89-1e64d29ad485.png">

试了一下，还是不行，新版使用后，dnsmasq还是无法启动，报错53端口被占用。
