### ISSUE TITLE
获取WARP IP 5次失败-【结论：香港暂时使用不了warp，可以选择 Client 的两个方案或者只能换地区了】

### ISSUE THREAD

**Issue by chnpeople** [fscarmen/warp#170]
腾讯国际云香港的机子， centos 7.6系统。装了233blog的v2ray和宝塔

**Comment by fscarmen** [comment]
#147

**Comment by fscarmen** [comment]
最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局
一键脚本: README.md#warp-go-运行脚本

**Comment by fscarmen** [comment]
最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局
一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)

**Comment by chnpeople** [comment]
> 最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局 一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)

大佬，可以弄新加坡的吗？

**Comment by fscarmen** [comment]
> > 最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局 一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)
> 
> 大佬，可以弄新加坡的吗？

新加坡用原来的 wgcf 也可以啊，当然新的 warp-go 也行。

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/62703343/184534799-cea0d0c0-a2c2-4624-b654-5b2e179c0991.png">

**Comment by chnpeople** [comment]
> > > 最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局 一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)
> > 
> > 
> > 大佬，可以弄新加坡的吗？
> 
> 新加坡用原来的 wgcf 也可以啊，当然新的 warp-go 也行。
> 
> <img alt="image" width="1317" src="https://user-images.githubusercontent.com/62703343/184534799-cea0d0c0-a2c2-4624-b654-5b2e179c0991.png">

哈哈，大佬我的意思是我是香港的机子可以warp新加坡的ip吗
