### ISSUE TITLE
netflix 刷出来的IP时效性非常低，请问大家有这种情况嘛？（已解决：见2楼提供的方法即可解决）

### ISSUE THREAD

**Issue by xiedy00** [fscarmen/warp#171]
美国的vps：基本上五分钟就失效重刷。
甲骨文东京的vps：前几天还刷的出来，最近都刷不出可用IP
请问大家是否有这种情况？

**Comment by fscarmen** [comment]
104.28那些IP段很差的。把美国的 vps 的 Endpoint 改为 162.159.192.1。重启一下 wgcf，也不要用 warp+ 和 teams
甲骨文东京那可能只能等了，不过我记得东京很多IP都是解锁的，不需要用warp吧

**Comment by xiedy00** [comment]
> 104.28那些IP段很差的。把美国的 vps 的 Endpoint 改为 162.159.192.1。重启一下 wgcf，也不要用 warp+ 和 teams 甲骨文东京那可能只能等了，不过我记得东京很多IP都是解锁的，不需要用warp吧

感谢回复，问一下不要用 warp+ 和 teams是什么道理呢？他们用的ip池会不一样嘛？用普通的warp正常使用其实没什么感觉吧？

**Comment by fscarmen** [comment]
感谢你支持。用了warp+和teams，经常分配到104.28这个ip段，而这个ip段，时时刻刻都在变的，如果不用奈飞还好。如果需要奈飞解锁，就一定不能用，否则你的tg提示响个不停的。

**Comment by xiedy00** [comment]
> 感谢你支持。用了warp+和teams，经常分配到104.28这个ip段，而这个ip段，时时刻刻都在变的，如果不用奈飞还好。如果需要奈飞解锁，就一定不能用，否则你的tg提示响个不停的。

感谢~我美国的vps是warp解锁ipv6的，麻烦您帮我看下我填写的这个是否正确：
![微信截图_20220630155829](https://user-images.githubusercontent.com/22208961/176625140-54f88b53-132a-4ee2-a075-7493d08ee007.png)

**Comment by fscarmen** [comment]
是的，就是这样。

**Comment by visense** [comment]
> 感谢你支持。用了warp+和teams，经常分配到104.28这个ip段，而这个ip段，时时刻刻都在变的，如果不用奈飞还好。如果需要奈飞解锁，就一定不能用，否则你的tg提示响个不停的。

不用warp+和teams，那用什么？

**Comment by xiedy00** [comment]
> 你v2ray匹配文件那里记得把奈飞流量分流去这个ipv6

按照你的方法，我现在一个小时没问题了。重点应该在于不用warp+和teams。用默认免费的就可以了。感谢！

**Comment by fscarmen** [comment]
> 
> 不用warp+和teams，那用什么？

用普通账户

**Comment by xiedy00** [comment]
> > > 不用warp+和teams，那用什么？
> > 
> > 
> > 用普通账户
> 
> 普通账户速度真是慢，team有什么方法？

其实当做解锁Netflix来看的话，我觉得速度还行。好像之前有看过说普通账户访问非cf cdn的网站其实和warp+速度上是没区别的。

**Comment by xiedy00** [comment]
> > 普通账户速度真是慢，team有什么方法？
> 
> 至今仍没有一位用户，能用数据证实普通账户比teams慢。

很奇怪，昨天正常，然后晚上开始到现在就一直刷不出IP了。
![微信截图_20220701095153](https://user-images.githubusercontent.com/22208961/176806853-90e292a1-84fc-429b-8bfc-c4c727e5b60b.png)
