### ISSUE TITLE
用Client WARP模式，自动刷Netflix出错。-【结论:刷 IP 和检测机制并没有出错，请留意不要跨区刷，如仍刷不到解锁的话，那就无解了】

### ISSUE THREAD

**Issue by xiedy00** [fscarmen/warp#172]
用该模式，如果是手动刷Netflix的ip就没问题，可以刷出ip；
如果用自动刷ip就一直刷，显示ip未解锁的。
是否为自动解锁脚本的检测机制出问题？

**Comment by fscarmen** [comment]
请问是不是刷到 104.28 开头的 IP ，这些 IP 段对于要解锁奈飞的很不友好，因为每次都会变化的，建议你不要使用 WARP+ 或者 Plus，只用普通免费账户，反而可以获取到8开头的IP段。

**Comment by xiedy00** [comment]
> 我是普通用户，但老是刷到104.28开头的ip 有什么方法可破吗？

我发觉是最近才变成这样的。我现在用普通账户出的都是104.28。Netflix的时效性很随机，有时候可以用好几天，有时候就是不断的刷。

**Comment by xiedy00** [comment]
> 请问是不是刷到 104.28 开头的 IP ，这些 IP 段对于要解锁奈飞的很不友好，因为每次都会变化的，建议你不要使用 WARP+ 或者 Plus，只用普通免费账户，反而可以获取到8开头的IP段。

最近普通账户出来的都是104.28的。所以也是不稳定了。

**Comment by fscarmen** [comment]
> 
> 最近普通账户出来的都是104.28的。所以也是不稳定了。

https://github.com/fscarmen/warp_unlock/issues/18

**Comment by xiedy00** [comment]
> > 最近普通账户出来的都是104.28的。所以也是不稳定了。
> 
> [fscarmen/warp_unlock#18](https://github.com/fscarmen/warp_unlock/issues/18)

那就是暂时无解。等恢复。谢谢

**Comment by xiedy00** [comment]
> > 最近普通账户出来的都是104.28的。所以也是不稳定了。
> 
> [fscarmen/warp_unlock#18](https://github.com/fscarmen/warp_unlock/issues/18)

那就是暂时无解。等恢复。谢谢
