### ISSUE TITLE
后台获取 WARP IP 中,最大尝试5次……

### ISSUE THREAD

**Issue by laopaoer-wallet** [fscarmen/warp#176]
升级 WARP+ 账户中……

2022/07/22 21:39:45 Using config file: wgcf-account.toml
2022/07/22 21:39:47 Updated license key detected, re-binding device to new account
2022/07/22 21:39:50 open wgcf-account.toml: permission denied
 创建快捷 bash warp 指令成功

 进度 3/3：运行 WARP

 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试

Mac Intel 一直卡在这里..

**Comment by fscarmen** [comment]
手动运行以下看看
```
sudo wg-quick up wgcf
```

**Comment by USATRUMP2021MAGA** [comment]
我的搬瓦工也是这样，系统是Debian 11 x86_64  重置系统十几次每次都这样
![Annotation 2022-08-04 191744](https://user-images.githubusercontent.com/93851708/182987475-51b31237-a3d2-4da5-a875-871f928500eb.png)

**Comment by fscarmen2** [comment]
> 手动运行以下看看
> 
> ```
> sudo wg-quick down wgcf; sudo wg-quick up wgcf
> ```

那不要sudo ，直接运行 
```
wg-quick down wgcf; wg-quick up wgcf
```

**Comment by fscarmen** [comment]
> 我的搬瓦工也是这样，系统是Debian 11 x86_64 重置系统十几次每次都这样 输入sudo wg-quick down wgcf; sudo wg-quick up wgcf 还是没用显示-bash: sudo: command not found ![Annotation 2022-08-04 191744](https://user-images.githubusercontent.com/93851708/182987846-b759c5a5-1fe9-4666-a62f-60311924bd79.png) ![Annotation 2022-08-04 192050](https://user-images.githubusercontent.com/93851708/182987852-1a639f0a-ce4e-4d63-98a5-80f3fe7701d2.png)

那不要sudo，试试
```
wg-quick down wgcf; wg-quick up wgcf
```
