### ISSUE TITLE
双栈机器使用warp-cli 成功连接上ipv4以后，流量没有分流到warp上

### ISSUE THREAD

**Issue by 20150561000** [fscarmen/warp#178]

**Comment by fscarmen** [comment]
看项目首页 README.md 文件，用v2ray或者x2ray，根据模板做分流

**Comment by 20150561000** [comment]
> 看项目首页 README.md 文件，用v2ray或者x2ray，根据模板做分流

请问可以全程代理流量吗？还是只能分流特定应用？

**Comment by fscarmen** [comment]
> 请问可以全程代理流量吗？还是只能分流特定应用？
> 
> +1
> 
> 我现在也是v4显示的是小鸡的ip v6 是cf ip 如何v4 访问所有网站都是cf ？

你这个v6是 cf ip的应该不是cli方案吧？如果你是 warp 双栈，并想优先 v4 全局的话，可以用

```
{
    "outbounds": [
        {
            "tag": "IP6-out",
            "protocol": "freedom",
            "settings": {}
        },
        {
            "tag": "IP4-out",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            }
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "outboundTag": "IP4-out",
                "domain": [
                    ""
                ]
            },
            {
                "type": "field",
                "outboundTag": "IP6-out",
                "network": "udp,tcp"
            }
        ]
    }
}
```

**Comment by fscarmen** [comment]
> 我运行的是菜单里第三个选项， 然后选的是ipv4优先 默认
> 
> 不知道你贴的上面的命令是什么 要在哪里执行运行 更改？

放在v2ray或者x2ray的配置文件啊，具体不同脚本这块文件的路径和文件名有不同，你要根据你使用的脚本处理。最后重启一下v2ray或者x2ray服务就行了

**Comment by fscarmen** [comment]
> 用的就是你的脚本 文件的路径和文件名是什么

要配合xray或v2ray脚本使用啊，像mack-a，x-ui，wulabing，233boy等主流脚本。

**Comment by fscarmen** [comment]
> 这下明白了 我没有搭v2 搭的是ssr 你贴的上面的命令能用在ssr上么

ssr的配置文件和书写规则我不知道呢，最好你问问ssr作者。了解在ssr中指定vps本地的 socks5://127.0.0.1:40000 出局如何处理。找到方法回头分享一下。
