### ISSUE TITLE
warp i刷新ip总是刷不出-【结论: 刷不出 IPv4，试试 v6，再刷不出也没有什么好办法，换 Endpoint 貌似没有任何变化】

### ISSUE THREAD

**Issue by Sentaku1129** [fscarmen/warp#179]
德国hax only ipv6刷取奈飞ipv4总是刷不出来，并且有时候会导致自身的ipv6也不能使用导致网络连接出问题

**Comment by fscarmen** [comment]
刷的时候因为不停的断开-连接-检测，所以会做成网络的不稳定，如果长时间刷不出来，就先不要刷了，特别是104.28开头的IP段极其差，经常变的。刷到8开头的才好。

**Comment by future-Hu** [comment]
> 刷的时候因为不停的断开-连接-检测，所以会做成网络的不稳定，如果长时间刷不出来，就先不要刷了，特别是104.28开头的IP段极其差，经常变的。刷到8开头的才好。

还有的问题是在导致ipv6的也异常了之后怎么恢复，刷取ip出问题网络无法连接，这时候是等待一段时间就好了么？刷取ip我尝试过很多次，一次都没有成功过

**Comment by fscarmen** [comment]
你用 ```warp o``` 关了warp就行了

**Comment by cilantrolee** [comment]
为什么刷不到 8.开头的IP了 一直重复104.28 😓

**Comment by future-Hu** [comment]
> 为什么刷不到 8.开头的IP了 一直重复104.28 😓

而且还一直总是就那几个了，只能刷vps所在区域的

**Comment by ben-august** [comment]
不知道是不是要改endpoint，美区VPS最近全是刷的104.28.开头的ip段，这个ip段没办法解锁Netflix。

**Comment by fscarmen** [comment]
> > 为什么刷不到 8.开头的IP了 一直重复104.28 😓
> 
> 而且还一直总是就那几个了，只能刷vps所在区域的

是啊，那些ip只有很少的这个的
