### ISSUE TITLE
是否有cloudflare-warp-client的openwrt版本，或容器版本可供使用？-【结论： WARP-client 只支持 amd64 环境，如果 openwrt 也运行在 amd64 的设备上，应该是可以的，如果是别的架构设备，估计暂时无戏了】

### ISSUE THREAD

**Issue by Meina9758** [fscarmen/warp#180]
在香港使用openwrt分流隐藏真实ip，之前一直使用wgcf。而后wgcf失效观察到warp-client可用但是未找到openwrt包。近期准备离开香港但是有eoip专线可连接回香港，如果在境内需要使用分流是否可以用warp-client？

**Comment by fscarmen** [comment]
很抱歉，CF官网关于 Client 的安装包只支持 AMD64 的三大系统，连 arm64，还有 amd64下的alpine都不支持。
详见：https://pkg.cloudflareclient.com/packages/cloudflare-warp

同时我又没有能力逆向破解，也暂时没有留意到有哪位高手破解并交叉编译可用于各CPU架构的魔改版本。所以你的想法暂时我实现不了。   

<img width="955" alt="image" src="https://user-images.githubusercontent.com/62703343/182022623-c4357859-1443-441c-9083-8701356d8a53.png">

**Comment by Meina9758** [comment]
> 很抱歉，CF官网关于客户端的安装包只支持AMD64的三大系统，连arm64，还有amd64下的alpine都支持。详见： [https](https://pkg.cloudflareclient.com/packages/cloudflare-warp) ://pkg.cloudflareclient.com/packages/cloudflare-warp[](https://pkg.cloudflareclient.com/packages/cloudflare-warp)
> 
> 我没有另一个能力逆向破解，也暂时没有注意到有哪位高手破解并交叉编译可用于各种CPU架构的魔改版本。所以你的联想暂时我无法实现。
> 
> <img alt="图片" width="955" src="https://user-images.githubusercontent.com/62703343/182022623-c4357859-1443-441c-9083-8701356d8a53.png">
好的，谢谢！但是有没有可能使用docker容器或者是虚拟化解决这些呢？openwrt也有x86版本（虽然我用的是arm64）

**Comment by fscarmen** [comment]
> > 很抱歉，CF官网关于客户端的安装包只支持AMD64的三大系统，连arm64，还有amd64下的alpine都支持。详见： [https](https://pkg.cloudflareclient.com/packages/cloudflare-warp) ://pkg.cloudflareclient.com/packages/cloudflare-warp
> > 我没有另一个能力逆向破解，也暂时没有注意到有哪位高手破解并交叉编译可用于各种CPU架构的魔改版本。所以你的联想暂时我无法实现。
> > <img alt="图片" width="955" src="https://user-images.githubusercontent.com/62703343/182022623-c4357859-1443-441c-9083-8701356d8a53.png">
> 
> 好的，谢谢！但是有没有可能使用docker容器或者是虚拟化解决这些呢？openwrt也有x86版本（虽然我用的是arm64）

如果是建立在 amd64 架构上的 ubuntu docker 我想应该是可以的，只是这样比较占资源了，可以先找找有没有其他作者已经做了并作优化，这样可大大减少容量和内存占用等。

而我自己只大量在 alpine 容器运行 wgcf，但就没有试过在ubuntu容器安装client。

**Comment by fscarmen** [comment]
warp-go 1.1.0 版本支持在 OpenWrt 上使用了，如还有需要，可以试用。

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/62703343/208330313-c3b729cf-462e-4276-9f99-d20d0a67129a.png">
