### ISSUE TITLE
docker容器的网络设置-【结论: 这些扩展应用已超出我的能力范围了，还请各位玩家多试试，折腾出结果的回头分享一下经验。】

### ISSUE THREAD

**Issue by lsbjkc** [fscarmen/warp#181]
安装环境：
脚本版本：2.40  功能新增：1.支持 VPS-free LXC VPS
 系统信息：
        当前操作系统：CentOS Linux 7 (Core)
        内核：5.17.1
        处理器架构：amd64
        虚拟化：kvm
        IPv4：104.28.*.* ( WARP IPv4 ) 美国  CLOUDFLARENET
        IPv6：
        WARP 网络接口已开启
        Client 未安装
        WireProxy 未安装

我的代理运行在docker容器里，要怎么配置网络才能走warp的IP出去？

**Comment by fscarmen** [comment]
你连着代理，在 ip.gs 里看看是否已经连着warp

**Comment by lsbjkc** [comment]
用--network=host，显示的是vps的IP
用--bridge模式代理直接无网络

**Comment by fscarmen** [comment]
> 用--network=host，显示的是vps的IP 用--bridge模式代理直接无网络

你用哪个项目啊？有抽个时间看看

**Comment by lsbjkc** [comment]
> > 用--network=host，显示的是vps的IP 用--bridge模式代理直接无网络
> 
> 你用哪个项目啊？有抽个时间看看
用的这个：https://hub.docker.com/r/yangyzp/docker-ssrmu

**Comment by fscarmen** [comment]
> 用的这个：https://hub.docker.com/r/yangyzp/docker-ssrmu

请问有没有一键脚本运行的？ docker run 要带什么参数和映射端口和目录都不太清楚。项目介绍那个主页: https://vinga.tech/ssrmu/ 也访问不了

**Comment by lsbjkc** [comment]
> > 用的这个：https://hub.docker.com/r/yangyzp/docker-ssrmu
> 
> 请问有没有一键脚本运行的？ docker run 要带什么参数和映射端口和目录都不太清楚。项目介绍那个主页: https://vinga.tech/ssrmu/ 也访问不了

参数都是一些数据对接的，我没有添加端口映射的参数进去
我试过用iptables的POSTROUTING把docker0网卡出来的流量全都转到wgcf的网卡上，但还是没办法使docker容器走warp的ip

以下是我的网卡和iptables的设置：
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:c1:4c:06:c2:72 brd ff:ff:ff:ff:ff:ff
    inet 172.26.13.91/20 brd 172.26.15.255 scope global dynamic eth0
       valid_lft 3238sec preferred_lft 3238sec
    inet6 2406:da18:425:7b00:f050:d82:b5ed:57e/128 scope global dynamic
       valid_lft 405sec preferred_lft 95sec
    inet6 fe80::c1:4cff:fe06:c272/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:15:b9:d8:8f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:15ff:feb9:d88f/64 scope link
       valid_lft forever preferred_lft forever
9: wgcf: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1420 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 172.16.0.2/32 scope global wgcf
       valid_lft forever preferred_lft forever
    inet6 fd01:5ca1:ab1e:8139:79cf:32dd:7abc:60df/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::7303:b8de:a94b:6bb5/64 scope link flags 800
       valid_lft forever preferred_lft forever

Chain PREROUTING (policy ACCEPT 3 packets, 180 bytes)
 pkts bytes target     prot opt in     out     source               destination
  170 10700 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 3 packets, 180 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 4 packets, 256 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 4 packets, 256 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 SNAT       all  --  *      *       172.17.0.0/16        0.0.0.0/0            to:172.16.0.2

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0

**Comment by fscarmen** [comment]
我是通过以下指令运行，容器里获取到 warp ip，剩下的代理我不会如何用了，我对这个项目不了解

```
docker run -dit --name ssrmu --restart=always --name ssrmu --sysctl net.ipv6.conf.all.disable_ipv6=0 --device /dev/net/tun --privileged --cap-add net_admin --cap-add sys_module --log-opt max-size=1m -v /lib/modules:/lib/modules yangyzp/docker-ssrmu:latest
docker exec -it ssrmu apk add -f wget grep
docker exec -it ssrmu wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
docker exec -it ssrmu bash menu.sh
```

<img width="723" alt="image" src="https://user-images.githubusercontent.com/62703343/182753285-311319dd-baa5-4178-ac4c-b80f44b8dc99.png">

**Comment by lsbjkc** [comment]
> 我是通过以下指令运行，容器里获取到 warp ip，剩下的代理我不会如何用了，我对这个项目不了解
> 
> ```
> docker run -dit --name ssrmu --restart=always --name ssrmu --sysctl net.ipv6.conf.all.disable_ipv6=0 --device /dev/net/tun --privileged --cap-add net_admin --cap-add sys_module --log-opt max-size=1m -v /lib/modules:/lib/modules yangyzp/docker-ssrmu:latest
> docker exec -it ssrmu apk add -f wget grep
> docker exec -it ssrmu wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
> docker exec -it ssrmu bash menu.sh
> ```
> 
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/62703343/182753285-311319dd-baa5-4178-ac4c-b80f44b8dc99.png">
按照你的方法第一次显示获取成功，再次执行docker exec -it ssrmu warp，warp接口又变成未开启，端口也始终不通
![image](https://user-images.githubusercontent.com/43370337/182851717-c2edd861-8b9d-4740-be37-0c3d65f7a680.png)

**Comment by fscarmen** [comment]
我这里再次进入仍然是可以的，你指的端口始终不通，是宿主机想通过alpine里的 warp 访问外网？

**Comment by fscarmen** [comment]
我在另一个项目 warp_unlock 是这样实现的，alpine 里安装 warp，然后通过 gost 建立一个socks5 代理供宿主机服务，宿主机通过v2ray的outbound分流，把流量指向该socks5服务。我想iptables也行的，不用v2ray，不过我不熟。

**Comment by lsbjkc** [comment]
> 我这里再次进入仍然是可以的，你指的端口始终不通，是宿主机想通过alpine里的 warp 访问外网？

是外部网络无法访问docker容器里的代理软件所监听的端口，似乎必须使用--network=host参数才可以。
我按照你的方法，使用默认的network参数，也就是bridge，无论是开不开warp都始终端口不通。

**Comment by fscarmen** [comment]
我看到这个项目好像只打开了个 41118 的端口服务，具体怎么用我就不清楚了。而你说用 bridge 模式时，无论开不开 warp 都不能正常使用？那是不是应该让该服务正常了，再加入 warp
```
root@chuncheon2:~# docker exec -it ssrmu ss -nlutp
Netid  State   Recv-Q  Send-Q   Local Address:Port    Peer Address:Port Process 
udp    UNCONN  0       0              0.0.0.0:41118        0.0.0.0:*            
udp    UNCONN  0       0                 [::]:41118           [::]:*            root@chuncheon2:~# docker exec -it ssrmu lsof -i:41118
1       /usr/bin/python3.8      /dev/pts/0
1       /usr/bin/python3.8      /dev/pts/0
1       /usr/bin/python3.8      /dev/pts/0
1       /usr/bin/python3.8      socket:[221978802]
1       /usr/bin/python3.8      anon_inode:[eventpoll]
1       /usr/bin/python3.8      socket:[221983346] 
```

**Comment by lsbjkc** [comment]
我用流媒体解锁测试脚本和mtr Netflix.com的IP对比，发现测试脚本可以识别warp获取的ip，但是mtr路由好像用的IP和warp的IP还不一样，warp的wgcf出口应该是172.16.0.2，这里mtr出口是172.16.0.1，不知道是哪里出了问题
![屏幕截图 2022-08-06 220140](https://user-images.githubusercontent.com/43370337/183252432-66a20a57-b09f-40c2-a0c3-8259e346123a.jpg)
![屏幕截图 2022-08-06 220322](https://user-images.githubusercontent.com/43370337/183252438-2f5af242-7a44-409f-a0e3-54ea6f968a84.jpg)

**Comment by fscarmen** [comment]
warp的两端，vps是172.1

**Comment by lsbjkc** [comment]
> warp连通时虚拟局域网的两端，vps是172.16.0.2，cloudflare端是172.16.0.1。在外网看来就是cf的ip。原理与小区家庭宽带差不多，没问题的

也就是说本地客户端通过服务器原本的IP连接服务器上的代理服务，这个时候代理服务所处的局域网和wgcf不在一个网段，导致代理服务不走warp网口，而是走eth0？
那我要什么设置才能让代理服务所处的网段和warp服务一致？

**Comment by fscarmen** [comment]
本脚本应该是warp全局的，不需要额外设置即可走warp了吧

**Comment by fscarmen** [comment]
> 
> 也就是说本地客户端通过服务器原本的IP连接服务器上的代理服务，这个时候代理服务所处的局域网和wgcf不在一个网段，导致代理服务不走warp网口，而是走eth0？
> 
> 那我要什么设置才能让代理服务所处的网段和warp服务一致？

忘记问了，你是用docker方案吗？

**Comment by lsbjkc** [comment]
代理服务和warp都试过docker和非docker，一旦获得CF的IP，代理服务就连不上，关闭warp就又好了，iptables各种操作都不行，似乎是ssrmu本身的问题。全网搜了半天，试了两三个晚上，最终还是用DNS解锁的方案了，就是要再单独开一台vps。

**Comment by fscarmen** [comment]
> 代理服务和warp都试过docker和非docker，一旦获得CF的IP，代理服务就连不上，关闭warp就又好了，iptables各种操作都不行，似乎是ssrmu本身的问题。全网搜了半天，试了两三个晚上，最终还是用DNS解锁的方案了，就是要再单独开一台vps。

这些扩展应用已超出我的能力范围了，还请各位玩家多试试，折腾出结果的回头分享一下经验。👍🏻
