### ISSUE TITLE
开启后内存占用越来越大-【结论: warp-cli 占用个 3、400 M 内存是正常的。可能会撑爆只有 500M 内存的小鸡】

### ISSUE THREAD

**Issue by wqs50** [fscarmen/warp#182]
使用“CloudFlare Client 并设置为 Proxy 模式” 内存随时间越来越大

**Comment by fscarmen** [comment]
这个问题不好回答，因为与你的环境和其他进程都可能有关。建议你在用 top 来看观察一下 warp-svc 进程占用的内存变化了。

<img width="912" alt="image" src="https://user-images.githubusercontent.com/62703343/183018974-6d74d9e8-78bd-4410-bc41-ba49d6bca2e1.png">

**Comment by wqs50** [comment]
![image](https://user-images.githubusercontent.com/63278029/183054062-632de707-529b-4943-95c2-e21fe30f7c06.png)
图片这个样子的，开始运行是40mb的占用，后面原来越大，现在最大的机器占用2G了

**Comment by wqs50** [comment]
我用的是soga的路由出站代理 socks连接，发现只要连接了这个占用就会越来越大

**Comment by fscarmen** [comment]
不连接能释放内存吗？我没留意过

**Comment by wqs50** [comment]
![image](https://user-images.githubusercontent.com/63278029/183099631-76ce3738-58a3-4d72-95e7-c5f496ac4a29.png)
我关掉出站代理后内存从262涨岛294就没变了，也没有降低

**Comment by fscarmen** [comment]
有下周找个时间在nas的虚拟机上看看吧，是连接youtube来测？

**Comment by wqs50** [comment]
我是用soga出站代理，socks连接warp，代理的有谷歌和奈飞

**Comment by wqs50** [comment]
![image](https://user-images.githubusercontent.com/63278029/183294422-76010883-d865-41d4-a64e-a3f123de9230.png)
这个是我的配置文件。我不知道warp日志在哪你需要的话告诉我一下

**Comment by fscarmen** [comment]
> 这个是我的配置文件。我不知道warp日志在哪你需要的话告诉

warp 并没有日志输出文件的哦，同时我水平有限，对你这个路由规则写法不太了解。现时我只在v2ray的配置文件里作分流。

**Comment by g-zp** [comment]
我也有同样的问题，小机要撑爆了
```
Tasks:  76 total,   1 running,  75 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.4 us,  4.1 sy,  0.0 ni, 91.8 id,  0.3 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :    473.6 total,     51.4 free,    356.3 used,     65.9 buff/cache
MiB Swap:    512.0 total,      0.0 free,    512.0 used.    103.8 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1630688 root      20   0 1250312 235148      0 S   2.0  48.5  14:46.91 warp-svc
    536 root      20   0 1343704  13372   2984 S   0.7   2.8  17:01.20 x-ui
     80 root      20   0       0      0      0 S   0.3   0.0  28:02.25 kswapd0
    580 root      20   0 4989156  41680   5552 S   0.3   8.6  26:09.40 xray-linux-amd6
2633644 root      20   0   12012   4028   3352 R   0.3   0.8   0:00.01 top
2633699 root      20   0   13760   8368   7192 S   0.3   1.7   0:00.01 sshd
      1 root      20   0  167572   4716   2868 S   0.0   1.0   0:35.63 systemd
```

**Comment by fscarmen** [comment]
可以试一下 warp 脚本的 wireproxy 方案或者 最新的 warp-go 脚本非全局方案。
也是通过v2ray的配置文件分流的。

**Comment by fscarmen** [comment]
其他用户反馈， warp-cli 占用个3、400 M 内存是正常的。
