### ISSUE TITLE
安装了warp脚本，现在想要warp go 使用team 是直接再次使用新的还是先卸载旧的？-【结论: warp-go 和 wgcf 两者互换还是先卸载再安装】

### ISSUE THREAD

**Issue by 8ty** [fscarmen/warp#187]

**Comment by fscarmen** [comment]
如果是你手动的话，需要先卸载 warp 脚本。
同时如果是针对 warp-go 1.0.2 的一键脚本，暂时还没有测试完，已处理了 warp+ 账户的升级，正在测试 team 账户的安装和升级。
最后如果你的 warp 使用正常，暂时不建议更换到 warp-go，因为 warp 的功能成熟完善。
