### ISSUE TITLE
似乎有什么不对的地方

### ISSUE THREAD

**Issue by fxzxmic** [fscarmen/warp#188]
![image](https://user-images.githubusercontent.com/54622331/184570078-af817662-e4ea-4f30-be0e-4d7d47d4d202.png)
我的Alpine显示不支持。

**Comment by fscarmen** [comment]
好像判断不了 alpine系统，你试试执行以下指令
```
grep -i pretty_name /etc/os-release 2>/dev/null | cut -d \" -f2
```

**Comment by fxzxmic** [comment]
是不是我卸载了alpine-base的关系，没有`/etc/os-release`这个文件。

**Comment by fscarmen** [comment]
有可能是的，因为脚本是用这个文件来判断该系统为 alpine 的

**Comment by fxzxmic** [comment]
那我应该怎么修改呢？

**Comment by fxzxmic** [comment]
我直接去用warp-go了，没有用脚本，抱歉。
