### ISSUE TITLE
warp-go 可以流量分流吗？

### ISSUE THREAD

**Issue by zhdsmy** [fscarmen/warp#189]
例如旧的 Client Socks5 或 WARP 模式，可以通过 x-ui 指定具体的流量走 warp

**Comment by taffychan** [comment]
warp-go是全局的warp

**Comment by fscarmen** [comment]
> 例如旧的 Client Socks5 或 WARP 模式，可以通过 x-ui 指定具体的流量走 warp

可以试试

**Comment by fscarmen** [comment]
在 xray 测试可以了。

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/62703343/184909537-10a63fc5-da73-4f26-8607-399d6686edde.png">

**Comment by zhdsmy** [comment]
666，期待新版

**Comment by fscarmen** [comment]
> 666，期待新版

2022.8.17 warp-go 一键脚本 v1.0.2
1. Add WARP IPv4 non-global and global switch echo other. configure v2ray/xray configuration file to triage
2. Output wgcf configuration file (warp-go e)

1.在原来全局的基础上，新增 WARP IPv4 非全局方案，配置 v2ray/xray 配置文件来分流，参数项目主页的 Client WARP 模式的模版
2.输出 wgcf 配置文件(warp-go e)

```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash [warp-go.sh](https://web.telegram.org/z/warp-go.sh) [option] [lisence]
```

**Comment by visense** [comment]
> 新增 WARP IPv4 非全局方案

ipv6可以非全局吗？全局模式有个问题，重启的时候，就会断网
