### ISSUE TITLE
搬瓦工 CentOS Linux 8 安装失败

### ISSUE THREAD

**Issue by jelly0925** [fscarmen/warp#19]
系统:centos 8
内核：4.18.0-80.el8.x86_64
在WGCF 注册阶段一直失败，提示：wg-quick: `wgcf' is not a WireGuard interfac
![warp1](https://user-images.githubusercontent.com/3022023/137607298-c88fbdde-e04a-4ae0-a400-a37024419c36.png)
![warp error](https://user-images.githubusercontent.com/3022023/137607322-44293dd8-b5f5-4dda-be5b-73a9a4f1b529.png)

**Comment by fscarmen** [comment]
谢谢反馈，我刚在 甲骨文 C8 系统上试了OK，正在GCP的C8试

![image](https://user-images.githubusercontent.com/62703343/137608937-f25d6e98-2be2-4bbe-bb43-63636c94e6c3.png)

**Comment by fscarmen** [comment]
再试试卸载，重新安装看看
```bash menu.sh u; bash menu.sh 2```

**Comment by fscarmen** [comment]
> 系统:centos 8 内核：4.18.0-80.el8.x86_64 在WGCF 注册阶段一直失败，提示：wg-quick: `wgcf' is not a WireGuard interfac ![warp1](https://user-images.githubusercontent.com/3022023/137607298-c88fbdde-e04a-4ae0-a400-a37024419c36.png) ![warp error](https://user-images.githubusercontent.com/3022023/137607322-44293dd8-b5f5-4dda-be5b-73a9a4f1b529.png)

脚本有处地方没有判断好CentOS7和8，导致有的 CentOS 8 安装不成功，现在已经修改，有机会安装的时候再试试，谢谢反馈。
