### ISSUE TITLE
warp ipv4网速问题

### ISSUE THREAD

**Issue by baby9** [fscarmen/warp#190]
euserv的机器安装warp-go或wgcf后ipv4都只能跑20Mbps左右，系统为debian，hax的机器安装warp-go后ipv4也是20Mbps，安装wgcf能跑100Mbps左右接近满速，系统为ubuntu

**Comment by baby9** [comment]
我这边可以提供机器测试

**Comment by fscarmen** [comment]
> euserv的机器安装warp-go或wgcf后ipv4都只能跑20Mbps左右，系统为debian，hax的机器安装warp-go后ipv4也是20Mbps，安装wgcf能跑100Mbps左右接近满速，系统为ubuntu

请问你是通过在什么环境下，通过哪种方式测速的呢？

**Comment by baby9** [comment]
> > euserv的机器安装warp-go或wgcf后ipv4都只能跑20Mbps左右，系统为debian，hax的机器安装warp-go后ipv4也是20Mbps，安装wgcf能跑100Mbps左右接近满速，系统为ubuntu
> 
> 请问你是通过在什么环境下，通过哪种方式测速的呢？

直接在机器上通过curl测速
curl -4 -Lo /dev/null -O https://fra-de-ping.vultr.com/vultr.com.100MB.bin

**Comment by baby9** [comment]
大量测试后，发现原因可能有两种：
1、euserv官方对机器udp限速
2、cloudflare对euserv的ip限速
我在机器上通过链式代理 local -> warp-go -> warp-cli -> 出口 这样ipv4是接近满速的

**Comment by fscarmen** [comment]
谢谢你的测试啊，我初步试了一下在 euserv 上，开了 warp ，下载只有 2.5MB /s 的样子。你那里是这样吗？

**Comment by baby9** [comment]
20Mbps一样的，warp-go和wgcf都是
