### ISSUE TITLE
warp-go global and non-global

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#192]
i try using your script per today
```
[Peer]
PublicKey   = sadasdasdsa
Endpoint    = 162.159.193.10:1701
KeepAlive   = 30
AllowedIPs = 0.0.0.0/0

[Script]
PostUp = ip -4 rule add from 10.1.1.131 lookup main
PostDown = ip -4 rule delete from 10.1.1.131 lookup main
```

between global and non global the different only on `AllowedIPs` ? last week it's has 4 line script postup/postdown like this one.
```
[Script]
PostUp = ip -4 rule add from 10.1.1.131 lookup main
PostDown = ip -4 rule delete from 10.1.1.131 lookup main
PostUp = ip -4 rule add from 172.16.0.2 lookup 60000; ip -4 route add default dev WARP table 60000; ip -4 rule add table main suppress_prefixlength 0
PostDown = ip -4 rule delete from 172.16.0.2 lookup 60000; ip -4 rule delete table main suppress_prefixlength 0
```

**Comment by malikshi** [comment]
found the commit https://github.com/fscarmen/warp/commit/1013584d2f15cca8fa9fcddbed2c50f205c2677b

**Comment by fscarmen** [comment]
> PostUp = ip -4 rule add from 172.16.0.2 lookup 60000; ip -4 route add default dev WARP table 60000; ip -4 rule add table main suppress_prefixlength 0
> PostDown = ip -4 rule delete from 172.16.0.2 lookup 60000; ip -4 rule delete table main suppress_prefixlength 0

These commands can only be executed after the WARP network interface has been established.
So they cannot be executed at the same time as other commands in the configuration file.

**Comment by fscarmen** [comment]
Warp-go one-click script support English today.

**Comment by malikshi** [comment]
> > PostUp = ip -4 rule add from 172.16.0.2 lookup 60000; ip -4 route add default dev WARP table 60000; ip -4 rule add table main suppress_prefixlength 0
> > PostDown = ip -4 rule delete from 172.16.0.2 lookup 60000; ip -4 rule delete table main suppress_prefixlength 0
> 
> These commands can only be executed after the WARP network interface has been established. So they cannot be executed at the same time as other commands in the configuration file.

Thx for elaborate it

**Comment by malikshi** [comment]
> Warp-go one-click script support English today.

That's would the best. Thx you for hard work!

**Comment by malikshi** [comment]
just fill `E` in /opt/wrap-go/language right ?
works like charm

**Comment by fscarmen** [comment]
Sorry. You must re-install the latest one to support English.

**Comment by malikshi** [comment]
> Sorry. You must re-install the latest one to support English.

just installed on spare vps 5 min ago,

**Comment by malikshi** [comment]
sir @fscarmen what is different between `lookup main prio 18` and `lookup main prio`.

**Comment by fscarmen** [comment]
> sir @fscarmen what is different between `lookup main prio 18` and `lookup main prio`.

Used to set the priority level, the smaller the number, the higher the priority level. 

If you do not set the priority level, then, by default, the priority level will start from 32766 decreasing, such as 32765, 32764 ...... 

If we need to set the priority level in particular, can be added at the end of the ip rule add command prio XXX parameter.
