### ISSUE TITLE
请问该项目是如何解决香港的连接问题？

### ISSUE THREAD

**Issue by youtonghy** [fscarmen/warp#195]
如题，本人目前通过wgcf提取了warp的wireguard配置用作代理链，但是无法在香港节点使用，由于没有合适的Linux环境，特想请教下香港地区的wireguard配置有何区别？

**Comment by fscarmen** [comment]
配置没有任何区别的，但香港要用warp-go作为核心运行程序，其他地区用wgcf或者warp-go两者都可以。
