### ISSUE TITLE
warp-go刷不出新IP-【结论: 2022.8.30 warp-go V1.0.6，解决了更换不了IP的bug】

### ISSUE THREAD

**Issue by Moelin-MtF** [fscarmen/warp#197]
warp-go刷IP的时候只能刷出同一个ip，刷不出新的IP·

**Comment by fscarmen** [comment]
这个控制不了，104.28的ip段，很多地区只1-3个ip的

**Comment by fscarmen** [comment]
有办法处理了
![image](https://user-images.githubusercontent.com/62703343/187359757-36b4397d-3dce-4864-bcfb-ac4a3a0103a1.png)

**Comment by fscarmen** [comment]
2022.8.30 warp-go V1.0.6
Fixed the bug of not changing IP.
解决了更换不了IP的bug
升级

```
warp-go v
```
