### ISSUE TITLE
注册 teams 账户失败，脚本中止-【结论: 用户长时间没有回复，先行 Closed ，如有问题请继续反馈】

### ISSUE THREAD

**Issue by h2ch** [fscarmen/warp#198]
使用提供的链接获取到的teams token一直提示注册teams账户失败

注册 teams 账户失败，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 
sed: can't read /opt/warp-go/warp.conf: No such file or directory
grep: /opt/warp-go/warp.conf: No such file or directory
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
 第2次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xe" for details.
 第3次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
 第4次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xe" for details.
 第5次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
奇怪，照计脚本有个判断，一定要注册到 /opt/warp-go/warp.conf 或者失败满 10 次就报错退出。你先用 `bash warp-go.sh u` 卸载，重启vps，再安装多次看看

**Comment by fscarmen** [comment]
看情况是没有注册成功，没有生成 /opt/warp-go/warp.conf 文件，但具体原因不明。
方便加个 tg: https://t.me/fscarmen2 ，把 ssh 信息发我看看
