### ISSUE TITLE
 注册 warp 账户失败，脚本中止-【结论: 用户长时间没有回复，先行 Closed ，如有问题请继续反馈】

### ISSUE THREAD

**Issue by ghost** [fscarmen/warp#199]
注册 warp 账户失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp/issues] 
sed: can't read /opt/warp-go/warp.conf: No such file or directory
grep: /opt/warp-go/warp.conf: No such file or directory
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
 第2次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xe" for details.
 第3次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
 第4次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xe" for details.
 第5次尝试 
Warning: The unit file, source configuration file or drop-ins of warp-go.service changed on disk. Run 'systemctl daemon-reload' to reload units.
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
看情况是没有注册成功，没有生成 /opt/warp-go/warp.conf 文件，但具体原因不明。
方便加个 tg: https://t.me/fscarmen2 ，把 ssh 信息发我看看

**Comment by fscarmen** [comment]
了解到有时候会触发 cf 的风控而导致注册不成功的，你可以再找个时间，卸载原来的 ```bash warp-go.sh u```，重启vps，再安装看看。
