### ISSUE TITLE
Web服务器被墙,使用warp能否正常访问国内API?

### ISSUE THREAD

**Issue by ppoiissbsjksms** [fscarmen/warp#20]
你好,我的web服务器需要访问国内API,但是WEB服务器被墙了,无法正常访问国内API,使用WARP添加一个IPV4后,能否做到正常访问国内API,添加之后和NGINX之类的WEB环境会有冲突吗?

**Comment by fscarmen** [comment]
按我理解是不会影响 nginx 的 web 应用的，实际情况如何，你可以安装脚本试，看哪些出问题再分析。大不了暂停服务 ```warp o``` 或者 卸载```warp u```
