### ISSUE TITLE
warp-go非全局模式成功warp IP但是仍然无法解锁Netflix

### ISSUE THREAD

**Issue by Yihan-zz** [fscarmen/warp#200]
Hi，@fscarmen ，非常感谢你的这款产品！它让我对Netflix重新燃起了兴趣，但是我在使用的时候遇到了一些问题。具体为：

- 使用warp-go的非全局模式（模式7）
- 使用免费账户
- 提示说已成功获取WARP free网络
- 但Netflix仍然无法解锁

请问是否需要其他额外步骤，比如更改一些配置之类的操作？另外，我是用的时V2rayN框架。

下面是我使用时的打印日志，希望对你有帮助。

> 脚本版本: 1.0.6         功能新增: 1.解决了非全局模式重启后，路由规则失效的bug; 2.解决了更换不了IP的bug
> 系统信息:
         当前操作系统: Debian GNU/Linux 11 (bullseye)
         内核: 5.10.0-17-cloud-amd64
         处理器架构: amd64v3
         虚拟化: kvm
         IPv4: 34.92.223.97  香港  GOOGLE-CLOUD-PLATFORM
         IPv6:
         WARP 网络接口未开启

 > 1.  为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv4 优先 (bash warp-go.sh 4)
 > 2.  为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv6 优先 (bash warp-go.sh 4)
 > 3.  为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6)
 > 4.  为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv6 优先 (bash warp-go.sh 6)
 > 5.  为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv4 优先 (bash warp-go.sh d)
 > 6.  为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv6 优先 (bash warp-go.sh d)
 > 7.  为 IPv4 only 添加 WARP IPv4 非全局 网络接口，IPv4 优先 (bash warp-go.sh n)
 > 8.  为 IPv4 only 添加 WARP IPv4 非全局 网络接口，IPv6 优先 (bash warp-go.sh n)
 > 9.  同步最新版本 (warp-go v)
 > 0.  退出脚本

 > 请选择: 7

 > 如有 WARP+ 或 Teams 账户请选择
>   1. WARP+
>   2. Teams
>   3. 使用免费账户 (默认)

>  请选择: 3

>  进度 1/3: 安装系统依赖……

> --2022-08-30 17:51:14--  https://gitlab.com/ProjectWARP/warp-go/-/releases/v1.0.5/downloads/warp-go_1.0.5_linux_amd64v3.tar.gz
Resolving gitlab.com (gitlab.com)... 172.65.251.78
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://gitlab.com/ProjectWARP/warp-go/uploads/c4b25251942e4be731a44bae59127590/warp-go_1.0.5_linux_amd64v3.tar.gz [following]
--2022-08-30 17:51:14--  https://gitlab.com/ProjectWARP/warp-go/uploads/c4b25251942e4be731a44bae59127590/warp-go_1.0.5_linux_amd64v3.tar.gz
Reusing existing connection to gitlab.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 2412153 (2.3M) [application/octet-stream]
Saving to: '/opt/warp-go/warp-go_1.0.5_linux_amd64v3.tar.gz'

> /opt/warp-go/warp-go_1.0.5_linux_amd64v3.tar.gz                100%[=================================================================================================================================================>]   2.30M  5.69MB/s    in 0.4s

> 2022-08-30 17:51:15 (5.69 MB/s) - '/opt/warp-go/warp-go_1.0.5_linux_amd64v3.tar.gz' saved [2412153/2412153]

 > 进度 2/3: 已安装 warp-go

 > 后台获取 WARP IP 中,最大尝试5次……
 > 第1次尝试
 > 已成功获取 WARP free 网络
 > 运行在 非全局 模式

==============================================================

 > IPv4: 104.28.247.68  香港  CLOUDFLARENET
 > IPv6:
 > 恭喜！WARP free 已开启，总耗时:13秒
 > 脚本当天运行次数: 1015，累计运行次数：17043

==============================================================

 > 再次运行用 warp-go [option] [lisence]，如

 > warp-go h (帮助菜单）
 warp-go o (临时 warp-go 开关)
 warp-go u (卸载 WARP 网络接口和 warp-go)
 warp-go v (同步脚本至最新版本)
 warp-go i (更换支持 Netflix 的IP)
 warp-go 4/6 (WARP IPv4/IPv6 单栈)
 warp-go d (WARP 双栈)
 warp-go n (WARP IPv4 非全局)
 warp-go g (WARP 全局 / 非全局相互切换)
 > warp-go e (输出 wireguard 配置文件)

**Comment by fscarmen** [comment]
很感谢你的使用和反馈，Netflix 分流需要参数项目主页上面的模板来修改 v2ray / xray 配置，最后重启服务
https://github.com/fscarmen/warp/blob/main/README.md#netflixgoogle-%E5%88%86%E6%B5%81%E5%88%B0-client-warp-%E7%BD%91%E7%BB%9C%E6%8E%A5%E5%8F%A3%E7%9A%84%E6%96%B9%E6%B3%95

**Comment by Yihan-zz** [comment]
多谢解答。由于我对vpn这块还是个新手，想请问下您提供的解答中的这个路由规则，是应该在客户端配置还是在服务端配置？

**Comment by fscarmen** [comment]
> 多谢解答。由于我对vpn这块还是个新手，想请问下您提供的解答中的这个路由规则，是应该在客户端配置还是在服务端配置？

一般用户是这样连接的 本地 v2ray 客户端 ---> vps v2ray 服务端 ---> 分流规则，遇到奈飞域名，分流到通过 warp-go 的 WARP 网络出口 ---> cf  warp 服务端 ---> 奈飞

**Comment by Yihan-zz** [comment]
> > 多谢解答。由于我对vpn这块还是个新手，想请问下您提供的解答中的这个路由规则，是应该在客户端配置还是在服务端配置？
> 
> 一般用户是这样连接的 本地 v2ray 客户端 ---> vps v2ray 服务端 ---> 分流规则，遇到奈飞域名，分流到通过 warp-go 的 WARP 网络出口 ---> cf warp 服务端 ---> 奈飞
> 
> 配置文件就是在你的 vps v2ray 服务端里改配置文件
Thanks ! 目前按照您的路有规则配置在了服务端，配置如下。 
目前的情况是：

- warp-go i显示HK解锁成功，ipv4：104.28.215.69
- 但是netflix无法访问，并不是只能看自制剧，是网站直接无法访问。
- 访问ip.gs，显示ip为104.28.215.69，正是warp-i提供的地址，这说明路由规则和warp都是应该生效的，但是为什么Netflix无法访问呢
> {
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "tag":"CLI_OUT",
      "protocol":"freedom",
      "settings":{
          "domainStrategy":"UseIPv4"
      },
      "sendThrough":"172.16.0.2"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
          "type":"field",
          "outboundTag":"CLI_OUT",
          "domain":[
              "geosite:netflix",
              "domain:ip.gs"
          ]
      }
    ]
  },
  "stats": {}
>}

**Comment by fscarmen** [comment]
试试这样

```
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "tag":"CLI_OUT",
      "protocol":"freedom",
      "settings":{
          "domainStrategy":"UseIPv4"
      },
      "sendThrough":"172.16.0.2"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
          "type":"field",
          "outboundTag":"CLI_OUT",
          "domain":[
              "geosite:netflix",
              "domain:ip.gs"
          ]
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```

**Comment by Yihan-zz** [comment]
> 试试这样
> 
> ```
> {
>   "api": {
>     "services": [
>       "HandlerService",
>       "LoggerService",
>       "StatsService"
>     ],
>     "tag": "api"
>   },
>   "inbounds": [
>     {
>       "listen": "127.0.0.1",
>       "port": 62789,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "address": "127.0.0.1"
>       },
>       "tag": "api"
>     }
>   ],
>   "outbounds": [
>     {
>       "protocol": "freedom",
>       "settings": {}
>     },
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "blocked"
>     },
>     {
>       "tag":"CLI_OUT",
>       "protocol":"freedom",
>       "settings":{
>           "domainStrategy":"UseIPv4"
>       },
>       "sendThrough":"172.16.0.2"
>     }
>   ],
>   "policy": {
>     "system": {
>       "statsInboundDownlink": true,
>       "statsInboundUplink": true
>     }
>   },
>   "routing": {
>     "rules": [
>       {
>           "type":"field",
>           "outboundTag":"CLI_OUT",
>           "domain":[
>               "geosite:netflix",
>               "domain:ip.gs"
>           ]
>       },
>       {
>         "inboundTag": [
>           "api"
>         ],
>         "outboundTag": "api",
>         "type": "field"
>       },
>       {
>         "ip": [
>           "geoip:private"
>         ],
>         "outboundTag": "blocked",
>         "type": "field"
>       },
>       {
>         "outboundTag": "blocked",
>         "protocol": [
>           "bittorrent"
>         ],
>         "type": "field"
>       }
>     ]
>   },
>   "stats": {}
> }
> ```

和之前的情况一样，仍然无法访问Netflix。我尝试在路由规则那里把"geosite:netflix"删去，只剩下"domain:ip.gs"，确实又可以访问了（未解锁版本）

**Comment by Yihan-zz** [comment]
另外，我在服务器上ping ip.gs和ping netflix也是一样的结果
```
root@instance-3:~# ping www.netflix.com
PING apiproxy-website-nlb-prod-1-bcf28d21f4bbcf2c.elb.us-west-2.amazonaws.com (52.38.7.83) 56(84) bytes of data.
^C
--- apiproxy-website-nlb-prod-1-bcf28d21f4bbcf2c.elb.us-west-2.amazonaws.com ping statistics ---
18 packets transmitted, 0 received, 100% packet loss, time 17383ms

root@instance-3:~# ping ip.gs
PING ip.gs (147.78.176.176) 56(84) bytes of data.
64 bytes from 147.78.176.176.static.xtom.de (147.78.176.176): icmp_seq=1 ttl=61 time=245 ms
64 bytes from 147.78.176.176.static.xtom.de (147.78.176.176): icmp_seq=2 ttl=61 time=244 ms
64 bytes from 147.78.176.176.static.xtom.de (147.78.176.176): icmp_seq=3 ttl=61 time=244 ms
64 bytes from 147.78.176.176.static.xtom.de (147.78.176.176): icmp_seq=4 ttl=61 time=244 ms
```

**Comment by Yihan-zz** [comment]
还有更神奇的事，我按照原来的配置。
在可以在浏览器里**访问未解锁的Netflix**的情况下，我竟然在本地**仍然无法ping通** www.netflix.com。
当我换了一个付费的ExpressVPN的节点，可以上解锁的Netflix，同时也可以ping 通Netflix

**Comment by Yihan-zz** [comment]
您好，我在网上找到了一个其他大神采用的SOCKS5的方法，并采用了您目录中的SOCKS5的分流规则，目前已经可以成功解锁Netflix了，十分感谢~

**Comment by fscarmen** [comment]
wireproxy 和 Client 都是 socks5 方案，脚本也有提供一键
