### ISSUE TITLE
[Feature request]: 是不是无法配合Wireguard 一起使用？-【结论：如与其他方案结合着用的，还请玩家多试试，我没有这样的环境，也很难还原现场】

### ISSUE THREAD

**Issue by omomm** [fscarmen/warp#202]
### Related Problem / 相关问题

是不是无法配合Wireguard 一起使用？

### Describe the solution you want / 描述你希望的解决方案

希望可以配合Wireguard 一起使用

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
能详细说说如何与 wireguard 一起使用吗？使用的场景是如何的？

**Comment by omomm** [comment]
大概情况如下：
1.我自己配置了wireguard，然后安装的咱们脚本的内容，也寻找解锁的IP，但是提示失败了，很奇怪尽然IP成了CF的了，进程里看不到warp-go的进程
2.然后我再配置第二台的时候，提示成功了，但是wireguard断流，接收出现了问题，只要配置成功就会出问题。所以基本上就是没有成功了
3.我在想是不是WARP使用的wireguard的方案，部分配置冲突了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fscarmen/warp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月31日(星期三) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fscarmen/warp] [Feature request]: 是不是无法配合Wireguard 一起使用？ (Issue #202)





 
能详细说说如何与 wireguard 一起使用吗？使用的场景是如何的？

**Comment by fscarmen** [comment]
> 1.我自己配置了wireguard，然后安装的咱们脚本的内容，也寻找解锁的IP，但是提示失败了，很奇怪尽然IP成了CF的了，进程里看不到warp-go的进程

`pgrep -laf warp-go` 或者  `systemctl status warp-go` 都可以看到进程和systemd服务正在打开

> 2.然后我再配置第二台的时候，提示成功了，但是wireguard断流，接收出现了问题，只要配置成功就会出问题。所以基本上就是没有成功了
> 3.我在想是不是WARP使用的wireguard的方案，部分配置冲突了

你的意思是连接是： 你本地 wireguard 客户端 -----> vps wireguard 服务端 -----> vps warp 客户端 -----> cf warp 服务端 -----> 外网？ 我没有试过在 vps 里同时搭两者的

同时，你在换ip的时候，正在使用该节点的话会导致断流的，因为他是不变的断开/连接

**Comment by omomm** [comment]
> 

不是不是，稳定IP也是的，所以不晓得怎么回事

**Comment by omomm** [comment]
> > 1.我自己配置了wireguard，然后安装的咱们脚本的内容，也寻找解锁的IP，但是提示失败了，很奇怪尽然IP成了CF的了，进程里看不到warp-go的进程
> 
> `pgrep -laf warp-go` 或者 `systemctl status warp-go` 都可以看到进程和systemd服务正在打开
> 
> > 2.然后我再配置第二台的时候，提示成功了，但是wireguard断流，接收出现了问题，只要配置成功就会出问题。所以基本上就是没有成功了
> > 3.我在想是不是WARP使用的wireguard的方案，部分配置冲突了
> 
> 你的意思是连接是： 你本地 wireguard 客户端 -----> vps wireguard 服务端 -----> vps warp 客户端 -----> cf warp 服务端 -----> 外网？ 我没有试过在 vps 里同时搭两者的
> 
> 同时，你在换ip的时候，正在使用该节点的话会导致断流的，因为他是不变的断开/连接

不是不是，稳定IP也是的，所以不晓得怎么回事

**Comment by omomm** [comment]
> > 1.我自己配置了wireguard，然后安装的咱们脚本的内容，也寻找解锁的IP，但是提示失败了，很奇怪尽然IP成了CF的了，进程里看不到warp-go的进程
> 
> `pgrep -laf warp-go` 或者 `systemctl status warp-go` 都可以看到进程和systemd服务正在打开
> 
> > 2.然后我再配置第二台的时候，提示成功了，但是wireguard断流，接收出现了问题，只要配置成功就会出问题。所以基本上就是没有成功了
> > 3.我在想是不是WARP使用的wireguard的方案，部分配置冲突了
> 
> 你的意思是连接是： 你本地 wireguard 客户端 -----> vps wireguard 服务端 -----> vps warp 客户端 -----> cf warp 服务端 -----> 外网？ 我没有试过在 vps 里同时搭两者的
> 
> 同时，你在换ip的时候，正在使用该节点的话会导致断流的，因为他是不变的断开/连接

可以帮忙看看哦，我觉得wireguard比较快，无论连接还是速度都比较方便，平常自己用，所以也不怎么被封锁-，-

**Comment by fscarmen** [comment]
> 可以帮忙看看哦，我觉得wireguard比较快，无论连接还是速度都比较方便，平常自己用，所以也不怎么被封锁-，-

如果非本脚本自身的问题，可能帮不到你啊

**Comment by omomm** [comment]
> > 可以帮忙看看哦，我觉得wireguard比较快，无论连接还是速度都比较方便，平常自己用，所以也不怎么被封锁-，-
> 
> 如果非本脚本自身的问题，可能帮不到你啊

不一定啊，WARP的配置文件下wireguard的文件目录下，和wireguard本身的文件在一起的，所以这会不会有冲突
然后昨天用openconnect也不得行，难道只能ssr衍生系列可以嘛-，-太局限了嘛
