### ISSUE TITLE
warp-go 脚本如何切换到中文界面-【结论: 改为中文 `echo 'C' > /opt/warp-go/language` ，改为英文 `echo 'E' > /opt/warp-go/language`】

### ISSUE THREAD

**Issue by Mrvivi** [fscarmen/warp#203]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

warp-go脚本默认英文界面，如何切换到中文呢？ 
<img width="473" alt="Snipaste_2022-09-05_12-58-49" src="https://user-images.githubusercontent.com/49402255/188363914-80d22d7d-f369-4802-baf7-7333d2b9e766.png">

### Log / 日志信息

 1.  WARP Non-global IPv4 switch to WARP global IPv4 (warp-go 4)
 2.  WARP Non-global IPv4 switch to WARP Global dualstack (warp-go d)
 3.  Switch to WARP global network interface (warp-go g)
 4.  Turn off warp-go (warp-go o)
 5.  Upgrade to WARP+ or Teams account (warp-go a)
 6.  Change the WARP IP to support Netflix (warp-go i)
 7.  Export wgcf configuration file (warp-go e)
 8.  Uninstall the WARP interface and warp-go (warp-go u)
 9.  Sync the latest version (warp-go v) 
 0.  Exit

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
脚本是以你首次安装的时候选择的语言为后续运行的默认，如要手动更改中文。
```
echo 'C' > /opt/warp-go/language
```

Mrvivi ***@***.***>于2022年9月5日 周一13:03写道：

**Comment by Mrvivi** [comment]
感谢回复 问题已经解决 
![image](https://user-images.githubusercontent.com/49402255/188426654-967f96ec-5880-47ae-9567-f7a64a8b50d4.png)

**Comment by Mrvivi** [comment]
谢谢老板
