### ISSUE TITLE
 注册 teams 账户失败，脚本中止-【结论: 用户长时间没有回复，先行 Closed ，如有问题请继续反馈】

### ISSUE THREAD

**Issue by mongoliabao555** [fscarmen/warp#204]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

第一次安装注册成功后发现连接成功率低，如果显示IP是IPV6地址可以上外网，如是Ipv4地址则不能上外网。一键脚本选择的是5，全局双栈Ipv4优先，很能刷到Ipv6,故重新运行脚本选择关闭warp，然后再次运行脚本选择删除warp,最后 再运行脚本 选6， 全局双栈Ipv6优先则发现注册teams账户失败，用的是https://warp-team-api.herokuapp.com/获取的token,我想应该是重复注册导致失败。

### Log / 日志信息

 进度 1/3: 安装系统依赖……

--2022-09-06 11:56:21--  https://gitlab.com/ProjectWARP/warp-go/-/releases/v1.0.5/downloads/warp-go_1.0.5_linux_amd64v3.tar.gz
Resolving gitlab.com (gitlab.com)... 172.65.251.78
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://gitlab.com/ProjectWARP/warp-go/uploads/c4b25251942e4be731a44bae59127590/warp-go_1.0.5_linux_amd64v3.tar.gz [following]
--2022-09-06 11:56:22--  https://gitlab.com/ProjectWARP/warp-go/uploads/c4b25251942e4be731a44bae59127590/warp-go_1.0.5_linux_amd64v3.tar.gz
Reusing existing connection to gitlab.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 2412153 (2.3M) [application/octet-stream]
Saving to: ‘/opt/warp-go/warp-go_1.0.5_linux_amd64v3.tar.gz’

/opt/warp-go/warp-go_1.0.5_linux_amd64v3.tar.gz 100%[====================================================================================================>]   2.30M  12.8MB/s    in 0.2s

2022-09-06 11:56:22 (12.8 MB/s) - ‘/opt/warp-go/warp-go_1.0.5_linux_amd64v3.tar.gz’ saved [2412153/2412153]

 注册 teams 账户失败，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
很感谢你的支持。
1.注册失败，应该是 token 失效所致的。获取的 token 在上一次卸载后就注销账户失效了，你可以再次获取并安装。
2.同时如果你要切换单双栈，不需要卸载重新安装的，直接  warp-go 4 改为 warp ipv4 ，warp-go 6 改为 warp ipv6 和 warp-go d 改为 warp 双栈的

**Comment by mongoliabao555** [comment]
非常感谢！重新获取token就可以再次安装了。电脑客户端无法连接成功，检查了下，Ipv4 常规设置里面是自动获得DNS服务器地址被改成指定的127.0.2.2和127.0.2.3，如果将其改成1.1.1.1或8.8.8.8则能连上，速度 很慢，如果改成自动获取则不能连。请问如何解决？手机端则没有问题，就是速度 慢点。

**Comment by fscarmen** [comment]
> Ipv4 常规设置里面是自动获得DNS服务器地址被改成指定的127.0.2.2和127.0.2.3

电脑客户端是指哪个？

**Comment by mongoliabao555** [comment]
电脑客户端是Zero Trust，就是Windows下使用不正常，安卓使用正常。还有我发现不用team账号登录连接成功高，用了team改成Zero Trust则基本连不上。问了其它人，没发现这个现象。

**Comment by fscarmen** [comment]
> 电脑客户端是Zero Trust

可能是账户影响了路由吧，具体不同地区可能有差异，这只能用户自己摸索了。

**Comment by fscarmen** [comment]
现在申请 teams 的问题解决了？
