### ISSUE TITLE
甲骨文的韩国首尔安装warp后YouTube页面打开正常，但是打开视频后需要缓冲一分多钟后才能播放-【结论: 有用户在指v2ray分流配置文件里，让油管走v6，问题解决。有同样问题的用户可参考】

### ISSUE THREAD

**Issue by TomKiss888** [fscarmen/warp#206]
### Script / 脚本

menu.sh

### OS / 操作系统

Windows

### Actual Situation / 实际情况

甲骨文的韩国首尔安装warp后YouTube页面打开正常，但是打开视频后需要缓冲一分多钟后才能播放

### Log / 日志信息

甲骨文的韩国首尔安装warp后YouTube页面打开正常，但是打开视频后需要缓冲一分多钟后才能播放，只要开始播放了，随意点击进度条均可正常缓冲

别的网站的视频都是缓冲正常的，电脑Windows和手机ios均出现此问题，卸载到warp后就正常

请问如何解决此问题？谢谢。

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你好，很感谢你的支持和反馈。想了解一下你用什么协议？哪个isp商？哪个客户端？
我在甲骨文的韩国首尔安装warp后，在广东电信或者移动下测试，尽量还原你的场景。

**Comment by TomKiss888** [comment]
你好，江苏电信，v2ray, vless xtls-rprx-direct
谢谢！

**Comment by oplle** [comment]
商家hax和woiden，位置德国，使用此脚本的warp添加v4接口，在油管测试，梯子走v4的时候，和楼上反馈的一样，打开一个新视频页面后会等几十秒，才会开始加载视频进度条，测试换成走v6立马就加载了。

**Comment by fscarmen** [comment]
晚上9:45 ，移动宽带，用不用 warp 都是这个数，没有表情了。
<img width="639" alt="image" src="https://user-images.githubusercontent.com/62703343/191274483-aa77dee2-5bbf-427e-825f-e35f2f9286d6.png">

**Comment by oplle** [comment]
@fscarmen 你这是出口拥堵，我是在网络出口正常的情况下测试的，还测试过别的线路，这问题是最近几天开始的，warp看油管会等几十秒才开始加载，开始加载后速度其实挺快的，问题只在首次进入视频（直播）页面才会这样。

**Comment by TomKiss888** [comment]
@oplle 刚刚换成了v6, 正常了，感谢。

**Comment by TomKiss888** [comment]
@fscarmen 移动用韩国首尔好像网速很差，不过安装楼上的朋友换成v6接口问题就解决了，多谢。

**Comment by fscarmen** [comment]
> 测试换成走v6立马就加载了。

换成v6是指v2ray分流那里让油管走v6是吗？

**Comment by TomKiss888** [comment]
@fscarmen 是的

**Comment by oplle** [comment]
昨天开始已经恢复正常

**Comment by fscarmen** [comment]
> 昨天开始已经恢复正常

无任何操作，视频（直播）的要等长时间这个恢复正常了？

**Comment by oplle** [comment]
对，直接就开始缓冲播放了
