### ISSUE TITLE
[help wanted 求助]: warp client换ip后需要手动重启warp r

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#210]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

环境：用的14选项warp client，安装11设置自动换ip
问题：自动换Netflix ip后，warp卡死，需要手动warp r断开后再warp r重启
建议：在脚本中怎么添加自动换ip后自动warp r 断开后再warp r重启

### Log / 日志信息

netflix not avaiable

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by visense** [comment]
机器是德国的，通过warp client获取的ip是104开头的，看到之前说要修改endpoint，warp client的endpoint在哪修改？

**Comment by fscarmen** [comment]
> 问题：自动换Netflix ip后，warp卡死，需要手动warp r断开后再warp r重启

这个我要稍后试一下，最近几天在重构注册和各账户之间的互换，需要大量测试，所以只能下周处理了。

> warp client的endpoint在哪修改
```
root@c:~# warp-cli set-custom-endpoint --help
warp-cli-set-custom-endpoint 
Force the client to connect to the specified IP:PORT endpoint (Zero Trust customers must run this
command as a privileged user)

USAGE:
    warp-cli set-custom-endpoint <ENDPOINT>

ARGS:
    <ENDPOINT>    

OPTIONS:
    -h, --help    Print help information
```

**Comment by visense** [comment]
辛苦了大佬

**Comment by fscarmen** [comment]
这个卡死的问题还存在吗？

**Comment by visense** [comment]
我每次都是用warp i获取到ip后先warp r断开再来一次warp r连接才能正常
________________________________
发件人: fscarmen ***@***.***>
发送时间: 2022年10月20日 14:02
收件人: fscarmen/warp ***@***.***>
抄送: cocodex211 ***@***.***>; Author ***@***.***>
主题: Re: [fscarmen/warp] [help wanted 求助]: warp client换ip后需要手动重启warp r (Issue #210)


这个卡死的问题还存在吗？

―

**Comment by fscarmen** [comment]
> 我每次都是用warp i获取到ip后先warp r断开再来一次warp r连接才能正常

这有问题哦，用了 `warp r` 相当于重连了一次，IP 跟着变，可能从解决变成不解锁状态的。
