### ISSUE TITLE
warp go 自动开机全局 -【结论: 用户的bbrplus是4.14.129版本的，太低，升级后应该可以正常使用】

### ISSUE THREAD

**Issue by wimdaw** [fscarmen/warp#211]
如题，安装了warp-go脚本，如何开机自动全局？每次开机之后之前设置的全部失效了，重新打开warp-go要重新获取warp ip，没有办法自动全局嘛，之前用的menu.sh 是可以开机自启的

**Comment by fscarmen** [comment]
我这里试过 Oracle , hax 和 euserv 重启， warp-go 全局都是可以的啊，你用以下看看systemd服务是否有启动，如果是 active 就是启动了，如果是 inactive 就是没有启动
```
systemctl is-active warp-go
```

**Comment by wimdaw** [comment]
是 两个脚本都要安装嘛，我先把warp卸载了再装的warp go，debian9和centos7下都无法自启

**Comment by fscarmen** [comment]
> 是 两个脚本都要安装嘛，我先把warp卸载了再装的warp go，debian9和centos7下都无法自启

安装其中一个即可，我在 EUserv 的 Debian 9 上试也是可以的，重启后服务还在。

**Comment by wimdaw** [comment]
![QQ截图20221007191913](https://user-images.githubusercontent.com/29478061/194541575-4b428743-c97c-486c-bd69-6c4224cffbc9.png)
重启就消失了

**Comment by wimdaw** [comment]
输入systemctl is-active warp-go 显示是active
![QQ截图20221007192106](https://user-images.githubusercontent.com/29478061/194541801-670146b9-1838-4ad5-bf7f-6884ac64dee6.png)

**Comment by wimdaw** [comment]
正常情况应该是这样吧
![QQ截图20221007193220](https://user-images.githubusercontent.com/29478061/194543764-3afb7704-cce5-4576-b450-f4a363eab3f5.png)

**Comment by fscarmen** [comment]
对哦，试试用些新一点的系统看看，如 debian 10,11 或者ubuntu 20.04, 22.04

**Comment by wimdaw** [comment]
好像是个依赖问题，怎么更新这个依赖呢？
![QQ截图20221008004545](https://user-images.githubusercontent.com/29478061/194605430-977f5509-ce2f-422c-bc72-0ea7c11ebe5e.png)

**Comment by fscarmen** [comment]
Debian 9
apt -y update;apt -y install wireguard-tools

CentOS 7
yum -y update;yum -y install wireguard-tools

**Comment by wimdaw** [comment]
![QQ截图20221008092359](https://user-images.githubusercontent.com/29478061/194680760-aa490550-0fd8-413d-a9c0-2a569e4d2c00.png)
这个依赖还是没法更新，导致安装出错

**Comment by fscarmen** [comment]
试试像提示那个， 安装  wireguard-dkms  wireguard-modules ，实在不行，应该要升级一下系统了

**Comment by wimdaw** [comment]
![QQ截图20221008093813](https://user-images.githubusercontent.com/29478061/194681229-2f4eb45f-3e68-480e-8c12-53fb426bef99.png)

**Comment by wimdaw** [comment]
找到原因了，应该是开启了bbrplus，导致失败，不开就正常

**Comment by fscarmen** [comment]
> 就正常

你的bbrplus是什么版本的？试试升级最新版本看看问题是否能解决？

**Comment by fscarmen** [comment]
> 找到原因了，应该是开启了bbrplus，导致失败，不开就正常

试过升级 BBRplus 版本吗？

**Comment by wimdaw** [comment]
5.19的bbrplus也无法正常使用，重启了得手动打开

**Comment by fscarmen** [comment]
> 5.19的bbrplus也无法正常使用，重启了得手动打开

我想试一下都不行，开gcp，改为 bbr 新版内核，之后就失联，再也 ssh 不进去了，试了3次都哪些。
