### ISSUE TITLE
[Bug]: warp 命令无法执行-【结论：CentOS 7 安装后不能正常进入菜单 ，原因是 Bug，已处理】

### ISSUE THREAD

**Issue by at2008** [fscarmen/warp#212]
### Expectation / 预期情况

执行warp命令，进入菜单

### Actual Situation / 实际情况

CentOS 7
warp 版本 2.45 

成功！已同步最新脚本，版本号:2.45  功能新增:1. 进一步完善账户间转换功能，你甚至可以从一个 WARP+ 换到另一个; 2. 重构账户注册模块。 
[root@10 ~]# warp
 本脚本只支持 Debian、Ubuntu、CentOS、Arch 或 Alpine 系统,问题反馈:[https://github.com/fscarmen/warp/issues] 

### Reproduction Method / 复现方法

CentOS 7
warp 版本 2.45 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
运行以后指令，把回显发一下
```
bash -x warp
```

**Comment by at2008** [comment]
> 运行以后指令，把回显发一下
> 
> ```
> bash -x warp
> ```

已私发
