### ISSUE TITLE
[QUESTIONS] Can i generate more warp free account?

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#213]
is it fine to generate more warp free account? i think i need like 5 account in one VM. i know it's bit exaggerate generate more profile like this.

**Comment by fscarmen** [comment]
1. Download wgcf from official project.
2. wgcf register --accept-tos --config /etc/wireguard/wgcf-account1.toml
3. wgcf generate --config /etc/wireguard/wgcf-account1.toml --profile /etc/wireguard/wgcf1.conf
4. wgcf register --accept-tos --config /etc/wireguard/wgcf-account2.toml
5. wgcf generate --config /etc/wireguard/wgcf-account1.toml --profile /etc/wireguard/wgcf2.conf
.......

**Comment by malikshi** [comment]
> 1. Download wgcf from official project.
> 2. wgcf register --accept-tos --config /etc/wireguard/wgcf-account1.toml
> 3. wgcf generate --config /etc/wireguard/wgcf-account1.toml --profile /etc/wireguard/wgcf1.conf
> 4. wgcf register --accept-tos --config /etc/wireguard/wgcf-account2.toml
> 5. wgcf generate --config /etc/wireguard/wgcf-account1.toml --profile /etc/wireguard/wgcf2.conf
>    .......

Thanks you very much I will give try
