### ISSUE TITLE
[help wanted 求助]: socks5局域网内其他电脑如何链接，我在本地树莓派安装的脚本开启了socks5-【结论：用户长时间不反馈，暂时关闭，有问题再来一起研究】

### ISSUE THREAD

**Issue by Git-Apt** [fscarmen/warp#214]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

我在新加坡我本地的树莓派建立了socks5它监听于127.0.0.1，内网IP是192.168.2.100，我本机内网IP是192.168.2.200，我通过本机链接树莓派的socks5，一直是无法链接的，树莓派本身链接这个地址是可以链接的上，然后我将监听地址换成0.0.0.0 和192.168.2.100 都无法建立链接，我该怎么办？才能建立链接

### Log / 日志信息

不知道怎么看日志

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你是用 wireproxy 方法吗？把里面的 127.0.0.1 改为 0.0.0.0
如果是 linux 就是 systemctl restart wireproxy 重启一下服务
最后 ss -nltp 看看结果即可
至于草霉派具体是否一样，还请用户自己摸索一下

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/62703343/195979997-7ed38746-a1b4-4ab8-b390-573ef313c2c9.png">

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/62703343/195980052-b170cd28-3e7e-455d-97ac-06c11759db64.png">

**Comment by Git-Apt** [comment]
> 你是用wireproxy的方案吗？ 把里面的127.0.0.1改为0.0.0.0 如果是linux 就是`systemctl restart wireproxy`重启一下服务 最后`ss -nltp`结果能 到草派具体是否一样，还请用户自己摸索一下
> 
> <img alt="图片" width="1190" src="https://user-images.githubusercontent.com/62703343/195979997-7ed38746-a1b4-4ab8-b390-573ef313c2c9.png">
> 
> <img alt="图片" width="1657" src="https://user-images.githubusercontent.com/62703343/195980052-b170cd28-3e7e-455d-97ac-06c11759db64.png">

我不知道我该用那个脚本，我只需要一个sock5.不需要全局代理。

**Comment by fscarmen** [comment]
如果你只要一个socks5代理，可以用 gost 快速搭建啊，可以过去该项目看看:
https://github.com/ginuerzh/gost

**Comment by Git-Apt** [comment]
> [如果你有一个袜子代理可以用 gost://这个泡妞啊，可以过去看看： https](https://github.com/ginuerzh/gost) githubcom/ginzh/gost [](https://github.com/ginuerzh/gost)

我没表达正确，我只需要一个链接了cf的socks5.

**Comment by fscarmen** [comment]
那用 wireproxy 应该可以满足你的需求，脚本有提供方案，只是不知道树霉派是否可以使用脚本。
详细可以了解一下: https://github.com/octeep/wireproxy

**Comment by Git-Apt** [comment]
看了下这个脚本要go语言编译我也安装了go语言也make成功了就是不知道咋开启socks5的CF、它文档也没说的详细。

**Comment by fscarmen** [comment]
他已经编译好相应的go版本了吧，下载来用就行，主要有个配置文件，而模板在项目里有

**Comment by Git-Apt** [comment]
> 他已经编译好相应的go版本了吧，下载来用就行，主要有个配置文件，而模板在项目里有

没看明白这个模板要怎么配置。是要建立一个wireguard链接到CF吗？

**Comment by fscarmen** [comment]
> > 他已经编译好相应的go版本了吧，下载来用就行，主要有个配置文件，而模板在项目里有
> 
> 没看明白这个模板要怎么配置。是要建立一个wireguard链接到CF吗？

如果你通过本脚本安装了 socks5 ，那不是已经是连上了 cf 吗？

**Comment by Git-Apt** [comment]
> > > 他已经编译好相应的版本了，下载来用就行，主要的配置文件，而模板在项目里有
> > 
> > 
> > 没看明白这个模板要怎么配置。是要建立一个wireguard链接到CF吗？
> 
> 如果你通过本脚本安装了socks5，那不是已经连上cf了吗？

我wget https://github.com/octeep/wireproxy 这个文件，也解压了它不知道该怎么配置它./wireproxy 不知道启动啥，大佬有TG群吗

**Comment by fscarmen** [comment]
请问你的问题解决了？
