### ISSUE TITLE
刷ip功能不正常，不能切换地区-【结论: WARP 都是就近分派原则，不支持跨区刷 IP 】

### ISSUE THREAD

**Issue by gnz1123** [fscarmen/warp#215]
### Expectation / 预期情况

输入hk后应该是刷HKip

### Actual Situation / 实际情况

当前 Netflix 地区是:US输入hk后一直不停的刷美国ip

### Reproduction Method / 复现方法

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
不能跨区刷的，warp是就近分配IP，如果是US的机器，只能分配US的

**Comment by gnz1123** [comment]
> 不能跨区刷的，warp是就近分配IP，如果是美国的机器，只能分配美国的

谢谢！不懂的太多还要加强学习
如何查看当前warp ip
有相关学习的tg群吗？

**Comment by gnz1123** [comment]
不懂的太多还需要学习
如何查看当前的warp ip
有相关的tg群吗？

**Comment by fscarmen** [comment]
> 不懂的太多还需要学习 如何查看当前的warp ip 有相关的tg群吗？


Cloudflare WARP第三方客户端 项目组
项目地址 https://gitlab.com/ProjectWARP
讨论群组 https://t.me/+WlUw6xhOTDY3OTdl

**Comment by gnz1123** [comment]
> 不能跨区刷的，warp是就近分配IP，如果是美国的机器，只能分配美国的

现在刷不到解锁ip就不停的刷，如果只想换ip，不需要解锁如何操作

**Comment by fscarmen** [comment]
> > 不能跨区刷的，warp是就近分配IP，如果是美国的机器，只能分配美国的
> 
> 现在刷不到解锁ip就不停的刷，如果只想换ip，不需要解锁如何操作

暂时没有只换ip的功能啊
