### ISSUE TITLE
[help wanted 求助]: 美国洛杉矶的刷出来 WARP IP 为什么会显示是中国深圳的-【结论：经过三个网的判断 ip.gs , ipinfo.io 和 ip.api.com，归属地都为 中国深圳。情况比较特殊，已超出脚本能力范围】

### ISSUE THREAD

**Issue by 404user** [fscarmen/warp#217]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

运行命令后得到的IP居然是中国深圳的，不知道大家有没遇到过这样的问题。服务器是美国洛杉矶的。
![image](https://user-images.githubusercontent.com/7830579/197374557-75d9c140-66ff-47dd-88e6-6ed6403dd6b7.png)

### Log / 日志信息

![image](https://user-images.githubusercontent.com/7830579/197374572-91c48d9c-d965-409b-ac46-1a010401df34.png)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
离谱了，查这些 IP ，全部是深圳的，怎么搞的? 

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/62703343/197375856-5747e6e6-da89-444b-9bed-d048420ea56a.png">

**Comment by 404user** [comment]
> 离谱了，查这些 IP ，全部是深圳的，怎么搞的?
> 
> <img alt="image" width="1517" src="https://user-images.githubusercontent.com/62703343/197375856-5747e6e6-da89-444b-9bed-d048420ea56a.png">

你也是这样吗？

**Comment by fscarmen** [comment]
> > 离谱了，查这些 IP ，全部是深圳的，怎么搞的?
> > <img alt="image" width="1517" src="https://user-images.githubusercontent.com/62703343/197375856-5747e6e6-da89-444b-9bed-d048420ea56a.png">
> 
> 你也是这样吗？

我是查你那些 IP 的归属，我这里没有这样的情况哦。上面补充了查 VPS 原生自带的 IP 和归属地方法，你判断一下。

**Comment by 404user** [comment]
> 

![image](https://user-images.githubusercontent.com/7830579/197376160-2b4a1d29-79d1-4082-8518-dbed3d661d77.png)
查到的原生IP 是洛杉矶的啊。

**Comment by fscarmen** [comment]
怎么送中了？搞不清楚了：（

**Comment by 404user** [comment]
> 

哎，搜索了很久都没找到跟我一样问题的。。。晕死。
