### ISSUE TITLE
[help wanted 求助]: aws ec2服务器刷奈飞IP后，不久变成无法联网-【结论: 如 warp IPv6 能刷到解锁的话，可以试试用户的方法---ipv6使用warp，ipv4用原始ip，ipv6来看奈飞。目前比较稳定，没有出现掉ip现象。】

### ISSUE THREAD

**Issue by rainshadower** [fscarmen/warp#218]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

搭建的亚马逊云新加坡ec2服务器，使用warp一键脚本。
刷了奈飞ip后能用几分钟，然后出现所有ip为空，warp不起用。造成普通联网都困难。
重刷的话又会好一会。
重建新服务器状态依旧。

### Log / 日志信息

脚本版本:2.46   功能新增:通过 [warp s 4/6/d] 来切换 IPv4 / IPv6 的优先级别
 系统信息:
         当前操作系统:Ubuntu 20.04.5 LTS
         内核:5.15.0-1022-aws
         处理器架构:amd64
         虚拟化:xen
         **IPv4:
         IPv6:**
         WARP 网络接口未开启
         WireProxy 未安装

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen2** [comment]
> 刷了奈飞ip后能用几分钟，然后出现所有ip为空，warp不起用。造成普通联网都困难。
> 重刷的话又会好一会。

是不是刷的 IP 失效，正在重刷 IP 运用，导致你的网络不稳定啊？

https://github.com/fscarmen/warp_unlock/issues/33#issuecomment-1286347520

**Comment by fscarmen** [comment]
> 刷了奈飞ip后能用几分钟，然后出现所有ip为空，warp不起用。造成普通联网都困难。
> 重刷的话又会好一会。

是不是刷的 IP 失效，正在重刷 IP 运用，导致你的网络不稳定啊？

https://github.com/fscarmen/warp_unlock/issues/33#issuecomment-1286347520

**Comment by rainshadower** [comment]
> 

不是，你说的这种情况我明白的。
我是已经成功刷到ip，并且已经正常播放，但是过一段时间（小于1天），整个就断了，再ssh看ip变成空。

我以前在别的甲骨文云，甚至awslight都用过这个脚本，都是好的。但是这次在ec2上第一次用却出现了这个问题。我把虚拟机删了重建依旧这个问题。

**Comment by fscarmen** [comment]
试一下不要 wgcf 配置文件里的 dns
```
warp o # 关闭 warp
sed -i "/DNS/s/.*/#&/g" wgcf.conf # 修改配置文件，去掉 dns，使用vps原来的
warp o # 重新打开
```

**Comment by fscarmen** [comment]
请问你的问题解决了吗？

**Comment by rainshadower** [comment]
之后我是用另一个方式，就是ipv6使用warp，ipv4用原始ip，ipv6来看奈飞。目前比较稳定，没有出现掉ip现象。有空我再试试你的方法。

**Comment by fengcharles** [comment]
我也出现同样的问题，vps所有的域名解析都无法通过

**Comment by fscarmen** [comment]
近两周发现有的地区--如美国的vps不能获取到warp ip，包括 wgcf 和  warp-go，我先不要刷，就手动开关一个，看能不能正常获取 IP 呢

**Comment by fengcharles** [comment]
不行，我是美国的VPS 现在什么方式都获取不了了

**Comment by fscarmen** [comment]
> 不行，我是美国的VPS 现在什么方式都获取不了了

![image](https://user-images.githubusercontent.com/62703343/203267402-902b1b54-b6aa-4886-bd6b-61af2b1571bd.png)

**Comment by fengcharles** [comment]
切换成 warp-go 可以用了。非常感谢。
另外wgcf 脚本 一直存在一个问题，就是脚本启动获取IP后，无论成功与否。DNS全部失效，任何网站都无法访问跟断网一样了。必须warp o 强制关闭后，才能恢复。

**Comment by fscarmen** [comment]
> 切换成 warp-go 可以用了。非常感谢。 另外wgcf 脚本 一直存在一个问题，就是脚本启动获取IP后，无论成功与否。DNS全部失效，任何网站都无法访问跟断网一样了。必须warp o 强制关闭后，才能恢复。

这个是严重的bug，如果都是这样，一早炸锅了，所以我推断是你的vps特殊性。可以试试不使用脚本的 dns ，用vps原生的。
具体做法是
```
warp o  # 关闭
sed -i "/DNS/s/.*/#&/g" /etc/wireguard/wgcf.conf # 使用VPS原生的DNS
warp o # 重新打开
```

**Comment by wang001200** [comment]
> 试一下不要 wgcf 配置文件里的 dns
> 
> ```
> warp o # 关闭 warp
> sed -i "/DNS/s/.*/#&/g" /etc/wireguard/wgcf.conf # 修改配置文件，去掉 dns，使用vps原来的
> warp o # 重新打开
> ```

我也遇到这个问题，RN的debian系统，但是是偶发的——用着用着突然断网了，登上vps warp命令发现系统信息里的ipv4没了。也是要warp o 才恢复正常。不知道是不是系统重启导致这个脚本开机运行的时候出问题了。先按照以上DNS修改来看看
另外问下，怎么判断这个脚本是开机自启动的？或者说判断wg网口是开机自启动的？（就是warp o吗？）

**Comment by fscarmen** [comment]
`systemctl status wg-quick@wgcf` 或者  `systemctl status warp-go` 用这个来systemd 来做进程守护的。
