### ISSUE TITLE
似乎warp+烧流量都不会动了了

### ISSUE THREAD

**Issue by Fangliding** [fscarmen/warp#219]
本人闲得无聊 尝试了一下注册一个新ID 刷了4GB warp+流量 然后放进warp-go开跑 跑了几个speedtest但是流量都没有动一点点(从speedtest报告的ISP和速度来看的的确确走了warp) 像是CF已经对warp+这个产品摆烂不管了()

**Comment by fscarmen** [comment]
是的，都不消耗的。只增不减

**Comment by Fangliding** [comment]
![IMG_20221030_233616](https://user-images.githubusercontent.com/45535409/198887505-70ee6b63-2a60-4c82-87a0-8d6fce88cdc4.jpg)
update 似乎这个界面的流量减了 但是点进去账户显示的会从2.71突然跳回4

**Comment by fscarmen** [comment]
你用warp a 升级，或升级后用warp进去后看数据对不上吗？项目说明那有个图，展示app数据刷新方法的

**Comment by Fangliding** [comment]
APP这边刷新了 VPS warp a一下还是4 不过显示的消耗和实际值对不上  再做点测试()

**Comment by fscarmen** [comment]
现在还是对不上吗？

**Comment by clearng** [comment]
我也是，warp+的流量动都不动，用了好几天了，少说也得有30GB，结果他一点没掉

**Comment by fscarmen** [comment]
> 我也是，warp+的流量动都不动，用了好几天了，少说也得有30GB，结果他一点没掉

不要迷恋 plus，他只是个传说

https://github.com/fscarmen/warp/issues/289#issuecomment-1595918026
