### ISSUE TITLE
[ASK] Recommended range ip address of endpoint warp

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#220]
can you give me recommendation for range ip address that work well for endpoint?

**Comment by fscarmen** [comment]
Endpoint IPV4 addressed

162.159.193.* (* value range is 1-10)
162.159.192.* (* value range is 0-254)
162.159.195.* (* value range is 0-254)

Endpoint IPV6 address:

[2606:4700:d0::]
[2606:4700:d1::]

:: can also be added after the value xxxx:xxxx, for example: 2606:4700:d1::1111:1111, the value range is not repeated, Google yourself.

**Comment by malikshi** [comment]
Thanks you very much.

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/83#issuecomment-1030869237
