### ISSUE TITLE
debian11系统纯IPV6主机添加IPV4支持不成功-【结论: 用户使用的 jsDelivr.net  的网址，那个已经没有更新半年了，请使用项目主页的下载链接】

### ISSUE THREAD

**Issue by victorok1234** [fscarmen/warp#221]
每次弹出，这个错误提示，免费账号创建也不成功，急求帮助，非常感谢。
![捕获2345234523](https://user-images.githubusercontent.com/117423073/199881149-ac65fa59-41a1-4cb6-9c60-28ef6715ce2a.PNG)

debian11系统

**Comment by fscarmen** [comment]
从你的截图来看，是连不上github，导致下载不了wireguard-go导致的，请问你这个是大陆vps吗？
试试以下的步骤
```
bash menu.sh u  # 卸载之前的
cp /etc/resolv.conf{,.bak}  # 备份 dns 文件
echo nameserver 8.8.8.8 > /etc/resolv.conf   # 换谷歌 dns
bash menu.sh  # 重新运行
```

**Comment by victorok1234** [comment]
欧洲的，卸载命令不起作用，DNS改后，发现原来能执行的安装warp-go.sh命令突然也不起作用了，原来能执行的这个一键安装命令也无效了，系统原来装的有tailscale没有IPV4地址，只有一个IPv6,现在看这情况貌似全挂了，远程主机该怎样才能实现IPV4和IPV6都能连接呢
![捕获23打发士大夫4523452](https://user-images.githubusercontent.com/117423073/199890297-70bbaf1c-0884-4f12-bdac-ea6f763eb422.PNG)
![捕获3245234234](https://user-images.githubusercontent.com/117423073/199890298-cc188900-3f62-4386-8226-99dfe7519621.PNG)
![捕获12341234](https://user-images.githubusercontent.com/117423073/199890302-0ef863ed-9d5e-488c-b1c1-5da03802db18.PNG)
![捕获3245234](https://user-images.githubusercontent.com/117423073/199890308-6ff44972-d8c5-41c1-9dff-5c8b394f1857.PNG)

**Comment by fscarmen** [comment]
不好意思，我看错了，原来是 ipv6 only，你再改改
```
echo -e "nameserver 2a00:1098:2b::1\nnameserver 2a01:4f9:c010:3f02::1\nnameserver 2a01:4f8:c2c:123f::1\nnameserver 2a00:1098:2c::1" > /etc/resolv.conf
```

**Comment by victorok1234** [comment]
执行过你发的这个命令后，又执行了一下wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh 这个命令，当时一直卡在获取ip提示那里，然后PUTTY客户端就断线了，现在貌似这几个命令都执行不了了，之前安装的有tailscale客户端，PUTTY客户端IPV4联机控制也连不上了……
![54756745](https://user-images.githubusercontent.com/117423073/199897056-3c958a13-9182-4773-b139-2326728cf57c.jpg)
![捕获435634563453](https://user-images.githubusercontent.com/117423073/199897073-6848a0d5-b3fb-42bd-a117-fc4cef397348.PNG)
![捕获23打发士大夫4523452](https://user-images.githubusercontent.com/117423073/199897075-d1a702fe-cd32-4880-a28c-29aa208175bf.PNG)

**Comment by fscarmen** [comment]
方便的话你重置一下，告诉我ssh进去看看

**Comment by victorok1234** [comment]
问题解决了，怀疑是JSDELIVER上的旧版本与这里的新版本，还有tailscale软件存在设置冲突或兼容性的问题，删了重装系统，不装TAILSCALE和JSDELIVR.net上的旧版本，一次就可以成功。非常感谢作者[fscarmen](https://github.com/fscarmen)的精品创作、无私分享、热心解答。

**Comment by fscarmen** [comment]
> 问题解决了，怀疑是JSDELIVER上的旧版本与这里的新版本，还有tailscale软件存在设置冲突或兼容性的问题，删了重装系统，不装TAILSCALE和JSDELIVR.net上的旧版本，一次就可以成功。非常感谢作者[fscarmen](https://github.com/fscarmen)的精品创作、无私分享、热心解答。

JSDELIVR.net 已经废弃很久了，估计上面的版本都是半年前的了。感谢你的支持。如后续有问题请随时过来提issue。
