### ISSUE TITLE
[Bug]: 德基（euserv）会莫名其妙的掉warp然后要再重装一遍-【结论： warp 掉的具体原因我也不清楚，wgcf 的朋友可以在定时任务里加入定时运行下 `warp n` 来获取网络，如果已经有网络，就不会工作，智能的】

### ISSUE THREAD

**Issue by 8ty** [fscarmen/warp#223]
### Expectation / 预期情况

正常运转

### Actual Situation / 实际情况

掉warp ,只剩ipv6

### Reproduction Method / 复现方法

就是正常使用

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
我没有这样的情况哦，掉 warp 的情况经常发生吗？
表现为　wg 有东西显示，连着warp
但 curl -s4m8 ip.gs 没有 ip，实际是断了。

**Comment by 8ty** [comment]
> 我没有这样的情况哦，掉 warp 的情况经常发生吗？ 表现为　wg 有东西显示，连着warp 但 curl -s4m8 ip.gs 没有 ip，实际是断了。

好像是3周内发生过2次，然后是好像warp文件完全没了，而且warp ip 也全没了

**Comment by fscarmen** [comment]
> 好像是3周内发生过2次，然后是好像warp文件完全没了，而且warp ip 也全没了

下次发生这样的情况，发个ssh我进去看看，谢谢！

**Comment by cxw620** [comment]
我的ipv6 only的vps也遇到这个情况, 重新安装才恢复正常. 
~~手动关闭warp后依然没办法上网, (这个应该是dns问题, `nano /etc/network/interfaces`添加dns-nameservers就恢复了)~~

**Comment by fscarmen** [comment]
> 此外我其他的vps也有类似的情况, 不过不频繁, 一个月左右的频率, warp o手动开关就恢复了

暂时未有好办法解决。



> 盲猜euserv的情况比较独特

德鸡已经要收费了，后续不再跟进支持了。还是要谢谢德鸡，脚本有7成工作都是在德鸡上完成的。
