### ISSUE TITLE
[Feature request]: 经实测发现WARP开启后没法与tailscale共存，可否增加的兼容tailscale的功能？-【结论：warp 与其他软件的协同工作，还请用户多自行研究】

### ISSUE THREAD

**Issue by victorok1234** [fscarmen/warp#225]
### Related Problem / 相关问题

ipv6主机连不上

### Describe the solution you want / 描述你希望的解决方案

兼容tailscale

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
全局是会使一些服务，如你说的tailscale，还有docker有端口映射的受影响
你试试用wireproxy或者 client的两个方案，这些是非全局的，之后在v2ray里作分流了。
