### ISSUE TITLE
Azure的Ubuntu 18.06无法创建Socks5-【结论: 已处理，Ubuntu 18.04 官方 Clinet 在 2022.7.472 及之前的版本是正常使用的，而之后的所有版本均不能正常工作，提示`ERROR: No response from daemon after 5 seconds. Is the process hung?`。处理方案是强制 Ubuntu 18.04 使用正常工作的最后一个版本】

### ISSUE THREAD

**Issue by fastincc** [fscarmen/warp#226]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

运行warp脚本 选择第五项时 提示无法创建Socks5

### Log / 日志信息

none

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
用 GCP 开了几台 VPS 试，的确是 Ubuntu 18.04 有点问题，同一个地区的 Ubuntu 20.04 是可以的，说明与地区服务无关，可能是 Client 更新版本的问题，需要长点时间排查。如果可以，请换成 Ubuntu 20.04 或者 22.04

**Comment by fastincc** [comment]
> 用 GCP 开了几台 VPS 试，的确是 Ubuntu 18.04 有点问题，同一个地区的 Ubuntu 20.04 是可以的，说明与地区服务无关，可能是 Client 更新版本的问题，需要长点时间排查。如果可以，请换成 Ubuntu 20.04 或者 22.04

感谢回复 最后我换成debian10 解决了

**Comment by fscarmen** [comment]
经过详细点测试，在 Ubuntu 18.04 的系统上，9月开始的 Client 程序都有问题，包括今天 2022年11月22日 的版本，运行 warp-cli 的一些指令，会提示 `ERROR: No response from daemon after 5 seconds. Is the process hung?`

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/62703343/203255868-7fba9b01-bd3f-4f8c-a3f6-dcb341a92a9c.png">

暂时先定点问题，后续只能强制让 Ubuntu 18.04 使用  2022年8月3日的 2022.7.472 版本。
