### ISSUE TITLE
变更teams账户提示配置格式不对

### ISSUE THREAD

**Issue by iislong** [fscarmen/warp#227]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

配置格式如下：

> [Interface]
PrivateKey = 8HToRWNwZGXAfateTJec9kS6JVDjhO1KbMCvoo9IfEU=
Address = 172.16.0.2/32
Address = fd01:5ca1:ab1e:8126:a1c3:3f7:e648:e5fc/128
DNS = 1.1.1.1
MTU = 1280
[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = engage.cloudflareclient.com:2408

这个是哪里不对，实际内容为自己的，上面贴的仅为格式

### Log / 日志信息

![Screenshot_2022-11-23-13-30-51-186-edit_com sonelli juicessh](https://user-images.githubusercontent.com/2937252/203475400-8b4a9745-6f05-4314-89d1-6b91aea2a839.jpg)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
脚本支持是从安卓模拟器提取出来的 xml 文件格式，因为正则是根据那个内容去匹配的，像这样的，方法可以看项目说明。
```
https://gist.githubusercontent.com/fscarmen/56aaf02d743551737c9973b8be7a3496/raw/61bf63e68e4e91152545679b8f11c72cac215128/2021.12.21
```

**Comment by iislong** [comment]
感谢，已更换成对应的xml文件了。
录入后除了ipv6不对，其他都正常，ipv6好像已自动更换了
