### ISSUE TITLE
[help wanted 求助]: 本地服务器做http代理流量分流

### ISSUE THREAD

**Issue by Atlantis829** [fscarmen/warp#229]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

家里有一个Ubuntu系统服务器，想用它装上warp脚本后，用手机的wifi代理功能（支持持http代理）实现代理上网以达到隐私保护作用，但是我发现不能很好的分流，所有流量被路由至境外，导致境内网站加载十分缓慢，虽然在手机或者电脑的填写代理界面有不走代理的域名可以填写，但是这样非常麻烦，我希望有一个可以值守在ubuntu的软件可以区分境内境外流量，让正常流量走服务器的实际ip，这样不用在手机端安装任何软件就可以，请问有什么解决方案，谢谢

### Log / 日志信息

亲参见实际情况说明

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
wireguard分流不好做的，那个配置文件里 AllowIP 只能填 IP段，而且是白名单制，所以限制很多的，想要分流，我看只能靠终端上的第三方应用，如clash等来处理好得多，但即使clash.meta暂时也不支持wireguard，已经过去提issue希望增加支持，只能等等了。

**Comment by Atlantis829** [comment]
> wireguard分流不好做的，那个配置文件里 AllowIP 只能填 IP段，而且是白名单制，所以限制很多的，想要分流，我看只能靠终端上的第三方应用，如clash等来处理好得多，但即使clash.meta暂时也不支持wireguard，已经过去提issue希望增加支持，只能等等了。
我有一个想法。貌似warp虚拟了一个网卡，假设为，172.0.3.1，貌似这个网卡只有Linux宿主机能访问，是否能将172.0.3.1这个网卡不主动接管任何流量（这时候linux机器为普通网络环境，不能直接访问某些网站），那么将其他终端上的流量全部发送到Linux宿主机，然后Linux宿主机用clash分流，规则内流量进入网卡172.0.3.1网卡，规则外（境内）的直接代理发出，这样是否更加合理呢？172.0.3.1这个网卡是否有http或者socks5接口以供访问呢？谢谢

**Comment by fscarmen** [comment]
你的想法不错，我在公司是以下这个方案，看看是否适合你。
环境，公司网络没有公网IP，局域网的一台 linux 192.168.0.100 安装了 wireproxy，即是连着 warp，监听着 0.0.0.0:40000。因为没有公网，我不怕外部的机器来访问，所以wireproxy建的Socks5我把监听的范围从172.0.0.1改为0.0.0.0，也没有设置用户名和密码了。

我需要终端 PC安装了clash，这样的情况下：
1. 国内网站 : 终端---clash 规则为直连 direct---国内网
2. 国外网站: 终端---clash 规则到局域网 192.168.0.100:40000 --- warp---国外网

**Comment by Atlantis829** [comment]
> 你的想法不错，我在公司是以下这个方案，看看是否适合你。 环境：公司网络没有公网IP，局域网的一台 linux 192.168.0.100 安装了 wireproxy，即是连着 warp，监听着 0.0.0.0:40000。因为没有公网，我不怕外部的机器来访问，所以wireproxy建的Socks5我把监听的范围从172.0.0.1改为0.0.0.0，也没有设置用户名和密码了。
> 
> 我需要终端 PC安装了clash，这样的情况下：
> 
>     1. 国内网站 : 终端---clash 策略为直连 direct---国内网
> 
>     2. 国外网站 : 终端---clash 策略到局域网 socks5://192.168.0.100:40000 --- warp---国外网

这种情况下貌似Linux是全外网环境吗？

**Comment by fscarmen** [comment]
> 这种情况下貌似Linux是全外网环境吗？

不是的，IPv4 是电信网， wireproxy 建的 socks5 才是连着外网，这样对宿主机 Linux 的影响很少的。

**Comment by fscarmen** [comment]
你的问题解决了？如果是，有些什么好经验分享一下？
