### ISSUE TITLE
建议添加自动设置最优mtu-【结论：2.08 已新增该功能】

### ISSUE THREAD

**Issue by OnlyFor** [fscarmen/warp#23]
参考

https://github.com/P3TERX/warp.sh/blob/main/warp.sh

中的

Get_WireGuard_Interface_MTU()

谢谢

**Comment by fscarmen** [comment]
2021.11.1  2.08 版本已经支持自动设置最优MTU
参考文章
https://www.cnblogs.com/wjoyxt/p/6873714.html
https://zhidao.baidu.com/question/341744899.html
https://blog.51cto.com/kfyxw/705918

参考项目 P神
https://github.com/P3TERX/warp.sh/blob/main/warp.sh

**Comment by OnlyFor** [comment]
今天上午试了一下最新版本，非常奇怪，

我的环境是gcp的debain11，安装完默认mtu是1280，
然后以前我用P神的项目的时候mtu是自动设置为1380，是可以正常上网使用的，
今天更新以后的版本，发现mtu自动改到了1460，但是连不上网了。。。连续try10次都不行，

看了一下串口，每次网络请求都会有的日志显示：
systemd-udevd[xxx]: autonegotiation is unset or enabled, the speed and duplex are not writable.

这方面没什么积累也不是很懂，是因为gcp的mtu太高会断网吗？

暂时没有时间仔细测试，目前切回以前1280的版本是可以正常运行的，

猜测和搜索的结果如下供参考：
1.warp plus机制和warp不一样导致以前1380可以但是现在1460不行？
2.https://issueexplorer.com/issue/hwdsl2/setup-ipsec-vpn/1000
3.https://github.com/StreisandEffect/streisand/issues/1552
4.https://webcache.googleusercontent.com/search?q=cache:oE44PPddDWkJ:https://www.willnet.net/index.php/archives/137/+&cd=2&hl=zh-CN&ct=clnk&gl=us

**Comment by fscarmen** [comment]
我用 GCP Debian 11 是没有问题的哦，MTU 也是 1460
![image](https://user-images.githubusercontent.com/62703343/139817962-aa20c69c-fa35-4e51-abad-303837c60e75.png)

![image](https://user-images.githubusercontent.com/62703343/139817308-b3097f45-3fda-4fdc-a2b0-4a7b6b2c0969.png)

**Comment by fscarmen** [comment]
我把用  ```warp o``` 把 warp 关了。用以下值去试，发现的确MTU是1460呢

```
root@hk:~# ping -c3 -s 1432 -M do 162.159.192.1
PING 162.159.192.1 (162.159.192.1) 1432(1460) bytes of data.
1440 bytes from 162.159.192.1: icmp_seq=1 ttl=57 time=2.04 ms
1440 bytes from 162.159.192.1: icmp_seq=2 ttl=57 time=2.36 ms
1440 bytes from 162.159.192.1: icmp_seq=3 ttl=57 time=2.17 ms

--- 162.159.192.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 2.042/2.192/2.363/0.131 ms
root@hk:~# ping -c3 -s 1433 -M do 162.159.192.1
PING 162.159.192.1 (162.159.192.1) 1433(1461) bytes of data.
ping: local error: message too long, mtu=1460
ping: local error: message too long, mtu=1460
ping: local error: message too long, mtu=1460

--- 162.159.192.1 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2028ms

root@hk:~# ping -c3 -s 1432 -M do 1.0.0.1
PING 1.0.0.1 (1.0.0.1) 1432(1460) bytes of data.
1440 bytes from 1.0.0.1: icmp_seq=1 ttl=57 time=3.08 ms
1440 bytes from 1.0.0.1: icmp_seq=2 ttl=57 time=3.44 ms
1440 bytes from 1.0.0.1: icmp_seq=3 ttl=57 time=2.94 ms

--- 1.0.0.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 2.937/3.149/3.435/0.209 ms
root@hk:~# ping -c3 -s 1433 -M do 1.0.0.1
PING 1.0.0.1 (1.0.0.1) 1433(1461) bytes of data.
ping: local error: message too long, mtu=1460
ping: local error: message too long, mtu=1460
ping: local error: message too long, mtu=1460

--- 1.0.0.1 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2051ms
```

**Comment by fscarmen** [comment]
艹，可能翻车了。wgcf作者说设大了没有什么卵用，反而会因MTU值带来一些兼容性的问题。

https://github.com/ViRb3/wgcf/issues/40

**Comment by OnlyFor** [comment]
感觉作者的尝试与回复，那我就维持现状1280吧。。。开始想多了以为提高mtu会加速。。。

**Comment by OnlyFor** [comment]
而且我内核用了xanmod，并且经常更新，有点兼容性问题也不好说

**Comment by fscarmen** [comment]
应该不关xanmod事的，看p神把找到的值-80的

**Comment by OnlyFor** [comment]
好的，谢谢大佬，我明天再试一下

**Comment by fscarmen** [comment]
wgcf原作者关于MTU的issue回复，他自己的测速，说1420只剩下不到一半速度，1280和1392的速度与原始不带warp的速度是一样的

> I also want to note that while leaving the mtu as default would _rarely_ work on my network, my speed is more than halved. Here are my speedtest stats:
> 
> * No Warp: 110-120Mbps
> * With warp and default 1420 mtu: 50Mbps
> * With warp and 1280 mtu: 110-120Mbps
> * With warp and 1392 mtu: 110-120Mbps
> 
> I don't have any speed change with warp when my mtu is set properly (1280 vs 1392).

**Comment by OnlyFor** [comment]
好的，谢谢

**Comment by fscarmen** [comment]
哈哈，找到关于 wireguard header 说明了。
https://lists.zx2c4.com/pipermail/wireguard/2017-December/002201.html
https://www.reddit.com/r/WireGuard/comments/mjcbcc/mtu_issuequestions/

> The overhead of WireGuard breaks down as follows:
> 
> - 20-byte IPv4 header or 40 byte IPv6 header
> - 8-byte UDP header
> - 4-byte type
> - 4-byte key index
> - 8-byte nonce
> - N-byte encrypted data
> - 16-byte authentication tag
> 
> So, if you assume 1500 byte ethernet frames, the worst case (IPv6)
> winds up being 1500-(40+8+4+4+8+16), leaving N=1420 bytes. However, if
> you know ahead of time that you're going to be using IPv4 exclusively,
> then you could get away with N=1440 bytes.


> This means: If you only have IPv4 on your outer channel, you can set the Wireguard MTU to 60 bytes less than the outer MTU. If your outer channel has also IPv6 and if you're going to contact the endpoint via it, you're good with 80 bytes less.
> 
> If you're using PPPoE, for instance DSL, you typically have 1492 bytes as the MTU on the link after your DSL modem.
> 
> A typical problem is: People set the MTU to 1440 or 1420 bytes because they're unaware of the PPPoE-header.

**Comment by OnlyFor** [comment]
实测没问题，可以正常运行，好像速度有提升

**Comment by fscarmen** [comment]
现在GCP的MTU是 1380吧？

**Comment by OnlyFor** [comment]
是的，我看了一下，最新脚本运行完是1380，整个过程非常顺滑
