### ISSUE TITLE
[help wanted 求助]: 关于优先级的问题

### ISSUE THREAD

**Issue by itcut** [fscarmen/warp#231]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

目前是AWS 双栈，想用Warp来刷Disney 解锁，只添加了IPv6，开启了Wireproxy设置了Socks，xray已经配置好了分流，解锁ok。

但是发现所有IPv6流量都走了warp（本意只想disney走warp），如果要实现除了Disney以外的其它IPv6流量还是走本机，是否只能选择iptable + dnsmasq + ipset 方案？

感谢大佬！

### Log / 日志信息

。。。

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
wireguard只能根据 ip-cidr 来分流，像谷歌的 IPv6可以通过以下方式获取
`curl -sL https://www.gstatic.com/ipranges/goog.json | grep ipv6Prefix | cut -d \" -f4`

如果你找到奈飞的IP段，可以添加入 `/etc/wireguard/proxy.conf` 的 [Peer] 下添加 AllowedIPs =
