### ISSUE TITLE
[help wanted 求助]: Warp go如何使用

### ISSUE THREAD

**Issue by ASentimentalMan** [fscarmen/warp#232]
### Script / 脚本

warp-go.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

大神您好
我按照文档安装了warp-go

`wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh [option] [lisence]`

提示我已经有了ip
使用nv测试后，还是提示我只能观看自制

`wget -O nf https://github.com/sjlleo/netflix-verify/releases/download/v3.1.0/nf_linux_amd64 && chmod +x nf && ./nf`

机器在阿里云hk，没有ipv6

我已经试过了所有的全局+freedom，只能看自制
所有的非全局+rules，直接打不开（参考[Issue #200](https://github.com/fscarmen/warp/issues/200)）
ping了engage.cloudflareclient.com可以通（参考[Issue #83](https://github.com/fscarmen/warp/issues/83)）

实在找不到问题在哪
请指教到底warp-go要怎么用

### Log / 日志信息

<img width="614" alt="WeChatb27467b4783182e9e2e14eb494d3787c" src="https://user-images.githubusercontent.com/34683131/204256027-8d25ded5-6191-4b4e-8a17-f173043e93f4.png">

<img width="340" alt="WeChat62d2b1ef7fed3235ecab5f52ac1460f2" src="https://user-images.githubusercontent.com/34683131/204256352-e5c2b7ae-adcd-406e-a956-9c29c6553122.png">

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
并非所有的WARP IP都是解锁的，而且有的地方 V4能解锁，有的地方V6能解锁，你可以试试。记得只有在全局下才能用nv的，非全局不能，因为nv不知道检测 warp 的专用网络接口。
刷解锁IP可以用专用项目: https://github.com/fscarmen/warp_unlock

**Comment by ASentimentalMan** [comment]
现在不知道warp-go到底起没起作用
我把服务器重制之后，直接运行nv说我是sg的ip
运行warp-go选hk之后，还是sg的ip
用warp-go重新获取ip，虽然成功了，但是没有变过
用warp_unlock最少5分钟才能刷一下，看日志ip也没有变过
要怎么样才能知道软件在正常工作呢
或者有没有办法把ipv4的nf流量转到那个可以用的ipv6上呢

**Comment by ASentimentalMan** [comment]
我把v2的outbounds设置为走172.16.0.2
不管warp-go设置为全局还是非全局
所有的网站都打不开
是不是可以理解为warp-go没起作用
![WeChat8b0061a039c605870810f419f3817f05](https://user-images.githubusercontent.com/34683131/204290280-fd8cace4-2a93-42da-9feb-693c73b9ecbf.png)
![WeChatdc4d66dbd5f7e71466cd8a22dcd86507](https://user-images.githubusercontent.com/34683131/204290319-b63f0bff-bd64-460a-a123-38f4e57624da.png)

**Comment by fscarmen** [comment]
如果是全局 v2ray 配置文件不需要另外设置的哦，你先试试把warp-go关了 `warp-go o`，再看看科学是否正常，如果正常，再`warp-go o`重新连上warp试试，现在很难判断。

**Comment by ASentimentalMan** [comment]
warp-go生成的网卡不管是不是全局根本没有网

![WeChateef72d38f28cec5404127893c64a2b27](https://user-images.githubusercontent.com/34683131/204479671-5c284192-7881-4718-837b-1a38292262b4.png)

**Comment by fscarmen** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/62703343/204480325-1c153d62-5e34-4af5-ac8b-0414bafb40fc.png">
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/62703343/204480368-83f732b2-1735-48d3-ba06-86b41f169898.png">

**Comment by fscarmen** [comment]
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/62703343/204480786-4aca2787-f0d3-41d6-9b50-a2d43fc3a47a.png">

**Comment by ASentimentalMan** [comment]
😂搞不定，全都试过了就是没网，不知是不是阿里的问题，谢谢大佬了

**Comment by fscarmen** [comment]
是不是被墙了，你的endpoint是多少的？

**Comment by ASentimentalMan** [comment]
[Interface]
PrivateKey = cDkQtT5hkg4SddhzDyEarHWTveB+l0ZC/cyBddBeFko=
Address    = 172.16.0.2/32
Address    = 2606:4700:110:82c9:f74c:4546:102f:b185/128
DNS        = 1.1.1.1
MTU        = 1280

[Peer]
PublicKey  = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint   = engage.cloudflareclient.com:2408

**Comment by ASentimentalMan** [comment]
应该没有被墙，是通的
![WeChatdac3608a3b8dc216cd493db0723bd928](https://user-images.githubusercontent.com/34683131/204498638-f83fe898-2749-43c7-8980-664790395485.png)

**Comment by ASentimentalMan** [comment]
搞定了，把我的方法记一下，希望后来的朋友有帮助

目标：只有netflix走warp解锁，其它都走服务器自己的流量
服务器：ali hk ipv4 only
nginx v2 都用docker

首先用nf可以看到最原始的服务器状态
![WeChat4c5dda82c721dadd01ca1818e218304b](https://user-images.githubusercontent.com/34683131/204770806-18601c8d-d2c6-4ec5-8a07-b6bbc799b044.png)
此时可以用wrap-go加一个ipv6

安装wrap-go
选择
3.  为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6)

再次用nf能看到
在原来的ipv4地址上多了一个已经可用的ipv6

![WeChatad7f159227302016fb3f4c17ad7bb280](https://user-images.githubusercontent.com/34683131/204772115-f7685e76-1eb8-4310-a632-fbe7f8ee2b99.png)

接下来的目标是让v2走这个ipv6
因为我的v2跑在docker里，默认docker是没有ipv6的，需要按翻官方文档添加支持
运行
vi  /etc/docker/daemon.json
保存内容
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
重启docker
sudo systemctl restart docker
随便进入一个容器
curl -6 ip.p3terx.com
如果通了说明docker可以了

接下来v2配置里需要走nf的加上settings-domainStrategy-UseIPv6
"outbounds": [
    {
      "protocol": "freedom",
      "settings": {
          "domainStrategy": "UseIPv6"
      }
    }
  ]

大功告成

**Comment by ASentimentalMan** [comment]
搞定了，把我的方法记一下，希望后来的朋友有帮助

目标：只有netflix走warp解锁，其它都走服务器自己的流量
服务器：ali hk ipv4 only
v2用的官方docker

首先用nf可以看到最原始的服务器状态
![WeChat4c5dda82c721dadd01ca1818e218304b](https://user-images.githubusercontent.com/34683131/204770806-18601c8d-d2c6-4ec5-8a07-b6bbc799b044.png)
此时可以用wrap-go加一个ipv6

安装wrap-go
选择
3.  为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6)

再次用nf能看到
在原来的ipv4地址上多了一个已经可用的ipv6

![WeChatad7f159227302016fb3f4c17ad7bb280](https://user-images.githubusercontent.com/34683131/204772115-f7685e76-1eb8-4310-a632-fbe7f8ee2b99.png)

接下来的目标是让v2走这个ipv6
因为我的v2跑在docker里，默认docker是没有ipv6的，需要按翻官方文档添加支持
运行
vi  /etc/docker/daemon.json
保存内容
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
重启docker
sudo systemctl restart docker
随便进入一个容器
curl -6 ip.p3terx.com
如果通了说明docker可以了

接下来v2配置里需要走nf的加上settings-domainStrategy-UseIPv6
"outbounds": [
    {
      "protocol": "freedom",
      "settings": {
          "domainStrategy": "UseIPv6"
      }
    }
]

去ip138可以看到ipv4是自己本来的
ipv6是warp提供的

大功告成

**Comment by fscarmen** [comment]
十分感谢你的分享啊。
我从这的配置文件裏没有看出单独奈飞的走IPv6呢，好像是全部的。

**Comment by fscarmen** [comment]
还有之前没有网络的问题是如何解决的呢？

**Comment by ASentimentalMan** [comment]
没有网络的问题我没有解决，我现在./nf -address 172.16.0.2还是说没有网
所以我添加了单独的全局的ipv6，虽然172.16.0.2没有网，实际是可以连上的
没有单独设置奈飞IPv6是我偷懒了，我这个节点专门给TV的
需要单个节点分流的话按照[Issue$200](https://github.com/fscarmen/warp/issues/200)配置应该就可以了

**Comment by ASentimentalMan** [comment]
warp网卡没有网络的问题我没有解决，我现在./nf -address 172.16.0.2还是说没有网
所以我添加了单独的全局的ipv6，虽然172.16.0.2没有网，但是默认的网卡运行./nf，说是可以连上的，实测也可以
没有单独设置奈飞IPv6是我偷懒了，我这个节点专门给TV的
需要单个节点分流的话按照[Issue$200](https://github.com/fscarmen/warp/issues/200)配置应该就可以了

**Comment by ASentimentalMan** [comment]
warp网卡没有网络的问题我没有解决，我现在./nf -address 172.16.0.2还是说没有网
所以我添加了单独的全局的ipv6，虽然172.16.0.2没有网，但是默认的网卡运行./nf，说是可以连上的，实测也可以
没有单独设置奈飞IPv6是我偷懒了，我这个节点专门给TV的
需要单个节点分流的话按照[Issue#200](https://github.com/fscarmen/warp/issues/200)配置应该就可以了
