### ISSUE TITLE
出现了一种新的情况

### ISSUE THREAD

**Issue by areyouokhaha** [fscarmen/warp#234]
用是可以解锁netflix，但是过不了recaptcha😂，就是登录netflix或者使用一些captcha验证的app，比如apkpure会过不了，导致用不了，什么原因😂

**Comment by fscarmen** [comment]
不太了解，德鸡 warp ，clash 全局，浏览器访问 apkpure 并没有弹出验证
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/62703343/204462736-361181ff-f390-465f-8129-3e86d0772e96.png">

**Comment by areyouokhaha** [comment]
这个问题我目前还没有解决，就觉得奇怪，用其它支持奈飞的节点登上去之后，接着用自己搭的节点看就目前只能这样。感觉有点脱裤子放屁的感觉哈哈，登不上去等于用不了😂

**Comment by fscarmen** [comment]
我没有奈飞，所以也不太清楚，看看其他用户的反馈了。我自己使用中，用warp，遇到有验证的网，也是能过的，没有遇到过一直过不了的。
如果奈飞强行加入的 recaptcha 把 warp ip 列为黑名单的话，就无计了。

**Comment by areyouokhaha** [comment]
会不会是vps的问题？因为你也能过apkpure，按道理来说也是能过netflix的，我现在是打开个网页就要认证，出现cloudflare的认证，不过大部分情况都用的了，就是netflix和apkpure这类app验证无法通过用不了，一直卡在那个验证的阶段

**Comment by fscarmen** [comment]
你有没有换另一个地区的节点试试？

**Comment by areyouokhaha** [comment]
没有了，除了机场，我那个vps自搭的是只有美国地区

**Comment by fscarmen** [comment]
要不我建个美国的ss节点，套warp ipv4，刷解锁，你再试试？

**Comment by areyouokhaha** [comment]
咋试？我已经安装好了，等它自己刷ip吗

**Comment by fscarmen** [comment]
想想又是，解锁通知要填你的信息不方便，算了

**Comment by areyouokhaha** [comment]
没事，可惜了，脚本是挺不错，解锁了非自制的，就是登录不上很头痛

**Comment by fscarmen** [comment]
我看其他用户使用正确的，请再检查一下。

**Comment by fscarmen** [comment]
根据其他用户反馈，奈飞没有人机的哦
https://github.com/fscarmen/warp/issues/247#issuecomment-1356684402
