### ISSUE TITLE
[help wanted 求助]: 如何使用自己的warp team-【结论：项目主页有获取 teams 信息的方法，脚本支持更换】

### ISSUE THREAD

**Issue by rainshadower** [fscarmen/warp#235]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

通过其他方式注册了一个team账号，有了私钥和对应的ipv6。那么需要修改哪个文件才能使用？
我找到“/etc/wireguard/wgcf.conf”这个文件，根据自己的私钥和ipv6修改了，保存了。
再运行warp，选择“变更warp账户”。
还是显示原来的这个 Private key    : OoyvpkySqdnZgGnjpVuD9HqUJ5lJiu8ZWo+cMI+/c00=

### Log / 日志信息

请确认Teams 信息
 Private key    : OoyvpkySqdnZgGnjpVuD9HqUJ5lJiu8ZWo+cMI+/c00= ( 符合 √ )
 Public key     : bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo= ( 符合 √ )
 Address IPv4   : 172.16.0.2/32 ( 符合 √ )
 Address IPv6   : fd01:5ca1:ab1e:8fbc:9ebc:f36b:555f:4291/128 ( 符合 √ )

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
更换 Private key 和 Address IPv6 和 endpoint，两次 warp o 即可。
但因为你是手动处理的，并不是用脚本提供的方法，所以脚本不能正确判断出是 team 账户。你用  `curl -ks4 https://www.cloudflare.com/cdn-cgi/trace | grep warp` 看看是不是 plus 了。

**Comment by rainshadower** [comment]
2次warp o，然后在输入在这行crl命令显示warp未打开。但是输入warp进去后看是打开着的。即便看到team在用，如何看到用的是默认的账户还是我的账户？
运行warp a，尝试用你提供的默认方法改成team账户，是把自己的配置发到“gist.github.com”，那么有没有模板？我将wgcf.conf的内容修改后，全部复制发到gist。然后share的url粘贴到ssh后，提示没有在获取到内容。

 请确认Teams 信息
 Private key    : ( 不符合 X )
 Public key     : ( 不符合 X )
 Address IPv4   : /32 ( 不符合 X )
 Address IPv6   : /128 ( 不符合 X )

**Comment by fscarmen** [comment]
> 那么有没有模板？

https://gist.githubusercontent.com/fscarmen/56aaf02d743551737c9973b8be7a3496/raw/61bf63e68e4e91152545679b8f11c72cac215128/2021.12.21

**Comment by rainshadower** [comment]
ok，这已经可以了，但是说我ipv6不符合。同样的配置，我用在WireGuard客户端是可以连通的。

**Comment by fscarmen** [comment]
ipv6 你的是如何的？

**Comment by fscarmen** [comment]
把这个文件上传到网址，获取下载地址，在安装或者升级的时候输入该地址，就会正则匹配相应的内容了。
本项目主页也有获取该文件的方法，大概是用安卓模拟器来提到的，不知道你“根据别人方式”有没有更简便点。

**Comment by rainshadower** [comment]
和这个方式好像差不多，都是用安卓模拟器。我参考的视频https://www.youtube.com/watch?v=Se5kI07k9eA，大概10分钟开始的内容。

**Comment by rainshadower** [comment]
嗯，我们使用的人不太了解各方恩怨，只是网上正好搜索到。我只是使用了他获取team账号的ipv6的方式，并没有使用他的warp脚本。
对比了“https://parkercs.tech/cloudflare-for-teams-wireguard-config/”内容：
**Pulling the Wireguard Configuration**
Go back into Powershell/Command Prompt, and type adb pull /data/data/com.cloudflare.onedotonedotonedotone/shared_prefs/com.cloudflare.onedotonedotonedotone_preferences.xml. This will place the configuration in the platform-tools folder. Go ahead and open it with your favorite editor, VS Code in my case.
也是使用安卓模拟器，拿到的也是“com.cloudflare.onedotonedotonedotone_preferences.xml”这个文件。
所以疑问只是在于ipv6为什么不符合。
当然也有可能他的获取方式在某个步骤是有问题的。

**Comment by fscarmen** [comment]
把 parkercs 获取的 xml 文件，应该是可以使用的哦，如果你仍然不行，可以加我tg @fscarmen2 ，发我看看

**Comment by wanzhiyu** [comment]
> 

我也是ipv6不符合，不明白为什么。
Address IPv6	: ……/128 ( 不符合 X )

**Comment by fscarmen2** [comment]
> > 
> 
> 我也是ipv6不符合，不明白为什么。 Private key : …… ( 符合 √ ) Address IPv6 : ……/128 ( 不符合 X ) 然后后台获取 WARP IP 中,最大尝试5次…… 最后失败。
> 
> 但是很神奇的事情发生了，我再次使用warp a， 当前账户类型是: WARP free
> 
> 1. 继续使用 free 账户，不变更
> 2. 变更为 WARP+ 账户
> 3. 变更为 Teams 账户 (你须事前把 Teams 文件上传到私密存储空间，比如:gist.github.com)
> 4. 退出脚本
> 
> 请选择: 3 请输入 Teams 文件 URL (如果留空，则使用脚本提供的): [https://gist.githubusercontent.com……](https://gist.githubusercontent.com%E2%80%A6%E2%80%A6)
> 
> 请确认Teams 信息 Private key : …… ( 符合 √ ) Address IPv6 : …… ( 不符合 X )
> 
> 确认请按 [y]，其他按键则使用免费账户: y 后台获取 WARP IP 中,最大尝试5次…… 第1次尝试 已成功获取 WARP 网络 IPv4:…… IPv6:…… ( WARP Teams IPv6 ) 日本 Cloudflare 已变更为 WARP teams 账户
> 
> 这就居然成功了？那为什么一开始直接那样不成功必须用免费帐户呢？是不是脚本哪里有问题

应该是正则有点问题，麻烦你把你的 ipv6 发这里一下，你可以改里面几个数字或者字母，但不要删，我看看。

**Comment by fscarmen** [comment]
> 这就居然成功了？那为什么一开始直接那样不成功必须用免费帐户呢？是不是脚本哪里有问题

应该是正则有点问题，麻烦你把你的 ipv6 发这里一下，你可以改里面几个数字或者字母，但不要删，我看看。

**Comment by wanzhiyu** [comment]
> > 这就居然成功了？那为什么一开始直接那样不成功必须用免费帐户呢？是不是脚本哪里有问题
> 
> 应该是正则有点问题，麻烦你把你的 ipv6 发这里一下，你可以改里面几个数字或者字母，但不要删，我看看。

这是我修改了几个数字/字母之后的Address IPv6	: 2606:4710:100:8dba:fe40:b4f1:b561:805e/128 ( 不符合 X )

**Comment by fscarmen** [comment]
> 这是我修改了几个数字/字母之后的Address IPv6 : 2606:4710:101:8dba:fe40:b4f1:b561:805e/128 ( 不符合 X )

我确认一下开关是 2606 是吧？我正则匹配的开头是 fd01 ，这里导致说匹配不正确，我找时间一并处理。
但我设计的时候是留有一手的，即使说不匹配，仍然可以按 y 通过的，所以只要 teams license 正常，是能升级成功的。

**Comment by wanzhiyu** [comment]
> > 这是我修改了几个数字/字母之后的Address IPv6 : 2606:4710:101:8dba:fe40:b4f1:b561:805e/128 ( 不符合 X )
> 
> 我确认一下开关是 2606 是吧？我正则匹配的开头是 fd01 ，这里导致说匹配不正确，我找时间一并处理。 但我设计的时候是留有一手的，即使说不匹配，仍然可以按 y 通过的，所以只要 teams license 正常，是能升级成功的。

我确认了一下，确实是2606

**Comment by fscarmen** [comment]
> 
> 我确认了一下，ipv6地址的开头4位确实是2606

谢谢，虽然显示不匹配，但不影响的，你照确认可以的了。

**Comment by wanzhiyu** [comment]
> 

好的，我暂且先使用warp a修改，期待您的修复，谢谢

**Comment by fscarmen** [comment]
> > 
> 
> 好的，我暂且先使用warp a修改，期待您的修复，谢谢

我试过，即使你安装的时候，显示出错，只要你确认了 y 了，仍然可以升级成功的，不需要再通过 warp a ，可能刚好那时候抽风吧。以下我是估计改了正则，让他显示不匹配的。

<img width="711" alt="image" src="https://user-images.githubusercontent.com/62703343/222086456-0374425e-2705-422f-9e05-71685b39e1ba.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/62703343/222086585-6df925cf-8b4d-4e08-9278-55b6177873d4.png">

**Comment by zzduci** [comment]
> 

我是直接获取了xml文件整个复制的，也是显示IPV6 不符合 我的IPV6是2606:4700开头的
![image](https://user-images.githubusercontent.com/122016328/224528897-6629a0de-0411-4d42-a039-833a8f7029e7.png)

**Comment by zzduci** [comment]
> > 我确认了一下，ipv6地址的开头4位确实是2606
> 
> 谢谢，虽然显示不匹配，但不影响的，你照确认可以的了。

![image](https://user-images.githubusercontent.com/122016328/224529227-9854eef8-272f-467b-b941-a51e02dfca5d.png)
获取不到IP

**Comment by zzduci** [comment]
![image](https://user-images.githubusercontent.com/122016328/224529560-eb407d29-4a06-4334-9004-9f8e62475389.png)

**Comment by fscarmen2** [comment]
> ![image](https://user-images.githubusercontent.com/122016328/224529560-eb407d29-4a06-4334-9004-9f8e62475389.png)

逐步排查吧，你先不要用 teams 信息，就用免费的，看看能不能获取。如果不行，那就是 vps 能否用 wgcf 的问题了。如果免费账户或者而你获取的 teams 账户不行，那就是 teams 账户的问题。你先看看。

**Comment by fscarmen** [comment]
> ![image](https://user-images.githubusercontent.com/122016328/224529560-eb407d29-4a06-4334-9004-9f8e62475389.png)

逐步排查吧，你先不要用 teams 信息，就用免费的，看看能不能获取。如果不行，那就是 vps 能否用 wgcf 的问题了。如果免费账户或者而你获取的 teams 账户不行，那就是 teams 账户的问题。你先看看。

**Comment by zzduci** [comment]
谷歌云VPS，  我试了用免费的账户也获取不到IP，但我的ZEROtrust账户提取出来用wireguard可以用

**Comment by zzduci** [comment]
> > ![image](https://user-images.githubusercontent.com/122016328/224529560-eb407d29-4a06-4334-9004-9f8e62475389.png)
> 
> 逐步排查吧，你先不要用 teams 信息，就用免费的，看看能不能获取。如果不行，那就是 vps 能否用 wgcf 的问题了。如果免费账户或者而你获取的 teams 账户不行，那就是 teams 账户的问题。你先看看。

![image](https://user-images.githubusercontent.com/122016328/224538654-be3b0505-8c7a-4bd2-8ac9-8c682c30a4f1.png)
为什么VC免费机可以获取到IP，而google的VPS不行呢，VC免费机，用ZEROtrust账户一下就获取到IP 了

**Comment by zzduci** [comment]
> > ![image](https://user-images.githubusercontent.com/122016328/224529560-eb407d29-4a06-4334-9004-9f8e62475389.png)
> 
> 逐步排查吧，你先不要用 teams 信息，就用免费的，看看能不能获取。如果不行，那就是 vps 能否用 wgcf 的问题了。如果免费账户或者而你获取的 teams 账户不行，那就是 teams 账户的问题。你先看看。

![1678616887809](https://user-images.githubusercontent.com/122016328/224538826-34a29ad2-7580-4c95-9dae-92334bbc6786.png)
VC机可以获取到IP ，但谷歌VPS好像不行，还有一个问题就是获取不到IP的话，什么网都不通了  我重装了好多次才发现，可以用  warp u  命令全部删掉重启就正常了，我的VC机一下午重装了3次

**Comment by clyde2010** [comment]
我的为什么显示私钥不符合IPV6符合呢？私钥这里也匹配不了？

**Comment by fscarmen** [comment]
> 我的为什么显示私钥不符合IPV6符合呢？私钥这里也匹配不了？

不知

**Comment by zzduci** [comment]
> 我的为什么显示私钥不符合IPV6符合呢？私钥这里也匹配不了？

https://parkercs.tech/cloudflare-for-teams-wireguard-config/  用这个方法提取

**Comment by clyde2010** [comment]
>
不如直接告诉我，config文件包含哪些内容，直接在文件目录下修改
