### ISSUE TITLE
[Bug]: Arch linux上没有找到适合的方案用于修改 warp-go 配置文件 warp.conf

### ISSUE THREAD

**Issue by e5u** [fscarmen/warp#238]
### Expectation / 预期情况

正常安装warp-go

### Actual Situation / 实际情况

```
[root@e5u ~]# wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh 4
--2022-12-01 12:15:14--  https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 63367 (62K) [text/plain]
Saving to: ‘warp-go.sh’

warp-go.sh                 100%[======================================>]  61.88K   325KB/s    in 0.2s    

Last-modified header missing -- time-stamps turned off.
2022-12-01 12:15:15 (325 KB/s) - ‘warp-go.sh’ saved [63367/63367]


 Language:
 1.English (default) 
 2.简体中文 

 Choose: 2
warp-go.sh: line 293: [: : integer expression expected

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 没有找到适合的方案用于修改 warp-go 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp/issues] 
```

### Reproduction Method / 复现方法

` wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh 4`

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
应该是与arch linux无关的，应该是检测vps的单双栈方面出问题。不太好判断，只能ssh进去看看。方便你私我
tg: @fscarmen2

**Comment by fscarmen** [comment]
根据 iputils 说明不再支持 ping6

ping6 went away 3 and a half years ago: https://github.com/iputils/iputils/comm … a72b6af61d

If there are still references to it on the Arch wiki, feel free to fix them up.

https://github.com/iputils/iputils/commit/ebad35fee3de851b809c7b72ccc654a72b6af61d

https://bbs.archlinux.org/viewtopic.php?id=241951
