### ISSUE TITLE
您好 warp +无法使用 

### ISSUE THREAD

**Issue by YiGeRen-yl** [fscarmen/warp#239]
warp  client 不能使用 warp+ 账号

只有wireproxy 才能使用 warp + 账号 很奇怪

**Comment by fscarmen** [comment]
> warp client 不能使用 warp+ 账号

可以啊，输入 License 不是可以吗？安装的时候选择又或者升级的时候使用，检测一下你的 License 是不是超过5台设备了，脚本应该会有提示。

**Comment by YiGeRen-yl** [comment]
真的不行 T14rSj80-1bX9s43c-V723dy9p 这个是我的license 你要不是试一下 账号没超过5个 我这个是在IOS上面买的 LICENSE 一直都不行 很奇怪

**Comment by YiGeRen-yl** [comment]
![1670311427189](https://user-images.githubusercontent.com/75572420/205847255-02a5ae26-671c-4a43-9738-27f413feba2c.png)
wireproxy 是可以的 但是 Client 不行

**Comment by YiGeRen-yl** [comment]
![1670312415352](https://user-images.githubusercontent.com/75572420/205850447-14d57d0b-30ad-41b1-a28e-e4e6350686ec.png)

![dc0c5eb8206c06dbad2b731110818da](https://user-images.githubusercontent.com/75572420/205850181-5dd16eaa-79b4-4e30-a35b-a3d93f32283e.jpg)
在linux WARP CLIENT 里面用了 LICENSE  显示还是FREE 但是手机上已经显示有设备了

**Comment by fscarmen** [comment]
我试下

**Comment by fscarmen** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/62703343/210689407-75f7e6a8-bd7f-4286-a2ee-de83e33ac8ff.png">

你这个 License 可以啊，我安装了两台机器，你把他删了吧。

**Comment by YiGeRen-yl** [comment]
使用 那个模式 是warp客户端还是 proxy

**Comment by fscarmen** [comment]
前者

**Comment by fscarmen** [comment]
试过是可以的

<img width="878" alt="image" src="https://user-images.githubusercontent.com/62703343/221797918-cf1c96d1-ffed-4c7f-b29a-220ffd9ed636.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/62703343/221798202-b761d6da-9f9b-42a0-8a15-64992da99236.png">
