### ISSUE TITLE
无法获取warp ip-【结论：最佳MTU值时，没有减去WireGuard需要的80，已修复】

### ISSUE THREAD

**Issue by taostart** [fscarmen/warp#24]
WARP 注册中…… 
 寻找 MTU 最优值…… 
 创建快捷 warp 指令成功 
 进度  3/3： 运行 WARP 
 后台获取 WARP IP 中,最大尝试10次…… 
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 第6次尝试 
 第7次尝试 
 第8次尝试 
 第9次尝试 
 第10次尝试 
 失败已超过1次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

/*
在多台VPS测试，结果相同
请检查API是否有变化
*/

**Comment by fscarmen** [comment]
我刚在 EUsev，甲骨文和 GCP上试过都可以呢。
你用下面指令，查MTU的数值
```cat /etc/wireguard/wgcf.conf | grep MTU``` 

用下面指令把他改为最保守的 1280，再试试
 ```wg-quick down wgcf; sed -i "s/MTU.*/MTU = 1280/g" /etc/wireguard/wgcf.conf; wg-quick up wgcf```

**Comment by fscarmen** [comment]
>  失败已超过1次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

这里有个参数的小错误，已经改为显示10次错误的，你再试试，如有问题再找我

**Comment by fscarmen** [comment]
> WARP 注册中…… 寻找 MTU 最优值…… 创建快捷 warp 指令成功 进度 3/3： 运行 WARP 后台获取 WARP IP 中,最大尝试10次…… 第1次尝试 第2次尝试 第3次尝试 第4次尝试 第5次尝试 第6次尝试 第7次尝试 第8次尝试 第9次尝试 第10次尝试 失败已超过1次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]
> 
> /* 在多台VPS测试，结果相同 请检查API是否有变化 */

请问你的系统是 CentOS 8吗？脚本有处地方没有判断好CentOS7和8，导致有的 CentOS 8 安装不成功，现在已经修改，有机会安装的时候再试试，谢谢反馈。

**Comment by taostart** [comment]
很抱歉没有即使回复您，今天查收了邮件并登陆vps同步了最新的脚本进行测试
测试如下：
 后台获取 WARP IP 中,最大尝试10次…… 
 第1次尝试 
 第2次尝试 
 已成功获取 WARP 网络
 IPv4:193.38.xxx.22x 俄罗斯 LLC Baxet
 IPv6:2a00:xxxx:4::x4 俄罗斯 LLC Baxet 
这里是我的系统信息:
 脚本版本：2.09  功能新增： 1.支持 WARP Linux Client，Socks5 代理监听:127.0.0.1:40000 
 系统信息：
        当前操作系统：CentOS Linux 7 (Core)
        内核：4.14.129-bbrplus
        处理器架构：amd64
        虚拟化：kvm 
        IPv4：193.38.xx.xx  LLC Baxet 
        WARP 未开启 
        Socks5 Client 未开启

**Comment by fscarmen** [comment]
> 在多台VPS测试，结果相同

你指的多台VPS都是同一个供应商的吗？

**Comment by taostart** [comment]
> > 在多台VPS测试，结果相同
> 
> 你指的多台VPS都是同一个供应商的吗？
并不是的，当时在digitalocean，virmach，euserv均有出现。而上述主机属于justhost。其他主机已通过重装系统解决。目前justhost的主机因为临期所以搁置未处理。

**Comment by fscarmen** [comment]
感谢你的反馈意见
现在上述的系统，除了justhost那个，其他的digitalocean，virmach，euserv 安装都正常了？

**Comment by taostart** [comment]
> 感谢你的反馈意见 现在上述的系统，除了justhost那个，其他的digitalocean，virmach，euserv 安装都正常了？

是的，已经全部成功获取。
感谢您的无私奉献。
