### ISSUE TITLE
[help wanted 求助]: 使用warp-cli在ubuntu 20.04成功登录TEAMS账号后，如何获取privatekey和ipv6地址呢？

### ISSUE THREAD

**Issue by jeremy125** [fscarmen/warp#240]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

我已使用warp-cli在ubuntu 20.04（VMWARE WORKSTATION）成功登录TEAMS账号后，如何获取privatekey和ipv6地址呢？现在网上有的资料都是使用android studio或其他安卓模拟器的方式来获取。

### Log / 日志信息

jeremy@jeremy-virtual-machine:/$ curl https://www.cloudflare.com/cdn-cgi/trace/
fl=12f782
h=www.cloudflare.com
ip=2XXXXXXXXX
ts=16XXXXXXX
visit_scheme=https
uag=curl/7.81.0
colo=LAX
sliver=none
http=http/2
loc=CN
tls=TLSv1.3
sni=plaintext
warp=plus
gateway=off
kex=XXXXX

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是warp-cli还是warp-go？看命令不像是cli

**Comment by jeremy125** [comment]
哦，可能日志有点误导了。  日志里面的内容是我使用官方warp-cli的方式登录到TEAMS账号后，用CURL的方式抓下来，WRAP是PLUS状态，也就是说虚拟机上TEAMS账号已经成功登录了。
现在就是不知道获取privatekey和对应IPV6地址的方式，小白一个，不清楚具体的配置文件在哪儿。

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/228#issuecomment-1326080128

**Comment by jeremy125** [comment]
> 

这个ISSUE我还看过，结果完美忽略了这行。已经找到相应的信息了，谢谢。
