### ISSUE TITLE
[help wanted 求助]: 刷完后IP地区相差比较大。。

### ISSUE THREAD

**Issue by Memory2014** [fscarmen/warp#241]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

对这个不是很清楚，按操作说明进行操作的。。几个脚本都尝试过。。
只有warp-go可以成功刷到IP，但是有些机器刷到了显示解锁，实际仍未解锁。。
现在还有一个问题，刷成功后可以换IP吗？

现在有台洛杉矶的机子，IP查询出来也是显示洛杉矶，但脚本刷完之后一直是纽约的IP，延迟相当于加倍了。。原来200左右，刷完后近400了。。
多次重新安装，刷完后仍是同一地区。。。

想问下怎么可以换IP，脚本是根据什么来确定地区的，，希望延迟不要这么大，或者可以刷相近地区的IP。。。

### Log / 日志信息

。。

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by Memory2014** [comment]
感谢解答。。
我是指刷成功后获取的warp ip，是纽约的。。原机是洛杉矶。。地区跨度比较大
卸载后重新安装多次都就是一样的情况。。每次warp ip都是纽约的

**Comment by fscarmen** [comment]
> 原机是洛杉矶。。

你厉害啊，我和其他网友的 LA 用 warp-go 都没有服务的。

**Comment by fscarmen** [comment]
有可能是 IP 库显示不准确而已。
