### ISSUE TITLE
【这两天获取不到IP的已解决，是由于ip api 服务商ip.gs炸了，现在官网都打不开，换成 ifconfig.co】我不确定 但是他现在不会显示你的ip了 [help wanted 求助]: 

### ISSUE THREAD

**Issue by Bannyfelt13** [fscarmen/warp#242]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

如题

他出现了脚本不显示你的ip  （both v4 / v6）

也许出现了什么问题？

### Log / 日志信息

*

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是的，昨天下午出现的，原因是检测ip用的服务端 ip.gs 炸了，现在官网都打不开，正在找理想的替代。

**Comment by fscarmen** [comment]
已处理，请用 `warp v` 升级一下
