### ISSUE TITLE
[help wanted 求助]: 安装失败，Unable to locate package linux-headers-3.10.0-1160.41.1.vz7.183.5-【结论：Linux 版本太旧，而且是 ovz 不能升级。可以考虑 warp-go 脚本或者实时编译 wireguard-tools】

### ISSUE THREAD

**Issue by DefendFreedom** [fscarmen/warp#243]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

WARP安装失败

 Version:2.46	 New features:Switch the IPv4 / IPv6 priority by [warp s 4/6/d].
 System infomation:
	 Operating System:Debian GNU/Linux 11 (bullseye)
	 Kernel:3.10.0-1160.41.1.vz7.183.5
	 Architecture:amd64
	 Virtualization:openvz 
	 IPv4:      
	 IPv6:      
	 WARP Interface is off 
	 Client is not installed. 
	 WireProxy is not installed.

### Log / 日志信息

Step 1/3: Install dependencies... 

--2022-12-10 07:44:02--  https://github.com/ViRb3/wgcf/releases/download/v2.2.15/wgcf_2.2.15_linux_amd64
0% [Working]2001:67c:2b0:db32:0:1:8c52:7904
Connecting to github.com (github.com)|2001:67c:2b0:db32:0:1:8c52:7904|:443... failed: Connection refused.
--2022-12-10 07:44:02--  https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.15_linux_amd64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
0% [Working]200 OK      
Length: 8687616 (8.3M) [application/octet-stream]
Saving to: '/usr/bin/wgcf'

/usr/bin/wgcf              100%[=======================================>]   8.29M  9.52MB/s    in 0.9s    

2022-12-10 07:44:03 (9.52 MB/s) - '/usr/bin/wgcf' saved [8687616/8687616]

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
iptables is already the newest version (1.8.7-1).
net-tools is already the newest version (1.60+git20181103.0eebece-1).
openresolv is already the newest version (3.12.0-1).
dnsutils is already the newest version (1:9.16.33-1~deb11u1).
Terminated
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Terminated
Terminated
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done

 Step 2/3: WGCF is ready 

E: Unable to locate package linux-headers-3.10.0-1160.41.1.vz7.183.5
E: Couldn't find any package by glob 'linux-headers-3.10.0-1160.41.1.vz7.183.5'

 Step 3/3: Searching for the best MTU value is ready. 

--2022-12-10 07:44:18--  https://raw.githubusercontent.com/fscarmen/warp/main/wireguard-go/wireguard-go_linux_amd64.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1035445 (1011K) [application/octet-stream]
Saving to: 'wireguard-go_linux_amd64.tar.gz'

wireguard-go_linux_amd64.t 100%[=======================================>]   1011K  --.-KB/s    in 0.09s   

Last-modified header missing -- time-stamps turned off.
2022-12-10 07:44:18 (11.1 MB/s) - 'wireguard-go_linux_amd64.tar.gz' saved [1035445/1035445]

 Create shortcut [warp] successfully 
 Running WARP 
 WireGuard tools are not installed or the configuration file wgcf.conf cannot be found, please reinstall. 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
试试 `apt update; apt -y reinstall iputils-ping`，再安装

**Comment by DefendFreedom** [comment]
> 试试 `apt update; apt -y reinstall iputils-ping`，再安装

这次ipv6地址可以获取到了，但安装仍然失败

Step 1/3: Install dependencies... 

--2022-12-10 09:18:59--  https://github.com/ViRb3/wgcf/releases/download/v2.2.15/wgcf_2.2.15_linux_amd64
0% [Working]Resolving github.com (github.com)... 2001:67c:2b0:db32:0:1:8c52:7904
Connecting to github.com (github.com)|2001:67c:2b0:db32:0:1:8c52:7904|:443... failed: Connection refused.
--2022-12-10 09:19:00--  https://raw.githubusercontent.com/fscarmen/warp/main/wgcf/wgcf_2.2.15_linux_amd64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://deb.debian.org/debian bullseye-backports InRelease
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease
0% [Working]200 OK
Length: 8687616 (8.3M) [application/octet-stream]
Saving to: '/usr/bin/wgcf'

/usr/bin/wgcf              100%[=======================================>]   8.29M  10.7MB/s    in 0.8s    

2022-12-10 09:19:01 (10.7 MB/s) - '/usr/bin/wgcf' saved [8687616/8687616]

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
iptables is already the newest version (1.8.7-1).
net-tools is already the newest version (1.60+git20181103.0eebece-1).
openresolv is already the newest version (3.12.0-1).
dnsutils is already the newest version (1:9.16.33-1~deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Terminated
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-3.10.0-1160.41.1.vz7.183.5
E: Couldn't find any package by glob 'linux-headers-3.10.0-1160.41.1.vz7.183.5'
Terminated
Terminated

 Step 2/3: WGCF is ready 


 Step 3/3: Searching for the best MTU value is ready. 

--2022-12-10 09:20:39--  https://raw.githubusercontent.com/fscarmen/warp/main/wireguard-go/wireguard-go_linux_amd64.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1035445 (1011K) [application/octet-stream]
Saving to: 'wireguard-go_linux_amd64.tar.gz'

wireguard-go_linux_amd64.t 100%[=======================================>]   1011K  --.-KB/s    in 0.09s   

Last-modified header missing -- time-stamps turned off.
2022-12-10 09:20:39 (10.8 MB/s) - 'wireguard-go_linux_amd64.tar.gz' saved [1035445/1035445]

 Create shortcut [warp] successfully 
 Running WARP 
 WireGuard tools are not installed or the configuration file wgcf.conf cannot be found, please reinstall.

**Comment by fscarmen** [comment]
`uname -r`  看看 Linux 版本，我感觉太旧了，现在都是5.16还是6.X了

**Comment by DefendFreedom** [comment]
> `uname -r` 看看 Linux 版本，我感觉太旧了，现在都是5.16还是6.X了

3.10.0-1160.41.1.vz7.183.5
确实挺旧的，但openvz是不也没办法升级啊

**Comment by fscarmen** [comment]
`apt update; apt -y install wireguard-tools` 看看能不能安装 wireguard-tools，如果不行，试试用 warp-go 脚本

**Comment by DefendFreedom** [comment]
> `apt update; apt -y install wireguard-tools` 看看能不能安装 wireguard-tools，如果不行，试试用 warp-go 脚本

1.wireguard-tools无法安装完成，会被自动中断
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  apparmor firmware-linux-free linux-image-5.10.0-19-rt-amd64 linux-image-rt-amd64
Suggested packages:
  apparmor-profiles-extra apparmor-utils linux-doc-5.10 debian-kernel-handbook grub-pc | grub-efi-amd64
  | extlinux
The following NEW packages will be installed:
  apparmor firmware-linux-free linux-image-5.10.0-19-rt-amd64 linux-image-rt-amd64 wireguard-tools
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 55.7 MB/56.5 MB of archives.
After this operation, 323 MB of additional disk space will be used.
13% [Working]Terminated

2.warp-go获取账号失败
 Step 1/3: Install dependencies... 

--2022-12-11 00:12:18--  https://gitlab.com/ProjectWARP/warp-go/-/releases/v1.0.6/downloads/warp-go_1.0.6_linux_amd64v3.tar.gz
Resolving gitlab.com (gitlab.com)... 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|2606:4700:90:0:f22e:fbec:5bed:a9b9|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://gitlab.com/ProjectWARP/warp-go/uploads/756c9de8fea091de885db2b4fb33e3f6/warp-go_1.0.6_linux_amd64v3.tar.gz [following]
--2022-12-11 00:12:18--  https://gitlab.com/ProjectWARP/warp-go/uploads/756c9de8fea091de885db2b4fb33e3f6/warp-go_1.0.6_linux_amd64v3.tar.gz
Reusing existing connection to [gitlab.com]:443.
HTTP request sent, awaiting response... 200 OK
Length: 2471646 (2.4M) [application/octet-stream]
Saving to: '/opt/warp-go/warp-go_1.0.6_linux_amd64v3.tar.gz'

/opt/warp-go/warp-go_1.0.6 100%[=======================================>]   2.36M  11.2MB/s    in 0.2s    

2022-12-11 00:12:19 (11.2 MB/s) - '/opt/warp-go/warp-go_1.0.6_linux_amd64v3.tar.gz' saved [2471646/2471646]

 Maximum 5 attempts to registe WARP free account... 
 Try 1 
 Try 2 
 Try 3 
 Try 4 
 Try 5 
 Registration of WARP free account failed, script aborted. Feedback: [https://github.com/fscarmen/warp/issues]

**Comment by DefendFreedom** [comment]
> 试试编译安装 wigreguard-tools
> 
> ```
> apt update
> apt -y install git make
> git clone git@github.com:WireGuard/wireguard-tools.git    # 按  yes
> cd wireguard-tools/src/
> make
> make install
> ```
> 
> 最后用 `type -p wg-quick` 看看有回显即是安装成功了，以下是我的记录
> 
> ```
> ubuntu $ apt update
> Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
> Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease             
> Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease             
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 54 packages can be upgraded. Run 'apt list --upgradable' to see them.
> 
> 
> ubuntu $ apt -y install git make
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> make is already the newest version (4.2.1-1.2).
> git is already the newest version (1:2.25.1-1ubuntu3.6).
> git set to manually installed.
> 0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
> 
> 
> ubuntu $ git clone git@github.com:WireGuard/wireguard-tools.git  # 按 yes
> Cloning into 'wireguard-tools'...
> The authenticity of host 'github.com (140.82.114.4)' can't be established.
> ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
> Warning: Permanently added 'github.com,140.82.114.4' (ECDSA) to the list of known hosts.
> remote: Enumerating objects: 3074, done.
> remote: Counting objects: 100% (279/279), done.
> remote: Compressing objects: 100% (173/173), done.
> remote: Total 3074 (delta 156), reused 200 (delta 99), pack-reused 2795
> Receiving objects: 100% (3074/3074), 665.16 KiB | 13.57 MiB/s, done.
> Resolving deltas: 100% (2065/2065), done.
> 
> 
> ubuntu $ cd wireguard-tools/src/
> 
> 
> ubuntu $ make
>   CC      wg.o
>   CC      config.o
>   CC      curve25519.o
>   CC      encoding.o
>   CC      genkey.o
>   CC      ipc.o
>   CC      pubkey.o
>   CC      set.o
>   CC      setconf.o
>   CC      show.o
>   CC      showconf.o
>   CC      terminal.o
>   LD      wg
> 
> 
> ubuntu $ make install
> 'wg' -> '/usr/bin/wg'
> 'man/wg.8' -> '/usr/share/man/man8/wg.8'
> 'completion/wg.bash-completion' -> '/usr/share/bash-completion/completions/wg'
> 'wg-quick/linux.bash' -> '/usr/bin/wg-quick'
> install: creating directory '/etc/wireguard'
> 'man/wg-quick.8' -> '/usr/share/man/man8/wg-quick.8'
> 'completion/wg-quick.bash-completion' -> '/usr/share/bash-completion/completions/wg-quick'
> 'systemd/wg-quick.target' -> '/lib/systemd/system/wg-quick.target'
> 'systemd/wg-quick@.service' -> '/lib/systemd/system/wg-quick@.service'
> 
> 
> ubuntu $ type -p wg-quick
> /usr/bin/wg-quick
> ```

运行git clone git@github.com:WireGuard/wireguard-tools.git 还是会被 Terminated...

Cloning into 'wireguard-tools'...
Terminated

不过又试了下warp-go，总算获取到了ip

多谢耐心解答~

**Comment by fscarmen** [comment]
太好了，能使用了，我就是觉得奇怪，现在问题点是没有 wireguard-tools 下的 wg-quick ，而 warp-go 又不需要这个，应该能用才对的。
感谢你的使用，支持和反馈。
