### ISSUE TITLE
Teams token website not working

### ISSUE THREAD

**Issue by testermania** [fscarmen/warp#244]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

404 after the enter name and code mail did not come yesterday.

https://web--public--warp-team-api--coia-mfs4.code.run/

### Log / 日志信息

HTTP ERROR 404

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
It's ok. Please check your network. I tested right now. 

[img]https://upload.cc/i1/2022/12/14/YBe8CG.png[/img]

[img]https://upload.cc/i1/2022/12/14/lJ4NSK.png[/img]

[img]https://upload.cc/i1/2022/12/14/FVnlj0.png[/img]

[img]https://upload.cc/i1/2022/12/14/ZyLYc7.png[/img]

**Comment by testermania** [comment]
I don't know what's wrong with my network. everything looks normal and gives the same 404 error with and without vpn.

**Comment by testermania** [comment]
I choose random name, it gives 404. but when I type the name in the picture, it doesn't give 404.

![Capture2](https://user-images.githubusercontent.com/61498468/207818015-65972c10-bb7d-40ae-a409-6b820b408695.PNG)
![Capture](https://user-images.githubusercontent.com/61498468/207818029-e779c76e-b27b-4faa-aade-035df7c629ef.PNG)

**Comment by testermania** [comment]
ı try this email (da2a9097da@emailkom.live) for fscarmen2 Didn’t receive an email.

**Comment by fscarmen** [comment]
Still can't open the site properly?

**Comment by testermania** [comment]
It enters with fscarmen2 but didn’t receive an code email.

**Comment by fscarmen** [comment]
https://developers.cloudflare.com/cloudflare-one/policies/access/

Use your Zero trust name instead. And remember to set the mail address end in .
