### ISSUE TITLE
[Bug]:  IP API 服务商 bug

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#247]
### Expectation / 预期情况

ovh英国服务器在ip.sb、ifconfig.co、ip.gs中显示法国，在ipinfo中显示英国

### Actual Situation / 实际情况

由于warp-go脚本中IP API 服务商显示的地区是法国，导致获取到warp的地区也是法国，服务器实际是英国的，获取不到英国的ip。
ip.gs打开后会被跳转到ip.sb

### Reproduction Method / 复现方法

![image](https://user-images.githubusercontent.com/3490833/208144652-1c7bb992-d697-464a-8b6c-64b9e5a1fd16.png)
上面是https://ip.sb/的显示地区
![image](https://user-images.githubusercontent.com/3490833/208144798-28e1b04b-37cd-4add-ac76-d5055d5a9f64.png)
上面是https://ifconfig.co/的显示地区
![image](https://user-images.githubusercontent.com/3490833/208144938-f29b8b95-c536-4200-ba91-af7c2d30a1fb.png)
上面是https://ipinfo.io/的显示地区

### Log / 日志信息

![image](https://user-images.githubusercontent.com/3490833/208145269-962a3640-d373-47cf-b8be-1c853d0ca57b.png)
warp-go 获取的地区是法国

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
这个显示法国和英国是ip数据库的问题，即是 warp 会根据你 51.38.*.* 的归属地分配 IP 的，而不是看ip.sb, ipinfo.io, ifconfig.co 的。你试试弄几次 warp-go o 开关，重新获取一些 IP 看看。
你也可以使用我的脚本测测回程
```
bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/tools/main/return.sh) [DESTINATION_IP]
```

**Comment by fscarmen** [comment]
| 网络 | 51.38.87.237 | 104.28.243.196 | 
  | --------- | -------- | --------------- |
  | ip.sb | 法国 | 巴黎 , 法国 |
  | ipinfo.io | London, England  |  FR Paris |
  | ifconfig.co |  FR France   | United States |
  | ipget.net | London, England |  Jamaica Kingston |
  | ip125.com | 英国, 英格兰, 倫敦金融城 | 法国, Île-de-France, 巴黎 |
  | ip-moe.zerodream.net |  法国  | 美国 |
  | abuseipdb.com | London, England | Paris, Ile-de-France |
  | ipip.net | 英国伦敦 | 澳大利亚新南威尔士州悉尼 |

综合过往其他用户的情况来看，没有一个 ip api 服务商的数据是完全准确的，据说 ip.sb 是收费的数据库，算是比较准的了。

**Comment by fscarmen** [comment]
问你个问题， 用Warp 的话，奈飞有 recaptcha 人机验证的吗？如果有，能通过的吗？

**Comment by fscarmen** [comment]
引用mjj 的贴子
https://hostloc.com/forum.php?mod=redirect&goto=findpost&ptid=954782&pid=11779530

curl -6 https://ifconfig.co
curl -4 https://ifconfig.co
curl -6 https://ipv6.icanhazip.com
curl -4 https://ipv4.icanhazip.com
curl -6 https://ifconfig.io
curl -4 https://ifconfig.io
curl -6 https://api.myip.com
curl -4 https://api.myip.com
curl -6 https://cloudflare.com/cdn-cgi/trace
curl -4 https://cloudflare.com/cdn-cgi/trace
curl -6 https://ip.fht.im
curl -4 https://ip.fht.im
curl -6 https://bot.whatismyipaddress.com
curl -4 https://bot.whatismyipaddress.com
curl -6 https://www.jsonip.com
curl -4 https://www.jsonip.com
curl -6 https://www.trackip.net/ip
curl -4 https://www.trackip.net/ip
curl -6 https://www.trackip.net/ip?json
curl -4 https://www.trackip.net/ip?json
curl -6 ip.sb
curl -4 ip.sb
dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com
dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com
dig -6 -t aaaa +short myip.opendns.com @resolver1.opendns.com
dig -4 -t a +short myip.opendns.com @resolver1.opendns.com
telnet ipv6.telnetmyip.com
telnet ipv4.telnetmyip.com
telnet -6 telnetmyip.com
telnet -4 telnetmyip.com
ssh -6 sshmyip.com
ssh -4 sshmyip.com

curl -4 https://ip.threep.top
curl -4 https://ip.fm
curl -4 https://cip.cc
curl -4 https://myip.ipip.net
curl -4 https://myip.biturl.top
curl -4 https://checkip.amazonaws.com
curl -4 https://httpbin.org/ip
curl -4 https://pv.sohu.com/cityjson
curl -4 "https://api.ipify.org?format=json"
curl -4 https://lerry.me/ip
curl -4 https://xabc.io/p
curl -4 https://api.akkariin.com:24443/getip/
curl -4 https://ipinfo.io/ip
curl -4 https://ifconfig.me/ip
curl -4 https://ipgrab.io
curl -4 https://myexternalip.com/raw
curl -4k https://whatismyip.akamai.com
curl -4 checkip.dyndns.com
curl -4 checkip.dyndns.org

**Comment by visense** [comment]
> 问你个问题， 用Warp 的话，奈飞有 recaptcha 人机验证的吗？如果有，能通过的吗？

1、感谢大佬回复！！！
2、我这里warp没有recaptcha，
3、测试（向大佬反馈一下）：用warp-go不管是v4还是v6获取的地址一直是法国的cloudfare，自己看了大佬的脚本修改了IP_API地址（ipinfo.io没有v6的curl方法用v4的方法获取的asn，图2），用warp-go任然是法国的地址，如下图
![image](https://user-images.githubusercontent.com/3490833/208284344-d0967dc4-8eb4-4c7f-816d-3da9da7d94f8.png)
![image](https://user-images.githubusercontent.com/3490833/208284368-34000776-f30a-47d6-a1da-446c8110c97c.png)

但是用menu.sh client或者sock5模式获取的地址就是英国的cloudfare，但是最近获取的ip很少（3个左右）

**Comment by fscarmen** [comment]
> 

你的意思是 warp-go 和 wgcf 在同一vps上获取的 ip 不相同？这个我倒没有研究。

**Comment by visense** [comment]
> > 
> 
> 你的意思是 warp-go 和 wgcf 在同一vps上获取的 ip 不相同？这个我倒没有研究。

1、是的，就是这台vps 用warp-go获取的是法国，wgcf获取的是英国（实际是英国机器），warp-go似乎会跳地域；
2、请教大佬：
①docker模式如何修改为v6获取方式（默认是v4），要是可以自己选就好了？
②能不能添加更换ip时间传参功能（默认30秒有点慢）；
![image](https://user-images.githubusercontent.com/3490833/208294696-04271e6d-5a8d-47eb-8172-aa33f5c214e4.png)
③12这个不知道怎么用？看了源码还是一头雾水！请大佬指教
![image](https://user-images.githubusercontent.com/3490833/208294804-f8b598c9-e355-42a0-af84-53c811c6007d.png)

**Comment by fscarmen** [comment]
>  ①docker模式如何修改为v6获取方式（默认是v4），要是可以自己选就好了？ ②能不能添加更换ip时间传参功能（默认30秒有点慢）

docker 是可以弄成 IPv6 的，你查查资料 docker 支持 IPv6 的方式 ，https://blog.csdn.net/avatar_2009/article/details/120081171
同时配置文件可能要改改，把 allowips 那里另上 AllowedIPs = ::/0 让接管 IPv6的流量

>  ②能不能添加更换ip时间传参功能（默认30秒有点慢）；
时间不能再设短了，过短会触发风控，注册不成功导致出错。

> ③12这个不知道怎么用？看了源码还是一头雾水！请大佬指教 !
这个就不用在v2ray里作奈飞的分流了，会根据域名是奈飞，vps分流去  warp 的网络接口，其他没有指定的流量，仍然会走vps原始的网络接口。

**Comment by visense** [comment]
> > ①docker模式如何修改为v6获取方式（默认是v4），要是可以自己选就好了？ ②能不能添加更换ip时间传参功能（默认30秒有点慢）
> 
> docker 是可以弄成 IPv6 的，你查查资料 docker 支持 IPv6 的方式 ，https://blog.csdn.net/avatar_2009/article/details/120081171 同时配置文件可能要改改，把 allowips 那里另上 AllowedIPs = ::/0 让接管 IPv6的流量
> 
> > ②能不能添加更换ip时间传参功能（默认30秒有点慢）；
> > 时间不能再设短了，过短会触发风控，注册不成功导致出错。
> 
> > ③12这个不知道怎么用？看了源码还是一头雾水！请大佬指教 !
> > 这个就不用在v2ray里作奈飞的分流了，会根据域名是奈飞，vps分流去  warp 的网络接口，其他没有指定的流量，仍然会走vps原始的网络接口。

感谢回复！
①更换ip时间传参功能：我刚刚试过，wgcf最短可以到4秒，warp-go最短8秒，再短会频繁出现下面的报错
![image](https://user-images.githubusercontent.com/3490833/208308558-dc82bfc3-af3b-45cc-9df4-747e7f7b199d.png)
②使用 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 可以把vpsip作为dns解锁机吗？下面这个项目同样有dsnmasq，可以做解锁机（且支持ipv6）
https://github.com/myxuchangbin/dnsmasq_sniproxy_install

**Comment by fscarmen** [comment]
> ②使用 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 可以把vpsip作为dns解锁机吗？下面这个项目同样有dsnmasq，可以做解锁机（且支持ipv6）
> https://github.com/myxuchangbin/dnsmasq_sniproxy_install

不是的， iptables + dnsmasq + ipet 的作用是把指定的域名，比如 netflix.com 指向 warp 的网络出口，没有指定的走原生出口，这个会比ip要好，因为某些网可能有多个IP段的，这个方式不需要在 v2ray 上作分流。

你说的这个项目好像是找台原生解锁的机器，让其他机器作dns代理，从而“骗”过奈飞，与 warp 不一样。

**Comment by fscarmen** [comment]
> ①更换ip时间传参功能：我刚刚试过，wgcf最短可以到4秒，warp-go最短8秒，再短会频繁出现下面的报错

不建议太短，因为一旦报错，后面都有可能出问题，而且有的机器慢点，要将就一下。你的机器能多快自己试了之后可以调的时间。
