### ISSUE TITLE
添加支持设置ipv4优先或ipv6优先-【结论：2.10 已新增该功能，支持用户自主选择 IPv4 /IPv6 优先】

### ISSUE THREAD

**Issue by OnlyFor** [fscarmen/warp#25]
目前在完成设置后应该是默认ipv4优先的，有的时候希望能ipv6优先，
我目前是手动设置ipv6优先的，随便找了一个参考的脚本如下：
https://raw.githubusercontent.com/BlueSkyXN/ChangeSource/master/ipv.sh

可以考虑集成一下操作会更便利一些

**Comment by fscarmen** [comment]
阅读了该作者的脚本，大体了解他的思路了，选择运行脚本的话，先还原vps原来的设置，如选ipv4、ipv6优先的话，在/etc/gai.conf插入相当的一行语句，如果选还原vps的话，就什么都不做（因为之前已经做了还原）
这个集成到脚本里也非常简单的，无非就是多个需要选择的而已。开始时不考虑的原因是脚本已经有比较多的选项了。
选项语言->（lxc）选择 wireguard-go 还是boringtun-> 选择是否输入warp+ license
再加一个选择，我怕增加用户的选择困难度！毕竟一键脚本都是希望傻瓜点好。而且应该是考虑线路和网络宽带等，ipv4优先的多吧？所以脚本默认设置为ipv4优先的。

**Comment by fscarmen** [comment]
2021.11.11 2.10 更新：1.Customize the priority of IPv4 / IPv6; 2.Customize the port of Client Socks5; 1.自定义 IPv4 / IPv6 优先组别; 2.自定义 Client Socks5 代理端口

**Comment by OnlyFor** [comment]
感谢！
