### ISSUE TITLE
[help wanted 求助]: 如何使用已有配置文件

### ISSUE THREAD

**Issue by StudenGit** [fscarmen/warp#251]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

在某TG群中看到了如下使用已有配置文件的教程：

不论之前用的是谁的脚本，如果准备用fscarman的脚本安装WARP，那就在刚回答完脚本问的你想用WARP+、Teams还是免费账户，回答优先级别（IPv4、IPv6、VPS初始设置）之前（就选这个时机，不要早也不要迟），新开个ssh会话（或者暂时跳出screen或tmux会话）把之前备份的wgcf-account.toml（fscarman的在/etc/wireguard下，P3TERX的在/etc/warp）恢复到当前路径（就是执行脚本时命令行所在的路径），再继续回答脚本的问题

但是实测似乎并没有效果，/etc/wireguard下的wgcf-account.toml与上传的wgcf-account.toml文件并不一致，实际上还是重新申请了一次账号，将wgcf-account.toml上传到/etc/wireguard/好像也不行

### Log / 日志信息

//

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
如果希望使用你自己的信息，可以在脚本安装好后，`warp o` 先停止wgcf，再把你的信息替换进去 /etc/wireguard/wgcf.conf ，最后 `warp o` 重新开启就可以了

**Comment by StudenGit** [comment]
> 如果希望使用你自己的信息，可以在脚本安装好后，`warp o` 先停止wgcf，再把你的信息替换进去 /etc/wireguard/wgcf.conf ，最后 `warp o` 重新开启就可以了

感谢回复，但是这样的话在安装脚本之后应该已经自动生成了一个配置文件，我的目的是在不生成新配置文件的情况下使用旧的配置文件，p3terx的脚本倒是有方法可以直接调用以前的账号，说是避免了重复申请 WARP 账号导致 IP 被 Cloud­flare 拉黑，但是那个脚本的功能没有你这个多

我个人也有些好奇，那些废弃的不再使用的WARP账号会怎么处理，也担心过多的废弃账号会使以后越难越难以申请新的账号，我个人的几个VPS上的账号都是不一样的

**Comment by fscarmen** [comment]
> 说是避免了重复申请 WARP 账号导致 IP 被 Cloud­flare 拉黑

没有这个说法的，我测试的机器之一，德鸡，同一ip都不知道申请几千上万次了。完全不用担心。


> 那些废弃的不再使用的WARP账号会怎么处理

我也问过 wgcf 的作者 ViRb3 为什么不提供用户注销账户的功能，回复说太忙不能开发，只能就此作罢。

**Comment by StudenGit** [comment]
> > 说是避免了重复申请 WARP 账号导致 IP 被 Cloud­flare 拉黑
> 
> 没有这个说法的，我测试的机器之一，德鸡，同一ip都不知道申请几千上万次了。完全不用担心。
> 
> > 那些废弃的不再使用的WARP账号会怎么处理
> 
> 我也问过 wgcf 的作者 ViRb3 为什么不提供用户注销账户的功能，回复说太忙不能开发，只能就此作罢。

好的，非常感谢！
