### ISSUE TITLE
[help wanted 求助]: Uninstalling

### ISSUE THREAD

**Issue by dxomg** [fscarmen/warp#252]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

I installed it but now i want o uninstall it

### Log / 日志信息

None

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
README.md  and `warp h`

**Comment by fscarmen** [comment]
README.md or `warp h`
