### ISSUE TITLE
[help wanted 求助]: warp-go ipv6 非全局

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#255]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

现在用warp-go刷ipv4只有2到3个ipv4地址能刷出来，想开启warp-go ipv6非全局
看了warp-go.sh，不知道能不能开，如果可以开ipv6非全局，大佬指教一下？

### Log / 日志信息

现在用warp-go刷ipv4只有2到3个ipv4地址能刷出来，想开启warp-go ipv6非全局
看了warp-go.sh，不知道能不能开，如果可以开ipv6非全局，大佬指教一下？

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
处理不了，不会

**Comment by visense** [comment]
> 处理不了，不会

我的操作如下，请大神帮忙研究下
1、用warp-go.sh安装ipv4非全局（选7）
2、打开/opt/warp-go/warp.conf，
把AllowedIPs改为 AllowedIPs = ::/0，并取消下面两个注释
```
#PostUp = /opt/warp-go/NonGlobalUp.sh
#PostDown = /opt/warp-go/NonGlobalDown.sh
```
3、打开/opt/warp-go/NonGlobalUp.sh，把ipv4的地方修改warp网卡的内网ipv6地址
```
sleep 5
ip -6 rule add from fe80::bef7:5705:b4e1:5274 lookup 60000
ip -6 rule add table main suppress_prefixlength 0
ip -6 route add default dev WARP table 60000
```
4、打开/opt/warp-go/NonGlobalDown.sh相应的修改为
```
ip -6 rule delete from fe80::bef7:5705:b4e1:5274 lookup 60000
ip -6 rule delete table main suppress_prefixlength 0
```
5、重启warp-go，两次warp-go，这样原来的warp-go非全局ipv4可以成功获取到ipv6地址

6、验证非全局（参考https://blog.suysker.xyz/archives/235文章中的）
①看出口ipv6地址
`curl -6 ip.p3terx.com`
显示为美国cloudfare，
②再测路由
`ip -6 route get 2001:4860:4860::8888`
显示为warp接口
验证现在为ipv6全局模式，
③接下来查看ipv6路由表
`ip -6 rule`
对照ipv4非全局的规则命令为（ip rule），发现多了个50000的表，用如下命令删除
`ip -6 rule del fwmark 0xc350 lookup 50000`

7、重复第6步的①、②检查ipv6出口和路由，发现用上面的③删除了wmark 0xc350 lookup 50000后ipv6变成了非全局

8、重启warp-go，重新获取ipv6地址，发现重启后又恢复了ipv6全局模式，查看ipv6路由
`ip -6 rule`
发现又多了fwmark 0xc350 lookup 50000`

我不知道大佬你的脚本中设定的哪个参数让ipv6恢复了全局，请帮忙研究下，因为最近部分vps 出现了如下问题
1、用wireproxy 获取不到ipv4地址，导致修改wireproxy参数为ipv6也不能获取ipv6地址
2、warp-go安装成功后，使用warp-go i显示获取ip成功，且解锁奈飞成功，但是用menu.sh的11选项安装warp_unlock.sh后，运行获取ip地址及检测奈飞会显示失败，就是说warp-go i和warp_unlock.sh的结果会不一样
3、用ipv4现在只能获取1到2个ip地址，且解锁不了，ipv6还能解锁，但是在后台运行解锁的时候v2ray会断网，所以产生了运行ipv6非全局的想法，
请大佬指教！

**Comment by fscarmen** [comment]
试试
```
cat /opt/warp-go/NonGlobalDown.sh 
ip -4 rule delete from 172.16.0.2 lookup 60000
ip -4 rule delete table main suppress_prefixlength 0
ip -6 rule delete oif lookup 60000
ip -6 rule delete table main suppress_prefixlength 0


cat /opt/warp-go/NonGlobalUp.sh 
sleep 5
ip -4 rule add from 172.16.0.2 lookup 60000
ip -4 rule add table main suppress_prefixlength 0
ip -4 route add default dev WARP table 60000
ip -6 rule add oif WARP lookup 60000
ip -6 route add default dev WARP table 60000
```

**Comment by visense** [comment]
> 试试
> 
> ```
> cat /opt/warp-go/NonGlobalDown.sh 
> ip -4 rule delete from 172.16.0.2 lookup 60000
> ip -4 rule delete table main suppress_prefixlength 0
> ip -6 rule delete oif lookup 60000
> ip -6 rule delete table main suppress_prefixlength 0
> 
> 
> cat /opt/warp-go/NonGlobalUp.sh 
> sleep 5
> ip -4 rule add from 172.16.0.2 lookup 60000
> ip -4 rule add table main suppress_prefixlength 0
> ip -4 route add default dev WARP table 60000
> ip -6 rule add oif WARP lookup 60000
> ip -6 route add default dev WARP table 60000
> ```

感谢回复，我试试

**Comment by fscarmen** [comment]
我晚点集成吧，最近很懒。
<img width="493" alt="image" src="https://user-images.githubusercontent.com/62703343/209676666-4bac9b1a-f134-4669-aaac-9999cd7f47b1.png">

**Comment by visense** [comment]
> 我晚点集成吧，最近很懒。 <img alt="image" width="493" src="https://user-images.githubusercontent.com/62703343/209676666-4bac9b1a-f134-4669-aaac-9999cd7f47b1.png">

请收下我的膝盖，大佬威武

**Comment by visense** [comment]
> 我晚点集成吧，最近很懒。 <img alt="image" width="493" src="https://user-images.githubusercontent.com/62703343/209676666-4bac9b1a-f134-4669-aaac-9999cd7f47b1.png">

按照上面的路由规则在我的服务器上还是全局的，后面参考了

`https://ro-che.info/articles/2021-02-27-linux-routing`

以及

`https://github.com/P3TERX/warp.sh/blob/main/warp.sh`

里面的

![image](https://user-images.githubusercontent.com/3490833/209731531-50d1d9de-4b2c-4af8-93b6-bcdb777cddca.png)

使用warp-go o后还是不成功，跟大佬反馈下

**Comment by visense** [comment]
![image](https://user-images.githubusercontent.com/3490833/209731669-0f35c9a3-a2f5-4f00-b05c-ad05b033257e.png)
这条不知道是哪来的

**Comment by fscarmen** [comment]
> ![image](https://user-images.githubusercontent.com/3490833/209731669-0f35c9a3-a2f5-4f00-b05c-ad05b033257e.png)
> 
> 这条不知道是哪来的，删了这条变成了非全局，但是过一会会自动添加上， 于是查看warp-go.sh源码
> 
> ![image](https://user-images.githubusercontent.com/3490833/209732418-d714baf2-fcbb-4ce2-8754-d37978460d0f.png)
> 
> 没发现有添加50000这个表

50000 这个表是 warp-go 主程序添加的

**Comment by fscarmen** [comment]
双栈是可以，原生单栈的vps还要测一下，好像不行

**Comment by fscarmen** [comment]
ip.sb 限制了，同一ip使用过多会出来 `error code: 1015` 报错。

**Comment by visense** [comment]
> 原生单栈的vps还要测一下，好像不行

有什么解决方法？

**Comment by fscarmen** [comment]
> > 原生单栈的vps还要测一下，好像不行
> 
> 有什么解决方法？

暂时没有，不稳定，老是测不到IP，所以一直未发布。

**Comment by fscarmen** [comment]
要另外找替代方案了，ip.sb 是托管在cf上有，有个访问限制的。以下是30s一次的，发现几分钟才恢复让访问一次，之后又封。

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/62703343/209915416-2e33fb58-38e1-4161-8447-482141aaa063.png">

**Comment by visense** [comment]
> 

不知道ipv4只能获取到2到3个固定的ip和这个是不是有关系?
https://ipinfo.io/登录以后好像可以用api，大佬你试试

**Comment by fscarmen** [comment]
> > 
> 
> 不知道ipv4只能获取到2到3个固定的ip和这个是不是有关系? [https://ipinfo.io/登录以后好像可以用api，大佬你试试](https://ipinfo.io/%E7%99%BB%E5%BD%95%E4%BB%A5%E5%90%8E%E5%A5%BD%E5%83%8F%E5%8F%AF%E4%BB%A5%E7%94%A8api%EF%BC%8C%E5%A4%A7%E4%BD%AC%E4%BD%A0%E8%AF%95%E8%AF%95)

ipinfo.io IP库是准的，可惜该网只能 ipv4，不支持 ipv6访问 

https://ipw.cn/ipv6webcheck/?site=ipinfo.co

![image](https://user-images.githubusercontent.com/62703343/209951046-ab41280c-fa04-4f32-b8ad-ddc5099d4474.png)

**Comment by visense** [comment]
> > > 
> > 
> > 
> > 不知道ipv4只能获取到2到3个固定的ip和这个是不是有关系? [https://ipinfo.io/登录以后好像可以用api，大佬你试试](https://ipinfo.io/%E7%99%BB%E5%BD%95%E4%BB%A5%E5%90%8E%E5%A5%BD%E5%83%8F%E5%8F%AF%E4%BB%A5%E7%94%A8api%EF%BC%8C%E5%A4%A7%E4%BD%AC%E4%BD%A0%E8%AF%95%E8%AF%95)
> 
> ipinfo.io IP库是准的，可惜该网只能 ipv4，不支持 ipv6访问
> 
> https://ipw.cn/ipv6webcheck/?site=ipinfo.co
> 
> ![image](https://user-images.githubusercontent.com/62703343/209951046-ab41280c-fa04-4f32-b8ad-ddc5099d4474.png)

是的，ipinfo.io后台没有ipv6 方法：https://ipinfo.io/developers
但是如果把IP_API替换成ipinfo.ip能正常持续刷ipv4地址也可以了，下面是之前发的issue及截图
ipinfo.ip相比ip.sb，对应的名称变了看下面的截图

`https://github.com/fscarmen/warp/issues/247`

![image](https://user-images.githubusercontent.com/3490833/209954785-a9bd2f90-72ce-4522-b76a-95ab6ffcd96c.png)

上面因为ipinfo.io没有ipv6，ipv6的api保留了ip.sb，但是后面的代码能力有限搞不下去了。。。

**Comment by visense** [comment]
另外，补充一下，用menu.sh只能刷到3个固定ip，而用P3terx大佬的
https://github.com/P3TERX/warp.sh/blob/main/warp.sh
却能刷出来不通的ip，只是他的脚本不带换ip功能

**Comment by fscarmen** [comment]
越弄越复杂了，暂时先不处理了。

**Comment by visense** [comment]
> 

辛苦大佬了

**Comment by visense** [comment]
> 越弄越复杂了，暂时先不处理了。

大佬，还想请教socks5两种模式如何开启ipv6，默认刷的是ipv4

**Comment by fscarmen** [comment]
> 大佬，还想请教socks5两种模式如何开启ipv6，默认刷的是ipv4

是啊，不处理ipv6了，iptable 那里也要处理的。
