### ISSUE TITLE
[Bug]: Azure获取IP不成功-【结论：有的地区 wgcf 暂停服务，可以试试 warp-go。`wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh; bash warp-go.sh`】

### ISSUE THREAD

**Issue by focsob** [fscarmen/warp#256]
### Expectation / 预期情况

10秒内取得IP

### Actual Situation / 实际情况

时间用了10分钟才尝试完5次，但都没有取得IP (已经使用了WARP+的密匙，手机亦看到)

### Reproduction Method / 复现方法

WARP A 使用WARP+的密匙>没有取得IP
WARP O>没有取得IP

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
试试 warp-go 脚本呢
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh; bash warp-go.sh
```

**Comment by focsob** [comment]
> warp-go

warp-go可以

**Comment by fscarmen** [comment]
有的地方比如香港，只能用 warp-go ，不能用 wgcf，如warp-go可以的话，就继续使用可以了。
