### ISSUE TITLE
[help wanted 求助]: 新加坡区刷不出ip-【结论：有时候某些地方只有2-3个甚至只有1个IP，刷来刷去都一样】

### ISSUE THREAD

**Issue by moelinmtf** [fscarmen/warp#257]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

新加坡区使用WARP刷不出ip，显示ipv4为空，但是显示流媒体解锁

### Log / 日志信息

 当前操作系统:Debian GNU/Linux 11 (bullseye)
         内核:5.10.0-19-amd64
         处理器架构:amd64
         虚拟化:kvm 
         IPv4:  ( WARP IPv4 )    
         IPv6: 2a09:bac1:6540:8::23:1e4 ( WARP IPv6 ) 新加坡  Cloudflare 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
估计是 ip api 服务商 ip.sb 使用了cloudflare 的防刷服务，同一 ip 在一定的时间里不能多次获取，限制次数。如果只是使用一下，是可以获取的，暂时没有太好的解决方案，用 ifconfig.co 是没有限制，但 IP 库不太准，其他的 IP api 服务商要么不支持 IPv6，要么是 IP 库不准，要么没有详细的归属地，isp供应商等信息显示。

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/62703343/210682365-68a55545-8269-460e-9dd0-447bff57bd7f.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/62703343/210682385-0dba3b02-583b-4b91-b94a-09a76f66523e.png">

你用`curl -ks4m5 -A Mozilla https://api.ip.sb/geoip`看看 IPv4

**Comment by visense** [comment]
> ifconfig.co

如何自己修改ip.sb为ifconfig.co？脚本中不知道哪些地方要改，改了怕出问题，大佬能不能指教一下？

**Comment by fscarmen** [comment]
开头几行，你看看就明了

**Comment by visense** [comment]
> 你看看就明了

ok

**Comment by fscarmen** [comment]
> > ifconfig.co
> 
> 如何自己修改ip.sb为ifconfig.co？脚本中不知道哪些地方要改，改了怕出问题，大佬能不能指教一下？

https://github.com/fscarmen/warp/blob/main/menu.sh#L7

https://github.com/fscarmen/warp/blob/main/warp-go.sh#L7
