### ISSUE TITLE
[Feature request]: ip保留问题

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#258]
### Related Problem / 相关问题

使用的是wireproxy，在outbond中将Netflix使用wireproxy获取的ip的流量，但是如果用warp_unlock改变ip，会导致Netflix的流量的IP一直在变，导致Netflix打不开

### Describe the solution you want / 描述你希望的解决方案

能不能保留原来的ip（即使不能解锁），等到下一次解锁使用新ip，这样可以让Netflix丝滑切换

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
暂时我未有解决方案，换 IP 时网络会断是一个硬伤，当然你只把奈飞流量分流过去 ，即是刷IP的时候，只影响到奈飞，其他网仍然走vps原生的网络出口，这样已经把影响降到最低了。至于你提的方案，我是想不出来如何处理了。保留不了IP的，除非弄多个wireproxy，这样本地就会有多个 socks5 代理，但他们都是不同的端口，如 127.0.0.1:40000，127.0.0.1:40001，127.0.0.1:40002 这样，不同的socks5在刷，你的v2ray也不知道如何分流啊。

**Comment by visense** [comment]
> 暂时我未有解决方案，换 IP 时网络会断是一个硬伤，当然你只把奈飞流量分流过去 ，即是刷IP的时候，只影响到奈飞，其他网仍然走vps原生的网络出口，这样已经把影响降到最低了。至于你提的方案，我是想不出来如何处理了。保留不了IP的，除非弄多个wireproxy，这样本地就会有多个 socks5 代理，但他们都是不同的端口，如 127.0.0.1:40000，127.0.0.1:40001，127.0.0.1:40002 这样，不同的socks5在刷，你的v2ray也不知道如何分流啊。

好的，感谢大佬回复！！！

**Comment by fscarmen** [comment]
有个思路，就是弄几个wireproxy，分别刷，找个地方存放好结果，刷成功的，马上更换 v2ray的配置文件，端口改为成功的那个。如果都不成功，就随便用一个，但这个太深度了，你有能力的话可以试试。

**Comment by visense** [comment]
> 有个思路，就是弄几个wireproxy，这样你的wireproxy配置文件弄几个，分别是不同的端口，systemd 也要弄几个，对应不同的wireproxy，几个分别刷，找个地方存放好结果，刷成功的，马上更换 v2ray的配置文件，端口改为成功的那个。如果都不成功，就随便用一个，但这个太深度了，你有能力的话可以试试。

我现在是这样的，在docker中运行wireProxy，分别不通的端口，可以获取到解锁的ip，看到v2ray分流route中有优先级，在route中分别对应不同的端口，但是这样是不行的，因为在v2ray的route中只会匹配最前面的规则成功，后面的规则中对应端口解锁了ip也用不了

**Comment by visense** [comment]
> 有个思路，就是弄几个wireproxy，这样你的wireproxy配置文件弄几个，分别是不同的端口，systemd 也要弄几个，对应不同的wireproxy，几个分别刷，找个地方存放好结果，刷成功的，马上更换 v2ray的配置文件，端口改为成功的那个。如果都不成功，就随便用一个，但这个太深度了，你有能力的话可以试试。

话说wireproxy获取不到ip这个问题怎么解决？使用 systemctl status wireproxy 情况如下

![image](https://user-images.githubusercontent.com/3490833/210903317-54144679-f2a8-4aad-ba8e-fa946e4ef8ea.png)

做了如下尝试：
1、查看/etc/resolv.conf文件dns设置的是8.8.8.8和8.8.4.4，并没有上面图片的 2001:4860:4860::8844
2、于是修改/etc/hosts文件，添加 

`104.16.123.96 www.cloudflare.com`

然后重启 systemctl restart wireproxy
3、再次运行systemctl status wireproxy  显示api.ip.sb 无法解析，再次修改/etc/hosts文件，添加

`104.26.13.31 api.ip.sb`

然后重启 systemctl restart wireproxy
4、仍然报错，
机器是香港的，其他机器都正常，查看了wireproxy 作者的的issue，没找到解决方法，大佬遇到过吗？

**Comment by fscarmen** [comment]
香港的机器不能用 wireproxy ，因为是 wgcf 机制，而wgcf 在香港上使用不了，换warp-go吧。
