### ISSUE TITLE
[Bug]: wireproxy Handshake did not complete

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#260]
### Expectation / 预期情况

获取ip

### Actual Situation / 实际情况

![image](https://user-images.githubusercontent.com/3490833/210912463-67c9d899-9628-4673-b878-03386c097f7e.png)
获取不到ip

使用 systemctl status wireproxy 情况如下

![image](https://user-images.githubusercontent.com/3490833/210903317-54144679-f2a8-4aad-ba8e-fa946e4ef8ea.png)

做了如下尝试：
1、查看/etc/resolv.conf文件dns设置的是8.8.8.8和8.8.4.4，并没有上面图片的 2001:4860:4860::8844
2、于是修改/etc/hosts文件，添加 

`104.16.123.96 www.cloudflare.com`

然后重启 systemctl restart wireproxy
3、再次运行systemctl status wireproxy  显示api.ip.sb 无法解析，再次修改/etc/hosts文件，添加

`104.26.13.31 api.ip.sb`

然后重启 systemctl restart wireproxy

4、尝试https://github.com/fscarmen/warp/issues/123

5、仍然报错，

机器是香港的，其他机器都正常，查看了wireproxy 作者的的issue，没找到解决方法，大佬遇到过吗？

### Reproduction Method / 复现方法

如上

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
wireproxy 也是用 wgcf 的底层的，即是在 HK 上没有 warp 服务，只能改用 clinet.

**Comment by visense** [comment]
> wireproxy 也是用 wgcf 的底层的，即是在 HK 上没有 warp 服务，只能改用 clinet.

感谢大佬回复，wireproxy长时间使用会出现 https://github.com/fscarmen/warp/issues/123 的问题，在此记录一下
