### ISSUE TITLE
[help wanted 求助]: client proxy模式ipv6

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#261]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

因为ipv4模式只能获取3个ip，于是而我这台机器wireproxy模式获取不到ip（ipv4和ipv6都不行），错误情况在 https://github.com/fscarmen/warp/issues/260 于是想通过client proxy模式运行ipv6

首先运行如下代码查看ipv4

`curl -sx socks5h://localhost:40000 -A Mozilla https://api.ip.sb/geoip 2>/dev/null`

结果如下：

![image](https://user-images.githubusercontent.com/3490833/211108294-e4613511-68bb-48a1-8815-c4d128714ce4.png)

运行如下代码查看ipv6

`curl -6sx socks5://127.0.0.1:40000 -A Mozilla https://api.ip.sb/geoip 2>/dev/null`

结果如下：

![image](https://user-images.githubusercontent.com/3490833/211108412-4fb4f580-8629-4843-a768-28635d51c63b.png)

说明warp-cli proxy模式在获取ipv4的同时获取到了ipv6地址，接下来安装warp_unlock.sh解锁，因为warp_unlock.sh里面默认是ipv4的模式，修改下面的代码

![image](https://user-images.githubusercontent.com/3490833/211109005-c23daaee-7aad-4186-8b80-1812ad402e4c.png)

手动运行bash /usr/bin/warp_unlock.sh重启client proxy，通过查看

`curl -6sx socks5://127.0.0.1:40000 -A Mozilla https://api.ip.sb/geoip 2>/dev/null`

发现能获取到ipv6，ipv6地址也能变，但是不能正常显示

![image](https://user-images.githubusercontent.com/3490833/211109254-98f32b8f-5563-43b8-9599-0bf58b08cb75.png)

现在遇到2个问题，1个是上面不能显示正常ipv6地址的问题（这个不显示也不影响），第二个问题是v2ray中如何分流，因为在v2ray outbound中，是用了如下代码

```
{
            "tag": "media-unlock",
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1",
                        "port": 40000,
                        "users": []
                    }
                ]
            }
    }

```
route用如下代码

```
{
                "type":"field",
                "outboundTag":"media-unlock",
                "domain":[
                    "geosite:netflix",
                    "domain:ip.gs"
                ]
        }
```

浏览器打开ip.gs发现ipv4是client proxy的ipv4，ipv6是client proxy的ipv6，设置ipv6优先，以及用https://91ai.net/thread-986027-1-1.htm

![image](https://user-images.githubusercontent.com/3490833/211109982-4af0814b-6aa1-4e77-8d19-a4f727419731.png)

遇到的问题，v2ray分流如何让ipv6优先

### Log / 日志信息

如上

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
有以下两点需要处理的，还是那个ip.sb的问题，同一ip不停的获取，会显示不出来的，使用上有限制。
找回之前的issue，把ipv6的路由加上去，v2ray分流过去，但具体我没有奈飞，也没有测试过，理论上是这样。

**Comment by visense** [comment]
> 有以下两点需要处理的，还是那个ip.sb的问题，同一ip不停的获取，会显示不出来的，使用上有限制。 找回之前的issue，把ipv6的路由加上去，v2ray分流过去，但具体我没有奈飞，也没有测试过，理论上是这样。

感谢大佬回复！
