### ISSUE TITLE
[help wanted 求助]: WARP-GO香港区刷不出ip-【结论：根据资深玩家 Meina9758反馈，检查此处到162.169.195.1到162.159.195.10 ip段traceroute，查看具体路径以判断落地在哪。部分香港IDC（特指某ntt线路）把这个地址路由到黑洞或者是美国  如果是路由到黑洞或者美国的，如何处理？  目前暂时无法处理，路由peer到美国的一般可以正常使用wgcf，黑洞无解，但是可以尝试162.159.19x.1-10，x指2-5之内的数字。目前已知信息是这几个段都可以播上warp，无特殊区别】

### ISSUE THREAD

**Issue by moelinmtf** [fscarmen/warp#262]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

warp-go香港区，安装的时候就获取不到IP，每次都会自动退出。

### Log / 日志信息

脚本版本: 1.1.0         功能新增: 支持 OpenWrt 系统
 系统信息:
         当前操作系统: Debian GNU/Linux 11 (bullseye)
         内核: 5.10.0-20-amd64
         处理器架构: amd64v4
         虚拟化: kvm 
         IPv4: 103.171.176.71  香港  Eons Data Communications Limited 
         IPv6:      
         WARP 网络接口未开启 

======================================================================================================================

 1.  WARP 全局 双栈 转为 WARP 全局 IPv4 (warp-go 4)
 2.  WARP 全局 双栈 转为 WARP 全局 IPv6 (warp-go 6)
 3.  转为 WARP 非全局 网络接口 (warp-go g)
 4.  打开 warp-go (warp-go o)
 5.  更换为 Free，WARP+ 或 Teams 账户 (warp-go a)
 6.  更换支持 Netflix 的 IP (warp-go i)
 7.  输出 wireguard 和 sing-box 配置文件 (warp-go e)
 8.  卸载 WARP 网络接口和 warp-go (warp-go u)
 9.  同步最新版本 (warp-go v) 
 0.  退出脚本
 
 请选择: 1
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
搞不清楚啊，我这里的 GCP 香港是可以的，刚试了。

**Comment by sfwtw** [comment]
+1

**Comment by fscarmen** [comment]
有点不好处理了，或者试试client的 warp模式， 在menu.sh 脚本有，看看那个是否可以了，再不行真没有办法了。

**Comment by Meina9758** [comment]
> 

首先查看peer到as13335是否在HKG，ping 162.159.195.10是否能通，traceroute看具体路由并附上跟踪表，谢谢

**Comment by fscarmen** [comment]
> > 
> 
> 首先查看peer到as13335是否在HKG，ping 162.159.195.10是否能通，traceroute看具体路由并附上跟踪表，谢谢

具体如何操作？方便截些图来看看？

**Comment by Meina9758** [comment]
主要检查此处到162.169.195.1到162.159.195.10 ip段traceroute，查看具体路径以判断落地在哪。部分香港IDC（特指某ntt线路）把这个地址路由到黑洞或者是美国
![屏幕截图 2023-01-17 170039](https://user-images.githubusercontent.com/79711420/212841805-edd5e95c-6a78-45b8-8e2e-5b105cc5e019.png)

**Comment by fscarmen** [comment]
> 主要检查此处到162.169.195.1到162.159.195.10 ip段traceroute，查看具体路径以判断落地在哪。部分香港IDC（特指某ntt线路）把这个地址路由到黑洞或者是美国 ![屏幕截图 2023-01-17 170039](https://user-images.githubusercontent.com/79711420/212841805-edd5e95c-6a78-45b8-8e2e-5b105cc5e019.png)

如果是路由到黑洞或者美国的，如何处理？

**Comment by Meina9758** [comment]
> > 主要检查此处到162.169.195.1到162.159.195.10 ip段traceroute，查看具体路径以判断落地在哪。部分香港IDC（特指某ntt线路）把这个地址路由到黑洞或者是美国 
> 
> 
> 
> 如果是路由到黑洞或者美国的，如何处理？

目前暂时无法处理，路由peer到美国的一般可以正常使用wgcf，黑洞无解，但是可以尝试162.159.19x.1-10，x指2-5之内的数字。目前已知信息是这几个段都可以播上warp，无特殊区别

**Comment by fscarmen** [comment]
> > > 主要检查此处到162.169.195.1到162.159.195.10 ip段traceroute，查看具体路径以判断落地在哪。部分香港IDC（特指某ntt线路）把这个地址路由到黑洞或者是美国
> > 
> > 
> > 如果是路由到黑洞或者美国的，如何处理？
> 
> 目前暂时无法处理，路由peer到美国的一般可以正常使用wgcf，黑洞无解，但是可以尝试162.159.19x.1-10，x指2-5之内的数字。目前已知信息是这几个段都可以播上warp，无特殊区别

根据资深玩家 [Meina9758](https://github.com/Meina9758) 的建议，可以在 VPS 上使用一下我的另一个测线路脚本看看情况
```
bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/tools/main/return.sh) 162.159.195.10
```

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/62703343/222324520-4ba9a6c5-2d2a-4ed3-9786-f423d5a6b893.png">

另外想请问 as133335 是什么，chatGPT如此回复，还希望你展开一下这个如何使用的，我也是一直不会
<img width="626" alt="image" src="https://user-images.githubusercontent.com/62703343/222324889-78c16228-ddda-4bcb-b670-7d69bafd5a6e.png">

**Comment by Meina9758** [comment]
> > > > 主要检查此处到162.169.195.1到162.159.195.10 ip段traceroute，查看具体路径以判断落地在哪。部分香港IDC（特指某ntt线路）把这个地址路由到黑洞或者是美国
> 
> > > 
> 
> > > 
> 
> > > 如果是路由到黑洞或者美国的，如何处理？
> 
> > 
> 
> > 目前暂时无法处理，路由peer到美国的一般可以正常使用wgcf，黑洞无解，但是可以尝试162.159.19x.1-10，x指2-5之内的数字。目前已知信息是这几个段都可以播上warp，无特殊区别
> 
> 
> 
> 根据资深玩家 [Meina9758](https://github.com/Meina9758) 的建议，可以在 VPS 上使用一下我的另一个测线路脚本看看情况
> 
> ```
> 
> bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/tools/main/return.sh) 162.159.195.10
> 
> ```
> 
> 
> 
> <img width="1022" alt="image" src="https://user-images.githubusercontent.com/62703343/222324520-4ba9a6c5-2d2a-4ed3-9786-f423d5a6b893.png">
> 
> 
> 
> 另外想请问 as133335 是什么，chatGPT如此回复，还希望你展开一下这个如何使用的，我也是一直不会
> 
> <img width="626" alt="image" src="https://user-images.githubusercontent.com/62703343/222324889-78c16228-ddda-4bcb-b670-7d69bafd5a6e.png">
> 
> 
AS13335为cloudflare的bgp as编号，可以简单的理解为宣告我这里有这些地址的方式，最简单的查询peer方式就是traceroute查看ASN，并且确认入口的地理位置，可以大致判断peer在哪建立或者路由走向。但因运营商和transit的pbr（策略路由）可能路径会有一些调整。

关于warp的地区是根据传入链接的peer地址来的，cloudflare目前所持ip全部都是广播，判断aspath以返回一个colo以确定warp区域，所以之前刷地址的方式并不可取，可能只是针对地址库未更新时的地址sign不正确，而导致误判或策略问题。
