### ISSUE TITLE
[Bug]:Client Proxy模式下的IP与WARP脚本显示的IP不同-【结论：根据资深玩家 Meina9758 的反馈，warp出口负载均衡，不用看了。甚至部分还能刷出来以前的8.x.x.x的ip，所以这个问题即是无解了】

### ISSUE THREAD

**Issue by Rockeeeer** [fscarmen/warp#263]
### Expectation / 预期情况

安装了Client Proxy的话，warp i命令应该刷新Client Proxy Socks5: 127.0.0.1:40000下的IP

### Actual Situation / 实际情况

作者你好，Client Proxy模式下的IP与WARP脚本显示的IP不同，WARP I刷ip的时候，刷的是WARP显示的IP，而不是刷Client Proxy Socks5: 127.0.0.1:40000模式下的IP，我实际使用的是Client Proxy Socks5，X-UI配置模板已正确修改，无法正确刷Client Proxy模式下的IP。
![1](https://user-images.githubusercontent.com/89590960/212524902-3d706693-788e-456a-a5b2-bab2b078cb6c.PNG)
![2](https://user-images.githubusercontent.com/89590960/212524913-f5205e59-3571-41ce-b003-c26ac3ec7a1e.PNG)

### Reproduction Method / 复现方法

0

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
最好不要多种模式都安装，不过脚本应该会让你选择刷哪个的，你试试
```
bash -x warp i
```
看看 debug 内容

**Comment by fscarmen** [comment]
两个 ip 不同的呢？难度 warp 连接不同的网络，用不同的出口IP?

**Comment by Rockeeeer** [comment]
感谢作者的回复
1：我只安装了CloudFlare Client 并设置为 Proxy 这一个模式，没有安装其他模式
2：执行warp i更换IP的时候，没有让我选择
3：我先是debian11，然后更换到ubuntu22.04 LTS，问题依旧出现

**Comment by fscarmen** [comment]
好像这个 ifconfig.me 的网站，获取出来的 ip 与其他的不一样呢，你试试其他的
<img width="750" alt="image" src="https://user-images.githubusercontent.com/62703343/212530073-cf35a237-7c35-4f9d-97e8-4561d0277d12.png">
```
curl ifconfig.me --proxy socks5://127.0.0.1:40000; echo ""

curl ip.sb --proxy socks5://127.0.0.1:40000; echo ""

curl ifconfig.co --proxy socks5://127.0.0.1:40000; echo ""

curl ipget.net --proxy socks5://127.0.0.1:40000; echo ""
```

```

**Comment by fscarmen** [comment]
> 感谢作者的回复 1：我只安装了CloudFlare Client 并设置为 Proxy 这一个模式，没有安装其他模式 2：执行warp i更换IP的时候，没有让我选择 3：我先是debian11，然后更换到ubuntu22.04 LTS，问题依旧出现

我刚才看错你的问题了，上面有图，同一时间，ifconfig.me 出来的结果与其他的网不一样的？你再多找几个试试

**Comment by Rockeeeer** [comment]
ifconfig.me出来的结果和其他的确实不同，但是netflix走的确是ifconfig.me出来的IP，也就是104.28.222.46
![1](https://user-images.githubusercontent.com/89590960/212530342-b194e873-0022-4afd-8850-9e814b6e598a.PNG)
![2](https://user-images.githubusercontent.com/89590960/212530348-c79b11fa-71bb-4bcc-ae4a-6d6f81edb183.PNG)

**Comment by fscarmen** [comment]
这就不太好办了，我看了一下 ifconfig.me 不能直接替换到脚本的 ip api 里，因为没有归属地 ,isp 商等信息的。

**Comment by Rockeeeer** [comment]
crontab，5分钟一检测的那个模式下

cat /root/result.log

![无标题](https://user-images.githubusercontent.com/89590960/212647582-e7949fca-a0e0-4314-bb59-42e9eb5129a1.png)

**Comment by fscarmen** [comment]
这个是由于 ip.sb 使用了 Cloudflare 的访问限制导致的。在以下这里，把 IP api 换成 ifconfig.co 那行

https://github.com/fscarmen/warp_unlock/blob/main/unlock.sh#L11

**Comment by Rockeeeer** [comment]
不好意思作者，我是新手，不是很明白
你是让我修改https://github.com/fscarmen/warp_unlock/blob/main/unlock.sh#L11里的IP API参数，然后点Propose changes？
还是让我在自己的VPS里修改unlock.sh里的IP API参数？
如果是让我修改自己VPS的参数，麻烦告诉一下文件的具体位置，一直没找到。。。谢谢

**Comment by Meina9758** [comment]
> 两个 ip 不同的呢？难度 warp 连接不同的网络，用不同的出口IP?

warp出口负载均衡，不用看了。甚至部分还能刷出来以前的8.x.x.x的ip
