### ISSUE TITLE
[Bug]: Openwrt无适合方案用于修改warp.conf-【结论：openWRT 由于我在骷髅头固件上试了一下，没有经过太多的测试。请资深的玩家手动运行 warp-go 原程序玩玩了。】

### ISSUE THREAD

**Issue by Meina9758** [fscarmen/warp#264]
### Expectation / 预期情况

最起码起个v6吧:(

### Actual Situation / 实际情况

没有找到适合的方案用于修改 warp-go 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp/issues]

### Reproduction Method / 复现方法

内核名不为openwrt的openwrt系统直接执行脚本就会终止，但直接使用warp-go源也播不上。希望能反馈一下

### Log / 日志信息

![image](https://user-images.githubusercontent.com/79711420/212842967-e38147d4-7e06-464c-abd3-9bccd26d20b2.png)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
> ### Reproduction Method / 复现方法
> 内核名不为openwrt的openwrt系统直接执行脚本就会终止，但直接使用warp-go源也播不上。希望能反馈一下

是这样的，只有一个r2s能测一下，没有其他设备测，所以也不知道其他设备的内核名。
同时那个测不到ip的，是因为ip.sb限制访问了，在脚本的开头把 ip api 从 ip.sb 换成 ifconfig.co

**Comment by Meina9758** [comment]
> > ### Reproduction Method / 复现方法
> > 内核名不为openwrt的openwrt系统直接执行脚本就会终止，但直接使用warp-go源也播不上。希望能反馈一下
> 
> 是这样的，只有一个r2s能测一下，没有其他设备测，所以也不知道其他设备的内核名。 同时那个测不到ip的，是因为ip.sb限制访问了，在脚本的开头把 ip api 从 ip.sb 换成 ifconfig.co

我可以提供pve进行测试，amd64，镜像源自备。需要联系我叭

**Comment by fscarmen** [comment]
你好，抱歉这么久才回复，最近一直在忙些在白嫖的容器类项目安装科学的项目，故这里更新和回复慢了很多。

**Comment by Meina9758** [comment]
> 你好，抱歉这么久才回复，最近一直在忙些在白嫖的容器类项目安装科学的项目，故这里更新和回复慢了很多。考虑到用户应该极少，故不增加该系统的支持了，因为只有大量用户，才能完善好的，用户少，就像 openwrt 一样，会有不少问题的。

<img width="513" alt="image" src="https://user-images.githubusercontent.com/79711420/214414840-7f7ab1f5-d4a6-4891-9991-3248fe671ec8.png">
目前已经放弃Openwrt作为主接入使用，但是CentOS8也出问题了。还有一个小问题是在默认状况下warp-go似乎不会掉线自动重播

**Comment by fscarmen** [comment]
他这个不一定是断网的，很大可能是 ip.sb 的访问限制，导致读不出 ip 数据而已，你试试 `curl -s4m5 ifconfig.co`  和 `curl -s6m5 ifconfig.co`
