### ISSUE TITLE
[help wanted 求助]: 开启warp双栈/IPv6模式后，原生IPv6无法接收入站-【结论：情况的确如此，同时我也暂时没有解决办法，期待有大佬告诉如何处理，让能用 ipv6 接入】

### ISSUE THREAD

**Issue by XhL6996** [fscarmen/warp#265]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

warp-go处于关闭状态时，本机的原生IPv6地址可以被ping通；开启warp-go的IPv6或者双栈全局模式时，通过ping.pe测试，所有测试点均ping不通；而开启IPv4全局模式时，原生IPv6可以正常入站。原生IPv4无论何种模式都可以正常入站。

### Log / 日志信息

none

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
>warp-go处于关闭状态时，本机的原生IPv6地址可以被ping通；开启warp-go的IPv6或者双栈全局模式时，通过ping.pe测试，所有测试点均ping不通

你的机器是 ipv4 还是 6 还是双栈的，我试过在 hax的 ipv6 机器上，开不开warp-go，那个 ipv6 地址都是通的啊

>而开启IPv4全局模式时，原生IPv6可以正常入站。原生IPv4无论何种模式都可以正常入站。

不太明白这个意思

**Comment by XhL6996** [comment]
> 你的机器是 ipv4 还是 6 还是双栈的，我试过在 hax的 ipv6 机器上，开不开warp-go，那个 ipv6 地址都是通的啊

机器是双栈的。

未开启warp-go时，ping.pe检测机器原生IPv6的联通性：
![2023-01-23_17-37](https://user-images.githubusercontent.com/63577165/214008059-fd43aa0e-454f-443f-839b-f4719057e6ba.png)
然后开启warp-go的IPv6或双栈的全局模式（3/4/5/6任意一项）
![2023-01-23_17-30](https://user-images.githubusercontent.com/63577165/214007050-2f5cefaf-3ffc-462e-b189-e659b0ec2c53.png)
然后这个IPv6地址就失联了：
![2023-01-23_17-38](https://user-images.githubusercontent.com/63577165/214008121-220699d7-b089-4d25-b27b-e8e6160baeda.png)

> 
> > 而开启IPv4全局模式时，原生IPv6可以正常入站。原生IPv4无论何种模式都可以正常入站。
> 
> 不太明白这个意思

这就是提供一个对比，开启IPv6全局或双栈全局时，机器原来的IPv6地址会失联。但开启IPv4全局或者双栈全局时，机器原来的IPv4可以接收入站，不会失联。

**Comment by fscarmen** [comment]
我用双栈机器试了，结果和你一样，可能 使用 WARP IPv6 的路由表要特殊处理一下才行，但暂时没有思路。

**Comment by XhL6996** [comment]
只有双栈有这个问题，纯v6反而没有。

**Comment by fscarmen** [comment]
我要找个时间试试，把 ip -6 route add 和 ip -6 route del 的两条去掉看看，不过有可能失联，一定要能vnc进机器的才行，比如甲骨文

**Comment by FLIER001** [comment]
一样的问题，求解

**Comment by gnz1123** [comment]
一些双栈机用warp也有这个问题，只是一部分，双栈转warp双栈，原生v6不能访问。

**Comment by zcvxcv** [comment]
> 一些双栈机用warp也有这个问题，只是一部分，双栈转warp双栈，原生v6不能访问。

没错，我的甲骨文美国也是这样。开启之后，甲骨文原本的v6，连接不上

**Comment by fscarmen** [comment]
我也暂时没有解决方案，希望后面有资深玩家提供方案，暂时关闭了。

**Comment by Delta-in-hub** [comment]
Same issue

**Comment by weiyideai520** [comment]
Same issue

**Comment by heygo1345678** [comment]
> 我也暂时没有解决方案，希望后面有资深玩家提供方案，暂时关闭了。

大佬，我在openwrt上面玩 clash tun 透明代理，和这个失联应该是类似，需要策略路由解决：
ip -6 route add default via fe80::1 dev eth1 table 300
ip -6 rule add from all fwmark 0x1 lookup 300
ip6tables -t mangle -I PREROUTING -p tcp --dport 443 -j MARK --set-mark 1
ip6tables -t mangle -I OUTPUT -p tcp --sport 443 -j MARK --set-mark 1

ip6tables -t mangle -I PREROUTING -p tcp --dport 22 -j MARK --set-mark 1
ip6tables -t mangle -I OUTPUT -p tcp --sport 22 -j MARK --set-mark 1

想请教您，可不可以不去这样一个一个的设置端口号，因为防火墙入站就有开关了，您脚本应该是默认不会失联针对所有入站，我又看不懂脚本，这个问题和warp确实是无关的，只是想顺便问问

**Comment by XhL6996** [comment]
> 我也暂时没有解决方案，希望后面有资深玩家提供方案，暂时关闭了。

抓了个包，看起来是回复的流量错误地通过WARP网卡送出。

**Comment by XhL6996** [comment]
> 我也暂时没有解决方案，希望后面有资深玩家提供方案，暂时关闭了。

找到问题所在了，这个路由规则是没毛病的，也是必不可少的。这个PostUp在双栈主机里面写了两条规则，但不知道什么原因，只能成功加进去一条。实际上ip -6 rule规则没加进去，导致IPv6的回复流量错误地通过WARP网卡发出。
解决方案也简单，把两条规则拆开写两个PostUp就可以了。
![Snipaste_2023-04-12_13-16-38](https://user-images.githubusercontent.com/63577165/231357250-20bbdd88-f964-40d8-ad09-03599ad8155e.png)

**Comment by fscarmen** [comment]
> > 我也暂时没有解决方案，希望后面有资深玩家提供方案，暂时关闭了。
> 
> 找到问题所在了，这个路由规则是没毛病的，也是必不可少的。这个PostUp在双栈主机里面写了两条规则，但不知道什么原因，只能成功加进去一条。实际上ip -6 rule规则没加进去，导致IPv6的回复流量错误地通过WARP网卡发出。 解决方案也简单，把两条规则拆开写两个PostUp就可以了。 ![Snipaste_2023-04-12_13-16-38](https://user-images.githubusercontent.com/63577165/231357250-20bbdd88-f964-40d8-ad09-03599ad8155e.png)

我现在是这样写的，也是分开的，但顺序与你的有不同？是不是一定要按你的顺序？

<img width="905" alt="image" src="https://user-images.githubusercontent.com/62703343/231367337-426ca954-bf10-4d15-8102-6d934691ca47.png">

**Comment by XhL6996** [comment]
> 我现在是这样写的，也是分开的，但顺序与你的有不同？是不是一定要按你的顺序？
> 
> <img alt="image" width="905" src="https://user-images.githubusercontent.com/62703343/231367337-426ca954-bf10-4d15-8102-6d934691ca47.png">

您这个顺序work吗？如果正常的话，那无所谓。我也是无意中发现的，不太懂其中原理，按理说写成一条加分号就可以了。可能是因为warp-go程序和官方wireguard有不同？（而且看本项目目前的存档还是写成一条加分号的形式，并不是您截图的写法👀。
