### ISSUE TITLE
[help wanted 求助]: 在设置机器人消息后，Tg没接到任何信息-【结论：请参考说明指引】

### ISSUE THREAD

**Issue by wangyufeng2006** [fscarmen/warp#267]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

在设置机器人消息后，Tg没接到任何信息。api和ID都是正常的

### Log / 日志信息

没找到log。。。

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
不是api哦，只是token哦，你有没有填错？
