### ISSUE TITLE
hax.co.id的centos8获取不了warp ip-【结论：HAX OpenVZ CentOS8 开启TUN有问题，建议改为Debian或者Ubuntu】

### ISSUE THREAD

**Issue by 2539159006** [fscarmen/warp#27]
**hax.co.id的centos8获取不了warp ip，重装也试过了，咋搞？**
![图片](https://user-images.githubusercontent.com/50311735/142402907-dfcdefb8-51f1-460c-9a8a-7eab89d302d1.png)

**Comment by fscarmen** [comment]
是KVM还是OpenVZ的？我有台KVM的，但一直说ssh密码错登陆不进去试。

**Comment by 2539159006** [comment]
OpenVZ的

**Comment by fscarmen** [comment]
请加我 TG: https://t.me/fscarmen2

**Comment by fscarmen** [comment]
原本检测TUN是否开启的方法 cat /dev/net/tun
在已开启的情况下显示 ```cat: /dev/net/tun: File descriptor in bad state```
没有开启则显示 ```cat: /dev/net/tun: Operation not permitted``` 或者  ```cat: /dev/net/tun: No such file or directory```

但CentOS 8 不知道为什么，明明没有开启却提示已经开启TUN的信息，导致脚本检测不出来而进行下去。
暂时没有找到另外的检测方法来补充或者替换。
建议用 Ubuntu 20.04 或者 Debian 10，试过没有出现上述的问题，脚本正常运行。

**Comment by fscarmen** [comment]
> OpenVZ的

请问现在处理了吗？

**Comment by misakano7545** [comment]
可以关闭这个issues了，已经问过Hax站长屏蔽CentOS 8了

**Comment by fscarmen** [comment]
> 已经问过Hax站长屏蔽CentOS 8了

Hax站长处理不了CentOS 8 的问题吗？毕竟仍有不少用户需要的。

**Comment by misakano7545** [comment]
> > 已经问过Hax站长屏蔽CentOS 8了
> 
> Hax站长处理不了CentOS 8 的问题吗？毕竟仍有不少用户需要的。

是CentOS8停止支持了
