### ISSUE TITLE
[Bug]:  没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。-【结论：暂时判断不出什么问题】

### ISSUE THREAD

**Issue by ailinzhou** [fscarmen/warp#271]
### Expectation / 预期情况

预期能开启WARP

### Actual Situation / 实际情况

运行开启warp命令后提升未安装  WireGuard tools。
```
> warp o
 没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。
```

按照https://www.wireguard.com/install/中文档安装 CentOS 7 方法3安装WireGuard tools 后依然不行提示和上面一样的错误。

### Reproduction Method / 复现方法

  ```
       Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
       Kernel: Linux 4.10.4-1.el7.elrepo.x86_64
       Architecture: x86-64
```

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
这个不太好判断，不过centos7系统太旧了，会存在比较多问题，可以的话最好用debian或者ubuntu
