### ISSUE TITLE
[help wanted 求助]: 香港机器使用warp-go失联-【结论：用户的 vps 比较特殊，IP 会变，导致配置文件不匹配而失联，需要另外找办法处理】

### ISSUE THREAD

**Issue by GreenTeodoro839** [fscarmen/warp#274]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

原生双线，用了warp-go全局双栈模式，机器失联了，ipv4 ipv6都不通

机器没有内网nat，直接是公网ip，之前配置好了正常，但是ip墙了换了ip，warp-go随系统启动之后就失联了。是因为warp-go不能换ip吗？有没有办法解决

### Log / 日志信息

没看到日志

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
因为配置文件里设置了你原来的公网IP，重启后运行也是那个IP，导致路由失败，看看有没有VNC，进去会的话修改配置文件，重启服务。不会的话卸载掉并重装。如果没有VNC，只能重装系统了。

**Comment by GreenTeodoro839** [comment]
> 因为配置文件里设置了你原来的公网IP，重启后运行也是那个IP，导致路由失败，看看有没有VNC，进去会的话修改配置文件，重启服务。不会的话卸载掉并重装。如果没有VNC，只能重装系统了。

ipv6不能用有办法吗？没换过ipv6，我看issue也有提这个的

**Comment by GreenTeodoro839** [comment]
还有，warp现在限速了吗？我用warp+，G口只能跑300M左右

**Comment by fscarmen** [comment]
> 还有，warp现在限速了吗？我用warp+，G口只能跑300M左右

你本地有ipv6的话，试试用ipv6 ssh能不能进去，如果不行就真有办法了。

> warp现在限速了吗？我用warp+，G口只能跑300M左右

是的，Warp我现在只用于chatGPT，其他都是减速的。

**Comment by GreenTeodoro839** [comment]
> > 还有，warp现在限速了吗？我用warp+，G口只能跑300M左右
> 
> 你本地有ipv6的话，试试用ipv6 ssh能不能进去，如果不行就真有办法了。
> 
> > warp现在限速了吗？我用warp+，G口只能跑300M左右
> 
> 是的，Warp我现在只用于chatGPT，其他都是减速的。

v6也是炸的，我进vnc去试试吧

**Comment by fscarmen** [comment]
处理了吗？是什么问题？

**Comment by GreenTeodoro839** [comment]
> 处理了吗？是什么问题？

进vnc用warp-go u卸载，然后重新安装就行了
配置文件不会改，建议做个脚本，可选安装，开机检查机器ip和配置文件的ip是否一致，不一致就关闭wireguard或者自动更正

**Comment by fscarmen** [comment]
> > 处理了吗？是什么问题？
> 
> 进vnc用warp-go u卸载，然后重新安装就行了 配置文件不会改，建议做个脚本，可选安装，开机检查机器ip和配置文件的ip是否一致，不一致就关闭wireguard或者自动更正

这个失联应该是偶发事件，再看看其他用户的反馈情况

2023.3.2 warp-go 一键脚本 V1.1.1
1. warp-go v1.0.8 is supported. Allowing custom MTU values in the configuration file /opt/warp-go/warp.conf; 

2. Singbox configuration exports reseved using 3-numeric-array instead of a string;

1. 支持 warp-go v1.0.8 , 允许在配置文件 /opt/warp-go/warp.conf 自定义 MTU 值;

2. Singbox配置导出 reseved 使用三个数字的数组代替字符串

```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
```

**Comment by fscarmen** [comment]
服务器的网卡为什么就变 IP 啊，不是固定的吗？

**Comment by fscarmen** [comment]
我在想能不能自己弄个内网网卡，指向你公网的网卡的网络接口，这样就不怕变了。

**Comment by GreenTeodoro839** [comment]
> 我在想能不能自己弄个内网网卡，指向你公网的网卡的网络接口，这样就不怕变了。

应该能用tun创建虚拟网卡，但是还要搞一个本地dhcp服务，让真正的网卡做wan

**Comment by fscarmen** [comment]
是的，就是这样，我觉得是可以的，原理是这样，不过我也不会创建这个网卡，所以你要找找教程。

**Comment by GreenTeodoro839** [comment]
> 是的，就是这样，我觉得是可以的，原理是这样，不过我也不会创建这个网卡，所以你要找找教程。

所以最简单的办法就是开机检测网卡ip和wireguard配置的ip一样不，不一样就停掉wireguard

**Comment by malikshi** [comment]
> 4\. Singbox configuration export reseved uses an array of three numbers instead of a string

How we get right reserved number?

**Comment by fscarmen** [comment]
> > 是的，就是这样，我觉得是可以的，原理是这样，不过我也不会创建这个网卡，所以你要找找教程。
> 
> 所以最简单的办法就是开机检测网卡ip和wireguard配置的ip一样不，不一样就停掉wireguard

有个简单的方法不用脚本了，并了重启自动运行。你安装好后运行，这样就能运行，如果因为换网络IP而失联，你重启一下就行
```
systemctl disable --now warp-go; systemctl start warp-go
```
