### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by firefoxOnFire** [fscarmen/warp#277]
### Related Problem / 相关问题

Using warp+ licence adding new device everytime

### Describe the solution you want / 描述你希望的解决方案

Put an option to enter my locally generated wireguard config too. This will help retain one config on my script.

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
Do you mean you want to use your own config instead of the scripts generate ?
Step:
1. `warp o`  to stop.
2. Edit the file: `/etc/wireguard/wgcf.conf` ,using your config.
3. `warp o` to start again.
