### ISSUE TITLE
[help wanted 求助]: 美国机器支持ChatGPT失败

### ISSUE THREAD

**Issue by JSilent** [fscarmen/warp#278]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

运行脚本后选12，然后出现
```
 Maximum 5 attempts to get WARP IP...
 Try 1
 Try 2
 Try 3
 Try 4
 Try 5
 There have been more than 5 failures. The script is aborted. Feedback: [https://github.com/fscarmen/warp/issues]
```
退出再选4也不行

### Log / 日志信息

```
 Maximum 5 attempts to get WARP IP...
 Try 1
 Try 2
 Try 3
 Try 4
 Try 5
 There have been more than 5 failures. The script is aborted. Feedback: [https://github.com/fscarmen/warp/issues]
```

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by JSilent** [comment]
Version:2.47    New features:Iptables + dnsmasq + ipset solution supports chatGPT. Install via the 12 option in the menu or [bash menu.sh e]
 System infomation:
         Operating System:Ubuntu 18.04.6 LTS
         Kernel:4.15.0-204-generic
         Architecture:amd64
         Virtualization:kvm
         IPv4: xxx.xxx.xxx.xxx  United States  IT7 Networks Inc
         IPv6:
         WARP Interface is off
         Client is not installed.
         WireProxy is not installed.

**Comment by moranno** [comment]
我刚刚也无法获取到IP，奇怪了

**Comment by fscarmen2** [comment]
用warp-go方案，非全局就行了

**Comment by fscarmen** [comment]
美国的LA的一些地区，香港均没有wgcf服务，可以换成 Client 的 warp 模式或者 使用warp-go脚本，不过xray分流那块需要处理一下。

**Comment by JSilent** [comment]
选14结果也是不行。
` Step 2/2: Setting Client Mode
 Maximum 5 attempts to get WARP IP...
 Try 1
 Try 2
 Try 3
 Try 4
 Try 5
 There have been more than 5 failures. The script is aborted. Feedback: [https://github.com/fscarmen/warp/issues]
`

**Comment by fscarmen** [comment]
那可能是其他原因了，机器是美国哪里的？ipv4还是ipv6机器？

**Comment by fscarmen** [comment]
> 选14结果也是不行。
> 
> ```
> Step 2/2: Setting Client Mode
>  Maximum 5 attempts to get WARP IP...
>  Try 1
>  Try 2
>  Try 3
>  Try 4
>  Try 5
>  There have been more than 5 failures. The script is aborted. Feedback: [https://github.com/fscarmen/warp/issues]
> ```

这个不太好判断了，可以的话，你先换个系统看看，再不行DD，再不行可能就是限制了。

**Comment by JSilent** [comment]
换成Centos 9，选5可以，谢谢~

**Comment by fscarmen** [comment]
恭喜恭喜，感谢你的支持。
