### ISSUE TITLE
[Bug]: amazon linux 2无法识别

### ISSUE THREAD

**Issue by kokutoukiritsugu** [fscarmen/warp#279]
### Expectation / 预期情况

应该识别为centos

### Actual Situation / 实际情况

提示系统版本过低.低于centos7

### Reproduction Method / 复现方法

修改里面的7为2就可以正常运行...
![Snipaste_2023-02-16_10-28-18](https://user-images.githubusercontent.com/5471433/219254904-94fc98de-400d-4e8a-b0b3-6d774853c84c.png)

### More information / 额外信息

➜  ~ grep -i pretty_name /etc/os-release
PRETTY_NAME="Amazon Linux 2"
➜  ~ hostnamectl  | grep -i system      
  Operating System: Amazon Linux 2

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by kokutoukiritsugu** [comment]
另外 amazon linux 2 安装epel是要用专有命令...
epel装完后才可以安装  sudo yum install -y wireguard-tools
`
➜  ~ sudo amazon-linux-extras install epel   
Installing epel-release
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Cleaning repos: amzn2-core amzn2extra-docker amzn2extra-epel amzn2extra-nginx1 epel
29 metadata files removed
10 sqlite files removed
0 metadata files removed
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                                              | 3.7 kB  00:00:00     
amzn2extra-docker                                                                                                                       | 3.0 kB  00:00:00     
amzn2extra-epel                                                                                                                         | 3.0 kB  00:00:00     
amzn2extra-nginx1                                                                                                                       | 3.0 kB  00:00:00     
epel/x86_64/metalink                                                                                                                    | 5.9 kB  00:00:00     
epel                                                                                                                                    | 4.7 kB  00:00:00     
https://d2lzkl7pfhq30w.cloudfront.net/pub/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
Trying other mirror.
epel                                                                                                                                    | 4.7 kB  00:00:00     
(1/12): amzn2-core/2/x86_64/group_gz                                                                                                    | 2.5 kB  00:00:00     
(2/12): amzn2-core/2/x86_64/updateinfo                                                                                                  | 556 kB  00:00:00     
(3/12): amzn2extra-epel/2/x86_64/primary_db                                                                                             | 1.8 kB  00:00:00     
(4/12): amzn2extra-nginx1/2/x86_64/updateinfo                                                                                           |   76 B  00:00:00     
(5/12): amzn2extra-nginx1/2/x86_64/primary_db                                                                                           |  60 kB  00:00:00     
(6/12): amzn2extra-docker/2/x86_64/updateinfo             
`

**Comment by fscarmen** [comment]
是这样的，以前遇到过一个免费的机器是 amason 的，所以有了这个。
这些太个性厂家系统，只能用户自己先处理好环境了。

**Comment by fscarmen** [comment]
我看了一下，是 大于等于7的哦，你那里的2是你改的？
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/62703343/219335234-77d49305-c4ce-4caa-a9e5-cac398a45471.png">

**Comment by kokutoukiritsugu** [comment]
嗯, 我自己改的, 可能以前存在一个不带2的amazon linux,我没用过也不知道.

现在这个aws lightsail开的机器,系统是 "Amazon Linux 2" 名字带2, 脚本解析后就以为系统版本号是2

➜ ~ grep -i pretty_name /etc/os-release
PRETTY_NAME="Amazon Linux 2"
➜ ~ hostnamectl | grep -i system
Operating System: Amazon Linux 2

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/blob/main/menu.sh#L445
https://github.com/fscarmen/warp/blob/main/menu.sh#L446
把这两行注释掉，跳过版本号检测

**Comment by kokutoukiritsugu** [comment]
ok

**Comment by fscarmen** [comment]
可以了吗？
