### ISSUE TITLE
请支持Alma Linux和Rocky Linux！

### ISSUE THREAD

**Issue by longmoon77** [fscarmen/warp#28]
Alma Linux和Rocky Linux都是CentOS Linux 8的后继者，您不需要修改什么，只需要检测到Alma Linux和Rocky Linux不阻断安装就行，因为从本质上来看，他们就是CentOS 8。
谢谢。

**Comment by fscarmen** [comment]
谢谢你的建议。这个情况与Oracle还有Amazon Linux 一样，都是CentOS Linux 7或8的，这两个我遇到过已经处理了。至于你提到的两个，我需要准确点的信息以防翻车。
分别运行下面以下两条指令，并把输出反馈给我。
```grep -i pretty_name /etc/os-release```

```hostnamectl  | grep -i system```

**Comment by fscarmen** [comment]
话说这些官改系统都是 C8 的，没有 Debian 和 Ubuntu 的呢？

**Comment by longmoon77** [comment]
> 谢谢你的建议。这个情况与Oracle还有Amazon Linux 一样，都是CentOS Linux 7或8的，这两个我遇到过已经处理了。至于你提到的两个，我需要准确点的信息以防翻车。
> 分别运行下面以下两条指令，并把输出反馈给我。
> ```grep -i pretty_name /etc/os-release```
> 
> ```hostnamectl  | grep -i system```
> 
> 是显示  Alma Linux 8 和 Rocky Linux 8 类似的吗？

```
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
```
```
Operating System: AlmaLinux 8.5 (Arctic Sphynx)
```

**Comment by fscarmen** [comment]
> ```
> PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
> ```
> 
> ```
> Operating System: AlmaLinux 8.5 (Arctic Sphynx)
> ```

你可以按上面的方法试试alma，我把他归类到 CentOS 里了

**Comment by longmoon77** [comment]
与Amazon Linux和Oracle Linux不同，前两者更多是自己的云服务使用；而Alma Linux和Rocky Linux都是完全免费开源的社区企业级Linux操作系统，上游是RHEL。未来应该会为所有主机商使用，毕竟CentOS Stream成为了RHEL的上游失去了其稳定性和可靠性，而CentOS Linux今年年底永久停止维护。

如果您热爱玩虚拟机，欢迎测试。

我目前使用Alma Linux，因为Rocky Linux的图标太丑了，而Alma Linux的图标设计得很有特色。并且Rocky Linux是完全社区驱动的（类似于Debian），而Alma Linux则是CloudLinux，Inc.投资成立了AlmaLinux OS基金会从而为AlmaLinux OS社区带来利益。基金会成员、赞助商和合作伙伴通过投资和长期支持承诺支持 AlmaLinux OS，以确保分发不受限制、费用和收费。

你甚至可以直接从CentOS转换成Alma Linux，只需用一个[脚本](https://github.com/AlmaLinux/almalinux-deploy)。

ISO：（南京大学）http://mirrors.nju.edu.cn/almalinux/8.5/isos/x86_64/

**Comment by fscarmen** [comment]
> 我目前使用Alma Linux，因为Rocky Linux的图标太丑了，而Alma Linux的图标设计得很有特色。

是界面化的吗？还有图标的呢。

刚好有鸡 甲骨文的 CentOS 8 KVM，正在换成Alma Linux试试

**Comment by fscarmen** [comment]
Alma Linux 可以了。你先按我上面的方法：1.下载 2.修改 3.安装

![image](https://user-images.githubusercontent.com/62703343/142813760-250c3769-9436-4b52-897f-73bc4c9b51e7.png)

![image](https://user-images.githubusercontent.com/62703343/142814067-d21f4d71-c6f4-44d9-af07-4d255d52209d.png)

![image](https://user-images.githubusercontent.com/62703343/142815932-16079c0c-0238-4414-a0ae-23264397bb92.png)

**Comment by fscarmen** [comment]
Rocky Linux 也可以了。

![image](https://user-images.githubusercontent.com/62703343/142822022-69cb7109-da2d-4568-bd84-70e1cdecd38f.png)

![image](https://user-images.githubusercontent.com/62703343/142821864-fd2e6dd0-13d6-4c66-a0e5-34e5a4f32ef4.png)

![image](https://user-images.githubusercontent.com/62703343/142823119-2bee9fc4-0eb4-4b07-9a70-d51f20a05591.png)

**Comment by longmoon77** [comment]
感谢您的付出！🥰

**Comment by fscarmen** [comment]
你暂时先手动，今明两天我更新脚本的时候，把这个一并加进去就好了。11.24日开始就不用输入手动更改的命令了。
