### ISSUE TITLE
[help wanted 求助]: WARP iptable 已安装 为何hysteria还未能访问chatgpt

### ISSUE THREAD

**Issue by fredericky123** [fscarmen/warp#280]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

先用hihy安装了hysteria，由于不支持分流，故而想用warp的分流功能
因此使用wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh e安装了iptable功能
进而提示如下：
WARP iptable 已安装
 连接/断开: warp o
 卸载: warp u 

是还需要进行什么额外的设置 才能访问chatgpt吗

### Log / 日志信息

WARP iptable 已安装
 连接/断开: warp o
 卸载: warp u 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fredericky123** [comment]
似乎发现原因了 是美国机器 在韩国机器就可正常运行以上脚本步骤

**Comment by fscarmen** [comment]
不太sure hysteria 用的udp是否可以，你试试在那些机器上用xray看看

**Comment by fredericky123** [comment]
如果用全局代理wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh d
hysteria也是可以的，只是会拖慢很多其他网站

**Comment by fscarmen** [comment]
不太会啊，有相关的资料？我对科学研究少的。

**Comment by fredericky123** [comment]
> 不太会啊，有相关的资料？我对科学研究少的。

https://xtls.github.io/document/level-2/warp.html#%E7%94%B3%E8%AF%B7-warp-%E8%B4%A6%E6%88%B7

**Comment by fredericky123** [comment]
是不是脚本dnsmap还有问题 导致系统dns设置为127.0.0.1

**Comment by fscarmen** [comment]
是这样的，本地的 dnsmasq 服务

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/62703343/219819187-83de76b1-abef-42e4-bd52-1fc310dc0ae6.png">

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/62703343/219819262-f0b550b5-7472-46c3-841c-ee765025cf1b.png">

**Comment by fredericky123** [comment]
我用warp-go安装dnsmasq，由于未获取到ip失败，于是卸载warp-go，结果nameserver没改过来，导致无法联网
应该是卸载不彻底吧 导致修改没改过来

**Comment by fscarmen** [comment]
试试
```
systemctl restart systemd-resolved
sleep 5
systemctl enable --now systemd-resolved
```

**Comment by fredericky123** [comment]
好像没啥用啊 手动vim /etc/resolv.conf改了namerserver后，怎么一觉起来又变成127.0.0.1和127.0.0.53了（已经卸载了warp和warp-go）

**Comment by fredericky123** [comment]
是不是一重启就被resolvconf重写了

**Comment by fredericky123** [comment]
啊 我系统安装了一堆服务额，重置系统也太崩溃了，没有其他解决办法么，是什么缘由导致安装warp go dnsmaq失败后dns总是被修改额
能不能从脚本处解决一下额

**Comment by fredericky123** [comment]
关键是如果重置系统，一安装warp-go的dnsmaq方案一失败，不就又死循环了么

**Comment by fredericky123** [comment]
发现手动vim /etc/resolv.conf改了namerserver后，不一会儿就变成127.0.0.1和127.0.0.53了，崩溃，这是dns被哪里接管了
是warp go卸载的了本地的dnsmasq还是安装了什么导致的 完全访问不了网络了

**Comment by fscarmen** [comment]
warp-go没有对dnsmasq操作的，wgcf有个方案会，但卸载后没网友的话，用之前给你的指令应可以了，我也搞不清楚了

**Comment by fredericky123** [comment]
之前安装了一堆方案，然后又都卸载，导致vim /etc/resolv.conf里的namerserver被自动修改，现在重装了xray，目前dns正常未被修改，再持续一段时间看看
ubuntu系统，不知道是不是这个原因https://www.eccee.com/soft-platform/524.html

**Comment by fscarmen** [comment]
把该文件设为只读？

**Comment by fredericky123** [comment]
再不行的话，只好这样了

**Comment by fredericky123** [comment]
难过，重装xray还是被修改1270.0.53
感觉是我安装dnsmasq ipset那个方案后导致的 那个安装失败后的删除是不是有什么不对的地方

**Comment by fredericky123** [comment]
与此同时，服务器同时安装了hyste和xray,xray不能解析出站，而hy解析出站是正常的，难道hys不走/etc/resolv.conf里的dns解析吗

**Comment by fredericky123** [comment]
我用了chmod 444 /etc/resolv.conf，与服务器断开连接后就又被修改为了127.0.0.1 怎么回事额 是53端口被占用了么

**Comment by fscarmen** [comment]
····
sudo systemctl stop dnsmasq
sudo systemctl disable dnsmasq
sudo systemctl stop ipset
sudo systemctl disable ipset
sudo apt-get remove dnsmasq ipset
sudo systemctl enable systemd-resolved
sudo systemctl start systemd-resolved
sudo nano /etc/netplan/50-cloud-init.yaml
sudo netplan apply
```

<img width="803" alt="image" src="https://user-images.githubusercontent.com/62703343/219831991-115b5210-64d8-42ea-afb2-66ee54de3c78.png">

<img width="682" alt="image" src="https://user-images.githubusercontent.com/62703343/219832094-98f48a55-379a-4bbb-93f9-19c2bac65531.png">

<img width="689" alt="image" src="https://user-images.githubusercontent.com/62703343/219832225-ac347ce5-7244-44c7-85a3-95a0689e86cf.png">

**Comment by fredericky123** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/13982749/219835810-b6e98ec2-5cb9-42f4-aeae-831b1141998e.png">
<img width="462" alt="image" src="https://user-images.githubusercontent.com/13982749/219835923-604a4ffa-52db-425c-b0f8-82c87ac97e3b.png">
打开后没有render选项，于是自己加了这个option结果报错唉

**Comment by fredericky123** [comment]
https://dyrnq.com/ubuntu-update-etc-resolve-conf/
这个信息供参考

**Comment by fredericky123** [comment]
您好，目前我用warp d方案，似乎可以解决系统dns的问题，请问这种情况下是所有服务器的出站流量被全局代理了是吗
有没有一个关于所有方案优缺点的对比呢

想要实现warp 根据域名进行非全局代理，应该用哪种方案呢

**Comment by fscarmen2** [comment]
这个是全局双栈方案，warp接管所有的流量了，速度应该没有你原生的快的。非全局可以用 client的两个方案或者 wireproxy 方案，都需要在 v2ray 配置文件里写 routing

**Comment by fredericky123** [comment]
谢谢，这过了一会儿，又不行了，dns又被改了，唉
这各个方案直接能共存吗，一个个安装会有问题吗
我依稀记得先安装了 warp d, 又warp c, warp l, warp e,把能安装的都装了一遍，也不知道最后生效的是哪个，以及这几个方案间是否有冲突

**Comment by fscarmen2** [comment]
我晕死，你全部这样混着来，我也不知道发生什么情况了

**Comment by fredericky123** [comment]
我以为能共存😭

**Comment by fredericky123** [comment]
我以为只要卸载了warp 是不是全部就能卸载干净了

**Comment by fredericky123** [comment]
目前如果安装dnsmasq方案，会出现dnsmasq无法启动的问题，但后续依然成功获得了warp ip，如何让dnsmasq成功启动呢

● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
     Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-02-18 09:16:13 UTC; 7ms ago
    Process: 2381809 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
    Process: 2381810 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)

Feb 18 09:16:13 instance-vp systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Feb 18 09:16:13 instance-vp dnsmasq[2381809]: dnsmasq: syntax check OK.
Feb 18 09:16:13 instance-vp dnsmasq[2381810]: dnsmasq: failed to create listening socket for port 53: Address already in use
Feb 18 09:16:13 instance-vp dnsmasq[2381810]: failed to create listening socket for port 53: Address already in use
Feb 18 09:16:13 instance-vp dnsmasq[2381810]: FAILED to start up
Feb 18 09:16:13 instance-vp systemd[1]: dnsmasq.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Feb 18 09:16:13 instance-vp systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Feb 18 09:16:13 instance-vp systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.

**Comment by fscarmen2** [comment]
这个真要谷歌一下，我真的搞不清，要根据日志查查

**Comment by fredericky123** [comment]
回到最初的问题，用了dnsmasq ipset方案，目前xray能访问chatgpt，而hysteria不能，是需要做额外的出站设置吗

**Comment by fredericky123** [comment]
另外一个请求，能否将回国流量根据域名cn添加到ipset方案中

**Comment by fscarmen2** [comment]
> 回到最初的问题，用了dnsmasq ipset方案，目前xray能访问chatgpt，而hysteria不能，是需要做额外的出站设置吗

那个 iptabels 分流的可能没有处理到udp的流量。 回国流量那个是在Xray配置里设置的，不同的脚本安装时的配置文件都不一样，所以应该找你使用的xray脚本作者处理。添加一个选项。

**Comment by fredericky123** [comment]
查了下，iptables是可以支持udp转发的，蹲一个更新。
回国那个确实在xray的脚本能设置，我想着在hysteria里也实现回国流量走warp

**Comment by fredericky123** [comment]
好神奇，dnsmasq方案用一段时间后，hysteria也能访问chatgpt了，难道是刚开始的时候dns没生效

**Comment by lucky2046** [comment]
能否给个干净的教程？

**Comment by fredericky123** [comment]
先hihy
再wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh e

**Comment by lucky2046** [comment]
请问，您这个方案和https://github.com/willoong9559/XrayWarp这个方案有什么差异

**Comment by fredericky123** [comment]
我用于hysteria协议，那个用于xray(⊙o⊙)…

**Comment by lucky2046** [comment]
> 先hihy 再wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh e
我试了menu.sh e或者menu.sh d，warp重连5次都不成功啊

**Comment by fredericky123** [comment]
> > 先hihy 再wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh e
> > 我试了menu.sh e或者menu.sh d，warp重连5次都不成功啊

这就是玄学了 前天我一次就成功 昨天怎么都不成功 今天一试就成功

**Comment by lucky2046** [comment]
这个脚本一用就不能上网了

**Comment by lucky2046** [comment]
我是干净的系统

**Comment by fscarmen** [comment]
> > > 先hihy 再wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh e
> > > 我试了menu.sh e或者menu.sh d，warp重连5次都不成功啊
> 
> 这就是玄学了 前天我一次就成功 昨天怎么都不成功 今天一试就成功

是指hysteria吗？

**Comment by lucky2046** [comment]
> 试试
> 
> ```
> systemctl restart systemd-resolved
> sleep 5
> systemctl enable --now systemd-resolved
> ```

用这个可以ping通google了

**Comment by fredericky123** [comment]
估计和我中途一样，想办法成功安装上dnsmasq就能上网了，我估计warp e是修改了系统的dns，或者你手动修改vim /etc/resolv.conf李的dns 看看是不是dns

**Comment by fredericky123** [comment]
> > > > 先hihy 再wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh e
> > > > 我试了menu.sh e或者menu.sh d，warp重连5次都不成功啊
> > 
> > 
> > 这就是玄学了 前天我一次就成功 昨天怎么都不成功 今天一试就成功
> 
> 是指hysteria吗？

是用warp e安装时获取warp ip失败，和协议没关系吧；昨天反复装卸，出现了无法获取，后来歇了一天就能正常获取了

**Comment by lucky2046** [comment]
我的/etc/resolv.conf文件内容是这样的

```
nameserver 127.0.0.53
options edns0
search ubuntu
```

**Comment by lucky2046** [comment]
我没有安装hysteria，直接用的menu.sh，分别试了e和d选项，warp -o都不能成功，然后我就卸载，就ping不同google了

**Comment by fredericky123** [comment]
和我的一样，不能上网的时候，改为1.1.1.1就能上了 可是又会被改过去
你用systemctl restart systemd-resolved能生效，就比我好很多了 我当时那个无效

**Comment by fredericky123** [comment]
> 我没有安装hysteria，直接用的menu.sh，分别试了e和d选项，warp -o都不能成功，然后我就卸载，就ping不同google了

系统dns被修改的原因

**Comment by fscarmen** [comment]
> 请问，您这个方案和[https://github.com/willoong9559/XrayWarp  这个方案有什么差异]

(https://github.com/willoong9559/XrayWarp%E8%BF%99%E4%B8%AA%E6%96%B9%E6%A1%88%E6%9C%89%E4%BB%80%E4%B9%88%E5%B7%AE%E5%BC%82)

就是菜单5的选项啊

**Comment by fscarmen** [comment]
systemctl restart systemd-resolved
这个要加点延时上去才行，我发现有的机器网络还是硬件的原因，导致这条命令在卸载的时候偶尔没有正确执行，我记下来，一并处理下先

**Comment by lucky2046** [comment]
我恢复联网的操作如下：
sudo systemctl stop dnsmasq
sudo systemctl disable dnsmasq
sudo systemctl stop ipset
sudo systemctl disable ipset
sudo apt-get remove dnsmasq ipset
sudo systemctl enable systemd-resolved
sudo systemctl start systemd-resolved
然后从其他机器恢复了/etc/netplan/50-cloud-init.yaml文件的内容
```
network:
    ethernets:
        ens3:
            dhcp4: true
            match:
                macaddress: 02:00:17:00:2a:da
            set-name: ens3
    version: 2
```

然后执行
```
systemctl restart systemd-resolved
sleep 5
systemctl enable --now systemd-resolved
```
执行完就可以上网了
现在/etc/resolv.conf 的内容仍然是
```
nameserver 127.0.0.53
options edns0
search vcn06281928.oraclevcn.com
```

**Comment by fredericky123** [comment]
关键步骤应该就是这个
systemctl restart systemd-resolved
sleep 5
systemctl enable --now systemd-resolved

**Comment by lucky2046** [comment]
> 关键步骤应该就是这个 systemctl restart systemd-resolved sleep 5 systemctl enable --now systemd-resolved

应该是的

**Comment by fscarmen** [comment]
> 我恢复联网的操作如下： sudo systemctl stop dnsmasq sudo systemctl disable dnsmasq sudo systemctl stop ipset sudo systemctl disable ipset sudo apt-get remove dnsmasq ipset sudo systemctl enable systemd-resolved sudo systemctl start systemd-resolved 然后从其他机器恢复了/etc/netplan/50-cloud-init.yaml文件的内容
> 
> ```
> network:
>     ethernets:
>         ens3:
>             dhcp4: true
>             match:
>                 macaddress: 02:00:17:00:2a:da
>             set-name: ens3
>     version: 2
> ```
> 
> 然后执行
> 
> ```
> systemctl restart systemd-resolved
> sleep 5
> systemctl enable --now systemd-resolved
> ```
> 
> 执行完就可以上网了 现在/etc/resolv.conf 的内容仍然是
> 
> ```
> nameserver 127.0.0.53
> options edns0
> search ubuntu
> ```

systemctl enable --now systemd-resolved

我dnsmasq卸载的时候发现没有网，运行这个就马上恢复正常了。

**Comment by fredericky123** [comment]
各个方案的优缺点能否出个合集说明呀，并且提示大家各个方案不能溶蚀安装

**Comment by lucky2046** [comment]
> > 请问，您这个方案和[https://github.com/willoong9559/XrayWarp]  这个方案有什么差异
> 
> ![image](https://user-images.githubusercontent.com/62703343/219875596-694f79cc-de6d-4cae-b322-ab17cc2bdb91.png)
> 
> 就是菜单5的选项啊

我运行了，最后显示开启了socks5端口，我在本地用v2ray连socks5的40000端口为啥连google都上不去啊

**Comment by lucky2046** [comment]
选择7之后，vps都连不上了

**Comment by fscarmen** [comment]
> > > 请问，您这个方案和[https://github.com/willoong9559/XrayWarp]  这个方案有什么差异
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62703343/219875596-694f79cc-de6d-4cae-b322-ab17cc2bdb91.png)
> > 就是菜单5的选项啊
> 
> 我运行了，最后显示开启了socks5端口，我在本地用v2ray连socks5的40000端口为啥连google都上不去啊
> 
> ```
> root@ubuntu:~# lsof -i:40000
> COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> warp-svc 19323 root   19u  IPv4  88123      0t0  TCP localhost:40000 (LISTEN)
> warp-svc 19323 root   21u  IPv4  87200      0t0  TCP localhost:40000->localhost:37056 (CLOSE_WAIT)
> ```

是不是v2ray的配置文件写错了，你是如何写的？

**Comment by fscarmen** [comment]
> 
```
systemctl enable --now systemd-resolved
```

我dnsmasq卸载的时候发现没有网，运行这个就马上恢复正常了

**Comment by lucky2046** [comment]
> > > > 请问，您这个方案和[https://github.com/willoong9559/XrayWarp]  这个方案有什么差异
> 
> > > 
> 
> > > 
> 
> > > ![image](https://user-images.githubusercontent.com/62703343/219875596-694f79cc-de6d-4cae-b322-ab17cc2bdb91.png)
> 
> > > 就是菜单5的选项啊
> 
> > 
> 
> > 我运行了，最后显示开启了socks5端口，我在本地用v2ray连socks5的40000端口为啥连google都上不去啊
> 
> > 
> 
> > ```
> 
> > root@ubuntu:~# lsof -i:40000
> 
> > COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> 
> > warp-svc 19323 root   19u  IPv4  88123      0t0  TCP localhost:40000 (LISTEN)
> 
> > warp-svc 19323 root   21u  IPv4  87200      0t0  TCP localhost:40000->localhost:37056 (CLOSE_WAIT)
> 
> > ```
> 
> 
> 
> 是不是v2ray的配置文件写错了，你是如何写的？

我telnet也不成功，本地看到端口是开了的

**Comment by lucky2046** [comment]
前两天也出现vps永远连不上的情况，看来卸载有时会有问题

**Comment by lucky2046** [comment]
是不是warp的模式不对导致的，全局模式就会出现ssh访问问题

**Comment by fscarmen** [comment]
> 是不是warp的模式不对导致的，全局模式就会出现ssh访问问题

有一个可能是脚本检测系统网络时出错导致使用错了模板，这样的情况下有可能会失联，如果有vnc的厂商，像甲骨文的可以进去看看。

**Comment by fscarmen** [comment]
> > 不太会啊，有相关的资料？我对科学研究少的。
> 
> https://xtls.github.io/document/level-2/warp.html#%E7%94%B3%E8%AF%B7-warp-%E8%B4%A6%E6%88%B7

谢谢，我没有用到回国通过 wireguard ，反正用到链式代理，使不用安装 warp，也能使用 warp 的服务来解锁 chatGPT.

[刷 Netflix 解锁 WARP IP 的方法](README.md#刷-Netflix-解锁-WARP-IP-的方法)

**Comment by lucky2046** [comment]
> 



> > > 不太会啊，有相关的资料？我对科学研究少的。
> > 
> > 
> > https://xtls.github.io/document/level-2/warp.html#%E7%94%B3%E8%AF%B7-warp-%E8%B4%A6%E6%88%B7
> 
> 谢谢，我没有用到回国通过 wireguard ，反而启发了我用到链式代理，使不用安装 warp，也能使用 warp 的服务来解锁 chatGPT.
> 
> [刷 Netflix 解锁 WARP IP 的方法](README.md#%E5%88%B7-Netflix-%E8%A7%A3%E9%94%81-WARP-IP-%E7%9A%84%E6%96%B9%E6%B3%95)

怎么用warp的服务解锁chatGPT，我现在是通过warp-cli客户端结合V2Ray解锁chatGPT的

**Comment by fscarmen** [comment]
这里不是有吗？用cli的方法没有这个厉害，除非你的机器是香港或者LA的。

<img width="925" alt="image" src="https://user-images.githubusercontent.com/62703343/221149335-e6d76ec7-87f8-4067-a57a-a248fd5bc75d.png">

**Comment by lucky2046** [comment]
> 这里不是有吗？用cli的方法没有这个厉害，除非你的机器是香港或者LA的。
> 
> <img alt="image" width="925" src="https://user-images.githubusercontent.com/62703343/221149335-e6d76ec7-87f8-4067-a57a-a248fd5bc75d.png">

我是甲骨文首尔的，通过warp-cli也可以上chatGPT

**Comment by fscarmen** [comment]
这个方案不需要安装 warp-cli ，直连 warp，节省系统资源。

**Comment by lucky2046** [comment]
> 这个方案不需要安装 warp-cli ，直连 warp，节省系统资源。

好的，感谢
