### ISSUE TITLE
刷warp+的方法基本都寄了-【结论：现在都用机器人获取 12PB 的 license 了，登陆一次，再换回自己原有的，即可变成12PB，https://t.me/warpplus】

### ISSUE THREAD

**Issue by Fangliding** [fscarmen/warp#281]
如题 warp p出来的三个项目 第一个被gayhub打击了 第二个疑似删库 第三个已经read only
第一个项目涉及git clone已经不可用了。第二个项目跑了似乎没有用 第三个项目报错说无法连接api
解决办法 嗯 找活着的项目换上去
第一个项目我找到一个fork跑了一下 似乎和第三个一样提示无法连接 不知道是不是cloudflare修改过相关设计了

**Comment by Michaol** [comment]
![image](https://user-images.githubusercontent.com/22289837/221060278-58adf1ba-34fe-4592-a28d-f9aefc501a79.png)

**Comment by fscarmen** [comment]
现在直接加12PB还是17PB的机器人，天天发几次license 你更换他 license ，再换回你的，马上有12 PB ，再也不想刷了。

**Comment by Fangliding** [comment]
> 现

有没有一种可能那个bot是我联系作者修的()
顺带一提 是26TB warp有这种bug就挺离谱
复制warp+我很早就知道了 只是一个broken的part在里面多少有点不合适 我找了个可以用的https://github.com/navaneethkm004/warp-plus 工作原理和以前差不多 要不就干脆移除掉

**Comment by 365active** [comment]
> 

请问登录指的是zero trust？

**Comment by 365active** [comment]
> 现在直接加12PB还是17PB的机器人，天天发几次license 你更换他 license ，再换回你的，马上有12 PB ，再也不想刷了。 https://t.me/warpplus

请问登录指的是zero trust？

**Comment by fscarmen** [comment]
手机下载个1.1.1.1 app ，先记下你原有的license ，更换他的，看到已经有23PB了，再换回你自己的，这样你也有23PB了，而且是你自己的 license ，不是与别人共用了

**Comment by fscarmen** [comment]
> > 现
> 
> 有没有一种可能那个bot是我联系作者修的() 顺带一提 是26TB warp有这种bug就挺离谱 复制warp+我很早就知道了 只是一个broken的part在里面多少有点不合适 我找了个可以用的https://github.com/navaneethkm004/warp-plus 工作原理和以前差不多 要不就干脆移除掉

很有可能，快教下我玩最新的 xray REALITY ，我想弄弄项目。

**Comment by 365active** [comment]
> 手机下载个1.1.1.1 app ，先记下你原有的license ，更换他的，看到已经有23PB了，再换回你自己的，这样你也有23PB了，而且是你自己的 license ，不是与别人共用了

怎么我换回自己的就没流量了……

**Comment by fscarmen** [comment]
> > 手机下载个1.1.1.1 app ，先记下你原有的license ，更换他的，看到已经有23PB了，再换回你自己的，这样你也有23PB了，而且是你自己的 license ，不是与别人共用了
> 
> 换他的能看到流量，但是换回自己的就没流量了囧……

是不是退出重进就行了？主页上有说刷新数据的方法的。

**Comment by 365active** [comment]
> > > 手机下载个1.1.1.1 app ，先记下你原有的license ，更换他的，看到已经有23PB了，再换回你自己的，这样你也有23PB了，而且是你自己的 license ，不是与别人共用了
> > 
> > 
> > 换他的能看到流量，但是换回自己的就没流量了囧……
> 
> 是不是退出重进就行了？主页上有说刷新数据的方法的。

也不成功，估计cf修复了？

**Comment by Fangliding** [comment]
> > > 现
> > 
> > 
> > 有没有一种可能那个bot是我联系作者修的() 顺带一提 是26TB warp有这种bug就挺离谱 复制warp+我很早就知道了 只是一个broken的part在里面多少有点不合适 我找了个可以用的https://github.com/navaneethkm004/warp-plus 工作原理和以前差不多 要不就干脆移除掉
> 
> 很有可能，快教下我玩最新的 xray REALITY ，我想弄弄项目。

这里有模板https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY 文档还在写()

**Comment by fscarmen** [comment]
> > > > 现
> > > 
> > > 
> > > 有没有一种可能那个bot是我联系作者修的() 顺带一提 是26TB warp有这种bug就挺离谱 复制warp+我很早就知道了 只是一个broken的part在里面多少有点不合适 我找了个可以用的https://github.com/navaneethkm004/warp-plus 工作原理和以前差不多 要不就干脆移除掉
> > 
> > 
> > 很有可能，快教下我玩最新的 xray REALITY ，我想弄弄项目。
> 
> 这里有模板https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY 文档还在写 记得去action下最新的building release还没发()

这个REALITY是不是只对直连起作用，对于像我这样用cdn tls 的，是不是没有作用的？

**Comment by Michaol** [comment]
> 

是的，不支持CDN

**Comment by fscarmen** [comment]
> > 
> 
> 是的，不支持CDN

直连我更喜欢暴力的 hysteria 和简单的 ss
