### ISSUE TITLE
[help wanted 求助]: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by msshn** [fscarmen/warp#282]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

I have xray + fake website on my vps and using Vless + TCP + TLS with valid certificates issued by Let's Encrypt
after installing WARP, my connection works for a few minutes and then disconnect with the following error in V2rayn:
"app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [x509: certificate signed by unknown authority] > common/retry: all retry attempts failed"
If I change Cloudflare IP, It will work for a few minutes and then disconnects again with the same error

### Log / 日志信息

no log

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
It have another better choice : https://github.com/fscarmen/ArgoX.
It is working using Vless + TCP + TLS without valid certificates.
We connect the vps with Cloudflare Argo tunnel.

**Comment by msshn** [comment]
Great, Thank you. Can it apply to existing xray instances ?

**Comment by fscarmen** [comment]
> Great, Thank you. Can it apply to existing xray instances ?

I think it 's better to uninstall the exsting one.
