### ISSUE TITLE
[Feature request]: dnsmasq方案能否支持添加域名

### ISSUE THREAD

**Issue by fredericky123** [fscarmen/warp#283]
### Related Problem / 相关问题

目前dnsmasq方案是内置了chatgpt,google等网址，能否支持自定义根据域名选择是否走warp代理

### Describe the solution you want / 描述你希望的解决方案

根据geosite的域名，如cn, youtube等自定义哪些域名走dnsmasq的warp代理

### Describe the alternatives you are considering / 描述你所考虑的替代方案

类似这个脚本里的方案，可以自定义域名走warp代理
https://github.com/mack-a/v2ray-agent

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
dnsmasq+ipset不太适合你说的那个场景，他只适合某几个网这样的分流。因为很不好管理的。你的要求其实有更好的解决方案，要么服务端在xray配置文件里，配合两个geo*.dat的文件来判断官网归属从而来分流。要么在客户端的clash里作分流，都是比较好的。

**Comment by fredericky123** [comment]
由于使用的是hys协议，故而服务器端xray分流的方案不适用了，不知道如何在clash客户端实现这一分流

**Comment by fscarmen** [comment]
哦，用hys的确没有 xray 那样处理，在 clash 的话，用clash.meta内核，支持hysteria协议，至于使用的模板，你可以找找谷歌和查查油管使用的方法，十分方便

**Comment by fredericky123** [comment]
不过我的目的是想让服务器访问国内网址时，全走warp，从而保护服务器ip隐私（例如全局模式下访问国内网站），clash客户端设置好也只是本地分流，而起不到保护服务器的作用唉

**Comment by fscarmen** [comment]
这个我就没有更深的研究了。
