### ISSUE TITLE
[help wanted 求助]: warp-go在v2ray配置文件中分流问题

### ISSUE THREAD

**Issue by huajuandeba** [fscarmen/warp#284]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

本人小白 安装了大佬的warp但是每次都是5次失败，查了一下之前的问题，我的vps在LA所以试了试wrap go 获得了可以解锁的ipv4地址
![1](https://user-images.githubusercontent.com/125900814/221790453-5e7d6225-116a-4281-8e47-33b45ee93244.png)

我想达成看netflix的时候使用warp go的节点，其他访问走自己的vbs节点
设备是软路由 固件是istoreos（openwrt）   插件是ssr plus+
因为我看warp有代理功能，可能开启之后就能在ssr plus+里面配置了，但是我现在无法用warp在warp go中没有看到相关功能，请问后续怎么设置能达成分流。

### Log / 日志信息

root@huajuan:~# warp-go

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 本项目专为 VPS 添加 WARP 网络接口，使用 wire-go 核心程序，利用CloudFlare-WARP 的各类接口，集成 wireguard-go，可以完全替代 WGCF。 救活了香港、多伦多等 VPS 也可以获取 WARP IP。再次感谢 @CoiaPrant 及其团队。项目地址: https://gitlab.com/ProjectWARP/warp-go/-/tree/master/ 
======================================================================================================================

 脚本版本: 1.1.0
 功能新增: 支持 OpenWrt 系统
 系统信息:
	 当前操作系统: Debian GNU/Linux 10 (buster)
	 内核: 6.1.11-bbrplus
	 处理器架构: amd64v2
	 虚拟化: kvm 
	 IPv4: 104.28.217.74  美国  Cloudflare 
	 IPv6:      
	 WARP free 网络接口已开启 
	 运行在 非全局 模式 

======================================================================================================================

 1. WARP 非全局 IPv4 转为 WARP 全局 IPv4 (warp-go 4) 
 2. WARP 非全局 IPv4 转为 WARP 全局 双栈 (warp-go d) 
 3. 转为 WARP 全局 网络接口 (warp-go g) 
 4. 关闭 warp-go (warp-go o) 
 5. 更换为 Free，WARP+ 或 Teams 账户 (warp-go a) 
 6. 更换支持 Netflix 的 IP (warp-go i) 
 7. 输出 wireguard 和 sing-box 配置文件 (warp-go e) 
 8. 卸载 WARP 网络接口和 warp-go (warp-go u) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
如果你是使用xray的话，在xray配置文件里分流即可。具体可以参考这里。记得做好配置文件的备份工作
https://github.com/fscarmen/warp/blob/main/README.md#netflixgoogle-%E5%88%86%E6%B5%81%E5%88%B0-client-warp-%E7%BD%91%E7%BB%9C%E6%8E%A5%E5%8F%A3%E7%9A%84%E6%96%B9%E6%B3%95

**Comment by huajuandeba** [comment]
> 如果你是使用xray的话，把warp-go设为非全局方案，在xray配置文件里分流即可。具体可以参考这里。记得做好配置文件的备份工作 https://github.com/fscarmen/warp/blob/main/README.md#netflixgoogle-%E5%88%86%E6%B5%81%E5%88%B0-client-warp-%E7%BD%91%E7%BB%9C%E6%8E%A5%E5%8F%A3%E7%9A%84%E6%96%B9%E6%B3%95

请问是把我现有配置文件里的outbounds全部替换，还是直接添加？
![2](https://user-images.githubusercontent.com/125900814/222025152-316a37b8-c046-4617-89a4-4f1ab5359a8c.png)

**Comment by fscarmen** [comment]
增加即可，不要把原来的去掉

**Comment by huajuandeba** [comment]
> 增加即可，不要把原来的去掉。像 [#286 (comment)](https://github.com/fscarmen/warp/issues/286#issuecomment-1449523406) 一样，他原来有DNS解锁奈飞的，所以在他原来的基础上增加 outbound 和 routing 即可，把 chatGPT的放在 routing的最开始比较好。

ludan老师的dns那段不需要加进去是么 就是整个配置文件里面两个“outbound”和“routing”

**Comment by huajuandeba** [comment]
> 那个是不同的方案来的，不能混在一起。

{
    "outbounds":[
        {
            "tag":"INTERNET_OUT",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIP"
            }
        },
        {
            "tag":"CLI_OUT",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv4"
            },
            "sendThrough":"我warp-go的ip"
        }
    ],
    "routing":{
        "rules":[
            {
                "type":"field",
                "outboundTag":"CLI_OUT",
                "domain":[
                    "geosite:google",
                    "geosite:netflix",
                    "domain:ip.gs"
                ]
            },
            {
                "type":"field",
                "outboundTag":"INTERNET_OUT",
                "network":"udp,tcp"
            }
        ]
    }
}


就是把上面这些加到我v2ray的config.json里面 就可以了对吧

**Comment by fscarmen** [comment]
你在分流那里需要把 ai.com / openai.com 加上啊，warp-go 可以用非全局

**Comment by fscarmen** [comment]
用 warp-go 非全局的话，模板这样改应该可以的
```
{
    "outbounds":[
        {
            "tag":"INTERNET_OUT",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIP"
            }
        },
        {
            "tag":"WARP-GO_INTERFACE",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv4"
            },
            "sendThrough":"172.16.0.2"
        }
    ],
    "routing":{
        "rules":[
            {
                "type":"field",
                "outboundTag":"WARP-GO_INTERFACE",
                "domain":[
                    "geosite:google",
                    "geosite:netflix",
                    "domain:ip.sb",
                    "domain:openai.com",
"domain:ai.com"

                ]
            },
            {
                "type":"field",
                "outboundTag":"INTERNET_OUT",
                "network":"udp,tcp"
            }
        ]
    },
    "dns":{
        "servers":[
            "1.1.1.1",
            "1.0.0.1"
        ]
    }
}
```

**Comment by huajuandeba** [comment]
试了好久编辑config.json（我不太懂linux，一直在google搜）我就把您上面编辑的字段用vim粘到了我的配置文件中，可以正常翻墙，但是netflix也没解锁，索性vps rebuild，重新安装v2ray warp-go 直接选1全局代理了，终于解锁非自制剧了，我都忘了之前看了哪篇提问，好像说全局代理可能会有什么影响。。。我放弃编辑配置文件分流了，我怀疑跟我的v2ray设置有关系，我之前是vless+mkcp，或者是跟我装的bbrplus内核有关系？

**Comment by DavidHuc** [comment]
你好，我也遇到了相似问题，所以直接在这里回帖请求各位帮忙debug。我的机器是在LA，参考说明，采用的warp-go脚本直接进行ipv4配置。系统及科学环境是centos 7, v2ray 4.45.2 +vmess+tls+websocket，配合ngix。因为需要用chatgpt，所以尝试warp。现在的问题是，如果我用warp-go的global模式，就可以正常warp，但是使用non-global模式，分流似乎失败了。以下是我的配置文件。

{
  "inbound": {
    "listen": "**(敏感信息手动打码)",
      "port": **(敏感信息手动打码),
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "alterId": **(敏感信息手动打码),
            "id": "**(敏感信息手动打码)"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "connectionReuse": false,
          "path": "**(敏感信息手动打码)",
          "headers": {
            "Host": "**(敏感信息手动打码)"
          }
        }
      }
  },
  "inboundDetour": [],
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  
  "outbound": [
    {
            "tag":"INTERNET_OUT",
            "protocol":"freedom",
            "settings":{}
        },
        {
            "tag":"CLI_OUT",
            "protocol":"freedom",
            "settings":{},
            "sendThrough":"**(敏感信息手动打码，warp-go反馈给我的clf IPv4地址)"
        }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "settings": {
      "rules": [
        {
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked",
          "type": "field"
        },
        {
                "type":"field",
                "outboundTag":"CLI_OUT",
                "domain":[
                    "geosite:google",
                    "geosite:netflix",
                    "domain:ip.gs"
                    "domain:openai.com"
                    "domain:ai.com"
                    ”domain:he.net" (特地加了一行，方便用bgp.he.net验证是否成功warp)
                ]
            },
        {
                "type":"field",
                "outboundTag":"INTERNET_OUT",
                "network":"tcp,udp"
          }
      ]
    },
    "strategy": "rules"
  }
}

因为加了he.net在warp列表中，比较方便测试。我在不使用global模式时，只有一个ipv4的clf地址，并且无法顺利转发；当我把warp-go切换成global模式后，可以顺利warp，同时，值得注意的是，warp-go多给了一个ipv6的clf地址。

我试图自己debug，把v2ray里面log部分从"warning"提升到"debug"或者"info"，但是没有额外log，不清楚问题发生在哪里，特地来求助。另外，我看到有的帖子说netflix需要sniffering，请问是否如此，如果需要，该如何设置？想一步做到位，别再改来改去了。

谢谢

**Comment by fscarmen** [comment]
> "type":"field",
> "outboundTag":"CLI_OUT",
> "domain":[
> "geosite:google",
> "geosite:netflix",
> "domain:ip.gs"
> "domain:openai.com"
> "domain:ai.com"
> ”domain:he.net" (特地加了一行，方便用bgp.he.net验证是否成功warp)
> ]

你这段有严重的格式问题，没有了 ,  同时  he.net 最开头的 " 也是中文全角，建议你改好后，去 https://www.json.cn/ 验证你改的json是否有问题。你这样连v2ray都运行不起来的。
<img width="641" alt="image" src="https://user-images.githubusercontent.com/62703343/224196593-8b3ffad8-fbd5-405a-869e-b5fccf0fcb09.png">

```
"type":"field",
"outboundTag":"CLI_OUT",
"domain":[
"geosite:google",
"geosite:netflix",
"domain:ip.gs",
"domain:openai.com",
"domain:ai.com",
"domain:he.net"
]
```

**Comment by fscarmen** [comment]
根据 v2ray [官网](https://www.v2ray.com/chapter_02/02_protocols.html) 显示，不支持 wireguard ，所以要改用 xray

<img width="303" alt="image" src="https://user-images.githubusercontent.com/62703343/224883000-a044fe44-e046-493e-b273-f6e220766014.png">

**Comment by fscarmen** [comment]
> BTW，我报一个warp-go.sh的小bug。我重置系统以后，root权限下，如果直接运行 warp-go.sh，第一步是会自动安装wget，但此时系统就会永远卡在那一步了，我不清楚具体问题是什么。但如果我先"yum install -y wget"再运行warp-go.sh，就不会有问题了。

我在 GCP 上开了台 CentOS 9 的机器，手动执行 yum install wget 会卡死 ，yum update 也卡死，感觉是 CentOS 9 的问题，脚本执行这两个命令，就会像你说的卡死了，但至于为什么你手动可以，我也无法解析了，建议你换个系统，最好是 debian 或者 ubuntu 的。

**Comment by DavidHuc** [comment]
> 根据 v2ray [官网](https://www.v2ray.com/chapter_02/02_protocols.html) 显示，不支持 wireguard ，所以要改用 xray
> 
> <img alt="image" width="303" src="https://user-images.githubusercontent.com/62703343/224883000-a044fe44-e046-493e-b273-f6e220766014.png">

感谢，我已经换了xray，现在可以把相关tag的定义写在outbound里了，但是还是不行。正常启动以后，可以在access.log里看到分流，但是网站依旧无法访问。

**Comment by fscarmen** [comment]
Debian 10 / Debian 11 / Ubuntu 20.04 / Ubuntu 22.04

**Comment by DavidHuc** [comment]
> > 根据 v2ray [官网](https://www.v2ray.com/chapter_02/02_protocols.html) 显示，不支持 wireguard ，所以要改用 xray
> > <img alt="image" width="303" src="https://user-images.githubusercontent.com/62703343/224883000-a044fe44-e046-493e-b273-f6e220766014.png">
> 
> 感谢，我已经换了xray，现在可以把相关tag的定义写在outbound里了，但是还是不行。正常启动以后，可以在access.log里看到分流，但是网站依旧无法访问。

谢谢，我最后解决了。似乎是不能用sendthrough，我最后被迫手动装了warp-go和wireguard，然后把wireguard配置文件放进去启动，最后成功了。

**Comment by fscarmen** [comment]
> 谢谢，我最后解决了。似乎是不能用sendthrough，我最后被迫手动装了warp-go和wireguard，然后把wireguard配置文件放进去启动，最后成功了。

你可以试试我的另一个 xray 脚本  ArgoX: https://github.com/fscarmen/ArgoX ，配套的服务网 [fscarmen.cloudflare.now.cc/](https://fscarmen.cloudflare.now.cc/) 可以生成 warp 注册信息，就不用你手动安装warp-go和wireguard。

**Comment by hezudao13** [comment]
用大佬的配置可以非全局，但是LZ你的配置里"sendThrough"应该填"172.16.0.2"而不是自己的出口IP啊 。FYI
