### ISSUE TITLE
[help wanted 求助]: 正确获取了 warp IPV4的地址，ip 是我VPS的真实ip-【结论：全局下应该是 warp 接管了所有的出口流量了，不太清楚为什么不生效，只能用户自行排查了】

### ISSUE THREAD

**Issue by LXCLI** [fscarmen/warp#285]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

安装了脚本，也正确获取了IPV4的地址，但是通过SSR访问谷歌的时候还是会显示人机验证，而且ip是我VPS的真实ip，是我什么地方漏掉了吗

### Log / 日志信息

安装了脚本，也正确获取了IPV4的地址，但是通过SSR访问谷歌的时候还是会显示人机验证，而且ip是我VPS的真实ip，是我什么地方漏掉了吗

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你用什么方案？

**Comment by LXCLI** [comment]
用的是双栈那个，然后ssr用的是PAC。
![image](https://user-images.githubusercontent.com/126491007/221869359-9f8bf339-2016-4562-a35b-249d5fc3b297.png)

**Comment by fscarmen** [comment]
你先试试ssr用全局，因为你的vps已经是warp全局了，不可能不走 warp 的

**Comment by LXCLI** [comment]
刚刚试了，还是会出机器人验证，然后提示我的ip还是vps的原ip，离谱

**Comment by LXCLI** [comment]
这个应该不用重启服务器叭，配置过程也挺顺利的，没报错发自我的手机-------- 原始邮件 --------发件人： fscarmen ***@***.***>日期： 2023年2月28日周二 晚上9:37收件人： fscarmen/warp ***@***.***>抄送： LXCLI ***@***.***>, Author ***@***.***>主    题： Re: [fscarmen/warp] [help wanted 求助]:  (Issue #285)

你先试试ssr用全局，因为你的vps已经是warp全局了，不可能不走 warp 的

**Comment by fscarmen** [comment]
搞不清楚，显示你vps原生的 IP太奇怪了

**Comment by fscarmen** [comment]
> 正常来说，应该配置完wrap就不用配置别的了吧，应该直接就默认用wrap的ip了吧

是的，我也是这样认为的，所以我也搞不不清楚了。

**Comment by xuanmenliuyao** [comment]
我也是出现了这个问题，能后成功输出ip，但实际访问网站还是原ip。请问解决了吗？也是Ubuntu，云服务器，安装的是”12“
后来发现安装的时候有个报错：
‘’‘
invoke-rc.d: initscript dnsmasq, action "start" failed.
× dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
     Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-03-06 12:59:34 CST; 31ms ago
    Process: 31677 ExecStartPre=/etc/init.d/dnsmasq checkconfig (code=exited, status=0/SUCCESS)
    Process: 31687 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
        CPU: 33ms

Mar 06 12:59:34 VM-0-11-ubuntu systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Mar 06 12:59:34 VM-0-11-ubuntu dnsmasq[31687]: dnsmasq: failed to create listening socket for port 53: Address already in use
Mar 06 12:59:34 VM-0-11-ubuntu systemd[1]: dnsmasq.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Mar 06 12:59:34 VM-0-11-ubuntu dnsmasq[31687]: failed to create listening socket for port 53: Address already in use
Mar 06 12:59:34 VM-0-11-ubuntu systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Mar 06 12:59:34 VM-0-11-ubuntu dnsmasq[31687]: FAILED to start up
Mar 06 12:59:34 VM-0-11-ubuntu systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Setting up libavahi-common-data:amd64 (0.8-5ubuntu5) ...
’‘’

**Comment by xuanmenliuyao** [comment]
邮件已收到，感谢您。
