### ISSUE TITLE
关于warp team是否真的有warp plus的效果

### ISSUE THREAD

**Issue by Fangliding** [fscarmen/warp#289]
关于下载速度 我在4Gbps的arm上测了一下free和plus实际都是七八百Mbps 最大速度应该没区别

关于延迟 本人使用的测试命令 从谷歌抄来的

`curl -o /dev/null -s -w 'time_namelookup: %{time_namelookup}\ntime_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n' https://derpicdn.net/img/view/2023/3/5/3058007.png`

对于非cloudflare网站 不仅是readme的解释还是本人实测都没有区别 不作讨论
命令是测试curl一个cloudflare网站的一张图 分析打开连接时间 开始传输时间 和总时间
我自己多轮测试出来的结论 虽然team在cf的网站会显示为plus 但是team和free基本是一样的 真正的warp plus延迟会稍微稳定和低一丢丢 从readme的介绍看plus优化的是edge到源的这部分 真正的源大概率是在美国的 我用欧洲鸡测可能感知不强 如果用香港新加坡或者其他旮旯地方或许感知更强

还有一个没什么用的小发现 因为warp plus只加速cf网站所以cf会很良心的只扣访问cf的流量(测试命令 从cf speedtest下载一个1GB大小的文件 字节可以自己改 下到dev/null不需要你去再删掉 `wget "https://speed.cloudflare.com/__down?bytes=1073741824" -O /dev/null`) 以及上传去非cf网站好像会按小比例扣除流量

**Comment by baby9** [comment]
我可以很明确地告诉你，plus和free是有区别的，在香港这个部分warp服务被ban的地方，晚高峰plus的速度是free的三倍以上，且非常稳定

**Comment by baby9** [comment]
> 我可以很明确地告诉你，plus和free是有区别的，在香港这个部分warp服务被ban的地方，晚高峰plus的速度是free的三倍以上，且非常稳定

纪念wgcf in HK被ban一周年

**Comment by fscarmen** [comment]
> > 我可以很明确地告诉你，plus和free是有区别的，在香港这个部分warp服务被ban的地方，晚高峰plus的速度是free的三倍以上，且非常稳定
> 
> 纪念wgcf in HK被ban一周年

希望明年的今日看不到你纪念二周年的贴子

**Comment by Fangliding** [comment]
> 我可以很明确地告诉你，plus和free是有区别的，在香港这个部分warp服务被ban的地方，晚高峰plus的速度是free的三倍以上，且非常稳定

如果你的机器上plus和free区别很大 那team表现如何呢

**Comment by fscarmen** [comment]
楼主最近研究出什么结论吗？我对这些少少的差异不敏感的。

**Comment by Fangliding** [comment]
> 楼主最近研究出什么结论吗？我对这些少少的差异不敏感的。

我最近测试了一下发现直接进 warp free和plus的回源节点略有不同(只有一点点不同) 但都是进本地cf节点回源 我在vps这边看日志 从来回源的访问ip ping过去延迟全是250+(欧洲鸡ping日本) 不知道是不是我开了develop模式的原因?不然如果那么看plus和free基本没差

**Comment by Fangliding** [comment]
还有一个小发现 就是那个reversed参数(有这个参数香港可以连接否则就像wgcf那样不行) 
附带了reversed参数的连接 无论重启多少次 对应的v4 v6 ip永远不会浮动 固定的 假如不带reversed参数 那随着重启出口ip会变 有的地方v4可能不会变但是v6会在1到2个/112之间浮动 如果带这玩意v6就是固定的那一个

**Comment by Fangliding** [comment]
还有一个小发现 就是那个reversed参数(有这个参数香港可以连接否则就像wgcf那样不行)
附带了reversed参数的连接 如果在同一个地区 无论重启多少次 对应的v4 v6 ip永远不会浮动 固定的 假如不带reversed参数 那随着重启出口ip会变 有的地方v4可能不会变但是v6会在1到2个/112之间浮动 如果带这玩意v6就是固定的那一个

**Comment by fscarmen** [comment]
> 附带了reversed参数的连接 如果在同一个地区 无论重启多少次 对应的v4 v6 ip永远不会浮动 固定的 假如不带reversed参数 那随着重启出口ip会变 有的地方v4可能不会变但是v6会在1到2个/112之间浮动 如果带这玩意v6就是固定的那一个

是的，你这么说我更清楚了。我在做关于刷 ip 解锁奈飞这里时。发现使用 wgcf 刷的时候，关了重启服务，IP就会变化了。而 Client / warp-go 不行，怎么重启服务 IP永远不会变化的，一定要注销了原来的账户，再重新注册才行，原来就是这个 reversed参数的问题，的确是这样，谢谢你的分享。

>我最近测试了一下发现直接进 warp free和plus的回源节点略有不同

这个是用 traceroute 来看的？

**Comment by fscarmen** [comment]
今天 wgcf 官方升级版本为 V2.2.16（2023-04-08），距离上个版本V2.2.16（2022-06-03)近一年了，看了下好像只修了一些bug，但没有使用 reversed 参数，香港的vps仍然不能使用。

**Comment by fscarmen** [comment]
nodeseek 有贴子有相关的数据作说明，[WARP、WARP+速度对比，以及WARP速度上限](https://www.nodeseek.com/post-9449-1) ，我把结论整理如下：

| 机器 | Hetzner德国 | | Hetnzer美西 |
| ----- | ----- | ----- |----- |
| 原生 IPv4 网络接口(Mbps) 上传 | 1505.17 |  | 1125.90 |
| WARP free IPv4(Mbps)  上传 | 751.82 | | 677.07 |
| WARP Plus IPv4(Mbps) 上传 | 760.94 | | 589.30 |
| | | | |
| 原生 IPv4 网络接口(Mbps) 下载 | 4980.52 | | 4179.68 |
| WARP free IPv4(Mbps)  下载 | 767.41 | | 1007.74 | 
| WARP plus IPv4(Mbps) 下载 | 815.90 | | 794.03 |
