### ISSUE TITLE
EUSERV Ubuntu20.04 系统安装失败

### ISSUE THREAD

**Issue by trackcn** [fscarmen/warp#29]
进度  2/3： 安装 WGCF 
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2021-11-23 17:41:37--  https://github.com/ViRb3/wgcf/releases/download/v2.2.9/wgcf_2.2.9_linux_amd64
Resolving github.com (github.com)... failed: No address associated with hostname.
wget: unable to resolve host address ‘github.com’
 WARP 注册中……

**Comment by fscarmen** [comment]
处理了，你先 
```
bash menu.sh u
```
 再 安装

**Comment by trackcn** [comment]
已经可以，感谢
