### ISSUE TITLE
[Bug]: New method to unlock chatgpt is slowing downloading speed

### ISSUE THREAD

**Issue by firefoxOnFire** [fscarmen/warp#290]
### Expectation / 预期情况

My change should not decrease the speed.

### Actual Situation / 实际情况

new method to [unlock chat gpt](https://github.com/fscarmen/warp#%E9%80%9A%E8%BF%87-warp-%E8%A7%A3%E9%94%81-chatgpt-%E7%9A%84%E6%96%B9%E6%B3%95) is slowing down the downloading as well as streaming services.

### Reproduction Method / 复现方法

make some change to access some streaming site or downloading site. It is slowed down by almost half. Ping is also incresed 4 times. I have tested many times. 

But when i use `warp o` to get warp ip. My speed is unchanged or even improved.

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
What is the method you using?

**Comment by firefoxOnFire** [comment]
> What is the method you using?

inbounds vmess
outbound wireguard

instead of only giving access to only specified sites. I used all tcp,udp

**Comment by fscarmen** [comment]
> > What is the method you using?
> 
> inbounds vmess outbound wireguard
> 
> instead of only giving access to only specified sites. I used all tcp,udp

I have never use warp for all sites. Warp is a reducer and must not be as fast as the native network. So you should use it minimally.

**Comment by fscarmen** [comment]
> > > What is the method you using?
> > 
> > 
> > inbounds vmess outbound wireguard
> > instead of only giving access to only specified sites. I used all tcp,udp
> 
> I have never used warp for all sites. Warp is a reducer and must not be as fast as the native network. So you should use it minimally.

**Comment by firefoxOnFire** [comment]
Brother do you have any idea where to use interface in outbound. I know about sendThrough but it can only have one ip either ipv6 or ipv4.

like he said [how](https://github.com/XTLS/Xray-core/issues/1735#issuecomment-1457670368)

**Comment by fscarmen** [comment]
> Brother do you have any idea where to use interface in outbound. I know about sendThrough but it can only have one ip either ipv6 or ipv4.
> 
> like he said [how](https://github.com/XTLS/Xray-core/issues/1735#issuecomment-1457670368)

warp-go with non-global mode is satisfied you.

**Comment by firefoxOnFire** [comment]
> > Brother do you have any idea where to use interface in outbound. I know about sendThrough but it can only have one ip either ipv6 or ipv4.
> > like he said [how](https://github.com/XTLS/Xray-core/issues/1735#issuecomment-1457670368)
> 
> warp-go with non-global mode is satisfied you.

I don't know how to set that. Can you send me example command??

**Comment by fscarmen** [comment]
> But when i use wg-quick or your script `warp o` then it is not slowing down speed.

It must be more efficient to handle it from the system level than to chain proxy from xray.

**Comment by firefoxOnFire** [comment]
> > But when i use wg-quick or your script `warp o` then it is not slowing down speed.
> 
> It must be more efficient to handle it from the system level than to chain proxy from xray.

yeah I dropped the idea about that. Can you point me to warp-go commands??

**Comment by fscarmen** [comment]
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
```

**Comment by firefoxOnFire** [comment]
> ```
> wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
> ```

Thanks awesome. Can we have non-global version using `wg-quick` ?

**Comment by firefoxOnFire** [comment]
> ```
> wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
> ```

I just tested. But non-global can't have both ipv4 and ipv6 at the same time. Actually my vps has already both address.

**Comment by fscarmen** [comment]
OK , try menu.sh warp client mode, menu  choose 5
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh 
```

**Comment by firefoxOnFire** [comment]
> 

yeah. but warp-go nonglobal giving one ip only is intentional???
i found `#AllowedIPs = 0.0.0.0/0,::/0` commented.

**Comment by fscarmen** [comment]
> found `#AllowedIPs = 0.0.0.0/0,::/0` commented.

#AllowedIPs = 0.0.0.0/0,::/0  non-global
AllowedIPs = 0.0.0.0/0,::/0 global

**Comment by firefoxOnFire** [comment]
> > found `#AllowedIPs = 0.0.0.0/0,::/0` commented.
> 
> #AllowedIPs = 0.0.0.0/0,::/0 non-global AllowedIPs = 0.0.0.0/0,::/0 global

So there is no way to get dual stack non-global?? Thanks for your script.

**Comment by firefoxOnFire** [comment]
I found out that using dns in config is actually slowing down my wireguard chain proxy. I was using dns over https.
Should i open this issue in xray itself??

Or can you reproduce this issue and raise in the main repo??

**Comment by fscarmen** [comment]
I am sorry to say that I have done little research on these. As far as I know, Xray hasn't made targeted optimizations to wireguard yet. So expect the xray team to follow up with an upgrade to this piece for faster wireguard speeds.
