### ISSUE TITLE
[Bug]: 刷ip时提示成功，但是检测仍然是original only

### ISSUE THREAD

**Issue by hsd815** [fscarmen/warp#291]
### Expectation / 预期情况

刷ip提示成功，应该netflix全解锁

### Actual Situation / 实际情况

实际没有解锁

### Reproduction Method / 复现方法

HK vps一键脚本wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
warp+账户
选择刷ip后提示成功

### Log / 日志信息

 脚本版本: 1.1.1
 功能新增: 1. 支持 warp-go v1.0.8 , 允许在配置文件 /opt/warp-go/warp.conf 自定义 MTU 值; 2. Singbox 配置导出 reseved 使用三个数字的数组代替字符串
 系统信息:
         当前操作系统: Ubuntu 22.04.1 LTS
         内核: 5.15.0-46-generic
         处理器架构: amd64v3
         虚拟化: kvm
         IPv4: 104.28.******  香港  Cloudflare
         IPv6: 2a09:*****香港  Cloudflare
         WARP plus 网络接口已开启
         运行在 全局 模式
         设备名: 'warp-go'       剩余流量:

======================================================================================================================

 1. WARP 全局 双栈 转为 WARP 全局 IPv4 (warp-go 4)
 2. WARP 全局 双栈 转为 WARP 全局 IPv6 (warp-go 6)
 3. 转为 WARP 非全局 网络接口 (warp-go g)
 4. 关闭 warp-go (warp-go o)
 5. 更换为 Free，WARP+ 或 Teams 账户 (warp-go a)
 6. 更换支持 Netflix 的 IP (warp-go i)
 7. 输出 wireguard 和 sing-box 配置文件 (warp-go e)
 8. 卸载 WARP 网络接口和 warp-go (warp-go u)
 9. 同步最新版本 (warp-go v)
 0. 退出脚本

 请选择: 6

 1. 刷 WARP IPv4 (默认)
 2. 刷 WARP IPv6

 请选择: 2
 当前 Netflix 地区是:HK，需要解锁当前地区请按 y , 如需其他地址请输入两位地区简写 (如 hk ,sg，默认:HK):
 2023-03-11 08:10:22 区域 HK 解锁成功，IPv6: 2a09:bac1:******* 香港 Cloudflare，1 小时后重新测 试，刷 IP 运行时长: 0 天 0 时 0 分 10 秒

 1. 刷 WARP IPv4 (默认)
 2. 刷 WARP IPv6
======================================================================================================================
 请选择: 1
 当前 Netflix 地区是:HK，需要解锁当前地区请按 y , 如需其他地址请输入两位地区简写 (如 hk ,sg，默认:HK):
 2023-03-11 08:18:52 区域 HK 解锁成功，IPv4: 104.28...... 香港 Cloudflare，1 小时后重新测试，刷 IP 运行时长: 0 天 0 时 0 分 5 秒

用检测脚本测试没有解锁，实际确实也没有解锁
IPv4和v6都是这种情况
======================================================================================================================
 ** 您的网络为: Cloudflare (:::*:*)
============[ Multination ]============
 Dazn:                                  Failed (Network Connection)
 HotStar:                               No
 Disney+:                               Yes (Region: HK)
 Netflix:                               Originals Only
 YouTube Premium:                       Yes (Region: HK)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
暂时没有时间研究具体问题出在哪里

**Comment by fscarmen** [comment]
奈飞解锁之前因为上游的 lmc999 从2023年3月4日调整了脚本，多加了个检测源，Netflix Detection:使用多个片源以支持更多地区 Pakistan等，https://github.com/lmc999/RegionRestrictionCheck/commit/449b778c49633db25a362e571239335948354345

使本脚本奈飞解锁部分失效，现在已经修正，需要重新安装，感谢大家的支持。
