### ISSUE TITLE
[help wanted 求助]: 谷歌人机验证

### ISSUE THREAD

**Issue by eve2ptp** [fscarmen/warp#292]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

custom-endpoint 设置 162.159.193.10 后打开谷歌会遇到人机验证。
不管是 free 或者 plus 账户，192、195 网段都遇到过。

### Log / 日志信息

.

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是全局的吗？看看分流有没有错，如果都没有问题，的确是 warp 的问题的话，我也没有办法了。

**Comment by eve2ptp** [comment]
> 是全局的吗？看看分流有没有错，如果都没有问题，的确是 warp 的问题的话，我也没有办法了。

wireproxy+ProxyOmega全局测的，这边无论怎么连都是SJC机房。

**Comment by fscarmen** [comment]
如果连了 warp 仍然有人机，那也没有办法了。

**Comment by fscarmen** [comment]
>  https://www.google.com/sorry/index

长见识了，原来google能在这个页面看访问的ip。另外人机能不能过？有办法或有相关的项目能判断的吗？
