### ISSUE TITLE
[help wanted 求助]: warp 使用疑惑

### ISSUE THREAD

**Issue by yfdoor** [fscarmen/warp#293]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

首先很抱歉在这里提出这个问题，因为实在在网络上没有找到解答：

我在甲骨文的云主机 B (only IP V4)上安装了一键脚本，生成了 warp IP: Warp-B-V4 和 Warp-B-V6. 另外在甲骨文的云主机 A 上装有探针程序来监控 B 的状态，这是前提，那么有几个疑惑需要请教一下：

1、为何我在 ping.pe 上 ping 不通  Warp-B-V4 这个 IP, 却能 ping 通 Warp-B-V6 这个 IP？如果这两个 IP 都是 warp 分配的内网IP，不是都应该 ping 不通?
2、B 上的一些 docker 程序端口无法打开了，看 issue 中有人提过，所以这个暂时无解是吗？
3、B 安装 warp 前， A 上显示的 B 丢包率为 50%  以上， 安装 warp 后， A 显示的丢包率为 0， 可是本地实际 ssh 连接 B 时，还是很慢。这是为什么呢？ 
3、我将 B 中的 /etc/wireguard/wsgf.conf 这个文件直接下载到本地，不做任何修改然后导入到 wireguard 的客户端，居然可以直接翻墙，而且速度要比连接 B 上搭建的 V2ray 连接快很多？
4、conf 配置文件中的 EndPoint IP 是 CF 分配的 IP 吗？这个 IP 在 warp 面板中没有看到啊？
```
[Interface]
PrivateKey = ******bEztSf1HJcaYiQn6ekgtJ+bmBuwK7dzbGg=
Address = 172.16.0.3/32, 2606:4700:110:89aa:717c/128
DNS = 1.1.1.1, 8.8.8.8, 8.8.4.4, 2606:4700:4700::1111, 2001:4860:4860::8888, 2001:4860:4860::8844
MTU = 1420
PostUp = ip -4 rule add from 10.0.0.245 lookup main
PostDown = ip -4 rule delete from 10.0.0.245 lookup main

[Peer]
PublicKey = *******1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ***.***.193.10:2408
```
万望得到解惑，谢谢！

 

### Log / 日志信息

NA

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
很感谢你的支持

> 1、为何我在 ping.pe 上 ping 不通 Warp-B-V4 这个 IP, 却能 ping 通 Warp-B-V6 这个 IP？如果这两个 IP 都是 warp 分配的内网IP，不是都应该 ping 不通?

我理解是 Warp-B-V4 是内网 IP，但 Warp-B-V6 不是。因为我们如果升级为 teams 账户或者  warp+ 账户的时候，wgcf.conf 里的 Private key 和 Address-V6 要一一对应，唯一的，但 Address-V4 即始终不会变，是 172.16.0.3/32

> 2、B 上的一些 docker 程序端口无法打开了，看 issue 中有人提过，所以这个暂时无解是吗？

你有多个选择：

1. warp 全局模式下，docker 模式模式改为 host ，即在 docker build 时加上 --net=host 指定，因为不加上时，默认是bridge模式：使用 --net=bridge
2. 安装 client 的两个模式，这样就是非全局方案，其中 proxy 模式是本地建了一个 socks5 代理，而 warp 模式是本地建了一个 CloudflareWARP 的网络接口，你需要配合 v2ray / xray 的分流规则，把需要的流量分流过去，主页 readme.MD 里有
3. 安装 warp-go 的非全局模式，也需要与2一样分流 

> 3、B 安装 warp 前， A 上显示的 B 丢包率为 50% 以上， 安装 warp 后， A 显示的丢包率为 0， 可是本地实际 ssh 连接 B 时，还是很慢。这是为什么呢？

warp 不会影响你的 云主机 B (only IP V4) 的ssh入局的，他只会影响出局，所以本地慢的话，应该是与 warp 无关的，建议你查看本地的网络环境，并在相同的环境下再 ssh 测试，warp 的开关是 `warp o`

> 3、我将 B 中的 /etc/wireguard/wsgf.conf 这个文件直接下载到本地，不做任何修改然后导入到 wireguard 的客户端，居然可以直接翻墙，而且速度要比连接 B 上搭建的 V2ray 连接快很多？

是的，在你的情况下，原来是  你本地  -> 通过v2ray 连到 vps -> warp 出局，wireguard是 你 -> warp 出局了，如果你那里的网络能使用 warp，这个是好方案，但要注意一点，在wireguard里不好设置分流规则，意味着你可能是全局的，访问大陆网站会慢，部分服务受限。

> 4、conf 配置文件中的 EndPoint IP 是 CF 分配的 IP 吗？这个 IP 在 warp 面板中没有看到啊？

不是的，这个是官方指定的一些 IP 段，绝大多数情况下，我们不用理会那个 endponit。

**Comment by Harvey365** [comment]
感谢巨佬做出的贡献，遇到类似疑问，获得解答，谢谢！

**Comment by Harvey365** [comment]
感谢巨佬做出的贡献，遇到类似疑问，获得解答，谢谢！

**Comment by yfdoor** [comment]
非常感谢如此快速的答复。

关于探针变化的问题，我的理解是，原来是主机 B 检测后将网络ping值，丢包率数据发送到 A ，warp 后优化出站网络，所以 B 到脚本设置测试节点的丢包率数据变好，发送给A 后，然后就在A上显示出来了较好的连接信息。

下面这是一个wg 配置的说明:

> [Interface]
> // 一个用于加密和身份验证的私钥，必须是 256 位长的随机字符串
> PrivateKey = <private_key>
> //定义了VPN接口的IP地址，可以是单个IP地址，也可以是CIDR块
> Address = <interface_address>
>// 定义了该VPN接口应使用的DNS服务器地址
> DNS = <dns_address>
> //定义了最大传输单元（MTU）的大小，即单个数据包可以传输的最大数据量
> MTU = <mtu_size>
> //定义了VPN接口所使用的路由表的编号，允许在同一主机上运行多个VPN连接
> Table = <routing_table>
> 
> //该部分定义了与之通信的远程对等体（peer）的参数
> [Peer]
> //远程对等体的公钥，必须与远程对等体的私钥匹配
> PublicKey = <public_key>
> //定义了远程对等体可以路由到的IP地址范围
> AllowedIPs = <allowed_ips>
>// 定义了远程对等体的IP地址和端口号，通常是对等体的公共IP地址和WireGuard服务监听的端口
> Endpoint = <endpoint_address>
> //定义了发送持久性保持活动包的时间间隔，以确保VPN连接保持活动状态，可选的
> PersistentKeepalive = <keepalive_interval>

可见 interface 是定义本机的服务端信息的，所以虽然直接拿过来用也可以，但是其实在这个局域网中，把本地 PC 和 主机 B 作为一台机器存在于整个warp 局域网中了吧？
peer 中定义应该就是warp 分配给你的这个网络中的节点 cf 的主机信息 ，Endpoint就是他的 IP? 就是由于这个节点的存在，才优化了我们的出站数据，因为数据都是通过 这个 Endpoint 节点中转后的？

不知道我的理解对不对！

**Comment by fscarmen** [comment]
> 可见 interface 是定义本机的服务端信息的

是的，这个信息能多台机器共用的

> 把本地 PC 和 主机 B 作为一台机器存在于整个warp 局域网中了吧

我不太理解你说的存在于整个warp局域网中的意思，反正是两台甚至多台用同一 [Interface] 信息是可以，至于各台机器之间有没有互通我想是没有了


> Endpoint就是他的 IP

是的，数据先到 endpoint，通过他代理再出去的。
