### ISSUE TITLE
[help wanted 求助]: 3/14 的更新，需要做什么特别的操作吗？

### ISSUE THREAD

**Issue by jackiehj** [fscarmen/warp#294]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

3.14 的更新，寻找最快的endpoint工具，除了更新脚本，还需要做什么操作吗？

### Log / 日志信息

脚本版本: 1.1.2
 功能新增: 为了加速 WARP，自动寻找最适合本机使用的 endpoint，感谢匿名的热心网友提供工具
 系统信息:
         当前操作系统: Debian GNU/Linux 10 (buster)
         内核: 4.19.0-5-amd64
         处理器架构: amd64
         虚拟化: kvm 
         IPv4: 104.28.215.*  香港  Cloudflare 
         IPv6:      
         WARP free 网络接口已开启 
         运行在 全局 模式 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
需要重新安装了：）

**Comment by jackiehj** [comment]
> 需要重新安装了：）

好的 我去试试～ 哈哈

**Comment by jackiehj** [comment]
变化是什么？还是我怎么验证它工作了？

**Comment by fscarmen** [comment]
从几千个ip+端口里找最佳的

**Comment by fscarmen** [comment]
我看作者的原理是 用ping 等网络工具，逐一查各个endpoint IP，每个 IP 同时又查若干个端口，出来的结果是

| IP:PORT |  LOSS  | DELAY |
|--|--|--|
| 162.159.192.51:7152|  0.00% | 136 ms
|162.159.192.36:928|  0.00% |  141 ms |
|162.159.195.114:928|  0.00% |  144 ms |
|162.159.192.35:928|  0.00% |  145 ms |
|162.159.195.234:7152|  0.00% |  146 ms |
|162.159.192.198:928|  0.00% |  146 ms |
|162.159.192.163:928|  0.00% |  147 ms |
|162.159.192.75:7152|  0.00% |  149 ms |
|162.159.192.162:928|  0.00% |  153 ms |
|162.159.195.182:928|  0.00% |  155 ms |
|162.159.192.91:928|  0.00% |  163 ms |
|162.159.195.139:7152|  0.00% |  166 ms |
|162.159.195.0:7152|  10.00% |  222 ms |
|162.159.192.117:7152|  10.00% |  222 ms |
|162.159.192.117:928|  10.00% |  223 ms |
|162.159.192.202:7152|  10.00% |  223 ms |
|162.159.192.167:928|  10.00% |  224 ms |
|162.159.195.15:7152|  10.00% |  224 ms |
