### ISSUE TITLE
[help wanted 求助]: endpoint detect exe file detect as trojan

### ISSUE THREAD

**Issue by kontorol** [fscarmen/warp#295]
### Script / 脚本

menu.sh

### OS / 操作系统

Windows

### Actual Situation / 实际情况

https://www.virustotal.com/gui/file/8abdb9afa0ef9afcdb755b8523aa2b6075a155092afd29f30a6a9057105a76ad/details

### Log / 日志信息

5 security vendors and no sandboxes flagged this file as malicious

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
We use the Linux release and it 's all ok.
warp-linux-arm64: https://www.virustotal.com/gui/file/eb06fa17222587e9c52ed6bda20e3265677b167c85829d7f1936826ac924b537

warp-linux-amd64: https://www.virustotal.com/gui/file/828110e59f5e2475236585f3b6a29435b3b049e05862a1234044848e4526e041

warp-linux-s390x: https://www.virustotal.com/gui/file/e3a6ed849412408a88f86307f0e49e550b75e0cc607005ba4e0dcad193fe0330
