### ISSUE TITLE
[Bug]: oracle linux 8.7

### ISSUE THREAD

**Issue by testermania** [fscarmen/warp#297]
### Expectation / 预期情况

service does not start

### Actual Situation / 实际情况

service does not start

### Reproduction Method / 复现方法

sudo warp-go o

### Log / 日志信息

Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xe" for details.
 Try 5
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xe" for details.

### More information / 额外信息

oracle linux 8.7 arm

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by testermania** [comment]
I try 

sudo systemctl daemon-reload 
nothing change. no root warning

systemctl daemon-reload 
asking root user pass

**Comment by fscarmen** [comment]
try reboot your vps

**Comment by testermania** [comment]
warp-go o

Try 5
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xe" for details.
 Failed more than 5 times, script aborted. Feedback: [https://github.com/fscarmen/warp/issues]

**Comment by testermania** [comment]
looks like selinux issue.

```
type=PROCTITLE msg=audit(03/17/2023 13:06:15.701:412) : proctitle=(warp-go)
type=SYSCALL msg=audit(03/17/2023 13:06:15.701:412) : arch=aarch64 syscall=execve success=no exit=EACCES(Permission denied) a0=0xaaaab9455c80 a1=0xaaaab9455ad0 a2=0xaaaab92d0f60 a3=0xaaaab9505a00 items=0 ppid=1 pid=7570 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=(warp-go) exe=/usr/lib/systemd/systemd subj=system_u:system_r:init_t:s0 key=(null)
type=AVC msg=audit(03/17/2023 13:06:15.701:412) : avc:  denied  { execute } for  pid=7570 comm=(warp-go) name=warp-go dev="dm-0" ino=67456173 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=0
```

**Comment by fscarmen** [comment]
> looks like selinux issue.
> 
> `ausearch -ts recent -m avc -i`
> 
> ```
> type=PROCTITLE msg=audit(03/17/2023 13:06:15.701:412) : proctitle=(warp-go)
> type=SYSCALL msg=audit(03/17/2023 13:06:15.701:412) : arch=aarch64 syscall=execve success=no exit=EACCES(Permission denied) a0=0xaaaab9455c80 a1=0xaaaab9455ad0 a2=0xaaaab92d0f60 a3=0xaaaab9505a00 items=0 ppid=1 pid=7570 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=(warp-go) exe=/usr/lib/systemd/systemd subj=system_u:system_r:init_t:s0 key=(null)
> type=AVC msg=audit(03/17/2023 13:06:15.701:412) : avc:  denied  { execute } for  pid=7570 comm=(warp-go) name=warp-go dev="dm-0" ino=67456173 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=0
> ```
> 
> FIXED https://unix.stackexchange.com/a/665036
> 
> `cd opt`
> 
> ` sudo mv warp-go /usr/local/bin`
> 
> `restorecon -Rv /usr/local/bin`
> 
> `sudo nano /usr/lib/systemd/system/warp-go.service`
> 
> CHANGE lines
> 
> ```
> WorkingDirectory=/usr/local/bin/warp-go/
> ExecStart=/usr/local/bin/warp-go/warp-go --config=/usr/local/bin/warp-go/warp.conf
> ```
> 
> reboot
> 
> but service does not start automatically after reboot
> 
> `sudo systemctl start warp-go`

try `sudo systemctl enable --now warp-go`

**Comment by testermania** [comment]
Failed to resolve hostname domain: System error
after the warp-go install.
