### ISSUE TITLE
[Bug]: 生成的wgcf.conf没有添加ipv6的路由表，已经找到解决方案

### ISSUE THREAD

**Issue by CoCoThink** [fscarmen/warp#299]
### Expectation / 预期情况

应该正常添加ipv6的路由表

### Actual Situation / 实际情况

现有的wgcf.conf中，最后路由表的添加命令为：
PostUp = ip -4 rule add from xxxxx lookup main;ip -6 rule add from xxxxxxx lookup main
PostDown = ip -4 rule delete from xxxxxxx lookup main; ip -6 rule delete from xxxxxx lookup main

经测试第二条添加ipv6的路由表的命令没有正常执行，导致机器的ipv6不通
经实验发现，下面的命令可以正常运行
PostUp = ip -4 rule add from xxxxx lookup main
PostUp = ip -6 rule add from xxxxxxx lookup main
PostDown = ip -4 rule delete from xxxxxxx lookup main
PostDown = ip -6 rule delete from xxxxxx lookup main

### Reproduction Method / 复现方法

按照上述描述修改wgcf.conf即可复现

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
现在脚本是分开的哦
<img width="890" alt="image" src="https://user-images.githubusercontent.com/62703343/226103278-a02bfb3a-1d02-476a-82ae-e3e474860c69.png">
