### ISSUE TITLE
readme介绍的关闭自启命令无效-【结论：以前版本为了保证重启后一定获取网络成功，在定时任务里做了处理。现在没有这样做，删掉就好了】

### ISSUE THREAD

**Issue by ben-august** [fscarmen/warp#30]
系统centos7
使用systemctl disable wg-quick@wgcf命令关闭自启动。但是系统重启后warp已经自动获取了 cloudflare ip。貌似这个命令没生效？

**Comment by fscarmen** [comment]
感谢你的反馈，更新一下指令 ```systemctl disable --now wg-quick@wgcf```
以下是我在EUserv CentOS7 上测试的结果:
1.安装 WARP 成功，已经检测到 WARP IP
2.检查  wg-quick@wgcf 为 enabled
3.运行 ```systemctl disable --now wg-quick@wgcf```
4.重启
5.重新登陆后再检查，没有启动WARP了

```
==============================================================

 IPv4：8.20.127.18 ( WARP IPv4 ) 德国 CLOUDFLARENET 
 IPv6：2a09:bac0:203::814:7f12 ( WARP IPv6 ) 德国 CLOUDFLARENET 
 恭喜！WARP 已开启，总耗时:68秒 
 IPv4 优先 

==============================================================

 再次运行用 warp [option] [lisence]，如
 
 warp h (帮助菜单）
 ...

[root@srv17333 ~]# hostnamectl | grep -i opera
  Operating System: CentOS Linux 7 (Core)
[root@srv17333 ~]# systemctl is-enabled wg-quick@wgcf
enabled
[root@srv17333 ~]# systemctl disable --now wg-quick@wgcf
Removed symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wgcf.service.
[root@srv17333 ~]# reboot

连接断开
连接成功
Last login: Sat Nov 27 04:04:55 2021 from 2a09:bac0:23::815:bcb
************************************************************
* CentOS7.6-64bit-minimal                
************************************************************
...

[root@srv17333 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
698: eth0@if699: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:84:ed:84:68:d4 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 2a02:180:6:1::2e40/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::284:edff:fe84:68d4/64 scope link 
       valid_lft forever preferred_lft forever
[root@srv17333 ~]# systemctl is-enabled wg-quick@wgcf
disabled
[root@srv17333 ~]# systemctl is-active wg-quick@wgcf
unknown
[root@srv17333 ~]# 
```

**Comment by ben-august** [comment]
没用，还是自启动获取warp ip了

**Comment by fscarmen** [comment]
依次运行 ```wg-quick down wgcf```
```systemctl stop wg-quick@wgcf```
```systemctl disable --now wg-quick@wgcf```
```ip a```
确定 WARP 没有运行后重启 ```reboot```，重新ssh后
```ip a```
```systemctl is-enabled wg-quick@wgcf```
```systemctl is-active wg-quick@wgcf```

**Comment by ben-august** [comment]
按照你的命令完整运行了一遍，依旧一样。warp也自动获取ip了。
![image](https://user-images.githubusercontent.com/36500518/143667140-4d422b9d-7860-465c-9f43-882cd2bb3cab.png)

**Comment by ben-august** [comment]
wg-quick down wgcf关闭后，wg-quick@wgcf一直显示active。

**Comment by fscarmen** [comment]
再看看定时任务处
```crontab -l```
```cat /etc/crontab```

**Comment by ben-august** [comment]
![image](https://user-images.githubusercontent.com/36500518/143667252-c650e218-7de2-471a-8082-6ca2ad7f9aeb.png)

**Comment by ben-august** [comment]
![image](https://user-images.githubusercontent.com/36500518/143667306-e5154db8-9ec8-4529-bcde-2b69078bf519.png)
我wiregurad目录下并没有autoup.sh脚本（开启显示隐藏文件功能了）。

**Comment by fscarmen** [comment]
哈哈，你应该是安装得很早版本了，现在没有把warp放在 crontab里了。你这样可以了 
```sed -i "/@reboot root.*/d" /etc/crontab; cat /etc/crontab; rm -f /etc/wireguard/WARP_AutoUp.sh```
应该没有了最下的两行 
@reboot root bash /etc/wireguard/WARP_AutoUp.sh
@reboot root warp n
之后再运行 ```systemctl disable --now wg-quick@wgcf; reboot``` 这样应该可以了

**Comment by ben-august** [comment]
搞定多谢。我经常warp v，意思是这不会覆盖之前的设置？
另外能不能增加个warp i 这种命令 方便查看获取的ip地址已经当前是否开启warp功能。

**Comment by fscarmen** [comment]
> 搞定多谢。我经常warp v，意思是这不会覆盖之前的设置？
感谢你的支持。那个处理方法是今年10月初之前的了。后面安装的脚本没有删除这些之前在定时任务里的计划。
事实上，除了新增功能和改bug修车外。我几乎每天都在优化代码以让运行速度更快。相信你用 ```warp o```会感觉出来了

> 另外能不能增加个warp i 这种命令 方便查看获取的ip地址已经当前是否开启warp功能。
有多种方法可以看：
1.```warp```进菜单看
2.```wg```看看有没有信息，如有即开启，如没有任何信息即没有开启
3.```curl -s4m8 ip.gs``` 或者 ```curl -s6m8 ip.gs``` 查当前的IP地址
4. ````warp o```拨号，如果已经连上，将不会变IP，如果之前是断开状态的，会连上warp，这时再显示IP
5. ```warp n```。与第4点差不多，具体差异你试试就知道了，打字说不清楚

**Comment by ben-august** [comment]
多谢大佬 辛苦。（有telegram群组不？）

**Comment by fscarmen** [comment]
不敢建群组啊，怕天天大家把车放过来修啊。
你可以加我 https://t.me/fscarmen2
估计会有一些相同的群的
