### ISSUE TITLE
[Feature request]: 建议添加非全局路由接口

### ISSUE THREAD

**Issue by EluneAdore1** [fscarmen/warp#300]
### Related Problem / 相关问题

XRAY的支持以接口名称为出口的方式添加outbound，如下 https://github.com/XTLS/Xray-core/pull/1494，
鉴于现在xray的wireguard性能比较烂，如果使用非全局路由接口，则可以在XRAY的outbound中直接使用wgcf的接口名称指定。

这样即享受了wgcf带来的极致性能，又不影响VPS本身的默认路由。

### Describe the solution you want / 描述你希望的解决方案

如p3terx的一键脚本，bash <(curl -fsSL git.io/warp.sh) wgx

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
有很多替代方案，所以我没有给这个选项了，你可以用 wireproxy / client 的 proxy 模式给本地建个 scoks5 代理，又或者用 client 的 warp 模式给本地弄个 CloudflareWARP 的网络接口，都可以用于xray分流

效果: wireproxy = client warp 模式 > client proxy 模式

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/62703343/226167089-fd3ed2cb-2757-4a30-b569-295489465718.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/62703343/226166915-62c99f59-718f-4682-9e36-05bd677f7d58.png">

**Comment by fscarmen** [comment]
你还可以使用 warp-go  的非全局模式，还有 wgcf  的 dnsmasq + ipset 等等方案，适合多种使用场景~

**Comment by EluneAdore1** [comment]
谢谢大佬，我明白了

**Comment by fscarmen** [comment]
有这么丰富的方案，完全能取代 p3terx 的那个方案了，如果我也加上，项目变得太复杂，选项太多了。你想要的处理了吗？

**Comment by EluneAdore1** [comment]
> 有这么丰富的方案，完全能取代 p3terx 的那个方案了，如果我也加上，项目变得太复杂，选项太多了。你想要的处理了吗？

处理好了，我本地用你的脚本，装好后down了wg接口，结合p3terx的路由表项稍微修改了下路由表，让系统路由优先级更高就可以了。

我之所以想这么做主要是，wireproxy和warp-go的性能和wireguard性能上确实低一些，其实都够用，完全是心理作用。

晚点有空了我再把xray的outbound改成以指定出接口的方式走warp，简化xray的配置

**Comment by fscarmen** [comment]
看了一下 p3 大神，他把以下这个写在配置文件了
```
Table = off
PostUP = ip -4 route add default dev wgcf table 51888
PostUP = ip -4 rule add from 172.16.0.2 lookup 51888
PostDown = ip -4 rule delete from 172.16.0.2 lookup 51888
PostUP = ip -4 rule add fwmark 51888 lookup 51888
PostDown = ip -4 rule delete fwmark 51888 lookup 51888
PostUP = ip -4 rule add table main suppress_prefixlength 0
PostDown = ip -4 rule delete table main suppress_prefixlength 0
PostUP = ip -6 route add default dev wgcf table 51888
PostUP = ip -6 rule add from 2606:4700:110:816c:f5cc:29f8:8b9a:601c lookup 51888
PostDown = ip -6 rule delete from 2606:4700:110:816c:f5cc:29f8:8b9a:601c lookup 51888
PostUP = ip -6 rule add fwmark 51888 lookup 51888
PostDown = ip -6 rule delete fwmark 51888 lookup 51888
PostUP = ip -6 rule add table main suppress_prefixlength 0
PostDown = ip -6 rule delete table main suppress_prefixlength 0
```

**Comment by yowynn** [comment]
> 你还可以使用 warp-go 的非全局模式，还有 wgcf 的 dnsmasq + ipset 等等方案，适合多种使用场景~

warp-go 的非全局模式,之后怎么在xray配置特定网站走warp的出口呢

**Comment by fscarmen** [comment]
> warp-go 的非全局模式,之后怎么在xray配置特定网站走warp的出口呢

https://github.com/fscarmen/warp/blob/main/README.md#netflixgoogle-%E5%88%86%E6%B5%81%E5%88%B0-client-warp-%E7%BD%91%E7%BB%9C%E6%8E%A5%E5%8F%A3%E7%9A%84%E6%96%B9%E6%B3%95

**Comment by opticalix** [comment]
> > warp-go 的非全局模式,之后怎么在xray配置特定网站走warp的出口呢
> 
> https://github.com/fscarmen/warp/blob/main/README.md#netflixgoogle-%E5%88%86%E6%B5%81%E5%88%B0-client-warp-%E7%BD%91%E7%BB%9C%E6%8E%A5%E5%8F%A3%E7%9A%84%E6%96%B9%E6%B3%95

使用该方法无效（dns没配，其他照抄）。不知道是不是warp没成功，请问要如何检查warp代理模式是否成功？

```
1. WARP 全局 IPv6 转为 WARP 全局 IPv4 (warp-go 4) 
 2. WARP 全局 IPv6 转为 WARP 全局 双栈 (warp-go d) 
 3. 转为 WARP 非全局 网络接口 (warp-go g) 
 4. 关闭 warp-go (warp-go o) 
 5. 更换为 Free，WARP+ 或 Teams 账户 (warp-go a) 
 6. 更换支持 Netflix 的 IP (warp-go i) 
 7. 输出 wireguard 和 sing-box 配置文件 (warp-go e) 
 8. 卸载 WARP 网络接口和 warp-go (warp-go u) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 3
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 已成功获取 WARP free 网络
 运行在 非全局 模式 
 IPv4:    
 IPv6:     

```

**Comment by fscarmen** [comment]
你的系统太旧啊，不清楚有没有影响，Ubuntu 16.04 + linux 3.13，能不能升级一下。

**Comment by fscarmen** [comment]
> 我的环境：
> 
> ```
> 
> 脚本版本: 1.1.2
> 
>  功能新增: 为了加速 WARP，自动寻找最适合本机使用的 endpoint，感谢匿名的热心网友提供工具
> 
>  系统信息:
> 
>          当前操作系统: Ubuntu 16.04.7 LTS
> 
>          内核: 3.13.0-43-generic
> 
>          处理器架构: amd64v3
> ```

你的vps是哪个地区的？

**Comment by opticalix** [comment]
> > 我的环境：
> > ```
> > 
> > 脚本版本: 1.1.2
> > 
> >  功能新增: 为了加速 WARP，自动寻找最适合本机使用的 endpoint，感谢匿名的热心网友提供工具
> > 
> >  系统信息:
> > 
> >          当前操作系统: Ubuntu 16.04.7 LTS
> > 
> >          内核: 3.13.0-43-generic
> > 
> >          处理器架构: amd64v3
> > ```
> 
> 你的vps是哪个地区的？

DO，印度的吧，不过经常显示在圣何塞

**Comment by opticalix** [comment]
> > 我的环境：
> > ```
> > 
> > 脚本版本: 1.1.2
> > 
> >  功能新增: 为了加速 WARP，自动寻找最适合本机使用的 endpoint，感谢匿名的热心网友提供工具
> > 
> >  系统信息:
> > 
> >          当前操作系统: Ubuntu 16.04.7 LTS
> > 
> >          内核: 3.13.0-43-generic
> > 
> >          处理器架构: amd64v3
> > ```
> 
> 你的vps是哪个地区的？

记错了，在旧金山..。试了下用Ubuntu 22，还是不行。怀疑是xray配置有误
