### ISSUE TITLE
[help wanted 求助]: 成功获取到香港cloudflare的warp IP，仍然显示不能访问ChatGPT

### ISSUE THREAD

**Issue by enerai** [fscarmen/warp#302]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

是香港腾讯云的机器，能够获取到香港cloudflare的IP，但是依然不能访问ChatGPT，应该怎么办

### Log / 日志信息

<img width="478" alt="image" src="https://user-images.githubusercontent.com/3956794/226198342-7969586e-03f1-4b5d-8a53-f7a82556b79a.png">

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
OpenAI不允许中国大陆、香港、伊朗、俄罗斯和非洲部分地区的用户注册，即使用了 warp 也不行。

**Comment by enerai** [comment]
明白了。感谢

**Comment by iKira** [comment]
> OpenAI不允许中国大陆、香港、伊朗、俄罗斯和非洲部分地区的用户注册，即使用了 warp 也不行。

并不是，HK套了WARP还能连OpenAI。

**Comment by ceozero** [comment]
> > OpenAI不允许中国大陆、香港、伊朗、俄罗斯和非洲部分地区的用户注册，即使用了 warp 也不行。
> 
> 并不是，HK套了WARP还能连OpenAI。

你是怎么套的，，我刷了很久IP都刷不出非香港IP。。。解不了GPT

而且看你用的是warp的脚本而不是warp-go的脚本？ 香港不是只能用warp-go的么？

**Comment by enerai** [comment]
> > > OpenAI不允许中国大陆、香港、伊朗、俄罗斯和非洲部分地区的用户注册，即使用了 warp 也不行。
> > 
> > 
> > 并不是，HK套了WARP还能连OpenAI。
> 
> 你是怎么套的，，我刷了很久IP都刷不出非香港IP。。。解不了GPT
> 
> 而且看你用的是warp的脚本而不是warp-go的脚本？ 香港不是只能用warp-go的么？

hk warp了没用

**Comment by iKira** [comment]
> > > > OpenAI不允许中国大陆、香港、伊朗、俄罗斯和非洲部分地区的用户注册，即使用了 warp 也不行。
> > > 
> > > 
> > > 并不是，HK套了WARP还能连OpenAI。
> > 
> > 
> > 你是怎么套的，，我刷了很久IP都刷不出非香港IP。。。解不了GPT
> > 而且看你用的是warp的脚本而不是warp-go的脚本？ 香港不是只能用warp-go的么？
> 
> hk warp了没用

是因为你没设置reserved
