### ISSUE TITLE
[help wanted 求助]: 德国warp+无法获取ipv6

### ISSUE THREAD

**Issue by GreenTeodoro839** [fscarmen/warp#304]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

使用warp+无法获取ipv6，使用普通warp账户正常获取，使用同一个key，在美国能获取warp+ ipv6。如果有需要可以提供key

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
反复试都是如此吗？

**Comment by GreenTeodoro839** [comment]
> 反复试都是如此吗？

都是这样，warp-go能用

**Comment by fscarmen** [comment]
> > 反复试都是如此吗？
> 
> 能否给warp-go的非全局模式也添加ipv6？在流媒体解锁等方面可能有用

暂时不添加了，加了要处理很多东西，比如全局非全局的切换，ipv4 / ipv6 / 双栈 的切换，很费时间处理的。
