### ISSUE TITLE
[help wanted 求助]: wireproxy不支持udp

### ISSUE THREAD

**Issue by GreenTeodoro839** [fscarmen/warp#306]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

如果把wireproxy作为v2ray出站，使用udp的dns就会失效，不能访问网站

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你好，这已经超出我的能力范围了，你提到使用udp的dns就会失效，不能访问网站，建议你去 v2ray 和 wireproxy 官方那边了解一下，期待你把解决方案回头发一下。

**Comment by GreenTeodoro839** [comment]
> 你好，这已经超出我的能力范围了，你提到使用udp的dns就会失效，不能访问网站，建议你去 v2ray 和 wireproxy 官方那边了解一下，期待你把解决方案回头发一下。

wireproxy的udp支持从2022年10月开始，到上周才添加完成，而wireproxy的release是2022年9月的，应该没有udp支持

**Comment by fscarmen** [comment]
是的，2022/09/02 v1.0.5 之后就没有 release新版本了，你说的这个功能有什么用的？

https://github.com/fscarmen/warp/blob/main/wireproxy/version_history

**Comment by GreenTeodoro839** [comment]
> 是的，2022/09/02 v1.0.5 之后就没有 release新版本了，你说的这个功能有什么用的？
> 
> https://github.com/fscarmen/warp/blob/main/wireproxy/version_history

如果让wireproxy作为v2ray上游，因为不支持udp，就无法进行dns解析，只能访问ip，不能访问域名

**Comment by fscarmen** [comment]
现在我的使用是 wireproxy 建的 socks5 供 xray 分流使用，这样是正常使用，和你说的方案，有什么不同？

**Comment by GreenTeodoro839** [comment]
> 现在我的使用是 wireproxy 建的 socks5 供 xray 分流使用，这样是正常使用，和你说的方案，有什么不同？

我是直接让v2ray所有流量全部走warp，分流不知道为什么不大好使，但是机器同时还有别的用处，没开全局模式

**Comment by fscarmen** [comment]
这个与我使用不是一样吗？不过我用xray 不知道有没有影响，我是安装 wireproxy 之后，把奈飞和指定的网站流量分流过去，其他的走原生的网络接口。而你这个情况，都不用选指定的域名了，全部指定到 wireproxy 的 socks5 可以了。
但我还是不明白，我这样连，也没有你说的 udp 问题啊，访问奈飞和ip.sb，我在pc上都是用域名的。没有你说的：只能访问ip，不能访问域名。

**Comment by theoneLee** [comment]
@fscarmen 
可以分享一下您完整的config.json么？
敏感信息可以屏蔽掉。

**Comment by GreenTeodoro839** [comment]
> @fscarmen 可以分享一下您完整的config.json么？ 敏感信息可以屏蔽掉。

他应该是warp用来分流流媒体，其他流量还是原来的出口，在readme里有示例

**Comment by fscarmen** [comment]
> 可以分享一下您完整的config.json么？

如果是warp用来分流流媒体，readme.MD 里有示例啊，[Netflix 分流到 WARP Client Proxy、WireProxy 的方法](https://github.com/fscarmen/warp/blob/main/README.md#netflix-%E5%88%86%E6%B5%81%E5%88%B0-warp-client-proxywireproxy-%E7%9A%84%E6%96%B9%E6%B3%95)
