### ISSUE TITLE
[help wanted 求助]: warp 和 warp-go 这两个脚本可以共用吗？

### ISSUE THREAD

**Issue by yowynn** [fscarmen/warp#308]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

warp 和 warp-go 这两个脚本可以共用吗，warp搜不到ip，需要用warp-go才能搜到，然而warp-go要想用非全局模式，还需要使用 warp 脚本中的 client 安装，才能转而使用xray等工具设置特定网站走warp代理，是这样吗

### Log / 日志信息

暂无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
不用啊，warp-go的非全局模式，只要在 xray 里指定出口为 CloudflareWARP 的网络接口即可，你可以通过 ip a 来看
