### ISSUE TITLE
[help wanted 求助]: 美国  DediPath 无法获取 WARP IP

### ISSUE THREAD

**Issue by weiyideai520** [fscarmen/warp#309]
### Script / 脚本

menu.sh

### OS / 操作系统

Others

### Actual Situation / 实际情况

获取 WARP IP  失败

### Log / 日志信息

 所有依赖已存在，不需要额外安装

 检查环境中……
 本项目专为 VPS 添加 wgcf 网络接口，详细说明: [https://github.com/fscarmen/warp]
 脚本特点:
         • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
         • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
         • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
         • 支持硬件结构类型: AMD、 ARM 和 s390x
         • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
         • 智能判断 WGCF 作者 github库的最新版本 （Latest release）
         • 支持 WARP Linux Socks5 Client
         • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商

======================================================================================================================

 脚本版本:2.48
 功能新增:为了提速 WARP，自动寻找最适合本机使用的 endpoint，应用在 wgcf 和 client，感谢匿名的热心网友提供工具
 系统信息:
         当前操作系统:AlmaLinux 8.7 (Stone Smilodon)
         内核:4.18.0
         处理器架构:amd64
         虚拟化:openvz
         IPv4: xxxxx  美国  DediPath
         IPv6: xxxxx  美国  DediPath
         WARP 网络接口未开启
         Client 未安装
         WireProxy 未安装

======================================================================================================================

 1.  WARP IPv6 转为 WARP IPv4 (warp 4)
 2.  WARP IPv6 转为 WARP 双栈 (warp d)
 3.  变更 WARP 账户 (warp a)
 4.  打开 WARP (warp o)
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c)
 6.  更换支持 Netflix 的 IP (warp i)
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u)
 8.  刷 WARP+ 流量 (warp p)
 9.  升级内核、安装BBR、DD脚本 (warp b)
 10. 同步最新版本 (warp v)
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知)
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e)
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w)
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l)
 0.  退出脚本

 请选择: 4
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
试试 warp-go 
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
```

**Comment by weiyideai520** [comment]
> 试试 warp-go
> 
> ```
> wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
> ```

可以了，非常感谢~

**Comment by fscarmen** [comment]
很好，是哪个区的？

**Comment by weiyideai520** [comment]
> 很好，是哪个区的？

你是说我的VPS吗？我的VPS是 洛杉矶

**Comment by fscarmen** [comment]
那就是了，la和香港可用warp-go
