### ISSUE TITLE
更新wireguard-go选项？

### ISSUE THREAD

**Issue by 2ndMessiah** [fscarmen/warp#31]
请问大大

wireguard-go客户端需要时常更新吗？看见咱们脚本没有提供此选项。

谢谢

**Comment by fscarmen** [comment]
用户才是大大呢，很高兴你使用本脚本并提意见。
事实上我项目的wireguard-go版本是比较老了，version 0.0.20201118，
官网显示之后还有以下版本：
0.0.20211016、0.0.20210424、v0.0.20201121
我试图用最新的，发现像EUserv某些版本出现水土不服的现象，表现为 wg-quick up wgcf 之后卡死不动。必须ctrl+c中止才行。所以为了兼容性我保持旧版本。
当然你可以使用新版本试试，但记得保留旧那个先，确认新的可用再删掉的

**Comment by 2ndMessiah** [comment]
感谢回复 果然有所考虑 那我还是保持版本比较好 版本差距也不大

感谢作者的辛勤更新 ovz小鸡的拯救者

**Comment by fscarmen** [comment]
PS: WGCF 通过github接口，运行时会实时获取原作者最新的版本。获取不了再使用 CDN 获取我项目里的WGCF版本的，现在是v2.2.9
