### ISSUE TITLE
[help wanted 求助]: 访问所有网站都是warp的ip吗，是否能够隐藏vps本身的ip

### ISSUE THREAD

**Issue by dinaau** [fscarmen/warp#313]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

1. 包括网站加了cf跟网站没有cf加持的

如果我用一个warp 开启的vsp去访问那些网站，它们识别我as 访客的ip地址都是warp ip吗？

2. warp是否能够指定某个区域的ip 而不仅仅是国家，比如一个美国有 san jose, washington DC ?

以下是所有的节点 https://www.cloudflarestatus.com/

### Log / 日志信息

n/a

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [x] Yes / 是

**Comment by fscarmen** [comment]
>如果我用一个warp 开启的vsp去访问那些网站，它们识别我as 访客的ip地址都是warp ip吗？

你使用了全局模式的话，无论到哪个网站，都会显示 warp 的 IP的，现在包括你指的cf加持网站
```
ubuntu $ curl -s4 ip.gs
104.28.222.46

ubuntu $ curl -s4 https://1.1.1.1/cdn-cgi/trace
fl=35f473
h=1.1.1.1
ip=104.28.222.46
ts=1680056483.371
visit_scheme=https
uag=curl/7.68.0
colo=SIN
sliver=010-sin02
http=http/2
loc=SG
tls=TLSv1.3
sni=off
warp=on
gateway=off
rbi=off
kex=X25519

ubuntu $ curl -s4 https://www.cloudflare.com/cdn-cgi/trace
fl=35f473
h=www.cloudflare.com
ip=104.28.222.46
ts=1680056497.601
visit_scheme=https
uag=curl/7.68.0
colo=SIN
sliver=010-sin02
http=http/2
loc=SG
tls=TLSv1.3
sni=plaintext
warp=on
gateway=off
rbi=off
kex=X25519
```

>2. warp是否能够指定某个区域的ip 而不仅仅是国家，比如一个美国有 san jose, washington DC ?

暂时没有这样的技术

**Comment by fscarmen** [comment]
> > > 如果我用一个warp 开启的vsp去访问那些网站，它们识别我as 访客的ip地址都是warp ip吗？
> > 
> > 
> > 你使用了全局模式的话，无论到哪个网站，都会显示 warp 的 IP的，现在包括你指的cf加持网站
> > ```
> > ubuntu $ curl -s4 ip.gs
> > 104.28.222.46
> > 
> > ubuntu $ curl -s4 https://1.1.1.1/cdn-cgi/trace
> > fl=35f473
> > h=1.1.1.1
> > ip=104.28.222.46
> > ts=1680056483.371
> > visit_scheme=https
> > uag=curl/7.68.0
> > colo=SIN
> > sliver=010-sin02
> > http=http/2
> > loc=SG
> > tls=TLSv1.3
> > sni=off
> > warp=on
> > gateway=off
> > rbi=off
> > kex=X25519
> > 
> > ubuntu $ curl -s4 https://www.cloudflare.com/cdn-cgi/trace
> > fl=35f473
> > h=www.cloudflare.com
> > ip=104.28.222.46
> > ts=1680056497.601
> > visit_scheme=https
> > uag=curl/7.68.0
> > colo=SIN
> > sliver=010-sin02
> > http=http/2
> > loc=SG
> > tls=TLSv1.3
> > sni=plaintext
> > warp=on
> > gateway=off
> > rbi=off
> > kex=X25519
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 2. warp是否能够指定某个区域的ip 而不仅仅是国家，比如一个美国有 san jose, washington DC ?
> > 
> > 
> > 暂时没有这样的技术
> 
> 这里有个项目 可以指定co-location， 是否能够整合到warp里？
> 
> 指定地区名后，延迟测速后得到的结果就都是指定地区的 IP 了（也可以继续进行下载测速） 节点地区名为当地 机场三字码，指定多个时用英文逗号分隔
> 
> CloudflareST.exe -cfcolo HKG,KHH,NRT,LAX,SEA,SJC,FRA,MAD
> 
> 注意，该参数只有在 HTTPing 延迟测速模式下才可用（因为要访问网页来获得）
> 
> https://github.com/XIU2/CloudflareSpeedTest

这个项目的  -cfcolo 是使用 CloudflareSpeedTest 本地到  HKG,KHH,NRT,LAX,SEA,SJC,FRA,MAD 这些地方的延迟吧？warp的ip分配是就近机房分配的，暂时未知道人为如何改变，有个方式是改上游接入网络，但这样我试过效果很差，速度很慢的，所以现在还没有一个非常好的改分配ip归属地的方法。
