### ISSUE TITLE
[help wanted 求助]: ip stack 固定在了 ipv6

### ISSUE THREAD

**Issue by cs50Mu** [fscarmen/warp#316]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

使用脚本更改优先级别不起作用。

在vps上：
```
xxx@ip-189-33-4-268:~$ sudo ./menu.sh s

 Language:
 1. English (default)
 2. 简体中文

 Choose: 2

 请选择优先级别:
 1. IPv4
 2. IPv6
 3. 使用 VPS 初始设置 (默认)

 请选择: 1

 IPv4 优先
```
通过 curl 确认，确实是 ipv4 了：

```
xxx@ip-189-33-4-268:~$ curl ip.p3terx.com
104.28.217.215
US / United States
AS13335 / CLOUDFLARENET

curl/7.58.0
```

但是，在本地获取的竟然是 ipv6 地址：

```
➜  curl ip.p3terx.com
2a09:bac5:4753:1482::20b:16
US / United States
AS /

curl/7.79.1
```

能帮看看这是什么情况吗。。？无论我在 vps 上怎么更改优先级别，本地获取的一直都是 ipv6 地址

### Log / 日志信息

没有

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你指的本地获取是指哪个本地？

**Comment by cs50Mu** [comment]
我的连接情况：

本地(Mac 电脑) --> 路由器（clash）---> vps(运行了gost、warp等）

**Comment by fscarmen** [comment]
你上游的 v2ray / xray 里已经 把 ip.p3terx.com 解析成 ipv4了，所以很多时候不是看 vps 的优先级，而是上游的 v2ray / xray

**Comment by cs50Mu** [comment]
意思是，代理软件无视了vps上的优先级选择，自己强制选择了ipv6？

**Comment by fscarmen** [comment]
是的，一个域名，在 v2ray / xray 里已经解析好 ip 再给 vps 的，所以 vps 的优先级别不起作用，你想要的效果，需要在 v2ray / xray 里设置 ipv4 ipv6 的优先级别，又或者哪些网站分流到 ipv6 等，谷歌一下模板可以了。

**Comment by cs50Mu** [comment]
多谢，不过我并不是用v2ray / xray来代理的，我再看看

**Comment by cs50Mu** [comment]
不是，我理解clash是可以本地不解析，直接把域名发给vps

**Comment by fscarmen** [comment]
这里数据传递的链条很长，经过的环节起码4、5个，而 linux 解析都已经是最后一个环节了，所以你从前面的环节那里找找答案好点。
