### ISSUE TITLE
[help wanted 求助]: 卸载脚本后，ipv4像消失了一样

### ISSUE THREAD

**Issue by sayainchina** [fscarmen/warp#317]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

卸载脚本后，ipv4像消失了一样，我也想找个log，但是整个ipv4是不通的情况，只有ipv6能连接上去，我的机器是ubuntu 18

### Log / 日志信息

 请选择: 5
 Client 需要原生 IPv4 才能正常安装，该 IP 不能是 Warp，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
```
bash menu.sh u
```

卸载后不行再重启，应该没有问题了。

**Comment by sayainchina** [comment]
> 

我刚刚试过，卸载后重启，都不行...整个ipv4像消失了一样

**Comment by fscarmen** [comment]
你试试，情况好奇怪

**Comment by sayainchina** [comment]
> 你试试，情况好奇怪

如果有需要，我可以提供log，但是...好像也没什么log输出啊（( Ĭ ^ Ĭ )）

**Comment by sayainchina** [comment]
> curl -4m8 ip.gs curl -4m8 ifconfig.co 看看

刚刚另外一种办法解决了，再次安装，然后暂停，最后卸载，然后再安装就好了...

**Comment by fscarmen** [comment]
> > curl -4m8 ip.gs curl -4m8 ifconfig.co 看看
> 
> 刚刚另外一种办法解决了，再次安装，然后暂停，最后卸载，然后再安装就好了...

还有这么怪的方法？

**Comment by moruga8964** [comment]
我也遇到了这个问题。一开始不知道怎么用，没 team token 就用 team 帐户模式接 IP 当然接不到，然后我的机子就没有 ipv4 了。
后面切到 free 接到了 cf 提供的 ipv4
