### ISSUE TITLE
[help wanted 求助]: chat gpt 依然被限制

### ISSUE THREAD

**Issue by ericjin07** [fscarmen/warp#319]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

我已经使用`warp-go.sh` 安装好了：
<img width="707" alt="Screenshot 2023-03-31 at 21 43 49" src="https://user-images.githubusercontent.com/32515008/229137426-440e6e56-738d-41cf-80d1-dc61fc1d9186.png">

可是通过从浏览器依旧被拦截，拦截的ip 是联通的：
<img width="541" alt="image" src="https://user-images.githubusercontent.com/32515008/229138412-b49e6581-c193-4def-b1b4-b018415e6a4a.png">

当前浏览器获取到的ip:
<img width="567" alt="Screenshot 2023-03-31 at 21 51 23" src="https://user-images.githubusercontent.com/32515008/229138997-1e5d29b5-bf07-4882-a89d-5347a17e8102.png">

vps 是 搬瓦工 LOS ANGELES - CN2 的
服务器上的翻墙协议trojan-go,  nginx 反向代理的
local 用的使用了全局代理

按理来gpt 应该获取不到我的联通ip呀

想请问一下，还有什么需要配置的么？

### Log / 日志信息

暂无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
感觉你是没有连到代理，直接访问chatGPT了，你浏览器 ip.sb 先看看，如果是 clash 等，看看连接里的分流规则对不对。

**Comment by ericjin07** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/32515008/229152914-764d1118-4192-4006-b4ca-cd5642ed87d1.png">

本地我没设分流了，直接用的全局模式，所有连接都走代理了

**Comment by fscarmen** [comment]
我现在用 poe.com 啦，既有chatGPT，又不用像官网那样受限制，也不需要老是要求验证真人

**Comment by yanboer** [comment]
> 我现在用 poe.com 啦，既有chatGPT，又不用像官网那样受限制，也不需要老是要求验证真人

赞，确实挺好用的。chatgpt 动不动就要验证真人刷新网页。

**Comment by QgZhan** [comment]
请问楼主解决了吗？我今天新换了个加州的VPS，也遇到了这种情况，之前用的韩国的没问题

**Comment by fscarmen** [comment]
chatGPT显示的ip是什么？你vps的还是warp的104.28开头的？

**Comment by QgZhan** [comment]
破案了，几个有名的VPS商家都被ban了，至少搬瓦工的IP都连不上

**Comment by fscarmen** [comment]
> 破案了，几个有名的VPS商家都被ban了，至少搬瓦工的IP都连不上

连不上 chatGPT 还是连不上 warp? 如果是前者，通过 warp 能连上吗？这样 chatGPT 只知道你的地区，已经不知道 VPS 商家的 IP 了

**Comment by fscarmen** [comment]
的确有的地方仍然是不行，比如大陆或者香港 使用了warp 去连 chatGPT，仍然是不行的，试试用 [poe.com ](https://poe.com/ChatGPT) 替代或者需要别的 vps了

**Comment by yzx1208** [comment]
我这里出现的是warp分流之后是出现429错误.Failed to load resource: the server responded with a status of 429 ()
