### ISSUE TITLE
2021.12.04 2.20 更新后，安装提示：“ 没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。”-【结论：手动安装wireguard-tools之后正常了。暂不太确认为什么没有安装到】

### ISSUE THREAD

**Issue by geekbb** [fscarmen/warp#32]
已确定选择“1”安装完毕后，提示“ 没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。”

**Comment by geekbb** [comment]
![image](https://user-images.githubusercontent.com/46196358/144709663-03314087-49e1-41fa-97e1-3dbdaef4dcd1.png)

**Comment by fscarmen** [comment]
我已经降级了，现在再试试，可能有一块需要处理一下再重新发出来，以兼容好点

**Comment by fscarmen** [comment]
应该是 wireguard-tools 没有安装好 ，什么系统？

**Comment by geekbb** [comment]
当前操作系统：Debian GNU/Linux 10 (buster)
        内核：5.10.79-bbrplus
        处理器架构：amd64
        虚拟化：kvm

**Comment by geekbb** [comment]
![image](https://user-images.githubusercontent.com/46196358/144709918-bae5b14d-afce-41f0-95e2-aacaacc395b8.png)
降级后的还是一样

**Comment by fscarmen** [comment]
你手动试试 ```apt -y install wireguard-tools```
遇到过系统安装不了

**Comment by geekbb** [comment]
> 你手动遇到`apt -y install wireguard-tools` 过系统安装失败

搞定，谢谢

**Comment by fscarmen** [comment]
是不是这里出现问题呢？
