### ISSUE TITLE
[help wanted 求助]: 卸载无效

### ISSUE THREAD

**Issue by liangfengshan** [fscarmen/warp#320]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

我通过菜单，选菜单里7选项卸载。控制台显示删除成功，但是使用warp命令还能打开菜单，且流量仍然使用的warp 添加ip6

### Log / 日志信息

 1.  Switch WARP IPv6 to WARP IPv4 (warp 4) 
 2.  Switch WARP IPv6 to WARP dualstack (warp d) 
 3.  Change the WARP account type (warp a) 
 4.  Turn on WARP (warp o) 
 5.  Install CloudFlare Client and set mode to Proxy (bash menu.sh c) 
 6.  Change the WARP IP to support Netflix (warp i) 
 7.  Turn off, uninstall WARP interface, Linux Client and WireProxy (warp u) 
 8.  Getting WARP+ quota by scripts (warp p) 
 9.  Upgrade kernel, turn on BBR, change Linux system (warp b) 
 10. Sync the latest version (warp v) 
 11. Professional one-click script for WARP to unblock streaming media (Supports multi-platform, multi-mode and TG push) 
 12. Install iptable + dnsmasq + ipset. Let WARP only take over the streaming media traffic (Not available for ipv6 only) (bash menu.sh e) 
 13. Install wireproxy. Wireguard client that exposes itself as a socks5 proxy or tunnels (bash menu.sh w) 
 14. Install CloudFlare Client and set mode to WARP (bash menu.sh l) 
 0.  Exit 

 Choose: 7
 WARP interface, Linux Client and WirePorxy have been completely deleted!
 IPv4: 45.144.176.153 Russia LLC Baxet
 IPv6: 2a09:bac5:51c3:369::57:1a1 Russia Cloudflare 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
建议再安装一次，然后卸载看看
