### ISSUE TITLE
[help wanted 求助]: 三毛机无法使用-【结论: Cloudflare 是对三毛的 IP 做了限制，所有的账户都不让注册，2023年4月6日，升级 wgcf ，使用共享免费账户方案已处理】

### ISSUE THREAD

**Issue by lalalabbbb** [fscarmen/warp#321]
### Script / 脚本

warp-go.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

在两台俄罗斯三毛机上运行warp-go.sh都报错，运行menu.sh跑几个小时都没跑完，但是在我的其他机器上都可以正常运行使用

### Log / 日志信息

 Language:
 1.English (default) 
 2.简体中文 

 Choose: 2
 检查环境中…… 
 本项目专为 VPS 添加 WARP 网络接口，使用 wire-go 核心程序，利用CloudFlare-WARP 的各类接口，集成 wireguard-go，可以完全替代 WGCF。 救活了香港、多伦多等 VPS 也可以获取 WARP IP。再次感谢 @CoiaPrant 及其团队。项目地址: https://gitlab.com/ProjectWARP/warp-go/-/tree/master/ 
======================================================================================================================

 脚本版本: 1.1.3
 功能新增: 1. warp endpoint 优选改为标准端口 [500,1701,2408,4500]; 2. 升级奈飞解锁部分
 系统信息:
	 当前操作系统: CentOS Linux 7 (Core)
	 内核: 3.10.0-1160.53.1.el7.x86_64
	 处理器架构: amd64v3
	 虚拟化: microsoft 
	 IPv4: *.*.*.*  俄罗斯  JSC Mediasoft ekspert 
	 IPv6:      
	 WARP 网络接口未开启 

======================================================================================================================

 1. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv4 优先 (bash warp-go.sh 4) 
 2. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv6 优先 (bash warp-go.sh 4) 
 3. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6) 
 4. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv6 优先 (bash warp-go.sh 6) 
 5. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv4 优先 (bash warp-go.sh d) 
 6. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv6 优先 (bash warp-go.sh d) 
 7. 为 IPv4 only 添加 WARP IPv4 非全局 网络接口，IPv4 优先 (bash warp-go.sh n) 
 8. 为 IPv4 only 添加 WARP IPv4 非全局 网络接口，IPv6 优先 (bash warp-go.sh n) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 4

 如有 WARP+ 或 Teams 账户请选择
 1. WARP+
 2. Teams
 3. 使用免费账户 (默认) 

 请选择: 3

 进度 1/3: 安装系统依赖…… 

 注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 注册 WARP free 账户失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by lalalabbbb** [comment]
刚刚尝试在curl cf的接口，返回tcp被重置

curl https://api.cloudflareclient.com/v0a2483/reg/*********-*********-*******-****
curl: (35) TCP connection reset by peer

**Comment by fscarmen** [comment]
当前操作系统: CentOS Linux 7 (Core)
内核: 3.10.0-1160.53.1.el7.x86_64
处理器架构: amd64v3
虚拟化: microsoft

判断不了什么问题呢，可以的话，换个debian或者ubuntu看看

**Comment by lalalabbbb** [comment]
我发现请求cf的接口被重置了，我在尝试反代cf的接口能不能解决

**Comment by lalalabbbb** [comment]
> 当前操作系统： CentOS Linux 7 （Core） 内核： 3.10.0-1160.53.1.el7.x86_64 处理器架构： amd64v3 虚拟化： Microsoft
> 
> 判断不了什么问题呢，可以的话，换个debian或者ubuntu看看

是否可以提供一下手动注册warp的命令呢？我这里报错一直是注册失败

**Comment by lalalabbbb** [comment]
/opt/warp-go/warp-go --config=/opt/warp-go/warp.conf
ERROR: (WARP-Go)2023/04/01 17:26:57 Failed to get warp info: Get "https://api.cloudflareclient.com/v0a2483/reg/d4faa37a-ab37-4da2-a299-9ecd2fa27ee1": read tcp 195.133.145.66:53908->162.159.128.2:443: read: connection reset by peer

**Comment by fscarmen** [comment]
仍然未解决？你试试安装 client 看是否可以呢？从而判断一下哪里出问题

**Comment by lalalabbbb** [comment]
> 仍然未解决？你试试安装 client 看是否可以呢？从而判断一下哪里出问题

yum install -y cloudflare-warp
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                |  18 kB  00:00:00     
 * base: centos-mirror.rbc.ru
 * epel: mirror.yandex.ru
 * extras: mirror.docker.ru
 * updates: mirror.docker.ru
base                                                                                | 3.6 kB  00:00:00     
https://pkg.cloudflareclient.com/dists/7/main/binary-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



 One of the configured repositories failed (Cloudflare CentOS Packages),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=cloudflare ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable cloudflare
        or
            subscription-manager repos --disable=cloudflare

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=cloudflare.skip_if_unavailable=true

failure: repodata/repomd.xml from cloudflare: [Errno 256] No more mirrors to try.
https://pkg.cloudflareclient.com/dists/7/main/binary-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by lalalabbbb** [comment]
> 仍然未解决？你试试安装 client 看是否可以呢？从而判断一下哪里出问题

是这个client吗？还是哪个的？如果不是的话方便给我一下安装命令吗？

**Comment by lalalabbbb** [comment]
误操作关闭了issue，已经打开了

**Comment by fscarmen** [comment]
官方是不支持你的 centos 7，我处理过，你可以这样安装
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh c
```

**Comment by lalalabbbb** [comment]
> 官方是不支持你的 centos 7，https://pkg.cloudflareclient.com/packages/cloudflare-warp 。我处理过，假装是 CentOS 8来安装，你可以运行
> 
> ```
> wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh c
> ```

[日志.log](https://github.com/fscarmen/warp/files/11146970/default.log)

**Comment by lalalabbbb** [comment]
在两台ruvds的三毛机上运行命令，到最后都是报“创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp/issues] ”错误

**Comment by fscarmen** [comment]
如果不行的话，建议换个系统，centOS7好难玩的

**Comment by lalalabbbb** [comment]
> 如果不行的话，建议换个系统，centOS7好难玩的

好的，我尝试更换其他系统试试

**Comment by fscarmen** [comment]
兄台，为什么你用的系统都这么老掉牙的，试试 ubuntu 22.04 / ubuntu 20.04 / debian 10 / debian 11 的，如果不行，tg 里找找我  @fscarmen2

**Comment by lalalabbbb** [comment]
我超过服务商的一天重装系统次数的限制，无法再重装系统了，我明天再试试

**Comment by fscarmen** [comment]
脚本已就该 VPS 处理，单双栈均已 OK，感谢提供机子测试。

<img width="719" alt="image" src="https://user-images.githubusercontent.com/62703343/230427487-c84752d6-1dca-434e-a2fb-8b34c03aa680.png">

**Comment by fscarmen** [comment]
这机器还在吗？能不能借来测一下。
