### ISSUE TITLE
[help wanted 求助]: docker内访问WirePorxy的端口问题[已解决]

### ISSUE THREAD

**Issue by klmmlk** [fscarmen/warp#322]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

麻烦各位了！
我在宿主机通过WirePorxy方式运行warp，但是docker内无法访问到该端口
docker容器网络模式采用：bridge
nc -nzv 172.17.0.1 40000 得到结果是 nc: 172.17.0.1 (172.17.0.1:40000): Host is unreachable
通过curl也是同样的结果。
我试图通过让WirePorxy运行在0.0.0.0上，也得到同样的结果，我尝试在此基础上用caddy反代40000端口，docker通过外部ip访问可以成功。但是我不想让这个接口暴露在外部，请问有什么好的方法可以解决。谢谢！！

### Log / 日志信息

暂无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
我有个项目 docker_unlcok ，在 docker 里运行 wgcf 获取 warp IP后，然后用 gost 为宿主机开放一个 socks5 端口为40000的代理，我在docker run 里既没有 `--network host` ，也没有 `-p 40000:40000` ，在 xray 里照样可以分流到该容器的内网IP 72.17.0.2+端口40000，其实我也不太了解为什么可以，但事实就是这样不需要对公网暴露，只监听宿主机。
