### ISSUE TITLE
[help wanted 求助]: 跑了1-2天后，VPS失联，现象就是VPS对外完全ping不通ip和域名

### ISSUE THREAD

**Issue by hezudao13** [fscarmen/warp#323]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

输入token安装warp team版失败，显示重连2次，然后SSH断掉。再登录则外网ip、域名都ping不通。warp-go的指令执行都没有反应。之前免费版都是可以正常使用的，目前该怎么挽救下。。请教大神

### Log / 日志信息

root@localhost:~# warp-go u
^Z
[1]+  Stopped                 warp-go u
root@localhost:~# warp-go o
^Z
[2]+  Stopped                 warp-go o
root@localhost:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
^Z
[3]+  Stopped                 ping 1.1.1.1
root@localhost:~# ping google.com
ping: google.com: Temporary failure in name resolution
root@localhost:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
^Z
[4]+  Stopped                 ping 1.1.1.1

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
不用teams，一样会断吗？

**Comment by hezudao13** [comment]
跑了两天后，VPS失联，现象就是VPS对外完全ping不通ip和域名，需要强制关闭服务再开启服务获取一次才可以恢复。之前用免费版和现在用team版都出现过，搬瓦家的LA，Debian 11系统

**Comment by hezudao13** [comment]
跑了1-2天后，VPS失联，现象就是VPS对外完全ping不通ip和域名，需要强制关闭服务再开启服务获取一次才可以恢复。之前用免费版和现在用team版都出现过，搬瓦家的LA，Debian 11系统

**Comment by fscarmen** [comment]
做个定时任务，每天定时1到2次复启服务，时间放在睡觉休息时呢

**Comment by hezudao13** [comment]
近两天没有失联，我再试试，不行就加个定时任务

**Comment by fscarmen** [comment]
嗯，我下个更新加个keepalive 30秒进去，看看会不会好点

**Comment by fscarmen** [comment]
> 最近依然是好了两天就复现异常，不知道到底啥情况，warp-go 在哪能看一下日志情况？

```
journalctl -u warp-go
```

**Comment by hezudao13** [comment]
看日志感觉有15s重试外没看到其他异常，目前是异常发生后，对外ping不通了，需要systemctl disable --now warp-g；然后再warp-go o 重新开启才行

Apr 18 00:33:33 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:33:33 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:34:23 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:34:23 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:34:24 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:34:24 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:34:24 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:34:24 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:36:10 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:36:10 peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds
Apr 18 00:36:10 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:36:10 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:36:11 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:36:11 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:36:11 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:36:11 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:36:36 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:36:36 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:36:52 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:36:52 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:37:11 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:37:11 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:37:23 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:37:23 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:38:04 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:38:04 peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds
Apr 18 00:38:04 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:38:04 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:38:04 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:38:04 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:38:04 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:38:04 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:38:30 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:38:30 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:38:45 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:38:45 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:39:00 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:39:00 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:39:16 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:39:16 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:39:59 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:39:59 peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds
Apr 18 00:39:59 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:39:59 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:39:59 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:39:59 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:39:59 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:39:59 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:40:25 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:40:25 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:41:11 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:41:11 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:41:51 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:41:51 peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds
Apr 18 00:41:51 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:41:51 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:41:51 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:41:51 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:41:51 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:41:51 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:42:16 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:42:16 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:42:31 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:42:31 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:43:02 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:43:02 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:43:52 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:43:52 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:43:52 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:43:52 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:43:52 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:43:52 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:43:52 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:43:52 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:44:07 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:44:07 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:44:22 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:44:22 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:45:55 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:45:55 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:45:55 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:45:55 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:45:55 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:45:55 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:46:36 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:46:36 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:47:33 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:47:33 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:47:57 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:47:57 peer(bmXO…fgyo) - Sending handshake initiation
Apr 18 00:47:57 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:47:57 peer(bmXO…fgyo) - Received handshake response
Apr 18 00:47:57 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:47:57 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:48:27 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:48:27 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:48:53 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:48:53 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:49:09 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:49:09 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:49:24 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:49:24 peer(bmXO…fgyo) - Sending keepalive packet
Apr 18 00:49:39 localhost.localdomain warp-go[14770]: DEBUG: (WARP-Go)2023/04/18 00:49:39 peer(bmXO…fgyo) - Sending keepalive packet

**Comment by yanghuan** [comment]
alpine  1.7.3 安装后，大概一天左右，也会发生网络不通的情况，关闭或者重启打开，就好了，但是过一天左右又会出问题。

**Comment by fscarmen** [comment]
> alpine 1.7.3 安装后，大概一天左右，也会发生网络不通的情况，关闭或者重启打开，就好了，但是过一天左右又会出问题。

这个应该是网络不稳定，导致不稳定的，你可以在 cron 里加上每1-2分钟 `warp n`，作用就是每1-2分钟检测一次是否有启动 wgcf，同时能刷到 IP。如果是，任务退出，如果不是，就会自动给你重启。

**Comment by yanghuan** [comment]
> > alpine 1.7.3 安装后，大概一天左右，也会发生网络不通的情况，关闭或者重启打开，就好了，但是过一天左右又会出问题。
> 
> 这个应该是网络不稳定，导致不稳定的，你可以在 cron 里加上每1-2分钟 `warp n`，作用就是每1-2分钟检测一次是否有启动 wgcf，同时能刷到 IP。如果是，任务退出，如果不是，就会自动给你重启服务。

好的，我试试

**Comment by fscarmen** [comment]
您可以按照以下步骤在Alpine中设置cron定时任务：

编辑 /etc/crontab 文件，添加以下内容：

```
*/2 * * * * root warp n
```
上述内容表示每两分钟执行一次warp n 命令

重新启动 cron 服务：
```
/etc/init.d/crond restart
```
上述命令会重启 cron 服务，使新的定时任务生效。

**Comment by siyue666** [comment]
> 您可以按照以下步骤在Alpine中设置cron定时任务：
> 
> 编辑 /etc/crontab 文件，添加以下内容：
> 
> ```
> */2 * * * * root warp n
> ```
> 
> 上述内容表示每两分钟执行一次warp n 命令
> 
> 重新启动 cron 服务：
> 
> ```
> /etc/init.d/crond restart
> ```
> 
> 上述命令会重启 cron 服务，使新的定时任务生效。

你好，我的vps失联要了，ssh也连接不上，能进救援模式，有什么办法挽救吗
