### ISSUE TITLE
通过 warp 解锁 chatGPT 的方法

### ISSUE THREAD

**Issue by siyue666** [fscarmen/warp#324]
请问x-ui这个要怎么改呢，不管怎么改都没网，看了之前的issues里面的模板也不行

{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727

**Comment by siyue666** [comment]
> [#286 (comment)](https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727)

还是不行，cilent也装不上，估计是因为系统是dd的不支持

**Comment by siyue666** [comment]
> [#286 (comment)](https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727)

重装试过了，加上查询ip的网站看是成功了，显示的是cloudflare的ip，但是ChatGPT仍然是真实ip

**Comment by fscarmen** [comment]
那么可能是没有分流过去，去 json.cn 查查你的配置文件是否正确

**Comment by gc89925** [comment]
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "tag": "WARP",
      "protocol": "wireguard",
      "settings": {
        "secretKey": "cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=",
        "address": [
          "172.16.0.2/32",
          "fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128"
        ],
        "peers": [
          {
            "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "endpoint": "engage.cloudflareclient.com:2408"
          }
        ]
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "type": "field",
        "domain": [
          "domain:openai.com",
          "domain:ai.com"
        ],
        "outboundTag": "WARP"
      }
    ]
  },
 
直接复制粘贴拿去用吧

**Comment by fscarmen** [comment]
> > [#286 (comment)](https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727)
> 
> 重装试过了，加上查询ip的网站看是成功了，显示的是cloudflare的ip，但是ChatGPT仍然是真实ip

https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727

**Comment by MinionTim** [comment]
> [#286 (comment)](https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727)

这种使用wireguard协议来做分流的方案，获取到的 warp ip  和直接使用 warp-cli 客户端获取的 warp ip  会有差别么。 感觉上我用的warp-cli 的 warp ip貌似已经没滥用到不行了，ip 已经进入到chatgpt 的风控边缘了

**Comment by jokerElsa** [comment]
> > [#286 (comment)](https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727)
> 
> 这种使用wireguard协议来做分流的方案，获取到的 warp ip 和直接使用 warp-cli 客户端获取的 warp ip 会有差别么。 感觉上我用的warp-cli 的 warp ip貌似已经没滥用到不行了，ip 已经进入到chatgpt 的风控边缘了

现在虽然不封但是我的聊天页已经进不去了，换warp ip也很快就转圈。

**Comment by wangfeng35** [comment]
> > > [#286 (comment)](https://github.com/fscarmen/warp/issues/286#issuecomment-1449511727)
> > 
> > 
> > 这种使用wireguard协议来做分流的方案，获取到的 warp ip 和直接使用 warp-cli 客户端获取的 warp ip 会有差别么。 感觉上我用的warp-cli 的 warp ip貌似已经没滥用到不行了，ip 已经进入到chatgpt 的风控边缘了
> 
> 现在虽然不封但是我的聊天页已经进不去了，换warp ip也很快就转圈。

看来很快又要挂
