### ISSUE TITLE
[help wanted 求助]: 成功安装 warp-go 并且开启全局模式，但所有的地方IP均显示VPS原生IP，没有显示warp IP

### ISSUE THREAD

**Issue by Metalheadache** [fscarmen/warp#326]
### Script / 脚本

warp-go.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

我的VPS（搬瓦工LA节点的CN2GIA）已经成功安装warp-go、成功获取ip并且开启全局模式了，但是所有地方的ip测试还是仍然显示的我VPS的IP，没有显示warp后的IP。不知道是不是哪里漏设置了，还是怎么回事？
VPS OS：CentOS 7
![image](https://user-images.githubusercontent.com/39906408/229973179-2f49f065-8fbf-41a5-a526-8de3cc5b0b0e.png)
![image](https://user-images.githubusercontent.com/39906408/229973234-6af276da-43e1-4c86-825f-ee9ee067357d.png)

### Log / 日志信息

暂无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
把你的代理软件设置全局先看看

**Comment by Metalheadache** [comment]
> 把你的代理软件设置全局先看看

目前设置的是全局的

**Comment by fscarmen** [comment]
搞不清楚了，我是没有遇到这样的情况，你多用个客户端开全局测测。
