### ISSUE TITLE
[Bug]: 不支持腾讯云的OpenCloudOS系统

### ISSUE THREAD

**Issue by enerai** [fscarmen/warp#328]
### Expectation / 预期情况

基于centos8应该能够安装

### Actual Situation / 实际情况

执行脚本提示不支持该系统

### Reproduction Method / 复现方法

腾讯云选用OpenCloudOS镜像，下载脚本执行

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你输入 `grep -i pretty_name /etc/os-release | cut -d \" -f2` 看显示什么，如果显示 OpenCloudOS *****的，把他全部改为小写，加到 https://github.com/fscarmen/warp/blob/main/menu.sh#L426

一定要紧跟 centos，后面加 | 再输入系统名，中间不要有任何空格，像下图所示

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/62703343/230434754-87cc40c7-829d-43d7-9f91-aaf791e1a5d1.png">

**Comment by enerai** [comment]
OK，修改sh文件当中的内容之后就可以执行了👍🏻
