### ISSUE TITLE
Quota Script error

### ISSUE THREAD

**Issue by asterriya** [fscarmen/warp#33]
WARP-PLUS-CLOUDFLARE (script) By ALIILAPRO

Traceback (most recent call last):
  File "/root/warp-plus-cloudflare/wp-plus.py", line 79, in <module>
    sys.stdout.write("\r[+] Preparing... " + animation[i % len(animation)])
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 19-28: ordinal not in range(256)

**Comment by fscarmen** [comment]
I just tried it on two systems - CentOS 8 and Debian 10.
it worked quite well.

![image](https://user-images.githubusercontent.com/62703343/144754243-ee502e28-ad01-4912-9e87-d129622d3adf.png)

**Comment by asterriya** [comment]
@fscarmen 
I try it on both machine - clear and working. Same error. What the issues it can be?

Also, want to ask if there is advantage to activate warp+ or it is useless?

**Comment by asterriya** [comment]
@fscarmen Can you recommend please how to make setup right. I have on my VPS ipv4 and ipv6 but on sysctl.conf I close ICMP redirect/ping/echo to make it private, so I want to be sure that everything is fine during setup

**Comment by fscarmen** [comment]
> @fscarmen I try it on both machine - clear and working. Same error. What the issues it can be?
> 
> Also, want to ask if there is advantage to activate warp+ or it is useless?

According to user feedback.WARP+ may be effective for websites that use cloudflare services, and a little change for others.

**Comment by asterriya** [comment]
So it's useless, mostly. Got it.

**Comment by fscarmen** [comment]
> 你能推荐一下如何正确设置吗？我有我的 VPS ipv4 和 ipv6 但在 sysctl.conf 我关闭 ICMP 重定向/ping/echo 以使其私有，所以我想确保在设置过程中一切正常

The script will check & install the dependencies. It seems no need to special treat. It run in a  clear system.

**Comment by fscarmen** [comment]
I think WARP+ or Teams is better. I tested three brush WARP+ traffic scripts right now. They ran normally.
[Argo 2.0: Smart Routing Learns New Tricks](https://blog.cloudflare.com/argo-v2/)
