### ISSUE TITLE
[help wanted 求助]: 无法获取warp IP

### ISSUE THREAD

**Issue by Nothingness-Void** [fscarmen/warp#331]
### Script / 脚本

warp-go.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

正常运行warp-go脚本后

======================================================================================================================

 脚本版本: 1.1.3
 功能新增: 1. warp endpoint 优选改为标准端口 [500,1701,2408,4500]; 2. 升级奈飞解锁部分
 系统信息:
         当前操作系统: CentOS Stream 9
         内核: 5.14.0-295.el9.x86_64
         处理器架构: amd64v3
         虚拟化: kvm 
         IPv4: 161.35.194.196  德国  Digital Ocean 
         IPv6: 2a03:b0c0:3:d0::728:d001  德国  Digital Ocean 
         WARP 网络接口未开启 

======================================================================================================================

 1. WARP 全局 双栈 转为 WARP 全局 IPv4 (warp-go 4) 
 2. WARP 全局 双栈 转为 WARP 全局 IPv6 (warp-go 6) 
 3. 转为 WARP 非全局 网络接口 (warp-go g) 
 4. 打开 warp-go (warp-go o) 
 5. 更换为 Free，WARP+ 或 Teams 账户 (warp-go a) 
 6. 更换支持 Netflix 的 IP (warp-go i) 
 7. 输出 wireguard 和 sing-box 配置文件 (warp-go e) 
 8. 卸载 WARP 网络接口和 warp-go (warp-go u) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 4
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 第2次尝试 
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.
 第3次尝试 
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.

### Log / 日志信息

Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

输入 `journalctl -xeu warp-go.service` 后显示

 Support: https://access.redhat.com/support
░░ 
░░ The unit warp-go.service has entered the 'failed' state with result 'exit-code'.
Apr 07 15:39:15 Ger-ipv6 systemd[1]: Failed to start warp-go service.
░░ Subject: A start job for unit warp-go.service has failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit warp-go.service has finished with a failure.
░░ 
░░ The job identifier is 8000 and the job result is failed.

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen2** [comment]
1.卸载warp-go `bash warp-go.sh u`
2.重置systemd `systemctl daemon-reload`
3.最好重启一下机器 `reboot`
4.再更新安装 warp-go 看看

**Comment by fscarmen** [comment]
1.卸载warp-go `bash warp-go.sh u`
2.重置systemd `systemctl daemon-reload`
3.最好重启一下机器 `reboot`
4.再更新安装 warp-go 看看

**Comment by Nothingness-Void** [comment]
> 1.卸载warp-go `bash warp-go.sh u` 2.重置systemd `systemctl daemon-reload` 3.最好重启一下机器 `reboot` 4.再更新安装 warp-go 看看

按照步骤尝试过了，依然是同样的问题

**Comment by Nothingness-Void** [comment]
我貌似找到问题了 在第二步安装WGCF的时候无法下载 会显示

Cloudflare CentOS Packages                                               1.3 kB/s | 3.3 kB     00:02    
Errors during downloading metadata for repository 'cloudflare':
  - Status code: 404 for https://pkg.cloudflareclient.com/dists/9/main/binary-x86_64/repodata/repomd.xml (IP: 2606:4700::6813:ed18)
Error: Failed to download metadata for repo 'cloudflare': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

我是digitalOcean的德国法兰克福服务器

**Comment by fscarmen** [comment]
备份一下 resolv.conf ，把 nameserver 改为8.8.8.8 看看

**Comment by Nothingness-Void** [comment]
改完了还是不行，我试了试另一个新加坡的服务器是能下载的，但是也获取不到warpIP且新加坡服务器没有如下报错

Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.
仅会尝试五次然后停止

**Comment by fscarmen** [comment]
我弄台机器试试，又或者你改debian 10 或者 ubuntu 20.04 以上的系统，centos 太难了

**Comment by KAILY1** [comment]
情况相同，tw节点gcp更换多个ip都不行，3个层级的账户都无法获取ip，切换WGCF-WARP可以获取内核，系统为debian11

**Comment by Nothingness-Void** [comment]
我在新加坡的机器上（CentOS 9）手动 yum安装warp然后用warp官方的命令成功连接上，已经给v2套上了 但是德国的机器就是不行，很奇怪

**Comment by fscarmen** [comment]
你德国的能换个系统试试吗？

**Comment by Nothingness-Void** [comment]
DigitalOcean的重建比较怪。
![image](https://user-images.githubusercontent.com/55913486/230713228-a88046ec-944f-4ed9-880d-ad60c10e2098.png)
好像选了一种系统之后重建只能选这个系统的不同版本

**Comment by KAILY1** [comment]
> 你德国的能力转换系统考试吗？
请教一下非全局模式下可以获取ip，切换全局模式

Job for warp-go.service failed.
See "systemctl status warp-go.service" and "journalctl -xe" for details.
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

请问怎么办，debian11，gcp
