### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by 1715819** [fscarmen/warp#332]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

出现了一个很奇怪的情况，获取ipv4网络成功后，下方日志并没有显示获取到的ipv4地址，但是在whoer.net查询ip的时候又可以查到ipv4。这是什么情况呢？

### Log / 日志信息

下方的日志没有显示ipv4地址

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
没问题的，ip.sb会限制warp的ip，导致有时查不出来

**Comment by 1715819** [comment]
感谢
