### ISSUE TITLE
[help wanted 求助]: trojan可以使用吗？

### ISSUE THREAD

**Issue by AbianTang** [fscarmen/warp#333]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

trojan的https支持ipv6吗

### Log / 日志信息

un

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
可以，同时你可配合另一项目使用，也有trojan

https://github.com/fscarmen/argox
