### ISSUE TITLE
[help wanted 求助]: 不能获取到warp ip

### ISSUE THREAD

**Issue by NickMao05** [fscarmen/warp#334]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

网络是成都电信，始终获取不到WARP IP，但是在ios上的官方的名为1.1.1.1应用却可以正常连接（windows客户端也不行）
想知道有没有自定endpoint ip的方法

### Log / 日志信息

后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
这个endpoint已经优选过的了，仍然是全部不通吗？

**Comment by NickMao05** [comment]
是的，其它warp有关也不能用

**Comment by NickMao05** [comment]
在挂了代理的情况下依旧无望

**Comment by NickMao05** [comment]
======================================================================================================================

 脚本版本: 1.1.3
 功能新增: 1. warp endpoint 优选改为标准端口 [500,1701,2408,4500]; 2. 升级奈飞解锁部分
 系统信息:
         当前操作系统: Ubuntu 20.04.5 LTS
         内核: 5.15.90.1-microsoft-standard-WSL2
         处理器架构: amd64v2
         虚拟化: wsl
         IPv4:
         IPv6:
         WARP 网络接口未开启
         设备名: 'warp-go'       剩余流量:

======================================================================================================================

**Comment by NickMao05** [comment]
也看不到ip地址
