### ISSUE TITLE
[Bug]: warp-go e 无法导出singbox配置

### ISSUE THREAD

**Issue by nuts2k** [fscarmen/warp#338]
### Expectation / 预期情况

应该可以看到singbox配置

### Actual Situation / 实际情况

 
cat: /opt/warp-go/singbox.json: No such file or directory
Expecting value: line 1 column 1 (char 0)

### Reproduction Method / 复现方法

版本1.1.3
warp-go e

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by nuts2k** [comment]
补充一下，已通过warp-go获得team的IP，其他一切正常，也能看到导出的warpcf.conf，就是singbox配置无法配置。
尝试直接运行/opt/warp-go/warp-go --config=/opt/warp-go/warp.conf --export-singbox=/opt/warp-go/singbox.json

报错：
flag provided but not defined: -export-singbox

**Comment by fscarmen** [comment]
> 补充一下，已通过warp-go获得team的IP，其他一切正常，也能看到导出的warpcf.conf，就是singbox配置无法导出。 尝试直接运行/opt/warp-go/warp-go --config=/opt/warp-go/warp.conf --export-singbox=/opt/warp-go/singbox.json
> 
> 报错： flag provided but not defined: -export-singbox

我试了一下可以哦，你可以重装试试，如果你只是要注册账户，可以来 https://fscarmen.cloudflare.now.cc/ 提取
![image](https://user-images.githubusercontent.com/62703343/230868568-d28c0853-a11d-4c35-8358-93e5c07b0ce3.png)

**Comment by nuts2k** [comment]
我还是重装一下试试吧，有可能我1.1.3是脚本升级的，会有一些奇怪的问题

**Comment by fscarmen** [comment]
> 我还是重装一下试试吧，有可能我1.1.3是脚本升级的，会有一些奇怪的问题

肯定是这个原因了，我只升级脚本，没有升级核心程序的。
