### ISSUE TITLE
请问可否支持官方客户端+wireguard双模式同时运行-【结论：2021.11.6 已支持，先安装 WARP IPv6 单栈，再安装 Linux proxy client，双双支持 WARP plus】

### ISSUE THREAD

**Issue by 1-1-2** [fscarmen/warp#34]
我的机器是v4单栈的，想法是打通v6访问能力，同时又能像 issue#22 那样使用 socks 转发。

参考 p3terx 大佬的脚本，这两个应该是可以同时被安装运行的。

但其实又挺舍不得这个脚本丰富的功能，不知道能否在这个脚本也实现起来。

望大佬纳入考虑，谢谢！

**Comment by fscarmen** [comment]
首先感谢你的支持。本脚本是支持你想要的。
你v4 机器安装 WARP IPv6 单栈 + Linux proxy client
因为 linux proxy 需要用到非 WARP 的 IPv4，所以不能占用，本脚本安装的已经有足够的提示了

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/145045220-7a1e1987-1988-47b9-8693-f1f3442f4bed.png)
![image](https://user-images.githubusercontent.com/62703343/145045830-9c14fa0b-697e-42eb-99c7-8edb3e40fd05.png)

**Comment by 1-1-2** [comment]
经过尝试，是可以同时启用的。只是需要分别安装😀

感谢指点

**Comment by fscarmen** [comment]
> 经过尝试，是可以同时启用的。只是需要分别安装

分别安装好点，否则 WARP ipv4 和 Linux Proxy Client 会打架的，只能选其一

**Comment by 1-1-2** [comment]
请问在v6+socks模式下，`warp o`是不是只操作wireguard？而不会去操作WARP Linux Client的warp-svc服务。

另外，在这种情况下，更换ip会照顾到 WARP Linux Client 吗。

**Comment by fscarmen** [comment]
```warp r```
![image](https://user-images.githubusercontent.com/62703343/145677181-43346b83-eab0-4244-9b1d-5863bf3bd949.png)

**Comment by fscarmen** [comment]
> 更换ip会照顾到 WARP Linux Client 吗。

你指socks5更换支持奈飞的 IP 吗？

**Comment by 1-1-2** [comment]
>`warp o`  `warp r` 

 r 和 o 是两个完全独立的开关，分别对应 wireguard 和 WARP Linux Client 是吗



> > 更换ip会照顾到 WARP Linux Client 吗。
> 
> 你指socks5更换支持奈飞的 IP 吗？

是指的这个问题。从当前菜单的描述和逻辑上，没能看出来`warp i`对应修改的是哪个接口的配置。

**Comment by fscarmen** [comment]
> r 和 o 是两个完全独立的开关，分别对应 wireguard 和 WARP Linux Client 是吗

是的
r对应WARP Linux Client开关：warp-cli --accept-tos disconnect和warp-cli --accept-tos connect

o对应wireguar(-go)的开关：wg-quick up wgcf和wg-quick down wgcf

**Comment by fscarmen** [comment]
> 是指的这个问题。从当前菜单的描述和逻辑上，没能看出来warp i对应修改的是哪个接口的配置。

当前我还没有找到 WARP Linux Porxy 更换IP的有效简单方法，我试了以下方式都不行，IP不变：
1.disconnect and connect again
2.重启systemd。 systemctl restart warp-svc，和 systemctl disable --now  warp-svc, systemctl enable --now  warp-svc
3.杀warp-svc的进程，kill -9
4.切换工作模式，warp-cli set-mode dot,
warp-cli set-mode proxy

估计重新获取账号，甚至重装才行，但这样意义不大。你有没有好意路？

**Comment by 1-1-2** [comment]
> > 是指的这个问题。从当前菜单的描述和逻辑上，没能看出来warp i对应修改的是哪个接口的配置。
> 
> 当前我还没有找到 WARP Linux Porxy 更换IP的有效简单方法，我试了以下方式都不行，IP不变： 1.断开重连：`warp-cli disconnect` 和 `warp-cli connect` 2.重启systemd： `systemctl restart warp-svc`，和 `systemctl disable --now warp-svc` `systemctl enable --now warp-svc` 3.杀warp-svc的进程，`pgrep -f warp-svc | xargs kill -9` 4.切换工作模式:`warp-cli set-mode dot` 和 `warp-cli set-mode proxy` 5.更换端口：`warp-cli set-mode proxy 50000`
> 
> 估计重新获取账号，甚至重装才行，但这样意义不大。你有没有好思路？

研究不深入，暂时没发掘到什么突破口

**Comment by fscarmen** [comment]
> 研究不深入，暂时没发掘到什么突破口

暂时能想的都试了，不行。如果需要删掉账户重新获取，甚至是需要重新安装warp-cli的话代价有点大。

**Comment by fscarmen** [comment]
> 研究不深入，暂时没发掘到什么突破口

我发去CloudFlare官方社区问了，如果再不行，只能每次重建账号，花20-30秒左右一次来曲线救国实现socks5换IP了

https://community.cloudflare.com/t/how-could-i-change-the-ipv4-under-warp-linux-client-proxy-mode/336650

**Comment by fscarmen** [comment]
> 研究不深入，暂时没发掘到什么突破口

刚更新的 2.23 支持两种模式下，保持plus状态下刷奈飞IP
