### ISSUE TITLE
WARP脚本和WARP-GO脚本的获取Teams账户方式不同[Bug]: -【结论：2023.5.20 V2.50 已经支持通过 token 升级 warp 账户(可通过 https://web--public--warp-team-api--coia-mfs4.code.run 轻松获取)】

### ISSUE THREAD

**Issue by Rockeeeer** [fscarmen/warp#340]
### Expectation / 预期情况

WARP脚本和WARP-GO脚本都应该可以获得Teams账户的IP

### Actual Situation / 实际情况

你好作者

WARP脚本，更换账户类型选项，更换为Teams账户的方式是提供URL。
WARP-GO脚本，更换账户类型选项，更换为Teams账户的方式是提供Teams token。

使用WARP脚本更换Teams账户，提供自己的URL（保证格式正确）无法获得IP，后又用脚本提供的，也无法获得IP。
彻底卸载WARP脚本，然后安装并使用WARP-GO脚本更换Teams账户，访问网址获得Teams token，可以获得IP。

测试了3台VPS，GCP日本，AWS香港，CC美国，测试结果一致
均为WARP+URL方式无法获取IP，而WARP-GO+Teams token却可以一次性获取IP

请问可以将Teams token的方式用在WARP上面吗？或者替换掉URL的方式。

### Reproduction Method / 复现方法

1

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
2023.5.20 wgcf 一键脚本 V2.50

1. Client supports IPv6 VPS only;
2. Support 4 ways to upgrade to teams account including token (Easily available at https://web--public--warp-team-api--coia-mfs4.code.run);
3. Use api to delete warp account while uninstalling

1. Client 支持 IPv6 only VPS 安装;
2. 支持包括 token 等4种方式升级为 teams 账户 (可通过 https://web--public--warp-team-api--coia-mfs4.code.run 轻松获取);
3. 卸载的同时使用 api 删除 warp 账户

```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh
```
