### ISSUE TITLE
warp-go 在网页上获取 team token 失败

### ISSUE THREAD

**Issue by moruga8964** [fscarmen/warp#342]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

进入网站 `https://web--public--warp-team-api--coia-mfs4.code.run/`
输入帐号 `〇〇.cloudflareaccess.com `
报错 `Get "https://〇〇.cloudflareaccess.com.cloudflareaccess.com/warp": x509: certificate is valid for ssl1075497.cloudflaressl.com, *.cloudflareaccess.com, cloudflareaccess.com, not 〇〇.cloudflareaccess.com.cloudflareaccess.com
`
team 帐户是 cf 开的 free plan ，绑了付款方式，应该算正常启用了。

### Log / 日志信息

*

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by moruga8964** [comment]
好吧. 解决了
team 名应该输入你的 〇〇 。不带后缀的。
warp client 也要加一条规则让你可以作为用户登陆，收验证码

**Comment by fscarmen** [comment]
恭喜！
