### ISSUE TITLE
[help wanted 求助]: 如果warp-go 设置为非全局模式，应该转发到哪个端口?

### ISSUE THREAD

**Issue by ericjin07** [fscarmen/warp#344]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

我想要非全局配置warp, 设置了之后，查看配置文件
/opt/warp-go/singbox.json 的inbounds 是这样的
```
"inbounds": [
        {
            "listen": "127.0.0.1",
            "listen_port": 2000,
            "udp_timeout": 300,
            "type": "socks"
        }
    ],

```

可是我转发到127.0.0.1:2000 后
```
Failed to connect to 127.0.0.1 port 2000 after 1 ms: Couldn't connect to server
```

我用的不是xray, 用的是gost 做的转发，2000 端口，40000 端口似乎都没用

### Log / 日志信息

如上

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by s-charvin** [comment]
作为小白， 我也在寻找问题解决方法。 目前根据 @fscarmen 大佬的提示，有个初步解决方法。

主要注意到的是: 这里的 warp-go 是通过一个虚拟网卡进行访问伪装，而不是 socks 之类的端口。 因此不能通过端口转发的方式实现网络分流。

具体修改转发方式如下：

```bash
vi /etc/v2ray/config.json
# 添加 v2ray 的出站配置
  "outbounds": [
.
.
.,
	{
		"tag":"warpOut",
		"protocol":"freedom",
		"settings":{
			"domainStrategy":"UseIPv4"
		},
	   "sendThrough":"172.16.0.2"
	 }
  ],

# 修改 v2ray 的数据通信路由配置(必须放置在原有规则的前面， 可以理解为这些规则顺序执行，不满足才会判断下一个)
"rules": [
   {
	"type":"field",
	"outboundTag":"warpOut",
	"domain":[
		"geosite:netflix",
		"domain:ip.gs",
		"domain:openai.com",
		"domain:ai.com"
		]
   },
   .
   .
   .

```
