### ISSUE TITLE
安装 WARP 的 Linux Client 和代理模式 失败

### ISSUE THREAD

**Issue by hanjunjidaxian** [fscarmen/warp#349]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

Failed to start warp-svc.service: Unit warp-svc.service not found.

### Log / 日志信息

![image](https://user-images.githubusercontent.com/55234098/232693927-ec339b91-e14b-4c7a-a2f0-df265106717d.png)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by hanjunjidaxian** [comment]
![Uploading image.png…]()
这是我的系统信息

**Comment by hanjunjidaxian** [comment]
![Uploading image.png…]()

**Comment by fscarmen** [comment]
可以的话，请换个系统了，CentOS 官方都不支持了。
