### ISSUE TITLE
[help wanted 求助]: 请问vps开启warproxy socks5代理，可以用shadowsocks客户端连上正常代理吗

### ISSUE THREAD

**Issue by longzhiri** [fscarmen/warp#350]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

1. 请问vps开启warproxy socks5代理，可以用shadowsocks客户端连上并且正常代理吗？
2. 我开启全局代理模式，ip route show 看到的路由规则是
```
0:      from all lookup local 
32763:  from myip lookup main 
32764:  from all lookup main suppress_prefixlength 0 
32765:  not from all fwmark 0xca6c lookup 51820 
32766:  from all lookup main 
32767:  from all lookup default 
```
其中from myip lookup main 这条规则岂不是会让本机对外流量都走去main路由表查找，而不是51820 这个路由到隧道接口的路由表，那wireguard是如何做到接管本机对外流量的

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
> * 请问vps开启warproxy socks5代理，可以用shadowsocks客户端连上并且正常代理吗？
现在wireproxy的配置文件 `/etc/wireguard/proxy.conf` 是只对本地服务的，你可以把 127.0.0.1 改为 0.0.0.0，这样可以对公网服务，我这样改是用在公司局域网，还好，如果你真用在公网，看说明文档加上用户名和密码。

> * 我开启全局代理模式，ip route show 看到的路由规则是，其中from myip lookup main 这条规则岂不是会让本机对外流量都走去main路由表查找，而不是51820 这个路由到隧道接口的路由表，那wireguard是如何做到接管本机对外流量的

这块我不懂的，最早是参照这三个文章处理的

P3terx: https://p3terx.com/archives/use-cloudflare-warp-to-add-extra-ipv4-or-ipv6-network-support-to-vps-servers-for-free.html
Luminous: https://luotianyi.vc/5252.html
Hiram: https://hiram.wang/cloudflare-wrap-vps

**Comment by fscarmen** [comment]
> * 请问vps开启warproxy socks5代理，可以用shadowsocks客户端连上并且正常代理吗？
 现在wireproxy的配置文件 `/etc/wireguard/proxy.conf` 是只对本地服务的，你可以把 127.0.0.1 改为 0.0.0.0，这样可以对公网服务，我这样改是用在公司局域网，还好，如果你真用在公网，看说明文档加上用户名和密码。

>  * 我开启全局代理模式，ip route show 看到的路由规则是，其中from myip lookup main 这条规则岂不是会让本机对外流量都走去main路由表查找，而不是51820 这个路由到隧道接口的路由表，那wireguard是如何做到接管本机对外流量的

这块我不懂的，最早是参照这三个文章处理的

P3terx: https://p3terx.com/archives/use-cloudflare-warp-to-add-extra-ipv4-or-ipv6-network-support-to-vps-servers-for-free.html     
Luminous: https://luotianyi.vc/5252.html     
Hiram: https://hiram.wang/cloudflare-wrap-vps

**Comment by longzhiri** [comment]
感谢回复，我目前是使用kcp建立隧道代理转发shadowsocks流量，看起来shadowsocks认证没成功，请问传统ssserver的
```
ssserver -p 443 -k password -m aes-256-cfb --user nobody -d start
```
其中参数nobody,password对应warproxy的用户密码是吗？那加密算法 aes-256-cfb这个在哪里配呢？

**Comment by fscarmen** [comment]
> 感谢回复，我目前是使用kcp建立隧道代理转发shadowsocks流量，看起来shadowsocks认证没成功，请问传统ssserver的
> 
> ```
> ssserver -p 443 -k password -m aes-256-cfb --user nobody -d start
> ```
> 
> 其中参数nobody,password对应warproxy的用户密码是吗？那加密算法 aes-256-cfb这个在哪里配呢？

我记得 wireproxy 没有这个加密算法的哦，只有用户名和密码，详细你去 wireproxy 的项目问问:　https://github.com/pufferffish/wireproxy

**Comment by longzhiri** [comment]
谢谢
