### ISSUE TITLE
ubt 提示账户注册失败

### ISSUE THREAD

**Issue by hanjunjidaxian** [fscarmen/warp#351]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

![image](https://user-images.githubusercontent.com/55234098/232826662-733254db-18b2-4f28-baa1-130576ea6328.png)

### Log / 日志信息

Unpacking desktop-file-utils (0.26-1ubuntu3) ...
Selecting previously unselected package libnspr4:amd64.
Preparing to unpack .../libnspr4_2%3a4.32-3build1_amd64.deb ...
Unpacking libnspr4:amd64 (2:4.32-3build1) ...
Selecting previously unselected package libnss3:amd64.
Preparing to unpack .../libnss3_2%3a3.68.2-0ubuntu1.2_amd64.deb ...
Unpacking libnss3:amd64 (2:3.68.2-0ubuntu1.2) ...
Selecting previously unselected package libnss3-tools.
Preparing to unpack .../libnss3-tools_2%3a3.68.2-0ubuntu1.2_amd64.deb ...
Unpacking libnss3-tools (2:3.68.2-0ubuntu1.2) ...
Setting up gnupg2 (2.2.27-3ubuntu2.1) ...
Setting up desktop-file-utils (0.26-1ubuntu3) ...
Setting up libnspr4:amd64 (2:4.32-3build1) ...
Setting up libnss3:amd64 (2:3.68.2-0ubuntu1.2) ...
Setting up libnss3-tools (2:3.68.2-0ubuntu1.2) ...
Setting up cloudflare-warp (2023.3.398-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/warp-svc.service → /lib/systemd/system/warp-svc.service.
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
desktop-file-utils is already the newest version (0.26-1ubuntu3).
desktop-file-utils set to manually installed.
gnupg2 is already the newest version (2.2.27-3ubuntu2.1).
gnupg2 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 94 not upgraded.
(Reading database ... 76776 files and directories currently installed.)
Preparing to unpack Client_Ubuntu_22.04.deb ...
Unpacking cloudflare-warp (2023.3.398-1) over (2023.3.398-1) ...
Setting up cloudflare-warp (2023.3.398-1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
 进度 2/2: 设置 Client 模式

 注册 Client 账户失败，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

root@vm351130:~#

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by hanjunjidaxian** [comment]
![image](https://user-images.githubusercontent.com/55234098/232827754-e439579b-86ac-4faf-9e74-bf3814623bd0.png)

**Comment by fscarmen2** [comment]
原来是俄罗斯的鸡，现在给 cf 制裁了，我已经找到解决方案，待更新脚本，你要稍等几天，预计周末。

**Comment by fscarmen** [comment]
原来是俄罗斯的鸡，现在给 cf 制裁了，不让注册账户，我已经找到解决方案，待更新脚本，你要稍等几天，预计周末。

**Comment by fscarmen** [comment]
warp-go 已经升级支持了，你可以用该脚本安装。
