### ISSUE TITLE
[help wanted 求助]:  replit

### ISSUE THREAD

**Issue by spysoos** [fscarmen/warp#352]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

Checking VPS infomation... 
 No suitable solution was found for modifying the wgcf configuration file wgcf.conf and the script aborted. When you see this message, please send feedback on the bug to:[https://github.com/fscarmen/warp/issues] 

### Log / 日志信息

Checking VPS infomation... 
 No suitable solution was found for modifying the wgcf configuration file wgcf.conf and the script aborted. When you see this message, please send feedback on the bug to:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by spysoos** [comment]
在replite内获取到Root权限后执行

**Comment by fscarmen** [comment]
不行的，这些母鸡没有开tun，你在replit上用 proot只是在上面套个子容器的样子，你可以这样查`lsmod | grep tun`有显示 tun的才能安装wgcf

**Comment by spysoos** [comment]
了解
