### ISSUE TITLE
[help wanted 求助]: 采用菜单12选项解锁chatgpt,遇到界面一直转菊花

### ISSUE THREAD

**Issue by gc89925** [fscarmen/warp#353]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

我使用的是menu.sh V2.47 Iptables + dnsmasq + ipset solution supports chatGPT. Install via the 12 option in the menu or bash menu.sh e; Iptables + dnsmasq + ipset 方案支持 chatGPT. 安装方式: 菜单 12 选项或者 bash menu.sh e
实测可以正常登录到openai.com,但是进去以后一直转菊花，没有任何错误提示，我换其他可以解锁chatgpt的VPS节点就可以正常访问。
然后尝试使用warp i命令更换IP以后 登录界面提示We have detected suspicious login behavior and further attempts will be blocked. Please contact the administrator，不允许登录，再次反复使用warp o和warp i开启关闭，更换IP后，只能得到转菊花和不允许登录两个结果
我的vps是搬瓦工cn2 gia洛杉矶线路

### Log / 日志信息

root@beautiful-hops-2:~# warp o
 已暂停 WARP，再次开启可以用 warp o 
root@beautiful-hops-2:~# warp o
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 已成功获取 WARP 网络 
 IPv4: ( WARP IPv4 )  
 IPv6:    
root@beautiful-hops-2:~# warp i
 当前 Netflix 地区是:US，需要解锁当前地区请按 [y], 如需其他地址请输入两位地区简写 (如 hk ,sg，默认:US): u^Hs
 当前 Netflix 地区是:US，需要解锁当前地区请按 [y], 如需其他地址请输入两位地区简写 (如 hk ,sg，默认:US): US
 2023-04-19 13:32:18 区域 US 解锁成功，IPv4: ，1 小时后重新测试，刷 IP 运行时长: 0 天 0 时 0 分 9 秒 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
LA 的机器，应该没有 warp 服务, 你安装成功吗？

**Comment by gc89925** [comment]
这是我的机器beautiful-hops-2.localdomain
SPECIAL 20G KVM PROMO V5 - LOS ANGELES - CN2 GIA ECOMMERCE
确实安装成功了，之前我也用过别的脚本，的确可以解锁chatgpt.但是采用的是全局的方式，我不想全局代理，仅需要访问chatgpt走warp流量就可以了

**Comment by gc89925** [comment]
> 

刚刚又测试了一遍又可以正常访问了，总是时好时坏，不知道是否因为更换了wrap ip的原因，另外请教一下怎么查看获取到的warp ip呢？

**Comment by houchangjun1996** [comment]
我跟你的情况几乎是一样的，我用的是warp-go脚本。
打开页面转菊花，加载不出对话历史，也不能开始对话，我这里分2种情况，
1是获取到了ip，但是可能lax地区vps套warp的人太多了，你获取到的这个出口IP同时被太多人共用触发了风控之类的机制或者网络拥塞，我也经常遇到这种情况，尤其是每周一，基本是全天转。其他时间就基本可以正常打开，偶尔会无限转圈。
这种情况下，在vps上运行curl ifconfig.me --proxy socks5://127.0.0.1:40000或者curl ifconfig.me --interface WARP可以显示获取到的warp ip。如果在xray的route规则里配置了访问ip138.com之类检测ip的网站也经过warp，可以在浏览器无痕窗口里打开这些网站并看到获取的ip。

2是没获取到ip，能打开页面只是因为浏览器调用了缓存，用无痕窗口就打不开。
这种情况下，在vps上运行curl ifconfig.me --proxy socks5://127.0.0.1:40000或者curl ifconfig.me --interface WARP显示不出获取到的warp ip。如果在xray的route规则里配置了访问ip138.com之类检测ip的网站也经过warp，也无法在浏览器无痕窗口里打开这些网站。
-------------------
1这种情况以我的能力来说几乎是无解，2的话我一般会运行warp-go看一下是不是因为每天系统自动重启后，warp-go没有自动打开，一般是要手动打开。

**Comment by houchangjun1996** [comment]
我跟你的情况几乎是一样的，我用的是warp-go脚本。
打开页面转菊花，加载不出对话历史，也不能开始对话，我这里分2种情况，
1是获取到了ip，但是可能lax地区vps套warp的人太多了，你获取到的这个出口IP同时被太多人共用触发了风控之类的机制或者网络拥塞，我也经常遇到这种情况，尤其是每周一，基本是全天转。其他时间就基本可以正常打开，偶尔会无限转圈。
这种情况下，在vps上运行curl ifconfig.me --proxy socks5://127.0.0.1:40000或者curl ifconfig.me --interface WARP可以显示获取到的warp ip。如果在xray的route规则里配置了访问ip138.com之类检测ip的网站也经过warp，可以在浏览器无痕窗口里打开这些网站并看到获取的ip。

2是没获取到ip，能打开页面只是因为浏览器调用了缓存，用无痕窗口就打不开。
这种情况下，在vps上运行curl ifconfig.me --proxy socks5://127.0.0.1:40000或者curl ifconfig.me --interface WARP显示不出获取到的warp ip。如果在xray的route规则里配置了访问ip138.com之类检测ip的网站也经过warp，也无法在浏览器无痕窗口里打开这些网站。
-------------------
1这种情况以我的能力来说几乎是无解，2的话我一般会运行warp-go看一下是不是因为每天系统自动重启后，warp-go没有自动打开，一般是要手动打开。

**Comment by gc89925** [comment]
> 
感谢，感谢！原来我不是个例，那我们的情况完全一样，通过你以上的命令我获取到的warp ip是 IPv4:104.28.195.185，而且从昨天测试到今天，每次获取到的IP都是这个，确实偶尔能正常登录，但是大部分的情况都是转菊花，而且看不到历史对话记录。先这样用这吧，确实没有别的办法，再次感谢你的解惑！

**Comment by fscarmen** [comment]
不知道用 warp ipv6 会不会好点，起码 IP 多得多，不易重复。

**Comment by houchangjun1996** [comment]
> > 
> 
> 感谢，感谢！原来我不是个例，那我们的情况完全一样，通过你以上的命令我获取到的warp ip是 IPv4:104.28.195.185，而且从昨天测试到今天，每次获取到的IP都是这个，确实偶尔能正常登录，但是大部分的情况都是转菊花，而且看不到历史对话记录。先这样用这吧，确实没有别的办法，再次感谢你的解惑！

我跟你是同一个出口ip，刚才测试了一下是可以正常访问的，建议用warp-go o断开warp的连接，重启vps再重新用warp-go o打开，或者直接转换成free账户，获取的ip可能会变化。再要么就把warp和warp-go都卸了再重装，看获取的ip会不会变化。

**Comment by gc89925** [comment]
我刚刚查了一下昨天的记录发现昨天获取到的warp IP是104.28.227.185,看来还是有变化的，中间我重装了好多次系统，今天反复测试获取到的都是同一个IP,不过现在也确实可以正常访问了，不知道到了晚上会不会又开始报错，上面作者本人也回复了，我晚点测试一下IPV6试试看会不会好点。

**Comment by gc89925** [comment]
> 不知道用 warp ipv6 会不会好点，起码 IP 多得多，不易重复。

即使本机没有IPV6地址，也可以申请用ipv6去访问chatgpt吗？我晚点试试，现在目前可以正常使用了，谢谢您的回复

**Comment by gc89925** [comment]
> 不知道用 warp ipv6 会不会好点，起码 IP 多得多，不易重复。
用ipv6返回这个结果
root@beautiful-hops-2:~# curl ifconfig.me --interface wgcf
curl: (7) Failed to connect to ifconfig.me port 80: No route to host

**Comment by fscarmen** [comment]
强制使用v6试试
```
curl -s6m8 ifconfig.me --interface wgcf
```

**Comment by jokerElsa** [comment]
> > 
> 
> 刚刚又测试了一遍又可以正常访问了，总是时好时坏，不知道是否因为更换了wrap ip的原因，另外请教一下怎么查看获取到的warp ip呢？
> 
> 过了10分钟再次打开又出现We have detected suspicious login behavior and further attempts will be blocked. Please contact the administrator

这两天同样菊花，插个眼。弱弱问下，获取到的ip不是跑下脚本就能看到吗。。。

**Comment by josephzjw** [comment]
我用的是warp-go，然后改成了ipv6，发现可以上chagpt了

**Comment by jokerElsa** [comment]
> 

ipv6是不是要全局啊。非全局好像不能双栈

**Comment by jokerElsa** [comment]
> 我用的是warp-go，然后改成了ipv6，发现可以上chagpt了

我用的也是go但是用的非全局

**Comment by PP-19** [comment]
> 强制使用v6试试
> 
> ```
> curl -s6m8 ifconfig.me --interface wgcf
> ```

用warp client proxy模式，在xray里设置分流出站访问chatgpt，也是转圈
昨天用了这个命令能正常访问，今天晚上又开始转圈了
直接用脚本的前三个选项添加warp网络接口倒是一直能正常访问

**Comment by josephzjw** [comment]
> > 我用的是warp-go，然后改成了ipv6，发现可以上chagpt了
> 
> 
> 
> 我用的也是go但是用的非全局

我不知道我是不是全局。这应该在哪里看？

**Comment by jokerElsa** [comment]
> > > 我用的是warp-go，然后改成了ipv6，发现可以上chagpt了
> > 
> > 
> > 我用的也是go但是用的非全局
> 
> 我不知道我是不是全局。这应该在哪里看？

用warp-go 跑脚本会写运行在非全局还是全局模式，里面很多内容都有，是否双栈及对应ip。
想要个非全局ipv6。。ipv4的ip估计已经被滥用了各种转圈。

**Comment by houchangjun1996** [comment]
现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。
把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了

**Comment by Ezi1h** [comment]
> 强制使用v6试试
> 
> ```
> curl -s6m8 ifconfig.me --interface wgcf
> ```

我用上面命令直接没返回值，用的是双栈模式，这应该是全局模式吧？现在是能登录，但是就是转菊花，怎么看我本地访问走没走ipv6地址呢？
```sh
脚本版本:2.49
 功能新增:1. warp endpoint 优选改为标准端口 [500,1701,2408,4500]; 2. 升级奈飞解锁部分
 系统信息:
         当前操作系统:Ubuntu 22.04 LTS
         内核:5.15.0-25-generic
         处理器架构:amd64
         虚拟化:kvm
         IPv4: 104.28.195.185 ( WARP Teams IPv4 ) 美国  Cloudflare
         IPv6: 2a09:bac5:624a:1846::26b:7e ( WARP Teams IPv6 ) 美国  Cloudflare
         WARP Teams 网络接口已开启
         Client 未安装
         WireProxy 未安装
root@tt:~# curl -s6m8 ifconfig.me --interface wgcf
root@tt:~#
```

**Comment by Ezi1h** [comment]
> 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了


dns块删除指的是什么？发现有dns配置的json，是下面这样的，需要删除么，用的[mack-a八合一脚本](https://github.com/mack-a/v2ray-agent)

```sh
root@tt:~# cat /etc/v2ray-agent/xray/conf/11_dns.json
{
    "dns": {
        "servers": [
          "localhost"
        ]
  }
}
```

**Comment by houchangjun1996** [comment]
> > 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了
> 
> dns块删除指的是什么？发现有dns配置的json，是下面这样的，需要删除么，用的[mack-a八合一脚本](https://github.com/mack-a/v2ray-agent)
> 
> ```shell
> root@tt:~# cat /etc/v2ray-agent/xray/conf/11_dns.json
> {
>     "dns": {
>         "servers": [
>           "localhost"
>         ]
>   }
> }
> ```

这个方法仅对搬瓦工搬瓦工港日美西的vps有效，其他厂商的主机无效。
这一段如果servers只有localhost，那一般来说改hosts文件然后重启vps就行了，如果还有别的dns服务器，我建议直接把这一整段都删掉，反正对我等小白来说，这个内建的dns有与没有似乎没啥影响。

**Comment by Ezi1h** [comment]
> > > 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了
> > 
> > 
> > dns块删除指的是什么？发现有dns配置的json，是下面这样的，需要删除么，用的[mack-a八合一脚本](https://github.com/mack-a/v2ray-agent)
> > ```shell
> > root@tt:~# cat /etc/v2ray-agent/xray/conf/11_dns.json
> > {
> >     "dns": {
> >         "servers": [
> >           "localhost"
> >         ]
> >   }
> > }
> > ```
> 
> 这个方法仅对搬瓦工搬瓦工港日美西的vps有效，其他厂商的主机无效。 这一段如果servers只有localhost，那一般来说改hosts文件然后重启vps就行了，如果还有别的dns服务器，我建议直接把这一整段都删掉，反正对我等小白来说，这个内建的dns有与没有似乎没啥影响。

我就瓦工dc6 la的机房，一会我试试~

**Comment by Ezi1h** [comment]
> > > > 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了
> > > 
> > > 
> > > dns块删除指的是什么？发现有dns配置的json，是下面这样的，需要删除么，用的[mack-a八合一脚本](https://github.com/mack-a/v2ray-agent)
> > > ```shell
> > > root@tt:~# cat /etc/v2ray-agent/xray/conf/11_dns.json
> > > {
> > >     "dns": {
> > >         "servers": [
> > >           "localhost"
> > >         ]
> > >   }
> > > }
> > > ```
> > 
> > 
> > 这个方法仅对搬瓦工搬瓦工港日美西的vps有效，其他厂商的主机无效。 这一段如果servers只有localhost，那一般来说改hosts文件然后重启vps就行了，如果还有别的dns服务器，我建议直接把这一整段都删掉，反正对我等小白来说，这个内建的dns有与没有似乎没啥影响。
> 
> 我就瓦工dc6 la的机房，一会我试试~

@houchangjun1996 兄弟nb，加了hosts确实可以了，感谢！

**Comment by gc89925** [comment]
> 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了

实测可行，warp都不用改了，直接改host就ok了，感谢！！

**Comment by mymolasses** [comment]
> 

老哥太牛了吧，这是从哪找到的

**Comment by mymolasses** [comment]
> 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。
> 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了

老哥太牛了吧，这是从哪找到的

**Comment by FikaCode** [comment]
> 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了

而你，我的朋友。你是真正的神。

**Comment by wsspsb** [comment]
> 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了

强啊兄弟  请问怎么来的ip  不知道能用多久  下次如果失效了我能自己找吗

**Comment by mymolasses** [comment]
> > 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了
> 
> 强啊兄弟 请问怎么来的ip 不知道能用多久 下次如果失效了我能自己找吗

同问！！

**Comment by kailpony** [comment]
> [justmysocks](https://justmysocks.net/members/knowledgebase.php?action=displayarticle&id=15?aff=26762)（此链接带aff）,瓦工官方的代理最近公告支持chatgpt

**Comment by kailpony** [comment]
> > > 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了
> > 
> > 
> > 强啊兄弟 请问怎么来的ip 不知道能用多久 下次如果失效了我能自己找吗
> 
> 同问！！

[justmysocks](https://justmysocks.net/members/knowledgebase.php?action=displayarticle&id=15?aff=26762)(此链接带aff），瓦工官方的代理最近宣布支持chatgpt，warp ipv6确实好很多，ipv4烂了，现在已经转圈，error429

**Comment by gitluci58** [comment]
> 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了

请受小弟一拜

**Comment by houchangjun1996** [comment]
> 

据说是dns解锁，仅适用于瓦工的主机。有的机房会自动转换，大部分需要自己手动改hosts才行。这是个内网保留地址，估计是不能自己找或者编。

**Comment by dengenergy** [comment]
> 现在搬瓦工主机有了解决方案，搬瓦工港日美西主机可以直接通过改hosts文件访问chatgpt。 把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com，然后如果/etc/v2ray/config.json里有dns块，则删除，重启vps就可以了

牛逼啊，我是搬瓦工的服务器，直接把/etc/hosts这个文件里加上172.31.255.2 chat.openai.com。这样操作就可以访问chatgpt了，这是我见过最朴素最有效果的。

**Comment by shandongtlb** [comment]
racknerd la mc机房之前还好好的，今天也不行了

**Comment by gadfly0x** [comment]
我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.

**Comment by houchangjun1996** [comment]
> 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.

此方法仅对搬瓦工主机有效，目前还没有听说改了hosts不能直连的情况，除非你改错了

**Comment by l123456789jy** [comment]
https://www.youtube.com/watch?v=FejpkSyRqko  操作视频

**Comment by FikaCode** [comment]
> 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.

只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。

**Comment by departurechen** [comment]
怎么去掉服务器dns设置，在哪呢

**Comment by departurechen** [comment]
> > 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.
> 
> 只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。

怎么去掉dns配置啊，在可否说详细点，在哪输入什么指令？谢谢大神

**Comment by departurechen** [comment]
> 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.

一样我也是这样

**Comment by departurechen** [comment]
> 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.

我也是

**Comment by FikaCode** [comment]
> > > 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.
> > 
> > 
> > 只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。
> 
> 怎么去掉dns配置啊，在可否说详细点，在哪输入什么指令？谢谢大神

目前服务器使用v2或者xray，在配置文件里面，一般在 /etc/v2ray/config.json 或者  /usr/local/etc/xray/config.json（按照自己服务器的位置来找），在配置文件里面删除 dns 的标签，比如我的只剩下 log inbounds outbounds 三个标签，然后重启服务v2服务。电脑客户端v2rayn 参数设置 把自定义dns 删除掉。手机端 v2rayNg 设置 启用本地dns 的勾去掉，vpn dns 已经设置的地址删掉。

**Comment by founderqiang** [comment]
> > 强制使用v6试试
> > ```
> > curl -s6m8 ifconfig.me --interface wgcf
> > ```
> 
> 用warp client proxy模式，在xray里设置分流出站访问chatgpt，也是转圈 昨天用了这个命令能正常访问，今天晚上又开始转圈了 直接用脚本的前三个选项添加warp网络接口倒是一直能正常访问

请问如何直接用脚本的前三个选项添加warp网络接口倒是一直能正常访问

**Comment by fscarmen** [comment]
可能该IP太多人共用了

**Comment by 2shou** [comment]
> > > > 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.
> > > 
> > > 
> > > 只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。
> > 
> > 
> > 怎么去掉dns配置啊，在可否说详细点，在哪输入什么指令？谢谢大神
> 
> 目前服务器使用v2或者xray，在配置文件里面，一般在 /etc/v2ray/config.json 或者 /usr/local/etc/xray/config.json（按照自己服务器的位置来找），在配置文件里面删除 dns 的标签，比如我的只剩下 log inbounds outbounds 三个标签，然后重启服务v2服务。电脑客户端v2rayn 参数设置 把自定义dns 删除掉。手机端 v2rayNg 设置 启用本地dns 的勾去掉，vpn dns 已经设置的地址删掉。

@FikaCode 改了之后还是连不上，ERR_CONNECTION_CLOSED

**Comment by houchangjun1996** [comment]
> > > > > 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.
> > > > 
> > > > 
> > > > 只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。
> > > 
> > > 
> > > 怎么去掉dns配置啊，在可否说详细点，在哪输入什么指令？谢谢大神
> > 
> > 
> > 目前服务器使用v2或者xray，在配置文件里面，一般在 /etc/v2ray/config.json 或者 /usr/local/etc/xray/config.json（按照自己服务器的位置来找），在配置文件里面删除 dns 的标签，比如我的只剩下 log inbounds outbounds 三个标签，然后重启服务v2服务。电脑客户端v2rayn 参数设置 把自定义dns 删除掉。手机端 v2rayNg 设置 启用本地dns 的勾去掉，vpn dns 已经设置的地址删掉。
> 
> @FikaCode @houchangjun1996 改了之后还是连不上，ERR_CONNECTION_CLOSED

以下这些工作做完就可以正常访问chatgpt了，如果还连不上只能说明操作有误。至于具体操作请自行百度，这些代码都不复杂，仔细观看分析，我这种文科生都看得懂。
1. 这个方法仅对搬瓦工主机有用
2. 改hosts文件
3. 去掉v2ray/xray的config.json文件里的dns配置，注意在https://www.json.cn/检查修改后的代码是否正确
4. 重启vps
5. 去掉客户端的自定义dns配置，重启服务

**Comment by FikaCode** [comment]
> > > > > 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.
> > > > 
> > > > 
> > > > 只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。
> > > 
> > > 
> > > 怎么去掉dns配置啊，在可否说详细点，在哪输入什么指令？谢谢大神
> > 
> > 
> > 目前服务器使用v2或者xray，在配置文件里面，一般在 /etc/v2ray/config.json 或者 /usr/local/etc/xray/config.json（按照自己服务器的位置来找），在配置文件里面删除 dns 的标签，比如我的只剩下 log inbounds outbounds 三个标签，然后重启服务v2服务。电脑客户端v2rayn 参数设置 把自定义dns 删除掉。手机端 v2rayNg 设置 启用本地dns 的勾去掉，vpn dns 已经设置的地址删掉。
> 
> @FikaCode @houchangjun1996 改了之后还是连不上，ERR_CONNECTION_CLOSED

试试再服务器上ping chat.openai.com ,查看解析的地址是否正确，172.31.255.2 是否ping的通，这个地址貌似是局域网地址，只在搬瓦工的服务器上才ping的通。应该说只要是搬瓦工的机子加了这个应该都没问题才对，据我所知应该没有人失败才对。电脑端的v2rayn 我甚至没改配置就正常了，只是手机端v2rayNG 开始不能访问，但是去设置里面去掉本地dns 也就正常了。

**Comment by 2shou** [comment]
> 

搬瓦工可以ping通，但是电脑端还是无法访问

**Comment by departurechen** [comment]
> > 
> 
> 搬瓦工可以ping通，但是电脑端还是无法访问 v2ray的日志显示accepted tcp:chat.openai.com:443 [blocked] @houchangjun1996
> 
> 已解决，是配置中我把privateip给block了，感谢！

哥们，没听懂啊，可否说详细点，具体怎么操作啊？

**Comment by departurechen** [comment]
> > > > > > 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.
> > > > > 
> > > > > 
> > > > > 只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。
> > > > 
> > > > 
> > > > 怎么去掉dns配置啊，在可否说详细点，在哪输入什么指令？谢谢大神
> > > 
> > > 
> > > 目前服务器使用v2或者xray，在配置文件里面，一般在 /etc/v2ray/config.json 或者 /usr/local/etc/xray/config.json（按照自己服务器的位置来找），在配置文件里面删除 dns 的标签，比如我的只剩下 log inbounds outbounds 三个标签，然后重启服务v2服务。电脑客户端v2rayn 参数设置 把自定义dns 删除掉。手机端 v2rayNg 设置 启用本地dns 的勾去掉，vpn dns 已经设置的地址删掉。
> > 
> > 
> > @FikaCode @houchangjun1996 改了之后还是连不上，ERR_CONNECTION_CLOSED
> 
> 以下这些工作做完就可以正常访问chatgpt了，如果还连不上只能说明操作有误。至于具体操作请自行百度，这些代码都不复杂，仔细观看分析，我这种文科生都看得懂。
> 
> 1. 这个方法仅对搬瓦工主机有用
> 2. 改hosts文件
> 3. 去掉v2ray/xray的config.json文件里的dns配置，注意在   ((https://www.json.cn))  检查修改后的代码是否正确
> 4. 重启vps
> 5. 去掉客户端的自定义dns配置，重启服务

为何我没有这俩个路径啊？ 是空的 /etc/v2ray/config.json 或者 /usr/local/etc/xray/config.json

**Comment by departurechen** [comment]
现在又不行了，能登陆进去，不转菊花，但是看不到历史记录，也不能输入指令，求大佬告知详细解决方法。谢谢。改host，走ipv6什么的都试过了不行.

**Comment by zygame** [comment]
> > > > > > 我加了172.31.255.2 chat.openai.com后，就无法访问：This site can’t be reachedchat.openai.com unexpectedly closed the connection.
> > > > > 
> > > > > 
> > > > > 只限于搬瓦工，服务器的dns 配置要去掉，然后手机端app 的使用本地dns 也要去掉。
> > > > 
> > > > 
> > > > 怎么去掉dns配置啊，在可否说详细点，在哪输入什么指令？谢谢大神
> > > 
> > > 
> > > 目前服务器使用v2或者xray，在配置文件里面，一般在 /etc/v2ray/config.json 或者 /usr/local/etc/xray/config.json（按照自己服务器的位置来找），在配置文件里面删除 dns 的标签，比如我的只剩下 log inbounds outbounds 三个标签，然后重启服务v2服务。电脑客户端v2rayn 参数设置 把自定义dns 删除掉。手机端 v2rayNg 设置 启用本地dns 的勾去掉，vpn dns 已经设置的地址删掉。
> > 
> > 
> > @FikaCode @houchangjun1996 改了之后还是连不上，ERR_CONNECTION_CLOSED
> 
> 以下这些工作做完就可以正常访问chatgpt了，如果还连不上只能说明操作有误。至于具体操作请自行百度，这些代码都不复杂，仔细观看分析，我这种文科生都看得懂。
> 
> 1. 这个方法仅对搬瓦工主机有用
> 2. 改hosts文件
> 3. 去掉v2ray/xray的config.json文件里的dns配置，注意在   ((https://www.json.cn))  检查修改后的代码是否正确
> 4. 重启vps
> 5. 去掉客户端的自定义dns配置，重启服务

172.31.255.2 原来是这个用处，我的VPS也是瓦工的GIA-E，Xray一直是block private ip，就一直上不去，我在机器上nslookup了一下发现是个A类私有，还在纳闷怎么回事，在机器的默认DNS resolv里看到有这个IP，随手删了就能用了，看来如果真出问题还得加回去……
