### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by houchangjun1996** [fscarmen/warp#355]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

系统reboot后warp-go应该自动打开，而实际上需要手动打开

脚本版本: 1.1.3
系统信息:
当前操作系统: Ubuntu 18.04 LTS
内核: 4.15.0-20-generic
处理器架构: amd64v2
虚拟化: kvm
每次reboot后warp-go不会自动启动，手动输入warp-go并运行会显示：4. 打开warp-go (warp-go o)

尝试采取的策略：
要在 Ubuntu 系统重启后自动运行 warp-o 命令，您可以按照以下步骤进行操作：
创建一个新的服务文件 /etc/systemd/system/warp-go o.service，使用以下命令：
sudo nano /etc/systemd/system/warp-go o.service
将以下内容粘贴到编辑器中：
[Unit]
Description=warp-go o Command
After=network-online.target
[Service]
User=root
ExecStart=/usr/local/bin/warp-go o
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
按 Ctrl + X 保存并退出编辑器。
执行以下命令，启用该服务并在系统重启时自动启动它：
sudo systemctl enable warp-go o.service
现在，每次重启 Ubuntu 后，warp-o 命令将自动运行。
后果：系统重启后不仅没有自动打开warp-go，而且手动运行warp-go o也因无法获取ip而启动失败
目前已删除了此服务，每次在系统重启后手动运行warp-go o

复现方法
仅安装warp-go脚本，未安装warp脚本（输入并执行warp时提示-bash: warp: command not found）
使用reboot命令重启Ubuntu 18.04 LTS

### Log / 日志信息

没有在/opt/warp-go/文件夹中找到log文件

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
1.脚本已经有一个systemd已经登陆了 `systemctl is-enabled warp-go` 看看是不是 enabled
2.你的服务文件中间有空格的？` /etc/systemd/system/warp-go o.service`

**Comment by houchangjun1996** [comment]
> 1.脚本已经有一个systemd已经登陆了 `systemctl is-enabled warp-go` 看看是不是 enabled 2.你的服务文件中间有空格的？` /etc/systemd/system/warp-go o.service`

谢谢，已经根据你的提醒解决了。
