### ISSUE TITLE
[help wanted 求助]: 提示Team用户不可用，但是在安卓模拟器里可以用

### ISSUE THREAD

**Issue by yunyuyuan** [fscarmen/warp#356]
### Script / 脚本

menu.sh

### OS / 操作系统

Arch - Linux

### Actual Situation / 实际情况

![image](https://user-images.githubusercontent.com/45785585/233260880-e2075906-01ca-4142-a6ac-f11d3857eb4a.png)
![image](https://user-images.githubusercontent.com/45785585/233260962-1a32be6d-5402-4da3-b8f9-48d5ab0934e0.png)

### Log / 日志信息

当前 Teams 账户不可用，自动切换回免费账户

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by yunyuyuan** [comment]
解决了，是因为我在模拟器上logout了一次，导致key失效了估计，重新`adb pull`然后更新gist就行了

**Comment by fscarmen** [comment]
太好了，你不说，我还不知道为什么呢？因为我登陆了，提取文件就没有管模拟器上面的了，另外问一下，你现在用的1.1.1.1是什么版本的？仍然能提取配置文件的

**Comment by yunyuyuan** [comment]
@fscarmen 我用你在readme里写的啊，V6.10，最新都没有Team这个菜单了
