### ISSUE TITLE
无法获取warp Ip-【结论：2023.5.10 warp-go V1.1.4 对接 warp-go 官方账户池 api，已处理，请重新下载并安装】

### ISSUE THREAD

**Issue by gaoningguo** [fscarmen/warp#357]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

<img width="893" alt="image" src="https://user-images.githubusercontent.com/112529571/233416603-af97a1e5-0d58-4ba6-9300-c4b2df1ff8dc.png">

### Log / 日志信息

注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 第2次尝试 
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.
 第3次尝试 
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.
 第4次尝试 
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.
 第5次尝试 
Job for warp-go.service failed because the control process exited with error code.
See "systemctl status warp-go.service" and "journalctl -xeu warp-go.service" for details.

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
`systemctl daemon-reload; warp-go o`
看看

**Comment by madmole1** [comment]
@gaoningguo 你安装的时候用的哪个方案？有一些方案对内核版本有要求。

**Comment by jinwyp** [comment]
warp-go.sh 已经无法获取到任何IP了， 只能用其他方案了

**Comment by V4444** [comment]
我也不行了，无法获取ip

**Comment by jokerElsa** [comment]
我的warp-go也是无法获取到各种ip了，和机器好像也有关系，昨天另一个机器就可以

**Comment by fscarmen** [comment]
2023.5.10 warp-go V1.1.4

1. Docking the warp-go official account pool api, wiki: https://docs.zeroteam.top/apis/warp; 
2. Change non-global from ipv4 only to dualstacks; 
3. Fix the bug that the native IPv6 cannot login when using dualstacks; 
4. Update the Best-enpoint app; 
5. Change ip api;  </br>

1. 对接 warp-go 官方账户池 api，wiki: https://docs.zeroteam.top/apis/warp; 
2. 非全局从ipv4 only 改为双栈; 
3. 修复双栈时使用原生 IPv6 不能登陆的 bug; 
4. 更新最佳 Endpoint 应用; 
5. 更换 ip api
