### ISSUE TITLE
[help wanted 求助]: 请问下能否自定义刷奈飞时间段间隔

### ISSUE THREAD

**Issue by lzhqweq1** [fscarmen/warp#358]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

脚本显示的默认时间间隔是1小时检测一次，但往往没有到1小时刷到的IP就只能看自制剧了。请问下有没有修改默认检测时间的方法呢，谢谢

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你好，我没有弄交互了，就是不想老出问题让用户选择或者填写，你在脚本 /etc/wireguard/menu.sh 把 sleep 1h 改为你想要的时间吧

**Comment by lzhqweq1** [comment]
谢谢解答哈~我去试一下

**Comment by lzhqweq1** [comment]
您好，我搜索了一下，一共有四个 sleep 1h 的位置，不知道修改为 sleep 0.1h 这样是否符合脚本的要求呢
