### ISSUE TITLE
[help wanted 求助]: Mac OS:Ventura(13.2.1) support

### ISSUE THREAD

**Issue by snow6784** [fscarmen/warp#359]
### Script / 脚本

menu.sh

### OS / 操作系统

Mac AMD64

### Actual Situation / 实际情况

Is there a version of that Script suitable for the MAC OS(Intel),Ventura(13.2.1)?
Thank you for your answer.

### Log / 日志信息

 The script supports Debian, Ubuntu, CentOS, Arch or Alpine systems only. Feedback: [https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
I made a scripts a year ago. https://github.com/fscarmen/warp/tree/main/pc   
But it doesn't seem to be working right now, so why not use 1.1.1.1 instead.

**Comment by snow6784** [comment]
I've tried your scripts "https://github.com/fscarmen/warp//main/pc", but i could only get an VPS IP with China. I want get en VPS IP to use chatgpt, so it also can't connected to chatgpt.
Do you have any other solutions?
----- 原始邮件 -----
发件人：fscarmen ***@***.***>
收件人：fscarmen/warp ***@***.***>
抄送人：snow6784 ***@***.***>,  Author ***@***.***>
主题：Re:_[fscarmen/warp]_[help_wanted_求助]:_Mac_OS:Ventura(13.2.1)_support_(Issue_#359)
日期：2023年04月21日 22点15分


I made a scripts a year ago. https://github.com/fscarmen/warp//main/pc

But it doesn't seem to be working right now, so why not use 1.1.1.1 instead.

**Comment by fscarmen** [comment]
Please use v2ray / x2ray / hysteria to connect your remote vps . Or visit https://poe.com/ChatGPT instead of ai.com
