### ISSUE TITLE
nat机子，启用后仅能ssh，网页端无法访问，搭的节点也断掉了，

### ISSUE THREAD

**Issue by zhaozhejun** [fscarmen/warp#36]
nat机子，启用后仅能ssh，网页端无法访问，搭的节点也断掉了，

启用的第一个，并监测奈飞

能给分析下什么原因吗

**Comment by fscarmen** [comment]
情况说太有点笼统，```warp o``` 关断 WARP 之后看是否正常了。

**Comment by zhaozhejun** [comment]
> 情况说太过笼统，`warp o` 关断 WARP 之后看是否正常了。

关闭后 恢复正常，，只安装了lkl-proxy

**Comment by zhaozhejun** [comment]
另一个问题，screen下，，运行menu，中文显示不正常，英文没问题。

**Comment by fscarmen** [comment]
> 另一个问题，screen下，，运行menu，中文显示不正常，英文没问题。

这么奇怪？不在 screen下中文正常，在screen下就不正常了？

**Comment by zhaozhejun** [comment]
![微信图片_20211210175045](https://user-images.githubusercontent.com/22097252/145554040-303cb7dc-3d8e-41d7-a6aa-01bf8757b86f.png)
我也很奇怪，所以换了 debian11、10、ubuntu20，都是显示有问题。。搞不好这 印度鸡系统就是有问题的。。
好像找到问题了。。这次重装 没安装lkl-proxy，启用warp后网络正常。

 Try 2. IPv4: 8.38.147.57 Singapore CLOUDFLARENET. Retest after 3 seconds.
还有个问题，监测奈飞，这个能修改时间吗？默认这应该是 3秒监测一次？

**Comment by fscarmen** [comment]
中文乱码的话，你试试输入```export LANG="en_US";export LANGUAGE="en_US"```
lkl-proxy 不建议安装，这个for openvz bbr没有效果的，我印象中也很久很久没有更新了

> 还有个问题，监测奈飞，这个能修改时间吗？默认这应该是 3秒监测一次？
现在的机制是刷不出奈飞适用IP就3秒后重新获取，不能太快，太急反而有时候出问题
当刷到奈飞IP后，保持60秒再刷

**Comment by fscarmen** [comment]
> 还有个问题，监测奈飞，这个能修改时间吗？默认这应该是 3秒监测一次？

哈哈，我的问题，解锁失败显示是红色的，3秒后重试，我英文提示忘记加 : Failed （今晚一并更新处理）
如果解锁成功显示是绿色的，60秒后重试

**Comment by zhaozhejun** [comment]
> > 还有个问题，监测奈飞，这个能修改时间吗？默认这应该是 3秒监测一次？
> 
> 哈哈，我的问题，解锁失败显示是红色的，3秒后重试，我英文提示忘记加 : Failed （今晚一并更新处理） 如果解锁成功显示是绿色的，60秒后重试
对 我的意思，这个60秒，能改的延长点吗？例如一小时监测一次，失败3秒仍不变，好像奈飞的策略据说 改成6小时一检测了

**Comment by zhaozhejun** [comment]
> export LANG="en_US";export LANGUAGE="en_US"

这个命令 输完 中文 仍如图显示，估计还是系统模板有问题。英文反正不影响使用。

**Comment by fscarmen** [comment]
> 对 我的意思，这个60秒，能改的延长点吗？例如一小时监测一次，失败3秒仍不变，好像奈飞的策略据说 改成6小时一检测了

可以的，我再结合其他用户看看改多少合适。说话你试 ```export LANG="en_US";export LANGUAGE="en_US"``` ，看印度机器是否可以显示正常的中文？

**Comment by zhaozhejun** [comment]
仍一样，screen模式下显示中文不完美如之前发的图。非screen显示没问题。哈哈，目前就是看不懂的正常模式下拍个图片，再进screen去运行。也不耽误事儿。

那就得后期60秒再度监测的调整了。无问题，我先关闭问题了

**Comment by fscarmen** [comment]
我在德鸡上安装lkl的加速没有问题

**Comment by fscarmen** [comment]
> 对 我的意思，这个60秒，能改的延长点吗？例如一小时监测一次，失败3秒仍不变，好像奈飞的策略据说 改成6小时一检测了

现在已经把时间从60秒改为1小时了，显示那里我也处理了一下 ，```export LANG=en_US.UTF-8``` ，你再试试会不会乱码呢？

**Comment by zhaozhejun** [comment]
> > 对 我的意思，这个60秒，能改的延长点吗？例如一小时监测一次，失败3秒仍不变，好像奈飞的策略据说 改成6小时一检测了
> 
> 现在已经把时间从60秒改为1小时了，显示那里我也处理了一下 ，`export LANG=en_US.UTF-8` ，你再试试会不会乱码呢？

仍一样，screen模式 与正常模式下，中文显示就是不对，
![微信截图_20211213103153](https://user-images.githubusercontent.com/22097252/145743897-00aed3f6-9191-415f-a7c9-1938265d603b.png)
![微信截图_20211213103737](https://user-images.githubusercontent.com/22097252/145743900-a1f9c3e2-8b57-443d-9e02-3f95215195d3.png)

**Comment by fscarmen** [comment]
> screen模式 与正常模式下

在screen下先输入 ```export LANG=en_US.UTF-8``` ，再看看
另外1小时那里你要  ```warp v``` 来升级才能改为1小时的，不用重新刷脚本

**Comment by fscarmen** [comment]
> 仍一样，screen模式 与正常模式下，中文显示就是不对，

我复现了 screen 下中文乱码的问题并解决了，请在screen 之前运行
```echo -e "defutf8 on\ndefencoding utf8\nencoding UTF-8 UTF-8" >> $(whereis screenrc | cut -d : -f2)```

**Comment by zhaozhejun** [comment]
> > 仍一样，screen模式 与正常模式下，中文显示就是不对，
> 
> 我复现了 screen 下中文乱码的问题并解决了，请在screen 之前运行 `echo -e "defutf8 on\ndefencoding utf8\nencoding UTF-8 UTF-8" >> $(whereis screenrc | cut -d : -f2)`

刚注意到，，测试完毕，，确实解决中文显示问题。。感谢感谢。。

**Comment by fscarmen** [comment]
> > > 仍一样，screen模式 与正常模式下，中文显示就是不对，
> 
> > 
> 
> > 我复现了 screen 下中文乱码的问题并解决了，请在screen 之前运行 `echo -e "defutf8 on\ndefencoding utf8\nencoding UTF-8 UTF-8" >> $(whereis screenrc | cut -d : -f2)`
> 
> 
> 
> 刚注意到，，测试完毕，，确实解决中文显示问题。。感谢感谢。。

有更简单方法，screen -U，超神
