### ISSUE TITLE
[help wanted 求助]: 已有 warp unlimited 帐号，如果获取 warp 链式配置

### ISSUE THREAD

**Issue by enerai** [fscarmen/warp#361]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

    "outbounds":[
        {
            "protocol":"freedom"
        },
        {
            "tag":"WARP",
            "protocol":"wireguard",
            "settings":{
                "secretKey":"cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=",
                "address":[
                    "172.16.0.2/32",
                    "fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128"
                ],
                "peers":[
                    {
                        "publicKey":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "endpoint":"engage.cloudflareclient.com:2408"
                    }
                ]
            }
        }
    ],

看到说明文档里面有这种方式去解锁ChatGPT，最近开通了unlimited订阅，但是不知道在哪里获取 secretKey address publicKey 这三个对应的 warp 参数

### Log / 日志信息

.

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
先停了 xray ，具体如何停要看你的项目了，更换以下的

<img width="648" alt="image" src="https://user-images.githubusercontent.com/62703343/233764342-f59a3870-ea87-4359-8e09-78034315d499.png">

**Comment by enerai** [comment]
我是在iOS上面通过内购开启的cloudflare warp unlimited，下一步是在哪里可以得到 secretKey 和可用的 v6

**Comment by fscarmen** [comment]
不会

**Comment by enerai** [comment]
> 

昨天挖了下，先用 warp-cli account 登录unlimited帐号，然后在vps上面搜cloudflare-warp文件夹，里面有配置文件，当中包含对应的secretKey和address

**Comment by fscarmen** [comment]
我还以下你在手机上获取先，那些通过 loon qx surge 等相应的插件可以获取，但比较难写教程了。

vps 上 client 的注册文件在 /var/lib/cloudflare-warp/ ，里面有 conf.json  reg.json

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/62703343/233818478-c3500782-2dba-48be-aa07-30805d9784f9.png">

**Comment by enerai** [comment]
> 我还以下你在手机上获取先，那些通过 loon qx surge 等相应的插件可以获取，但比较难写教程了。
> 
> vps 上 client 的注册文件在 /var/lib/cloudflare-warp/ ，里面有 conf.json reg.json
> 
> <img alt="image" width="1131" src="https://user-images.githubusercontent.com/62703343/233818478-c3500782-2dba-48be-aa07-30805d9784f9.png">

感谢告知！
