### ISSUE TITLE
使用Amazon云服务器安装报错[help wanted 求助]: 

### ISSUE THREAD

**Issue by y3534365** [fscarmen/warp#362]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

安装提示报错

### Log / 日志信息

所有依赖已存在，不需要额外安装 

 检查环境中…… 
grep: warning: stray \ before 0
grep: warning: stray \ before /
grep: warning: stray \ before :
grep: warning: stray \ before :
grep: warning: stray \ before /
grep: warning: stray \ before 0
grep: warning: stray \ before /
grep: warning: stray \ before :
grep: warning: stray \ before :
grep: warning: stray \ before /
Failed to restart wg-quick@wgcf.service: Unit wg-quick@wgcf.service not found.
 没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
判断不出来，这个 grep 命令报错了，你试试重新安装
```
apt upate; apy install -y grep
```
