### ISSUE TITLE
[Bug]: 使用脚本开v4直接啥也干不了，warp指令也出不来了，下载也不行，没网了

### ISSUE THREAD

**Issue by hyyxiaoluo** [fscarmen/warp#363]
### Expectation / 预期情况

正常使用

### Actual Situation / 实际情况

在使用一键脚本后目前直接卡在创建warp的v4界面，一直卡着，后来我直接重启了还是不行，warp指令输入也是没反应，下载其他的东西也下载不了，直接废了，怎么办，重启也没解决啊

### Reproduction Method / 复现方法

执行wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh [option] [lisence]目前也是不行

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
`bash menu.sh u` 卸载看看

**Comment by hyyxiaoluo** [comment]
好的谢谢建议，我已经重新开了一台，那台重启完还是那样我就换了，遇到的话试试你的
