### ISSUE TITLE
[help wanted 求助]: Temporary failure resolving 'deb.debian.org'-【结论：改源地址，问题解决】

### ISSUE THREAD

**Issue by lmhg666** [fscarmen/warp#364]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

菜单选项12最后提示如下
没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。

### Log / 日志信息

Temporary failure resolving 'deb.debian.org'
Ign:16 https://deb.debian.org/debian bullseye/main amd64 libavahi-client3 amd64 0.8-5+deb11u1
Ign:2 https://debian.mirror.constant.com bullseye/main amd64 libgdk-pixbuf2.0-common all 2.42.2+dfsg-1+deb11u1
Ign:17 https://deb.debian.org/debian bullseye/main amd64 libpixman-1-0 amd64 0.40.0-1.1~deb11u1
Ign:3 https://debian.mirror.constant.com bullseye/main amd64 libgdk-pixbuf-2.0-0 amd64 2.42.2+dfsg-1+deb11u1
Ign:18 https://deb.debian.org/debian bullseye/main amd64 libxcb-render0 amd64 1.14-3
Err:4 https://debian.mirror.constant.com bullseye/main amd64 gtk-update-icon-cache amd64 3.24.24-4+deb11u2
  Temporary failure resolving 'deb.debian.org'
Ign:19 https://deb.debian.org/debian bullseye/main amd64 libxrender1 amd64 1:0.9.10-1
Err:5 https://debian.mirror.constant.com bullseye/main amd64 adwaita-icon-theme all 3.38.0-1
  Temporary failure resolving 'deb.debian.org'
Ign:20 https://deb.debian.org/debian bullseye/main amd64 libcairo2 amd64 1.16.0-5
Err:6 https://debian.mirror.constant.com bullseye/main amd64 dns-root-data all 2021011101
  Temporary failure resolving 'deb.debian.org'
Ign:21 https://deb.debian.org/debian bullseye/main amd64 libcairo-gobject2 amd64 1.16.0-5
Err:7 https://debian.mirror.constant.com bullseye/main amd64 dnsmasq-base amd64 2.85-1
  Temporary failure resolving 'deb.debian.org'
Ign:22 https://deb.debian.org/debian bullseye/main amd64 libcups2 amd64 2.3.3op2-3+deb11u2
Err:8 https://debian.mirror.constant.com bullseye/main amd64 dnsmasq all 2.85-1
  Temporary failure resolving 'deb.debian.org'
Ign:23 https://deb.debian.org/debian bullseye/main amd64 libdatrie1 amd64 0.2.13-1
Err:9 https://debian.mirror.constant.com bullseye/main amd64 fontconfig amd64 2.13.1-4.2
  Temporary failure resolving 'deb.debian.org'
Ign:24 https://deb.debian.org/debian bullseye/main amd64 libfribidi0 amd64 1.0.8-2+deb11u1
Err:10 https://debian.mirror.constant.com bullseye/main amd64 libipset13 amd64 7.10-1
  Temporary failure resolving 'deb.debian.org'
Ign:25 https://deb.debian.org/debian bullseye/main amd64 libgtk2.0-common all 2.24.33-2
Err:11 https://debian.mirror.constant.com bullseye/main amd64 ipset amd64 7.10-1
  Temporary failure resolving 'deb.debian.org'
Ign:26 https://deb.debian.org/debian bullseye/main amd64 libgraphite2-3 amd64 1.3.14-1
Err:12 https://debian.mirror.constant.com bullseye/main amd64 libatk1.0-data all 2.36.0-2
  Temporary failure resolving 'deb.debian.org'
Ign:27 https://deb.debian.org/debian bullseye/main amd64 libharfbuzz0b amd64 2.7.4-1
Err:13 https://debian.mirror.constant.com bullseye/main amd64 libatk1.0-0 amd64 2.36.0-2
  Temporary failure resolving 'deb.debian.org'
Ign:28 https://deb.debian.org/debian bullseye/main amd64 libthai-data all 0.1.28-3
Err:14 https://debian.mirror.constant.com bullseye/main amd64 libavahi-common-data amd64 0.8-5+deb11u1
  Temporary failure resolving 'deb.debian.org'
Ign:29 https://deb.debian.org/debian bullseye/main amd64 libthai0 amd64 0.1.28-3
Err:15 https://debian.mirror.constant.com bullseye/main amd64 libavahi-common3 amd64 0.8-5+deb11u1
  Temporary failure resolving 'deb.debian.org'
Ign:30 https://deb.debian.org/debian bullseye/main amd64 libpango-1.0-0 amd64 1.46.2-3
Err:16 https://debian.mirror.constant.com bullseye/main amd64 libavahi-client3 amd64 0.8-5+deb11u1
  Temporary failure resolving 'deb.debian.org'
Ign:31 https://deb.debian.org/debian bullseye/main amd64 libpangoft2-1.0-0 amd64 1.46.2-3
Ign:17 https://debian.mirror.constant.com bullseye/main amd64 libpixman-1-0 amd64 0.40.0-1.1~deb11u1
Ign:32 https://deb.debian.org/debian bullseye/main amd64 libpangocairo-1.0-0 amd64 1.46.2-3
Err:18 https://debian.mirror.constant.com bullseye/main amd64 libxcb-render0 amd64 1.14-3
  Temporary failure resolving 'deb.debian.org'
Ign:33 https://deb.debian.org/debian bullseye/main amd64 libxcomposite1 amd64 1:0.4.5-1
Err:19 https://debian.mirror.constant.com bullseye/main amd64 libxrender1 amd64 1:0.9.10-1
  Temporary failure resolving 'deb.debian.org'
Ign:34 https://deb.debian.org/debian bullseye/main amd64 libxcursor1 amd64 1:1.2.0-2
Err:20 https://debian.mirror.constant.com bullseye/main amd64 libcairo2 amd64 1.16.0-5
  Temporary failure resolving 'deb.debian.org'
Ign:35 https://deb.debian.org/debian bullseye/main amd64 libxi6 amd64 2:1.7.10-1
Err:21 https://debian.mirror.constant.com bullseye/main amd64 libcairo-gobject2 amd64 1.16.0-5
  Temporary failure resolving 'deb.debian.org'
Ign:36 https://deb.debian.org/debian bullseye/main amd64 libxinerama1 amd64 2:1.1.4-2
Ign:22 https://debian.mirror.constant.com bullseye/main amd64 libcups2 amd64 2.3.3op2-3+deb11u2
Ign:37 https://deb.debian.org/debian bullseye/main amd64 libxrandr2 amd64 2:1.5.1-1
Err:23 https://debian.mirror.constant.com bullseye/main amd64 libdatrie1 amd64 0.2.13-1
  Temporary failure resolving 'deb.debian.org'
Ign:38 https://deb.debian.org/debian bullseye/main amd64 libgtk2.0-0 amd64 2.24.33-2
Err:24 https://debian.mirror.constant.com bullseye/main amd64 libfribidi0 amd64 1.0.8-2+deb11u1
  Temporary failure resolving 'deb.debian.org'
Ign:39 https://deb.debian.org/debian bullseye/main amd64 libgail18 amd64 2.24.33-2
Err:25 https://debian.mirror.constant.com bullseye/main amd64 libgtk2.0-common all 2.24.33-2
  Temporary failure resolving 'deb.debian.org'
Ign:40 https://deb.debian.org/debian bullseye/main amd64 libgail-common amd64 2.24.33-2
Err:26 https://debian.mirror.constant.com bullseye/main amd64 libgraphite2-3 amd64 1.3.14-1
  Temporary failure resolving 'deb.debian.org'
Ign:41 https://deb.debian.org/debian bullseye/main amd64 libgdk-pixbuf2.0-bin amd64 2.42.2+dfsg-1+deb11u1
Err:27 https://debian.mirror.constant.com bullseye/main amd64 libharfbuzz0b amd64 2.7.4-1
  Temporary failure resolving 'deb.debian.org'
Ign:42 https://deb.debian.org/debian bullseye/main amd64 libgtk2.0-bin amd64 2.24.33-2
Err:28 https://debian.mirror.constant.com bullseye/main amd64 libthai-data all 0.1.28-3
  Temporary failure resolving 'deb.debian.org'
Ign:43 https://deb.debian.org/debian bullseye/main amd64 librsvg2-2 amd64 2.50.3+dfsg-1
Err:29 https://debian.mirror.constant.com bullseye/main amd64 libthai0 amd64 0.1.28-3
  Temporary failure resolving 'deb.debian.org'
Ign:44 https://deb.debian.org/debian bullseye/main amd64 librsvg2-common amd64 2.50.3+dfsg-1
Err:30 https://debian.mirror.constant.com bullseye/main amd64 libpango-1.0-0 amd64 1.46.2-3
  Temporary failure resolving 'deb.debian.org'
Ign:45 https://deb.debian.org/debian bullseye/main amd64 mtr amd64 0.94-1+deb11u1
Err:31 https://debian.mirror.constant.com bullseye/main amd64 libpangoft2-1.0-0 amd64 1.46.2-3
  Temporary failure resolving 'deb.debian.org'
Ign:46 https://deb.debian.org/debian bullseye/main amd64 resolvconf all 1.87
Err:32 https://debian.mirror.constant.com bullseye/main amd64 libpangocairo-1.0-0 amd64 1.46.2-3
  Temporary failure resolving 'deb.debian.org'
Err:2 https://debian.mirror.constant.com bullseye/main amd64 libgdk-pixbuf2.0-common all 2.42.2+dfsg-1+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:33 https://debian.mirror.constant.com bullseye/main amd64 libxcomposite1 amd64 1:0.4.5-1
  Temporary failure resolving 'deb.debian.org'
Err:3 https://debian.mirror.constant.com bullseye/main amd64 libgdk-pixbuf-2.0-0 amd64 2.42.2+dfsg-1+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:34 https://debian.mirror.constant.com bullseye/main amd64 libxcursor1 amd64 1:1.2.0-2
  Temporary failure resolving 'deb.debian.org'
Err:17 https://debian.mirror.constant.com bullseye/main amd64 libpixman-1-0 amd64 0.40.0-1.1~deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:35 https://debian.mirror.constant.com bullseye/main amd64 libxi6 amd64 2:1.7.10-1
  Temporary failure resolving 'deb.debian.org'
Err:22 https://debian.mirror.constant.com bullseye/main amd64 libcups2 amd64 2.3.3op2-3+deb11u2
  Temporary failure resolving 'deb.debian.org'
Err:36 https://debian.mirror.constant.com bullseye/main amd64 libxinerama1 amd64 2:1.1.4-2
  Temporary failure resolving 'deb.debian.org'
Err:37 https://debian.mirror.constant.com bullseye/main amd64 libxrandr2 amd64 2:1.5.1-1
  Temporary failure resolving 'deb.debian.org'
Err:38 https://debian.mirror.constant.com bullseye/main amd64 libgtk2.0-0 amd64 2.24.33-2
  Temporary failure resolving 'deb.debian.org'
Err:39 https://debian.mirror.constant.com bullseye/main amd64 libgail18 amd64 2.24.33-2
  Temporary failure resolving 'deb.debian.org'
Err:40 https://debian.mirror.constant.com bullseye/main amd64 libgail-common amd64 2.24.33-2
  Temporary failure resolving 'deb.debian.org'
Ign:41 https://debian.mirror.constant.com bullseye/main amd64 libgdk-pixbuf2.0-bin amd64 2.42.2+dfsg-1+deb11u1
Err:42 https://debian.mirror.constant.com bullseye/main amd64 libgtk2.0-bin amd64 2.24.33-2
  Temporary failure resolving 'deb.debian.org'
Err:41 https://debian.mirror.constant.com bullseye/main amd64 libgdk-pixbuf2.0-bin amd64 2.42.2+dfsg-1+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:43 https://debian.mirror.constant.com bullseye/main amd64 librsvg2-2 amd64 2.50.3+dfsg-1
  Temporary failure resolving 'deb.debian.org'
Err:44 https://debian.mirror.constant.com bullseye/main amd64 librsvg2-common amd64 2.50.3+dfsg-1
  Temporary failure resolving 'deb.debian.org'
Err:45 https://debian.mirror.constant.com bullseye/main amd64 mtr amd64 0.94-1+deb11u1
  Temporary failure resolving 'deb.debian.org'
Err:46 https://debian.mirror.constant.com bullseye/main amd64 resolvconf all 1.87
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/h/hicolor-icon-theme/hicolor-icon-theme_0.17-2_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://deb.debian.org/debian-security/pool/updates/main/g/gdk-pixbuf/libgdk-pixbuf2.0-common_2.42.2%2bdfsg-1%2bdeb11u1_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://deb.debian.org/debian-security/pool/updates/main/g/gdk-pixbuf/libgdk-pixbuf-2.0-0_2.42.2%2bdfsg-1%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/g/gtk%2b3.0/gtk-update-icon-cache_3.24.24-4%2bdeb11u2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/a/adwaita-icon-theme/adwaita-icon-theme_3.38.0-1_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/d/dns-root-data/dns-root-data_2021011101_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/d/dnsmasq/dnsmasq-base_2.85-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/d/dnsmasq/dnsmasq_2.85-1_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/f/fontconfig/fontconfig_2.13.1-4.2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/i/ipset/libipset13_7.10-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/i/ipset/ipset_7.10-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/a/atk1.0/libatk1.0-data_2.36.0-2_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/a/atk1.0/libatk1.0-0_2.36.0-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/a/avahi/libavahi-common-data_0.8-5%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/a/avahi/libavahi-common3_0.8-5%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/a/avahi/libavahi-client3_0.8-5%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://deb.debian.org/debian-security/pool/updates/main/p/pixman/libpixman-1-0_0.40.0-1.1%7edeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libx/libxcb/libxcb-render0_1.14-3_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libx/libxrender/libxrender1_0.9.10-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/c/cairo/libcairo2_1.16.0-5_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/c/cairo/libcairo-gobject2_1.16.0-5_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://deb.debian.org/debian-security/pool/updates/main/c/cups/libcups2_2.3.3op2-3%2bdeb11u2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libd/libdatrie/libdatrie1_0.2.13-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/f/fribidi/libfribidi0_1.0.8-2%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/g/gtk%2b2.0/libgtk2.0-common_2.24.33-2_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/g/graphite2/libgraphite2-3_1.3.14-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/h/harfbuzz/libharfbuzz0b_2.7.4-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libt/libthai/libthai-data_0.1.28-3_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libt/libthai/libthai0_0.1.28-3_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/p/pango1.0/libpango-1.0-0_1.46.2-3_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/p/pango1.0/libpangoft2-1.0-0_1.46.2-3_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/p/pango1.0/libpangocairo-1.0-0_1.46.2-3_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libx/libxcomposite/libxcomposite1_0.4.5-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libx/libxcursor/libxcursor1_1.2.0-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libx/libxi/libxi6_1.7.10-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libx/libxinerama/libxinerama1_1.1.4-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libx/libxrandr/libxrandr2_1.5.1-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/g/gtk%2b2.0/libgtk2.0-0_2.24.33-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/g/gtk%2b2.0/libgail18_2.24.33-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/g/gtk%2b2.0/libgail-common_2.24.33-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://deb.debian.org/debian-security/pool/updates/main/g/gdk-pixbuf/libgdk-pixbuf2.0-bin_2.42.2%2bdfsg-1%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/g/gtk%2b2.0/libgtk2.0-bin_2.24.33-2_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libr/librsvg/librsvg2-2_2.50.3%2bdfsg-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/libr/librsvg/librsvg2-common_2.50.3%2bdfsg-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/m/mtr/mtr_0.94-1%2bdeb11u1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch https://debian.mirror.constant.com/pool/main/r/resolvconf/resolvconf_1.87_all.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
menu.sh: line 1205: /etc/dnsmasq.d/warp.conf: No such file or directory
--2023-04-24 06:34:03--  https://raw.githubusercontent.com/fscarmen/warp/main/wireguard-go/wireguard-go_linux_amd64.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘raw.githubusercontent.com’
tar (child): wireguard-go_linux_amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
这些错误提示表明您的系统在解析域名 `deb.debian.org` 和 `debian.mirror.constant.com` 时出现问题。错误信息 "Temporary failure resolving" 表示可能存在 DNS（域名系统）配置或 DNS 服务器本身的临时问题。

要解决此问题，您可以尝试以下步骤：

1. 检查您的网络连接，确保您已连接到互联网。

2. 检查您的 DNS 配置是否正确。您可以通过检查 `/etc/resolv.conf` 文件的内容来进行检查，该文件包含您系统的 DNS 服务器配置。如果文件为空或包含不正确的信息，则可能需要使用正确的 DNS 服务器配置进行更新。

3. 尝试使用不同的 DNS 服务器。您可以通过更新 `/etc/resolv.conf` 文件中不同的 DNS 服务器的 IP 地址来更改 DNS 服务器。例如，您可以添加以下行以使用 Google 的公共 DNS 服务器：

   `````
   nameserver 8.8.8.8
   ```

4. 如果问题仍然存在，请尝试使用不同的镜像下载包。您可以更新 `/etc/apt/sources.list` 文件以使用不同的镜像。例如，您可以使用以下镜像：

   ````
   deb http://ftp.debian.org/debian bullseye main
   deb-src http://ftp.debian.org/debian bullseye main
   ````

   更新文件后，请运行 `sudo apt-get update` 命令更新软件包列表，然后再次尝试安装软件包。

**Comment by fscarmen** [comment]
这个问题的处理，应该是你的库有问题，必须先处理了。

**Comment by lmhg666** [comment]
已经改了源地址，问题解决，感谢
