### ISSUE TITLE
[help wanted 求助]: 执行warp u卸载后，依然绑定着cloudflare的ip，执行ip addr show还有warp的网卡在

### ISSUE THREAD

**Issue by zsanjin-p** [fscarmen/warp#365]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

执行warp u卸载后，依然绑定着cloudflare的ip，执行ip addr show还有warp的网卡在

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
手动看看
```
wg-quick donw wgcf
systemctl disable --now wg-quick@wgcf
```
不行就重启再看看。

**Comment by zsanjin-p** [comment]
> 手动看看
> 
> ```
> wg-quick donw wgcf
> systemctl disable --now wg-quick@wgcf
> ```
> 
> 不行就重启再看看。

我后来直接把这个网卡删了，我是想重新安装看看因为最近套了warp感觉很慢 ，不知道是不是免费的原因

**Comment by fscarmen** [comment]
warp 是减速器来的，尽量最小化使用。
