### ISSUE TITLE
[Bug]: 选择免费账户依然是 plus 账户

### ISSUE THREAD

**Issue by qianxu2001** [fscarmen/warp#366]
### Expectation / 预期情况

选择免费账户 trace 的 warp 应该为 on 而不是 plus

### Actual Situation / 实际情况

选择免费账户 trace 的 warp 是 plus，使用一段时间后会出现无法上网，疑似 plus 账号流量耗尽

### Reproduction Method / 复现方法

bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh) 4

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
> 疑似 plus 账号流量耗尽

应该没有流量用完的，你试试 `warp-go o; warp-go o` 重启一下服务看看

**Comment by Fangliding** [comment]
> > 疑似 plus 账号流量耗尽
> 
> 应该没有流量用完的，你试试 `warp-go o; warp-go o` 重启一下服务看看

这不是脚本bug 是warp-go的特性 warp go直接注册出来是plus账号

**Comment by rookiesky** [comment]
有什么办法解决吗？我也碰到这个问题了，第一次使用了warp+后，后续再使用free 获取的也还是之前的IP，哪怕我重装系统后再装也还是第一次获取的IP。

**Comment by fscarmen** [comment]
> > > 疑似 plus 账号流量耗尽
> > 
> > 
> > 应该没有流量用完的，你试试 `warp-go o; warp-go o` 重启一下服务看看
> 
> 这不是脚本bug 是warp-go的特性 warp go直接注册出来是plus账号

warp-go 作者 coia 说过，因为他内置了邀请码，这样他和新注册的用户都有 1G 的warp+流量，你可以使用24PB的 tg bot 提供的key升级一下。

**Comment by wang001200** [comment]
> > > > 疑似 plus 账号流量耗尽
> > > 
> > > 
> > > 应该没有流量用完的，你试试 `warp-go o; warp-go o` 重启一下服务看看
> > 
> > 
> > 这不是脚本bug 是warp-go的特性 warp go直接注册出来是plus账号
> 
> warp-go 作者 coia 说过，因为他内置了邀请码，这样他和新注册的用户都有 1G 的warp+流量，你可以使用24PB的 tg bot 提供的key升级一下。

请问这个「你可以使用24PB的 tg bot 提供的key升级一下」具体怎么操作。我现在就是warp-go开几天后就会连不上vps，warp-go o才能继续梯子
