### ISSUE TITLE
关于warp和chatgpt

### ISSUE THREAD

**Issue by Fangliding** [fscarmen/warp#367]
根据群友的一些奇怪问题和我的一些遭遇 研究出的奇怪特性
当浏览器使用quic并且出口是warp时，会导致CloudFlare的API错乱 返回的客户端IP变成0.0.0.0，这并不影响已经登录的账号的使用 但是登录会被禁止(如下图)
![IMG_20230427_181207](https://user-images.githubusercontent.com/45535409/234837943-47492f8d-a4f2-405c-b620-5c60c51f8040.jpg)
这可能就是一部分人套了warp也不能使用chatgpt的原因 解决办法很简单 在xray路由中禁止443端口的udp流量(quic) 或者去Chrome://flags关闭quic
虽然和这个项目好像没很大关系但是只有我发现了这个问题平时我又只在xray群没法告诉很多人 因为这个项目曝光度比较高 希望可以加到 warp解锁chatgpt 章节好让更多人可以避开这个坑()

**Comment by jaesony** [comment]
😂

**Comment by Ezi1h** [comment]
禁用后，能登录，但是登录后页面就一直显示转圈。。。什么都干不了，有遇到的吗？左下角和之之前也不一样了呢

![image](https://user-images.githubusercontent.com/38790566/235063751-855f5de7-30c0-4369-a084-e1c6ad9a5826.png)

**Comment by jaesony** [comment]
估计还是IP的原因，我有个节点也一样，ipv4的warp一直转圈，换成ipv6就可以了

**Comment by Yang-z** [comment]
我遇到的情况是，如果quic不关闭，chatgpt拒绝访问，列出我的ip，是vps未套warp前原本的ip，我还以为是他有什么技术能识别原ip。看到这个issue，我也才确认是同quic开启有关。这是为什么呢？我看warp在vps上是全局的呀。

**Comment by LoveClears** [comment]
> 浏览器禁止使用quic后，可以登录，但登录后页面就一个直接显示转圈。。。什么都干不了，有遇到的吗？
> 
> ![图像](https://user-images.githubusercontent.com/38790566/235063751-855f5de7-30c0-4369-a084-e1c6ad9a5826.png)

解决了吗 我也这样问题....

**Comment by fscarmen** [comment]
[help wanted 求助]: 采用菜单12选项解锁chatgpt,遇到界面一直转菊花
https://github.com/fscarmen/warp/issues/353

**Comment by V4444** [comment]
之前安装了warp貌似可以访问gpt,现在不行了
