### ISSUE TITLE
[help wanted 求助]: 请问怎么查看warp服务的进程和状态，用ps命令并没有找到

### ISSUE THREAD

**Issue by mebest100** [fscarmen/warp#369]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

请问怎么查看warp服务的进程和状态，用ps命令并没有找到

### Log / 日志信息

请问怎么查看warp服务的进程和状态，用ps命令并没有找到

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
查状态  `wg`
查服务 `systemctl status wg-quick@wgcf`
