### ISSUE TITLE
单IPV4 VPS，用2.21 版本启用双栈后，异常

### ISSUE THREAD

**Issue by at2008** [fscarmen/warp#37]
异常：
1 : 启用后，再次运行warp，进入后，显示 对 ipv6 启用 warp
2 : ping 外部域名不通 ，好像本机的 ipv4 消失了一样

也许我vps有问题，不知道哪里出问题了，两台一样的情况，都是从Ubuntu 18.04 升级到 20.04后安装的脚本

能不能提供一下 warp 2.20版本的，让我试一下

**Comment by fscarmen** [comment]
运行第一次```warp o```把warp关了
再运行一次```warp o```打开，应该有IP显示的，包括V4和V6。
看是否正常，把回显发一下

**Comment by at2008** [comment]
> 运行第一次`warp o`把warp关了 再运行一次`warp o`打开，应该有IP显示的，包括V4和V6。 看是否正常，把回显发一下

应该时我的Ubuntu内核没有升级完整，我内核回退到5.5.5 后，都正常了，脚本应该时正常的。
多谢回复，问题关闭。

**Comment by fscarmen** [comment]
> 应该是我的Ubuntu内核没有升级完整，我内核回退到5.5.5 后，都正常了，脚本应该是正常的。

我试过 Linux 5.13、5.14、5.15 之后使用脚本都是可以的。
感谢你的支持。如遇到其他问题或者好的建议随时发过来！
