### ISSUE TITLE
[Bug]: Registration of WARP free account failed-【Result: 2023.5.10 warp-go V1.1.4 Docking the warp-go official account pool api】

### ISSUE THREAD

**Issue by AliM1988** [fscarmen/warp#372]
### Expectation / 预期情况

Registration of WARP free account failed

### Actual Situation / 实际情况

My vps info:

 Version: 1.1.3
 New features: 1. Change the best Warp endpoint to standard ports [500,1701,2408,4500]; 2. Upgrade the Netflix unlocking section
 System infomation:
         Operating System: Ubuntu 20.04.6 LTS
         Kernel: 5.4.0-148-generic
         Architecture: amd64v3
         Virtualization: kvm
         IPv4: ****  Germany  xTom GmbH
         IPv6: ******  Germany  xTom GmbH
         WARP network interface is not turned on

### Reproduction Method / 复现方法

-

### Log / 日志信息

-

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
warp-go recently registered an api problem, the original author Coia already has an alternative, the script I have to be late to fix the issue.

**Comment by fscarmen** [comment]
2023.5.10 warp-go V1.1.4
1. Docking the warp-go official account pool api, wiki: https://docs.zeroteam.top/apis/warp; 
2. Change non-global from ipv4 only to dualstacks; 
3. Fix the bug that the native IPv6 cannot login when using dualstacks; 
4. Update the Best-enpoint app; 
5. Change ip api; 

1. 对接 warp-go 官方账户池 api，wiki: https://docs.zeroteam.top/apis/warp; 
2. 非全局从ipv4 only 改为双栈; 
3. 修复双栈时使用原生 IPv6 不能登陆的 bug; 
4. 更新最佳 Endpoint 应用; 
5. 更换 ip api


https://github.com/fscarmen/warp
