### ISSUE TITLE
[help wanted 求助]:注册warp账户失败-【结论：2023.5.10 warp-go V1.1.4 对接 warp-go 官方账户池 api】

### ISSUE THREAD

**Issue by lukaschan** [fscarmen/warp#374]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

搬瓦工，脚本注册free或plus账户尝试5次后均失败中止。warp-cli却可以

### Log / 日志信息

 1. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv4 优先 (bash warp-go.sh 4) 
 2. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv6 优先 (bash warp-go.sh 4) 
 3. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6) 
 4. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv6 优先 (bash warp-go.sh 6) 
 5. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv4 优先 (bash warp-go.sh d) 
 6. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv6 优先 (bash warp-go.sh d) 
 7. 为 IPv4 only 添加 WARP IPv4 非全局 网络接口，IPv4 优先 (bash warp-go.sh n) 
 8. 为 IPv4 only 添加 WARP IPv4 非全局 网络接口，IPv6 优先 (bash warp-go.sh n) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 7

 如有 WARP+ 或 Teams 账户请选择
 1. WARP+
 2. Teams
 3. 使用免费账户 (默认) 

 请选择: 1
 如有 WARP+ License 请输入，没有可回车继续: 【脱敏】
 请自定义设备名 (如果不输入，默认为 [warp-go]): 76

 进度 1/3: 安装系统依赖…… 

 注册 WARP+ 账户中, 最大尝试5次…… 
 第1次尝试 

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 注册 WARP+ 账户失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
warp-go最近注册的api有问题，原作者 Coia 已经有替代方案，脚本我要迟点才能把车修好了。

**Comment by fscarmen** [comment]
2023.5.10 warp-go V1.1.4
1. Docking the warp-go official account pool api, wiki: https://docs.zeroteam.top/apis/warp; 
2. Change non-global from ipv4 only to dualstacks; 
3. Fix the bug that the native IPv6 cannot login when using dualstacks; 
4. Update the Best-enpoint app; 
5. Change ip api; 

1. 对接 warp-go 官方账户池 api，wiki: https://docs.zeroteam.top/apis/warp; 
2. 非全局从ipv4 only 改为双栈; 
3. 修复双栈时使用原生 IPv6 不能登陆的 bug; 
4. 更新最佳 Endpoint 应用; 
5. 更换 ip api


https://github.com/fscarmen/warp
