### ISSUE TITLE
[help wanted 求助]: 注册 WARP free 账户失败，手动用WGCF注册成功了，有没有办法把配置文件移植过来？

### ISSUE THREAD

**Issue by yburger** [fscarmen/warp#375]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Others

### Actual Situation / 实际情况

运行在OpenWRT上，注册 WARP free 账户总是失败，试了下用wgcf手动生成了wgcf-profile.conf和wgcf-account.toml，有没有办法把配置信息填到配置文件里直接使用从而跳过程序的注册阶段？

### Log / 日志信息

 注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 
 第2次尝试 
 第3次尝试 

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 第4次尝试 
 第5次尝试 
 注册 WARP free 账户失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
> 了下用wgcf手动生成了wgcf-profile.conf和wgcf-account.toml，有没有办法把配置信息填到配置文件里直接使用从而跳过程序的注册阶段？

不太明白为什么手动可以，脚本跑的时候不行，脚本也是用这两个指令的，需要查查才行。同时我也做了注册失败一定次数，自动使用一个默认配置文件的，我想不通为什么这个不生效。

https://github.com/fscarmen/warp/blob/main/menu.sh#L1401
