### ISSUE TITLE
[help wanted 求助]: 模式选择问题 以及全局warp配置

### ISSUE THREAD

**Issue by dinaau** [fscarmen/warp#376]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

vps上面已经在运行其他的docker项目

想安装个warp，并且只用v2rayN这个客户端来实现 所有的流量都走warp

并且安装好后warp不会影响到其他docker的工作， 其他docker需要走vps本身的ip流量

请问这个需求需要安装哪个模式，并且如何配置服务器端和v2rayN的客户端？

### Log / 日志信息

n/a

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
用wireproxy或者clinet方式，之后v2ray/xray把全部流量指向通过脚本创建的 socks5 或者 interface 了，这样使warp只接管v2ray过来的流量，保证了v2ray使用了warp服务，又保证了docker使用vps原生的网络出口了。

**Comment by fscarmen** [comment]
v2rayN 是客户端来的哦

**Comment by fscarmen** [comment]
如果你是需要全局走warp，那就安装 warp 菜单里的3可以啦

**Comment by fscarmen** [comment]
[#](https://github.com/fscarmen/warp/issues/115
