### ISSUE TITLE
[help wanted 求助]: iptable+ipset+dnsmasq模式，Netflix分流安卓APP不生效。

### ISSUE THREAD

**Issue by shandongtlb** [fscarmen/warp#377]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

iptable+ipset+dnsmasq模式，Netflix分流安卓APP不生效。
大佬好呀，我特别喜欢您脚本这个分流模式，但是发现这个模式只能在电脑端web网页和手机网页有效，绝命毒师 的页面是可以打开的，如图:
![Screenshot_20230508_021135_Chrome](https://user-images.githubusercontent.com/40312509/236695137-23cc29cd-fe3c-446d-96ee-f3b472f209e1.jpg)

但是在手机app上，则检测报开启了VPN或代理，无法播放。
![Screenshot_20230508_021357_Netflix](https://user-images.githubusercontent.com/40312509/236695231-80745000-962a-46a3-996a-cd9df2393252.jpg)

为了证明不是warp网络的问题，我试着开启了一下全局模式，是可以的，只有分流模式才会报VPN。感觉是dnsmasq名单没配置好，求教大佬！

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [x] Yes / 是

**Comment by shandongtlb** [comment]
补充一下信息，vps是racknerd的la dc02机房机器，Ubuntu22，内核5.15。开启分流方案后，流媒体解锁脚本基本上都能过，chatgpt也可以，但奈飞的app没法看，报VPN，其他迪士尼等app没试过

**Comment by fscarmen** [comment]
你指的全局是指 vps 上使用 warp 全局吗? 这样在奈飞的 app就不会报错，能看。
而使用了dnsmasq之后，奈飞app就报vpn错误了？

**Comment by shandongtlb** [comment]
> 你指的全局是指 vps 上使用 warp 全局吗? 这样在奈飞的 app就不会报错，能看。 而使用了dnsmasq之后，奈飞app就报vpn错误了？

首先谢谢大佬的回复，对的对的，全局是指vps所有流量都走warp，这个没问题的，然而开了dnsmasq分流就不行了，因此推测是dnsmasq域名配置可能还需要进一步优化

**Comment by shandongtlb** [comment]
再补充一下，我在电脑挂这个vps的梯子之后，手机安卓端通过WiFi上代理模式连接我的电脑，也是可以访问APP的，只有手机端开VPN才会报错

**Comment by fscarmen** [comment]
我觉得有两个可能，1.手机使用了其他的域名或者IP，所以 dnsmasq 那里没有设置的，所以没有走warp，2.app能做检测机制，像农行app，检测到开着vpn就不让使用，这个在手机网页浏览器是做不到的，所以浏览器能使用。

**Comment by shandongtlb** [comment]
> 

辛苦了大佬，半夜两点还回我消息！
1.“手机使用了其他的域名或者IP”这个是什么意思呀，不太懂，那这样的话需要怎么设置呢，另外，我看server=1.1.1.1和8.8.8.8这个是代表dns查询走warp吗？
2.我之前用全局warp方案开启app是没问题的，只有用分流方案才会报vpn。因此如果app能做检测机制的话，全局应该也用不了了。不知道其他人在使用的时候有没有遇到此类问题。。

**Comment by shandongtlb** [comment]
我明白第一个的意思了，我用抓包app给netflix app抓了一下包，发现那些访问域名都包含在内，貌似只有239.255.255.250这个ip我没有包含

**Comment by fscarmen** [comment]
我想可以这样调试，用 warp 全局，再在手机app看有没有这个vpn的报错，如果没有了，就是app运行中，有的域名和ip没有走Warp。

**Comment by shandongtlb** [comment]
> 我想可以这样调试，用 warp 全局，再在手机app看有没有这个vpn的报错，如果没有了，就是app运行中，有的域名和ip没有走Warp。

对的，就是开全局的时候，APP不报VPN，所以应该是分流的时候域名或ip没走全

**Comment by fscarmen** [comment]
这条是什么意思呢？你如何发现这个IP的？

**Comment by fscarmen** [comment]
> 问题已经解决，只需每次开机后添加 ipset add warp 239.255.255.250 这条ip即可，后续大佬可以考虑把这个加进脚本以实现每次开机自动添加。

已添加
https://github.com/fscarmen/warp/blob/a39d3b0712f974a814f32b1af04e945f2a26ff4a/menu.sh#L1270

**Comment by shandongtlb** [comment]
还得加上这个，不然还是不行： ipset add warp 45.57.0.0/17
另外，可以参考一下这个ip列表 https://cdn.jsdelivr.net/gh/QiuSimons/Netflix_IP/NF_only.txt ，按理说这些都得添加，但我试了一下，ipset add warp 45.57.0.0/17 这个就行，可能地区不一样，需要添加的IP也不一样

**Comment by fscarmen** [comment]
你试试在  /etc/dnsmasq.d/warp.conf  里输入这个 ipset=/45.57.0.0/17/warp
