### ISSUE TITLE
[Feature request]: 希望能支持Debian12系统

### ISSUE THREAD

**Issue by f3j43fz** [fscarmen/warp#379]
### Related Problem / 相关问题

当我在debian12系统中运行此脚本，选择5 （安装 CloudFlare Client 并设置为 Proxy 模式）时，报错了，这是报错代码：

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnupg2 is already the newest version (2.2.40-1.1).
The following NEW packages will be installed:
  desktop-file-utils
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 91.2 kB of archives.
After this operation, 292 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 desktop-file-utils amd64 0.26-1 [91.2 kB]
Fetched 91.2 kB in 0s (805 kB/s)              
Selecting previously unselected package desktop-file-utils.
(Reading database ... 29062 files and directories currently installed.)
Preparing to unpack .../desktop-file-utils_0.26-1_amd64.deb ...
Unpacking desktop-file-utils (0.26-1) ...
Setting up desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for man-db (2.11.2-2) ...
dpkg: error: cannot access archive 'Client_Debian_12.deb': No such file or directory  --------关键信息
Failed to start warp-svc.service: Unit warp-svc.service not found.
 进度 2/2: 设置 Client 模式 
menu.sh: line 1702: warp-cli: command not found
 创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp/issues] 

### Describe the solution you want / 描述你希望的解决方案

增加对Debian12系统的支持

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
没有环境试呢。
