### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by asterriya** [fscarmen/warp#38]
E: Release file for http://security.debian.org/debian-security/dists/buster/updates/InRelease is not valid yet (invalid for another 1d 1h 5 min 30s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/buster-backports/InRelease is not valid yet (invalid for another 1d 15h 23 min 16s). Updates for this repository will not be applied.
Reading package lists… Done
Building dependency tree       
Reading state information… Done
E: Unable to locate package wireguard-tools

 WireGuard's tools not installed or the configuration file wgcf.conf cannot be found, please reinstall.

And how to use Warp Team? Where to find it and activate?

**Comment by fscarmen** [comment]
It seems that you could not connect debian to install the dependency of "wireguard-tools".
You try this ```apt -y update; apt -y install wireguard-tools```.
You need "Google.com" If it still didn't work.

And the WARP team license will be processed automatically when you choose [ y ] to use it .

**Comment by asterriya** [comment]
From other's git script is working. Strange.

**Comment by fscarmen** [comment]
forward that git to me pls.i find the different in wireguard-tools installing

**Comment by asterriya** [comment]
https://github.com/kkkyg/CFwarp

**Comment by fscarmen** [comment]
> https://github.com/kkkyg/CFwarp

I couldn't find the difference. If it is convenient for you, install this script again and give me the result.

**Comment by fscarmen** [comment]
Is the problem solved?
