### ISSUE TITLE
[help wanted 求助]: 日本的vps分到了中国的cloudfare？

### ISSUE THREAD

**Issue by zsanjin-p** [fscarmen/warp#380]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

今天换了服务器，日本的，64.176.51.xxx，按往常一样运行warp，在warp脚本显示我的ip是中国，然后获取免费账户的cloudfare地址一直出错，因为大于5次都没获取到ip，用了team才获取到ip，ip地址为104.28.193.101，cloudfare
在各个ip查询站点里面查，有的说这个ip是美国，有的说是澳大利亚，不过还有的说这是宁波的ip，结果我全局模式也被openai封，bing也不让用，bing还强行锁定cn.bing.com，但是我能用谷歌，谷歌安全搜索也可以关，这就很离谱了

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by shandongtlb** [comment]
哈哈哈哈太惨了兄弟，什么出口转内销

**Comment by shandongtlb** [comment]
warp i jp试试

**Comment by zsanjin-p** [comment]
> 换原生ip解决了，避雷一下vultr5美元的大版IP



> 哈哈哈哈太惨了兄弟，什么出口转内销

换原生IP了，我是没想到还能cloudflare还能把自家ip识别为中国的

**Comment by shandongtlb** [comment]
> > 换原生ip解决了，避雷一下vultr5美元的大版IP
> 
> > 哈哈哈哈太惨了兄弟，什么出口转内销
> 
> 换原生IP了，我是没想到还能cloudflare还能把自家ip识别为中国的

哈哈哈哈哈，神奇

**Comment by fscarmen** [comment]
用 `warp i jp` 换 warp ip，如果多次仍然检测是中国的话，建议让厂家换个 IP了，warp 暂时没有办法改接入的归属地。

**Comment by zsanjin-p** [comment]
> 用 `warp i jp` 换 warp ip，如果多次仍然检测是中国的话，建议让厂家换个 IP了，warp 暂时没有办法改接入的归属地。

原生ip被识别为中国，没办法已经换了机房位置
