### ISSUE TITLE
[help wanted 求助]: menu.sh Debian 系统5次获取IP失败

### ISSUE THREAD

**Issue by hwmbing11** [fscarmen/warp#382]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

warp 打不开 
![image](https://user-images.githubusercontent.com/63941939/237036281-9321130b-33b7-4147-8ab0-f31bf93bb87d.png)

### Log / 日志信息

 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

刷了好久也不行

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
vps归属地是哪里的？试试 warp-go?

**Comment by founderqiang** [comment]
楼主现在解决了吗，我也出现了同样的问题，解决了的话能否告诉解决方法
