### ISSUE TITLE
[help wanted 求助]: 可以在原有wireguard上添加warp吗？并且需要多用户

### ISSUE THREAD

**Issue by jianmicha** [fscarmen/warp#385]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

原有wireguard是使用秋水逸冰的脚本，现在想套warp来保护服务器。

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
tg上提到同样问题那位朋友是你吗？

**Comment by jianmicha** [comment]
是的😀

fscarmen ***@***.***>于2023年5月11日 周四09:18写道：

**Comment by fscarmen** [comment]
玩法太高级了，在wireugard连vps基础上，再套warp出局，期待你找到如何弄，回头分享一下。
