### ISSUE TITLE
[help wanted 求助]: 无法卸载停用和重装

### ISSUE THREAD

**Issue by ixxmu** [fscarmen/warp#386]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

严重bug，无法卸载无法重装！卡着IP无法登陆！

### Log / 日志信息

严重bug，无法卸载无法重装！卡着IP无法登陆！

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
很大可能是贵小鸡骨骼精奇，导致脚本判断环境失败导致使用错配置，我试过几个小鸡安装和卸载都是正常的，而且最近我没有更新过 `menu.sh` 脚本，应该不大可能有大范围致命bug的，如果你的小鸡有 vnc ，进去后卸载就行了。

**Comment by ixxmu** [comment]
> 很大可能是贵小鸡骨骼精奇，导致脚本判断环境失败导致使用错配置，我试过几个小鸡安装和卸载都是正常的，而且最近我没有更新过 `menu.sh` 脚本，应该不大可能有大范围致命bug的，如果你的小鸡有 vnc ，进去后卸载就行了。

没有什么轻不轻奇的，就是和tailscale冲突了，已经手动卸载折腾好了。

再次感谢大佬的脚本！

**Comment by fscarmen** [comment]
你可以试试使用非全局的方案，比如 wireproxy 模式， clinet 模式 和 warp-go 的非全局模式，这些或许不会与 tailscale 冲突。

**Comment by ixxmu** [comment]
> 你可以试试使用非全局的方案，比如 wireproxy 模式， clinet 模式 和 warp-go 的非全局模式，这些或许不会与 tailscale 冲突。

好的，我试试，感谢大佬回复
