### ISSUE TITLE
[Bug]: 汇报一个奇怪的现象，使用电脑能用网页gpt，手机则不行，重启vps手机又可以使用了

### ISSUE THREAD

**Issue by zsanjin-p** [fscarmen/warp#387]
### Expectation / 预期情况

手机，电脑应该均能正常使用gpt

### Actual Situation / 实际情况

是这样的，已经正常套上warp了，用电脑也能正常浏览gpt，但是用手机则正常登录，但是一直转圈圈，加载不出对话，昨天还是正常能用的。手机上用了各类浏览器都是这样转菊花，试了bingai是能正常用的，很奇怪的是电脑能使用gpt，手机就转菊花，然后我试着重启vps，手机就能正常访问，不知道是是什么原因

### Reproduction Method / 复现方法

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
会不会手机的流量走了其他地方？

**Comment by zsanjin-p** [comment]
> 会不会手机的流量走了其他节点？

当时在ip138上面确认过了是warp获取的IP地址，而且能访问bingai，原生的日本IP也被bingai拉黑了，所以就感觉很奇怪，电脑能用gpt手机不能，重启了vps又能了，主要是昨天的时候手机还能正常用，不知道发生了什么，用的是v2ray的伪装ws+tls，电脑和手机同步的节点

**Comment by shandongtlb** [comment]
在vps上运行一次curl chat.openai.com 手机就行了

**Comment by zsanjin-p** [comment]
> 在vps上运行一次curl chat.openai.com 手机就行了

不行啊，发现重启vps，电脑或者手机谁先登录谁能用，慢登录的转菊花

**Comment by szylhh** [comment]
我也是，手机不行，电脑可以，手机其他都走了warp，就是openai不走warp，走服务器流量

**Comment by szylhh** [comment]
试了别的客户端也是，确定开的全局，电脑没问题

**Comment by shandongtlb** [comment]
> > 在vps上运行一次curl chat.openai.com 手机就行了
> 
> 不行啊，发现重启vps，电脑或者手机谁先登录谁能用，慢登录的转菊花

我用的是那个iptable分流方案，每次重启运行一下curl就好了
