### ISSUE TITLE
开启一段时间后，服务器网络完全卡死

### ISSUE THREAD

**Issue by fengcharles** [fscarmen/warp#39]
当前操作系统：CentOS Linux 7 (Core)
内核：5.15.7-1.el7.elrepo.x86_64
处理器架构：amd64
虚拟化：kvm

一般情况下 warp 开启后 正常访问没有问题，一天以后，VPS 的网络几乎处于崩溃状态，无法ping域名，网络连接速度非常慢，必须打开脚本 重启才行，请问有遇到同款问题的吗？

**Comment by fscarmen** [comment]
暂时没有看到同款的问题，或者你换个系统看问题是否依旧? Debian 11或者 Ubuntu 20.04这样？

**Comment by at2008** [comment]
> 当前操作系统：CentOS Linux 7 (Core) 内核：5.15.7-1.el7.elrepo.x86_64 处理器架构：amd64 虚拟化：kvm
> 
> 一般情况下 warp 开启后 正常访问没有问题，一天以后，VPS 的网络几乎处于崩溃状态，无法ping域名，网络连接速度非常慢，必须打开脚本 重启才行，请问有遇到同款问题的吗？

我遇到过，我的原因是 Ubuntu 安装 5.15.5 内核没正常安装，退回到低一些的内核版本正常了；
还有一个原因，另外的一个 issue 里面有提到，大概与 docker 网络冲突，估计也有可能；

仅供参考。

**Comment by fscarmen** [comment]
> > 当前操作系统：CentOS Linux 7 (Core) 内核：5.15.7-1.el7.elrepo.x86_64 处理器架构：amd64 虚拟化：kvm
> > 一般情况下 warp 开启后 正常访问没有问题，一天以后，VPS 的网络几乎处于崩溃状态，无法ping域名，网络连接速度非常慢，必须打开脚本 重启才行，请问有遇到同款问题的吗？
> 
> 我遇到过，我的原因是 Ubuntu 安装 5.15.5 内核没正常安装，退回到低一些的内核版本正常了； 还有一个原因，另外的一个 issue 里面有提到，大概与 docker 网络冲突，估计也有可能；
> 
> 仅供参考。

啊，我的GCP 香港也升级到 5.15的，但好像没有这个问题，与docker协同的环境需要按主多测了

**Comment by at2008** [comment]
> > > 当前操作系统：CentOS Linux 7 (Core) 内核：5.15.7-1.el7.elrepo.x86_64 处理器架构：amd64 虚拟化：kvm
> > > 一般情况下 warp 开启后 正常访问没有问题，一天以后，VPS 的网络几乎处于崩溃状态，无法ping域名，网络连接速度非常慢，必须打开脚本 重启才行，请问有遇到同款问题的吗？
> > 
> > 
> > 我遇到过，我的原因是 Ubuntu 安装 5.15.5 内核没正常安装，退回到低一些的内核版本正常了； 还有一个原因，另外的一个 issue 里面有提到，大概与 docker 网络冲突，估计也有可能；
> > 仅供参考。
> 
> 啊，我的GCP 香港也升级到 5.15的，但好像没有这个问题，与docker协同的环境需要按主多测了

正常安装成功应该是没有问题的，我的是安装部分成功，4个安装包，其中一个没安装成功，导致系统异常。不是脚本的问题。

**Comment by fengcharles** [comment]
> 

好的 非常感谢，我降级版本试试看

**Comment by fengcharles** [comment]
> > > > 当前操作系统：CentOS Linux 7 (Core) 内核：5.15.7-1.el7.elrepo.x86_64 处理器架构：amd64 虚拟化：kvm
> > > > 一般情况下 warp 开启后 正常访问没有问题，一天以后，VPS 的网络几乎处于崩溃状态，无法ping域名，网络连接速度非常慢，必须打开脚本 重启才行，请问有遇到同款问题的吗？
> > > 
> > > 
> > > 我遇到过，我的原因是 Ubuntu 安装 5.15.5 内核没正常安装，退回到低一些的内核版本正常了； 还有一个原因，另外的一个 issue 里面有提到，大概与 docker 网络冲突，估计也有可能；
> > > 仅供参考。
> > 
> > 
> > 啊，我的GCP 香港也升级到 5.15的，但好像没有这个问题，与docker协同的环境需要按主多测了
> 
> 正常安装成功应该是没有问题的，我的是安装部分成功，4个安装包，其中一个没安装成功，导致系统异常。不是脚本的问题。

好的 非常感谢 提供意见，我降级版本试试看

**Comment by fscarmen** [comment]
> 好的 非常感谢 提供意见，我降级版本试试看

这个问题解决了吗？如何处理的？

**Comment by fengcharles** [comment]
> > 好的 非常感谢 提供意见，我降级版本试试看
> 
> 这个问题解决了吗？如何处理的？

这两天观察下来，没有自己卡死的情况了，不过我可以通过运行命令（ systemctl restart wg-quick@wgcf ） 重现这个问题。一旦运行这个命令，肯定会卡死。网络卡死的表现是，域名服务器失效，导致很多域名无法解析。

**Comment by fscarmen** [comment]
> systemctl restart wg-quick@wgcf

这个命令相当于与CF的warp重新拨号，我是用这个指令作换奈飞IP的，现在加了新的刷奈飞IP功能，你可以试试```warp i``` 看是否正常，有ip显示的

**Comment by fengcharles** [comment]
> > systemctl restart wg-quick@wgcf
> 
> 这个命令相当于与CF的warp重新拨号，我是用这个指令作换奈飞IP的，现在加了新的刷奈飞IP功能，你可以试试`warp i` 看是否正常，有ip显示的

OK
