### ISSUE TITLE
[help wanted 求助]: 1.1.4脚本非全局模式获取不到 IPv4 的地址

### ISSUE THREAD

**Issue by ganyyy** [fscarmen/warp#391]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

1.1.4 版本中，

VPS 地区：美国
VPS 服务商：cloudcone

1. 非全局只能刷新出 IPv6的 WARP IP，无法刷新出 IPv4 的 WARP IP。

![image](https://github.com/fscarmen/warp/assets/26517484/fc000c96-14d5-43ff-ac59-d94b4d711bb8)

2. 使用全局模式可以刷出IPv4，但是v2ray 的 mKCP 节点无法连接。
       v2ray的分流配置
![image](https://github.com/fscarmen/warp/assets/26517484/2bd6f305-2397-46f8-ae6e-515c64027251)
       全局可以获取到IPv4
![image](https://github.com/fscarmen/warp/assets/26517484/1de8c746-3f62-4149-a453-10403b86d9fc)
       v2ray 测试失败的日志
![image](https://github.com/fscarmen/warp/assets/26517484/e4382d54-c8c8-4c01-b8a7-60f6fc08d2cf)
3. 使用非全局模式 + IPv6，mKCP可以连接，但是无法通过WARP连接网站，
       warp-go的运行信息
![image](https://github.com/fscarmen/warp/assets/26517484/e32c9769-ccf5-4e0b-9e5f-39bca6558306)
       warp-go的执行日志
![image](https://github.com/fscarmen/warp/assets/26517484/b3a08136-befe-4dfb-80bc-837861b6c94b)
       v2ray的debug日志
![image](https://github.com/fscarmen/warp/assets/26517484/fe6bd540-37d0-4b09-a951-44b92af2f1da)

4. 不确定是不是WARP的问题，有人遇到过ssh经常断开的情况吗？
![image](https://github.com/fscarmen/warp/assets/26517484/aa146b0b-e535-468c-ae61-796b6e03c77f)

### Log / 日志信息

参见问题描述，如果需要文本日志后续可以补充。

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by ganyyy** [comment]
尝试过先开启全局，再切回非全局的 情况，还是只能获取到 IPv6 的 WARP IP
![image](https://github.com/fscarmen/warp/assets/26517484/18b47612-2d4b-4ef7-b5cb-302d7c83e41a)

**Comment by ganyyy** [comment]
开启warp-go后的网卡信息
![image](https://github.com/fscarmen/warp/assets/26517484/601dd65b-8a6f-4bf6-9b62-3098efde50d7)

**Comment by zsanjin-p** [comment]
+1，我也是这样的

**Comment by zsanjin-p** [comment]
1. 为 原生双栈 添加 WARP IPv4 全局 网络接口，IPv4 优先 (bash warp-go.sh 4) 
 2. 为 原生双栈 添加 WARP IPv4 全局 网络接口，IPv6 优先 (bash warp-go.sh 4) 
 3. 为 原生双栈 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6) 
 4. 为 原生双栈 添加 WARP IPv6 全局 网络接口，IPv6 优先 (bash warp-go.sh 6) 
 5. 为 原生双栈 添加 WARP 双栈 全局 网络接口，IPv4 优先 (bash warp-go.sh d) 
 6. 为 原生双栈 添加 WARP 双栈 全局 网络接口，IPv6 优先 (bash warp-go.sh d) 
 7. 为 原生双栈 添加 WARP 双栈 非全局 网络接口，IPv4 优先 (bash warp-go.sh n) 
 8. 为 原生双栈 添加 WARP 双栈 非全局 网络接口，IPv6 优先 (bash warp-go.sh n) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 7

 如有 WARP+ 或 Teams 账户请选择
 1. WARP+
 2. Teams
 3. 使用免费账户 (默认) 

 请选择: 

 进度 1/3: 安装系统依赖…… 

 注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 

 进度 2/3: 已安装 warp-go 


 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 已成功获取 WARP free 网络
 运行在 非全局 模式 

==============================================================

 IPv4:      
 IPv6: 2a09:bac5:4302:dc::16:1ac  日本  Cloudflare 
 恭喜！WARP free 已开启，总耗时:37秒
 脚本当天运行次数: 4670，累计运行次数：713756 
 IPv4 优先 

==============================================================

 再次运行用 warp-go [option] [lisence]，如
 
 warp-go h (帮助）
 warp-go o (临时 warp-go 开关)
 warp-go u (卸载 WARP 网络接口和 warp-go)
 warp-go v (同步脚本至最新版本)
 warp-go i (更换支持 Netflix 的IP)
 warp-go 4/6 (WARP IPv4/IPv6 单栈)
 warp-go d (WARP 双栈)
 warp-go n (WARP IPv4 非全局)
 warp-go g (WARP 全局 / 非全局相互切换)
 warp-go e (输出 wireguard 和 sing-box 配置文件)
 warp-go a (更换到 Free，WARP+ 或 Teams 账户)

**Comment by zsanjin-p** [comment]
奇怪的是在菜单脚本那里选择3，却只能获取ipv4地址，ipv6的是空的，之前都能获取到的

	 WARP 网络接口未开启 
	 Client 未安装 
	 WireProxy 未安装 

======================================================================================================================

 1.  为 原生双栈 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
 2.  为 原生双栈 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
 3.  为 原生双栈 添加 WARP 双栈网络接口 (bash menu.sh d) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 3

。。。

 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 已成功获取 WARP 网络 

==============================================================

 IPv4: 104.28.238.182  日本  Cloudflare, Inc. 
 IPv6:      
 恭喜！WARP 已开启，总耗时:44秒， 脚本当天运行次数:12546，累计运行次数:2925654 
 IPv4 优先 

==============================================================

**Comment by ganyyy** [comment]
今天发现非全局又可以获取到ipv4了😅
