### ISSUE TITLE
[Feature request]:  全局双栈ipv4和ipv6，用来解锁chatGPT正常，用代理不行，但是全局就会导致twitch无法正常观看源清晰度 有没有什么办法可以解决 

### ISSUE THREAD

**Issue by luluQAQ** [fscarmen/warp#392]
### Related Problem / 相关问题

用了warp代理之后twitch异常

### Describe the solution you want / 描述你希望的解决方案

可以指定某些域名在全局双栈的情况下也依然不代理

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
用iptable的方案，白名单的机制
