### ISSUE TITLE
[help wanted 求助]: 安装Wireproxy 本地 Socks5: 空白

### ISSUE THREAD

**Issue by shiwoslj** [fscarmen/warp#394]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

脚本版本:2.49
 功能新增:1. warp endpoint 优选改为标准端口 [500,1701,2408,4500]; 2. 升级奈飞解锁部分
 系统信息:
         当前操作系统:Debian GNU/Linux 10 (buster)
         内核:4.19.0-23-amd64
         处理器架构:amd64
         虚拟化:microsoft 
         IPv4: 104.28.195.106  美国  Cloudflare, Inc. 
         IPv6: 2001:19f0:5c00:1d2b:5400:4ff:fe70:2f5b  美国  Choopa, LLC 
         WARP Teams 网络接口已开启        
         Client 未安装 
         WARP WireProxy 已开启   本地 Socks5: 
         WARP IPv4:    

前天安装成功的wireproxy有 【本地 Socks5: 】今天试了很多台VPS都是空白的【本地 Socks5: 】

### Log / 日志信息

wireproxy_linux_amd64.tar.gz   100%[===================================================>]   1.98M  --.-KB/s    in 0.1s    

2023-05-15 18:17:09 (16.7 MB/s) - ‘wireproxy_linux_amd64.tar.gz’ saved [2080762/2080762]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables is already the newest version (1.8.2-4).
net-tools is already the newest version (1.60+git20180626.aebd88e-1).
openresolv is already the newest version (3.8.0-1).
dnsutils is already the newest version (1:9.11.5.P4+dfsg-5.1+deb10u8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-4.19.0-23-amd64 is already the newest version (4.19.269-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wireguard-dkms is already the newest version (1.0.20210219-1~bpo10+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 进度 2/3: 已安装 WGCF 

 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

Created symlink /etc/systemd/system/multi-user.target.wants/wireproxy.service → /lib/systemd/system/wireproxy.service.
 创建快捷 warp 指令成功 
 恭喜！Wireproxy 工作中, 总耗时:42秒， 脚本当天运行次数:24659，累计运行次数:2966422
 本地 Socks5: 127.0.0.1:40000
 WARP free IPv4:    

==============================================================

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
已处理，请用 `warp v` 更新一下即可

**Comment by shiwoslj** [comment]
谢谢，今天默认脚本安装也没问题了，谢谢
