### ISSUE TITLE
> 强制使用v6试试-【结论: 2023.6.21 wgcf 一键脚本 V2.52，可以使用 client proxy 模式双栈，在服务端xray里设置】

### ISSUE THREAD

**Issue by founderqiang** [fscarmen/warp#398]
> 强制使用v6试试
> 
> ```
> curl -s6m8 ifconfig.me --interface wgcf
> ```

用warp client proxy模式，在xray里设置分流出站访问chatgpt，也是转圈
昨天用了这个命令能正常访问，今天晚上又开始转圈了
直接用脚本的前三个选项添加warp网络接口倒是一直能正常访问

_Originally posted by @PP-19 in https://github.com/fscarmen/warp/issues/353#issuecomment-1518064710_

**Comment by fscarmen** [comment]
试试用 xray 里直接使用warp看看，加入了 reserved 和 mtu
https://github.com/fscarmen/warp/blob/main/README.md#%E9%80%9A%E8%BF%87-warp-%E8%A7%A3%E9%94%81-chatgpt-%E7%9A%84%E6%96%B9%E6%B3%95
