### ISSUE TITLE
开启IPV6 以后 与docker端口映射冲突，导致docker容器的应用无法访问

### ISSUE THREAD

**Issue by fengcharles** [fscarmen/warp#40]
测试了一下发现关闭了IPv6就正常了，有没有单独关闭IPv6 只开启ipv4的方法？

**Comment by fscarmen** [comment]
你的意思是你的vps原来只有ipv4，你想弄个ipv4是warp，不需要ipv6的方案？

**Comment by fengcharles** [comment]
> 你的意思是你的vps原来只有ipv4，你想弄个ipv4是warp，不需要ipv6的方案？

对的 就是这个意思。 因为我发现开启IPV6 后，我的docker对外暴露的端口，均无法正常访问，我去docker社区也问过了，确实存在这个问题，要么不用ipv6 要么不用docker

**Comment by fscarmen** [comment]
> 对的 就是这个意思

应该没有问题的，我试试改改配置文件先

**Comment by fscarmen** [comment]
先按双栈的正常安装，运行完脚本，正常获取双栈 WARP ip 后运行以下2条指令

```
sed -i "/::\/0/d" /etc/wireguard/wgcf.conf
systemctl restart wg-quick@wgcf
```

然后你用这两条指令看看 IPv4 和 IPv6的情况
```
curl -s4m3 ip.gs
curl -s6m3 ip.gs
```

**Comment by fengcharles** [comment]
> 



> 先按双栈的正常安装，运行完脚本，正常获取双栈 WARP ip 后运行以下2条指令
> 
> ```
> sed -i "/::\/0/d" /etc/wireguard/wgcf.conf
> systemctl restart wg-quick@wgcf
> ```
> 
> 然后你用这两条指令看看 IPv4 和 IPv6的情况
> 
> ```
> curl -s4m3 ip.gs
> curl -s6m3 ip.gs
> ```
试了一下  systemctl restart wg-quick@wgcf 这个命令以后，网络变成了巨卡巨慢的状态，最后只能使用warp这个命令重新安装，等了好久才重新启动起来

**Comment by fengcharles** [comment]
> 

从错误状态来看，是很多域名都解析了导致的。

**Comment by fengcharles** [comment]
![image](https://user-images.githubusercontent.com/6244198/146314674-6fadca38-f3da-4372-b427-4ef26d659dc7.png)

**Comment by fscarmen** [comment]
由于我还没有试过这个情况，我要试试其稳定性

**Comment by fscarmen** [comment]
由于我还没有试过这个情况，我要试试其稳定性

**Comment by fscarmen** [comment]
> 对的 就是这个意思。 因为我发现开启IPV6 后，我的docker对外暴露的端口，均无法正常访问，我去docker社区也问过了，确实存在这个问题，要么不用ipv6 要么不用docker

我暂时试到的结果，即使不要ipv6，只开ipv4的情况下，仍然访问不了docker对外开放的端口。至于网络慢暂未遇到

**Comment by fengcharles** [comment]
> > 对的 就是这个意思。 因为我发现开启IPV6 后，我的docker对外暴露的端口，均无法正常访问，我去docker社区也问过了，确实存在这个问题，要么不用ipv6 要么不用docker
> 
> 我暂时试到的结果，即使不要ipv6，只开ipv4的情况下，仍然访问不了docker对外开放的端口。至于网络慢暂未遇到

嗯，我看了下 只要开启warp就会导致docker对外暴露的端口全部转到tpc6上，试了很多方法也不行，目前我先决定不用docker运行了。

**Comment by fscarmen** [comment]
如果在ipv6 only的机器上安装docker，再用原生ipv6的地址访问是没有问题的。问题就出在ipv4这里，我已经发贴去 cloudflare的社区问，如何把 docker 用到的 172.17.0.1/16，排除在 warp 外，我试过是可行的
具体是配置文件里有个 AllowedIPs = 0.0.0.0/0 即是所有 IPv4 的地址，我改为 ip.gs 的 AllowedIPs = 147.78.176.176/32，即便开启了 warp，docker也是正常的，只有 ip.gs通过warp，其他网都走回原生的IP
这样的黑白名单机制不符合我们的使用场景

https://community.cloudflare.com/t/how-to-set-the-excluded-ips-in-warp-profile-wgcf-profile-conf/336919

**Comment by fengcharles** [comment]
> 如果在ipv6 only的机器上安装docker，再用原生ipv6的地址访问是没有问题的。问题就出在ipv4这里，我已经发贴去 cloudflare的社区问，如何把 docker 用到的 172.17.0.1/16，排除在 warp 外 方案我试过是可行的，具体方法是下： 配置文件 wgcf.conf 里有项 AllowedIPs = 0.0.0.0/0， 即是warp 接管所有ipv4，我改为 ip.gs 的 AllowedIPs = 147.78.176.176/32，即便开启了 warp，docker可以正常访问，只有 ip.gs通过warp，其他网都走回原生的IP
> 
> 但这样的黑白名单机制不符合我们的使用场景
> 
> https://community.cloudflare.com/t/how-to-set-the-excluded-ips-in-warp-profile-wgcf-profile-conf/336919

嗯，我暂时先不用docker了，避免一直折腾导致服务器长时间不可用。回头再等等看其他更好得方案。

**Comment by fscarmen** [comment]
可以试试最新的iptable+dnsmasq+ipset方案，把需要走warp的网络域名添加进去，这样就不影响docker映射出来的端口了

**Comment by CrazyMed** [comment]
我也是用docker起了ss rust。发展只要开双栈或者ipv4就没法用ss。但是之前好像没用映射端口docker 直接net到host上就能用ipv4？

**Comment by fscarmen** [comment]
host模式是可以的，之前试过了

**Comment by CrazyMed** [comment]
> host模式是可以的，之前试过了

那太好了。明天改过来
