### ISSUE TITLE
[help wanted 求助]: 没一会就断网，重启也没网。

### ISSUE THREAD

**Issue by npzs** [fscarmen/warp#401]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

使用最新版本安装了wgcf双栈，并使用 token 形式升级到 teams 账户（我自己注册的zreo trust），最开始的时候一切正常。
但是大概2-3个小时之后，突然没网了，然后服务器无数次重启，都是断网（但SSH连接可用）。
curl 测试 https://www.cloudflare.com/cdn-cgi/trace，无论v4v6全是没有任何反馈。

使用 warp n 重新获取，2-3次提示成功，查看账户为正常的 plus（curl 测试 https://www.cloudflare.com/cdn-cgi/trace，4/6都正常），可大概10几分钟，又断网了，此时再使用  warp n 又提示成功，但是这时再去 trace，不管4还是6，均显示 off，也就是再获取不到了（只是脚本提示成功）
再重启，没网，只能 warp n 玩一会，如此循环……

### Log / 日志信息

Last login: Sat May 20 18:16:42 2023 from 39.152.xxx.xxx
root@xxxx:~# curl -4skm 8 https://www.cloudflare.com/cdn-cgi/trace
root@xxxx:~# curl -6skm 8 https://www.cloudflare.com/cdn-cgi/trace
root@xxxx:~# warp n
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 已成功获取 WARP Teams 网络
 IPv4:104.28.xxx.xxx  美国 Cloudflare, Inc.
 IPv6:2a09:bac5:636d:xxxxxxxxx  美国 Cloudflare
root@xxxx:~# curl -4skm 8 https://www.cloudflare.com/cdn-cgi/trace
fl=619f97
h=www.cloudflare.com
ip=104.28.xxx.xxx
ts=1684607014.372
visit_scheme=https
uag=curl/7.81.0
colo=LAX
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=plus
gateway=off
rbi=off
kex=X25519
root@xxxx:~# curl -6skm 8 https://www.cloudflare.com/cdn-cgi/trace
fl=619f97
h=www.cloudflare.com
ip=2a09:bac5:636b:xxxxxx
ts=1684607018.565
visit_scheme=https
uag=curl/7.81.0
colo=LAX
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=plus
gateway=off
rbi=off
kex=X25519
root@xxxx:~# curl -4skm 8 https://www.cloudflare.com/cdn-cgi/trace
fl=447f127
h=www.cloudflare.com
ip=149.248.xxx.xxx
ts=1684608079.291
visit_scheme=https
uag=curl/7.81.0
colo=LAX
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
root@xxxx:~# curl -6skm 8 https://www.cloudflare.com/cdn-cgi/trace
fl=445f224
h=www.cloudflare.com
ip=2001:19f0:6000:9fc2:xxxxxxxx
ts=1684608082.926
visit_scheme=https
uag=curl/7.81.0
colo=LAX
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
root@xxxx:~# warp n
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试
 第2次尝试
 已成功获取 WARP Teams 网络
 IPv4:104.28.xxx.xxx  美国 Cloudflare, Inc.
 IPv6:2a09:bac5:6368:xxxxxxx  美国 Cloudflare
root@xxxx:~# curl -4skm 8 https://www.cloudflare.com/cdn-cgi/trace
fl=446f112
h=www.cloudflare.com
ip=149.248.xxx.xxx
ts=1684608110.16
visit_scheme=https
uag=curl/7.81.0
colo=LAX
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
root@xxxx:~# curl -6skm 8 https://www.cloudflare.com/cdn-cgi/trace
fl=619f23
h=www.cloudflare.com
ip=2001:19f0:6000:9fc2:xxxxxxxx
ts=1684608114.633
visit_scheme=https
uag=curl/7.81.0
colo=LAX
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
root@xxxx:~# reboot
root@xxxx:~# Connection to 149.248.xxx.xxx closed by remote host.
Connection to 149.248.xxx.xxx closed.

>ssh -i .ssh\xxxxx root@149.248.xxx.xxx
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of 2023年 05月 20日 星期六 18:18:16 UTC

  IPv4 address for enp1s0: 149.248.xxx.xxx
  IPv6 address for enp1s0: 2001:19f0:6000:9fc2:xxxxxxxx
  IPv4 address for wgcf:   172.16.0.2
  IPv6 address for wgcf:   2606:4700:110:89dc:xxxxxxxxxxx

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

Last login: Sat May 20 18:18:16 2023 from 39.152.xxx.xxx
root@xxxx:~# curl -4skm 8 https://www.cloudflare.com/cdn-cgi/trace
root@xxxx:~# curl -6skm 8 https://www.cloudflare.com/cdn-cgi/trace
root@xxxx:~#

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
使用免费或者 plus 账户也会有同样的问题吗？

**Comment by npzs** [comment]
> 使用免费或者 plus 账户也会有同样的问题吗？

这还没没测试过，我 warp+ 只注册的时候提供了许可，直接就覆盖团队账户了，我等下晚上试试。
（不过说起这个，我当时是上一个版本用的本脚本，上一个版本我登录团队之后，不管想切换回warp还是warp+，输出窗口只有一句类似正在切换的提示，然后就卡住不动了，就是说无法从团队版切换为其他版本，就是因为这个原因，昨天直接完全卸载了，重新安装，才发现了这个最新的版本。。。
所以新版能否切换等晚上回去试试先）

**Comment by npzs** [comment]
> 使用免费或者 plus 账户也会有同样的问题吗？

新版问题依旧，同样不能从团队版切换到其他版本：
`root@xxxx:~# warp a

 所有依赖已存在，不需要额外安装

 检查环境中……

 当前账户类型是: WARP teams
 1. 变更为 free 账户
 2. 变更为 WARP+ 账户
 3. 更换为另一个 Teams 账户
 0. 退出脚本

 请选择: 2
 请输入WARP+ License: 164C2UgF-xxxxxxxxxxxxxx
 请自定义 WARP+ 设备名 (如果不输入，默认为 [WARP]):

 升级 WARP+ 账户中……

`

卡在这个提示已经10分钟了。

**Comment by fscarmen** [comment]
我这里可以哦，两台机器都行，暂时试不出什么问题呢
```
root@chuncheon2:~# warp a 

 所有依赖已存在，不需要额外安装 

 检查环境中…… 

 当前账户类型是: WARP teams      
 1. 变更为 free 账户
 2. 变更为 WARP+ 账户
 3. 更换为另一个 Teams 账户
 0. 退出脚本 

 请选择: 2
 请输入WARP+ License: N8*****jg-sS9jD314-5o****9F
 请自定义 WARP+ 设备名 (如果不输入，默认为 [WARP]): test

 升级 WARP+ 账户中…… 

 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 已成功获取 WARP+ 网络 
 IPv4:144.24.67.244  韩国 Oracle Corporation
 IPv6:2a09:bac5:4774:155::22:83  韩国 Cloudflare 
 已变更为 WARP+ 账户
 设备名: test
 剩余流量: 24.59 PB 
root@chuncheon2:~# warp a 

 所有依赖已存在，不需要额外安装 

 检查环境中…… 

 当前账户类型是: WARP +  
 剩余流量: 24.59 PB
 1. 变更为 free 账户
 2. 变更为另一个 WARP+ 账户
 3. 变更为 Teams 账户
 0. 退出脚本 

 请选择: 3

 1. 通过在线文件
 2. 使用 token (可通过 https://web--public--warp-team-api--coia-mfs4.code.run 轻松获取)
 3. 手动输入 private key 和 IPv6
 4. 共享 teams 账户 (默认) 

 请选择: 2
 token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjliNmZkZmJmZmVhOGZjNDVkYjUxMjAzMGE0ZjM5Y2IyMTY0MWZmYzUwZjcwMDgzOTEyYjhkMGEwYmY2NTcxOGQifQ.eyJhdWQiOlsiN2JhZmVlYjJhYmQyMzBlNzI1NDFlODk5MGYwZWM2MWNkMThhNWI0OTI5MmFjY2E3ZTQzNTI1MzNiY2EwM2RhOCJdLCJlbWFpbCI6Inhmc3RsaXdpQG1haWxwYXJzZXIuaW8iLCJleHAiOjE2ODQ2NzUxOTAsImlhdCI6MTY4NDY3NTEzMCwibmJmIjoxNjg0Njc1MTMwLCJpc3MiOiJodHRwczovL2ZzY2FybWVuMy5jbG91ZGZsYXJlYWNjZXNzLmNvbSIsInR5cGUiOiJhcHAiLCJpZGVudGl0eV9ub25jZSI6IlFwTnliZUF4TGVwWlZTc3AiLCJzdWIiOiJjZTA3YjdlNy0zMDAzLTU1MTgtODRiZi0zZjcwYTM3YTBmZDMiLCJ3YXJwIjp0cnVlLCJpcCI6IjM0LjE1MC4xMjMuNTYiLCJhY2NvdW50X2lkIjoiYWNlZTMwYzk1OWMyMGVjN2Q1NjQyNzZkZGUyODAwZWMiLCJpZGVudGl0eSI6eyJlbWFpbCI6Inhmc3RsaXdpQG1haWxwYXJzZXIuaW8ifSwiY291bnRyeSI6IkhLIn0.C63-QIfhSq7imY9fHrLCvaIDyydJ2rl2nOnqeYWjckQU39GLvioqnv2-EgpdQ16J0jOUx4XK6T671it_O5e9TMor_QnE79uWT56GiaBEIc4zadJ0rUkM3PUi1KxPUODuglgfvwLcX75SMr6Fp9W2JCnOpQ0-VjnWzk3jmFurdgPBoqu8AqY-K2On0IoQVIZNleFYh8RzdnLKcJgs52KdhBZnNq2EpetetjCzxXRVJfcuOSBmZm8xJiux9EcAIKJzV3XUodmNPQaaVq6JzrU6VoxGggUcMFroz-T1zeEyH31WC4aRk0_y5XX7nOMc7bojefONi-hmlclNOrPI0HPlhw

 请确认Teams 信息
 Private key    : yAiF8JrFyIyeAuQ25+2+Nmz8f+9Hn9NSI68u4AzX6kM= ( 符合 √ )
 Address IPv6   : 2606:4700:110:81eb:2c7c:7263:17f1:e72d/128 ( 符合 √ ) 

 确认请按 [y]，其他按键则使用免费账户: y
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 已成功获取 WARP Teams 网络 
 IPv4:144.24.67.244  韩国 Oracle Corporation
 IPv6:2a09:bac5:4770:155::22:df  韩国 Cloudflare 
 已变更为 WARP teams 账户 
```

**Comment by npzs** [comment]
> 我这里可以哦，两台机器都行，暂时试不出什么问题呢
> 
> ```
> root@chuncheon2:~# warp a 
> 
>  所有依赖已存在，不需要额外安装 
> 
>  检查环境中…… 
> 
>  当前账户类型是: WARP teams      
>  1. 变更为 free 账户
>  2. 变更为 WARP+ 账户
>  3. 更换为另一个 Teams 账户
>  0. 退出脚本 
> 
>  请选择: 2
>  请输入WARP+ License: N8*****jg-sS9jD314-5o****9F
>  请自定义 WARP+ 设备名 (如果不输入，默认为 [WARP]): test
> 
>  升级 WARP+ 账户中…… 
> 
>  后台获取 WARP IP 中,最大尝试5次……
>  第1次尝试 
>  已成功获取 WARP+ 网络 
>  IPv4:144.24.67.244  韩国 Oracle Corporation
>  IPv6:2a09:bac5:4774:155::22:83  韩国 Cloudflare 
>  已变更为 WARP+ 账户
>  设备名: test
>  剩余流量: 24.59 PB 
> root@chuncheon2:~# warp a 
> 
>  所有依赖已存在，不需要额外安装 
> 
>  检查环境中…… 
> 
>  当前账户类型是: WARP +  
>  剩余流量: 24.59 PB
>  1. 变更为 free 账户
>  2. 变更为另一个 WARP+ 账户
>  3. 变更为 Teams 账户
>  0. 退出脚本 
> 
>  请选择: 3
> 
>  1. 通过在线文件
>  2. 使用 token (可通过 https://web--public--warp-team-api--coia-mfs4.code.run 轻松获取)
>  3. 手动输入 private key 和 IPv6
>  4. 共享 teams 账户 (默认) 
> 
>  请选择: 2
>  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjliNmZkZmJmZmVhOGZjNDVkYjUxMjAzMGE0ZjM5Y2IyMTY0MWZmYzUwZjcwMDgzOTEyYjhkMGEwYmY2NTcxOGQifQ.eyJhdWQiOlsiN2JhZmVlYjJhYmQyMzBlNzI1NDFlODk5MGYwZWM2MWNkMThhNWI0OTI5MmFjY2E3ZTQzNTI1MzNiY2EwM2RhOCJdLCJlbWFpbCI6Inhmc3RsaXdpQG1haWxwYXJzZXIuaW8iLCJleHAiOjE2ODQ2NzUxOTAsImlhdCI6MTY4NDY3NTEzMCwibmJmIjoxNjg0Njc1MTMwLCJpc3MiOiJodHRwczovL2ZzY2FybWVuMy5jbG91ZGZsYXJlYWNjZXNzLmNvbSIsInR5cGUiOiJhcHAiLCJpZGVudGl0eV9ub25jZSI6IlFwTnliZUF4TGVwWlZTc3AiLCJzdWIiOiJjZTA3YjdlNy0zMDAzLTU1MTgtODRiZi0zZjcwYTM3YTBmZDMiLCJ3YXJwIjp0cnVlLCJpcCI6IjM0LjE1MC4xMjMuNTYiLCJhY2NvdW50X2lkIjoiYWNlZTMwYzk1OWMyMGVjN2Q1NjQyNzZkZGUyODAwZWMiLCJpZGVudGl0eSI6eyJlbWFpbCI6Inhmc3RsaXdpQG1haWxwYXJzZXIuaW8ifSwiY291bnRyeSI6IkhLIn0.C63-QIfhSq7imY9fHrLCvaIDyydJ2rl2nOnqeYWjckQU39GLvioqnv2-EgpdQ16J0jOUx4XK6T671it_O5e9TMor_QnE79uWT56GiaBEIc4zadJ0rUkM3PUi1KxPUODuglgfvwLcX75SMr6Fp9W2JCnOpQ0-VjnWzk3jmFurdgPBoqu8AqY-K2On0IoQVIZNleFYh8RzdnLKcJgs52KdhBZnNq2EpetetjCzxXRVJfcuOSBmZm8xJiux9EcAIKJzV3XUodmNPQaaVq6JzrU6VoxGggUcMFroz-T1zeEyH31WC4aRk0_y5XX7nOMc7bojefONi-hmlclNOrPI0HPlhw
> 
>  请确认Teams 信息
>  Private key    : yAiF8JrFyIyeAuQ25+2+Nmz8f+9Hn9NSI68u4AzX6kM= ( 符合 √ )
>  Address IPv6   : 2606:4700:110:81eb:2c7c:7263:17f1:e72d/128 ( 符合 √ ) 
> 
>  确认请按 [y]，其他按键则使用免费账户: y
>  后台获取 WARP IP 中,最大尝试5次……
>  第1次尝试 
>  第2次尝试 
>  已成功获取 WARP Teams 网络 
>  IPv4:144.24.67.244  韩国 Oracle Corporation
>  IPv6:2a09:bac5:4770:155::22:df  韩国 Cloudflare 
>  已变更为 WARP teams 账户 
> ```

关于不能切换账户的问题，我差不多的找到原因了，说到底还是跟我最终的问题（团队账户无法正常上网有关），首先我看了眼脚本代码，跟切换到waro+有关的应该是这段：

`    cp -f /etc/wireguard/wgcf-account.toml /etc/wireguard/account-temp.toml || exit 1
    sed -i "s#license_key.*#license_key = \'$LICENSE\'#g" /etc/wireguard/account-temp.toml
    wgcf update --name "$NAME" --config /etc/wireguard/account-temp.toml > /etc/wireguard/info-temp.log 2>&1
    # 升级时回显 429 说明触发反滥用风控, 还有 404 Not Found / TimeOut / timed out 等情况，可以通过不停的申请来处理; 回显 400 说明使用的终端设置超过5台, 维持原账户处理
    while grep -qisE "429 Too Many Requests|404 Not Found|time.*out" /etc/wireguard/info-temp.log; do
      wgcf update --name "$NAME" --config /etc/wireguard/account-temp.toml > /etc/wireguard/info-temp.log 2>&1
    done`

我看到目录里已经生成了 account-temp.toml，但就是因为我没网，下面的 wgcf update 一直没有返回正常的结果，就卡在那里了，好像连 while 循环都没进去，因为我查看了 info-temp.log，里面只有这么一句：

2023/05/21 14:00:52 Using config file: /etc/wireguard/account-temp.toml

也就是卡在那就不动了，所以归根结底得解决我网络的问题，不过老板也可以看看遇到这种情况脚本能不能判断出来，给个窗口提示也好。。。不然不仔细研究都不知道咋回事

**Comment by npzs** [comment]
我现在重启了服务器，凑合着团队版可以正常使用的这段时间，再次执行 warp a，在网络正常的情况下，唰唰的就把账户切换了，我现在是 warp+，我使用一段时间，再看看网络会不会掉。

**Comment by fscarmen** [comment]
> 
> 也就是卡在那就不动了，所以归根结底得解决我网络的问题，不过老板也可以看看遇到这种情况脚本能不能判断出来，给个窗口提示也好。。。不然不仔细研究都不知道咋回事

我估计是卡在这步，还没有到 while 那里的不断循环，你可以用 bash -x warp a  看看详细运行的，如果是这样，就没有办法了，因为，wgcf 不是我弄的，他卡死估计没有做相应的处理。

**Comment by npzs** [comment]
> > 也就是卡在那就不动了，所以归根结底得解决我网络的问题，不过老板也可以看看遇到这种情况脚本能不能判断出来，给个窗口提示也好。。。不然不仔细研究都不知道咋回事
> 
> 我估计是卡在这步，还没有到 while 那里的不断循环，你可以用 `bash -x warp a` 看看详细运行的，如果是这样，就没有办法了，因为，wgcf 不是我弄的，他卡死估计没有做相应的处理。

不是呀，可以变相解决嘛，比如在执行 wgcf update 之前，就有个网络检测就可以啦（貌似curl 获取IP 就行），如果是我这种网络不通的情况，直接给错误提示就好了，因为网不通账户是不可能切换成功的，不必执行。

**Comment by npzs** [comment]
> 使用免费或者 plus 账户也会有同样的问题吗？

真是奇了怪了，我切换到warp+账户，昨晚到现在运行17-18个小时了，还显示为plus，也不掉线断网了，这咋回事，不让我用team账户呢。。。

**Comment by fscarmen** [comment]
关闭开机启动是 `systemctl disable wg-quick@wgcf`

**Comment by yzhpxd** [comment]
我是升级的WARP teams，选择2，ipv6套warp，正常。就是面板分流不会，求大神help

**Comment by clbby** [comment]
关闭防火墙 

> > 使用免费或者 plus 账户也会有同样的问题吗？
> 
> 完咯老板，我前天说的吧，我把账户设置成 warp+ 了，当时看着挺好的也不掉线断网了，可我隔了一天忙别的事，刚才登录看还是好好的，我以为真的解决了，可我刚才重启了一下，启动完连接SSH，再去 curl [https://www.cloudflare.com/cdn-cgi/trace，不管是v4还是v6，又是没网了（不影响SSH），我在服务器上PING别的地址直接卡住一个包也出不去，但是我在本地机器可以PING通我的服务器。](https://www.cloudflare.com/cdn-cgi/trace%EF%BC%8C%E4%B8%8D%E7%AE%A1%E6%98%AFv4%E8%BF%98%E6%98%AFv6%EF%BC%8C%E5%8F%88%E6%98%AF%E6%B2%A1%E7%BD%91%E4%BA%86%EF%BC%88%E4%B8%8D%E5%BD%B1%E5%93%8DSSH%EF%BC%89%EF%BC%8C%E6%88%91%E5%9C%A8%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8APING%E5%88%AB%E7%9A%84%E5%9C%B0%E5%9D%80%E7%9B%B4%E6%8E%A5%E5%8D%A1%E4%BD%8F%E4%B8%80%E4%B8%AA%E5%8C%85%E4%B9%9F%E5%87%BA%E4%B8%8D%E5%8E%BB%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E5%9C%A8%E6%9C%AC%E5%9C%B0%E6%9C%BA%E5%99%A8%E5%8F%AF%E4%BB%A5PING%E9%80%9A%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E3%80%82) 而我执行 warp n 第三次会提示获取成功，此时看起来就正常了，但是不出意外的话，过一段时间又会出现团队版账户那样断了的情况（而且有一个直观的感觉，凡是出问题的时候，好像服务器就有点卡，像是在执行什么循环或其他的东西没执行成功一样，终端窗口确定一个命令，卡顿一下才开始，而没有wgcf或者wgcf正常的时候，终端操作都是十分流畅的）。
> 
> 我想问下，wgcf安装成功后，都有哪里的代码跟开机启动服务有关啊，我想试试屏蔽这些代码，重启VPS后手动开启，来进一步找找原因。
> 
> （更新一下，刚才我不是说 warp n 能正常上网了吗，当时我看脚本提示成功就没测试，我来发完回复又 curl 了一下，结果v4v6都显示的 warp off，也就是说，我能联网只是服务器本身的IP给正常启用了，而 warp 根本没成功启动起来。。）
我是关闭防火墙后warp 0再开启就显示warp=on了 版本Ubuntu 22.04.2 LTS

**Comment by npzs** [comment]
> 关闭防火墙
> 

没用，因为我安装脚本之前就已经关了：
`ufw disable`
VPS面板的防火墙我从来就没启用过，系统里这样就行了吧，可还是出上面的问题。

**Comment by npzs** [comment]
> 关闭开机启动是 `systemctl disable wg-quick@wgcf`

老板，貌似我有进展了。
查看wgcf官方issues的时候，发现有不少人遇到跟我类似的问题，好像当初wgcf安装的时候也给设置最大mtu，很大可能就是它引起的。
部分用户反应改小了就好了，我跟着改了一下，目前2天多了，team账户一直连接的没有断开。

目前还不敢武断的判定一定是mtu，有待后续观察吧，我也先改成1360了，今天再加点看看情况。
（vltur 双栈vps开的双ip warp，是不是测试最佳mtu的时候取值高了。我记不太清，好像改之前，当时是warp+账户，默认脚本给我设置的是1400，而我先升级了team账户，脚本就把mtu设置成1420了。。。同一个vps的不同warp账户的最佳mtu还会变的？）
目前从1360设置为1384再观察几天吧

**Comment by fscarmen** [comment]
脚本升级，应该不会改原来的 MTU值的哦，只处理 privatekey 和 ipv6 address，同时现在 MTU是根据以下的介绍处理的：
https://lists.zx2c4.com/pipermail/wireguard/2017-December/002201.html

wireugard的 ipv6要留80字节，ipv4要留60字节，我取大的80，这样 v4 和 v6 都通用了。
具体是使用 ping 找出 MTU值，再减80得出 wireugard里设置的 mtu 值，
这个方法使用了二年多了，也的确时不时有用户反馈断连接，我试过加上  `PersistentKeepalive = 30` ，好像效果也不好。
你的试验倒是一个好尝试，期待回头分享一下进一步的结果。

**Comment by fscarmen** [comment]
> 同一个vps的不同warp账户的最佳mtu还会变的

我理解是不会的，所以脚本升级为teams也没有改mtu的，具体我要再试试，很久没有动过这块了。

**Comment by npzs** [comment]
> > 同一个VPS的不同warp账户的最佳mtu还会变的
> 
> 我刚刚试了，升级为 teams 账户，脚本并不会改 MTU 值，我是在一台壳上试的，刚安装好 free 账户之后 ，MTU 值是 1420，我改为 1280，再升级为teams 账户，该值仍旧为刚才手动修改的 1280。即是升级teams，脚本不会动 MTU 值的。

这玩意真的很难快速定位问题，慢慢来吧。
首先，我先是warp+，看wgcf那里帖子说到mtu的时候，我查了下配置文件，但是我确实记不清了。。。我印象里是1400，因为这个过程很短，我就给升级到team了，我就是寻思着，如果能解决问题，我最终还是想用team账户的，team确实显示着1420。
所以改账户之后mtu变了的事我确实拿不准，也没去读代码，反正对于我目前，这个并不要紧，嘿嘿。

其实在使用你的脚本之前，我就读过wgcf里的一些资料，找不到链接了，但是好像有一篇我从上下文来理解就是比较提倡改最佳mtu的，但是后续反馈也出现很多问题，可能与硬件有关也说不准，所以后来直到现在，他好像并不推荐改了，就是说比较懂的可以自己测试着改，普通用户他建议就用最初的默认值，好像各种系统还不一样，没记错的话安卓只有1280好像。

而我现在有8成把握，我的问题好像就跟这个mtu有关系，因为上次发帖的时候，我1360运行两天正常，我给改1384了，结果前天吧，看服务器断了，我又给改1372了，刚才连上去看了看，还正常没断。

所以我现在有个怀疑，就是测试最佳mtu那套代码好像并不完美，我看过几个脚本的代码，几乎都是一套逻辑，好像最初是从一个国外脚本提取出来的，我知道它的原理是提取最大的那个发送临界值，可我觉着在某些系统上漏掉了什么，导致那个结果预留的不对，应该再小一点，或者……应该交给每个用户单独测试自己的，总之就有这么个想法，没有证据，哈哈。

**Comment by npzs** [comment]
PersistentKeepalive = 30
这个是保活的吧，我看wgcf那边也有人提到跟这个有关，但是目前我还没动它，好像mtu就能解决我的问题，看几天再说

**Comment by npzs** [comment]
> 嗯，我十分期待你的结果，我翻了一下 wgcf 项目关于这块的讨论，看到wgcf的作者说1280不会差，你试试，如果仍然稳定，我马上改。
> 
> [ViRb3/wgcf#40](https://github.com/ViRb3/wgcf/issues/40)

今天是我测试的第十二天了，我想应该有资格回复：
设置最佳mtu应该会对部分主机的wgcf稳定运行造成影响，自从降低了mtu之后，目前我的主机warp服务一直稳定运行，没有出现断网情况。

以前看过某脚本，它检测最佳mtu是在安装warp之前，就是测试物理网卡的mtu，可我觉着测试虚拟出来新的warp网卡才对吧，不应该是找到发送网卡出站的最大传输单元才符合逻辑么？
不知道咱这个是什么时机测试的最佳mtu，我不是很懂，但觉着跟这个有关。
![Untitled(1)](https://github.com/fscarmen/warp/assets/130886317/c7982fb3-1c5a-4a46-ac5e-613c812e8c22)

目前如图，我设置的是1372，我发现1384会断，只是后来忙别的，一直没再逐步增加，这个1372应该并不是我能稳定运行的最大值，应该还能加点，不过找到最大值的意义到底有没有用，还真不清楚。

**Comment by fscarmen** [comment]
> 以前看过某脚本，它检测最佳mtu是在安装warp之前，就是测试物理网卡的mtu，可我觉着测试虚拟出来新的warp网卡才对吧，不应该是找到发送网卡出站的最大传输单元才符合逻辑么？

现在主流的脚本，包括我的，p3terx的，misaka的和甬哥的，均是一样的流程，测试原生的物理网卡MTU值，再根据 wireguard 协议头需要占用的字节数（IPv4是60，IPv6是80，取较大值）80来扣减得出来的 warp MTU值。
你提到的在warp网上测有个矛盾就是  warp 的配置文件里要提前设置一个 MTU 值，比如设置了较低的1280，再测意思就完全没有意义了，因为也只能是1280了。

> 设置最佳mtu应该会对部分主机的wgcf稳定运行造成影响，自从降低了mtu之后，目前我的主机warp服务一直稳定运行，没有出现断网情况。

我想了解一下，脚本检测出的 MTU 值是多少，我想看看你设置的 1372 和脚本测出来的有多少差异，其实这个 MTU 对于实际网速几乎没有影响的，wgcf 的作者做过测试，所以为了稳定性，我直接多减一些，现在80不稳定就减100，再不行减120这样。

**Comment by cat9999sss** [comment]
经过测试mtu会自动变成1420

**Comment by fscarmen2** [comment]
> 经过测试mtu会自动变成1420

我要找找原因

**Comment by cat9999sss** [comment]
只能用笨办法解决问题，定时检测网络：

`#!/bin/bash

# 定义外网地址
external_host="www.google.com"

# 定义日志文件路径
log_file="/path/to/log.txt"

# 测试外网连接
function test_external_connection() {
  curl -sSf $external_host > /dev/null
  return $?
}

# 检测外网连接并执行相应操作
function check_external_connection() {
  if test_external_connection; then
    echo "$(date): 外网通畅" >> $log_file
    echo "外网通畅"
  else
    echo "$(date): 外网不通" >> $log_file
    run_warp_go
  fi
}

# 执行warp-go命令
function run_warp_go() {
  echo "运行warp-go命令"
  # 替换为运行"warp-go o"的实际命令
  warp-go o
}

# 循环执行检测
while true; do
  check_external_connection
  sleep 5
done
`
