### ISSUE TITLE
warp-go脚本无法完成账号注册或登录 [Bug]: -【结论: 2023.5.21 18:20 已处理，引入官方 api 注册，当 warp-go api 出问题时，仍然能注册账户】

### ISSUE THREAD

**Issue by PoPTu** [fscarmen/warp#402]
### Expectation / 预期情况

正常注册免费或登录WARP+账号

### Actual Situation / 实际情况

使用warp-go脚本时，在注册免费或使用WARP+账号时出现问题。
注册免费账号在尝试五次后失败（已测试两台不同地区的主机，不过使用warp脚本可正常注册或使用WARP+，另外这两台主机之前皆使用过warp-go）
Registe WARP+账号五次后也提示失败

PS: 问题首次出现于今日上午（或许因20号更新）

### Reproduction Method / 复现方法

运行warp-go脚本；选项1或2（任意语言）；选项1-8（任意模式）；选项1或3（免费或Plus）

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by PoPTu** [comment]
有一台使用warp-go的主机开始情况和#389 类似，于今天早上突然不能获取IP，于是重装——打算换WARP+账号，结果发现不能注册WARP，开始以为主机被CloudFlare限制了（之前创了一个每5分钟刷新一次适用流媒体IP的小脚本），但在CloudFlare中没有查看到相关文档。然后换了一台主机测试，结果在使用warp-go脚本时又出现错误。后来试了warp脚本，结果它可以正常使用，有点怀疑昨天更新，可是看了下日志也没发现有啥影响。咱这warp和warp-go账号注册有啥不同么？

**Comment by PoPTu** [comment]
又测试了一下，应该和脚本版本完全无关。但这个问题是客观存在的，我换了一台位于米国的从未用过WARP的主机使用warp-go时也注册不了。
![image](https://github.com/fscarmen/warp/assets/134193326/942577c1-b668-453f-bc8b-b420e9f47e0d)
![image](https://github.com/fscarmen/warp/assets/134193326/973f2b07-5e4e-41b4-89fe-599ae403e15d)
用warp脚本可以正常注册账号：
![image](https://github.com/fscarmen/warp/assets/134193326/b20f4fbc-97c5-4538-9595-3c0a80bd9bb8)
![image](https://github.com/fscarmen/warp/assets/134193326/8f724478-eda5-4ddd-a24b-9183be20a4f5)
个人猜测是warp-go所使用的账号注册有点问题，如需其他日志乐意提供！

另外，warp-go的全局模式确实非常漂亮，不过在刷适用流媒体IP时，咱先验证当前IP再刷可能会更好一点

**Comment by fscarmen** [comment]
已处理。 warp-go api 出问题，加入官方的 api 做 plan B

**Comment by fscarmen** [comment]
> 另外，warp-go的全局模式确实非常漂亮

默认是全局的

> 不过在刷适用流媒体IP时，咱先验证当前IP再刷可能会更好一点

说详细点？

**Comment by PoPTu** [comment]
好嘞，根据最近的使用，我觉得脚本在执行Brush WARP IP后立即进行了一次IP刷新，但实际在实际使用中——至少我会用它检测流媒体解锁情况，从某些程度上说首先检测当前IP，再判断是否刷新会更优雅一些。

**Comment by fscarmen** [comment]
现在就是这个逻辑啊。先检测当前是否能解锁，不能解锁再换的啊。

**Comment by PoPTu** [comment]
OK 那相当无敌

**Comment by fscarmen** [comment]
官方的api已经恢复了。
