### ISSUE TITLE
[help wanted 求助]: 使用脚本后，再次运行warp后显示Serving directory /root on port 3000 with ["index.html","index.htm"] index files.

### ISSUE THREAD

**Issue by PhilliCheung** [fscarmen/warp#404]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

使用脚本后，再次运行warp后显示：
Serving directory /root on port 3000 with ["index.html","index.htm"] index files.
有解决方案吗

### Log / 日志信息

Serving directory /root on port 3000 with ["index.html","index.htm"] index files.

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen2** [comment]
没看到过这个报错，你可查下什么意思

**Comment by fscarmen** [comment]
没有看到过这种报错，不知道什么情况，你可查一下如何处理。
