### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by crossxyz** [fscarmen/warp#405]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 
Expecting value: line 1 column 1 (char 0)
 第2次尝试 
Expecting value: line 1 column 1 (char 0)
 第3次尝试 
Expecting value: line 1 column 1 (char 0)
 第4次尝试 
Expecting value: line 1 column 1 (char 0)
 第5次尝试 
Expecting value: line 1 column 1 (char 0)
 注册 WARP free 账户失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp/issues] 

### Log / 日志信息

已搜索但不知道如何解决

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by crossxyz** [comment]
前几天装的时候没问题的，重装系统之后就报错了，现在重装也是像这样报错的

**Comment by crossxyz** [comment]
昨天重装系统几次也没成功，准备摆烂了，结果早上一次就成功了。
之前也安装成功过，可能是玄学问题

**Comment by fscarmen** [comment]
这个报错没有见过，应该是系统的问题。
