### ISSUE TITLE
求助:想用自已的teams帐号， 3. 手动输入 private key 和 IPv6在那里找？

### ISSUE THREAD

**Issue by yzhpxd** [fscarmen/warp#406]
还有面板设置里secretKey":"cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=",
                "address":[
                    "172.16.0.2/32",
                    "fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128"
                ],
                "peers":[
                    {
                        "publicKey":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "endpoint":"engage.cloudflareclient.com:2408

secretKey和publicKey  想用自已teasm帐号的，在那里可以找到。cloudflare里那里找？？

**Comment by fscarmen** [comment]
你通过项目介绍的方式，使用模板器提取文件，又或者使用token方式注册，这样就能获取到你要的 private key 和 ipv6 了
