### ISSUE TITLE
大神能否帮做个ipv6的分流面板，x-ui原版面板，ipv6安装了warp，没有分流-【结论：[各种场景下 xray outbound 和 routing 模板的说明](https://github.com/fscarmen/ArgoX/blob/main/README.md#%E5%90%84%E7%A7%8D%E5%9C%BA%E6%99%AF%E4%B8%8B-xray-outbound-%E5%92%8C-routing-%E6%A8%A1%E6%9D%BF%E7%9A%84%E8%AF%B4%E6%98%8E)】

### ISSUE THREAD

**Issue by yzhpxd** [fscarmen/warp#407]
这是x-ui原版的面板
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by fscarmen** [comment]
这个相当于ipv6的白名单，是 "ipget.net","spotify.com","openai.com" 这几个域名的使用 ipv6，非这三具域名的，使用ipv4，
至于你提到的所有域名优先使用ipv6，不能访问的再到ipv4，这个你最好在xray群问问，知道的话回头告诉声。

**Comment by yzhpxd** [comment]
xray有tg群？学习下

**Comment by yzhpxd** [comment]
用上面的分流代码有个bug,x-ui面板不再统计流量了。

**Comment by yzhpxd** [comment]
chatgpt牛逼，好象可以了，多次问答后。大神看下可以不？

{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "tag": "IP4-out",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      }
    },
    {
      "tag": "IP6-out",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv6"
      }
    },
    {
      "tag": "Warp-out",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv6"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {},
        "sockopt": {
          "mark": 255
        }
      }
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "Warp-out",
        "domain": [
          "ipget.net",
          "spotify.com",
          "openai.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "IP6-out",
        "network": "tcp,udp"
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by yzhpxd** [comment]
有个bug,不能统计流量了，只能用宝塔

**Comment by yzhpxd** [comment]
误会了，chatgpt也没用，是因为https://ipget.net/和https://whatismyipaddress.com/两个统计时间的误差，是warp后的ip变化误以为两个ipv6

**Comment by SherlockChiang** [comment]
在WARP面板中“安装 CloudFlare Client 并设置为 Proxy 模式”
```json
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
        "tag":"WARP",
        "protocol":"socks",
        "settings": {
              "servers": [
                {
                  "address": "127.0.0.1",
                  "port": 40000
                }
              ]
        }
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy":"AsIs",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "type":"field",
        "domain":[
            "domain:openai.com",
            "domain:ai.com",
            "domain:bing.com"
        ],
        "outboundTag":"WARP"
    }
    ]
  },
  "stats": {}
}
```

**Comment by yzhpxd** [comment]
> 

试了下，引号域名打不开，其它的还是走warp后的ipv6

**Comment by fscarmen** [comment]
今天整理了一下 outbound 和 routing 的各式模板，你参考着改啦

https://github.com/fscarmen/ArgoX/blob/main/README.md#各种场景下-xray-outbound-和-routing-模板的说明
