### ISSUE TITLE
[Bug]: DNS过滤导致的WARP注册失败 脚本提示curl failed

### ISSUE THREAD

**Issue by PoPTu** [fscarmen/warp#408]
### Expectation / 预期情况

正常注册WARP

### Actual Situation / 实际情况

账号注册接口存在问题

### Reproduction Method / 复现方法

部分地区WARP　注册接口找不到主机或者注册失败

### More information / 额外信息

<img width="742" alt="20230526_094045791_iOS" src="https://github.com/fscarmen/warp/assets/134193326/b22a0ba9-66b2-4a03-b678-e79ba5a85d19">

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by PoPTu** [comment]
![IMG_1643](https://github.com/fscarmen/warp/assets/134193326/d0ea9655-d8a4-43da-99d8-784d36a2f73a)

**Comment by fscarmen** [comment]
你试试浏览器访问 `https://wg.cloudflare.now.cc` ，如果有private key 和 public key ，那你就在 vps 上运行 `curl -sSL https://wg.cloudflare.now.cc``` 看看能不能获取到，感觉systemd 有问题了，运行一下 `systemctl deamon-reload`

**Comment by PoPTu** [comment]
一针见血 被加载了1Hosts的AdguardHome过滤了 删掉后正常
![image](https://github.com/fscarmen/warp/assets/134193326/3cf67714-1749-4148-8b56-6396cf3b7abc)

**Comment by fscarmen** [comment]
你是通过 token 升级的吧？

**Comment by PoPTu** [comment]
WARP吗？没有用team，用的普通WARP+的key。
