### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by amirng** [fscarmen/warp#409]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

Hello
I need to hide ip server from Spotify using warp project, please help me

### Log / 日志信息

no

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
run `bash menu.sh d` to use global warp ip. and the web you visit will detect not your real server is but the warp ip.

**Comment by amirng** [comment]
Can't this be done only for Spotify?
This is the work of the entire IP server
