### ISSUE TITLE
warp.conf.tmp1文件导致的 ip_info: command not found 或 curl: option -: is unknown [help wanted 求助]: 

### ISSUE THREAD

**Issue by PoPTu** [fscarmen/warp#410]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

似乎是文件权限问题 warp.conf.tmp1 文件的权限问题
在多次运行warp-go -i后，可能出现该文件无法访问的错误（也可能是每小时自动刷新和手动刷IP同时在访问该文件）
出现该问题后WARP将连接失败（无提示，只是不显示IP），之后继而出现ip_info: command not found错误：
![image](https://github.com/fscarmen/warp/assets/134193326/f75926e6-112a-461b-9091-c0d4fdd1d1df)
重装可以解决。

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
奇怪，也不应该会出现 ip_info 错误的啊

**Comment by fscarmen** [comment]
warp-go 官方的 api 有问题，我现在处理下

**Comment by PoPTu** [comment]
多谢 如果有什么可以帮上忙的尽管叫我

**Comment by fscarmen** [comment]
```
systemctl daemon-reload
warp v
```
这样处理后再运行刷ip

**Comment by PoPTu** [comment]
OK 正常了
