### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by rwoss** [fscarmen/warp#411]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Arch - Linux

### Actual Situation / 实际情况

进度 1/3: 安装系统依赖…… 

resolving dependencies...
looking for conflicting packages...
 注册 WARP+ 账户中, 最大尝试5次…… 

Packages (1) openresolv-3.13.1-1
 第1次尝试 

Total Download Size:   0.02 MiB
Total Installed Size:  0.06 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 openresolv-3.13.1-1-any                                       23.2 KiB  20.2 KiB/s 00:01 [####################################################] 100%
(1/1) checking keys in keyring                                                            [####################################################] 100%(1/1) checking package integrity                                                          [####################################################] 100%(1/1) loading package files                                                               [####################################################] 100%(1/1) checking for file conflicts                                                         [####################################################] 100%(1/1) checking available disk space                                                       [####################################################] 100%:: Processing package changes...
(1/1) installing openresolv                                                               [####################################################] 100%:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

 进度 2/3: 已安装 warp-go 

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

grep: warning: stray \ before 0
grep: warning: stray \ before /
grep: warning: stray \ before :
grep: warning: stray \ before :
grep: warning: stray \ before /
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
Failed to restart wg-quick@wgcf.service: Unit wg-quick@wgcf.service not found.
 第2次尝试 
Failed to restart wg-quick@wgcf.service: Unit wg-quick@wgcf.service not found.
 第3次尝试 
Failed to restart wg-quick@wgcf.service: Unit wg-quick@wgcf.service not found.
 第4次尝试 
Failed to restart wg-quick@wgcf.service: Unit wg-quick@wgcf.service not found.
 第5次尝试 
Failed to restart wg-quick@wgcf.service: Unit wg-quick@wgcf.service not found.
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
我对 arch 不太了解，看样子了 grep 命令需要升级一下

**Comment by rwoss** [comment]
我记得之前是能用的 后面更新着好像就不行了

**Comment by fscarmen** [comment]
请自行排查原因了，因为我对arch不熟，也没有这样的环境。
