### ISSUE TITLE
Lack of changing the warp ip [Bug]: 

### ISSUE THREAD

**Issue by mobagheri** [fscarmen/warp#413]
### Expectation / 预期情况

Capability of changing the warp ip

### Actual Situation / 实际情况

when we use from the 6th option of the script to change the warp ip, we get an error.

### Reproduction Method / 复现方法

# warp i

### Log / 日志信息

# warp i
The current Netflix region is US. Confirm press [y] . If you want another regions, please enter the two-digit region abbreviation. (su ch as hk, sg. Default is US): US
2023-05-31 09:27:00 Try 1. Failed. IPV: 104.28.196.104 Russia Cloudflare. Retry after 5 seconds. Brush ip runing time: 0 days 0 hours 0 minutes 7 seconds
2023-05-31 09:27:06 Try 2. Failed. IPv: 104.28.196.104 Russia Cloudflare. Retry after 5 seconds. Brush ip runing time:0 days 0 hours 0 minutes 13 seconds

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
It 's not a bug but the Cloudflare only provides 2-3 warp IPv4 in a region. I suggest you try IPv6.

**Comment by mobagheri** [comment]
> It's not a bug but the CloudFlare only provides 2-3 warp Ipv4 in a region. I suggest you try Ipv6.

Thanks for your reply. But I want to change the location of the IP. For example, I have a server with the Russia location. In your script, automatically the CloudFlare IP with the location of Russia is selected. Actually, I want to change the default IP of your script to the other locations like US or DE. When I want to change the location of the CloudFlare IP with the 6th option of your script, this error has been appeared. I appreciated if you help to change the location of the CloudFlare IP of your script different from the server's location.

**Comment by mobagheri** [comment]
Hi. According to my topic and your statement about the lack of assigning different location IPs to the Russia server, the following script assign Germany CF IP to the Russia server. Could you please add this capability to your script to change the russia Ip to germany or other location like US?

**Comment by fscarmen** [comment]
Are you saying that you want to use the Warp service on a VPS in Russia?

**Comment by mobagheri** [comment]
> Are you saying that you want to use the Warp service on a VPS in Russia?

Absolutely true. I have a 3x-ui panel. I install it on a Russia VPS server. with your WARP script, I want to assign different location IPs to my server, like DE or US IPs. With this method, we can bypass restrictions on a Russian VPS IP.

**Comment by fscarmen** [comment]
Can you lend me a Russian VPS for testing, please?

**Comment by fscarmen** [comment]
fscarmen@gmail.com

**Comment by fscarmen** [comment]
> Hi. According to my topic and your statement about the lack of assigning different location IPs to the Russia server, the following script assigns Germany CF IP to the Russia server. Could you please add this capability to your script to change the Russia IP to Germany or another location like the US?
> 
> https://github.com/yonggekkk/warp-yg
> 
> Thanks.

I have tested this script . It was got the  Russia warp ip too . How did you get the US ip?

**Comment by mobagheri** [comment]
> > Hi. According to my topic and your statement about the lack of assigning different location IPs to the Russia server, the following script assigns Germany CF IP to the Russia server. Could you please add this capability to your script to change the Russia IP to Germany or another location like the US?
> > https://github.com/yonggekkk/warp-yg
> > Thanks.
> 
> I have tested this script . It was got the Russia warp ip too . How did you get the US ip?

I got Germany warp IP (104.28.159.10) with this script. My primary IP was for Russia. I think this script randomly assigns different locations IPs to the VPS Server.

**Comment by fscarmen** [comment]
<img width="697" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/a51f6bc7-dba5-45cf-88c0-0be9bb91e29a">

**Comment by mobagheri** [comment]
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/62703343/244646878-a51f6bc7-dba5-45cf-88c0-0be9bb91e29a.png">

Do you think there is any way to change the WARP IP location?

**Comment by mobagheri** [comment]
Because when we use the WARP script in the Russia server, the changing of the IP doesn't help us to open websites like chatbot and .....

**Comment by fscarmen** [comment]
> > > Hi. According to my topic and your statement about the lack of assigning different location IPs to the Russia server, the following script assigns Germany CF IP to the Russia server. Could you please add this capability to your script to change the Russia IP to Germany or another location like the US?
> > > https://github.com/yonggekkk/warp-yg
> > > Thanks.
> > 
> > 
> > I have tested this script . It was got the Russia warp ip too . How did you get the US ip?
> 
> I got Germany warp IP (104.28.159.10) with this script. My primary IP was for Russia. I think this script randomly assigns different locations IPs to the VPS Server.

You can try one more time. I don't think it could get the Germany IP stably.

**Comment by mobagheri** [comment]
> > > > Hi. According to my topic and your statement about the lack of assigning different location IPs to the Russia server, the following script assigns Germany CF IP to the Russia server. Could you please add this capability to your script to change the Russia IP to Germany or another location like the US?
> > > > https://github.com/yonggekkk/warp-yg
> > > > Thanks.
> > > 
> > > 
> > > I have tested this script . It was got the Russia warp ip too . How did you get the US ip?
> > 
> > 
> > I got Germany warp IP (104.28.159.10) with this script. My primary IP was for Russia. I think this script randomly assigns different locations IPs to the VPS Server.
> 
> You can try one more time. I don't think it could get the Germany IP stably.

OK. For sure. Also, if you find any method for IP changing please inform me about it. Thanks.

**Comment by fscarmen** [comment]
OK. For sure.

**Comment by wulfric93** [comment]
did you found a way to change warp ip ?
