### ISSUE TITLE
[help wanted 求助]: /dev/fd/63: line 46: python3: command not found-【结论：bug，缺少检测python3依赖，已处理】

### ISSUE THREAD

**Issue by lck1115** [fscarmen/warp#414]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

之前好好，不知道什么时候IP掉了，重新获取一直失败。
就卸载了重装，结果就装不上，报错如下：

### Log / 日志信息

进度 1/3: 安装系统依赖…… 

 注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 
/dev/fd/63: line 46: python3: command not found
(23) Failed writing body
 第2次尝试 
/dev/fd/63: line 46: python3: command not found
(23) Failed writing body
 第3次尝试 
/dev/fd/63: line 46: python3: command not found
(23) Failed writing body
 第4次尝试 
/dev/fd/63: line 46: python3: command not found
(23) Failed writing body
 第5次尝试 
/dev/fd/63: line 46: python3: command not found
(23) Failed writing body
 注册 WARP free 账户失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp/issues] 

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 API 获取不到注册信息，脚本退出，问题反馈: [https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
卸载，`systemctl daemon-reload`，重新安装
再不行再卸载，重启，重新安装

**Comment by lck1115** [comment]
reload，reboot都试了，还是报错，
如下：

进度 1/3: 安装系统依赖…… 

下载 warp-go 压缩文件不成功，脚本退出，问题反馈: [https://github.com/fscarmen/warp/issues]
tar (child): /tmp/warp-go.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
chmod: cannot access '/tmp/warp-go': No such file or directory

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 API 获取不到注册信息，脚本退出，问题反馈: [https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
`[ ! -d /tmp ] && echo 'mkdir' &&mkdir -p /tmp || echo "/tmp is exist"` 运行这个看看

**Comment by lck1115** [comment]
/tmp is exist
运行脚本后还是报错。

**Comment by fscarmen** [comment]
分析不出来问题出在哪里了

**Comment by lck1115** [comment]
换别人的脚本，成功了并且获取到了IP。

**Comment by fscarmen** [comment]
能成功就好

**Comment by gaboolic** [comment]
> `[ ! -d /tmp ] && echo 'mkdir' && mkdir -p /tmp || echo "/tmp is exist"` 运行这个看看

我也遇到了这个"下载 warp-go 压缩文件不成功，脚本退出"错误。/tmp路径存在
然后我看了下脚本，脚本里面获取ARCHITECTURE调用了check_arch() { # 判断处理器架构 case $(uname -m)
我手动执行了一下uname -m，输出是aarch64，是不是这个原因？没有能符合的文件名……
我的设备是随身wifi刷的debian……
