### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 01shu** [fscarmen/warp#415]
### Expectation / 预期情况

创建 Socks5 代理失败

### Actual Situation / 实际情况

运行menu脚本，然后安装 WARP 的 Linux Client 和代理模式，报错，提示创建Socks5代理失败

### Reproduction Method / 复现方法

wget -O  menu.sh https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && bash menu.sh

### Log / 日志信息

  /root/glibc-2.28/build/elf/ldconfig  \
			/lib64 /usr/lib64
LD_SO=ld-linux-x86-64.so.2 CC="gcc -B/usr/bin/" /usr/bin/perl scripts/test-installation.pl /root/glibc-2.28/build/
/usr/bin/ld: cannot find -lnss_test2
collect2: error: ld returned 1 exit status
Execution of gcc -B/usr/bin/ failed!
The script has found some problems with your installation!
Please read the FAQ and the README file and check the following:
- Did you change the gcc specs file (necessary after upgrading from
  Linux libc5)?
- Are there any symbolic links of the form libXXX.so to old libraries?
  Links like libm.so -> libm.so.5 (where libm.so.5 is an old library) are wrong,
  libm.so should point to the newly installed glibc file - and there should be
  only one such link (check e.g. /lib and /usr/lib)
You should restart this script from your build directory after you've
fixed all problems!
Btw. the script doesn't work if you're installing GNU libc not as your
primary library!
make[1]: *** [Makefile:111: install] Error 1
make[1]: Leaving directory '/root/glibc-2.28'
make: *** [Makefile:12: install] Error 2

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你使用的指令是非常落后的了，建议到项目主要看最新的来运行，同时你的系统是centos7啊，这个系统也建议你换成debian或者ubuntu

**Comment by Bobbyliujhdy** [comment]
创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
现在仍然未成功吗？
