### ISSUE TITLE
[help wanted 求助]: 关于socks5代理使用IPv6的问题

### ISSUE THREAD

**Issue by toyo2333** [fscarmen/warp#416]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

前提：

双栈VPS机器，设置了代理，安装了Warp，我使用的是代理模式，然后将ChatGPT,ipw.cn等的访问用Xray路由转发到Warp sock5 代理出站

情况：

1，当我不用Warp时候，本地电脑上浏览器都是可以使用IPv6打开ChatGTP和ipw.cn的,都是优先使用IPv6。

2，开启并连接Warp之后，的ipv4和ipv6地址都成功获取了Warp的地址。但是访问ChatGTP和ipw.cn却变成了用IPv4优先了。

3，我以为是vps的问题，我在VPS直接使用warp代理访问ChatGTP或者ipw.cn的测试API，却都都能使用IPv6，

例1： curl https://chat.openai.com/cdn-cgi/trace  --proxy socks5://127.0.0.1:40000，结果显示warp=on, ip是一个Warp节点的IPV6的地址 IPv6优先访问

例2：curl test.ipw.cn --proxy socks5://127.0.0.1:40000 APi返回给我的也是IPv6的Warp地址

说明VPS上使用Warp socks5代理模式访问目标站点，IPv6优先OK的

我的问题来了：为什么在我本地电脑上就不行了呢？ 上面的123已经说明了，VPS的xray路由里把域名加进去转发到Warp sock5 Proxy之后，就显示IPv4访问了。去掉，就能IPv6，其他条件都没变。

这是什么原因呢？应该不是我的电脑或者浏览器或者VPS的问题把，是我的warp proxy哪里设置错误了么？盼望大佬来解答一下。

PS，不是说IPv4就不行，都能用，我就是想知道为啥？

### Log / 日志信息

暂时没有

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
xray分流了dns解了，就轮不到linux的4或6优先了，因为他已把域名根据xray配置文件的规则，把那两个网的域名解释为v4或v6的ip了，所以你要在xray里处理那两个网
同时我印象中client只有v4，没v6，如是wireproxy就要替换v6的ip过去

**Comment by rmdbbs** [comment]
“你要在xray里处理那两个网”---
这个能再说的细一些么？我是个小白用户。。不太理解

“同时我印象中client只有v4，没v6”---
这是不是意味着我在xray的 outboundTag里指定代理的设置为"domainStrategy": "UseIPv6"也没有用？

就是我目前这个方法只能走v4出站？

**Comment by fscarmen** [comment]
wireproxy方式，然后warp y停掉，把warp的v6地址，在/etc/wireguard/wgcf.conf 换到/etc/wireguard/proxy.conf文件处，最后warp y开启

**Comment by fscarmen** [comment]
![image](https://github.com/fscarmen/warp/assets/62703343/d930d94f-8b4b-4808-8fe0-7adcd820f3c5)

**Comment by toyo2333** [comment]
解决了，换wgcf脚本只接管v6就可以了。warp-cli的proxy模式可能本身不支持。
