### ISSUE TITLE
华普团队IP的好处？

### ISSUE THREAD

**Issue by asterriya** [fscarmen/warp#42]
WARP团队在warp plus下的好处是什么？

**Comment by fscarmen** [comment]
Use WARP Team account instead of Plus. No need to brush Plus traffic any more.      
使用脚本提供 TEAM 账户替代 Plus，免刷流量

**Comment by asterriya** [comment]
Got it. But I turned on Warp team account first and then apply warp+ script. Is it ok? Browserleaks.com shows me warp team IP as it should be. And how to use my own Cloudflare for teams account if I have it?

So warp team included warp+ benefits as fast speed and argo smart routing?

**Comment by fscarmen** [comment]
> Got it. But I turned on Warp team account first and then apply warp+ script. Is it ok?

certainly.



> And how to use my own Cloudflare for teams account if I have it

1. Follow this step to get the Team  Configuration file ：https://parkercs.tech/cloudflare-for-teams-wireguard-config/
2. Upload the file to private storage space before. For example: gist.github.com
3. ```warp v ``` to update the lastest script. Run ```warp d```, it requires you to paste the URL of Team  Configuitration file.
4. It will change the wgcf.conf with the Team Private Key. IPv4 ,IPv6 and Endpoint automationlly.


> And can I change DNS to from 8.8.8.8 to 1.1.1.1

ofcourse

**Comment by asterriya** [comment]
I didn't find that Cloudflare for teams included warp+ or using Argo smart routing.

So after I'll apply this instruction, then I can control whole traffic through my Cloudflare for teams dashboard, right?

Warp v/warp в, You mean something like that wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && bash menu.sh warp v and wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && bash menu.sh warp d?

**Comment by fscarmen** [comment]
> I didn't find that Cloudflare for teams included warp+ or using Argo smart routing.

I think this is automatic when we set the dns to 1.1.1.1 under WARP plus or Team account.

You need run the script first. And then you can run again with  ```warp [option]```

**Comment by asterriya** [comment]
Ok, I will try and then let you know about progress.

> You need run the script first.

You mean to follow guide first, right?

> I think this is automatic when we set the dns to 1.1.1.1 under WARP plus or Team account.

So it's necessary to change DNS from 8.8.8.8 to 1.1.1.1?

And what I use V2ray (vless+WS+CDN)? Do I need to change config somehow? Or better to use SS+V2ray plugin (WS+CDN)?

**Comment by fscarmen** [comment]
> You mean to follow guide first, right?

If you still haven't installed warp, run ``` wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && bash menu.sh``` 
 to install free account through script first. And then run ```warp d``` to switch to the warp+  or team account.



> So it's necessary to change DNS from 8.8.8.8 to 1.1.1.1?
And what the differences if I can apply DNS provided by Cloudflare for teams (inside dashboard) and apply this DNS inside my DNS resolv into Linux system?

I am not sure it could be better. I haven't compared the two DNS.





> And what I use V2ray (vless+WS+CDN)? Do I need to change config somehow? Or better to use SS+V2ray plugin (WS+CDN)?

If you require making  accurate diversion, you need to modify the v2ray outbound config file.

**Comment by asterriya** [comment]
Did you compare the speed differences before/after applying Cloudflare for teams?

**Comment by fscarmen** [comment]
> Did you compare the speed differences before/after applying Cloudflare for teams?

Sorry not yet so far.     
I am very happy if you tell me the difference between the two.

**Comment by asterriya** [comment]
Is it safe to use this script https://gist.githubusercontent.com/fscarmen/56aaf02d743551737c9973b8be7a3496/raw/16cf34edf5fb28be00f53bb1c510e95a35491032/com.cloudflare.onedotonedotonedotone_preferences.xml ? I mean that no one will see what site's I'm visiting, including the owner of this URL?

**Comment by fscarmen** [comment]
> Is it safe to use this script https://gist.githubusercontent.com/fscarmen/56aaf02d743551737c9973b8be7a3496/raw/16cf34edf5fb28be00f53bb1c510e95a35491032/com.cloudflare.onedotonedotonedotone_preferences.xml ? I mean that no one will see what site's I'm visiting, including the owner of this URL?

The owner is me . And i guess it 's safe cause I could find nothing about the user information in the dashboard.
Of course you'd better use the file that took by yourself.

![image](https://user-images.githubusercontent.com/62703343/146862835-1a9a7276-2645-4ade-8551-8f4234a9f405.png)
![image](https://user-images.githubusercontent.com/62703343/146862932-09db0e43-49ce-4edb-8d74-37592fd025a2.png)

**Comment by asterriya** [comment]
Asking this because I can't use this method explained in guide. Because the file is too huge, and it's blocking by my ISP provide, so I can download it at all. So I hope your URL will help to me.

**Comment by fscarmen** [comment]
> So I hope your URL will help to me.

Did it work？

**Comment by asterriya** [comment]
> > So I hope your URL will help to me.
> 
> Did it work？

It's working but I have an idea. Testing it.

**Comment by fscarmen** [comment]
> So you dont see any data even on analytics page?

There is nothing data about that user.     
I don’t even know how many people use it.

**Comment by asterriya** [comment]
And last question. Is it ok if cloudflare dns in proxied status? Or I need turned it on only dns status?

**Comment by fscarmen** [comment]
> And last question. Is it ok if cloudflare dns in proxied status? Or I need turned it on only dns status?

yes.   ```vim /etc/wireguard/wgcf.conf```
chane the dns to 1.1.1.1 .  Save and quit.
```systemctl restart wg-quick@wgcf```

**Comment by asterriya** [comment]
No I'm talking about proxied status inside cloudflare dasboard cause using shadowsocks to bypass censorship

**Comment by fscarmen** [comment]
Sorry . I don't understand what you mean. If you wanna know the information and stauts in cloudflare dashboard. I can provide you with username and password. Telegram : @fscarmen2
