### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by moelinmtf** [fscarmen/warp#422]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

荷兰服务器刷出不出ip

### Log / 日志信息

 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/419
