### ISSUE TITLE
[help wanted 求助]: 关于wgcf的key的问题-【结论： wgcf 获取的 warp 账户是通用的。不同设备之间需要处理 PostUp和 PostDown】

### ISSUE THREAD

**Issue by toyo2333** [fscarmen/warp#423]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

请问下wgcf生产的配置文件，在重装系统或者迁移系统后会失效么？

我最近把一台已经配置好v6 wgcf的系统快照，然后迁移到另外一个机房去了。重新启动起来后，这些配置私钥什么的还有效么？

其实就是想问这个当初注册生成的私钥和是否和硬件还是系统软件绑定呢？

### Log / 日志信息

null

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
<img width="839" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/7d39d3a4-9ed4-4f20-a352-4f8c0f1f1af7">

除了 PostUp =  和 PostDown =  开头的要根据使用的vps网络接口来（这个影响路由规则，弄不好会失联），其他的账户信息，privatekey ,ipv6 等可以迁移甚至共用。

**Comment by toyo2333** [comment]
> <img alt="image" width="839" src="https://user-images.githubusercontent.com/62703343/245700066-7d39d3a4-9ed4-4f20-a352-4f8c0f1f1af7.png">
> 除了 PostUp = 和 PostDown = 开头的要根据使用的vps网络接口来（这个影响路由规则，弄不好会失联），其他的账户信息，privatekey ,ipv6 等可以迁移甚至共用。

我弄好了。我是双栈机器，之前只绑定了v6.迁移过去后直接启动系统，ssh v4连过去没问题。检查了下warp状态也ok。想了想如果是双栈绑定确实有可能会有失联问题。
