### ISSUE TITLE
[help wanted 求助]: 我的 vps 上面安装 docker 外网无法访问容器-【结论：在`docker run`时，我们可以使用 `--network host` 将Docker容器的网络模式设置为主机（host）模式】

### ISSUE THREAD

**Issue by zcr268** [fscarmen/warp#424]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

warp 安装好后还能安装  docker 么？
我的 vps 上面安装 docker 外网无法访问容器

### Log / 日志信息

RT

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
在issue里搜一下所有docker的话题，有处理方案的。

**Comment by tjyuli** [comment]
搞定了，谢谢

**Comment by fscarmen2** [comment]
你是如何解决的呢？

**Comment by fscarmen** [comment]
你是如何处理的呢？

**Comment by tjyuli** [comment]
docker run -d --net host -e WEBPORT=[6688] -it badapple9/speedtest-x   去掉中括号，端口改成自己的

**Comment by fscarmen** [comment]
就是使用了host的网络模式。

**Comment by tjyuli** [comment]
是的
