### ISSUE TITLE
[help wanted 求助]: 安装了docker版的h5测速，打不开网址

### ISSUE THREAD

**Issue by tjyuli** [fscarmen/warp#425]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

warp有时开机不能获取到ip，这时候docker版的h5测速就能用，（https://hub.docker.com/r/ilemonrain/html5-speedtest/），但是一旦获取到cf的ip了就打不开h5的页面了

### Log / 日志信息

2023/06/14 12:47:37 Using config file: /etc/wireguard/account-temp.toml
2023/06/14 12:47:37 Updated license key detected, re-binding device to new account
2023/06/14 12:47:40 Setting device name
2023/06/14 12:47:41 =======================================
2023/06/14 12:47:41 Device name   : v
2023/06/14 12:47:41 Device model  : PC
2023/06/14 12:47:41 Device active : true
2023/06/14 12:47:41 Account type  : limited
2023/06/14 12:47:41 Role          : child
2023/06/14 12:47:41 Premium data  : 21.85 PiB
2023/06/14 12:47:41 Quota         : 21.85 PiB
2023/06/14 12:47:41 =======================================
2023/06/14 12:47:41 Successfully updated Cloudflare Warp account

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen2** [comment]
https://github.com/fscarmen/warp/issues/424

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/424

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/424

这个是docker使用 host 模式处理的。
