### ISSUE TITLE
[help wanted 求助]: warp-go 在使用全局双栈时，可能丢失网络

### ISSUE THREAD

**Issue by PoPTu** [fscarmen/warp#426]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

使用warp-go 全局双栈和warp_unlock (仅设置单维度网络的解锁) 时，可能会丢失双栈WARP 网络（大约半天到一天半），但是warp 并未断开，表现为主机没有网络，并且打开warp-go 非常慢，打开后可见IPv4 与IPv6 地址皆为空白。
重启warp-go 服务可以解决。
猜测：warp_unlock 更换WARP 服务后导致，但是应该只更换了一个维度网络的WARP ，实际上v4 和v6 网络都会断。

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是的，warp ipv4和 warp ipv6 都会同时断和连接上，这个改不了

**Comment by PoPTu** [comment]
好的
那如果出现双栈网络全断的情况有什么快速处理的办法吗（全断时，需要等待数分钟warp-go才能刷新出界面）？

**Comment by fscarmen** [comment]
不需要数分钟啊
`systemctl restart warp-go`

**Comment by PoPTu** [comment]
对哦 用系统重启服务就好啊！
