### ISSUE TITLE
[help wanted 求助]: Client_Debian_12.deb': No such file or directory-【结论：2023.6.18 menu.sh V2.51 Client 支持 Debian 12 (bookworm)】

### ISSUE THREAD

**Issue by bzcrl** [fscarmen/warp#427]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

dpkg: error: cannot access archive 'Client_Debian_12.deb': No such file or directory

### Log / 日志信息

dpkg: error: cannot access archive 'Client_Debian_12.deb': No such file or directory
Failed to start warp-svc.service: Unit warp-svc.service not found.
 进度 2/2: 设置 Client 模式 
menu.sh: line 1838: warp-cli: command not found

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
cf 官方还没有推出 debian12 的版本，不过推测把debian 11 的版本改名为12的可以使用的，建议你手动处理一下。

**Comment by bzcrl** [comment]
> cf 官方改了安装包的下载主页 ，再看 https://pkg.cloudflareclient.com/ 这里已经支持 Debian 12 了，我这几天花时间改一下才行。
感谢大佬 辛苦了🌹

**Comment by fscarmen** [comment]
> > cf 官方改了安装包的下载主页 ，再看 https://pkg.cloudflareclient.com/ 这里已经支持 Debian 12 了，我这几天花时间改一下才行。
> 
> 感谢大佬 辛苦了🌹

正在测试中，夜点能处理好。

**Comment by fscarmen** [comment]
2023.6.18 menu.sh V2.51 Client supports Debian 12 (bookworm); Client 支持 Debian 12 (bookworm)
