### ISSUE TITLE
hax.co.id使用脚本报错

### ISSUE THREAD

**Issue by qsgy-edge** [fscarmen/warp#43]
没有加载 TUN 模块，请在管理后台开启或联系供应商了解如何开启

**Comment by fscarmen** [comment]
先去 https://hax.co.id/vps-control 点击Enable TUN打开tun，耐心等待，待完成后点击Restart重启VPS，最后在ssh命令行输入 “cat /dev/net/tun” （不带引号），显示什么什么bad state就说明成功了

如果出现something error，不用理，群主面板的bug，照样重启，不行重复步骤开tun

**Comment by visense** [comment]
> 先去 [https://hax.co.id/vps-control ](https://hax.co.id/vps-control%C2%A0) 点击Enable TUN打开tun，耐心等待，待完成后点击Restart重启VPS，最后在ssh命令行输入 “cat /dev/net/tun” （不带引号），显示什么什么bad state就说明成功了
> 
> 如果出现something error，不用理，群主面板的bug，照样重启，不行重复步骤开tun

good👍

**Comment by huankong233** [comment]
> 先去[https://hax.co.id/vps-control ](https://hax.co.id/vps-control%C2%A0)点击Enable TUN打开tun，等待等待，待完成后点击重启VPS，最后在ssh命令行输入“cat /dev/net/tun”（不带引号），显示什么不好的状态就说明成功了
> 
> 如果出现错误，不用理，群主面板的bug，照样重启，不可重复步骤开tun

安装时无法获取WARP IP 中,最大尝5次……

**Comment by fscarmen** [comment]
请问是什么机器，如果是 lxc 的 Debian 11, Ubuntu 20.04 或者 CentOS 8
用方式处理 [# 44] (https://github.com/fscarmen/warp/issues/44)

```until curl -s4m8 ip.gs; do bash warp n; done```

**Comment by huankong233** [comment]
> 请问是什么机器，如果是 lxc 的 Debian 11, Ubuntu 20.04 或者 CentOS 8 用方式处理 #44
> 
> `until curl -s4m8 ip.gs; do bash warp n; done`

找到问题了，我使用的是centos7，换debian就好了

**Comment by fscarmen** [comment]
> centos7

C7 是系统的原因，处理不了

**Comment by fscarmen** [comment]
> centos7

C7 是系统的原因，处理不了

**Comment by huankong233** [comment]
> > centos7
> 
> C7 是系统的原因，处理不了

嗯
