### ISSUE TITLE
[Bug]: 执行bash warp-go.sh后，脚本输出"下载 warp-go 压缩文件不成功，脚本退出"

### ISSUE THREAD

**Issue by gaboolic** [fscarmen/warp#431]
### Expectation / 预期情况

执行bash warp-go.sh成功

### Actual Situation / 实际情况

执行bash warp-go.sh后，脚本输出"下载 warp-go 压缩文件不成功，脚本退出"

### Reproduction Method / 复现方法

我也遇到了这个"下载 warp-go 压缩文件不成功，脚本退出"错误。/tmp路径存在
然后我看了下脚本，脚本里面获取ARCHITECTURE调用了check_arch() { # 判断处理器架构 case $(uname -m)
我手动执行了一下uname -m，输出是aarch64，是不是这个原因？没有能符合的文件名……
我的设备是随身wifi刷的debian……

### More information / 额外信息

可能存在的问题：
手动执行了一下uname -m，输出是aarch64

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
<img width="705" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/c4cfb92c-c968-4b8c-9e89-42dc588fafea">

有这项的哦，你试试手动运行以下的看看
```
wget -O /tmp/warp-go.tar.gz https://raw.githubusercontent.com/fscarmen/warp/main/warp-go/warp-go_1.0.8_linux_arm64.tar.gz

tar xzf /tmp/warp-go.tar.gz -C /tmp/ warp-go

chmod +x /tmp/warp-go

/tmp/warp-go -h
```

**Comment by gaboolic** [comment]
> <img alt="image" width="705" src="https://user-images.githubusercontent.com/62703343/247841293-c4cfb92c-c968-4b8c-9e89-42dc588fafea.png">
> 有这项的哦，你试试手动运行以下的看看
> 
> ```
> wget -O /tmp/warp-go.tar.gz https://raw.githubusercontent.com/fscarmen/warp/main/warp-go/warp-go_1.0.8_linux_arm64.tar.gz
> 
> tar xzf /tmp/warp-go.tar.gz -C /tmp/ warp-go
> 
> chmod +x /tmp/warp-go
> 
> /tmp/warp-go -h
> ```

输出 -config string
    	WARP Config (default "warp.conf")
  -device-name string
    	WARP Device Name
  -export-singbox string
    	Export SingBox config (SOCKS Mode)
  -export-wireguard string
    	Export WireGuard config (like wgcf)
  -h	Show help
  -license string
    	WARP+ License
  -register
    	Register device to WARP
  -remove
    	Remove WARP Device
  -reset-key
    	Reset wireguard private key
  -team-config string
    	WARP Team Config
  -update
    	Update WARP Info
  -v	Show version and warp-go info

**Comment by gaboolic** [comment]
感觉还是网络问题。给github加了个反代，又卡在后面了。我准备手动试试
后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by gaboolic** [comment]
> 

是的 之前"下载 warp-go 压缩文件不成功，脚本退出"应该是连github连不上
github地址改成反代后的地址之后，是执行到后台获取 WARP IP 中失败了……
准备手动配置那堆东东了

**Comment by gaboolic** [comment]
话说可能真的是我这网络不稳定，我现在又执行 总算成功了
请选择: 4
后台获取 WARP IP 中, 最大尝试5次……
第1次尝试
第2次尝试
已成功获取 WARP plus 网络
运行在 全局 模式

**Comment by fscarmen** [comment]
OK
