### ISSUE TITLE
[help wanted 求助]: e 安装 iptables + dnsmasq + ipset 分流流媒体方案后，设备重启后无法上网

### ISSUE THREAD

**Issue by gaboolic** [fscarmen/warp#433]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

设备重启之后无法上网，排查发现/etc/resolv.conf 为127.0.0.1，然后排查到是dnsmasq的启动脚本修改的此文件。

我是使用bash menu.sh e 安装 iptables + dnsmasq + ipset 分流流媒体方案，dnsmasq开机启动脚本修改了/etc/resolv.conf 为127.0.0.1
是哪里没操作对吗？

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是这样的哦，不能上网暂时没有什么头绪了，这里上面的图是原生的 ns，8.8.8.8，安装 iptables + dnsmasq 之后，被设置的域名就用了 warp 出口了

<img width="654" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/c7cdde01-bd7c-40fc-9635-447b55550960">

**Comment by gaboolic** [comment]
> 

当时是能上网的，重启之后上不了。谷歌一番 有可能是debian+ dnsmasq的bug，说是再重启一下dnsmasq就好了
我放弃了，卸载dnsmasq了
