### ISSUE TITLE
[Feature request]: 建议Socks5模式可设置绑定网卡，以便docker镜像代理访问

### ISSUE THREAD

**Issue by default102** [fscarmen/warp#434]
### Related Problem / 相关问题

Socks5模式默认绑定127.0.0.1，导致k3s、docker等镜像无法直接访问

### Describe the solution you want / 描述你希望的解决方案

希望可以像端口一样自定义绑定网卡或IP

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
>建议Socks5模式可设置绑定网卡

这个我倒不会哦，有没有相关的教程？

同时，如果是安装client 的话，你试试用 warp 模式，菜单14选项，如果你用proxy模式，建docker 的时候，创建容器的时候设置为host模式也行
具体参考
https://github.com/fscarmen/warp/issues/115

**Comment by yy4382** [comment]
> > 建议Socks5模式可设置绑定网卡
> 如果你用proxy模式，建docker 的时候，创建容器的时候设置为host模式也行 具体参考 #115

如果使用 docker-compose，有多个service的时候使用host网络会很麻烦，如果有redis还可能会有安全问题，所以还是建议搞一个如楼主所说的绑定网卡功能吧
