### ISSUE TITLE
[help wanted 求助]: 无法上网了

### ISSUE THREAD

**Issue by lck1115** [fscarmen/warp#435]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

warp自动掉了，获取也一直获取不到，所以卸载了，想重新安装一下。
结果就连不上网了，ssh可以连上。。
ping google.com也不通

### Log / 日志信息

root@FR:~# wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh d
--2023-06-25 10:34:22--  https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘raw.githubusercontent.com’

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
试试，这样卸载
```
wg-quick down wgcf
bash menu.sh u
```

**Comment by lck1115** [comment]
> 试试，这样卸载
> 
> ```
> wg-quick down wgcf
> bash menu.sh u
> ```

-bash: /usr/bin/wg-quick: No such file or directory
应该是已经卸载完了，但是上不了网了。。

**Comment by fscarmen** [comment]
systemctl restart systemd-resolved
再看看 `cat /etc/resolv.conf` 看看ns

**Comment by lck1115** [comment]
# Generated by resolvconf
nameserver 10.194.3.12
nameserver 10.194.3.3

原来如此，
不知道为啥ns被改成了内外地址，关键我这还是ipv6 only的机器。。

**Comment by fscarmen** [comment]
如果是 ipv6的，把 ns 改一下看看
echo -e "nameserver 2a00:1098:2b::1\nnameserver 2a01:4f9:c010:3f02::1\nnameserver 2a01:4f8:c2c:123f::1\nnameserver 2a00:1098:2c::1" > /etc/resolv.conf

**Comment by lck1115** [comment]
我把dns改成了Google dns的ipv4和ipv6，可以上网了，但是docker还是不能上网，端口不通，docker是host模式，之前都没问题的。。

**Comment by fscarmen** [comment]
docker restart 一下看看，端口有没有被占用。

**Comment by lck1115** [comment]
> docker restart 一下看看，端口有没有被占用。

restart了，也rm重建了，还是上不了网，端口没被占用。。

**Comment by fscarmen** [comment]
宿主机能上网，docker不能连网是吗？

**Comment by lck1115** [comment]
是的啊。。

**Comment by fscarmen** [comment]
把 warp 断开了就能连上了？

**Comment by univerioiln233** [comment]
> # Generated by resolvconf
> nameserver 10.194.3.12 nameserver 10.194.3.3
> 
> 原来如此， 不知道为啥ns被改成了内外地址，关键我这还是ipv6 only的机器。。

wgcf.conf内的dns设置会自动写入resolv

**Comment by fscarmen** [comment]
处理一下 /etc/resolv.conf ，看看是否恢复正常
