### ISSUE TITLE
[help wanted 求助]: WARP+ 突然不能用了

### ISSUE THREAD

**Issue by PoPTu** [fscarmen/warp#436]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

![image](https://github.com/fscarmen/warp/assets/134193326/c757245d-ff3e-4642-adae-8dcefb128a0e)
可能是WARP 接口问题？在使用WARP+账号时提示upgrade failed.  标准账号正常

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
检查你的 license 绑定的设备是不是超过5台了

**Comment by PoPTu** [comment]
我在多个服务器上尝试了不同Key和但都出现了这个问题，不过之前登录过的Key未受到影响

**Comment by PoPTu** [comment]
![image](https://github.com/fscarmen/warp/assets/134193326/ac7b192e-998c-45bd-ad3c-2824ff80ffbc)
warp.sh 正常

**Comment by PoPTu** [comment]
应该是接口问题

**Comment by teralomaniac** [comment]
我也是今天刚遇到这个问题，前两天还好好的。

**Comment by PoPTu** [comment]
> 

换warp client吧，也几乎全局

**Comment by fscarmen** [comment]
<img width="619" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/a61f0e47-f0b0-4a69-b170-784200e1bb67">

我这里可以啊

**Comment by PoPTu** [comment]
> 

又测试了一下menu.sh，直接添加WARP时可以使用WARP+账号，但是使用warp l设置为CloudFlare Client时会出现错误提示超过五个设备——实际上仅有一个设备使用的账号也会如此

**Comment by fscarmen** [comment]
我这里不会哦，你检测一下，再重新试试看

**Comment by LINRONGG** [comment]
我也是！WARP Linux Client，开启 WARP 模式时，开启WARP+的时候也提示超过5台设备（实际上没超）。而且我是正价付费的WARP+无限流量的。（会不会是因为无限流量识别错误？）

**Comment by PoPTu** [comment]
> 我也是！WARP Linux Client，开启 WARP 模式时，开启WARP+的时候也提示超过5台设备（实际上没超）。而且我是正价付费的WARP+无限流量的。（会不会是因为无限流量识别错误？）

两种账号我都试了，都一样的，等等吧 或者用默认方式

**Comment by fscarmen** [comment]
暂时先用默认账户先啦，一样速度的，我正在忙重构脚本

**Comment by fscarmen** [comment]
现在可以了？

**Comment by LINRONGG** [comment]
> 现在可以了？

还是失败，还是提示超过5台设备。但是用WGCF就正常。

**Comment by fscarmen** [comment]
> > 现在可以了？
> 
> 还是失败，还是提示超过5台设备。但是用WGCF就正常。

我自己的 license 试不出来呢，不过 warp+ 速度并没有提高的，用普通免费的可以了。
