### ISSUE TITLE
[help wanted 求助]: shadowsocks代理如何配置路由策略？

### ISSUE THREAD

**Issue by Akrusher** [fscarmen/warp#437]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

在vultr的vps配置的ssr，使用的shadowsocks客户端，安装warp之后显示能获取新的IP，在本地访问chatgpt的时候还是被blocked，显示的还是原来vps的ip，想问一下需要在vps上更改ssr的配置文件吗，shadowsocks客户端需要更改吗

### Log / 日志信息

部署warp成功，没有看到报错信息

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by Akrusher** [comment]
<img width="822" alt="截屏2023-06-26 下午11 46 47" src="https://github.com/fscarmen/warp/assets/18118614/769da9c0-c751-4575-99f9-fb751a3162cb">
我看是拿到warp提供的新的ip地址了，
脚本版本:2.52
 功能新增:1. Client Proxy 模式支持 warp 双栈; 2. Client warp 模式支持 warp 双栈; 3. 加快脚本启动速度; 感谢网友 ⑥哥, WordsWorthLess, us254 and chika0801 关于 xray 模板的指导
 系统信息:
	 当前操作系统:CentOS Linux 7 (Core)
	 内核:4.11.8-1.el7.elrepo.x86_64
	 处理器架构:amd64
	 虚拟化:microsoft
	 IPv4: 104.28.243.190 法国  Cloudflare, Inc.
	 IPv6: 2001:19f0:6801:441:5400:4ff:fe7b:cce9 法国  Choopa, LLC
	 WARP 网络接口已开启
	 Client 未安装
	 WireProxy 未安装
但是访问chatgpt的时候还是vps的地址，看xray配置文件更改了，配置文件的 outbound 和 routing，使用ssr的话不需要更改vps配置吗

**Comment by Akrusher** [comment]
<img width="279" alt="截屏2023-06-26 下午11 52 15" src="https://github.com/fscarmen/warp/assets/18118614/c8f6ee64-13db-4f15-a74b-954232eb01c3">
在vps上curl ip.gs的时候也是显示的warp获取的新的ip，但是本地通过shadowsocks客户端连接的机器，访问ip.gs时显示的是vps的ip地址，需要怎么配置一下啊，本地开的是全局模式

**Comment by socosfly** [comment]
https://github.com/mack-a/v2ray-agent
建议直接上傻瓜式脚本解决

**Comment by fscarmen** [comment]
> 显示的还是原来vps的ip

显示vps原生的 IPv6 : 2001:xxx:cce9 的IP吗？shadowsocks 协议的分流我也不会。
