### ISSUE TITLE
[Bug]: 没有找到适合的方案用于修改 wgcf 配置文件 wgcf.conf，脚本中止

### ISSUE THREAD

**Issue by GreatMichaelLee** [fscarmen/warp#438]
### Expectation / 预期情况

正常安装

### Actual Situation / 实际情况

 Language:
 1. English (default)
 2. 简体中文

 Choose: 2

 所有依赖已存在，不需要额外安装

 检查环境中……
 没有找到适合的方案用于修改 wgcf 配置文件 wgcf.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp/issues]

### Reproduction Method / 复现方法

初次安装，一头雾水，什么意思啊？缺什么？

### Log / 日志信息

None

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
看一下有没有ping命令，没有的话，先安装
```
apt-get update
apt-get install -y iputils-ping
```

**Comment by GreatMichaelLee** [comment]
root@local:~# apt-get update
Hit:1 http://deb.xanmod.org releases InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [723 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [932 kB]
Fetched 1992 kB in 4s (503 kB/s)
Reading package lists... Done
root@local:~# apt-get install -y iputils-ping
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
iputils-ping is already the newest version (3:20211215-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by fscarmen** [comment]
那么你运行 `bash -x menu.sh` 看看，把日志发一下

**Comment by GreatMichaelLee** [comment]
[log.txt](https://github.com/fscarmen/warp/files/11884064/log.txt)
麻烦你看看，谢谢

**Comment by fscarmen** [comment]
可能第一次安装失败导致，你先试试 `bash menu.sh u` 来卸载，再重新安装看看

**Comment by GreatMichaelLee** [comment]
> 可能第一次安装失败导致，你先试试 `bash menu.sh u` 来卸载，再重新安装看看

一样.....not working

**Comment by GreatMichaelLee** [comment]
在线等啊，大佬，装不上很着急....

**Comment by GreatMichaelLee** [comment]
> 我也是一样的问题，系统Ubuntu，之前一样的系统装都没问题，今天第一次遇到。

我也是ubuntu

**Comment by fscarmen2** [comment]
> 我也是一样的问题，系统Ubuntu，之前一样的系统装都没问题，今天第一次遇到。

是不是warp-go？我刚更新了，修bug了。

**Comment by fscarmen** [comment]
已处理，重新下载并安装，今天升级有处遗留了

**Comment by fscarmen** [comment]
两位现在安装正常了吗？

**Comment by GreatMichaelLee** [comment]
我改用go正常了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 上午10:31
收件人: ***@***.***&gt;;
抄送: "michael ***@***.******@***.***&gt;;
主题: Re: [fscarmen/warp] [Bug]: 没有找到适合的方案用于修改 wgcf 配置文件 wgcf.conf，脚本中止 (Issue #438)




 
两位现在安装正常了吗？

**Comment by fscarmen** [comment]
应该用 wgcf 也是可以的，下次试试，没有问题我先 close 了
