### ISSUE TITLE
没有找到适合的方案用于修改 wgcf 配置文件 wgcf.conf，脚本中止。Bug]: 

### ISSUE THREAD

**Issue by mekkhalawang** [fscarmen/warp#439]
### Expectation / 预期情况

正常安装后的第一二选项应该是转为ipv4或者6

### Actual Situation / 实际情况

实际情况就是1和2选项只显示：“转为”两个字。然后输入1回车后就提示上面的话。

### Reproduction Method / 复现方法

使用脚本wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh [option] [lisence]

### More information / 额外信息

 123

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by startui** [comment]
我也遇到了同样的问题
![Screenshot_2023-06-28-00-21-38-581_com server auditor ssh client](https://github.com/fscarmen/warp/assets/136451363/ce47e348-a7a6-45e4-b3fb-44b456f5f804)

**Comment by fscarmen** [comment]
已处理，重新下载并安装，今天升级有处遗留了

**Comment by startui** [comment]
> 已处理，重新下载并安装，今天升级有处遗留了

好的，现在正常了

**Comment by fscarmen** [comment]
已处理。
