### ISSUE TITLE
Hax.co.id 印尼区无法获取warp ip-【Conclusion: There is a bug and have fixed already.】

### ISSUE THREAD

**Issue by misakano7545** [fscarmen/warp#44]
<img src="https://user-images.githubusercontent.com/96560028/147248876-6d91c0b9-9535-4588-91dd-7a24699159f6.png" width="60%" />

如图

**Comment by fscarmen** [comment]
Debian 11 和 CentOS 8 已经处理了，如图
![image](https://user-images.githubusercontent.com/62703343/147266533-727f945f-5d03-428d-b179-d20beec93706.png)
![image](https://user-images.githubusercontent.com/62703343/147266637-094a91ff-ec65-4ee8-9c89-6b72a6bae63f.png)
![image](https://user-images.githubusercontent.com/62703343/147267031-7acee805-09fa-40f9-a1a8-fb1e96fddcd8.png)

**Comment by fscarmen** [comment]
lxc 机器母鸡资源不够，warp 需要不停的刷才能获取到
```until curl -s4m5 ip.gs; do bash -x warp n; done```

**Comment by malikshi** [comment]
i had same issues with biznetgio
```sh
 Create shortcut [warp] successfully
 Running WARP
 Maximum 5 attempts to get WARP IP...
 Try 1
 Try 2
 Try 3
 Try 4
 Try 5
 There have been more than 5 failures. The script is aborted. Feedback: [https://github.com/fscarmen/warp/issues]
```
somehow restarted the services wgcf make it works

**Comment by fscarmen** [comment]
There is a bug 

> i had same issues with biznetgio
> 
> ```shell
>  Create shortcut [warp] successfully
>  Running WARP
>  Maximum 5 attempts to get WARP IP...
>  Try 1
>  Try 2
>  Try 3
>  Try 4
>  Try 5
>  There have been more than 5 failures. The script is aborted. Feedback: [https://github.com/fscarmen/warp/issues]
> ```
> 
> somehow restarted the services wgcf make it works

There is a bug in the latest verion. I have fixed it. But cdn is still not updated. U run the script again
```
wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && bash menu.sh
```
