### ISSUE TITLE
失败已超过5次，脚本中止，问题反馈

### ISSUE THREAD

**Issue by zxfhit** [fscarmen/warp#440]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### Log / 日志信息

wu

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
我在一台 ubuntu 20.04 的 ipv6 only 机器上试是可以的。
<img width="720" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/3845a31c-a893-4d3f-9554-fb0515437e33">

<img width="771" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/6d7545f3-cbb3-440c-adb1-e038688168b2">

**Comment by zxfhit** [comment]
> 我在一台 ubuntu 20.04 的 ipv6 only 机器上试是可以的。 <img alt="image" width="720" src="https://user-images.githubusercontent.com/62703343/249444177-3845a31c-a893-4d3f-9554-fb0515437e33.png">
> 
> <img alt="image" width="771" src="https://user-images.githubusercontent.com/62703343/249444108-6d7545f3-cbb3-440c-adb1-e038688168b2.png">

你好，问题 排除了，ip获取需要很长的时间，我第一次没有耐心，第二次花费了700多秒获得到warp网络。我还有一个问题，如果的服务器重新启动，我还需要进行操作吗？是否会自动执行warp?

**Comment by fscarmen** [comment]
700多秒不正常，不过不影响使用。

重启不要操作，有进程守护
