### ISSUE TITLE
[help wanted 求助]: 安装了warp-go出现谷歌验证码了

### ISSUE THREAD

**Issue by KENAN1412** [fscarmen/warp#441]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

安装了warp-go出现谷歌验证码了

### Log / 日志信息

![图片](https://github.com/fscarmen/warp/assets/77651819/b222ddbb-8278-4da2-a932-3b53304d5de9)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
在 google 搜索 what is my ip address ，看看是不是 warp 的 IP，如果是说明通过warp访问了，有验证可能该 IP 同一时间用的人多，有点黑。

**Comment by KENAN1412** [comment]
换team会不会更换ip

**Comment by fscarmen** [comment]
账户是 teams ，更换 ip 的话会提示换不了。
