### ISSUE TITLE
[help wanted 求助]: 关于private_key和reserved值

### ISSUE THREAD

**Issue by sjkhsl** [fscarmen/warp#442]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

访问chatgpt的模板中private_key和reserved值在哪里获取？

### Log / 日志信息

没有日志

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
如果你安装了最新脚本，可以在 /etc/wireguard/warp-account.conf 查看，如果没有安装，想弄个新的，可以在https://fscarmen.cloudflare.now.cc/  ，右上角有个generate的按键，能生成一个新账户，有你要的

**Comment by sjkhsl** [comment]
> 如果你安装了最新脚本，可以在 /etc/wireguard/warp-account.conf 查看，如果没有安装，想弄个新的，可以在https://fscarmen.cloudflare.now.cc/ ，右上角有个generate的按键，能生成一个新账户，有你要的

感谢！

**Comment by fscarmen** [comment]
找到了吗？

**Comment by sjkhsl** [comment]
> 找到了吗？

找到了

**Comment by jnxyatmjx** [comment]
reserved值跟什么有关系？我看我更换了公钥私钥 都不影响reserved的使用。reserved可以取任意值吗？

**Comment by fscarmen** [comment]
> reserved值跟什么有关系？我看我更换了公钥私钥 都不影响reserved的使用。reserved可以取任意值吗？

当然不是啦，账户-私钥-device_id-access_token必须一一对应的，只是很多地方（香港,LA除外）不需要验证reserved而已

**Comment by jnxyatmjx** [comment]
> > > reserved值跟什么有关系？我看我更换了公钥私钥 都不影响reserved的使用。reserved可以取任意值吗？
> > 
> > 
> > 当然不是啦，账户-私钥-device_id-access_token必须一一对应的，只是很多地方（香港,LA除外）不需要验证reserved而已
> 
> 如果team用户，有什么办法能生成reserved呢？你说的device_id是不是reserved？

确认下来是 team账户  无reserved值。

**Comment by fscarmen** [comment]
什么账户都有该值的

**Comment by jnxyatmjx** [comment]
> 什么账户都有该值的

好的吧。我用api.sh脚本结合自己team的token ，使用api.sh -i 发现接口跟没没有返回reserved

**Comment by fscarmen** [comment]
> 好的吧。我用api.sh脚本结合自己team的token ，使用api.sh -i 发现接口跟没没有返回reserved

要用 -f <账户信息文件的路径> -i

**Comment by jnxyatmjx** [comment]
> 要用 -f


> > 好的吧。我用api.sh脚本结合自己team的token ，使用api.sh -i 发现接口跟没没有返回reserved
> 
> 要用 -f <账户信息文件的路径> -i

嗷嗷。我赶快试下。先行谢过了。

**Comment by jnxyatmjx** [comment]
> > 好的吧。我用api.sh脚本结合自己team的token ，使用api.sh -i 发现接口跟没没有返回reserved
> 
> 要用 -f <账户信息文件的路径> -i
你这命令 如有神助！！reserved立马显现。

**Comment by jnxyatmjx** [comment]
不过最后还是想确认下， team账号相关信息配置到 xray里。能在LA或者香港正常使用吗？

**Comment by fscarmen** [comment]
> 能在LA或者香港正常使用吗？

可以的，按 xray 的要求填全即可。

**Comment by jnxyatmjx** [comment]
> > 能在LA或者香港正常使用吗？
> 
> 可以的，按 xray 的要求填全即可。

确实如你所说，LA服务器，通过api.sh+team token可以正常使用的。

**Comment by Morris-Lucifer** [comment]
我也没找到reserved值，参照[这个issue](https://github.com/fscarmen/warp/issues/120#issuecomment-1086817819) 配置的xray也能用，就是不知道为什么显示为ipv4的warp地址，而直接用命令 curl https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000 测试依旧是ipv6的warp地址

**Comment by fscarmen** [comment]
> /etc/wireguard和/root/wireguard的配置文件都看了，我也没找到reserved值
用本项目的 api 指定 wgcf-account.toml 或者 warp-account.conf 文件即可找到 reserved 值

> (https://github.com/fscarmen/warp/issues/120#issuecomment-1086817819) 配置的xray也能用，就是不知道为什么： 笔记本浏览器直接访问 https://chat.openai.com/cdn-cgi/trace 显示为ipv4的warp地址， 而vps直接用命令 `curl https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000` 测试依旧是ipv6的warp地址

因为 xray 里指定了访问 chatGPT 用 warp IPv4，你在vps里指定 `curl -4m5 https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000`

**Comment by Morris-Lucifer** [comment]
> > /etc/wireguard和/root/wireguard的配置文件都看了，我也没找到reserved值
> 
> 用本项目的 api 指定 wgcf-account.toml 或者 warp-account.conf 文件即可找到 reserved 值
> 
> > ([#120 (comment)](https://github.com/fscarmen/warp/issues/120#issuecomment-1086817819)) 配置的xray也能用，就是不知道为什么： 笔记本浏览器直接访问 https://chat.openai.com/cdn-cgi/trace 显示为ipv4的warp地址， 而vps直接用命令 `curl https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000` 测试依旧是ipv6的warp地址
> 
> 因为 xray 里指定了访问 chatGPT 用 warp IPv4，你在vps里指定 `curl -4m5 https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000`

原来是这样，谢谢大佬

**Comment by Morris-Lucifer** [comment]
> > /etc/wireguard和/root/wireguard的配置文件都看了，我也没找到reserved值
> 
> 用本项目的 api 指定 wgcf-account.toml 或者 warp-account.conf 文件即可找到 reserved 值
> 
> > ([#120 (comment)](https://github.com/fscarmen/warp/issues/120#issuecomment-1086817819)) 配置的xray也能用，就是不知道为什么： 笔记本浏览器直接访问 https://chat.openai.com/cdn-cgi/trace 显示为ipv4的warp地址， 而vps直接用命令 `curl https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000` 测试依旧是ipv6的warp地址
> 
> 因为 xray 里指定了访问 chatGPT 用 warp IPv4，你在vps里指定 `curl -4m5 https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000`

又发现了新的问题，为什么用相同的配置（直接笔记本分享给手机），手机chrome访问 https://chat.openai.com/cdn-cgi/trace 显示的是vps原来的ipv4地址啊
