### ISSUE TITLE
[help wanted 求助]: 一直在重复尝试获取

### ISSUE THREAD

**Issue by smalllam** [fscarmen/warp#444]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

一直在重复尝试获取，昨天是这样，今天还是这样
使用命令：wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh [option] [lisence]

### Log / 日志信息

======================================================================================================================

 1.  WARP IPv6 转为 WARP IPv4 (warp 4) 
 2.  WARP IPv6 转为 WARP 双栈 (warp d) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 2
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xe" for details.
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp]
 脚本特点:
         • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
         • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
         • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
         • 支持硬件结构类型: AMD、 ARM 和 s390x
         • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
         • 支持 WARP Linux Socks5 Client
         • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
 
======================================================================================================================

 脚本版本:3.00 beta
 功能新增:重要更新: 1. 全面用 Cloudflare 官方 warp api 替代 wgcf; 2. 使用 wireguard-go with reserved 替代内核。使香港，洛杉矶等受限地区使用 warp; 以上均是热心网友的作品，我谨代表本脚本的所有用户感谢这位网友和 warp-go 作者 coia 的贡献; 3.由于改动太大，请用户重新安装，如有问题请反馈，我将会尽快处理
 系统信息:
         当前操作系统:Debian GNU/Linux 11 (bullseye)
         内核:5.15.108-1-pve
         处理器架构:amd64
         虚拟化:lxc 
         IPv4:     
         IPv6: 2406:cb42:0:1010::a14 United States  Shock Hosting LLC 
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  WARP 双栈 转为 WARP IPv4 (warp 4) 
 2.  WARP 双栈 转为 WARP IPv6 (warp 6) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 2
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xe" for details.
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
systemd运行报错，看看报错信息 `systemctl status wg-quick@warp`，同时是不是在切换 IPv4 / IPv6 的时候出现的呢？如果是，今天有个更新，`warp v`一下，同时让 `/etc/wireguard/warp.conf` 文件里的 Reserved 前面要有 # 号，如
```
#Reserved = [113, 234, 182]
```

**Comment by zhaozongwen** [comment]
错误信息查看是未开启tun，Failed to create TUN device: CreateTUN("warp") 
联系服务器厂商开启就可解决此问题

**Comment by fscarmen** [comment]
```
systemctl disable --now wg-quick@wgcf
systemctl disable --now wg-quick@warp
wg-quick down wgcf
wg-quick down warp
warp u
rm -rf /etc/wireguard
```
彻底卸载后再重新安装看看
