### ISSUE TITLE
[help wanted 求助]: Alpine 系统提示没有安装 WireGuard tools 或者找不到配置文件 warp.conf-【结论：已处理适配性的问题】

### ISSUE THREAD

**Issue by xiaopan369** [fscarmen/warp#446]
### Script / 脚本

menu.sh

### OS / 操作系统

Alpine - Linux

### Actual Situation / 实际情况

显示没有安装 WireGuard tools 或者找不到配置文件 warp.conf，请重新安装。 

### Log / 日志信息

======================================================================================================================

 脚本版本:3.00 beta
 功能新增:重要更新: 1. 全面用 Cloudflare 官方 warp api 替代 wgcf; 2. 使用 wireguard-go with reserved 替代内核。使香港，洛杉矶等受限地区使用 warp; 以上均是热心网友的作品，我谨代表本脚本的所有用户感谢这位网友和 warp-go 作者 coia 的贡献; 3.由于改动太大，请用户重新安装，如有问题请反馈，我将会尽快处理
 系统信息:
         当前操作系统:Alpine Linux v3.17
         内核:5.15.107-2-pve
         处理器架构:amd64
         虚拟化: 
         IPv4:     
         IPv6: 
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  为 NAT IPv4 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
 2.  为 NAT IPv4 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
 3.  为 NAT IPv4 添加 WARP 双栈网络接口 (bash menu.sh d) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 3

 如有 WARP+ 或 Teams 账户请选择
 1. 使用免费账户 (默认)
 2. WARP+
 3. Teams 

 请选择: 

 请选择优先级别:
 1. IPv4
 2. IPv6
 3. 使用 VPS 初始设置 (默认) 

 请选择: 

 进度 1/3: 安装系统依赖…… 

OK: 28 MiB in 72 packages
OK: 28 MiB in 72 packages
--2023-07-03 20:20:30--  https://raw.githubusercontent.com/fscarmen/warp/main/wireguard-go/wireguard-go-linux-amd64-20230223
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2691072 (2.6M) [application/octet-stream]
Saving to: '/usr/bin/wireguard-go'

/usr/bin/wireguard-go                100%[====================================================================>]   2.57M  11.8MB/s    in 0.2s    

2023-07-03 20:20:31 (11.8 MB/s) - '/usr/bin/wireguard-go' saved [2691072/2691072]

sed: /etc/wireguard/warp.conf: No such file or directory
menu.sh: line 2005: systemctl: command not found
 创建快捷 warp 指令成功 
 运行 WARP 
 没有安装 WireGuard tools 或者找不到配置文件 warp.conf，请重新安装。 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
> sed: /etc/wireguard/warp.conf: No such file or directory
这个报错没有关系，上面获取不了原生的 IP问题比较大，你试试
```
ping6 -c2 -w10 2606:4700:d0::a29f:c001
ping -6 -c2 -w10 2606:4700:d0::a29f:c001
curl -ks6m5 -A Mozilla https://api.ip.sb/geoip
```

**Comment by xiaopan369** [comment]
> > sed: /etc/wireguard/warp.conf: 没有这样的文件或目录
> > 这个报错没有关系，上面获取不了无法解决的IP问题比较大，你试试
> 
> ```
> ping6 -c2 -w10 2606:4700:d0::a29f:c001
> ping -6 -c2 -w10 2606:4700:d0::a29f:c001
> curl -ks6m5 -A Mozilla https://api.ip.sb/geoip
> ```

CT210:~# ping6 -c2 -w10 2606:4700:d0::a29f:c001
PING 2606:4700:d0::a29f:c001 (2606:4700:d0::a29f:c001): 56 data bytes
64 bytes from 2606:4700:d0::a29f:c001: seq=0 ttl=59 time=1.192 ms
64 bytes from 2606:4700:d0::a29f:c001: seq=1 ttl=59 time=1.200 ms

--- 2606:4700:d0::a29f:c001 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 1.192/1.196/1.200 ms
CT210:~# ping -6 -c2 -w10 2606:4700:d0::a29f:c001
PING 2606:4700:d0::a29f:c001 (2606:4700:d0::a29f:c001): 56 data bytes
64 bytes from 2606:4700:d0::a29f:c001: seq=0 ttl=59 time=1.143 ms
64 bytes from 2606:4700:d0::a29f:c001: seq=1 ttl=59 time=1.302 ms

--- 2606:4700:d0::a29f:c001 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 1.143/1.222/1.302 ms
CT210:~# curl -ks6m5 -A Mozilla https://api.ip.sb/geoip
{"organization":"Nextarray-asn-01","longitude":-79.3716,"timezone":"America\/Toronto","isp":"Nextarray-asn-01","offset":-18000,"asn":33696,"asn_organization":"NEXTARRAY-ASN-01","country":"Canada","ip":"2602:fed2:7307:1028::b33","latitude":43.6319,"continent_code":"NA","country_code":"CA"}

**Comment by fscarmen** [comment]
这样应该没有问题啊，不太清楚为什么菜单里显示不出来原生的 IP。方便的话，你把 ssh 发到我的邮箱 fscarmen@gmail.com ，我进去排查一下，不过也要今晚夜点了

**Comment by fscarmen** [comment]
已处理了，并更新了脚本，主要是有个python3依赖和data指定有不同，都已适配了。

<img width="709" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/c4202323-23b1-4d4e-a4a0-d1ed2ab12ebc">

**Comment by xiaopan369** [comment]
好的已解决
