### ISSUE TITLE
[help wanted 求助]: 腾讯云（海外）无法正常使用

### ISSUE THREAD

**Issue by 404area** [fscarmen/warp#448]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

腾讯轻量云新加坡地区安装warp后 xray 无法正常使用。具体表现为：使用warp双栈模式正常获取ip后，在云主机上curl cip.cc 发现能够正常获取到warp的ip，但是本地主机通过挂xray访问google.com等域名，无法正常访问，但是本机访问ip111.cn发现网页反馈是使用warp获取的ip进行访问google.com等域名，通过warp o 命令暂停后，随即可以正常访问google等域名。

备注：相同配置一摸一样的安装操作，aws的轻量云一点儿问题没有，但是腾讯云就会出现上述问题！

### Log / 日志信息

<img width="636" alt="image" src="https://github.com/fscarmen/warp/assets/50036307/e8b5d156-a516-4f9f-b114-268067d35597">
<img width="504" alt="image" src="https://github.com/fscarmen/warp/assets/50036307/7c901b8b-cd5e-4ef8-9e0c-1b86535b7555">
<img width="475" alt="image" src="https://github.com/fscarmen/warp/assets/50036307/8ea94f71-3f93-494a-a01f-b0d3ab9e3d81">

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by 404area** [comment]
怀疑是某种转发出现了问题，或者腾讯云的某种限制，由于个人linux操作，网络路由这块儿水平不高，自己不知道如何排查

**Comment by fscarmen** [comment]
> ### Script / 脚本
> menu.sh
> 
> ### OS / 操作系统
> CentOS - Linux
> 
> ### Actual Situation / 实际情况
> 腾讯轻量云新加坡地区安装warp后 xray 无法正常使用。具体表现为：使用warp双栈模式正常获取ip后，在云主机上curl cip.cc 发现能够正常获取到warp的ip，但是本地主机通过挂xray访问google.com等域名，无法正常访问，但是本机访问ip111.cn发现网页反馈是使用warp获取的ip进行访问google.com等域名，通过warp o 命令暂停后，随即可以正常访问google等域名。
> 
> 备注：相同配置一摸一样的安装操作，aws的轻量云一点儿问题没有，但是腾讯云就会出现上述问题！
> 
> ### Log / 日志信息
> <img alt="image" width="636" src="https://user-images.githubusercontent.com/50036307/251364215-e8b5d156-a516-4f9f-b114-268067d35597.png"> <img alt="image" width="504" src="https://user-images.githubusercontent.com/50036307/251364281-7c901b8b-cd5e-4ef8-9e0c-1b86535b7555.png"> <img alt="image" width="475" src="https://user-images.githubusercontent.com/50036307/251364315-8ea94f71-3f93-494a-a01f-b0d3ab9e3d81.png">
> ### I confirm that I have updated to the latest version / 我确认已更新至最新版本
> * [x]  Yes / 是
> 
> ### I confirm that I have checked the history issues / 我确认已查询历史 issues
> * [x]  Yes / 是

你的vps能用warp访问外网，应该不存在问题啊，想不出排查方向了。
