### ISSUE TITLE
[help wanted 求助]: 不支持 ARM6

### ISSUE THREAD

**Issue by ddase1** [fscarmen/warp#449]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

不支持 ARM6

### Log / 日志信息

请选择: 5
 Client 不支持 ARM64，问题反馈:[https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
没有环境测，所以没有支持了。arm6是不是太旧了。
