### ISSUE TITLE
每次执行命令都要选择语言，建议优化一下操作 -【结论：已支持，旧版本升级，中文 echo 'C' >/etc/wireguard/language; warp v   英文 echo 'E' >/etc/wireguard/language; warp v】

### ISSUE THREAD

**Issue by at2008** [fscarmen/warp#45]
比如，默认语言按上次选择的语言选项；
在设置选项增加一项设置默认语言选项；

**Comment by fscarmen** [comment]
上几天升级的版本已经可以了，你可以这样升级
中文 ```echo 'C' >/etc/wireguard/languagen; warp v```

英文 ```echo 'E' >/etc/wireguard/languagen; warp v```

**Comment by at2008** [comment]
这几天每个版本都升级过， warp v 升级的，每次执行warp 还是要选择语言；
刚才执行 echo 'C' >/etc/wireguard/languagen; warp v ，然后执行warp，还是要选择语言；
奇怪了。。。

**Comment by fscarmen** [comment]
我是SB，我是SB，我是SB

**Comment by at2008** [comment]
NB NB NB 👍😂
