### ISSUE TITLE
[help wanted 求助]: high traffic and many connections

### ISSUE THREAD

**Issue by ssmetall** [fscarmen/warp#451]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

Hello, I have a xray core server with high traffic ( 1gb) and many connections(20k ) , I set the dual stack method, but apparently +warp cannot handle it and the connections are disconnected, I also tested the socks method and the situation got worse, please help me, what can I do?

### Log / 日志信息

ubuntu 22 , 16 core cpu  32 gb ram

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
Presumably the high traffic of multiple connections leads to limitations by WARP, and there's not much that can be done about that.
