### ISSUE TITLE
[help wanted 求助]:为什么teams账户不支持更换IP了？

### ISSUE THREAD

**Issue by lihuaiyu0131** [fscarmen/warp#452]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

为什么teams账户不支持更换IP了？

### Log / 日志信息

为什么teams账户不支持更换IP了？

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是的，tean token和reserved的原因

**Comment by lihuaiyu0131** [comment]
> 是的，tean token和reserved的原因

以后都不行了吗？

**Comment by fscarmen** [comment]
是的，不要执着于team，没有任何数据显示 team 和 plus 比 free 快。

**Comment by Benjamin1919** [comment]
> 是的，不要执着于team，没有任何数据显示 team 和 plus 比 free 快。

我记得free是有流量限制的，最多用1G还是5G来着……而Teams是无限流量的

**Comment by fscarmen** [comment]
没有这样的事，你放心使用 free 就行了。
