### ISSUE TITLE
[help wanted 求助]: 系统提示没有安装 WireGuard tools 或者找不到配置文件 warp.conf

### ISSUE THREAD

**Issue by morbid542** [fscarmen/warp#453]
### Script / 脚本

menu.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

我在运行脚本删除时其他文件也选择删除了该如何进行恢复

### Log / 日志信息

该如何进行恢复

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen2** [comment]
可以了？

**Comment by fscarmen** [comment]
处理了？

**Comment by morbid542** [comment]
是的

**Comment by fscarmen** [comment]
什么问题导致的呢？
