### ISSUE TITLE
[help wanted 求助]: 双栈只使用IPV6 → warp 双栈

### ISSUE THREAD

**Issue by lloyd18** [fscarmen/warp#454]
正常使用是V4 → warp 4 或 warp 双栈，或V6到 → warp 双栈
但是我有这边点非主流，由于本机V4太垃圾了，全球丢包，但是V6是正常的，想要关闭本机V4而使用 V6 到 warp 双栈要怎么做呢
谢谢

**Comment by fscarmen** [comment]
可是可以，不过这样做，只能通过 IPv6 ssh 了，暂时未有更好办法，如果需求，先用 IPv6 ssh，按下面操作
```
warp o  # 停止warp
sed -i "/ip -4/s/.*/#&/g; s/Endpoint.*/Endpoint = [2606:4700:d1::a29f:c101]:2408/g" /etc/wireguard/warp.conf  # 修改配置文件，不走原生v4，更换 Endpoint 为 v6 IP
warp o # 重新开启
```

**Comment by lloyd18** [comment]
> 不过可以，不过这样做，就只能通过 IPv6 ssh 了，暂时没有更好的办法，如果有需求，先用 IPv6 ssh，按下面操作
> 
> ```
> warp o  # 停止warp
> sed -i "/ip -4/s/.*/#&/g; s/Endpoint.*/Endpoint = [2606:4700:d1::a29f:c101]:2408/g" /etc/wireguard/warp.conf  # 修改配置文件，不走原生v4，更换 Endpoint 为 v6 IP
> warp o # 重新开启
> ```

谢谢，给商家工单后维护结束V4恢复正常，问题得到解决。
