### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by mobagheri** [fscarmen/warp#455]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

Hello. I wish to forward the squid proxy traffic under the WARP. Would it be possible for you to help me edit the config file for the squid proxy so that it tunnels to 127.0.0.1:40000? Thanks a lot.

### Log / 日志信息

No Error

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
Sorry, I have never contacted "squid proxy". If you want to know how to config the file, I recommand you visit http://www.squid-cache.org and ask for help there.

**Comment by mobagheri** [comment]
> Sorry, I have never contacted "squid proxy". If you want to know how to config the file, I recommand you visit http://www.squid-cache.org and ask for help there.

Thanks for your kind reply. considering that I do not want to modify the squid proxy's configuration, If I want to forward al output traffic of the server to the 127.0.0.1:40000 socks proxy, what command do you recommend?

**Comment by fscarmen** [comment]
[xray](https://github.com/XTLS/Xray-core)

**Comment by fscarmen** [comment]
Sorry, I'm not familiar with iptables, you can try it.
