### ISSUE TITLE
[help wanted 求助]重装，就出现了没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止: 

### ISSUE THREAD

**Issue by founderqiang** [fscarmen/warp#457]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

warp 在升级到新版本之后 要求卸载重装，用warp u 卸载之后，用这条命令 
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh d

重装，就出现了没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp/issues] 
哪位大神清楚这是什么问题啊

### Log / 日志信息

没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
```
systemctl disable --now wg-quick@wgcf
bash menu.sh u
rm -rf /etc/wireguard
bash menu.sh
```

**Comment by founderqiang** [comment]
> ```
> systemctl disable --now wg-quick@wgcf
> bash menu.sh u
> rm -rf /etc/wireguard
> bash menu.sh
> ```
还是出现同样的问题

**Comment by fscarmen** [comment]
能正常访问网络吗？ curl -m8 ip.gs 看看

**Comment by founderqiang** [comment]
root@vultr:~# curl -m8 ip.gs
2a09:bac5:a2fd:1973::289:84

**Comment by fscarmen** [comment]
你是安装了warp-go脚本吗？他与 menu.sh 不一样的
你试试这样完成卸载
```
systemctl disable --now warp-go
warp-go u
rm -rf /opt/warp-go
```

**Comment by founderqiang** [comment]
当前操作系统:Debian GNU/Linux 10 (buster)
         内核:4.19.0-23-amd64
         处理器架构:amd64
         虚拟化:microsoft 
         IPv4: 104.28.247.137 美国  Cloudflare, Inc. 
         IPv6: 2a09:bac5:a2fd:1973::289:84 美国  Cloudflare 
         WARP 网络接口已开启 
         Client 已安装， 断开状态 
         WireProxy 未安装 

======================================================================================================================

 1.  连接 Client (warp r) 
 2.  连接 Wireproxy (warp y) 
 3.  更改 Client 或 WireProxy 端口 
 4.  打开 WARP (warp o) 
 5.  (!!! 已安装，请勿选择)安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. (!!! 已安装，请勿选择)安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 



> 能正常访问网络吗？ curl -m8 ip.gs 看看

应该能行了，请问仅仅安装warp 的话应该选哪个

**Comment by fscarmen** [comment]
你不是已经是warp的ip了吗？还装什么？

**Comment by founderqiang** [comment]
没有，选择4时，显示warp未安装，现在又出现我刚才的问题了

**Comment by fscarmen** [comment]
方便你把ssh发给处理吧，fscarmen@gmail.com

**Comment by founderqiang** [comment]
vps系统重启了一下，好了，非常感谢您的帮助

**Comment by doge2mars** [comment]
> ```
> systemctl disable --now wg-quick@wgcf
> bash menu.sh u
> rm -rf /etc/wireguard
> bash menu.sh
> ```

这个方法管用，谢了
