### ISSUE TITLE
[help wanted 求助]: 咨询各模式之间的性能比较

### ISSUE THREAD

**Issue by shandongtlb** [fscarmen/warp#458]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

因为要进行分流，当前warp脚本中的warp模式（第1个）、WARP Client Proxy socks模式、WireProxy模式、WARP Client Proxy网卡模式以及warp-go脚本中的非全局模式中，哪一个性能比较好呢？

系统 ubuntu22
内核5.15
洛杉矶dmit机房

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
请自行安装对比，比较好的做法是vps里用 speedtest-cli 来试，对比一下网速和系统资源的占用情况。

**Comment by shandongtlb** [comment]
好的好的

**Comment by fscarmen** [comment]
> 好的好的

回头你有测试的话，可以分享一下数据，谢谢！
