### ISSUE TITLE
[Feature request]: 请求支持 Fedora 系统-【2023.7.21 menu.sh 一键脚本 V3.00 beta2  支持 Fedora 系统】

### ISSUE THREAD

**Issue by aozaki-kuro** [fscarmen/warp#459]
### Related Problem / 相关问题

使用本脚本的时候弹出消息 `本脚本只支持 Debian、Ubuntu、CentOS、Arch 或 Alpine 系统` 但我目前服务器上使用的是 Fedora 系统。

### Describe the solution you want / 描述你希望的解决方案

希望可以支持 Fedora。查看脚本后发现已经支持红帽系其他版本，Fedora 使用的包管理器是 `dnf` 但大部分操作应该是和 `yum` 类似的。希望可以加入支持，谢谢！

### Describe the alternatives you are considering / 描述你所考虑的替代方案

我将系统判别条件修改为 `REGEX=("debian" "ubuntu" "centos|red hat|kernel|oracle linux|alma|rocky|fedora" "amazon linux" "alpine" "arch linux")` 并将所有 `yum` 直接替换为 `dnf`，运行后没有出现任何问题，成功安装 warp 客户端。希望可以添加至新版本中。

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
好的，抽空处理下。

**Comment by fscarmen** [comment]
你运行个 cat /etc/os-release 和 hostnamectl 看有什么粘贴一下

**Comment by aozaki-kuro** [comment]
`cat /etc/os-release` 的结果如下：

```
NAME="Fedora Linux"
VERSION="38 (Thirty Eight)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Thirty Eight)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
```

`hostnamectl` 的结果如下：

```
     Static hostname: hetzner-de-arm
           Icon name: computer-vm
             Chassis: vm 🖴
          Machine ID: [已隐去]
             Boot ID: [已隐去]
      Virtualization: kvm
    Operating System: Fedora Linux 38 (Thirty Eight)
         CPE OS Name: cpe:/o:fedoraproject:fedora:38
      OS Support End: Tue 2024-05-14
OS Support Remaining: 9month 4w
              Kernel: Linux 6.3.12-200.fc38.aarch64
        Architecture: arm64
     Hardware Vendor: Hetzner
      Hardware Model: vServer
    Firmware Version: 20171111
       Firmware Date: Sat 2017-11-11
```

另：我在自己本地安装的虚拟机里，`hostnamectl` 显示 `Operating System: Fedora Linux 38 (Cloud Edition)`

**Comment by fscarmen** [comment]
好的，应个38的版本好像是新的，知道什么版本以上能安装wireguard-tools吗？

**Comment by aozaki-kuro** [comment]
目前可以查到的最早就是到 Fedora 32
https://bodhi.fedoraproject.org/updates/?packages=wireguard-tools

但官方的 packages 页面已经只有 37 / 38 了（还有 RHEL 7 / 8 ）。由于手里没有那么旧的版本，无法验证是否能在 Fedora 32 上运行。
https://packages.fedoraproject.org/pkgs/wireguard-tools/wireguard-tools/

Fedora 大概每 6 个月发布一个大版本，每个版本维护周期 13 个月左右，所以版本变化挺快的。

**Comment by fscarmen** [comment]
哭死，在GCP上开了一个 Fedora Cloud Base 34 v34.20210423.0，ssh登陆不了。之后就开了一个 Debian 11 的去 dd ，https://www.nazo.run/archives/171.html，也是不成功，系统失联。

**Comment by aozaki-kuro** [comment]
试试用这个项目呢
https://github.com/leitbogioro/Tools

这个可以装 37、38 的，也就是现在还在生命周期里的版本。
34 我记得上周折腾的时候就遇到过很多签名和源失效，升级出错的问题，所以建议是别试了😂

**Comment by aozaki-kuro** [comment]
<img width="1220" alt="image" src="https://github.com/fscarmen/warp/assets/28428951/a1ddd7ff-554f-48dd-bc29-586e23aae0a8">

OK 我在家里的 NAS 上开了一台 Fedora 34 测试了一下，能够装 `wireguard-tools`

<img width="431" alt="image" src="https://github.com/fscarmen/warp/assets/28428951/a2ea68a3-b3a1-4b44-89f8-2b342a4cf422">

随后用我自己瞎改的脚本倒也能跑通，成功给 IPv4 only 环境添加了 IPv6 / 双栈 😂

**Comment by fscarmen** [comment]
老哥早说啊，害我弄了半天。用 dnf 的好了，正想给你试，如果yum不用改，我就不加dnf了

**Comment by aozaki-kuro** [comment]
😂 我的锅我的锅，我是今年才开始用的红帽系，有些文档还没还仔细看过，非常抱歉

**Comment by fscarmen** [comment]
> 😂 我的锅我的锅，我是今年才开始用的红帽系，有些文档还没还仔细看过，非常抱歉


不过想想我还有一个最低版本要求的，每个系统如果低于某个版本，不让安装的，如debian 不能低于9 , Ubuntu 不能低于 16.04，而 Fedora 不能低于 34。我先发个改好的脚本在这里，我在GCP上的37、38测过的。麻烦你试试，你把 `.zip` 去掉，因为附件后缀有要求。

[menu.sh.zip](https://github.com/fscarmen/warp/files/12066935/menu.sh.zip)

**Comment by aozaki-kuro** [comment]
测试好了

- Fedora 34, amd64
- Fedora 38, arm64

都可以运行，并且正常获取双栈 IP。
`wireguard-tools` 最低支持的版本 Fedora 32 因为实在太老了就没有安装。

**Comment by fscarmen** [comment]
> 测试好了
> 
> * Fedora 34, amd64
> * Fedora 38, arm64
> 
> 都可以运行，并且正常获取双栈 IP。 `wireguard-tools` 最低支持的版本 Fedora 32 因为实在太老了就没有安装。

好的，感谢你的测试，晚点我看看还有些什么一并重新上去，最近重构了，还需要多点时间来观察。
