### ISSUE TITLE
[help wanted 求助]: C7系统不能正常使用-【结论：3.0需要彻底卸载后重装，恢复正常】

### ISSUE THREAD

**Issue by amggmm** [fscarmen/warp#460]
### Script / 脚本

warp-go.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

 脚本版本:3.00 beta
 功能新增:重要更新: 1. 全面用 Cloudflare 官方 warp api 替代 wgcf; 2. 使用 wireguard-go with reserved 替代内核。使香港，洛杉矶等受限地区使用 warp; 以上均是热心网友的作品，我谨代表本脚本的所有用户感谢这位网友和 warp-go 作者 coia 的贡献; 3.由于改动太大，请用户重新安装，如有问题请反馈，我将会尽快处理
 系统信息:
         当前操作系统:CentOS Linux 7 (Core)
         内核:6.4.3-bbrplus.el7.x86_64
         处理器架构:amd64
         虚拟化:kvm 
         IPv4:     
         IPv6:     
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

### Log / 日志信息

<img width="673" alt="屏幕截图 2023-07-17 095154" src="https://github.com/fscarmen/warp/assets/88455444/50a7923d-9b35-4834-9a38-664d964ea941">

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
```
cat /etc/wireguard/warp.conf
wg-quick up warp
```

看看如何显示，从你的日志来看，查不到 IPv4 和 v6 的 IP 吗？这样有问题的。

**Comment by amggmm** [comment]
> ```
> cat /etc/wireguard/warp.conf
> wg-quick up warp
> ```
> 
> 看看如何显示，从你的日志来看，查不到 IPv4 和 v6 的 IP 吗？有这些问题的。

我服务器是有IP4的，开了warp第三个，但是获取不到warp的ip，然后重新进去获取错误信息，然后就看见没有IP了，如果删了就可以重新看见IP了

**Comment by fscarmen** [comment]
> cat /etc/wireguard/warp.conf
> wg-quick up warp

你运行这两个指令，看回显什么，发一下

**Comment by amggmm** [comment]
> > cat /etc/wireguard/warp.conf 
> > wg-快速扭曲
> 
> 你运行这两个指令，看回显什么，发一下

删了warp是不是获取不了，如果是可能要等一会，我重新安装一下

**Comment by amggmm** [comment]
> > cat /etc/wireguard/warp.conf 
> > wg-快速扭曲
> 
> 你运行这两个指令，看回显什么，发一下

<img width="594" alt="image" src="https://github.com/fscarmen/warp/assets/88455444/5080f751-b33a-431e-b367-9076753a8cb5">

**Comment by fscarmen** [comment]
Reserverd 那里没有数值的呢？

**Comment by amggmm** [comment]
> Reserverd那里没有数值呢？

这里需要什么数值呀，不清楚

**Comment by fscarmen** [comment]
建议你重装了，运行下面的，有可能会报错，也不要紧的
```
systemctl disable --now wg-quick@wgcf
systemctl disable --now wg-quick@warp
wg-quick down wgcf
wg-quick down warp
bash menu.sh u
rm -rf /etc/wireguard
```
之后再重装脚本看看

**Comment by amggmm** [comment]
> 建议你重装了，运行下面的，有可能会报错，也不要紧的
> 
> ```
> systemctl disable --now wg-quick@wgcf
> systemctl disable --now wg-quick@warp
> wg-quick down wgcf
> wg-quick down warp
> warp u
> rm -rf /etc/wireguard
> ```
> 
> 之后重装脚本看看
弄好了

**Comment by fscarmen** [comment]
重新安装了吗？正常吧

**Comment by amggmm** [comment]
> 重新安装了吗？正常吧
正常了
