### ISSUE TITLE
[help wanted 求助]: 怎么每10分钟更换一次warp的ip

### ISSUE THREAD

**Issue by TWStz233** [fscarmen/warp#463]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

怎么每10分钟更换一次warp的ip

### Log / 日志信息

no logs

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
脚本没有现成这样的功能，大体思路，做个 sh 脚本，完成以下操作。
1. 停了 warp
2. 通过api.sh脚本注销现在的账户
3. 通过api.sh脚本注册一个新的warp账户
4. 把账户信息更换至现在配置文件处 `/etc/wireguard/warp`
5. 重新账户 warp
6. 以上5天做个while true循环，每次 sleep 10m

**Comment by TWStz233** [comment]
> 脚本没有现成这样的功能，大体思路，做个 sh 脚本，完成以下操作。
> 
> 1. 停了 warp
> 2. 通过api.sh脚本注销现在的账户
> 3. 通过api.sh脚本注册一个新的warp账户
> 4. 把账户信息更换至现在配置文件处 `/etc/wireguard/warp`
> 5. 重新账户 warp
> 6. 以上5天做个while true循环，每次 sleep 10m

ok
谢谢
