### ISSUE TITLE
[help wanted 求助]: 获取不到IP-【结论：2023.7.21 menu.sh 一键脚本 V3.00 beta2  修复 client 2023.7.40-1 版本导致的开关错误】

### ISSUE THREAD

**Issue by dfldylan** [fscarmen/warp#464]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

我是socks端口模式，
当首次运行时，可以显示出ip地址
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh c
```
<img width="560" alt="image" src="https://github.com/fscarmen/warp/assets/28103567/e00d1643-9a17-400f-a9f2-f45991edbfee">

但是接着输入warp就会发现还是vps的真实ip
![image](https://github.com/fscarmen/warp/assets/28103567/2447165d-4002-45a7-8482-7486bf462c39)
获取ip就一直卡住在这里
<img width="643" alt="image" src="https://github.com/fscarmen/warp/assets/28103567/c067f51e-5b20-470b-8af1-3eeae0015d63">

### Log / 日志信息

 本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp]
 脚本特点:
         • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
         • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
         • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
         • 支持硬件结构类型: AMD、 ARM 和 s390x
         • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
         • 支持 WARP Linux Socks5 Client
         • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
 
======================================================================================================================

 脚本版本:3.00 beta
 功能新增:重要更新: 1. 全面用 Cloudflare 官方 warp api 替代 wgcf; 2. 使用 wireguard-go with reserved 替代内核。使香港，洛杉矶等受限地区使用 warp; 以上均是热心网友的作品，我谨代表本脚本的所有用户感谢这位网友和 warp-go 作者 coia 的贡献; 3.由于改动太大，请用户重新安装，如有问题请反馈，我将会尽快处理
 系统信息:
         当前操作系统:Debian GNU/Linux 11 (bullseye)
         内核:5.10.0-8-amd64
         处理器架构:amd64
         虚拟化:kvm 
         IPv4: 172.x.x.x 美国  IT7 Networks Inc 
         IPv6:     
         WARP 网络接口未开启 
         Client 已安装， 断开状态 
         WireProxy 未安装 

======================================================================================================================

 1.  连接 Client (warp r) 
 2.  连接 Wireproxy (warp y) 
 3.  更改 Client 或 WireProxy 端口 
 4.  打开 WARP (warp o) 
 5.  (!!! 已安装，请勿选择)安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. (!!! 已安装，请勿选择)安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 6

 1. 刷 WARP IPv4 (默认)
 2. 刷 WARP IPv6 

 请选择: 1
 当前 Netflix 地区是:US，需要解锁当前地区请按 [y], 如需其他地址请输入两位地区简写 (如 hk ,sg，默认:US): y

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by dfldylan** [comment]
好像问题就是上面第二个图Client无法打开，netstat -tunlp可以看到有127.0.0.1:40000的监听
输入warp r就提示断开了，连40000的监听都没有了

总之就是Client 无法打开

**Comment by fscarmen** [comment]
你试下多次输入`warp r`看看有没获取到 IP

**Comment by dfldylan** [comment]
不太行

<img width="452" alt="image" src="https://github.com/fscarmen/warp/assets/28103567/c209fd3a-f37e-41dc-956d-aade7a9eb64d">

**Comment by dfldylan** [comment]
我退回2.5.0版本，可以了

<img width="452" alt="截屏2023-07-21 23 00 50" src="https://github.com/fscarmen/warp/assets/28103567/9ef935f2-154a-43f0-936d-09359c7ea9c2">

**Comment by fscarmen** [comment]
查到了，是 client 升级了，显示的信息有变化，今天会处理好

**Comment by fscarmen** [comment]
2023.7.21 menu.sh V3.00 beta2

1. If the system supports wireguard kernel and wireguard-go-reserved, it can be switched use [warp k], which requires a script reinstallation;
2. Support Fedora system;
3. Fix switch error caused by client version 2023.7.40-1

1. 如果系统支持 wireguard kernel 和 wireguard-go-reserved，可以通过 [warp k] 切换，需要重装脚本;
2. 支持 Fedora 系统;
3. 修复 client 2023.7.40-1 版本导致的开关错误

**Comment by dfldylan** [comment]
solve it, thanks!
