### ISSUE TITLE
[Bug]: 只能使用 wireguard kernel 运行

### ISSUE THREAD

**Issue by OuOumm** [fscarmen/warp#465]
### Expectation / 预期情况

安装成功

### Actual Situation / 实际情况

没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp/issues]

### Reproduction Method / 复现方法

直接使用 wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh d 安装，之前使用了warp u卸载了一次。

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/460#issuecomment-1637315343

卸载一次再重装看看，有的vps只能用内核，有的只能用wireguard-go，有的两者都可以，这样才让选择的。

![image](https://github.com/fscarmen/warp/assets/62703343/d903adde-1bc2-4bf5-86e7-23283ca517f9)

**Comment by OuOumm** [comment]
> [#460 (comment)](https://github.com/fscarmen/warp/issues/460#issuecomment-1637315343)
> 
> 卸载一次再重装看看，有的vps只能用内核，有的只能用wireguard-go，有的两者都可以，这样才让选择的。
> 
> ![image](https://user-images.githubusercontent.com/62703343/255324551-d903adde-1bc2-4bf5-86e7-23283ca517f9.png)

但是目前我的vps好像直接没有网了？卡在这里不动了。
![image](https://github.com/fscarmen/warp/assets/43441064/d397833d-864e-4cc3-941f-7be1653ed076)

**Comment by OuOumm** [comment]
> [#460 (comment)](https://github.com/fscarmen/warp/issues/460#issuecomment-1637315343)
> 
> 卸载一次再重装看看，有的vps只能用内核，有的只能用wireguard-go，有的两者都可以，这样才让选择的。
> 
> ![image](https://user-images.githubusercontent.com/62703343/255324551-d903adde-1bc2-4bf5-86e7-23283ca517f9.png)

--2023-07-22 18:29:45--  https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'raw.githubusercontent.com'

**Comment by OuOumm** [comment]
我在写在之前，他的ipv4跟ipv6都为空，并且1，2选项都是   转换但是后面全是空白。

**Comment by fscarmen** [comment]
应该是有问题了，卸载了再说

**Comment by OuOumm** [comment]
Before I wrote, his ipv4 and ipv6 are empty, and the 1,2 options are both converted

> 应该是有问题了，卸载了再说

已经执行卸载命令了。运行安装命令还是卡在

--2023-07-22 18:37:30--  https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 

然后就没响应了。

**Comment by OuOumm** [comment]
> 应该是有问题了，卸载了再说

![image](https://github.com/fscarmen/warp/assets/43441064/8a37ab98-091e-4c29-983b-8fe3ebfde6a5)
ping 8.8.8.8都有问题了捏。。

**Comment by OuOumm** [comment]
> > 应该是有问题了，卸载了再说
> 
> ![image](https://user-images.githubusercontent.com/43441064/255325770-8a37ab98-091e-4c29-983b-8fe3ebfde6a5.png) ping 8.8.8.8都有问题了捏。。
