### ISSUE TITLE
[Bug]: 3.00 beta2 刷奈飞ip报错-【结论：warp i 如要做成 systemd 服务的话，请参照 https://github.com/fscarmen/warp/issues/467#issuecomment-1646837693 】

### ISSUE THREAD

**Issue by GreatMichaelLee** [fscarmen/warp#467]
### Expectation / 预期情况

成功刷新ip/脚本返回

### Actual Situation / 实际情况

刷新ip,但脚本报错，提示
`sed: -e expression #1, char 136: unterminated `s' command`
且刷新后一直开在那里不返回退出，脚本没法结束释放。
![image](https://github.com/fscarmen/warp/assets/20067401/66c12dcd-dc82-4b67-94f5-77f7f1caab92)

### Reproduction Method / 复现方法

直接操作即可。

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
我用了两台机器都复现不了，你试试卸载再重新安装，再不行运行 `bash -x warp i hk` ，把日志发来看看。

<img width="1126" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/6e141caf-cd82-4030-9500-062e93f35c18">

<img width="1072" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/d51d6ae3-cb39-4867-abc2-ec64eb02aedc">

**Comment by GreatMichaelLee** [comment]
> 我用了两台机器都复现不了，你试试卸载再重新安装，再不行运行 `bash -x warp i hk` ，把日志发来看看。
> 
> <img alt="image" width="1126" src="https://user-images.githubusercontent.com/62703343/255374627-6e141caf-cd82-4030-9500-062e93f35c18.png"> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/62703343/255374637-d51d6ae3-cb39-4867-abc2-ec64eb02aedc.png">

不是你这个流程，我是进入菜单后选择6刷的

**Comment by fscarmen** [comment]
一样的，菜单选6和 `warp i`一样的

**Comment by GreatMichaelLee** [comment]
![image](https://github.com/fscarmen/warp/assets/20067401/6c493832-5226-4dbb-88a0-7eeb7b384758)
到这儿就卡住了，一看 sleep 1h啊 -_-! 那脚本肯定卡1个小时不退出了。

**Comment by fscarmen** [comment]
流程是这样无错，解锁了就休息1小时再试，如果不解锁，就30秒左右更换账户再试。

**Comment by fscarmen** [comment]
但你上图还有个报错， 你重装后还有报错的话，你可以试试把地区设置为日本，强制他换IP，用 `bash -x warp i jp` 看看

**Comment by GreatMichaelLee** [comment]
> 流程是这样无错，解锁了就休息1小时再试，如果不解锁，就30秒左右更换账户再试。

那我不是手工刷ip,这个窗口shell 不是一直都不能退出啊？这个不是应该fork一个在后台刷吗？为啥在前台sleep啊？

**Comment by GreatMichaelLee** [comment]
> 但你上图还有个报错， 你重装后还有报错的话，你可以试试把地区设置为日本，强制他换IP，用 `bash -x warp i jp` 看看

```
 2023-07-23 14:27:27 尝试第9次，解锁失败，IPv6: 2a09:bac5:3982:e6::**** 香港 Cloudflare，10秒后重新测试，刷 IP 运行时长: 0 天 0 时 2 分 39 秒
+ wg-quick down warp
+ '[' -s /etc/wireguard/info.log ']'
+ grep -q 'Device name' /etc/wireguard/info.log
++ cat /etc/wireguard/license
+ local LICENSE=**********
++ awk '{print $NF}' /etc/wireguard/info.log
+ local 'NAME=***
limited'
+ bash /dev/fd/63 --cancle --file /etc/wireguard/warp-account.conf
++ curl -m5 -sSL https://raw.githubusercontent.com/fscarmen/warp/main/api.sh
+ bash /dev/fd/63 --registe --file /etc/wireguard/warp-account.conf
++ curl -m5 -sSL https://raw.githubusercontent.com/fscarmen/warp/main/api.sh
++ sed 's#cat $registe_path; ##'
+ [[ -n ********** ]]
+ [[ -n ***
limited ]]
+ '[' -n ********** ']'
+ bash /dev/fd/63 --file /etc/wireguard/warp-account.conf --license **********
++ curl -m5 -sSL https://raw.githubusercontent.com/fscarmen/warp/main/api.sh
+ '[' -n '***
limited' ']'
+ bash /dev/fd/63 --file /etc/wireguard/warp-account.conf --name *** limited
++ curl -m5 -sSL https://raw.githubusercontent.com/fscarmen/warp/main/api.sh
++ grep private_key /etc/wireguard/warp-account.conf
++ cut '-d"' -f4
+ local PRIVATEKEY=**********
++ grep '"v6.*"$' /etc/wireguard/warp-account.conf
++ cut '-d"' -f4
+ local ADDRESS6=2606:4700:110:8f64:4374:3393:****:****
++ reserved_and_clientid /etc/wireguard/warp-account.conf file
++ '[' file = reserved ']'
++ '[' file = file ']'
++ local FILE_PATH=/etc/wireguard/warp-account.conf
++ grep client_id /etc/wireguard/warp-account.conf
++ cut '-d"' -f4
++ xxd -p
++ base64 -d
++ fold -w2
++ read HEX
++ awk '{print "["$1", "$2", "$3"]"}'
++ printf '%d ' 0xb5
++ read HEX
++ printf '%d ' 0xe7
++ read HEX
++ printf '%d ' 0xb3
++ read HEX
+ local 'RESERVED=[181, 231, 179]'
+ '[' -s /etc/wireguard/warp.conf ']'
+ sed -i 's#\(PrivateKey[ ]\+=[ ]\+\).*#\1kNqhNs3S5IL7VoK0uCainVPjrZLsUt4rw8WQOiXTR0o=#g; s#\(Address[ ]\+=[ ]\+\).*\(/128\)#\12606:4700:110:8f64:4374:3393:****:****\2#g; s#\(.*Reserved[ ]\+=[ ]\+\).*#\1[181, 231, 179]#g' /etc/wireguard/warp.conf
+ sed -i 's#\([ ]\+"license": "\).*#\1**********"#g; s#"account_type".*#"account_type": "limited",#g; s#\([ ]\+"name": "\).*#\1***
limited"#g' /etc/wireguard/warp-account.conf
sed: -e expression #1, char 136: unterminated `s' command
+ ss -nltp
+ grep dnsmasq
+ wg-quick up warp
+ sleep 10
```

**Comment by fscarmen** [comment]
`sed: -e expression #1, char 136: unterminated `s' command`
是不是你起的设备名包含了特殊字符导致的呢？你的设备名起什么呢？我的设备名是: tesst，没有遇到上面的报错

<img width="1164" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/a5e3c481-f64e-45ef-9f00-b4e86fc7b4d4">

**Comment by GreatMichaelLee** [comment]
> `sed: -e expression #1, char 136: unterminated `s' command` 是不是你起的设备名包含了特殊字符导致的呢？你的设备名起什么呢？我的设备名是: tesst，没有遇到上面的报错
> 
> <img alt="image" width="1164" src="https://user-images.githubusercontent.com/62703343/255380700-a5e3c481-f64e-45ef-9f00-b4e86fc7b4d4.png">

设备名三个字母，没有任何特殊符号和空格

**Comment by fscarmen** [comment]
`cat /etc/wireguard/info.log` 看看是不是这样
```
root:~# cat /etc/wireguard/info.log
Device name   : tesst
```

如果有两行，就运行以下这个后，确保只有一行，再用 `warp i hk` 换 IP
```
head -n 1 /etc/wireguard/info.log > /etc/wireguard/info.log
```

**Comment by GreatMichaelLee** [comment]
![image](https://github.com/fscarmen/warp/assets/20067401/00fbdc77-7009-4d6e-838d-c92941f5af5a)
不知道为何我的account type是limited.....

**Comment by fscarmen** [comment]
> ![image](https://user-images.githubusercontent.com/20067401/255381995-00fbdc77-7009-4d6e-838d-c92941f5af5a.png) 不知道为何我的account type是limited.....

我记下来了，是以前的版本才有这个的，看日志才发现，现在已经不需要了，删了这行。

**Comment by GreatMichaelLee** [comment]
> > ![image](https://user-images.githubusercontent.com/20067401/255381995-00fbdc77-7009-4d6e-838d-c92941f5af5a.png) 不知道为何我的account type是limited.....
> 
> 我记起来了，是以前的版本才有这个的，看日志才发现，现在已经不需要了，删了这行。

删哪里？info.log....?

**Comment by fscarmen** [comment]
head -n 1 /etc/wireguard/info.log > /etc/wireguard/info.log

**Comment by GreatMichaelLee** [comment]
> head -n 1 /etc/wireguard/info.log > /etc/wireguard/info.log

运行完后info.log里空了，正常吗

**Comment by fscarmen** [comment]
你手动输一下，Device name : xxx

**Comment by GreatMichaelLee** [comment]
> 你手动输一下，Device name : xxx

还是专注搞下这个刷到ip不退出的问题吧，貌似刷到后，sleep一小时，这个时候如果我ctrl +c 强制推掉， warp接口会掉，而且我重新warp -o后之前刷到的ip也没有了。

**Comment by fscarmen** [comment]
那个不是问题，是这样设计的，因为即使刷到可用的话，也有可能过一段时间失效不能用，所以又要重新测试，所以是不停的刷的，没有退出的，你放screen刷

**Comment by fscarmen** [comment]
强行退出的话，不能联网用warp n

**Comment by GreatMichaelLee** [comment]
> 那个不是问题，是这样设计的，因为即使刷到可用的话，也有可能过一段时间失效不能用，所以又要重新测试，所以是不停的刷的，没有退出的，你放screen刷

这个设计能否优化一下，定时刷啊，fork一个后台进程，用户可以自定义间隔（可以直接调用crontab, 脚本包一层的话可以优化一下逻辑，防止CF防刷），这样就可以无人值守，时常可用了，脚本可以检测pid文件检测这个进程。用screen太麻烦了，目前这种方式不太友好啊-_-!

**Comment by GreatMichaelLee** [comment]
> > 那个不是问题，是这样设计的，因为即使刷到可用的话，也有可能过一段时间失效不能用，所以又要重新测试，所以是不停的刷的，没有退出的，你放screen刷
> 
> 这个设计能否优化一下，定时刷啊，fork一个后台进程，用户可以自定义间隔（可以直接调用crontab, 脚本包一层的话可以优化一下逻辑，做下间隔限制，防止CF防刷策略被ban掉），这样就可以无人值守，时常可用了，脚本可以检测pid文件检测这个进程。用screen太麻烦了，目前这种方式不太友好啊-_-!

另外现行脚本好像刷ip有个bug或者叫logic hole吧，好像不管当前Ip可不可以解锁，一上来就直接开刷了，是不是可以先进到脚本先检测一下当前ip是不是可以解，如果可以解锁就直接返回了？反正我测的是进来就不管三七二十一直接刷，不管当前IP是不是OK,不知道当前脚本实现是不是这样？如果当前IP可用，建议就不用再重复刷了。

**Comment by fscarmen** [comment]
> 好像不管当前Ip可不可以解锁，一上来就直接开刷了，是不是可以先进到脚本先检测一下当前ip是不是可以解，如果可以解锁就直接返回了？

现在是这样啊，看那个IP能解锁的话，不会刷的。先检测，能解锁等待1小时，不能解锁才换IP
<img width="1071" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/3a2db7dd-f681-42b4-a644-bd9ac90f58b9">

> 这个设计能否优化一下，定时刷啊?

菜单 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 

或者以下项目请了解下
https://github.com/fscarmen/warp_unlock

**Comment by GreatMichaelLee** [comment]
> > 好像不管当前Ip可不可以解锁，一上来就直接开刷了，是不是可以先进到脚本先检测一下当前ip是不是可以解，如果可以解锁就直接返回了？
> 
> 现在是这样啊，看那个IP能解锁的话，不会刷的。先检测，能解锁等待1小时，不能解锁才换IP <img alt="image" width="1071" src="https://user-images.githubusercontent.com/62703343/255386768-3a2db7dd-f681-42b4-a644-bd9ac90f58b9.png">
> 
> > 这个设计能否优化一下，定时刷啊?
> 
> 菜单 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知)
> 
> 或者以下项目请了解下 https://github.com/fscarmen/warp_unlock

哦，那逻辑没问题。

可能我不需要warp脚本帮我做额外的分流工作，我一般自己写xray的json做分流了，因为我自己有些定制化分流需求，用warp脚本可能就搞乱了…这里只希望用到这个刷ip的功能，但是貌似，呃…就是前面说的问题了，大佬评估一下看能否优化吧，毕竟我想还是有需求有场景的，哈哈，谢了。

**Comment by fscarmen** [comment]
> 我一般自己写xray的json做分流了，因为我自己有些定制化分流需求，用warp脚本可能就搞乱了…

你可以用 wireproxy / client 和 warp-go 非全局方案，这些都不会影响到你的原生 IP，符合你说的场景，如果有更复杂的，这个就太个性化了，脚本处理不了。

**Comment by GreatMichaelLee** [comment]
> > 我一般自己写xray的json做分流了，因为我自己有些定制化分流需求，用warp脚本可能就搞乱了…
> 
> 你可以用 wireproxy / client 和 warp-go 非全局方案，这些都不会影响到你的原生 IP，符合你说的场景，如果有更复杂的，这个就太个性化了，脚本处理不了。

算了，我把你的脚本这个刷ip的命令注册为Linux 服务，用simple或者fork方式就好了。卡在这里，实在难受，关键是我的这个ssh终端session不可能一直不关啊，ctrl+c关了这个刷的就退出了，最要命的是ctl+c刷到的IP没有reattach上去，warp也shutdown了。

**Comment by GreatMichaelLee** [comment]
已搞定，用simple类型注册了一个服务，算是一个reference case吧，谢了。

```
[Unit]
Description=warpip
After=network.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/usr/bin/warp i hk
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

![image](https://github.com/fscarmen/warp/assets/20067401/f39f6719-48f6-416b-a0a5-bc044af61d4e)

**Comment by fscarmen** [comment]
Nice
