### ISSUE TITLE
链式代理模式下如何刷解锁ip

### ISSUE THREAD

**Issue by shandongtlb** [fscarmen/warp#468]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

如题，在使用链式代理模式时，如何刷解锁的ip呢
[链接](https://github.com/fscarmen/warp#%E9%80%9A%E8%BF%87-warp-%E8%A7%A3%E9%94%81-chatgpt-%E7%9A%84%E6%96%B9%E6%B3%95)

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
不行

**Comment by shandongtlb** [comment]
好吧谢谢
