### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by liangfengshan** [fscarmen/warp#469]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

用 warp 刷出来的 IP 是中国的 ipv6 地址是什么原因

### Log / 日志信息

无
<img width="813" alt="image" src="https://github.com/fscarmen/warp/assets/35560294/7a0596a7-61a9-459b-b30a-169065da7d67">

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你看看该IP在其他平台是不是也认定为中国了，是 cf 就近原则分配的，改不了。

**Comment by liangfengshan** [comment]
> 你看看该IP在其他平台是不是也认定为中国了，是 cf 就近原则分配的，改不了。

好吧 😮‍💨
