### ISSUE TITLE
[help wanted 求助]: warp-go.sh无法获取ip

### ISSUE THREAD

**Issue by zhiwen-Jiang** [fscarmen/warp#470]
### Script / 脚本

warp-go.sh

### OS / 操作系统

CentOS - Linux

### Actual Situation / 实际情况

 当前账户类型是: free
 1. 继续使用 free 账户，不变更
 2. 变更为 WARP+ 账户
 3. 变更为 Teams 账户 (可通过 https://web--public--warp-team-api--coia-mfs4.code.run 轻松获取，如果留空，则使用脚本提供的)
 0. 返回主菜单

 请选择: 1
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

### Log / 日志信息

 当前账户类型是: free
 1. 继续使用 free 账户，不变更
 2. 变更为 WARP+ 账户
 3. 变更为 Teams 账户 (可通过 https://web--public--warp-team-api--coia-mfs4.code.run 轻松获取，如果留空，则使用脚本提供的)
 0. 返回主菜单

 请选择: 1
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
卸载重装，选free账户看行不行？

**Comment by ysk666666** [comment]
@zhiwen-Jiang 再试试，我昨天也无法获取到ip，今天好了。感觉跟vps所在的地区有关
