### ISSUE TITLE
[help wanted 求助]: 在未获取到ipv4与6时，vps疑似断网？

### ISSUE THREAD

**Issue by OuOumm** [fscarmen/warp#471]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

![image](https://github.com/fscarmen/warp/assets/43441064/3a016973-afa7-4013-ba23-090e7d4babb6)

安装了xray。

跟之前发的issue一样，但是使用了sudo systemctl enable systemd-resolved.service重启后恢复了正常，不过在没有获取到ip后，网络又出问题了，并且整个vps的网络出现故障，故障情况，ping 8.8.8.8显示超时。

### Log / 日志信息

PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
38 packets transmitted, 0 received, 100% packet loss, time 941ms

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
```
wg-quick down warp
warp u
systemctl restart systemd-resolved
```

先卸载了，这样再看看有没有网络

**Comment by OuOumm** [comment]
> ```
> wg-quick down warp
> warp u
> systemctl restart systemd-resolved
> ```
> 
> 先卸载了，这样再看看有没有网络

寄，warp u执行卡住了。

**Comment by fscarmen** [comment]
可以不？

**Comment by OuOumm** [comment]
> 可以不？

不太行 还是没有网络

![image](https://github.com/fscarmen/warp/assets/43441064/a116499f-899a-4dde-8c14-c39ca1786fad)

**Comment by fscarmen** [comment]
如果仍然未能处理的话，方便的话发个 ssh 信息到 fscarmen@gmail.com ，我看看。

**Comment by fscarmen** [comment]
看了，之前应该是没有卸载好，清理干净后重新安装就可以了

<img width="829" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/b601228d-b944-491c-b7f5-253fe8e337a8">

**Comment by fscarmen** [comment]
我不知道为什么 wg-quick 命令没有了，同时 /etc/wireguard目录也没有了，但 `ip a` 中 ，warp 网卡还存在，我用了 `ifconfig warp down`来把网络接口关闭后网络恢复正常，我再安装一次，卸载一次(warp u)以便卸载清楚，最后再安装一次。

至于为什么发生以上情况不清楚，用脚本卸载里没有见过这个情况，可能是中途遇到问题中断了，又使用了一些手动命令导致的。

**Comment by OuOumm** [comment]
> 我不知道为什么 wg-quick 命令没有了，同时 /etc/wireguard目录也没有了，但 `ip a` 中 ，warp 网卡还存在，我用了 `ifconfig warp down`来把网络接口关闭后网络恢复正常，我再安装一次，卸载一次(warp u)以便卸载清楚，最后再安装一次。
> 
> 至于为什么发生以上情况不清楚，用脚本卸载里没有见过这个情况，可能是中途遇到问题中断了，又使用了一些手动命令导致的。

懂了。没有获取到ipv4跟6的时候，卸载命令就用不出来，卡在那里不会动。准确来说整个脚本都加载不出来。要等很久。
