### ISSUE TITLE
[help wanted 求助]: 只能使用 wireguard kernel 运行   没有找到适合的方案用于修改 warp 配置文件 warp.conf

### ISSUE THREAD

**Issue by OuOumm** [fscarmen/warp#472]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

![image](https://github.com/fscarmen/warp/assets/43441064/099308b6-1848-47f0-b3e4-639714aafa04)

还是这个问题，已经卸载了，执行了多次warp u命令，也用了https://github.com/fscarmen/warp/issues/471
https://github.com/fscarmen/warp/issues/465 的解决方法，但是都没解决。服务商最近进行了一次迁移备份升级，并且ip地址也换了，不卸载vps解析不到网络，就只能卸载重装，重装的时候就提示这个了。

### Log / 日志信息

![image](https://github.com/fscarmen/warp/assets/43441064/099308b6-1848-47f0-b3e4-639714aafa04)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
方便的话，你重置一下系统再安装，不卸载了。

**Comment by OuOumm** [comment]
> 方便的话，你重置一下系统再安装，不卸载了。

好吧~也只能这样了。就是要装一大堆东西了。

**Comment by fscarmen** [comment]
要么你把系统ssh发我 fscarmen@gmail.com

**Comment by OuOumm** [comment]
> 要么你把系统ssh发我 [fscarmen@gmail.com](mailto:fscarmen@gmail.com)

已发送。

**Comment by fscarmen** [comment]
可以了，很奇怪，你的vps访问不了 https://www.cloudflare.com ，我改为  https://1.1.1.1

<img width="924" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/813bad3f-48b1-4dba-9e52-ffbfa1242f7d">

**Comment by OuOumm** [comment]
> 可以了，很奇怪，你的vps访问不了 https://www.cloudflare.com ，我改为 https://1.1.1.1
> 
> <img alt="image" width="924" src="https://user-images.githubusercontent.com/62703343/257116651-813bad3f-48b1-4dba-9e52-ffbfa1242f7d.png">

可能是dns问题？

**Comment by fscarmen** [comment]
我看过 /etc/resolv.conf ，好像又没什么问题

OuO_umm ***@***.***>于2023年7月31日 周一12:40写道：

**Comment by OuOumm** [comment]
> 我看过 /etc/resolv.conf ，好像又没什么问题 
尝试关闭warp运行curl命令，提示这个了。
curl -i www.cloudflare.com/cdn-cgi/trace/   
curl: (52) Empty reply from server

加上https
curl -i https://www.cloudflare.com/cdn-cgi/trace/
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.cloudflare.com:443

**Comment by fscarmen** [comment]
```
curl --interface warp www.cloudflare.com/cdn-cgi/trace/
```

**Comment by fscarmen** [comment]
> > 可以了，很奇怪，你的vps访问不了 https://www.cloudflare.com ，我改为 https://1.1.1.1
> > <img alt="image" width="924" src="https://user-images.githubusercontent.com/62703343/257116651-813bad3f-48b1-4dba-9e52-ffbfa1242f7d.png">
> 
> 可能是dns问题？

都是用谷歌的解析，看不出问题，但就是 cloudflare.com 不能，而 1.1.1.1 则可以。
```
root@:~# cat /etc/resolv.conf
# --- BEGIN PVE ---
search ds.oranme.net
nameserver 8.8.8.8
nameserver 8.8.4.4
# --- END PVE ---
```

**Comment by OuOumm** [comment]
> ```
> curl --interface warp www.cloudflare.com/cdn-cgi/trace/
> ```

尝试了一下，经过warp之后就可以了
curl --interface warp www.cloudflare.com/cdn-cgi/trace/
fl=71f1022
h=www.cloudflare.com
ip=2a09:bac5:2aa2:2c8::47:3fe
ts=1690784815.961
visit_scheme=http
uag=curl/7.64.0
colo=FRA
sliver=none
http=http/1.1
loc=DE
tls=off
sni=off
warp=on
gateway=off
rbi=off
kex=none

**Comment by OuOumm** [comment]
> 

离谱的是，我改成这样的dns都不行
cat /etc/resolv.conf
# Generated by resolvconf
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2606:4700:4700::1111
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844

**Comment by OuOumm** [comment]
有点像IP被cloudflare拉黑了的感觉？

**Comment by fscarmen** [comment]
> 有点像IP被cloudflare拉黑了的感觉？

我也是第一次遇到 cloudflare 不通，1.1.1.1通的，你试试ping一下，详细你可以问问供应商，发个ticket.

**Comment by OuOumm** [comment]
> > 有点像IP被cloudflare拉黑了的感觉？
> 
> 我也是第一次遇到 cloudflare 不通，1.1.1.1通的，你试试ping一下，详细你可以问问供应商，发个ticket.

`root@OranMe:/root# ping www.cloudflare.com
PING www.cloudflare.com(2606:4700::6810:7b60 (2606:4700::6810:7b60)) 56 data bytes
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=1 ttl=64 time=7.28 ms
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=2 ttl=64 time=6.50 ms
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=3 ttl=64 time=6.16 ms
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=4 ttl=64 time=6.02 ms
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=5 ttl=64 time=6.23 ms`


有点离谱的感觉。。

**Comment by fscarmen** [comment]
关了warp再ping

**Comment by OuOumm** [comment]
> 关了warp再ping

```
root@OranMe:/root# warp o
 已暂停 WARP，再次开启可以用 warp o 
root@OranMe:/root# ping www.cloudflare.com
PING www.cloudflare.com(2606:4700::6810:7b60 (2606:4700::6810:7b60)) 56 data bytes
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=1 ttl=56 time=5.79 ms
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=2 ttl=56 time=5.69 ms
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=3 ttl=56 time=5.86 ms
64 bytes from 2606:4700::6810:7b60 (2606:4700::6810:7b60): icmp_seq=4 ttl=56 time=6.17 ms
```

emmm居然通的

**Comment by OuOumm** [comment]
> 关了warp再ping

这是开了warp的

```

root@OranMe:/root# warp o 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 已成功获取 WARP 网络 
 IPv4:104.28.221.41 德国 Cloudflare, Inc.
 IPv6:2a09:bac5:2aa3:2c8::47:2e2 德国 Cloudflare 
root@OranMe:/root# curl -i https://www.cloudflare.com/cdn-cgi/trace/
HTTP/2 200 
date: Mon, 31 Jul 2023 06:39:07 GMT
content-type: text/plain
access-control-allow-origin: *
server: cloudflare
cf-ray: 7ef3d7aa3f7a5b4a-FRA
x-frame-options: DENY
x-content-type-options: nosniff
expires: Thu, 01 Jan 1970 00:00:01 GMT
cache-control: no-cache

fl=71f738
h=www.cloudflare.com
ip=2a09:bac5:2aa3:2c8::47:2e2
ts=1690785547.878
visit_scheme=https
uag=curl/7.64.0
colo=FRA
sliver=010-fra03
http=http/2
loc=DE
tls=TLSv1.3
sni=plaintext
warp=on
gateway=off
rbi=off
kex=X25519
```

**Comment by fscarmen** [comment]
具体不知道为什么，在原生网络出口中 curl cloudflare 居然不行，你有时间就查查，知道的话告诉声啦

**Comment by OuOumm** [comment]
> 具体不知道为什么，在原生网络出口中 curl cloudflare 居然不行，你有时间就查查，知道的话告诉声啦

OK，排查完跟你说。

**Comment by OuOumm** [comment]
> 具体不知道为什么，在原生网络出口中 curl cloudflare 居然不行，你有时间就查查，知道的话告诉声啦

排查完啦，服务商阻塞了全部外网域名。

**Comment by fscarmen** [comment]
但为什么ping得通呢？

**Comment by OuOumm** [comment]
> 但为什么ping得通呢？
做了域名限制，但是没做ip限制，23333
