### ISSUE TITLE
[help wanted 求助]: 请问只有warp-go支持非全局IP吗？-【结论：2023.8.15，支持 warp 非全局方案】

### ISSUE THREAD

**Issue by w123456w30w** [fscarmen/warp#475]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

请问只有warp-go支持非全局IP吗？

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
menu.sh 里的 wireproxy / dnsmasq+ipset / client 的warp模式/ client 的proxy模式 ，这4个都是非全局的

**Comment by w123456w30w** [comment]
> menu.sh 里的 wireproxy / dnsmasq+ipset / client 的warp模式/ client 的proxy模式 ，这4个都是非全局的

感谢回复，那这些模式下面的wireguard是使用wireguard-go实现的还是说可以用kernel wireguard？

**Comment by fscarmen** [comment]
|方案|wireguard-go|kernel wireguard|
|-|-|-|
|warp|yes|yes|
|warp-go|no|no|
|wireproxy|no|no|
|dnsmasq+ipset|yes|yes|
|client 的warp模式|no|no|
|client 的proxy|no|no|

**Comment by fscarmen** [comment]
2023.8.15 menu.sh V3.00 1. Add a non-global working mode, it can be switched use [warp g], which requires a script reinstallation; 2. Support regions sanctioned by Cloudflare, such as Russia, with a shared account; 3. IPv6 only uses the preset nat64 and restores the original nameserver file when uninstalled; 1. 增加warp的非全局工作模式，可以通过 [warp g] 切换，需要重装脚本; 2. 支持被Cloudflare制裁地区，如俄罗斯，使用共享账户; 3. IPv6 only 使用预设 nat64，卸载时恢复原始 nameserver 文件
