### ISSUE TITLE
Warp官方客户端 warp模式，不做任何额外配置能直接使用[help wanted 求助]: 

### ISSUE THREAD

**Issue by jnxyatmjx** [fscarmen/warp#477]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

官方客户端 Warp模式下，warp-cli connect 后 不做任何其他配置下，vps能正常ssh连接。之前好像不行。咋地了是官方升级了吗

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by jnxyatmjx** [comment]
debian@ghk:~$ ip rule show
0:      from all lookup local
32765:  not from all fwmark 0x100cf lookup 65743
32766:  from all lookup main
32767:  from all lookup default
会看到 增加了路由规则

**Comment by jnxyatmjx** [comment]
> > 可能除了 22端口 ，其他端口都无法直接连接。好奇怪。iptables也没发现异常
> 
> 你不说真不知道啊，官方之前的使用可以说是很大的坑的，用户必须要设置22的回源路由，否则设置mode 为 proxy，一 connect 马上失联。vps 的后台能 ssh 的还好，没有的话只能重置，难度他处理了这个问题了？

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/configure-warp/route-traffic/warp-architecture/ 看这个连接，估计warp自己处理了。应该是用fwmark 方式打包，且做了逻辑过滤。但iptables上没发现有相关配置项

**Comment by fscarmen** [comment]
等下，我刚才看漏了，你是说 warp 模式吗？之前也是可以的啊，ssh 不会断，就是没有路由，你的科学等没有办法走 client 的 warp 而已。是 proxy 模式才会失联。

**Comment by jnxyatmjx** [comment]
> 等下，我刚才看漏了，你是说 warp 模式吗？之前也是可以的啊，ssh 不会断，就是没有路由，你的科学等没有办法走 client 的 warp 而已。是 proxy 模式才会失联。

不是吧 proxy模式 只是起了一个socks5代理。不会监控机器网络。warp才是类似全局吧。

**Comment by jnxyatmjx** [comment]
搞乌龙了！！！应该是设置的warp Split Tunnels的问题。

**Comment by fscarmen** [comment]
> 搞乌龙了！！！应该是设置的warp Split Tunnels的问题。

这个split tunnels 是如何玩的？

**Comment by jnxyatmjx** [comment]
> > 搞乌龙了！！！应该是设置的warp Split Tunnels的问题。
> 
> 这个split tunnels 是如何玩的？

官方客户端默认split tunnels是exclude模式这就使全局流量都走warp。
把split tunnels改为Include IPs and domains，就保证了vps能正常访问。同时vps上还有虚拟接口 CloudflareWARP。
再使用xray的接口方式，就能愉快用官方warp了。试用了两天现在看很稳的。
