### ISSUE TITLE
检测解锁Netflix失效，是否可以加入定时任务-【结论：该功独立出来另一新项目，为 WARP 解锁流媒体而生: https://github.com/fscarmen/warp_unlock】

### ISSUE THREAD

**Issue by Netflixxp** [fscarmen/warp#48]
change_ip()这个部分，能否加入定时检测IP是否被Netflix封了，如果是就自动运行更换IP的指令

**Comment by fscarmen** [comment]
好提议，我想想如何做

**Comment by at2008** [comment]
高频检测会不会被封IP什么的？

**Comment by fscarmen** [comment]
> 高频检测会不会被封IP什么的？

应该不怕，因为不行就换ip了，又不是一个固定的ip，但就是怕永远刷不出来，我试过了，刷了一晚3000多次都不行

**Comment by Netflixxp** [comment]
其实就是加个定时任务，检测IP是否解锁，不解锁就运行更换IP的指令，直到解锁

**Comment by fscarmen** [comment]
> 直到解锁

前面都没问题，就是这个，如一直解锁不了，机器会死循环不停换warp ip的哦

**Comment by fscarmen** [comment]
[WARP Teams 获取并用于 Linux 的方法](README.md#WARP-Teams-获取并用于-Linux-的方法)
