### ISSUE TITLE
[Bug]: 安装3.00版本检查环境后卡住-【结论：2023年8月17日，重构了查 IP 的逻辑，已解决】

### ISSUE THREAD

**Issue by GreatMichaelLee** [fscarmen/warp#481]
### Expectation / 预期情况

应该顺利走往下一步

### Actual Situation / 实际情况

卡住半天不动，用-x查看发现卡在探测一个什么网址这里。
![image](https://github.com/fscarmen/warp/assets/20067401/e87ce2a7-717f-4cd7-81f9-2f9ba011c371)

### Reproduction Method / 复现方法

正常执行warp

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
你卡那地方与现在的升级没有关系的，你卡在 `curl --retry 5 -ks4m5 --interface warp https://www.cloudflare.com/cdn-cgi/trace`
你手动执行再看看，或者运行这个 `curl --retry 5 -ks4m5 --interface warp https://1.1.1.1/cdn-cgi/trace`，以下一台是 IPv4 only ，一台是 IPv6 only 的机器
<img width="950" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/df35a918-3245-4323-bf9f-ae5ad00cea87">
<img width="966" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/05f18f1e-272a-45f1-8822-e644bb8e2248">

**Comment by GreatMichaelLee** [comment]
> curl --retry 5 -ks4m5 --interface warp https://1.1.1.1/cdn-cgi/trace

手动也是卡啊

**Comment by GreatMichaelLee** [comment]
> > curl --retry 5 -ks4m5 --interface warp https://1.1.1.1/cdn-cgi/trace
> 
> 手动也是卡啊

我有两个机器，一个香港，一个美国，都是一样的卡

**Comment by fscarmen** [comment]
你先不要用warp+，先用免费账号看看。

**Comment by GreatMichaelLee** [comment]
如果我把 curl里的interface从warp改成eth0, 则很快返回结果

**Comment by fscarmen** [comment]
但我这里没有问题，搞不清楚什么情况
第一台机器
<img width="827" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/01912a9e-090d-4ec6-b16c-ae445455b0c6">

第二台机器
<img width="811" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/8f819bea-811f-449e-846b-208fcdeac49f">

**Comment by GreatMichaelLee** [comment]
我明白了，我看你的ipv4是104开头的，这个是cloudflare的ip吧，你用的ipv4/6双栈吧？你用v6单站试试？我的warp是v6, v4没有用warp

**Comment by GreatMichaelLee** [comment]
我估计URL是v4的，用warp v6 interface去curl,可能有问题。

**Comment by fscarmen** [comment]
我这里仍然没有卡，一台 ipv4 的机器，另一台是 ipv6 的机器，都是使用 warp ipv6 非全局

<img width="868" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/24ebd772-bef7-4a7c-b1ff-b640c93ad0a0">

<img width="873" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/ce1220a9-2f7b-4e51-be2e-5d75abc8e294">

**Comment by GreatMichaelLee** [comment]
你看你的ipv4也显示不出来了是不是？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月16日(周三) 晚上7:39
收件人: ***@***.***&gt;;
抄送: "michael ***@***.******@***.***&gt;;
主题: Re: [fscarmen/warp] [Bug]: 安装3.00版本检查环境后卡住 (Issue #481)




 
我这里仍然没有卡，一台 ipv4 的机器，另一台是 ipv6 的机器，都是使用 warp ipv6 非全局

**Comment by fscarmen** [comment]
是啊，因为选了只要 warp ipv6 啊，要双栈就 [warp d]，要 warp ipv4 就 [warp 4]，这样来切换啊

**Comment by GreatMichaelLee** [comment]
不是这样的，上一版是都显示的。这个不是主要问题。主要问题还是curl卡，影响使用，麻烦debug一下，估计就是我说的原因，curl有没有类似ping/ping6这样的区别？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月16日(周三) 晚上7:58
收件人: ***@***.***&gt;;
抄送: "michael ***@***.******@***.***&gt;;
主题: Re: [fscarmen/warp] [Bug]: 安装3.00版本检查环境后卡住 (Issue #481)




 
是啊，因为选了只要 warp ipv6 啊，要双栈就 [warp d]，要 warp ipv4 就 [warp 4]，这样来切换啊

**Comment by fscarmen** [comment]
> 不是这样的，上一版是都显示的。这个不是主要问题。主要问题还是curl卡，影响使用，麻烦debug一下，估计就是我说的原因，curl有没有类似ping/ping6这样的区别？

今天处理下逻辑，知道问题点在哪里了

**Comment by fscarmen** [comment]
[menu.sh.zip](https://github.com/fscarmen/warp/files/12365022/menu.sh.zip)

我已经改过一个逻辑，先给你测一下。
你下载到vps，把 .zip 去掉，记得不是解压，直接去掉，因为附件不能传 .sh 文件
之后 `mv -f menu.sh /etc/wireguard/` 再看看

**Comment by GreatMichaelLee** [comment]
> 我已经改过一个逻辑，`warp v` 升级

修复了~感谢！

**Comment by fscarmen** [comment]
> > 我已经改过一个逻辑，`warp v` 升级
> 
> 修复了~感谢！

Nice，有问题再过来提。
