### ISSUE TITLE
[help wanted 求助]: 

### ISSUE THREAD

**Issue by wulfric93** [fscarmen/warp#482]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

hi there hope you doing well 
i want to use warp globaly on my vps which located in iran 
i enterd Warp+ key and the ip given to me is from iran 
is it possible to change warp ip to another country ?

### Log / 日志信息

==============================================================

 Through Iptable + dnsmasq + ipset, minimize the realization of media unblocking such as chatGPT, Netflix, WARP IPv4 only takes over the streaming media traffic,adapted from the mature works of [Anemone],[https://github.com/acacia233/Project-WARP-Unlock] 

==============================================================

 1. Run script 
 0. Exit 

 Choose: 1

 Install using:
 1. wireguard kernel (default)
 2. wireguard-go with reserved 

 Choose: 1
 No suitable solution was found for modifying the warp configuration file warp.conf and the script aborted. When you see this message, please send feedback on the bug to:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
So far no effective solution has been found. Cloudflare will assign IPs to the nearest data center outlets.
