### ISSUE TITLE
[Bug]: iptable无法获取到IP

### ISSUE THREAD

**Issue by EmbyTV** [fscarmen/warp#484]
### Expectation / 预期情况

正常获取IP

### Actual Situation / 实际情况

iptable无法获取到IP，不管是v4还是v6，但是wireproxy一切正常，wireproxy一下子就获取到了，iptable模式下，用warp i都一直刷不出来获取不到

### Reproduction Method / 复现方法

menu选择12或者13

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
<img width="1085" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/3b4c5c09-2a37-4e01-aa25-487ef8f7bd53">

我这里可以，你的情况如何，截个图

**Comment by fscarmen** [comment]
iptable 方案比其他的都吃环境，有的系统就是不行，CentOS 是全部不行，也不好排查，用其他方案替代吧。
