### ISSUE TITLE
[help wanted 求助]: Ubuntu 安装 wireguard-tools 时报错W:GPG error:http://deb.debian.org/debian buster-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO PUBKEY ***** -【结论：从 Ubuntu 的密钥服务器中获取并导入所需的公钥，运行 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ******】

### ISSUE THREAD

**Issue by MS666666** [fscarmen/warp#485]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

安装时报一个 **没有安装 WireGuard tools 或者找不到配置文件 warp.conf，请重新安装。**错误这个如何解决，求大佬们告知！

### Log / 日志信息

![image](https://github.com/fscarmen/warp/assets/44149537/8848bbeb-db60-495c-b0ef-4522be241a0f)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
运行 `sed -i "/clear/d" menu.sh; bash -x menu.sh` ，把日志发出来看看

**Comment by MS666666** [comment]
@fscarmen 
![image](https://github.com/fscarmen/warp/assets/44149537/90ec9f5b-e4e9-41d7-a648-94e98f9184f2)

**Comment by MS666666** [comment]
@fscarmen 还是报错
![image](https://github.com/fscarmen/warp/assets/44149537/82dc825f-7a73-4bf9-b116-84b55c9c21c6)

**Comment by fscarmen** [comment]
试试 ` apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131`再安装， 最后的那个key你复制你错误那里，不要直接用我的，我可能输入错的，之后再运行多次 `
apt update; apt -y install wireguard-tools`

<img width="1673" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/33753331-1874-4785-9ad6-9e57e80356ea">

**Comment by MS666666** [comment]
@fscarmen OK了谢谢大哥
![image](https://github.com/fscarmen/warp/assets/44149537/057dc82d-8515-4bcb-8cee-de0f80856659)

**Comment by fscarmen** [comment]
这个是ubuntu的问题，有报错的话，可以查查chatGPT，google，这些是常规报错，很容易查的。
