### ISSUE TITLE
[Bug]: 关闭warp后，重启又默认打开warp

### ISSUE THREAD

**Issue by w9666** [fscarmen/warp#486]
### Expectation / 预期情况

重启后保持关闭warp

### Actual Situation / 实际情况

重启又默认打开warp

### Reproduction Method / 复现方法

warp o 关闭warp
重启VPS

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是这样设计的，如果想开机后不启用，可以用 `systemctl disable --now wg-quick@warp`

**Comment by w9666** [comment]
关闭warp的同时禁用开机启动，打开warp的同时启用开机启动，这不是很合理吗？

**Comment by fscarmen** [comment]
`warp o` 定义为临时开关的，有的用户希望重启后启动，如果增加询问是否关闭重启启动，这样增加交互显然不恰当，一键脚本众品难调啊，如果你想重启不启动，就使用 `systemctl disable --now wg-quick@warp`，如果又想开回来，就使用`systemctl enable --now wg-quick@warp`，感谢支持和理解。
