### ISSUE TITLE
[help wanted 求助]: 容器无法获取IP-【结论：docker 需要在 run 的时候加上参数创建 `--device /dev/net/tun --privileged --cap-add net_admin --cap-add sys_module`】

### ISSUE THREAD

**Issue by Jasonxu2010** [fscarmen/warp#488]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

warp双笺 共享teams 
地理位置：中国广州，同一局域网内电脑/手机正常使用warp

### Log / 日志信息

root@c70945c753b6:~# wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh [option] [lisence/url/token]
--2023-08-25 15:39:31--  https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... ^C
root@c70945c753b6:~# wget -N https://ghproxy.com/https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh [option] [lisence/url/token]
--2023-08-25 15:40:25--  https://ghproxy.com/https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
Resolving ghproxy.com (ghproxy.com)... 129.146.41.82
Connecting to ghproxy.com (ghproxy.com)|129.146.41.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151065 (148K) [text/plain]
Saving to: 'menu.sh'

menu.sh                      100%[==============================================>] 147.52K   114KB/s    in 1.3s    

Last-modified header missing -- time-stamps turned off.
2023-08-25 15:40:28 (114 KB/s) - 'menu.sh' saved [151065/151065]

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp]
 脚本特点:
	 • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
	 • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
	 • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
	 • 支持硬件结构类型: AMD、 ARM 和 s390x
	 • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
	 • 支持 WARP Linux Socks5 Client
	 • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
 
======================================================================================================================

 脚本版本:3.00
 功能新增:1. 增加warp的非全局工作模式，可以通过 [warp g] 切换，需要重装脚本; 2. 支持被Cloudflare制裁地区，如俄罗斯，使用共享账户; 3. IPv6 only 使用预设 nat64，卸载时恢复原始 nameserver 文件; 4. 增加 Github CDN
 系统信息:
	 当前操作系统:Ubuntu 22.04.3 LTS
	 内核:5.15.0-79-generic
	 处理器架构:amd64
	 虚拟化: 
	 IPv4: 119.34.172.61 中国  CHINANET Guangdong province Guangzhou MAN network 
	 IPv6:     
	 WARP 网络接口未开启 
	 Client 未安装 
	 WireProxy 未安装 

======================================================================================================================

 1.  WARP 双栈 转为 WARP IPv4 (warp 4) 
 2.  WARP 双栈 转为 WARP IPv6 (warp 6) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 4
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by Jasonxu2010** [comment]
![image](https://github.com/fscarmen/warp/assets/117326624/7ebaacbf-cd06-4511-870d-982c044c6e5a)

**Comment by fscarmen** [comment]
wg-quick down warp; wg-quick up warp 看看

**Comment by Jasonxu2010** [comment]
![image](https://github.com/fscarmen/warp/assets/117326624/590710c3-c3ea-40c6-86e5-8494a949e6c0)

**Comment by fscarmen** [comment]
提示没权限呢，`sodu wg-quick up warp` 试试呢

**Comment by Jasonxu2010** [comment]
![image](https://github.com/fscarmen/warp/assets/117326624/aef6cb64-55bb-4690-9877-1d4891886656)

**Comment by Jasonxu2010** [comment]
docker的Ubuntu 22.04 已经是root了

**Comment by fscarmen** [comment]
`apt update; apt install -y sudo; sodu wg-quick up warp` 看看

**Comment by dongkid** [comment]
我是docker Debian，出现了同样的问题，无法获取ip。
![Screenshot_2023-08-27-21-11-35-223-edit_com server auditor ssh client](https://github.com/fscarmen/warp/assets/80565742/9067c0c8-85fa-4ebf-9970-c49f880c0350)

**Comment by fscarmen** [comment]
建dockerr 的时候加参数  `--device /dev/net/tun --privileged --cap-add net_admin --cap-add sys_module`

**Comment by dongkid** [comment]
> 建dockerr 的时候加参数 `--device /dev/net/tun --privileged --cap-add net_admin --cap-add sys_module`

问题解决了，谢谢大佬

**Comment by fscarmen** [comment]
> 
> 问题解决了，谢谢大佬

谢谢支持。

**Comment by fscarmen** [comment]
> docker的Ubuntu 22.04 已经是root了

参照上面的解决方案，最开始的时候，你并没有提到你的ubuntu22.04是docker来的。
