### ISSUE TITLE
Hax OpenVZ区无法获取warp ip-【结论：长时间未见回复，估计问题已处理 】

### ISSUE THREAD

**Issue by misakano7545** [fscarmen/warp#49]
https://streamable.com/x780ua
安装过程如下

同样的机器，kkkyg的脚本可以正常获取

**Comment by fscarmen** [comment]
今天早上更新了一下，你再试试

**Comment by fscarmen** [comment]
我这里是没有问题的，如果你有鸡仍然不行，发给我有针对性的看看更好

![image](https://user-images.githubusercontent.com/62703343/147717528-b5e1ba42-ed93-421a-8d1e-b7b29727d25b.png)
