### ISSUE TITLE
[help wanted 求助]: 无法获取ip-【结论：Rocky Linux 9.0 暂不支持】

### ISSUE THREAD

**Issue by gslvly** [fscarmen/warp#490]
### Script / 脚本

warp-go.sh

### OS / 操作系统

Alpine - Linux

### Actual Situation / 实际情况

无法获取ip，偶尔能获取成功，升级版本后就很难获取成功了

### Log / 日志信息

 本项目专为 VPS 添加 WARP 网络接口，使用 wire-go 核心程序，利用CloudFlare-WARP 的各类接口，集成 wireguard-go，可以完全替代 WGCF。 救活了香港、多伦多等 VPS 也可以获取 WARP IP。再次感谢 @CoiaPrant 及其团队。项目地址: https://gitlab.com/ProjectWARP/warp-go/-/tree/master/ 
======================================================================================================================

 脚本版本: 1.1.5
 功能新增: 增加 Github CDN
 系统信息:
	 当前操作系统: Rocky Linux 9.0 (Blue Onyx)
	 内核: 5.14.0-70.13.1.el9_0.x86_64
	 处理器架构: amd64v2
	 虚拟化: kvm 
	 IPv4: 144.34.252.54  美国  IT7 Networks Inc 
	 IPv6:      
	 WARP 网络接口未开启 

======================================================================================================================

 1. WARP 全局 IPv6 转为 WARP 全局 IPv4 (warp-go 4) 
 2. WARP 全局 IPv6 转为 WARP 全局 双栈 (warp-go d) 
 3. 转为 WARP 非全局 网络接口 (warp-go g) 
 4. 打开 warp-go (warp-go o) 
 5. 更换为 Free，WARP+ 或 Teams 账户 (warp-go a) 
 6. 更换支持 Netflix 的 IP (warp-go i) 
 7. 输出 wireguard 和 sing-box 配置文件 (warp-go e) 
 8. 卸载 WARP 网络接口和 warp-go (warp-go u) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 4
 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/488

**Comment by gslvly** [comment]
大佬，我不是用的docker ，是rocky 系统，warp-go o它就直接去找ip 一直到失败

**Comment by gslvly** [comment]
> #488

大佬，我不是用的docker ，是rocky 系统，warp-go o它就直接去找ip 一直到失败

**Comment by fscarmen** [comment]
> > #488
> 
> 大佬，我不是用的docker ，是rocky 系统，warp-go o它就直接去找ip 一直到失败

这个系统极少人使用，所以测试也不多，你试试 warp 主脚本是否可以呢。

**Comment by gslvly** [comment]
进度 1/3: 安装系统依赖…… 

Cloudflare CentOS Packages                                                                                                                           42 kB/s |  27 kB     00:00    
Errors during downloading metadata for repository 'cloudflare':
  - Status code: 404 for https://pkg.cloudflareclient.com/dists/9/main/binary-x86_64/repodata/repomd.xml (IP: 104.19.237.24)
Error: Failed to download metadata for repo 'cloudflare': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Cloudflare CentOS Packages                                                                                                                           42 kB/s |  27 kB     00:00    
Errors during downloading metadata for repository 'cloudflare':
  - Status code: 404 for https://pkg.cloudflareclient.com/dists/9/main/binary-x86_64/repodata/repomd.xml (IP: 104.19.236.24)
Error: Failed to download metadata for repo 'cloudflare': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
menu.sh: line 1831: xxd: command not found

> 刚才开了台 rocky 的试了下，warp-go 的确不行，换成 warp 就行了。
> 
> ```
> [root@instance-4 ~]# bash menu.sh
>  
>  Language:
>  1. English (default) 
>  2. 简体中文
>  
>  Choose: 2
> 
>  所有依赖已存在，不需要额外安装 
> 
>  检查环境中…… 
>  本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp]
>  脚本特点:
>          • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
>          • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
>          • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
>          • 支持硬件结构类型: AMD、 ARM 和 s390x
>          • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
>          • 支持 WARP Linux Socks5 Client
>          • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
>  
> ======================================================================================================================
> 
>  脚本版本:3.00
>  功能新增:1. 增加warp的非全局工作模式，可以通过 [warp g] 切换，需要重装脚本; 2. 支持被Cloudflare制裁地区，如俄罗斯，使用共享账户; 3. IPv6 only 使用预设 nat64，卸载时恢复原始 nameserver 文件; 4. 增加 Github CDN
>  系统信息:
>          当前操作系统:Rocky Linux 8.8 (Green Obsidian)
>          内核:4.18.0-477.15.1.el8_8.cloud.x86_64
>          处理器架构:amd64
>          虚拟化:kvm 
>          IPv4: 34.70.219.202 美国  Google LLC 
>          IPv6:     
>          WARP 网络接口未开启 
>          Client 未安装 
>          WireProxy 未安装 
> 
> ======================================================================================================================
> 
>  1.  为 IPv4 only 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
>  2.  为 IPv4 only 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
>  3.  为 IPv4 only 添加 WARP 双栈网络接口 (bash menu.sh d) 
>  4.  打开 WARP (warp o) 
>  5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
>  6.  更换支持 Netflix 的 IP (warp i) 
>  7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
>  8.  刷 WARP+ 流量 (warp p) 
>  9.  升级内核、安装BBR、DD脚本 (warp b) 
>  10. 同步最新版本 (warp v) 
>  11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
>  12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
>  13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
>  14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
>  0.  退出脚本 
> 
>  请选择: 3
> 
>  只能使用 wireguard-go with reserved 运行 
> 
>  工作模式:
>  1. 全局 (默认)
>  2. 非全局 
> 
>  请选择: 
> 
>  如有 WARP+ 或 Teams 账户请选择
>  1. 使用免费账户 (默认)
>  2. WARP+
>  3. Teams 
> 
>  请选择: 
> 
>  请选择优先级别:
>  1. IPv4
>  2. IPv6
>  3. 使用 VPS 初始设置 (默认) 
> 
>  请选择: 
> 
>  进度 1/3: 安装系统依赖…… 
> 
> Last metadata expiration check: 0:02:03 ago on Thu Aug 31 09:34:23 2023.
> Dependencies resolved.
> =========================================================================================================================================================
>  Package                                 Architecture                      Version                               Repository                         Size
> =========================================================================================================================================================
> Installing:
>  epel-release                            noarch                            8-18.el8                              extras                             24 k
> 
> Transaction Summary
> =========================================================================================================================================================
> Install  1 Package
> 
> Total download size: 24 k
> Installed size: 35 k
> Downloading Packages:
> epel-release-8-18.el8.noarch.rpm                                                                                         837 kB/s |  24 kB     00:00    
> ---------------------------------------------------------------------------------------------------------------------------------------------------------
> Total                                                                                                                    126 kB/s |  24 kB     00:00     
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                                                                                                 1/1 
>   Installing       : epel-release-8-18.el8.noarch                                                                                                    1/1 
>   Running scriptlet: epel-release-8-18.el8.noarch                                                                                                    1/1 
> Many EPEL packages require the CodeReady Builder (CRB) repository.
> It is recommended that you run /usr/bin/crb enable to enable the CRB repository.
> 
> 
>  进度 2/3: 已安装 WARP 
> 
>   Verifying        : epel-release-8-18.el8.noarch                                                                                                    1/1 
> 
> Installed:
>   epel-release-8-18.el8.noarch                                                                                                                           
> 
> Complete!
> Extra Packages for Enterprise Linux 8 - x86_64                                                                            19 MB/s |  16 MB     00:00    
> Last metadata expiration check: 0:00:06 ago on Thu Aug 31 09:36:29 2023.
> Package net-tools-2.0-0.52.20160912git.el8.x86_64 is already installed.
> Package iptables-1.8.4-24.el8.x86_64 is already installed.
> Dependencies resolved.
> Nothing to do.
> Complete!
> Last metadata expiration check: 0:00:09 ago on Thu Aug 31 09:36:29 2023.
> Dependencies resolved.
> =========================================================================================================================================================
>  Package                                 Architecture                   Version                                       Repository                    Size
> =========================================================================================================================================================
> Installing:
>  wireguard-tools                         x86_64                         1.0.20210914-1.el8                            epel                         125 k
> 
> Transaction Summary
> =========================================================================================================================================================
> Install  1 Package
> 
> Total download size: 125 k
> Installed size: 292 k
> Downloading Packages:
> wireguard-tools-1.0.20210914-1.el8.x86_64.rpm                                                                            642 kB/s | 125 kB     00:00    
> ---------------------------------------------------------------------------------------------------------------------------------------------------------
> Total                                                                                                                    384 kB/s | 125 kB     00:00     
> Extra Packages for Enterprise Linux 8 - x86_64                                                                           1.6 MB/s | 1.6 kB     00:00    
> Importing GPG key 0x2F86D6A1:
>  Userid     : "Fedora EPEL (8) <epel@fedoraproject.org>"
>  Fingerprint: 94E2 79EB 8D8F 25B2 1810 ADF1 21EA 45AB 2F86 D6A1
>  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
> Key imported successfully
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                                                                                                 1/1 
>   Installing       : wireguard-tools-1.0.20210914-1.el8.x86_64                                                                                       1/1 
>   Running scriptlet: wireguard-tools-1.0.20210914-1.el8.x86_64                                                                                       1/1 
>   Verifying        : wireguard-tools-1.0.20210914-1.el8.x86_64                                                                                       1/1 
> 
> Installed:
>   wireguard-tools-1.0.20210914-1.el8.x86_64                                                                                                              
> 
> Complete!
> Last metadata expiration check: 0:00:12 ago on Thu Aug 31 09:36:29 2023.
> Dependencies resolved.
> =========================================================================================================================================================
>  Package                              Architecture             Version                                          Repository                          Size
> =========================================================================================================================================================
> Installing:
>  kernel                               x86_64                   4.18.0-477.21.1.el8_8.cloud                      cloud-kernel                       9.4 M
> Upgrading:
>  epel-release                         noarch                   8-19.el8                                         epel                                25 k
>  google-cloud-sdk                     x86_64                   444.0.0-1                                        google-cloud-sdk                   113 M
>  kernel-tools                         x86_64                   4.18.0-477.21.1.el8_8.cloud                      cloud-kernel                       9.6 M
>  kernel-tools-libs                    x86_64                   4.18.0-477.21.1.el8_8.cloud                      cloud-kernel                       9.4 M
>  python3-perf                         x86_64                   4.18.0-477.21.1.el8_8.cloud                      cloud-kernel                       9.6 M
>  python3-syspurpose                   x86_64                   1.28.36-3.el8_8.rocky.0.1                        baseos                             336 k
> Installing dependencies:
>  kernel-core                          x86_64                   4.18.0-477.21.1.el8_8.cloud                      cloud-kernel                        42 M
>  kernel-modules                       x86_64                   4.18.0-477.21.1.el8_8.cloud                      cloud-kernel                        34 M
> 
> Transaction Summary
> =========================================================================================================================================================
> Install  3 Packages
> Upgrade  6 Packages
> 
> Total download size: 227 M
> Downloading Packages:
> (1/9): kernel-4.18.0-477.21.1.el8_8.cloud.x86_64.rpm                                                                     8.0 MB/s | 9.4 MB     00:01    
> (2/9): python3-perf-4.18.0-477.21.1.el8_8.cloud.x86_64.rpm                                                               8.0 MB/s | 9.6 MB     00:01    
> (3/9): kernel-tools-libs-4.18.0-477.21.1.el8_8.cloud.x86_64.rpm                                                          8.4 MB/s | 9.4 MB     00:01    
> (4/9): kernel-core-4.18.0-477.21.1.el8_8.cloud.x86_64.rpm                                                                 10 MB/s |  42 MB     00:04    
> (5/9): python3-syspurpose-1.28.36-3.el8_8.rocky.0.1.x86_64.rpm                                                           5.7 MB/s | 336 kB     00:00    
> (6/9): epel-release-8-19.el8.noarch.rpm                                                                                  165 kB/s |  25 kB     00:00    
> (7/9): kernel-tools-4.18.0-477.21.1.el8_8.cloud.x86_64.rpm                                                               8.5 MB/s | 9.6 MB     00:01    
> (8/9): kernel-modules-4.18.0-477.21.1.el8_8.cloud.x86_64.rpm                                                             6.8 MB/s |  34 MB     00:05    
> (9/9): 1ea9d7165c68b91b389e35600c7f7c55c072e05a99c555297f 92% [===================================================-    ]  32 MB/s | 210 MB     00:00 ETA
>  进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 
> 
> (9/9): 1ea9d7165c68b91b389e35600c7f7c55c072e05a99c555297f03079b4ba56143-google-cloud-sdk-444.0.0-1.x86_64.rpm             29 MB/s | 113 MB     00:03    
> ---------------------------------------------------------------------------------------------------------------------------------------------------------
> Total                                                                                                                     26 MB/s | 227 MB     00:08     
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                                                                                                 1/1 
>   Running scriptlet: kernel-core-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                  1/1 
>   Installing       : kernel-core-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                 1/15 
>   Running scriptlet: kernel-core-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                 1/15 
>   Installing       : kernel-modules-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                              2/15 
>   Running scriptlet: kernel-modules-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                              2/15 
>   Upgrading        : kernel-tools-libs-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                           3/15 
>   Running scriptlet: kernel-tools-libs-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                           3/15 
>   Upgrading        : kernel-tools-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                4/15 
>   Running scriptlet: kernel-tools-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                4/15 
>   Installing       : kernel-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                      5/15 
>   Upgrading        : google-cloud-sdk-444.0.0-1.x86_64                                                                                              6/15 
>   Running scriptlet: google-cloud-sdk-444.0.0-1.x86_64                                                                                              6/15 
>   Upgrading        : epel-release-8-19.el8.noarch                                                                                                   7/15 
>   Running scriptlet: epel-release-8-19.el8.noarch                                                                                                   7/15 
>   Upgrading        : python3-syspurpose-1.28.36-3.el8_8.rocky.0.1.x86_64                                                                            8/15 
>   Upgrading        : python3-perf-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                9/15 
>   Running scriptlet: kernel-tools-4.18.0-477.21.1.el8_8.x86_64                                                                                     10/15 
>   Cleanup          : kernel-tools-4.18.0-477.21.1.el8_8.x86_64                                                                                     10/15 
>   Running scriptlet: kernel-tools-4.18.0-477.21.1.el8_8.x86_64                                                                                     10/15 
>   Running scriptlet: google-cloud-sdk-442.0.0-1.x86_64                                                                                             11/15 
>   Cleanup          : google-cloud-sdk-442.0.0-1.x86_64                                                                                             11/15 
>   Running scriptlet: google-cloud-sdk-442.0.0-1.x86_64                                                                                             11/15 
>   Cleanup          : epel-release-8-18.el8.noarch                                                                                                  12/15 
>   Cleanup          : python3-syspurpose-1.28.36-2.el8.x86_64                                                                                       13/15 
>   Cleanup          : kernel-tools-libs-4.18.0-477.21.1.el8_8.x86_64                                                                                14/15 
>   Running scriptlet: kernel-tools-libs-4.18.0-477.21.1.el8_8.x86_64                                                                                14/15 
>   Cleanup          : python3-perf-4.18.0-477.21.1.el8_8.x86_64                                                                                     15/15 
>   Running scriptlet: kernel-core-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                15/15 
>   Running scriptlet: kernel-modules-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                             15/15 
>   Running scriptlet: python3-perf-4.18.0-477.21.1.el8_8.x86_64                                                                                     15/15 
>   Verifying        : kernel-modules-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                              1/15 
>   Verifying        : kernel-core-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                 2/15 
>   Verifying        : kernel-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                      3/15 
>   Verifying        : python3-perf-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                4/15 
>   Verifying        : python3-perf-4.18.0-477.21.1.el8_8.x86_64                                                                                      5/15 
>   Verifying        : kernel-tools-libs-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                           6/15 
>   Verifying        : kernel-tools-libs-4.18.0-477.21.1.el8_8.x86_64                                                                                 7/15 
>   Verifying        : kernel-tools-4.18.0-477.21.1.el8_8.cloud.x86_64                                                                                8/15 
>   Verifying        : kernel-tools-4.18.0-477.21.1.el8_8.x86_64                                                                                      9/15 
>   Verifying        : python3-syspurpose-1.28.36-3.el8_8.rocky.0.1.x86_64                                                                           10/15 
>   Verifying        : python3-syspurpose-1.28.36-2.el8.x86_64                                                                                       11/15 
>   Verifying        : epel-release-8-19.el8.noarch                                                                                                  12/15 
>   Verifying        : epel-release-8-18.el8.noarch                                                                                                  13/15 
>   Verifying        : google-cloud-sdk-444.0.0-1.x86_64                                                                                             14/15 
>   Verifying        : google-cloud-sdk-442.0.0-1.x86_64                                                                                             15/15 
> 
> Upgraded:
>   epel-release-8-19.el8.noarch                                             google-cloud-sdk-444.0.0-1.x86_64                                            
>   kernel-tools-4.18.0-477.21.1.el8_8.cloud.x86_64                          kernel-tools-libs-4.18.0-477.21.1.el8_8.cloud.x86_64                         
>   python3-perf-4.18.0-477.21.1.el8_8.cloud.x86_64                          python3-syspurpose-1.28.36-3.el8_8.rocky.0.1.x86_64                          
> Installed:
>   kernel-4.18.0-477.21.1.el8_8.cloud.x86_64     kernel-core-4.18.0-477.21.1.el8_8.cloud.x86_64     kernel-modules-4.18.0-477.21.1.el8_8.cloud.x86_64    
> 
> Complete!
> --2023-08-31 09:46:18--  https://cdn4.cloudflare.now.cc/proxy/https://raw.githubusercontent.com/fscarmen/warp/main/wireguard-go/wireguard-go-linux-amd64-20230223
> Resolving cdn4.cloudflare.now.cc (cdn4.cloudflare.now.cc)... 104.21.48.202, 172.67.156.44
> Connecting to cdn4.cloudflare.now.cc (cdn4.cloudflare.now.cc)|104.21.48.202|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 2691072 (2.6M) [application/octet-stream]
> Saving to: ‘/usr/bin/wireguard-go’
> 
> /usr/bin/wireguard-go                  100%[=========================================================================>]   2.57M  --.-KB/s    in 0.06s   
> 
> 2023-08-31 09:46:19 (46.4 MB/s) - ‘/usr/bin/wireguard-go’ saved [2691072/2691072]
> 
>  创建快捷 warp 指令成功 
>  运行 WARP 
>  后台获取 WARP IP 中,最大尝试5次……
>  第1次尝试 
>  已成功获取 WARP 网络, 工作模式: 全局 
> 
> ==============================================================
> 
>  IPv4: 104.28.247.219 美国  Cloudflare, Inc. 
>  IPv6: 2a09:bac5:7520:8c::e:122 美国  Cloudflare Warp 
>  恭喜！WARP 已开启，总耗时:599秒， 脚本当天运行次数:7210，累计运行次数:5822417 
>  IPv6 优先 , 工作模式: 全局 
> 
> ==============================================================
> 
>  再次运行用 warp [option] [lisence]，如
>  
>  warp h (帮助菜单）
>  warp n (获取 WARP IP)
>  warp o (临时warp开关)
>  warp u (卸载 WARP 网络接口和 Socks5 Client)
>  warp b (升级内核、开启BBR及DD)
>  warp a (更换账户为 Free，WARP+ 或 Teams)
>  warp p (刷WARP+流量)
>  warp v (同步脚本至最新版本)
>  warp r (WARP Linux Client 开关)
>  warp 4/6 (WARP IPv4/IPv6 单栈)
>  warp d (WARP 双栈)
>  warp c (安装 WARP Linux Client，开启 Socks5 代理模式)
>  warp l (安装 WARP Linux Client，开启 WARP 模式)
>  warp i (更换支持 Netflix 的IP)
>  warp e (安装 Iptables + dnsmasq + ipset 解决方案)
>  warp w (安装 WireProxy 解决方案)
>  warp y (WireProxy socks5 开关)
>  warp k (切换 wireguard 内核 / wireguard-go-reserved)
>  warp g (切换 warp 全局 / 非全局)
>  warp s 4/6/d (优先级: IPv4 / IPv6 / VPS default)
> ```
感谢大佬回复，rocky9 下载不了centos的pkg,可能支持到了8。在安装系统依赖时挂掉了，如果不行，只能换个系统了。
```
 进度 1/3: 安装系统依赖…… 

Cloudflare CentOS Packages                                                                                                                           42 kB/s |  27 kB     00:00    
Errors during downloading metadata for repository 'cloudflare':
  - Status code: 404 for https://pkg.cloudflareclient.com/dists/9/main/binary-x86_64/repodata/repomd.xml (IP: 104.19.237.24)
Error: Failed to download metadata for repo 'cloudflare': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Cloudflare CentOS Packages                                                                                                                           42 kB/s |  27 kB     00:00    
Errors during downloading metadata for repository 'cloudflare':
  - Status code: 404 for https://pkg.cloudflareclient.com/dists/9/main/binary-x86_64/repodata/repomd.xml (IP: 104.19.236.24)
Error: Failed to download metadata for repo 'cloudflare': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
menu.sh: line 1831: xxd: command not found
```
