### ISSUE TITLE
[Feature request]: 使用e参数安装 iptables + dnsmasq + ipset 分流流媒体方案，能否添加一个只获取ipv6的选项？

### ISSUE THREAD

**Issue by moranno** [fscarmen/warp#491]
### Related Problem / 相关问题

当前使用e参数为只获取cf的ipv4地址作为chatgpt和流媒体的解锁，但经常出现无法获取到ipv4地址情况（特别是美西、香港、俄罗斯）

### Describe the solution you want / 描述你希望的解决方案

能否在e参数下添加一个只获取ipv6地址的选项，作为无法获取到ipv4地址时，获取ipv6地址实现解锁？

### Describe the alternatives you are considering / 描述你所考虑的替代方案

也可以考虑尝试先获取ipv4，如果获取失败，则获取ipv6地址。

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
这个方案比较难调，如果你有用singbox或者xray，用非全局方案就了啦。

**Comment by moranno** [comment]
> 这个方案比较难调，如果你有用singbox或者xray，用非全局方案就了啦。

请问非全局模式是不是需要配合xray或者singbox的出站分流功能？
分流不能用warp脚本做？

**Comment by moranno** [comment]
测试了下非全局模式下很容易就能获取到ipv6地址，ipv4地址为空：不过，既然e参数也是非全局，能否调整下获取地址的策略呢？

![image](https://github.com/fscarmen/warp/assets/77610980/71b27e4a-5b07-4999-a498-8fde167699e5)

**Comment by fscarmen** [comment]
> 测试了下非全局模式下很容易就能获取到ipv6地址，ipv4地址为空，我又尝试warp g切换为全局模式，然后又无法获取ip了
> 
> 不过，既然e参数也是非全局，能否调整下获取地址的策略呢？
> 
> ![image](https://user-images.githubusercontent.com/77610980/264161870-71b27e4a-5b07-4999-a498-8fde167699e5.png)
> 
> ![image](https://user-images.githubusercontent.com/77610980/264162224-a4b4d882-3075-4b8e-84a9-593896b96c61.png)

如果你选择了双栈，不应该 ipv4 那里为空的哦

**Comment by moranno** [comment]
我发现了个奇怪的现象，获取不到warp ip的系统（ubuntu 20.04）尝试升级到22.04也无法获取，更好vps IP后还是无法获取；
后来dd系统到debian 12后很顺利就获取到warp IP了

**Comment by fscarmen** [comment]
> 我发现了个奇怪的现象，获取不到warp ip的系统（ubuntu 20.04）尝试升级到22.04也无法获取，更好vps IP后还是无法获取； 后来dd系统到debian 12后很顺利就获取到warp IP了

这个不知道什么情况，乱猜是原来的 ubuntu 20.04 有点问题，升级的时候一并带延续了。而 debian 12 是新dd的系统，所以成功。
