### ISSUE TITLE
[Bug]: xxd依赖检查缺失后,安装异常

### ISSUE THREAD

**Issue by suninx** [fscarmen/warp#493]
### Expectation / 预期情况

正常安装所缺少依赖

### Actual Situation / 实际情况

新开裸机,没有安装vim,因此缺少xxd依赖,脚本检测到xxd依赖缺失,提示正在安装依赖;
实际上安装依赖没有成功,脚本继续执行下去了,进而导致主机DNS异常,不仅无法获取warp ip,dns也出现异常,无法正常解析域名

### Reproduction Method / 复现方法

卸载vim-common就能复现了吧  xxd依赖在vim-common中

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by suninx** [comment]
我是centos 7.9 2009的发行版,以下是脚本执行打印信息,IP和主机名信息已做处理;

[root@local ~]# wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh [option] [lisence/url/token]
--2023-08-31 08:21:19--  https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151430 (148K) [text/plain]
Saving to: ‘menu.sh’

100%[========================================================================================================================================================================================================>] 151,430      497KB/s   in 0.3s   

Last-modified header missing -- time-stamps turned off.
2023-08-31 08:21:20 (497 KB/s) - ‘menu.sh’ saved [151430/151430]

 
 Language:
 1. English (default) 
 2. 简体中文
 
 Choose: 2

 安装依赖列表: xxd python3 

 检查环境中…… 
 本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp]
 脚本特点:
	 • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
	 • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
	 • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
	 • 支持硬件结构类型: AMD、 ARM 和 s390x
	 • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
	 • 支持 WARP Linux Socks5 Client
	 • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
 
======================================================================================================================

 脚本版本:3.00
 功能新增:1. 增加warp的非全局工作模式，可以通过 [warp g] 切换，需要重装脚本; 2. 支持被Cloudflare制裁地区，如俄罗斯，使用共享账户; 3. IPv6 only 使用预设 nat64，卸载时恢复原始 nameserver 文件; 4. 增加 Github CDN
 系统信息:
	 当前操作系统:CentOS Linux 7 (Core)
	 内核:3.10.0-1160.76.1.el7.x86_64
	 处理器架构:amd64
	 虚拟化:kvm 
	 IPv4: ***.***.***.*** 香港  *** Network Services Limited 
	 IPv6:     
	 WARP 网络接口未开启 
	 Client 未安装 
	 WireProxy 未安装 

======================================================================================================================

 1.  为 IPv4 only 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
 2.  为 IPv4 only 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
 3.  为 IPv4 only 添加 WARP 双栈网络接口 (bash menu.sh d) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 1

 只能使用 wireguard-go with reserved 运行 

 工作模式:
 1. 全局 (默认)
 2. 非全局 

 请选择: 

 如有 WARP+ 或 Teams 账户请选择
 1. 使用免费账户 (默认)
 2. WARP+
 3. Teams 

 请选择: 

 请选择优先级别:
 1. IPv4
 2. IPv6
 3. 使用 VPS 初始设置 (默认) 

 请选择: 

 进度 1/3: 安装系统依赖…… 

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.xtom.com.hk
 * extras: mirror.xtom.com.hk
 * updates: mirror.xtom.com.hk
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-11 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================================================================================================
 Package                                                        Arch                                                     Version                                                   Repository                                                Size
==================================================================================================================================================================================================================================================
Installing:
 epel-release                                                   noarch                                                   7-11                                                      extras                                                    15 k

Transaction Summary
==================================================================================================================================================================================================================================================
Install  1 Package

Total download size: 15 k
Installed size: 24 k
Downloading packages:
epel-release-7-11.noarch.rpm                                                                                                                                                                                               |  15 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : epel-release-7-11.noarch                                                                                                                                                                                                       1/1 
  Verifying  : epel-release-7-11.noarch                                                                                                                                                                                                       1/1 

Installed:
  epel-release.noarch 0:7-11                                                                                                                                                                                                                      

Complete!
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                                                                                                                                                       |  25 kB  00:00:00     
menu.sh: line 1831: xxd: command not found

 进度 2/3: 已安装 WARP 

 * base: mirror.xtom.com.hk
 * epel: creeperhost.mm.fcix.net
 * extras: mirror.xtom.com.hk
 * updates: mirror.xtom.com.hk
epel                                                                                                                                                                                                                       | 4.7 kB  00:00:00     
(1/3): epel/x86_64/group_gz                                                                                                                                                                                                |  99 kB  00:00:01     

 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

epel/x86_64/updateinfo         FAILED                                          
https://mirrors.netix.net/epel/7/x86_64/repodata/8af683c2027f222c6ce4a90e7eb9ff7fe548bd3545e5fcf48f8ef14a60e8d7d0-updateinfo.xml.bz2: [Errno 14] curl#6 - "Could not resolve host: mirrors.netix.net; Unknown error".0 B/s |  48 kB  --:--:-- ETA 
Trying other mirror.
epel/x86_64/primary_db         FAILED                                          
https://mirrors.uni-ruse.bg/epel/7/x86_64/repodata/41b2d1278011955a86cd6b90b6da233f597a99081f053eb8785d5f77edadcd78-primary.sqlite.bz2: [Errno 14] curl#6 - "Could not resolve host: mirrors.uni-ruse.bg; Unknown error"/s |  48 kB  --:--:-- ETA 
Trying other mirror.
(2/3): epel/x86_64/updateinfo                                                                                                                                                                                              | 1.0 MB  00:00:02     
(3/3): epel/x86_64/primary_db                                                                                                                                                                                              | 7.0 MB  00:00:02     
Package net-tools-2.0-0.25.20131004git.el7.x86_64 already installed and latest version
Package iptables-1.4.21-35.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.xtom.com.hk
 * epel: cdn.centos.no
 * extras: mirror.xtom.com.hk
 * updates: mirror.xtom.com.hk
Resolving Dependencies
--> Running transaction check
---> Package wireguard-tools.x86_64 0:1.0.20210914-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================================================================================================
 Package                                                        Arch                                                  Version                                                           Repository                                           Size
==================================================================================================================================================================================================================================================
Installing:
 wireguard-tools                                                x86_64                                                1.0.20210914-1.el7                                                epel                                                122 k

Transaction Summary
==================================================================================================================================================================================================================================================
Install  1 Package

Total download size: 122 k
Installed size: 291 k
Downloading packages:
warning: /var/cache/yum/x86_64/7/epel/packages/wireguard-tools-1.0.20210914-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 352c64e5: NOKEY=====-                                                      ]  0.0 B/s |  53 kB  --:--:-- ETA 
Public key for wireguard-tools-1.0.20210914-1.el7.x86_64.rpm is not installed
wireguard-tools-1.0.20210914-1.el7.x86_64.rpm                                                                                                                                                                              | 122 kB  00:00:01     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-11.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wireguard-tools-1.0.20210914-1.el7.x86_64                                                                                                                                                                                      1/1 
  Verifying  : wireguard-tools-1.0.20210914-1.el7.x86_64                                                                                                                                                                                      1/1 

Installed:
  wireguard-tools.x86_64 0:1.0.20210914-1.el7                                                                                                                                                                                                     

Complete!
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.xtom.com.hk
 * epel: creeperhost.mm.fcix.net
 * extras: mirror.xtom.com.hk
 * updates: mirror.xtom.com.hk
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-11 will be updated
---> Package epel-release.noarch 0:7-14 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================================================================================================
 Package                                                         Arch                                                      Version                                                  Repository                                               Size
==================================================================================================================================================================================================================================================
Updating:
 epel-release                                                    noarch                                                    7-14                                                     epel                                                     15 k

Transaction Summary
==================================================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 15 k
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
epel-release-7-14.noarch.rpm                                                                                                                                                                                               |  15 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : epel-release-7-14.noarch                                                                                                                                                                                                       1/2 
  Cleanup    : epel-release-7-11.noarch                                                                                                                                                                                                       2/2 
  Verifying  : epel-release-7-14.noarch                                                                                                                                                                                                       1/2 
  Verifying  : epel-release-7-11.noarch                                                                                                                                                                                                       2/2 

Updated:
  epel-release.noarch 0:7-14                                                                                                                                                                                                                      

Complete!
--2023-08-31 08:27:05--  https://cdn2.cloudflare.now.cc/https://raw.githubusercontent.com/fscarmen/warp/main/wireguard-go/wireguard-go-linux-amd64-20230223
Resolving cdn2.cloudflare.now.cc (cdn2.cloudflare.now.cc)... 104.21.48.202, 172.67.156.44
Connecting to cdn2.cloudflare.now.cc (cdn2.cloudflare.now.cc)|104.21.48.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2691072 (2.6M) [application/octet-stream]
Saving to: ‘/usr/bin/wireguard-go’

100%[========================================================================================================================================================================================================>] 2,691,072   2.65MB/s   in 1.0s
2023-08-31 08:27:08 (2.65 MB/s) - ‘/usr/bin/wireguard-go’ saved [2691072/2691072]

 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
我更新了，针对centos 7 这个xxd需要 vim-common，请下载附件，把 .zip 去掉，是去掉不是解压，
[menu.sh.zip](https://github.com/fscarmen/warp/files/12486513/menu.sh.zip)

**Comment by suninx** [comment]
了解，感谢您

**Comment by fscarmen** [comment]
> 了解，感谢您

今天还要修些bug，待完善后会更新正式库，如有问题再来告诉我，谢谢支持。

**Comment by fscarmen** [comment]
已经更新了
