### ISSUE TITLE
[help wanted 求助]: 刷不出解锁的IP

### ISSUE THREAD

**Issue by shandongtlb** [fscarmen/warp#494]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

LAX地区 dmit Ubuntu 22.04  

报告2个问题
第一个：
开启cloudflare client warp模式时，重启之后ipv6没有，必须手动关闭开启才能出来；另外刷了一小时ipv4和6，但一直失败：
` 2023-09-01 09:51:56 尝试第227次，解锁失败，IPv6: 2a09:bac5:624f:78::c:376 美国 Cloudflare Warp，10秒后重新测试，刷 IP 运行时长: 0 天 1 时 7 分 52 秒 `

于是乎，我尝试使用warp双栈非全局模式，结果发现第二个问题：
运行几分钟之后，整改系统的ipv6均处于不可用状态，且速度很慢

### Log / 日志信息

暂时没有

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by shandongtlb** [comment]
更新一下，本人另一台机器用的其他的大佬的warp脚本，发现也不行了，难道说nf直接把warp全ban了？

**Comment by GreatMichaelLee** [comment]
> 更新一下，本人另一台机器用的其他的大佬的warp脚本，发现也不行了，难道说nf直接把warp全ban了？

一样的情况，偶然能刷出一个来，坚持不了一个小时就挂了。两个可能性
1. 奈飞对warp6的风控又开始发疯了。之前轻轻松松刷出来，而且坚挺，用个几天都不是问题。
2. 目前脚本检测解锁的机制被奈飞侦测到了，把那两个节目的资源文件做了特殊处理，导致脚本侦测解锁与否的真实有效性非100%可靠。

现在看上去前一个可能性80%，后一个可能性20%

**Comment by shandongtlb** [comment]
> > 更新一下，本人另一台机器用的其他的大佬的warp脚本，发现也不行了，难道说nf直接把warp全ban了？
> 
> 第一个问题估计是脚本的问题，等这里老板fix吧 第二个解锁的问题，一样的情况，偶然能刷出一个来，坚持不了一个小时就挂了。我的美国vps还好点，香港的基本很难。两个可能性
> 
> 1. 奈飞对warp6的风控又开始发疯了，估计自动封v6段。之前轻轻松松刷出来，而且坚挺，用个几天都不是问题。
> 2. 目前脚本检测解锁的机制被奈飞侦测到了，把那两个节目的资源文件做了特殊处理，导致脚本侦测解锁与否的真实有效性非100%可靠。也有可能发现你的源warp v6 IP如果一直在探测访问那两个节目就会把你当前可用的v6给封掉。

我这个是洛杉矶的vps，不行了

**Comment by fscarmen** [comment]
> 另外刷了一小时ipv4和6，但一直失败

如果你看到 IP 有更换，刷的程序还正常即说明脚本没有问题，刷不出解锁也没有办法

> 于是乎，我尝试使用warp双栈非全局模式，结果发现第二个问题：
运行几分钟之后，整改系统的ipv6均处于不可用状态，且速度很慢

你是不是同时在刷非全局的 IPv6 ，在刷的时候，网络会断断续续的

> 第一个：开启cloudflare client warp模式时，重启之后ipv6没有

我的一台机器试过OK，那个 systemd 是 Cloudflare 官方自带的，我也没有作更改，如果仍然不行，就`warp r`重启一下
```
 进度 2/2: 设置 Client 模式 
 Linux Client 正常运行中。 Socks5 代理监听:127.0.0.1:40000 
 创建快捷 warp 指令成功 

==============================================================

 恭喜！WARP Free Linux Client 工作中, 总耗时:22秒， 脚本当天运行次数:9916，累计运行次数:5898464
 本地 Socks5: 127.0.0.1:40000
 WARP Free IPv4: 104.28.215.220 United States Cloudflare, Inc.
 WARP Free IPv6: 2a09:bac5:7521:8c::e:2e3 United States Cloudflare Warp 

==============================================================

 再次运行用 warp [option] [lisence]，如 

 warp h (帮助菜单）
 warp n (获取 WARP IP)
 warp o (临时warp开关)
 warp u (卸载 WARP 网络接口和 Socks5 Client)
 warp b (升级内核、开启BBR及DD)
 warp a (更换账户为 Free，WARP+ 或 Teams)
 warp p (刷WARP+流量)
 warp v (同步脚本至最新版本)
 warp r (WARP Linux Client 开关)
 warp 4/6 (WARP IPv4/IPv6 单栈)
 warp d (WARP 双栈)
 warp c (安装 WARP Linux Client，开启 Socks5 代理模式)
 warp l (安装 WARP Linux Client，开启 WARP 模式)
 warp i (更换支持 Netflix 的IP)
 warp e (安装 Iptables + dnsmasq + ipset 解决方案)
 warp w (安装 WireProxy 解决方案)
 warp y (WireProxy socks5 开关)
 warp k (切换 wireguard 内核 / wireguard-go-reserved)
 warp g (切换 warp 全局 / 非全局)
 warp s 4/6/d (优先级: IPv4 / IPv6 / VPS default)
 
root@instance-2:~# reboot
root@instance-2:~# 

Linux instance-2 5.10.0-25-cloud-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Sep  3 21:17:45 2023 from 130.162.150.73
root@instance-2:~# curl -s6m8 -x socks5://127.0.0.1:40000 ip.sb
2a09:bac5:7527:8c::e:179
root@instance-2:~# curl -s4m8 -x socks5://127.0.0.1:40000 ip.sb
104.28.247.220
```

**Comment by shandongtlb** [comment]
现在已经在用warp双栈非全局模式了，暂时没啥问题，谢谢大佬

**Comment by shandongtlb** [comment]
![Screenshot_20230905_214042_Chrome](https://github.com/fscarmen/warp/assets/40312509/eb4d0fb4-1adc-4a07-9977-d7899873c0f4)
![Screenshot_20230905_214029_Chrome](https://github.com/fscarmen/warp/assets/40312509/3bb5cb20-ea54-4908-81cc-1433cc0600fa)
复现了大佬，使用非全局方案，现在ipv6全挂掉了。。

**Comment by shandongtlb** [comment]
> 你配置文件里，把ip.sb从 warpIPv4 改到6那里看看

配置并没有区分4和6，刚搭建的时候没问题，运行两天之后就这样了。

**Comment by shandongtlb** [comment]
其实也好解决，打开ipv6路由就行了，一切就都解决掉了，现在纠结和疑问的是，在ipv6路由关闭状态下，为什么一开始搭建是好的，用两天就不行了呢，比较奇怪
