### ISSUE TITLE
[help wanted 求助]: 更换解锁netflix的ip成功后未正常退出疑问

### ISSUE THREAD

**Issue by ynhzzu** [fscarmen/warp#495]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

新手咨询：执行warp更换解锁netflix的ip时，更换完毕，一直卡着不退出，是正常现象吗？不是更换成功后就退出吗？

目前没看到什么错误日志，不影响正常使用。

### Log / 日志信息

![image](https://github.com/fscarmen/warp/assets/15062203/e23d0567-fe74-4341-84ba-9dd95a6a9075)

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
是这样的，解锁后保持着，1小时后再测，仍然解锁又会继续1小时，不解锁就马上刷，你用这个的话，最好在screen 下运行。
