### ISSUE TITLE
[help wanted 求助]: 能不能从指定地区选ip

### ISSUE THREAD

**Issue by yonghu996** [fscarmen/warp#498]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

比如我vps设备是香港的，我想warp代理ip为日本的，可以实现吗

### Log / 日志信息

no

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/469
https://github.com/fscarmen/warp/issues/479
