### ISSUE TITLE
被netflix封杀了吗？

### ISSUE THREAD

**Issue by ligang2020** [fscarmen/warp#5]
配置成功！还是不能解锁netflix

**Comment by fscarmen** [comment]
Netflix 再次更改封锁策略

Netflix 在今日（9月1日）凌晨重新调整了他们的策略，封锁力度已大致上回到了8月4号之前的状态。

据初步了解，8月4号以前能解锁 Netflix 的大部分 IP 当前可以解锁，不能解锁的在此次调整中多被重新封禁。

Cloudflare WARP 依然解锁，但不建议大量使用。

8月4日，Netflix 采取了一次极端的封锁，此次封锁导致绝大部分非家宽IP被加入黑名单。8月25日，Netflix 又大范围解封了 IP。此次调整可以被认为是对极端封锁政策的否定。

[消息等级 Level C · 一般]
