### ISSUE TITLE
netflix换ip,区域选择的的问题

### ISSUE THREAD

**Issue by visense** [fscarmen/warp#50]
我是从luoxue-bot/warp_auto_change_ip一直跟过来的，更换netflix ip时候区域是自动选择的，能否手动指定区域，如果获取不到解封的ip再自动获取相近区域的ip?

**Comment by fscarmen** [comment]
关于你提到的手动指定区域的问题，经过这段时间和群友的了解，warp是按原生vps ip的区域以就近原则分配的，即日本的vps，即使我们指令区域是美国，也只会“永远”无法获取到想要的。

感谢你的支持，我在那项目也留言了。可惜luoxue 一直没有出现，讨论不了该问题。同时我看他的脚本写得有点啰嗦，改好了PR了，也没有见他回复。

**Comment by visense** [comment]
> 
感谢大佬回复，我只是想日本的vps,获取到日本的ip,韩国的vps获取到韩国的ip。就近原则分配的话，实际使用下来韩国vps获取到日本ip,台湾vps也获取到日本ip，期待这个问题解决！！！

**Comment by fscarmen** [comment]
> 感谢大佬回复，我只是想日本的vps,获取到日本的ip,韩国的vps获取到韩国的ip。就近原则分配的话，实际使用下来韩国vps获取到日本ip,台湾vps也获取到日本ip，期待这个问题解决！！！

有这个情况？我想了解两个问题
1. 你是想获取vps当地资源还是异地资源？如果是前者，我可以直接判断你的vps现在ip归属，然后把这个带到去刷IP那里，这样就不需要你输入了。
2. 如果当地没有Warp的点，他会分去附近地方的，比如印度尼西亚会派新加坡的ip，所以填了印度尼西亚的话会永远死循环了。这个可能我要在第1点的基础上做个处理如下：
3. 让用户确认是否选用vps 原生所在地，如果是按 y 。如果 n 则填希望的区域。 最后如果N次后仍然刷不出来，就以就近个停止。

**Comment by visense** [comment]
> 



> > 感谢大佬回复，我只是想日本的vps,获取到日本的ip,韩国的vps获取到韩国的ip。就近原则分配的话，实际使用下来韩国vps获取到日本ip,台湾vps也获取到日本ip，期待这个问题解决！！！
> 
> 有这个情况？
> 
> 1. 你是想获取vps当地资源还是异地资源？如果是前者，我可以直接判断你的vps现在ip归属，然后把这个带到去刷IP那里，这样就不需要你输入了。
> 2. 如果当地没有Warp的点，他会分去附近地方的，比如印度尼西亚会派新加坡的ip，所以填了印度尼西亚的话会永远死循环了。这个可能我要在第1点的基础上做个处理如下：
> 3. 让用户确认是否选用vps 原生所在地，如果是按 y 。如果 n 则填希望的区域。 最后如果N次后仍然刷不出来，就以就近个停止。

实际使用中，可否省去用户确认？首先自动选择ip归属地获取NF的ip，如果获取不到，再去附近地方获取?

**Comment by fscarmen** [comment]
> > 
> 
> > > 感谢大佬回复，我只是想日本的vps,获取到日本的ip,韩国的vps获取到韩国的ip。就近原则分配的话，实际使用下来韩国vps获取到日本ip,台湾vps也获取到日本ip，期待这个问题解决！！！
> > 
> > 
> > 有这个情况？
> > 
> > 1. 你是想获取vps当地资源还是异地资源？如果是前者，我可以直接判断你的vps现在ip归属，然后把这个带到去刷IP那里，这样就不需要你输入了。
> > 2. 如果当地没有Warp的点，他会分去附近地方的，比如印度尼西亚会派新加坡的ip，所以填了印度尼西亚的话会永远死循环了。这个可能我要在第1点的基础上做个处理如下：
> > 3. 让用户确认是否选用vps 原生所在地，如果是按 y 。如果 n 则填希望的区域。 最后如果N次后仍然刷不出来，就以就近个停止。
> 
> 实际使用中，可否省去用户确认？首先自动选择ip归属地获取NF的ip，如果获取不到，再去附近地方获取?

我更希望不需要用户确认，获取n次(这个值可以随时设置）ip归属地的，超过就不管了，获取他分配的支持奈飞的。

元旦快乐！

**Comment by visense** [comment]
> > 实际使用中，可否省去用户确认？首先自动选择ip归属地获取NF的ip，如果获取不到，再去附近地方获取?
> 
> 我更希望不需要用户确认，获取n次(这个值可以随时设置）ip归属地的，超过就不管了，获取他分配的支持奈飞的。
> 
> 元旦快乐！
元旦快乐！大佬，那这要怎么实现呢？

**Comment by fscarmen** [comment]
> > > 实际使用中，可否省去用户确认？首先自动选择ip归属地获取NF的ip，如果获取不到，再去附近地方获取?
> > 
> > 
> > 我更希望不需要用户确认，获取n次(这个值可以随时设置）ip归属地的，超过就不管了，获取他分配的支持奈飞的。
> > 元旦快乐！
> > 元旦快乐！大佬，那这要怎么实现呢？

我再收集一下其他用户的意见，你看现在 ```warp i```是否满足你使用，如果不满足，可以用落雪，他那个能选的

**Comment by visense** [comment]
> > > > 实际使用中，可否省去用户确认？首先自动选择ip归属地获取NF的ip，如果获取不到，再去附近地方获取?
> > > 
> > > 
> > > 我更希望不需要用户确认，获取n次(这个值可以随时设置）ip归属地的，超过就不管了，获取他分配的支持奈飞的。
> > > 元旦快乐！
> > > 元旦快乐！大佬，那这要怎么实现呢？
> 
> 我再收集一下其他用户的意见，你看现在 `warp i`是否满足你使用，如果不满足，可以用落雪，他那个能选的
落雪的我在hinet vps上测试过，始终无法获取TW的NF ip，使用warp i，会获取到日本的NF ip，我也不知道哪出了问题

**Comment by visense** [comment]
> > > > 实际使用中，可否省去用户确认？首先自动选择ip归属地获取NF的ip，如果获取不到，再去附近地方获取?
> > > 
> > > 
> > > 我更希望不需要用户确认，获取n次(这个值可以随时设置）ip归属地的，超过就不管了，获取他分配的支持奈飞的。
> > > 元旦快乐！
> > > 元旦快乐！大佬，那这要怎么实现呢？
> 
> 我再收集一下其他用户的意见，你看现在 `warp i`是否满足你使用，如果不满足，可以用落雪，他那个能选的
落雪的我在hinet vps上测试过，始终无法获取TW的NF ip，使用warp i，会获取到日本的NF ip，我也不知道哪出了问题

**Comment by fscarmen** [comment]
> 落雪的我在hinet vps上测试过，始终无法获取TW的NF ip，使用warp i，会获取到日本的NF ip，我也不知道哪出了问


> 2. 如果当地没有Warp的点，他会分去附近地方的，比如印度尼西亚会派新加坡的ip，所以填了印度尼西亚的话会永远死循环了。这个可能我要在第1点的基础上做个处理如下：


这里提过了

**Comment by visense** [comment]
> > 落雪的我在hinet vps上测试过，始终无法获取TW的NF ip，使用warp i，会获取到日本的NF ip，我也不知道哪出了问
> 
> > 2. 如果当地没有Warp的点，他会分去附近地方的，比如印度尼西亚会派新加坡的ip，所以填了印度尼西亚的话会永远死循环了。这个可能我要在第1点的基础上做个处理如下：
> 
> 这里提过了

感谢！！！

**Comment by fscarmen** [comment]
> 实际使用下来韩国vps获取到日本ip,台湾vps也获取到日本ip

针对这点我还是想继续了解一下，像这个韩国vps，获取的ip是以下哪个情况呢？
1.一直都是日本 warp ip    
2. 一时日本一时韩国  warp ip   
3. 其他

台湾VPS同理
4.一直都是日本 warp ip    
5. 一时日本一时台湾  warp ip   
6. 其他

**Comment by visense** [comment]
> > 实际使用下来韩国vps获取到日本ip,台湾vps也获取到日本ip
> 
> 针对这点我还是想继续了解一下，像这个韩国vps，获取的ip是以下哪个情况呢？ 1.一直都是日本 warp ip 2. 一时日本一时韩国 warp ip 3. 其他
> 
> 台湾VPS同理 4.一直都是日本 warp ip 5. 一时日本一时台湾 warp ip 6. 其他

1、韩国是azure家的vps，地区是韩国，获取的ip一直都是日本 warp ip没有韩国；【忘记尝试记录了】
2、台湾vps是hinet，本来是原生ip解锁的，但是被封了，用warp i获取的ip一直都是日本没有台湾；【在warp i中没有获取台湾ip尝试记录】
3、比如上面的台湾，由于没有首先尝试获取本地区warp ip的，而是直接获取了日本的ip，所有想warp i首先自动获取本地区的ip,而后获取其他地区的ip

**Comment by fscarmen** [comment]
我改一个版本你试好吗？

**Comment by fscarmen** [comment]
2022.1.11 升级为2.26片，让用户在刷奈飞IP的时候输入地区，升级后再运行 #57 
```
warp v  #升级
warp i  #刷IP
```

**Comment by visense** [comment]
> 2022.1.11 升级为2.26版本，让用户在刷 Netflix IP的时候输入地区，升级后再运行
> 
> ```
> warp v  #升级
> warp i  #刷IP
> ```

感谢大佬，辛苦了！！！

**Comment by fscarmen** [comment]
> > 2022.1.11 升级为2.26版本，让用户在刷 Netflix IP的时候输入地区，升级后再运行
> > ```
> > warp v  #升级
> > warp i  #刷IP
> > ```
> 
> 感谢大佬，辛苦了！！！

有时间帮忙试试效果，因为我没有 Netflix ，所以试不了。

**Comment by visense** [comment]
> > > 2022.1.11 升级为2.26版本，让用户在刷 Netflix IP的时候输入地区，升级后再运行
> > > ```
> > > warp v  #升级
> > > warp i  #刷IP
> > > ```
> > 
> > 
> > 感谢大佬，辛苦了！！！
> 
> 有时间帮忙试试效果，因为我没有 Netflix ，所以试不了。

好的，我测试，给你反馈
