### ISSUE TITLE
[help wanted 求助]: 能否切换获取到指定地区的ip

### ISSUE THREAD

**Issue by yonghu996** [fscarmen/warp#500]
### Script / 脚本

menu.sh

### OS / 操作系统

Debian - Linux

### Actual Situation / 实际情况

比如我美国的VPS想获取JP的warp的ip

### Log / 日志信息

无

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/498
https://github.com/fscarmen/warp/issues/469
https://github.com/fscarmen/warp/issues/479
