### ISSUE TITLE
docker dns lookup failed with timeout-【结论：container指定了一个dns ，docker run -dit --dns="8.8.8.8" ....... 就可以了】

### ISSUE THREAD

**Issue by MiniSoda** [fscarmen/warp#52]
启动warp后trojan的docker不能解析dns

```
root@remote:~# docker exec -it trojan nslookup www.google.com
;; connection timed out; no servers could be reached
```

Docker container 用host network配置
warp关闭后正常

**Comment by MiniSoda** [comment]
重新生成container指定了一个dns好了，
`docker run -dt --name trojan --network=host  --dns="8.8.8.8" trojangfw/trojan`

**Comment by fscarmen** [comment]
兄弟高手啊，我对docker不熟，只会玩玩青龙和探针这些。
最近我有个相法和你探讨一下，由于形形式式的系统和版本，warp脚本包括我和其他作者的都做不到全面的兼容性，只能遇到一个供应商的问题处理一下。
我的想法是像你安装torjan docker一样，把warp打包在docker里，以极轻量级的alpine为底包（脚本现已适配了），做个wgcf的为vps服务，这样我就不用考虑复杂的系统问题了。当然代价是占用较高的内存和空间资源，可能影响性能。

**Comment by fscarmen** [comment]
还是就是使用了 warp ，青龙 docker 就访问不了，我知道问题在那里，但一直没有好的处理方法。

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/148038525-8436d349-9db5-44d7-8b23-2ea328580f76.png)

**Comment by MiniSoda** [comment]
厉害了老哥，这是搞定了吗

**Comment by fscarmen** [comment]
嗯，完成大半了。

**Comment by fscarmen** [comment]
搞定了  WARP+ 和 PLUS 已经加了进去了
```
wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/docker.sh && bash docker.sh [option] [lisence] ## 安装 docker、拉镜像和安装容器

docker exec -it wgcf sh #部分系统在容器外 docker exec -it wgcf wg-quick up wgcf 不行，一定要分开执行的。进入容器

wg-quick up wgcf; exit #运行 WGCF 并退出容器。
```
