### ISSUE TITLE
hax ipv6 only vps 延时大-【结论：对原生 IPv6 only 的vps，把 CF 的IPv6 DNS放在最前面，延时大大降低】 

### ISSUE THREAD

**Issue by zhenkuaileya** [fscarmen/warp#53]
大佬，你能申请一台hax测试一下不，用你的warp建的节点延迟贼高，换了甬哥的就很正常，Linuxone也有问题，临时关了warp延时1000，开warp延时5000，然后我就折腾了一下午Linuxone号没了。修好了我还会爱你的。

**Comment by fscarmen** [comment]
感谢你的意见，我对比了一下，发现是dns先后顺序的区别，我调了一版给你，你方便测测并反馈个结果呢，我和甬哥的都有卸载选项的
```
wget -O ./menu.sh https://raw.githubusercontent.com/fscarmen/tools/main/a.sh && bash menu.sh
```

**Comment by zhenkuaileya** [comment]
> 谢谢你的意见，我对比了一下，发现是dns先后顺序的区别，我调一个版本给你，你方便测测并反馈个结果呢，我和甬哥的卸选项的
> 
> ```
> wget -O ./menu.sh https://raw.githubusercontent.com/fscarmen/tools/main/a.sh && bash menu.sh
> ```

爱了爱了，真快啊。这个版本没问题了

**Comment by zhenkuaileya** [comment]
fscarmen YYDS

**Comment by fscarmen** [comment]
> fscarmen YYDS

感谢你的支持和宝贵意见。

现在节点的延时大大减少了？曾经脚本的dns顺序是与改给你的一样，是遇到有点问题后面换了次序的，但现在想不起来因为什么了。

Linux1 暂时也只有我的脚本支持，同时他只支持添加 WARP IPv4 单栈的，你先申请一个，到时我再调一下dns的次序你试试

**Comment by zhenkuaileya** [comment]
> > fscarmen YYDS
> 
> 感谢你的支持和宝贵意见。现在已经更新到正式那里了，所以后续你仍然用原有的安装方式可以了。
> 
> 现在节点的延时大大减少了？曾经脚本的dns顺序是与改给你的一样，是遇到有点问题后面换了次序的，但现在想不起来因为什么了。
> 
> Linux1 暂时也只有我的脚本支持，同时他只支持添加 WARP IPv4 单栈的，你先申请一个，到时我再调一下dns的次序你试试

好的，收到。感谢大佬
