### ISSUE TITLE
debian11获取ip失败

### ISSUE THREAD

**Issue by yuanweize** [fscarmen/warp#54]
![image](https://user-images.githubusercontent.com/30067203/148077490-5e95eed1-d460-4c9a-a0bd-105edfa4af88.jpeg)![image](https://user-images.githubusercontent.com/30067203/148077502-215841bf-45e9-4a56-ab3f-395295014dc8.png)

**Comment by fscarmen** [comment]
手动运行，把回显放上来 ```wg-quick up wgcf && curl -s4m12 ip.gs```

**Comment by yuanweize** [comment]
![image](https://user-images.githubusercontent.com/30067203/148124430-748fd8de-f2b2-4d75-92f9-47ddc322b7c5.jpeg)谢谢，不过这个脚本还是获取不到ip。我另外一台相同的环境debian10没问题

**Comment by fscarmen** [comment]
D11 获取不到，运行```wg-quick up wgcf```看提示什么？

**Comment by fscarmen** [comment]
我用GCP开了个 Debian 11 ，升级为 BBRplus 后再运行脚本，十分顺利的

![image](https://user-images.githubusercontent.com/62703343/148149390-cbed93de-5ceb-4ea1-8079-15057b976c8c.png)

**Comment by yuanweize** [comment]
![image](https://user-images.githubusercontent.com/30067203/148154779-62389651-27dc-40a5-8e15-f60a6a27563b.png)
debian11内核从升级4.14.129到新版bbrplus(5.10.89-bbrplus),成功获取到ipv6.

**Comment by fscarmen** [comment]
> debian11内核从升级4.14.129到新版bbrplus(5.10.89-bbrplus),成功获取到ipv6.

nice ! 问题解决了！

**Comment by yuanweize** [comment]
是的,我是使用的原脚本.之前内核4.14.129时,尝试了很多的脚本都失败.应该是内核版本和debian11的问题

**Comment by fscarmen** [comment]
再补充问一下，你说 Debian 10 成功的，又是什么内核什么版本的？

**Comment by yuanweize** [comment]
> 再补充问一下，你说 Debian 10 成功的，又是什么内核什么版本的？

![image](https://user-images.githubusercontent.com/30067203/148155981-ed6d5d0e-4794-4819-a5ea-ea19e7fcc59b.png)

**Comment by yuanweize** [comment]
> D11 获取不到，运行`wg-quick up wgcf`看提示什么？

[#] ip link add wgcf type wireguard
[#] wg setconf wgcf /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev wgcf
[#] ip -6 address add fd01:5ca1:ab1e:8ef7:8ed9:4f45:d65f:e27/128 dev wgcf
[#] ip link set mtu 1420 up dev wgcf
[#] resolvconf -a wgcf -m 0 -x
[#] wg set wgcf fwmark 51820
[#] ip -6 route add ::/0 dev wgcf table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
/dev/fd/63:5:1-130: Error: Could not process rule: No such file or directory

[#] resolvconf -d wgcf -f
[#] ip -6 rule delete table 51820
[#] ip -6 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wgcf

**Comment by fscarmen** [comment]
那结论是：
Debian 10 + bbrplus 4.14.129 可以
Debian 11 + bbrplus 4.14.129 不行
Debian 11 + bbrplus 5.10.89 可以
是这样吗？

**Comment by yuanweize** [comment]
> 那结论是： Debian 10 + bbrplus 4.14.129 可以 Debian 11 + bbrplus 4.14.129 不行 Debian 11 + bbrplus 5.10.89 可以 是这样吗？

是的

**Comment by fscarmen** [comment]
感谢支持，如使用中有任何问题或者功能方向的好想法，欢迎随时来留言！
