### ISSUE TITLE
docker报错-【结论：使用 WGCF 版本后问题解决 】

### ISSUE THREAD

**Issue by jerrychen417** [fscarmen/warp#56]
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
 创建快捷 warp 指令成功 
Error: No such container: wgcf

https://hax.co.id  VPS是这个，系统是
系统信息：
	当前操作系统：Debian GNU/Linux 10 (buster)
	内核：3.10.0-1160.41.1.vz7.183.5
	处理器架构：amd64
	虚拟化：openvz 
	IPv4：     
	IPv6：2a01:4f8:13a:2690:face:fbb:8f:1  Germany  Hetzner Online GmbH 
	WARP 网络接口未开启

**Comment by fscarmen** [comment]
先处理 DNS64 的问题
```
echo -e "nameserver 2a00:1098:2b::1\nnameserver 2a01:4f9:c010:3f02::1\nnameserver 2a01:4f8:c2c:123f::1\nnameserver 2a00:1098:2c::1" > /etc/resolv.conf
```

**Comment by jerrychen417** [comment]
感谢回复，这几个DNS是涌哥写在GitHub上面的那几个吧，也有试过，不行，下面这个直接就成功了
https://blog.misaka.rest/202110/89.html

**Comment by fscarmen** [comment]
你是指dns成功了还是在母鸡上安装warp成功了？

**Comment by jerrychen417** [comment]
安装warp成功

**Comment by fscarmen** [comment]
我就是奇怪，我还以为你想试新的东西呢，如果单是 warp，你用本项目成熟的脚本，安装warp像打炮一样爽的
