### ISSUE TITLE
自动换IP建议增加指定地区，例如SG -【结论：2022.1.11 升级为2.26版本，让用户在刷 Netflix IP的时候输入地区，升级后再运行】

### ISSUE THREAD

**Issue by socosfly** [fscarmen/warp#57]
现在会出现新加坡换出来美国，日本

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/50
这里有讨论，没有结果所以没有做，我想问你的新加坡vps，换ip会换出来美国、日本和新加坡不定，会变化的吗？如果是这样即可以加，但我了解的情况是换来换去都换不到其他区域的。

**Comment by socosfly** [comment]
luxe-bot项目也会换出其他地区IP，指定SG会放弃掉，继续刷，直到出SG

**Comment by fscarmen** [comment]
> luxe-bot项目也会换出其他地区IP，指定SG会放弃掉，继续刷，直到出SG

行的，这两天处理该问题吧。计划在 luxe 基础上作个改进。你看看有没有补充
1.自动获取现 IP 下奈飞的区域（不一定是解锁的）。比如是 SG。
2.问用户是否使用该区域，如是就按 y。如不是则输入希望区域的英文简码，比如输入 y 或者 JP（我会根据用户的输入信息情况作分别处理）

**Comment by fscarmen** [comment]
2022.1.11 升级为2.26片，让用户在刷奈飞IP的时候输入地区，升级后再运行
```
warp v  #升级
warp i   #刷IP
```

**Comment by socosfly** [comment]
感谢，完美！
<img width="1153" alt="截屏2022-01-12 21 46 06" src="https://user-images.githubusercontent.com/63989353/149166653-8b876cfe-8d74-446a-9121-e8994c8a7c49.png">

**Comment by fscarmen** [comment]
开个 screen 会话在后台刷，你vps可以退出ssh或者干别的事了
```
screen -US a   #新建一个叫a的会话

warp i #在a里运行刷 Netflix IP
```

之后按 Ctrl+a，再按 d 退出
