### ISSUE TITLE
Virmach西雅图的机（Debian10）无法获取warp ip

### ISSUE THREAD

**Issue by iSonce** [fscarmen/warp#58]
![1](https://user-images.githubusercontent.com/57745505/148778095-987c71c6-18fc-4026-9e3d-68e1ad0b3ecc.jpg)
![2](https://user-images.githubusercontent.com/57745505/148778147-4ad02c20-97d8-4e73-91b9-5b13e9fedba9.jpg)

**Comment by iSonce** [comment]
> `wg-quick up wgcf` 发下回显

![image](https://user-images.githubusercontent.com/57745505/148778968-9b0d6b4c-bce3-4ca0-bf43-0e4865df8838.png)

**Comment by fscarmen** [comment]
```warp b``` 升级一下内核，有可能是 wg-quick 与内核版本不匹配所致

**Comment by iSonce** [comment]
![image](https://user-images.githubusercontent.com/57745505/148779778-d5a1c308-0dcb-4a3a-9a36-797610db3bf4.png)
是bbrplus不兼容吗

**Comment by fscarmen** [comment]
```sed -i "/0\.\0\/0/d" /etc/wireguard/wgcf.conf; systemctl restart wg-quick@wgcf; warp n```
看看结果

**Comment by iSonce** [comment]
> `sed -i "/0\.\0\/0/d" /etc/wireguard/wgcf.conf; systemctl restart wg-quick@wgcf; warp n` 看看结果

把bbrplus重新安装了一下，然后就获取成功了
![image](https://user-images.githubusercontent.com/57745505/148781766-d10e9e88-6f62-4b10-ae65-fedebcccb525.png)
感谢！

**Comment by fscarmen** [comment]
不关 bbrplus 的事，问题点应该出在你的 ip 直接是公网的。
这种网络环境下只能单栈而不能双栈WARP。你的 v4 还不是WARP的，这个问题与 IBM Linux1一样，同时我还没有找到解决方案

**Comment by iSonce** [comment]
> 不关 bbrplus 的事，问题点应该出在你的 ip 直接是公网的。 这种网络环境下只能单栈而不能双栈WARP。你的 v4 还不是WARP的，这个问题与 IBM Linux1一样，同时我还没有找到解决方案

第一次获取成功后确实是单栈的，只有v6的warp，然后我关闭后又申请了一下申请到双栈了的。
![image](https://user-images.githubusercontent.com/57745505/148784559-c493dd0e-ae19-424b-838b-8ac633600c7a.png)

**Comment by fscarmen** [comment]
那就真是 bbrplus 升级的问题了 ，你的情况与 #54 一模一样
