### ISSUE TITLE
更新luoxue的可选地区版本后，刷不到可用IP

### ISSUE THREAD

**Issue by nanwua** [fscarmen/warp#59]
使用地区码刷IP时刷不到指定地区IP

**Comment by fscarmen** [comment]
这个功能是为一些地区跳来跳去的使用的。前提是你那个地区的warp要能获取到。
举例你几乎不可能在一个德国的vps上获取香港的指令IP？
你是哪个地区的？获取到的IP又是哪个区呢？

**Comment by nanwua** [comment]
我是香港的想要获取台湾IP

**Comment by nanwua** [comment]
> 这个功能是为一些地区跳来跳去的使用的。前提是你那个地区的经要能获取到。 举例你几乎不可能在一个德国的VPS上获取香港的指令IP？ 你是哪个地区的？获取到的IP又是哪个区呢？

我大概明白了，感谢大佬

**Comment by fscarmen** [comment]
> 我是香港的想要获取台湾IP

如果香港vps 获取的 ip 有时香港，有时日本，有时台湾。这种情况下是可以的。
但如果 warp 分配的 IP 只有香港和日本。这样情况下是永远不可能获取台湾的。
warp 是就近分配原则的。

**Comment by fscarmen** [comment]
#57 这种情况下是可以的
