### ISSUE TITLE
请问怎么只开启ipv6单栈？

### ISSUE THREAD

**Issue by 759071793** [fscarmen/warp#61]
我的vps有ipv4和ipv6，但是我只想开一个ipv6单栈，不知道怎么操作。。

**Comment by misakano7545** [comment]
那就先这样，再那样，最后这样就行

**Comment by fscarmen** [comment]
先安装双栈方案

如只开 warp IPv6
```
sed -i "s/^.*\:\:\/0/#&/g" /etc/wireguard/wgcf.conf; systemctl restart  wg-quick@wgcf; warp n
```

如只开 warp IPv4
```
sed -i "s/^.*0\.\0\/0/#&/g" /etc/wireguard/wgcf.conf; systemctl restart  wg-quick@wgcf; warp n
```

**Comment by 759071793** [comment]
> 归纳楼上的方法，先安装双栈方案
> 
> 如只开 warp IPv6
> 
> ```
> sed -i "s/^.*\:\:\/0/#&/g" /etc/wireguard/wgcf.conf; systemctl restart  wg-quick@wgcf; warp n
> ```
> 
> 如只开 warp IPv4
> 
> ```
> sed -i "s/^.*0\.\0\/0/#&/g" /etc/wireguard/wgcf.conf; systemctl restart  wg-quick@wgcf; warp n
> ```

感谢大佬

**Comment by fscarmen** [comment]
> 感谢大佬

上面的我调反了，已经修正命令
