### ISSUE TITLE
every installation still says wireguard tools not installled

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#62]
Information
```
        Operating System：Ubuntu 20.04.3 LTS
        Kernel：5.4.0-29-generic
        Architecture：amd64
        Virtualization：kvm
```
i used `expect` to auto install. everytime i used your running your script on fresh installation vps keep error like this one
```
 WireGuard tools are not installed or the configuration file wgcf.conf cannot be found, please reinstall.
```
and i already installl wireguard-tools since i run wireguard server script first then install warp. and wireguard server running perfectly just your script keep those errors

![image](https://user-images.githubusercontent.com/9080737/149640149-747b6f4c-3f66-48ee-91fa-919522fc3189.png)

**Comment by malikshi** [comment]
fixed by updated the command order in expect script

**Comment by fscarmen** [comment]
I am very confused that the script will upgrade the library's by ```apt -y update``` before installing wireguard-tools.

What is your solution steps.

![image](https://user-images.githubusercontent.com/62703343/149656916-e0e4c187-d19a-4447-9b83-1512cd9f27aa.png)

**Comment by malikshi** [comment]
> I am very confused that the script will upgrade the library's by `apt -y update` before installing wireguard-tools.
> 
> What is your solution steps.
> 
> ![image](https://user-images.githubusercontent.com/62703343/149656916-e0e4c187-d19a-4447-9b83-1512cd9f27aa.png)

Your command step bit different from old one which is my auto install can't work with those new menu

**Comment by fscarmen** [comment]
> which is my auto install can't work

What does your auto-install mean.
Is it a script？

**Comment by malikshi** [comment]
> > which is my auto install can't work
> 
> What does your auto-install mean. Is it a script？

Yes
