### ISSUE TITLE
Did you force dual stack native ipv4 & ipv6 to use dual stack warp too?-【Conclusion: 2022.1.21  version 2.30, according to user needs, 1. Increase the WARP single-stack network interface. 2. Let the user enter the region when brushing the Netflix IP】

### ISSUE THREAD

**Issue by malikshi** [fscarmen/warp#63]
can i use ipv6 warp and ipv4 from original?

**Comment by fscarmen** [comment]
native ipv4 & ipv6  -> warp dual stack

**Comment by malikshi** [comment]
okay, i will using https://github.com/P3TERX/warp.sh since yours force vps with native ipv4&ipv6 with warp dual stack

**Comment by fscarmen** [comment]
Consider adding various warp options in the future.

**Comment by fscarmen** [comment]
2022.1.21 Version 2.30:

1.All support WARP single-stack and dual-stack solutions. Switch to each other easily and quickly. Such as ```warp s 4```,```warp s 6```,```warp s d```;

2.Brush Netflix Unlock IP with the expect area. Such as ```warp i hk```.

**Comment by malikshi** [comment]
> 2022.1.21 Version 2.30:
> 
> 1.All support WARP single-stack and dual-stack solutions. Switch to each other easily and quickly. Such as `warp s 4`,`warp s 6`,`warp s d`;
> 
> 2.Brush Netflix Unlock IP with the expect area. Such as `warp i hk`.

i saw your commit sir, thank you very much for the updates, i will try new version later.

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/150553655-3414ca79-23dd-4797-be3a-f23356150338.png)

**Comment by fscarmen** [comment]
BTW: 3.Fixed stuck when brushing Netflix IP. I think the problem you are having is that bug

**Comment by malikshi** [comment]
> BTW: 3.Fixed stuck when brushing Netflix IP. I think the problem you are having is that bug

Yes it's. I have vps openvz with native dual stack to test but I don't know is it work with your script

**Comment by fscarmen** [comment]
You could leave a message when there is a problem.

**Comment by fscarmen** [comment]
Has your needs been resolved?

**Comment by malikshi** [comment]
> Has your needs been resolved?

yes, brush Netflix IP `warp i US` is only support for ipv6? does https://github.com/fscarmen/warp_unlock supported netflix ipv6 ?

**Comment by fscarmen** [comment]
```warp  i ``` not only support ipv6, but also ipv4 and socks5.
project "warp_unlock" provides 3 ways to unlock. All of ipv4 ipv6 and socks5  are support.
And according to my experience. It 's very hard to unlock by ipv6. So you 'd better choose ipv4 and socks5.

**Comment by malikshi** [comment]
@fscarmen said
>And according to my experience. It 's very hard to unlock by ipv6. So you 'd better choose ipv4 and socks5.

yes i will try socks5.

**Comment by malikshi** [comment]
sir @fscarmen i there the problem when switch from state `warp s 4` or `warp s d` to state `warp s 6`
```sh
PostUp = ip -4 rule add from ipv4 lookup main
PostDown = ip -4 rule delete from ipv4 lookup main
```
those need to delete right when changing to `warp s 6`

**Comment by fscarmen** [comment]
I used IPv4 only, IPv6 only and dualstack to test again. They weren't any problem. 

![image](https://user-images.githubusercontent.com/62703343/153692524-6b5c1d09-57e4-4349-9a52-884b7314957b.png)
![image](https://user-images.githubusercontent.com/62703343/153692645-4a0cc294-27fa-47e4-9c50-138fdb16c2c5.png)
![image](https://user-images.githubusercontent.com/62703343/153693044-1aacbc40-a2b5-48e3-b263-f429ecf56881.png)
