### ISSUE TITLE
帮我看看, 哪里出了问题? 403 Forbidden > websocket: bad handshake

### ISSUE THREAD

**Issue by joshatt** [fscarmen/warp#65]
帮忙看看哪里的问题: 
hax装了xui, 开启bbr, 然后warp, 得到ipv4地址, 可以ping通. 
然后cf中把我的域名指向这个v4 ip(然后ping了一下域名,正常), 不开云朵. SSL/TLS=FULL, 添加证书(client certificate)
然后xui中使用vless443, ws, tls, 我这个域名, 证书. 
最后实测, 403 Forbidden > websocket: bad handshake

**Comment by fscarmen** [comment]
> 然后cf中把我的域名指向这个v4 ip(然后ping了一下域名,正常), 不开云朵. SSL/TLS=FULL, 添加证书(client certificate)

这个warp ipv4是共享的，只能用于vps对外访问，不能用于你不能用他访问vps。

cf里域名插入AAAA指向hax给的原生ipv6，vless用ws，用优选出来的ip作cdn

**Comment by joshatt** [comment]
谢谢解答.

> cf里域名插入AAAA指向hax给的原生ipv6，vless用ws，
前几天, 我在学用warp之前, 就是这样套用cf cdn的, 能通

> 用优选出来的ip作cdn
作cdn? 意思是替换v2ray客户端的"地址(address)"吗? 
我在刚才说的套用cf cdn的基础上, 也尝试过用其他的cf扫描优选工具得到了几个优选ip,  替换到v2ray客户端的address,  都不通,  当时我猜是ipv6的机器有特别之处

**Comment by fscarmen** [comment]
> 也尝试过用其他的cf扫描优选工具得到了几个优选ip, 替换到v2ray客户端的address

是这样的啊，扫描出来符合你网络的优选IP没有遇到过不能使用的，你要意思要用带ws的方案，不能直连

**Comment by joshatt** [comment]
> > 也尝试过用其他的cf扫描优选工具得到了几个优选ip, 替换到v2ray客户端的address
> 
> 是这样的啊，扫描出来符合你网络的优选IP没有遇到过不能使用的，你要意思要用带ws的方案，不能直连

又折腾了两天, 还是没搞明白 ---- 既然不是填写在v2ray客户端, 通过这个ip访问vps, 那么用在哪里呢? 是在cf中让域名指向warp的ipv4吗, 但这样还不如直接把域名指向vps的原本ipv6?

**Comment by fscarmen** [comment]
> 又折腾了两天, 还是没搞明白 ---- 既然不是填写在v2ray客户端, 通过这个ip访问vps, 那么用在哪里呢? 是在cf中让域名指向warp的ipv4吗, 但这样还不如直接把域名指向vps的原本ipv6?

经过几天的研究，弄清楚作用了？
