### ISSUE TITLE
运行一段时间后，网络会卡死

### ISSUE THREAD

**Issue by dogxgit** [fscarmen/warp#66]
在screen里使用 warp i 刷ip，一段时间后（一两天）网络会卡死，用 warp n 指令才能恢复。
Ubuntu 20.04和Debian 11都试过了，vps是gcp的，配置2cpu1gram

**Comment by fscarmen** [comment]
我在德鸡、GCP和甲骨文试试先

**Comment by fscarmen** [comment]
> 在screen里使用 warp i 刷ip，一段时间后（一两天）网络会卡死，用 warp n 指令才能恢复。 Ubuntu 20.04和Debian 11都试过了，vps是gcp的，配置2cpu1gram

你仍然在 screen 下运行 ```bash -x warp i```，到时看卡死在哪些

**Comment by dogxgit** [comment]
刚刚回去看又卡住了
![屏幕截图 2022-01-18 002557](https://user-images.githubusercontent.com/97828604/149806477-f7211a5b-6338-497c-8141-b49b61488c8d.png)
就卡在这里然后断网了

**Comment by dogxgit** [comment]
> > 在screen里使用 warp i 刷ip，一段时间后（一两天）网络会卡死，用 warp n 指令才能恢复。 Ubuntu 20.04和Debian 11都试过了，vps是gcp的，配置2cpu1gram
> 
> 你仍然在 screen 下运行 `bash -x warp i`，到时看卡死在哪些

好的

**Comment by fscarmen** [comment]
暂时都正常，EUserv 暂时刷不出来的，也在更新，没有挂啊
![image](https://user-images.githubusercontent.com/62703343/149865663-e3f3a563-43c1-447d-933c-1d72049845b1.png)

**Comment by fscarmen** [comment]
暂时正常，运行了1天又10小时了
![image](https://user-images.githubusercontent.com/62703343/150050439-c491a2c5-fb02-41d2-b8d3-f0e0f0925734.png)
![image](https://user-images.githubusercontent.com/62703343/150050464-f01c4600-77a0-42af-a86a-a73ac531cc94.png)
![image](https://user-images.githubusercontent.com/62703343/150050495-72a40938-758c-45e5-ae04-e6c0b31a9380.png)

**Comment by dogxgit** [comment]
我这边这三天也是正常在跑的状态，来这边反馈后就没出现过卡死的状态了（捂脸，暂时先关了，如果后续还出现该情况，再来反馈并附上具体卡住位置的截图。辛苦大佬了，谢谢你写出这么好用的脚本~

**Comment by fscarmen** [comment]
> 辛苦大佬了，谢谢你写出这么好用的脚本~

应该是我感谢大家的使用、积极反馈和优化建议。

**Comment by fscarmen** [comment]
> 我这边这三天也是正常在跑的状态，来这边反馈后就没出现过卡死的状态了（捂脸，暂时先关了，如果后续还出现该情况，再来反馈并附上具体卡住位置的截图。辛苦大佬了，谢谢你写出这么好用的脚本~

找到个问题点，如果获取 IP 信息的 ip.gs 返回 IP 不及时，就会导致我脚本卡死的情况，已经作了相应的处理，估计是OK了
