### ISSUE TITLE
该脚本搭建的warp有log吗-【结论：可以通过以下方式运行脚本以输出名为 warp.log 的日志，bash menu.sh 2>&1 | tee warp.log 】

### ISSUE THREAD

**Issue by longmoon77** [fscarmen/warp#67]
小问题想问一下，请问这个脚本创建的warp、wireguard、linux client有日志可以看吗，或者是没有。

并不是想要看日志，只是如果有的话，他们存放在哪里呢。

**Comment by fscarmen** [comment]
这个没有哦。
倒是选择的中或英语言，如果用warp+或者Teams账户，会有记录放在 /etc/wireguard/ 下

**Comment by fscarmen** [comment]
你可以自己弄个日志文件，假设文件名为 warp.log
```bash menu.sh 2>&1 | tee warp.log```

**Comment by longmoon77** [comment]
我其实是因为有强迫症，因为nginx和xray-core都有日志，我看到里面有error日志或者warning日志就浑身不舒服。我怕warp也有这个日志，特地来问一下，不要一堆错误日志，当然如果能手动开启日志的话，那也非常不错呢。
