### ISSUE TITLE
脚本很方便~顺便提点建议-【结论：2022.1.21 升级为2.30版本，应用户需求，1.增加 WARP 单栈网络接口。2.让用户在刷 Netflix IP的时候输入地区】

### ISSUE THREAD

**Issue by kisekimi** [fscarmen/warp#68]
换IP功能很方便，
1.希望下续增加单 warp ipv4 的方式
2.希望增加后台自动检测并更换的脚本

**Comment by fscarmen** [comment]
下个版本更新这块，涉及的内容比较多，需要时间测
可以先按 #61 的方法手动处理

**Comment by ben-august** [comment]
既然warp都自启了，能不能自启warp i。
（虽然自己crontab也能实现）

**Comment by fscarmen** [comment]
这个版本要求输入解锁地区，直接放 /etc/crontab 可能不行，我要加个传参上去才可以吧
比如  @reboot root warp i hk 这样

**Comment by fscarmen** [comment]
> 虽然自己crontab也能实现

不要求输入解锁区域那个版本是可以的，现在最新这个行吗？你是如何实现的？

**Comment by ben-august** [comment]
旧版本是可以的。新版本能不能加上去自启warp i，区域默认。

**Comment by fscarmen** [comment]
> 旧版本是可以的。新版本能不能加上去自启warp i，区域默认。

可以， warp i [地区] ，如果地区不填，就用当前获取到的地区作为默认

**Comment by fscarmen** [comment]
2022.1.21 Version 2.30: 

1.全面支持WARP单栈与双栈方案，简单并快速切换，如```warp s 4```,```warp s 6```,```warp s d```; 
 
2.在刷解锁 Netflix WARP IP 时可以带上期望的地区,如 ```warp i hk```。你可以结合 crontab,screen,nohup & 等方式使用

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/150553822-a0e80de6-e726-4472-85a6-500f2d1608e2.png)

**Comment by iii80** [comment]
docker里面是不是也可以用这个带界面的功能呢，可以选择支持netflix的ip

**Comment by ben-august** [comment]
请问最新版本warp自启是放到哪里了？crontab里没有来着。想自己实现开机自启使用screen完成warp i us。我怕和你的自启冲突。

**Comment by fscarmen** [comment]
我没有做自启，因为实现的方式有多样，如果太小白玩这个容易出现莫名其妙、奇奇怪怪的问题的。
你自己做可以了，你试一下
```
echo "@reboot root warp i hk" >> /etc/crontab
```

**Comment by ben-august** [comment]
> 
试了下warp i us命令 会出现语言选择，这个是正常的？？如果是这样要自启的话 crontab里添加以下任务是不行的吧
```
reboot root warp i hk
```

![image](https://user-images.githubusercontent.com/36500518/150628945-f93e42de-58fa-4bbd-82ff-b3c74d99a0b5.png)

**Comment by fscarmen** [comment]
你这个版本应该是比较旧的了，没有默认语言的

中文 ```echo 'C' >/etc/wireguard/language; warp v```

**Comment by ben-august** [comment]
但是我每次都是warp v更新的，现在用的就是最新版的2.30。意思是之前版本使用warp v更新后需要自己执行```echo 'C' >/etc/wireguard/language; warp v```来设置一次？

**Comment by fscarmen** [comment]
> 但是我每次都是warp v更新的，现在用的就是最新版的2.30。意思是之前版本使用warp v更新后需要自己执行`echo 'C' >/etc/wireguard/language; warp v`来设置一次？

只要一次即可，以后不需要用这个指令，用 ```warp v```就可以了

**Comment by ben-august** [comment]
已解决。多谢。
我在root目录下写了个warp_netflix.sh,内容如下：
```
screen -dmS warp
screen -r warp -p 0 -X stuff "warp i us"
screen -r warp -p 0 -X stuff $'\n'

```
然后在crontab里添加```@rebooot root /root/warp_netflix.sh```，成功实现自启以screen方式运行warp i us命令。

**Comment by fscarmen** [comment]
> screen -r warp -p 0 -X stuff "warp i us"
> screen -r warp -p 0 -X stuff $'\n'

这两个 screen 的参数分别是什么意思啊？也伸手一下：）

**Comment by fscarmen** [comment]
> echo '@reboot root warp i hk' >> /etc/crontab

echo '@reboot root warp i hk' >> /etc/crontab 这样是可以的，我故意设置了一下永远不可能获取到的区域，可以看到重启后，ip一直在变，进程也能看到
```
root@instance-2:~# curl -s4m5 ip.gs
8.44.63.79

root@instance-2:~# curl -s4m5 ip.gs
8.44.63.21

root@instance-2:~# curl -s4m5 ip.gs
8.44.63.102

root@instance-2:~# pgrep -laf warp
326 /bin/sh -c warp i de
327 /bin/bash /bin/warp i de

root@instance-2:~# ps -aux | grep warp
root       326  0.0  0.1   2388   752 ?        Ss   08:09   0:00 /bin/sh -c warp i de
root       327  0.0  0.5   5800  3528 ?        S    08:09   0:00 /bin/bash /bin/warp i de
root      5405  0.0  0.1   4836   888 pts/0    S+   08:12   0:00 grep warp


root@instance-2:~# cat /etc/crontab
...
...
@reboot root warp i de

```

**Comment by ben-august** [comment]
> > screen -r warp -p 0 -X stuff "warp i us"
> > screen -r warp -p 0 -X stuff $'\n'
> 
> 这两个 screen 的参数分别是什么意思啊？也伸手一下：）

我参考的这个呢https://blog.51cto.com/johnsteven/1323942

**Comment by fscarmen** [comment]
> 
> 我参考的这个呢https://blog.51cto.com/johnsteven/1323942

感觉复杂了，我整理了下：[刷 Netflix 解锁 WARP IP 的方法](https://github.com/fscarmen/warp/blob/main/README.md#%E5%88%B7-Netflix-%E8%A7%A3%E9%94%81-WARP-IP-%E7%9A%84%E6%96%B9%E6%B3%95)

**Comment by ben-august** [comment]
麻烦问一下这个解锁检测是远程检测的吗？我意思是检测脚本是远程调用的吗。因为有时候检测会失效（目前暂未遇到），所以需要作者保持更新，如果是远程调用的话，作者应该有维护，不用担心检测脚本失效。

**Comment by fscarmen** [comment]
> 麻烦问一下这个解锁检测是远程检测的吗？我意思是检测脚本是远程调用的吗。因为有时候检测会失效（目前暂未遇到），所以需要作者保持更新，如果是远程调用的话，作者应该有维护，不用担心检测脚本失效。

用落雪项目改过来了，大大化简了，只检测 Netflix，本地运行。如果调用方式，我们都没有做接口相互传参的情况下，我需要稍稍改动他们的脚本以便输出的结果传给我。

同时我也看了流行的几个查流媒体解锁的，都是一样的检测方法：通过《香肠猴》https://www.netflix.com/title/81215567 来查的。（估计大家都是"借鉴"来"借鉴"去的）

如果方法失效，会影响全部的Netflix解锁检测工具，他们更新的同时，我会马上同步上的。

**Comment by fscarmen** [comment]
> 麻烦问一下这个解锁检测是远程检测的吗？我意思是检测脚本是远程调用的吗。因为有时候检测会失效（目前暂未遇到），所以需要作者保持更新，如果是远程调用的话，作者应该有维护，不用担心检测脚本失效。

现在已经调用了 lmc999 检测 Netflix 用的 title 了，每次使用都会重新获取一次检测视频，毫秒级的。
