### ISSUE TITLE
一直刷的都是同一个IP，刷一辈子也刷不出来啊~！-【结论：2022.2.12 已升级，作了判断并限制，只能换 warp ip，避免用户一直换原生 IP 的现象发生】

### ISSUE THREAD

**Issue by caiqing7831** [fscarmen/warp#69]
![微信截图_20220119171025](https://user-images.githubusercontent.com/95904036/150099466-a8249ac3-a7be-4e61-894f-b29e49196c16.png)
vultr的机子
centOS7

**Comment by fscarmen** [comment]
请问你已经安装好warp了吗？这个 IP 好像是 VPS 的原生 IP
刷的话只能刷WARP IP

**Comment by caiqing7831** [comment]
> 

按照教程一步一步来的啊，没有哪个地方出现问题啊？
为什么会这样呢
测试了2台 都是这样子

**Comment by caiqing7831** [comment]
> 请问你已经安装好warp了吗？这个 IP 好像是 VPS 的原生 IP 刷的话只能刷WARP IP



> 请问你已经安装好warp了吗？这个 IP 好像是 VPS 的原生 IP 刷的话只能刷WARP IP

按照教程一步一步来的啊，没有哪个地方出现问题啊？
为什么会这样呢
测试了2台 都是这样子

**Comment by fscarmen** [comment]
> 按照教程一步一步来的啊，没有哪个地方出现问题啊？
> 
> 为什么会这样呢
> 
> 测试了2台 都是这样子

```warp n```
发来看看

**Comment by caiqing7831** [comment]
> warp n

![Uploading 5.png…]()

**Comment by caiqing7831** [comment]
> > 按照教程一步一步来的啊，没有哪个地方出现问题啊？
> > 为什么会这样呢
> > 测试了2台 都是这样子
> 
> `warp n` 发来看看

![5](https://user-images.githubusercontent.com/95904036/150151938-aaff6f62-d32d-4503-a6d0-503c11a4f711.png)

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/150153902-83aecf8e-a6db-4e9e-b9ca-8a102b6b9c59.png)

**Comment by fscarmen** [comment]
请问问题解决了吗？

**Comment by fscarmen** [comment]
已经复现了用户的问题了，你可以升级一下再刷，```warp v```
