### ISSUE TITLE
在甲骨文AMDX86 vps上无法运行

### ISSUE THREAD

**Issue by justhy** [fscarmen/warp#7]
下载脚本后，出现以下错误，脚本不会运行。

Last-modified header missing -- time-stamps turned off.

**Comment by fscarmen** [comment]
你的操作系统是什么呢？
用以下指令
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && chmod +x menu.sh && ./menu.sh
截个图来看看？

**Comment by justhy** [comment]
不好意思，我的VPS我给DD成Debian8了，不在脚本的支持范围内。

**Comment by fscarmen** [comment]
脚本加入了 ylx2016 的成熟作品，可以 继续DD
