### ISSUE TITLE
没有加载 TUN 模块，请在管理后台开启或联系供应商了解如何开启，

### ISSUE THREAD

**Issue by qiangua5210** [fscarmen/warp#70]
我问过供应商，没有限制此开关，我试过命令开启也无法开启，我的系统是centos7.5，请问下大佬怎么弄

**Comment by qiangua5210** [comment]
我查完，显示的我tun模块是开启状态，但是我还是无法安装脚本

**Comment by fscarmen** [comment]
先运行以下指令，把结果发来看看```cat /dev/net/tun```

运行以下的跳过TUN
```
wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && sed -i "696d" menu.sh && bash menu.sh
```

**Comment by qiangua5210** [comment]
![eee](https://user-images.githubusercontent.com/24908791/150301165-7324f17e-93df-466d-9e47-e463b3bd5209.png)

**Comment by fscarmen** [comment]
看看最后获取 WARP IP 的时候是否能成功了

**Comment by qiangua5210** [comment]
@fscarmen 我晚点我测试下，:smile:，谢谢

**Comment by qiangua5210** [comment]
5次尝试失败。脚本终止了

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/150316401-da6e728b-2020-4b73-a4a8-b95254de0aaa.png)

**Comment by qiangua5210** [comment]
> ```warp```
> 截图看一下什么系统。其实你那个提示是没有开TUN的

centos7

**Comment by qiangua5210** [comment]
> `warp` 截图看一下什么系统。其实你那个提示是没有开TUN的

我换成debian可以获取到ip了，但是更换奈飞ip，一直没有成功，更换5次必定卡主。。。
必须要重启机器或者等待很久才能操作

**Comment by fscarmen** [comment]
你在 Debian 输入 ```cat /dev/net/tun``` 显示与 CentOS 一样的信息吗？脚本是通过这里的回显来判断是否开TUN的

是不是机器或者网络性能过差？更换的时间从5秒换成15秒试试，j=15 表示中间间隔15秒
```
sed -i "s/i=0;j=5/i=0;j=15/g" /etc/wireguard/menu.sh
```

**Comment by qiangua5210** [comment]
> 你在 Debian 输入 `cat /dev/net/tun` 显示与 CentOS 一样的信息吗？脚本是通过这里的回显来判断是否开TUN的
> 
> 是不是机器或者网络性能过差？更换的时间从5秒换成15秒试试，j=15 表示中间间隔15秒
> 
> ```
> sed -i "s/i=0;j=5/i=0;j=15/g" /etc/wireguard/menu.sh
> ```

返回的不是一样的，机器确实不是很好，但是我觉得够用

**Comment by fscarmen** [comment]
> 返回的不是一样的

现在```cat /dev/net/tun```回显是什么呢？
把刷的间隔时长调大了问题解决了吗？

**Comment by qiangua5210** [comment]
> 
cat: /dev/net/tun: File descriptor in bad state
显示这个。
我还没调整更换时间，现在好像拉不到ip了，更换了38次还是没有。。我现在把更换时间拉长试试

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/150457027-f8659218-783b-4daa-bee7-ef28afac8510.png)
我吧刷的间隔时间拉长，然后就刷了7次就卡主了的。。
![image](https://user-images.githubusercontent.com/24908791/150457089-87a49d7a-b729-482d-97e0-09070d4863a5.png)

**Comment by fscarmen** [comment]
香港的 WARP 解锁有点难的，很多IP都在小黑屋里。要刷挺久的

**Comment by fscarmen** [comment]
> cat: /dev/net/tun: File descriptor in bad state

这个才是 TUN 打开该显示的内容

**Comment by qiangua5210** [comment]
> 香港的 WARP 解锁有点难的，很多IP都在小黑屋里。要刷

**Comment by qiangua5210** [comment]
> > 香港的 WARP 解锁有点难的，很多IP都在小黑屋里。要刷
![image](https://user-images.githubusercontent.com/24908791/150459278-4a045e90-018f-4e0a-baa0-c0d9428e4900.png)
我选的新加坡的也不行，还是解锁的香港，而且好像也卡在了14次

**Comment by fscarmen** [comment]
> 我选的新加坡的也不行，还是解锁的香港，而且好像也卡在了14次

这样你永远刷不出来的，因为WARP是就近分配的，HK有点，他一定会分配香港的，你选了SG，是永远没有可能成功的

**Comment by qiangua5210** [comment]
> > 我选的新加坡的也不行，还是解锁的香港，而且好像也卡在了14次
> 
> 这样你永远刷不出来的，因为WARP是就近分配的，HK有点，他一定会分配香港的，你选了SG，是永远没有可能成功的

这样吗。。。好吧

**Comment by qiangua5210** [comment]
> > 我选的新加坡的也不行，还是解锁的香港，而且好像也卡在了14次
> 
> 这样你永远刷不出来的，因为WARP是就近分配的，HK有点，他一定会分配香港的，你选了SG，是永远没有可能成功的

但是有时候显示当前地区是us，是怎么回事呀

**Comment by fscarmen** [comment]
获取不到地区时，默认值为US。有可能是 CloudFlare 公司是美国导致的，反正你是香港的话，必须要刷到香港才行。我有的鸡性能很差的，都不会这样刷死。建议你放screen里刷

**Comment by qiangua5210** [comment]
screen 这个我不会。。。

**Comment by fscarmen** [comment]
> 
> 我换成debian可以获取到ip了，但是更换奈飞ip，一直没有成功，更换5次必定卡主。。。 必须要重启机器或者等待很久才能操作

找到个问题点，如果获取 IP 信息的 ip.gs 返回 IP 不及时，就会导致我脚本卡死的情况，已经作了相应的处理，估计是OK了

**Comment by qiangua5210** [comment]
> 

我暂时用甲骨文的代替了，回头我试下

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/150680953-bd756825-1ec3-42c7-b1ef-8dbc623af776.png)
这次好多了刷了700多次，可能长时间没动，自动断开了。好难刷

**Comment by fscarmen** [comment]
>screen 这个我不会。。。

我已经在 README.md 里放了说明了，很详细的

> 这次好多了刷了700多次，可能长时间没动，自动断开了。好难刷

已经刷死说明bug应该是处理好了。
今天 CloudFlare 香港在调路由维护中，一直刷不到，这可以在这里查 https://www.cloudflarestatus.com/
以下是我的：
![photo1642940868](https://user-images.githubusercontent.com/62703343/150681170-29cfb426-2786-4823-86a2-b1eea07b9a78.jpeg)

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/150681326-6cf50520-ca9c-4969-9e08-50235addb71b.png)
还有个问题。这个时候我点更换ip，读出来的时候就是us地区了

**Comment by fscarmen** [comment]
有时候读不到值，就默认US，没有关系的，填你需要的就行，最重要是能刷出来的

**Comment by qiangua5210** [comment]
> 默认US，没有关系的，填你需要的就行，最重要是能刷出来的

我懂了，等那个cloudflare上那个香港正常了再去换ip是吧

**Comment by fscarmen** [comment]
不用等啦，你一直刷，反正是后台的，有空过去看看可以了

**Comment by qiangua5210** [comment]
> 不用等啦，你一直刷，反正是后台的，有空过去看看可以了

ok，谢谢

**Comment by fscarmen** [comment]
> ok，谢谢

主页的screen学会了没有？

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/150681755-f71087f0-4fc6-4cf2-bae6-e05969005c4b.png)
这个吗。我没看懂这是干嘛用的。。。

**Comment by fscarmen** [comment]
在后台刷 Netflix 的方法

**Comment by qiangua5210** [comment]
> 在后台刷 Netflix 的方法

就是挂着，我不用打开ssh看着的意思是吧

**Comment by fscarmen** [comment]
是的，即使你退出ssh，机器也会在后台自动运行着啊

**Comment by qiangua5210** [comment]
不管，我就要看着，哈哈哈哈

**Comment by fscarmen** [comment]
香港的我这里已经可以了。说明维护好了

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/150682561-f163d8f3-beb1-4fc9-99f9-547502bf955d.png)
nice，几天了第一次看到ipw，我来试试

**Comment by qiangua5210** [comment]
用了两天了，目前没啥问题，感谢大佬。
