### ISSUE TITLE
无法获取ip  -【结论：已处理】

### ISSUE THREAD

**Issue by qiangua5210** [fscarmen/warp#71]

**Comment by fscarmen** [comment]
把菜单界面关于机器情况的截图看看
分别运行 ```cat /dev/net/tun```   
```wg-quick up wgcf```
发回显看看

**Comment by fscarmen** [comment]
请问问题解决了吗？

**Comment by qiangua5210** [comment]
> 请问问题解决了吗？

我是之前问你的那个，同一个人哇，弄好了哇

**Comment by fscarmen** [comment]
哈哈，我记得了，准备有大招出来了

**Comment by qiangua5210** [comment]
> 哈哈，我记得了，准备有大招出来了
有啥大招哈哈

**Comment by fscarmen** [comment]
2022.1.25 Media unlock daemon. Check it every 5 minutes. If unlocked, the scheduled task exits immediately. If it is not unlocked, it will be swiped successfully in the background. Advantages: Minimized use of system resources. Disadvantage: Can't see the results as intuitively as screen

流媒体解锁守护进程,定时5分钟检查一次,遇到不解锁时更换 WARP IP，直至刷成功。 优点: 占用系统资源最小化。 缺点: 不能像 screen 那么直观看到结果

bash <(curl -sSL https://raw.githubusercontent.com/fscarmen/tools/main/warp_crontab.sh)

**Comment by qiangua5210** [comment]
我安装了，怎么才能知道有没有刷成功呢，这是后台进程，

**Comment by fscarmen** [comment]
WGCF 方式
````
curl -4 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36" -fsL --write-out %{http_code} --output /dev/null --max-time 10 "https://www.netflix.com/title/81215567"
```

Socks5 方式
```
curl --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36' -s4m5 --socks5 "$(ss -nltp | grep warp | grep -oP '127.0*\S+')" -fsL --write-out '%{http_code}' --output /dev/null --max-time 10 https://www.netflix.com/title/81215567
```

如显示 200 则是已经解锁成功，如果是404、403说明解决不成功，000说明获取不了地区信息。
日后工具会升级，用户体验感超强。

**Comment by qiangua5210** [comment]
可以，我重新弄了一台机器，但是好像挺难刷出来的，香港的

**Comment by fscarmen** [comment]
你地区那里有没有选香港啊？

**Comment by qiangua5210** [comment]
> 你地区那里有没有选香港啊？
默认就是香港，我填的y

**Comment by fscarmen** [comment]
你用上面的方式，回显是什么？

**Comment by qiangua5210** [comment]
![image](https://user-images.githubusercontent.com/24908791/151096823-b72ff62e-3ec4-41d4-88fa-bc7dcdb999fd.png)

**Comment by qiangua5210** [comment]
卧槽。牛皮，可以了，哈哈哈，真牛皮

**Comment by fscarmen** [comment]
> 卧槽。牛皮，可以了，哈哈哈，真牛皮

用户的支持是最大的动力，暂时项目只做了个最最基础功能，后续还会有更多的姿势来刷 WARP IP，尽管我已经把认为最好的方法提前做了。

**Comment by qiangua5210** [comment]
哈哈哈，谢谢大佬。舒服，机场又贵，支持奈飞又不及时，还是自己弄一个自在一点，哈哈

**Comment by fscarmen** [comment]
我可以加这群，我在里面 https://t.me/+DXRiWU7iEdYwNTA1

**Comment by qiangua5210** [comment]
好的哇

**Comment by fscarmen** [comment]
这个，https://t.me/bins_bins666，刚才管理员把群公开了

**Comment by qiangua5210** [comment]
> 这个，https://t.me/bins_bins666，刚才管理员把群公开了

我刚才加了，douyu就是我
