### ISSUE TITLE
后台获取 WARP IP，5次失败-【结论：原环境是 Debian 11 + bbrplus 4.14.129，通过脚本入口 [ylx2016] 大神脚本升级为最新的 5.10.89 就成功了】

### ISSUE THREAD

**Issue by JohnfreeLau** [fscarmen/warp#72]

**Comment by fscarmen** [comment]
把菜单界面关于机器情况的截图看看
分别运行 ```cat /dev/net/tun```   
```wg-quick up wgcf```
发回显看看

**Comment by JohnfreeLau** [comment]
![image](https://user-images.githubusercontent.com/58518949/150461158-5cadc0ab-9458-4a83-a0b2-7548820b7e2e.png)
![image](https://user-images.githubusercontent.com/58518949/150461300-e823b660-4baa-4d23-8c21-70768d551208.png)
![image](https://user-images.githubusercontent.com/58518949/150461432-9ae68bfd-29fe-4098-a9e1-e579d8e825a6.png)

**Comment by fscarmen** [comment]
``` warp b``` 把BBRPLUS内核升级即可，以下一样的问题处理了
#58 #54

**Comment by fscarmen** [comment]
请问问题解决了吗？

**Comment by JohnfreeLau** [comment]
> 请问问题解决了吗？

解决了

**Comment by fscarmen** [comment]
> 解决了

是通过升级 bbrplus 、更换内核还是什么办法处理的呢？
