### ISSUE TITLE
版本更新后ip没原来好刷

### ISSUE THREAD

**Issue by USATRUMP2021MAGA** [fscarmen/warp#74]
![Annotation 2022-01-24 175746](https://user-images.githubusercontent.com/93851708/150896698-bb4f857a-134e-45d1-9cee-f8229336737f.png)
![Annotation 2022-01-24 175924](https://user-images.githubusercontent.com/93851708/150896710-848c30ec-ef7e-442d-8a1c-5850f0468b1f.png)

**Comment by USATRUMP2021MAGA** [comment]
是哪一步安装有误吗？？

**Comment by USATRUMP2021MAGA** [comment]
发现刷的ip一直有重复的

**Comment by fscarmen** [comment]
> 是哪一步安装有误吗？？

没有问题



> 发现刷的ip一直有重复的

IP分配机制是自动就近分配的，所以有可能分配到重复的，因为这个随机性就导致了成功的偶然性，运气就快点，运气差就慢点。暂时未找到能控制的方法。以下是我香港的挂机刷解锁的情况，可以看到上一次是刷了70多次才成功的

![image](https://user-images.githubusercontent.com/62703343/150903756-e3f20439-8080-4e7a-a9fa-a6cda36b0826.png)

**Comment by USATRUMP2021MAGA** [comment]
![Annotation 2022-01-24 191913](https://user-images.githubusercontent.com/93851708/150904891-68a47417-cb41-4bfc-8360-b009a8f1ebd0.png)
换了台机器安装提示这

**Comment by fscarmen** [comment]
```cat /dev/net/tun```
```hostnamectl```
发个回显看看

**Comment by fscarmen** [comment]
长时间没有回复，临时关闭处理。
