### ISSUE TITLE
定时任务， 5分钟后台检测一次是否解锁

### ISSUE THREAD

**Issue by othelloYu** [fscarmen/warp#75]
1.  实现5分钟后台检测一次是否解锁，然后判断是否切换的方法

大佬，很冒昧我想问一下您所说的定时任务，比如5分钟后台检测一次是否解锁，因为我的新加坡的机子不知道是什么原因好像每天上午10点多就会解锁失败，然后我就要被迫连ssh重新更换Netflix ip，我也上网查了下crontab的使用方法，我打算每小时自动监测一次  vim /etc/crobtab  @hourly 0 * * * *  （后面就不会写了，我不知道如何监测以及对监测结果进行判定进行切换） 大佬可以告诉我我该怎么做吗？

**Comment by fscarmen** [comment]
> 1. 实现5分钟后台检测一次是否解锁，然后判断是否切换的方法
> 
> 大佬，很冒昧我想问一下您所说的定时任务，比如5分钟后台检测一次是否解锁，因为我的新加坡的机子不知道是什么原因好像每天上午10点多就会解锁失败，然后我就要被迫连ssh重新更换Netflix ip，我也上网查了下crontab的使用方法，我打算每小时自动监测一次 vim /etc/crobtab @hourly 0 * * * * （后面就不会写了，我不知道如何监测以及对监测结果进行判定进行切换） 大佬可以告诉我我该怎么做吗？

这里介绍的方法都可以用呀https://github.com/fscarmen/warp/blob/main/README.md#%E5%88%B7-netflix-%E8%A7%A3%E9%94%81-warp-ip-%E7%9A%84%E6%96%B9%E6%B3%95

如果你想5分钟检测一次，不解锁就运行，可以参照我另一项目，他是每次钟检测一次docker状态的
https://github.com/fscarmen/tools/blob/main/EU_docker_Up.sh

**Comment by othelloYu** [comment]
> > 1. 实现5分钟后台检测一次是否解锁，然后判断是否切换的方法
> > 
> > 大佬，很冒昧我想问一下您所说的定时任务，比如5分钟后台检测一次是否解锁，因为我的新加坡的机子不知道是什么原因好像每天上午10点多就会解锁失败，然后我就要被迫连ssh重新更换Netflix ip，我也上网查了下crontab的使用方法，我打算每小时自动监测一次 vim /etc/crobtab  @hourly  0 * * * * （后面就不会写了，我不知道如何监测以及对监测结果进行判定进行切换） 大佬可以告诉我我该怎么做吗？
> 
> 这里介绍的方法都可以用呀 [https://github.com/fscarmen/warp/blob/main/README.md#%E5%88%B7-netflix-%E8%A7%A3%E9%94%81-warp-ip-%E7%9A%84%E6%96%B9%E6%B3%95 ](https://github.com/fscarmen/warp/blob/main/README.md#%E5%88%B7-netflix-%E8%A7%A3%E9%94%81-warp-ip-%E7%9A%84%E6%96%B9%E6%B3%95)
> 
> 如果你想5分钟检测一次，不解锁就运行，可以参照我另一项目，他是每次钟检测一次docker状态的 [https://github.com/fscarmen/tools/blob/main/EU_docker_Up.sh ](https://github.com/fscarmen/tools/blob/main/EU_docker_Up.sh)

哦，懂了懂了，多谢大佬解答。原来是直接以screen 多会话方式运行 ，脚本已经自带监测和切换的了，我都没有想到可以这样，学到了，谢谢大佬！

**Comment by fscarmen** [comment]
> 1.  实现5分钟后台检测一次是否解锁，然后判断是否切换的方法
> 
> 
> 
> 大佬，很冒昧我想问一下您所说的定时任务，比如5分钟后台检测一次是否解锁，因为我的新加坡的机子不知道是什么原因好像每天上午10点多就会解锁失败，然后我就要被迫连ssh重新更换Netflix ip，我也上网查了下crontab的使用方法，我打算每小时自动监测一次  vim /etc/crobtab  @hourly 0 * * * *  （后面就不会写了，我不知道如何监测以及对监测结果进行判定进行切换） 大佬可以告诉我我该怎么做吗？

这个我计划花点时间来做，主要是测试。预估春节前。让大家多个选择。
