### ISSUE TITLE
香港谷歌云无法开启warp

### ISSUE THREAD

**Issue by wangsicheng0710** [fscarmen/warp#77]
无论安装了多少次都会提示：没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。
但是在加拿大的谷歌云上就可以成功安装
用的同一个脚本

**Comment by fscarmen** [comment]
香港那里应该是没有安装成功，运行以下两条指令，发回显
```
type -P wg
ls /etc/wireguard/
```

**Comment by wangsicheng0710** [comment]
language  menu.sh  wgcf-account.toml  wgcf-profile.conf  wgcf.conf

**Comment by fscarmen** [comment]
第一条呢

**Comment by wangsicheng0710** [comment]
第一条没输出

**Comment by fscarmen** [comment]
什么系统，改过内核吗？

**Comment by wangsicheng0710** [comment]
没改过内核
Debian

**Comment by fscarmen** [comment]
你试试
```
apt -y update
ayt -y install wireguard-tools
```
看看如何提示
如果成功再
```
type -P wg
```

**Comment by wangsicheng0710** [comment]
谢谢

**Comment by wangsicheng0710** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 linux-headers-4.11.8-041108-generic : Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by wangsicheng0710** [comment]
还是没输出

**Comment by wangsicheng0710** [comment]
可以上了
谢谢大佬

**Comment by wangsicheng0710** [comment]
又不行

**Comment by wangsicheng0710** [comment]
这个WireGuard tools咋安装

**Comment by fscarmen** [comment]
升级一下内核先，应该是过旧
```
warp b
```

**Comment by wangsicheng0710** [comment]
还是不行

**Comment by wangsicheng0710** [comment]
还是提示WireGuard tools咋办

**Comment by fscarmen** [comment]
你换个系统试试，我也是用GCP Debian 11的，一定可以

**Comment by fscarmen** [comment]
长时间没有回复，临时关闭处理。

**Comment by fscarmen** [comment]
最新技术---warp-go，独立于 wgcf，拯救像香港、多伦多等不能通过 wgcf 获取 warp 服务的 vps，让其获取 WARP IPv4, IPv6 或双栈，实现 warp 全局
一键脚本:[warp-go 运行脚本](https://github.com/fscarmen/warp#warp-go-%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC)
