### ISSUE TITLE
获取WARP IP5次都失败-【结论：用户一直未能获取，放弃了】

### ISSUE THREAD

**Issue by Ryana15ptcc** [fscarmen/warp#78]

**Comment by fscarmen** [comment]
wg-quick up wgcf
warp进菜单截个配置看看

**Comment by Ryana15ptcc** [comment]
![Uploading Screenshot_2022-01-27-22-28-59-767_JuiceSSH.png…]()

**Comment by fscarmen** [comment]
升级下CentOS内核，太旧了

**Comment by reov** [comment]
我的ipv6 only小鸡也5次都不行
![Screenshot_2022-02-16-12-45-47-91_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/47272954/154197955-b67e7316-df50-4d86-9370-be390ac7803e.jpg)
![Uploading Screenshot_2022-02-16-12-47-12-29_3d419158bad5872c40592a6c9956e692.jpg…]()

**Comment by fscarmen** [comment]
> 我的ipv6 only小鸡也5次都不行

运行指令，进入 warp 菜单，一并截个图来看看
```
cat /etc/wireguard/wgcf.conf
```

**Comment by reov** [comment]
> 

![Uploading Screenshot_2022-02-16-15-03-52-34_3d419158bad5872c40592a6c9956e692.jpg…]()

![Uploading Screenshot_2022-02-16-15-04-30-47_3d419158bad5872c40592a6c9956e692.jpg…]()

**Comment by reov** [comment]
![Screenshot_2022-02-16-15-03-52-34_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/47272954/154213872-16ff2073-d694-4c05-81ad-65f415efd346.jpg)
![Screenshot_2022-02-16-15-04-30-47_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/47272954/154213940-c1fd8898-3f5a-45c7-99d5-3bb5aea509f2.jpg)

**Comment by fscarmen** [comment]
看不出问题 ：（

**Comment by fscarmen** [comment]
问题处理了吗？

**Comment by reov** [comment]
没有，已经放弃了

fscarmen ***@***.***> 于 2022年2月26日周六 21:33写道：
