### ISSUE TITLE
支持 armv7l 架构 -【结论：没有机器测试，对 Raspbian 又相对陌生，暂不做支持】 

### ISSUE THREAD

**Issue by hmsjy2017** [fscarmen/warp#79]
```
当前架构 armv7l 暂不支持,问题反馈:[https://github.com/fscarmen/warp/issues]
```
希望加入 armv7l / armhf 支持
另外建议支持 Raspbian。

**Comment by fscarmen** [comment]
这些架构的系统我都没有接触过，也没有机器试呢。
armv7 理论上是可以的。

**Comment by hmsjy2017** [comment]
wgcf 官方提供 armv7 的二进制文件
https://github.com/ViRb3/wgcf/releases/download/v2.2.11/wgcf_2.2.11_linux_armv7

**Comment by fscarmen** [comment]
我看到，但没有测试环境。所以没有放进去

**Comment by hmsjy2017** [comment]
我可以协助测试

**Comment by fscarmen** [comment]
wget -O $PWD/menu.sh https://github.com/fscarmen/warp/blob/main/old/t.sh && bash $PWD/menu.sh

**Comment by hmsjy2017** [comment]
```
本脚本只支持 Debian、Ubuntu、CentOS 或 Alpine 系统,问题反馈:[https://github.com/fscarmen/warp/issues]
```
由于系统是 Raspbian，暂时用不了。
