### ISSUE TITLE
euserv执行脚本报错

### ISSUE THREAD

**Issue by aProfessor23** [fscarmen/warp#8]
一直提示443... failed network is unreachable，我用之前的脚本可以wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && chmod +x menu.sh && ./menu.sh

**Comment by fscarmen** [comment]
德鸡的话，请先添加DNS64，再运行就可以了
echo nameserver 2a00:1098:2b::1 > /etc/resolv.conf

**Comment by aProfessor23** [comment]
多谢

> 德鸡的话，请先添加DNS64，再运行就可以了
> echo nameserver 2a00:1098:2b::1 > /etc/resolv.conf
> 
> wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && chmod +x menu.sh && ./menu.sh

**Comment by fscarmen** [comment]
成功了吗？

**Comment by aProfessor23** [comment]
> 成功了吗？

按你的方法，我试了下可以。

**Comment by fscarmen** [comment]
只是德鸡需要添加那个 DNS64 的nameserver，其他的不用，直接运行可以了。
