### ISSUE TITLE
warp安装失败

### ISSUE THREAD

**Issue by 15601560** [fscarmen/warp#80]
运行warp结果
```
 系统信息：
        当前操作系统：CentOS Linux 7 (Core)
        内核：5.16.4-1.el7.elrepo.x86_64
        处理器架构：amd64
        虚拟化：kvm 
        IPv4：104.233.163.184  美国  PEGTECHINC-AP-03 
        IPv6：     
        WARP 网络接口未开启 
        Client 未安装
```
运行wg-quick up wgcf结果
```
[#] ip link add wgcf type wireguard
[#] wg setconf wgcf /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev wgcf
[#] ip -6 address add fd01:5ca1:ab1e:82f6:3efe:852a:294c:b392/128 dev wgcf
[#] ip link set mtu 1420 up dev wgcf
[#] mount `1.1.1.1 8.8.8.8 8.8.4.4 2606:4700:4700::1111 2001:4860:4860::8888 2001:4860:4860::8844' /etc/resolv.conf
unshare: unrecognized option '--propagation'

Usage:
 unshare [options] <program> [args...]

Options:
 -m, --mount       unshare mounts namespace
 -u, --uts         unshare UTS namespace (hostname etc)
 -i, --ipc         unshare System V IPC namespace
 -n, --net         unshare network namespace
 -p, --pid         unshare pid namespace

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see unshare(1).
[#] ip link delete dev wgcf
```
加速内核bbr fq 更新过了已重启

**Comment by fscarmen** [comment]
> 运行warp结果
> 
> 
> 加速内核bbr fq 更新过了已重启

兄弟专业，我能想到的检测方式和处理方法都给你使用了。在所有用户的反馈中，系统遇到问题的9成是CentOS问题
故障点应该在
```
unshare: unrecognized option '--propagation'
```
这个我也不会，你可以找找有没有相关资料，升级别个依赖处理一下。实在不行可以换 Ubuntu或者 Debian系统，至少是CentOS 8。等你好消息

**Comment by 15601560** [comment]
一路从Debian9（不行）升级到11
偷渡到了FFF
 当前操作系统：Debian GNU/Linux 11 (bullseye)
        内核：5.10.0-11-amd64
        处理器架构：amd64
        虚拟化：kvm 
        IPv4：8.37.43.229 ( WARP IPv4 ) 日本  CLOUDFLARENET 
        IPv6：2a09:bac0:22::825:2be5 ( WARP IPv6 ) 日本  CLOUDFLARENET

**Comment by 15601560** [comment]
应该是系统叭，建议安装之前检测下，不是能用的系统直接说了，免得再来问

**Comment by fscarmen** [comment]
> 应该是系统叭，建议安装之前检测下，不是能用的系统直接说了，免得再来问

这个已经有了。Debian ≥ 10 ，Ubuntu ≥ 18.04 , CentOS ≥ 7
Debian 9 应该会有提示说不支持。(当然可以用 docker 方案，这里不展开）
CentOS 7 也是有比较多可以支持的，所以不能作一刀切。

**Comment by 15601560** [comment]
> > 应该是系统 Lou，建议安装前检测下，不是能用的系统直接说了，免得再来问
> 
> Debian ≥ 10 ，Ubuntu ≥ 18.04 ，CentOS ≥ 7，会有提示不支持的。 Debian 9 应该说提示不支持的。（当然可以用docker 方案，这里不展开） CentOS 7 也是有比较可以支持的，所以不能作一刀切。


当前操作系统：CentOS Linux 7.9

        内核：3.10.0-957.el7.elrepo.x86_64

        处理器架构：amd64

        虚拟化：kvm 

看到你说有的centos有的中用，居然成了，按着这个服务器提供商给的centos是Linux Centos 7.0.1406 X86 64 Min Gen2 V2，更新到7.9依然不行，用隔壁dd脚本装到7就可以正常运行，内核是3.10，应该和内核没关系，可能是服务商删了一些组件还是mini版本本就缺少组件有待验证

**Comment by fscarmen** [comment]
那个 mini 版本的也有些是可以，例如 EUserv ，所以只能如此了，看来你是 CentOS 的忠实用户啊。

**Comment by 15601560** [comment]
哦豁，EUserv中用？我去搞一台，等我发现点啥给你仓库push点垃圾

**Comment by fscarmen** [comment]
> 哦豁，EUserv中用？我去搞一台，等我发现点啥给你仓库push点垃圾

学习机来的，之前测试主安装脚本的时候非常有用，我 CentOS 7,8; Ubuntu 18.04, 20.04; Debian 9, 10 ,11 都有一台来试的。

**Comment by 15601560** [comment]
芜湖，我找到解决办法！！！！！！！！

应该是软件包老旧

1. 用隔壁换源一把梭 `bash <(curl -sSL https://cdn.jsdelivr.net/gh/SuperManito/LinuxMirrors@main/ChangeMirrors.sh)` 
2. 镜像选择有**EPEL**的（阿里腾讯华为均可） 下面**一路y下去**确认就好
3. 更新内核（**可不选**）
4. 直接执行warp脚本
 ps. EPEL 真好用

**Comment by 15601560** [comment]
```
        当前操作系统：CentOS Linux 7 (Core)
        内核：5.16.4-1.el7.elrepo.x86_64
        处理器架构：amd64
        虚拟化：kvm 
        IPv4：8.37.43.220 ( WARP IPv4 ) 日本  CLOUDFLARENET 
        IPv6：2a09:bac0:22::825:2bdc ( WARP IPv6 ) 日本  CLOUDFLARENET 
        WARP 网络接口已开启 

```

**Comment by 15601560** [comment]
可以尝试在脚本运行时先添加EPEL源，这样包不会因为老旧无法运行

**Comment by fscarmen** [comment]
这块就算了，这个是更底层需要处理的了，各vps供应商原始epel源肯定有他的原因。如果随便换了，改了官方的配置，无论换哪个源如果因为线路的原因连不上，带来是灾难性的。这无疑是给自己挖大坑的。
