### ISSUE TITLE
只安装WARP Client开启SOCKS5代理，怎样应用teams账户设置？ -【结论：Teams信息只能用于WGCF方案。 Client 可以用 WARP+ License】

### ISSUE THREAD

**Issue by windfrom** [fscarmen/warp#82]
安装了 WARP Linux Client并开启 Socks5 代理模式

通过安卓模拟器抓包了Teams账户设置，但当想应用到WARP设置时，在/etc/wireguard下没有发现wgcf.conf配置文件

是不是必须得安装WARP IPv4或IPv6网络接口后才有wgcf.conf配置文件？

在仅安装WARP Client的情况下要怎么才能应用teams账户设置呢？

**Comment by fscarmen** [comment]
Teams信息只能用于WGCF方案
而client的话可用WARP+方案，README有提供获取方式

**Comment by windfrom** [comment]
> Teams信息只能用于WGCF方案 而client的话可用WARP+方案，README有提供获取方式

多谢解惑了！

我试了安装了WARP IPv4网络接口后，在/etc/wireguard下有两个配置文件wgcf.conf和wgcf-profile.conf，两个都需要更改吗？

**Comment by windfrom** [comment]
> 

刚只改了一个配置后不能获取IP了，两个同时更改后就可以使用Teams账户了！WARP IPv4网络接口

**Comment by fscarmen** [comment]
wgcf.conf
改这个可以了

**Comment by windfrom** [comment]
> 

试了用1.1.1.1客户端获取WARP+ License Key，但在用warp a + License升级warp+账户时总是提示“升级失败，WARP+ 账户错误或者已激活超过5台设备，自动更换免费 WARP 账户继续”，手机客户端账户设备中就显示了两台设备，一台是手机本身，另外一台链接的设备是刚才升级warp+账户的VPS，没有超过5台设备。这是怎么回事呢

**Comment by fscarmen** [comment]
我这里是可以哦，你的 license 格式是如何的？

![image](https://user-images.githubusercontent.com/62703343/152354938-d1fed542-38b0-4f61-b94f-8fcdb1787c25.png)

**Comment by windfrom** [comment]
> 我这里是可以哦，你的 license 格式是如何的？
> 
> ![image](https://user-images.githubusercontent.com/62703343/152354938-d1fed542-38b0-4f61-b94f-8fcdb1787c25.png)

终于可以了！！原来是我还没有任何流量，得先刷到流量再能升级成功WARP+账户。。。

**Comment by fscarmen** [comment]
> 
> 终于可以了！！原来是我还没有任何流量，得先刷到流量再能升级成功WARP+账户。。。

你是成功了吗？用脚本里提供的来刷？

**Comment by fscarmen** [comment]
不客气，谢谢你的支持！
