### ISSUE TITLE
「求助」脚本运行，检测环境后，无IPv4/v6，并且选项1和2显示不完整-【结论：腾讯轻云，大陆VPS，禁止连接engage.cloudflareclient.com，故用不了WARP】

### ISSUE THREAD

**Issue by yfchen1988** [fscarmen/warp#83]
腾讯轻量云 - 香港 Ubuntu 20.04
已经切换到Ubuntu官方repo，并且apt-get update/apt-get upgrade
手动安装了wireguard、wireguard-tools
uname -r  5.16.7-051607-generic
type -P wg 返回 /usr/bin/wg
ls /etc/wireguard 返回没有，文件夹中空空如也

再bwg的美国机器上使用一切正常

错误截图如下，还请前辈、先进指教。

![截屏2022-02-06 23 24 40](https://user-images.githubusercontent.com/26248546/152688546-5afb4c3a-69a3-41e2-b322-b2dc1e76cd91.png)
![截屏2022-02-06 23 25 22](https://user-images.githubusercontent.com/26248546/152688556-92547a72-20f6-4b9f-bfb0-890ea9d77004.png)

**Comment by fscarmen** [comment]
> ls /etc/wireguard 返回没有，文件夹中空空如也

没有安装成功，不知道腾讯轻量云的线路有没有限制，你先 
关了 wgcf ```wg-quick down wgcf```
测一下是否能连通 warp 的服务器 ```ping -c2 -W10 162.159.192.1 ```

**Comment by yfchen1988** [comment]
> > ls /etc/wireguard 返回没有，文件夹中空空如也
> 
> 没有安装成功，不知道腾讯轻量云的线路有没有限制，你先 关了 wgcf `wg-quick down wgcf` 测一下是否能连通 warp 的服务器 `ping -c2 -W10 162.159.192.1 `

感谢你这么晚了还能回复，帮助解答。

根据你的指点，尝试关闭WG，但还提示缺少conf文件，关闭后截图如下；
同时在这个状态下去ping warp服务器，结果如截图2；

供参考，还望得到进一步指导，谢谢！

![截屏2022-02-06 23 49 11](https://user-images.githubusercontent.com/26248546/152689149-eba901b0-2d2c-4e5a-bf08-ca0b47bc2a88.png)


![截屏2022-02-06 23 52 41](https://user-images.githubusercontent.com/26248546/152689158-48578a08-df51-4818-b582-a8040220948d.png)

**Comment by fscarmen** [comment]
麻烦了，大陆鸡，与阿里云一样，如果你一开始用脚本安装，应该会提示这点的

**Comment by yfchen1988** [comment]
抱歉，我没有明白你的意思。
“麻烦了”是指什么呢？解决这个问题需要相当复杂和繁琐的步骤？又或是只其他方面的，比如与现实生活相关的？
我在使用unlock.sh脚本的开始时候并没有注意到什么关于大陆机的提示。能否麻烦你告知大致内容，我重新运行一次仔细看看呢？

谢谢你！
祝新年快乐！
发自我的iPhone

**Comment by fscarmen** [comment]
> 抱歉，我没有明白你的意思。

使用 warp 的服务，你可以理解一端A是你这里，另一端B是CF的服务端，连通这两端才能使用。大陆的vps限制对接B，等于用不了，暂时我没有办法破。

**Comment by yfchen1988** [comment]
彻底明白了！ 谢谢。

那就放弃这台大陆的机器了。不过看来无论是阿里云还是腾讯云，即使机器机房在香港，也无法使用warp了呗。

发自我的iPhone

**Comment by fscarmen** [comment]
> 不过看来无论是阿里云还是腾讯云，即使机器机房在香港，也无法使用warp了呗。

我想是的。

**Comment by fscarmen** [comment]
### Personal & WARP
| 162.159.192.0 | [2606:4700:d0::a29f:c000] |
| :---: | :---: |
| 162.159.192.1:2408 | [2606:4700:d0::a29f:c001]:2408
| 162.159.192.2:2408 | [2606:4700:d0::a29f:c002]:2408
| 162.159.192.3:2408 | [2606:4700:d0::a29f:c003]:2408
| 162.159.192.4:2408 | [2606:4700:d0::a29f:c004]:2408
| 162.159.192.5:2408 | [2606:4700:d0::a29f:c005]:2408
| 162.159.192.6:2408 | [2606:4700:d0::a29f:c006]:2408
| 162.159.192.7:2408 | [2606:4700:d0::a29f:c007]:2408
| 162.159.192.8:2408 | [2606:4700:d0::a29f:c008]:2408
| 162.159.192.9:2408 | [2606:4700:d0::a29f:c009]:2408

### Teams & WARP+
| 162.159.193.0 | [2606:4700:d0::a29f:c100] |
| :---: | :---: |
| 162.159.193.1:2408 | [2606:4700:d0::a29f:c101]:2408
| 162.159.193.2:2408 | [2606:4700:d0::a29f:c102]:2408
| 162.159.193.3:2408 | [2606:4700:d0::a29f:c103]:2408
| 162.159.193.4:2408 | [2606:4700:d0::a29f:c104]:2408
| 162.159.193.5:2408 | [2606:4700:d0::a29f:c105]:2408
| 162.159.193.6:2408 | [2606:4700:d0::a29f:c106]:2408
| 162.159.193.7:2408 | [2606:4700:d0::a29f:c107]:2408
| 162.159.193.8:2408 | [2606:4700:d0::a29f:c108]:2408
| 162.159.193.9:2408 | [2606:4700:d0::a29f:c109]:2408
