### ISSUE TITLE
docker: Error response from daemon

### ISSUE THREAD

**Issue by CosmosLibra** [fscarmen/warp#84]
docker: Error response from daemon: manifest for fscarmen/wgcf:AMD64 not found: manifest unknown: manifest unknown.
![image](https://user-images.githubusercontent.com/20694541/152760793-15a92862-50a3-4a5d-888d-aedc9089fe68.png)

**Comment by fscarmen** [comment]
fixed ,please try again

**Comment by CosmosLibra** [comment]
谢谢 安装成功了 选择的ipv4  但尝试了10次 依然显示失败
![image](https://user-images.githubusercontent.com/20694541/152763048-6211dd98-9ffb-48e3-a869-0ac603e23397.png)

**Comment by fscarmen** [comment]
你是要用docker 方案吗？有成熟的方案哦
docker 方案的话，你试试这样
```
docker exec -it wgcf sh # 进入容器
wg-quick down wgcf # 无论之前如何，先关了wgcf
wg-quick up wgcf # 打开wgcf
curl -s4m5 ip.gs # 看是否能获取 warp ipv4
exit # 退出容器
```

**Comment by CosmosLibra** [comment]
再次感谢  请问大佬 运行推出容器后 测试获取到了一个v4地址 请问退出容器后要运行守护程序吗

**Comment by fscarmen** [comment]
> 再次感谢  请问大佬 运行推出容器后 测试获取到了一个v4地址 请问退出容器后要运行守护程序吗 

可以的，在外面，回去截图给你。
你自己运行成功吗？

**Comment by fscarmen** [comment]
> 请问退出容器后要运行守护程序吗

不需要的，正常使用可以了

**Comment by CosmosLibra** [comment]
大佬 运行wg-quick up wgcf 提示缺少内核 正常吗
![image](https://user-images.githubusercontent.com/20694541/152899784-273c43ef-4c78-44cf-aa3e-d74674cc0268.png)

**Comment by fscarmen** [comment]
能获取到ip吗？

**Comment by CosmosLibra** [comment]
curl -s4m5 ip.gs 回显是空的  但不报错

**Comment by fscarmen** [comment]
嗯，加了 -s 就不会报错了，话说昨天你不是成功了吗？

**Comment by CosmosLibra** [comment]
昨天成功获取一个ip 然后登录网飞首页 提示not allowed,以为是没有开守护进程  再次运行curl -s4m5 ip.gs 就和上面说的一样了 然后我尝试在容器外运行
![image](https://user-images.githubusercontent.com/20694541/152902862-8177de80-af96-4397-8c48-4623541cafe0.png)

**Comment by fscarmen** [comment]
暂时不要用docker项目了，还是存在容器外运行不了的问题，这情况你进容器里多数可以。
你用 ```warp u```卸载了，安装回传统的版本吧 ``` wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && bash menu.sh [option] [lisence]```

**Comment by CosmosLibra** [comment]
好的 我试试 谢谢

**Comment by fscarmen** [comment]
请问现在可以了吗？
