### ISSUE TITLE
大佬帮忙看下-【结论：socks5 方案，修改完配置文件之后记得重启一下 xray/v2ray 服务才能生效，如 mack-a 八合一就需要 systemctl restart xray】

### ISSUE THREAD

**Issue by LYOyoo** [fscarmen/warp#86]
我按照分流那段操作，先安装client，然后刷ip，因为我原本安装了xray然后就把教程说的那个配置文件原本代码全部删了然后把你给的那段代码直接粘贴进去，最后安装完是显示这样的

系统信息：
	当前操作系统：Debian GNU/Linux 10 (buster)
	内核：4.19.0-18-amd64
	处理器架构：amd64
	虚拟化：kvm 
	IPv4：23.95.213.155  美国  AS-COLOCROSSING 
	IPv6：     
	WARP 网络接口未开启 
	WARP Socks5 Client 已开启	本地 Socks5:127.0.0.1:40000 WARP IPv4:8.10.148.7 美国 CLOUDFLARENET
我是哪一段出错了吗

**Comment by fscarmen** [comment]
没有错啊，你不是已经创建了 socks5 的代理了吗？之后你的 Netflix 就分流过去啊

**Comment by LYOyoo** [comment]
哦行了行了，感谢大佬们的脚本，原来是是没重启

**Comment by fscarmen** [comment]
是的，```systemctl restart xray```
刷解锁 IP 可以用另一个专业的项目:
https://github.com/fscarmen/warp_unlock
