### ISSUE TITLE
ip_info: command not found-【Conclusion: 2022.2.18 the bug has been  fixed. [warp v] to update.】

### ISSUE THREAD

**Issue by testermania** [fscarmen/warp#88]
warp 6
`/usr/bin/warp: line 513: ip_info: command not found`

**Comment by testermania** [comment]
yes there are 4 files

language
menu.sh
wgcf-account.toml
wgcf.conf
wgcf-profile.conf

**Comment by fscarmen** [comment]
``` cat  /etc/wireguard/wgcf.conf```

**Comment by testermania** [comment]
```
[Interface]
PrivateKey = 
Address = 172.16.0.2/32
Address = fd01:5ca1:ab1e:869c:a6f1:472c:13a8:3acd/128
DNS = 2606:4700:4700::1111,2001:4860:4860::8888,2001:4860:4860::8844,1.1.1.1,8.8.8.8,8.8.4.4
MTU = 1400
PostUp = ip -6 rule add from (server ipv6 ip) lookup main
PostDown = ip -6 rule delete from (server ipv6 ip) lookup main
[Peer]
PublicKey = 
AllowedIPs = 0.0.0.0/0
#AllowedIPs = ::/0
Endpoint = [2606:4700:d0::a29f:c001]:2408
```

**Comment by fscarmen** [comment]
The same environment with you  and no problem. 

![image](https://user-images.githubusercontent.com/62703343/153754899-fb5c8795-af1a-4708-a1fd-c957afb274bd.png)

**Comment by testermania** [comment]
If it's not important thing, we can turn it off.

![image](https://user-images.githubusercontent.com/61498468/153757148-c2955ad9-addd-4e48-909d-cb75b995093c.png)

**Comment by fscarmen** [comment]
It 's a big bug . But i have no idea why the variable "$NF" is not assigned.

**Comment by testermania** [comment]
thank you i don't use tg. I'll try a clean install and let you know tomorrow.

**Comment by fscarmen** [comment]
ok

**Comment by fscarmen** [comment]
> thank you i don't use tg. I'll try a clean install and let you know tomorrow.

The bug has beed fixed. Plz use ```warp v``` to update.

**Comment by fscarmen** [comment]
Has the fault been eliminated?
