### ISSUE TITLE
用机子自己的dns (adguard home)-【结论：我也不会，请用户自行研究，可能的话分享一下经验】

### ISSUE THREAD

**Issue by wft44maqb** [fscarmen/warp#90]
想要用机子自己的dns (adguard home)要怎样搞?

**Comment by wft44maqb** [comment]
`/etc/docker/daemon.json`:
```
{
  "dns" : [
    "127.0.0.1",
    "(机子ip)"
  ]
}
```

**Comment by wft44maqb** [comment]
@fscarmen 方便留telegram么?

**Comment by wft44maqb** [comment]
机子连不上了 hhhhhh

**Comment by fscarmen** [comment]
adguard home 我不会啊
@fscarmen2

**Comment by wft44maqb** [comment]
https://github.com/Jigsaw-Code/outline-server

https://github.com/Jigsaw-Code/

@fscarmen2 @fscarmen

**Comment by fscarmen** [comment]
你可加tg交流:
https://t.me/fscarmen2
