### ISSUE TITLE
大佬能否找个时间适配下ubuntu 16系统的适配？-【结论：2022.2.20，作了调整 ，支持 Ubuntu 16.04 LTS 】 

### ISSUE THREAD

**Issue by bbggkk** [fscarmen/warp#93]
有个机买了蛮久了 性能流量都够用 但是官方没有18或者20版本的升级  谢谢大佬了！

**Comment by fscarmen** [comment]
要试试支不支持才行

**Comment by fscarmen** [comment]
你是用户，你才是大佬。你可以试改下下面的再安装看看

![Uploading 88B3A1AF-3B87-4F99-BD0D-E3CFC24E884A.jpeg…]()

**Comment by bbggkk** [comment]
> 你是用户，你才是大佬。你可以试改下下面的再安装看看
> 
> ![68A5CDBC-FB23-4626-B8A8-45BDF1941EC0](https://user-images.githubusercontent.com/62703343/154799087-d1b67dd0-6b6a-48dd-8a22-cebbefc85cd2.jpeg)

这个是哪一级目录？具体文件名？谢谢大佬！！

**Comment by fscarmen** [comment]
menu.sh
这个文件

**Comment by bbggkk** [comment]
谢谢大佬 看到了！！！

**Comment by fscarmen** [comment]
> 谢谢大佬 看到了！！！

我今晚用甲骨文 DD 个 16.04 再试试

**Comment by bbggkk** [comment]
> > 谢谢大佬 看到了！！！
> 
> 我今晚用甲骨文 DD 个 16.04，也是成功的，没有遇到任何挑战。
> 
> <img alt="" width="70%" src="https://user-images.githubusercontent.com/62703343/154974761-f2890c76-6265-4181-8cdb-c6e774c6fd77.png">

确实能用了 再次感谢大佬i！！！！

**Comment by fscarmen** [comment]
> 确实能用了 再次感谢大佬i！！！！

谢谢你的支持，用户才是大佬👍🏻👍🏻
