### ISSUE TITLE
今天安装warp，一直无法获取warp IP

### ISSUE THREAD

**Issue by luuanng** [fscarmen/warp#95]
一直是这样的log。 

创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by luuanng** [comment]
抱歉打扰了，看到别的里面写了需要升级了内核的建议，就先升级了BBR，现在好了。

**Comment by fscarmen** [comment]
是bbrplus吗？是需要升级，本脚本自带那个可以处理

#54 #58 #72

**Comment by luuanng** [comment]
centos 7，刚开始直接安装warp失败，所以就先安装了bbr内核，之后再安装warp就成功了。

> 是bbrplus吗？是需要升级，本脚本自带那个可以处理
> 
> #54 #58 #72

**Comment by fscarmen** [comment]
> centos 7，刚开始直接安装warp失败，所以就先安装了bbr内核，之后再安装warp就成功了。
> 

C7 兼容性是差少少。谢谢你的支持！

**Comment by luuanng** [comment]
> > centos 7，刚开始直接安装warp失败，所以就先安装了bbr内核，之后再安装warp就成功了。
> 
> C7 兼容性是差少少。谢谢你的支持！

感谢大佬support~脚本非常好用，可惜现在亚太区不能解锁了。
