### ISSUE TITLE
创建 Socks5 代理失败-【结论： 2022年3月10日，虽然官方 Client Proxy 不支持 CentOS 7 和 Ubuntu 18.04，其他“作者”已经放弃并做限制。但我死心不息，终于用若干“技术”处理好，均可以支持了，其中 Ubuntu 18.04已经集成，CentOS 7 稍后。估计又要被抄作业了：）】

### ISSUE THREAD

**Issue by redtime1213** [fscarmen/warp#96]
Retrieving http://pkg.cloudflareclient.com/cloudflare-release-el7.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping http://pkg.cloudflareclient.com/cloudflare-release-el7.rpm - transfer failed
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.siena.edu
 * elrepo: mirror.rackspace.com
 * epel: mirror.lshiy.com
 * extras: mirrors.xtom.com
 * updates: repo1.sea.innoscale.net
No packages marked for update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.siena.edu
 * elrepo: dfw.mirror.rackspace.com
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirrors.xtom.com
 * updates: repo1.sea.innoscale.net
No package cloudflare-warp available.
Error: Nothing to do
 进度 2/2： 设置代理模式 
 创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
是CentOS 7系统吗？不支持呢

https://pkg.cloudflareclient.com/packages/cloudflare-warp

![093EBC56-F39C-4A94-AA5E-C7C388BA9F20](https://user-images.githubusercontent.com/62703343/155259571-ef93cdd3-574d-4cfc-826a-e29bfd257d59.jpeg)

**Comment by fscarmen** [comment]
换系统解决了？
