### ISSUE TITLE
一直解锁失败-【结论：2022年2月17日中午时分，Netfilx 大面积封杀亚太区 WARP IP，暂时欧美区不受影响，各用户都在静待最新事态发展。】

### ISSUE THREAD

**Issue by hualiuqiang** [fscarmen/warp#97]
![image](https://user-images.githubusercontent.com/53924610/155265250-ea9a6abf-dd39-4c82-87fb-d79e8cbdbefd.png)
一直解锁失败

**Comment by hualiuqiang** [comment]
谷歌云 香港 新加坡 台湾 都是这样

**Comment by fscarmen** [comment]
#91
