### ISSUE TITLE
warp获取ip失败

### ISSUE THREAD

**Issue by luuanng** [fscarmen/warp#99]
后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
/usr/bin/warp: line 645: ss: command not found
 第2次尝试 
/usr/bin/warp: line 651: ss: command not found
 第3次尝试 
/usr/bin/warp: line 651: ss: command not found
 第4次尝试 
/usr/bin/warp: line 651: ss: command not found
 第5次尝试 
/usr/bin/warp: line 651: ss: command not found
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues]

**Comment by fscarmen** [comment]
请问是什么系统？居然没有 ss 命令。第一次遇到
你百度一下 ss 命令如何安装呢？

**Comment by luuanng** [comment]
> 请问是什么系统？居然没有 ss 命令。第一次遇到 你百度一下 ss 命令如何安装呢？

好奇怪，我之前是好的，卸载再安装就没有ss命令了，难道是我执行了下面的脚本导致的么？
--------------------------------
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) 
 --------------------------------
我刚开始是装好warp的，然后又进warp执行了上面的12，发现没什么变化，就卸载掉warp重新用脚本装了warp，
就出现了上面的「ss: command not found」的错误。

**Comment by luuanng** [comment]
现在已经用「yum install iproute」装回ss重新安装成功了。

**Comment by luuanng** [comment]
现在已经用「yum install iproute」装回ss重新安装成功了。

**Comment by fscarmen** [comment]
![image](https://user-images.githubusercontent.com/62703343/155283331-5efda782-1216-40a2-99fc-30bbd7735a14.png)

**Comment by fscarmen** [comment]
我为了试这个ss是哪个依赖的，卸载  iproute2 导致两台vps失联了，只能重置系统了。

**Comment by luuanng** [comment]
> 我为了试这个ss是哪个依赖的，卸载 iproute2 导致两台vps失联了，只能重置系统了。

狗妹纳塞😂

**Comment by luuanng** [comment]
> 我为了试这个ss是哪个依赖的，卸载 iproute2 导致两台vps失联了，只能重置系统了。

之前卸载都是没问题的，不知道为什么这次就出了问题。最近对vps没有做别的操作，我的系统里面只有nginx，trojan和warp来着😂
